### ISSUE TITLE
Support shared secrets for initial minion auth

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#10070]
I keep seeing people with issues with aws autoscaling and keys. it would be nice if you could send a one-time-password in to a minion that's known by the master. It could go into user-data and would be sent along with the initial auth, then you'd know the minion was legit, but you wouldn't need to store anything permanently useable in the user-data.

**Comment by JensRantil** [comment]
> Any way around this? Would the suggestion in this thread solve the problem?

@foxx I am looking into autoscaling with Salt, too. My current take is this:
 * create an AMI role that has access to a preseeded key in S3. Give that role to all autoscaled EC2 instances.
 * write a custom script that executes at boot of my AMI (using supplied "User Data" payload). It does the following:
  * Runs [`salt-bootstrap`](https://github.com/saltstack/salt-bootstrap) installing [preseeded key](https://github.com/saltstack/salt-bootstrap/issues/772).
  * Using a reactor to 1) check the minion key fingerprint and minion id and then 2) accepting the key. Checking fingerprint here is crucial to me since I would not feel comfortable to simply accepting based on minion-supplied minion id (since a fraudulent minion could use this).

Thoughts? Did you solve this some other way?

**Comment by hemebond** [comment]
My first time using all this auto-scaling stuff but [this is what I currently have](https://gist.github.com/hemebond/4b48df43721adb283e0df404501a4b59).

**Comment by JensRantil** [comment]
I am running auto scaling in production using this setup: https://github.com/JensRantil/saltstack-autoscaling Works like a charm and is much more secure than that proposed solution of using a shared secret. I propose we close this issue and make my solution a best practise.

**Comment by rossengeorgiev** [comment]
In salt 2018, minions can be accepted based on grains.

https://docs.saltstack.com/en/latest/ref/configuration/master.html#autosign-grains-dir
