### ISSUE TITLE
Git state doesn't fetch tags before trying to checkout to it

### ISSUE THREAD

**Issue by Lothiraldan** [saltstack/salt#10141]
In git.latest state, salt try to run git fetch (https://github.com/saltstack/salt/blob/develop/salt/states/git.py#L222) before trying to checkout to rev (https://github.com/saltstack/salt/blob/develop/salt/states/git.py#L227).

The problem is when we use tags which are not retrieved via git fetch (a multi head on master branch). Salt should run git fetch with "--tags" option in order to retrieve them.

The usecase is not common and we maybe need to work on our release workflow but it's an easy fix, so if it's a good idea, I will add a pull-request.

**Comment by ezheidtmann** [comment]
I got bit by this today. Hopefully working on a PR later today.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/26341 by specifying multiple refspecs when ``fetch_tags is True``.

**Comment by acornejo** [comment]
Does anybody have a workaround until the work from @terminalImage arrives?

Our build script depends on tags to determine versions. I tried adding a git fetch --tags as parte of the build step, but this doesn't fetch ANY tags.

Presumably this is because when salt did the clone it setup the remote to track only one branch and none of the tags.

Looking for an alternative ti work around this on the build script before the change lands on salt, ideas?
