### ISSUE TITLE
Jobs cache: keep_jobs not deleting old files

### ISSUE THREAD

**Issue by LucsT** [saltstack/salt#10443]
Hello, 

Problem : 
     Jobs call with cmd_async let millions of files in directory /var/cache/salt/master/jobs/
     Files seems to be never deleted. Even if I set a strict settings 'keep_jobs: 1'
     Problem is more about number of files(inodes) than disk space for me.

I have a syndic with about 200 minions.  
I see the number of files growth with X*Y  where X:number of minions  in this syndic Y: jobs launched

Versions (minion, syndic, master) are: 
           Salt: 0.17.5
         Python: 2.6.6 (r266:84292, Dec 26 2010, 22:31:48)
         Jinja2: 2.5.5
       M2Crypto: 0.20.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.1.0
         PyYAML: 3.09
          PyZMQ: 13.1.0
            ZMQ: 3.2.3

Not very familar with erlang, only solution I found to avoid problem is to manually erase file jobs.
Tell me if anything else is welcome.

Lucas

**Comment by rallytime** [comment]
@DaveQB - Just a bump here. Several releases have come out on the 2014.7 branch since this was last discussed. Are you still seeing this issue? Did you get a change to test?

**Comment by DaveQB** [comment]
@rallytime Sorry to stretch this out. We haven't upgraded since this issue arose and relying on cronjobs as a work around. The ticket to start the upgrade process has floated to near the top of my list, so it shouldn't be long now.

Thanks

**Comment by rallytime** [comment]
No problem! Thanks for the update. Keep us posted. :)

**Comment by DaveQB** [comment]
We tried the upgrade to 2014.7.1 and that ended in a disaster as you are aware of from other issues we have conversed on @rallytime . We have successfully rolled back to 2014.1.3. I hope 2015 works for us, so we can upgrade and I can re-test for this issue.

So this ticket will stay open a little while longer I am afraid.

**Comment by rallytime** [comment]
@DaveQB No problem. Apologies that the upgrade has caused so much strife. Hopefully the multi-master issues we have discussed on other tickets are resolved and the upgrade goes more smoothly.

**Comment by trevor-h** [comment]
I seem to have encountered this issue on a testing salt-master. We have several 2014.7.x salt-masters in production with keep_jobs: 48 and 100% of jobs being async and have never seen this issue.

With a 2015.5.1 salt-master we have just seen this issue for the first time. Same scenario with keep_jobs at 48 and 100% async jobs.  Inode output from df:

Filesystem      Inodes   IUsed IFree IUse% Mounted on
/dev/vda1      1966080 1966080     0  100% /

Seems the salt-master is using > 75% of the available inodes and I've had to resort to manually cleaning out the job cache. Could be a fluke or something fixed in a later 2015.5 but I figure it's worth noting as relevant to this issue.

Versions report below:

**Comment by basepi** [comment]
@trevor-h When you're manually cleaning out the job cache, are there in fact jobs with a jid older than 48 hours?

**Comment by frogunder** [comment]
@DaveQB, @trevor-h - Is this still an issue for you?

**Comment by cachedout** [comment]
Closed for lack of response.
