### ISSUE TITLE
Create documentation that talks about using Jinja specifically for Salt.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#10480]
We've got a lot of great Jinja examples through the documentation, as well as on gists. A centralized place with a bunch of examples showing how to use Jinja with Salt, the fact you can use Python with it, etc. would be great.

**Comment by jacobhammons** [comment]
I think most of this content was gathered and placed in the Jinja renderer doc, I've moved it to a more prominent doc titled Understanding Jinja under the Using Salt heading, https://docs.saltstack.com/en/latest/topics/jinja/index.html#including-context-during-include-import

I've also added a section on writing custom modules to deal with Jinja complexities.

@gravyboat If you think this issue is resolved please close, thanks!

**Comment by gravyboat** [comment]
This looks really good. I think there could definitely be more related to common Salt implementations (such as imports from defaults.yaml, map files, the pillar, etc.), as well as more 'advanced' topics like defaults, advanced loops, and so forth. A lot of this could probably be stolen from the existing formulas, but this is the sort of content most people end up asking about. Showing people how to reference and loop through pillars is especially common.
