### ISSUE TITLE
`state.top` does not take/obey `saltenv` argument

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#10660]
We need to make `state.top` take a `saltenv` argument which will limit the search to only that environment.  This allows `state.top` to be used to trigger a versioned highstate from a given branch in gitfs, for example, without having to have a different name for the topfile in each branch.

**Comment by somenick** [comment]
Based on the source state.highstate does accept (and has for a while: #4474) a saltenv kwarg that's undocumented, and seems to point to a very simple similar solution for state.top as well as a possible workaround: set 'environment' in the minion config.

Another workaround might be the obscure - but documented - 'localconfig' param.

It is a bit confusing because http://docs.saltstack.com/en/latest/ref/configuration/minion.html#environment explicitly mentions the top file for something it can't be used for: defining the environments is indeed best done in top files, but picking the environment can only be (officially) done in the minion config since saltenv doesn't work/is undocumented for the two methods that actually use them.

maybe this should be reclassified as a low hanging fruit bug...

**Comment by alex-solidfire** [comment]
Thanks @somenick .  We will give this a shot.
