### ISSUE TITLE
Create a 'comprehensive index' which contains all items.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#10876]
With the changes to the document structure @dlanderson mentioned that it's no longer possible to search the table of contents for everything (primarily items that were 3 layers deep or more). Previously all the state modules, and execution modules would be in there. Maybe if we created another page that just has everything on it, that would satisfy this? It would be especially useful for people who might not be downloading the docs and doing searches. @cachedout any opinion or ideas?

**Comment by jacobhammons** [comment]
With the navigation changes we've made to the site over the past year and the effectiveness of Google search, I think that the original intent of this issue is solved and that this can be closed.

Regarding the index, I think it is useful in its current form for PDF output, but I don't think it needs additional time invested. @gravyboat if you agree please close, thanks!
