### ISSUE TITLE
pkg.install and pkg.available_version on windows minion to SL master do not seem to behave according to docs.

### ISSUE THREAD

**Issue by Gehn** [saltstack/salt#10948]
This problem seemed very similar to behavior specified on #4630 and the linked #6894, and while the latter was resolved via a typo, I did not see anything that would be relevant in this situation?  (Could be totally blind, thanks in advance for any help you can give.)  Please let me know if there is any other information I can provide to facilitate this.

Master: (sl 6.2)
root@slprototype:/srv/salt/repositories/win>salt --versions-report
           Salt: 0.17.5

Minion: (win server 2k8)
C:\salt>salt --versions-report
           Salt: 0.17.5-52-g2d4772c

Following the tutorial specified at:
http://docs.saltstack.com/ref/windows-package-manager.html

/etc/salt/master has all instances of
/srv/salt/win/repo changed to /srv/salt/repositories/win

in /srv/salt/repositories/win/firefox/init.sls:
```
firefox:
  27.0.1:
    installer: 'salt://repositories/win/firefox/Firefox Setup Stub 27.0.1.exe'
    full_name: Mozilla Firefox 27.0.1 (x86 en-US)
    locale: en_US
    reboot: False
    install_flags: ' -ms'
    uninstaller: '%ProgramFiles(x86)%/Mozilla Firefox/uninstall/helper.exe'
    uninstall_flags: ' /S'
```
(stolen from tutorial, modified for most up to date version, the installer is local in that directory.)
```
root@slprototype:/srv/salt/repositories/win>salt-run winrepo.genrepo
{'name_map': {'Mozilla Firefox 27.0.1 (x86 en-US)': 'firefox',
              'Python 2.7.6 (64-bit)': 'python',
              'Salt Minion 0.17.5-2': 'salt-minion'},
 'repo': {'firefox': {'27.0.1': {'full_name': 'Mozilla Firefox 27.0.1 (x86 en-US)',
                                 'install_flags': ' -ms',
                                 'installer': 'salt://repositories/win/firefox/Firefox Setup Stub 27.0.1.exe',
                                 'locale': 'en_US',
                                 'reboot': False,
                                 'uninstall_flags': ' /S',
                                 'uninstaller': '%ProgramFiles(x86)%/Mozilla Firefox/uninstall/helper.exe'}},
          'python': {'2.7.6': {'full_name': 'Python 2.7.6 (64-bit)',
                               'install_flags': '/qn /norestart',
                               'installer': 'http://www.python.org/ftp/python/2.7.6/python-2.7.6.amd64.msi',
                               'locale': 'en_US',
                               'msiexec': True,
                               'reboot': False,
                               'uninstall_flags': '/qn',
                               'uninstaller': 'http://www.python.org/ftp/python/2.7.6/python-2.7.6.amd64.msi'}},
          'salt-minion': {'0.17.5-2': {'full_name': 'Salt Minion 0.17.5-2',
                                       'install_flags': ' /S /master=172.23.254.31 /minion-name=%COMPUTERNAME%',
                                       'installer': 'salt://repositories/win/salt-minion/Salt-Minion-0.17.5-2-AMD64-Setup.exe',
                                       'locale': 'en_US',
                                       'reboot': False,
                                       'uninstall_flags': '',
                                       'uninstaller': ''}}}}
```
(Yes, I had prepared some other packages.  If there's any thought that they are interfering, I can nuke em, but I figured at this point it was very unlikely they were.)

Specified the refresh.
```
root@slprototype:/srv/salt/repositories/win>salt zinc14 pkg.refresh_db
zinc14:
    True
```

Things start getting interesting when I run available_version.  As you see, no results.
```
root@slprototype:/srv/salt/repositories/win>salt -v -t 100 zinc14 pkg.available_version firefox
Executing job with jid 20140304165418973273
-------------------------------------------

zinc14:

```

Tried to do an install anyway:

```
root@slprototype:/srv/salt/repositories/win>salt -v -t 100 zinc14 pkg.install firefox
Executing job with jid 20140304165530375286
-------------------------------------------

zinc14:
    ----------
```

No error, as well... I tried to run it by proxy of a state, to get more useful information, and lo and behold:
```
root@slprototype:/srv/salt/repositories/win>salt zinc14 state.sls firefox
zinc14:
----------
    State: - pkg
    Name:      firefox
    Function:  installed
        Result:    False
        Comment:   Package firefox not found in the repository.
        Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total:     1
```

(the firefox sls is entirely a pkg.install: firefox)

**Comment by ek-dyoder** [comment]
Hey everybody - I'm completely new to salt and git, so forgive my ignorance. I've been banging my head against my laptop for the last several hours trying to figure out why my Windows minions aren't installing packages defined my my states. Then I found this thread.

The results of my trying to apply the highstate and directly installing the packages onto the minion is almost exactly what the op experienced. The only problem is that the op posted that over a year ago. Am I missing something or is this still a problem pending resolution?

On a sidenote - I'd love to get more involved in salt (disclaimer: I suck at IRC). Where is the best place to go to 'join the community'?

Thanks,
-David

**Comment by basepi** [comment]
I think this is still an issue, we need to get it fixed.

As far as getting involved, unfortunately IRC is one of the main ways (#salt on freenode), but we also have a community mailing list: https://groups.google.com/forum/#!forum/salt-users

**Comment by ek-dyoder** [comment]
Is there any workaround? Or some way of having msiexec install software via cmd.run?

**Comment by mm-nsawlidi** [comment]
I am having the same issue as described. I'd like to migrate my infrastructure over to Salt, but the core servers are Windows Server 2008 R2 or Windows Server 2012 R2.

I can post more detail if needed.

**Comment by ek-dyoder** [comment]
Ok, so I have a little more information I'd like to contribute here. I know that software installation doesn't work on Windows clients, but when it does work, I foresee problems.

Windows doesn't have a package manager (yet), so it doesn't work the same way as apt-get, yum, etc. On Windows machines, especially when installing an MSI, the installer software accepts arguments that **modify the installation** and/or set configuration options that would otherwise need to be set manually or through the gui.

Here's why this is a problem...

Certain applications I install have arguments passed to the installer that *may change* depending on:
       - where the computer is physically located
       - which client of mine the computer belongs to
       - or whether the installation should be performed silently or not.

So for example, I have an application that needs to be installed on all computers at one of my clients that tracks print jobs and assigns them to job numbers in our accounting database. The application needs to know which one of two servers it should report to. The application's server is specified as a command line argument during install time. Assuming installing software on Windows works within salt, this still wouldn't work because I'd have to create 2 packages (one for each computer whose application is reporting to different servers), but in doing that I would break installations for when computers move between office (and need to report to a different server). Furthermore, the application installs a Windows service which contacts that application's server to check for updates and, if available, installs them silently. This would further break salt's package management on Windows because on Windows there is no function to hold a package at a specified installed version (unless salt can do locally what GP and SCCM do).

Another example is a VPN client I use that is hosted at it's latest version on an internet host. Installation on client computers is beautifully simple:
```
msiexec -i http://example.com/path/to/latest/installer.msi DEPLOYID=xxx-xxxx-xxx
```
This installs the latest version of the VPN client, starts the service, provisions an account, and connects the computer to a specified network. **DEPLOYID** is a GUID which configures the VPN client on any network I've preconfigured on the service. It's really nice. But this wouldn't work either in salt because the **DEPLOYID** will change depending on which client I install the software for; I suppose the workaround here is to setup a separate salt-master for each client. But I would still have the same problem with package management, because the installed MSI is the latest version at install time, but the client (once installed) updates itself regularly. So if salt is trying to maintain an installed version, it will keep installing over and over again once the first update is published on the hosted service.

I'm not sure if what I'm saying makes any sense at all, I can try to clarify further if need be. I just really like salt and want to use it at all my clients, but the package management on Windows absolutely must be fixed first.

-David

**Comment by carolynvs** [comment]
I ended up ditching the pkg module and writing my own called choco. It uses chocolatey ("apt-get for windows") and better handles being stateful.

We sometimes use the public chocolatey packages on chocolatey.org and otherwise all internal apps, special builds, custom install scripts, etc all go into custom packages on our internal chocolatey feed. Works pretty well so far.

**Comment by lorengordon** [comment]
I actually have had quite a bit of success installing software on Windows with salt's windows package manager, so it's probably a *little* too broad to say software installation doesn't work with Windows clients at all.

As for controlling parameters that may vary per minion, they've been working on adding rendering support to salt's windows package manager, so you could write the sls for the package such that it uses jinja (or whatever renderer you like) to get the parameter value from pillar (or a grain, or a default lookup dictionary, or whatever).

**Comment by lorengordon** [comment]
The templating support only appears to be in the develop branch at the moment, via https://github.com/saltstack/salt/pull/22675.

**Comment by lorengordon** [comment]
You'll also see in the documentation for the [pkg.installed state](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed) that as of version 2014.7.0, it supports an `allow_updates` parameter that would appear intended to address the other issue described here.  From the doc:

**allow_updates**

>    Allow the package to be updated outside Salt's control (e.g. auto updates on Windows). This means a package on the Minion can have a newer version than the latest available in the repository without enforcing a re-installation of the package.

>    *New in version 2014.7.0.*

**Comment by ek-dyoder** [comment]
@lorengordon Thanks for the allow_updates bit - that seems pretty useful and I totally missed that my first time through the documentation. However, how did you get applications to install on Windows minions using salt's pkg.install? I can't get it to work, and if I'm not mistaken, that's much of what this issue is about...

@carolynvs - I'm going to have to look more into chocolatey. Once I ran sys.doc after I brought up my first Windows minion I remember seeing a bunch of chocolatey commands. I guess I never looked further into it because it seemed like I would hit the same walls with package versions and unique installation parameters (but it looks like @lorengordon corrected me on that). I'll check it out again. Thanks!

**Comment by lorengordon** [comment]
Ahh, well, my own work has been on masterless environments, so some of my experience may not translate perfectly. But here's my general setup...

My directory hierarchy:

```
C:\> tree C:\salt\srv
C:\SALT\SRV
├───formulas
│   └───emet-formula
├───states
│   └───base
└───winrepo
    └───emet_pkg
```

That directory structure drives my `file_roots` configuration:

```
file_roots:
  base:
    - C:\salt\srv\states\base
    - C:\salt\srv\winrepo
    - C:\salt\srv\formulas\emet-formula
```

In the emet_pkg directory is an `init.sls` straight from [salt-winrepo](https://github.com/saltstack/salt-winrepo/blob/master/emet.sls):

```
Emet:
  5.1:
    installer: 'http://download.microsoft.com/download/A/A/8/AA853FAE-7608-462E-B166-45B0F065BA13/EMET%205.1%20Setup.msi'
    full_name: 'EMET 5.1'
    reboot: False
    install_flags: ' ALLUSERS=1 /quiet /qn /norestart'
    msiexec: True
    uninstaller: 'http://download.microsoft.com/download/A/A/8/AA853FAE-7608-462E-B166-45B0F065BA13/EMET%205.1%20Setup.msi'
    uninstall_flags: ' /qn'
```

The [emet formula](https://github.com/lorengordon/emet-formula) is one I wrote to handle a .NET dependency check and install the LGPO policy files, but a simple `emet.sls` works if placed in the `base` directory (and the .NET dependency is otherwise met):

```
install_emet:
  pkg.installed:
    - name: 'Emet'
    - version: '5.1'
    - allow_updates: True
```

And, finally, top.sls would look something like:
```
base:
  '*':
    - emet
```

**Comment by dragon788** [comment]
Has anybody in this thread been using the documented salt-run winrepo.genrepo command to actually generate their repo after populating it with the installers and properly formatted sls files for each package? There are some excellent examples here and I've been using them for various packages on 2014.7.x.

http://docs.saltstack.com/en/2014.7/topics/windows/windows-package-manager.html

https://github.com/saltstack/salt-winrepo

**Comment by lorengordon** [comment]
Yes, @dragon788, I have. I forgot to add that step in the description of my setup above, but it is necessary to use winrepo.genrepo to update the winrepo database and `salt '*' pkg.refresh_db` to distribute the database to the minions after making any changes to the winrepo sls files (or the winrepo directory structure, or the winrepo configuration options) on the master.

**Comment by dragon788** [comment]
Thanks for the update Loren, I spent a few hours today playing with various versions of 2014.7 and I can further confirm there is some broke broke stuff in the Windows package management, but a lot of it depends on which version of Salt you have on the master and minions. 

This originally was opened for 0.17.1, there have been some major leaps since then, but one thing that jumped out at me was the examples always show pkg.available_version as returning a dictionary, but I only ever got a SINGLE return even when I watched the debug output on my master when the repo was built showing 6-7 versions (ironically of the salt minion package). I was running these commands between the master and minion (via salt-call) and got pretty similar results. 

I also noticed that %COMPUTERNAME% as shown in the example above actually failed for me on certain versions of the 2014.7.x salt minion, in particular I think .2 didn't parse it properly though .1 had.

**Comment by curiousmep** [comment]
I believe the main issue here still wasn't resolved. Running the command
# salt '*' pkg.available_version Firefox

Still shows only one version of firefox.

**Comment by twangboy** [comment]
I think some of the confusion here might be coming from the documentation. Looking at the code ```pkg.available_version``` has been deprecated. The code calls ```pkg.latest_version``` instead. So, only the latest version will display. The documentation however shows all versions being displayed.
http://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#install-windows-software
I'll have our documentation guy @jacobhammons take a look at this.

**Comment by dragon788** [comment]
It looks like to list the available versions on Windows it is now 'pkg.list_available' if you want to see all the available versions of a package. I've tried this and it showed me the two versions of Salt-Minion that we have in our Winrepo.
