### ISSUE TITLE
Create CSV outputter

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#11098]
Please create a CSV outputter

**Comment by arno01** [comment]
Let's keep this open.

**Comment by dkfsalt** [comment]
Just to throw my 2 pence in, this will only work with flat data.

I think what we need here is a list of requirements and target behaviors.  For instance:
1) Outputter operates only at the top-level of the data, which must be a object, list object or elemental datatype
 1a) If top level object is an object/dict, the CSV output will be a single row, with each property/key being a column
 1b) If top level object is a list, the outputter will aggregate the properties/keys from all objects in the output (first pass?)
 1c) If top level object is an elemental datatype, the outputter will return a two records, a header with "string" and the returned value 
2. Must print the key names (header row)
3. Must flatten properties that are lists and use a pipe character (to be discussed) as a separator
4. Properties that are sub-objects will not be outputted (no minification of json because minified json has commas and lots of quotes in them that a CSV parser may not like)

Any other suggestions?
