### ISSUE TITLE
Command minion to change masters

### ISSUE THREAD

**Issue by dfboyd** [saltstack/salt#11107]
Salt should include a supported mechanism to command a minion to change to a different master.

At the moment, people are managing the /etc/salt/minion contents as a textfile, configuring the master name in there, and have a variety of different methods for getting the minion to restart itself when that file changes.  Since you can't reliably command the minion to restart itself with "watch /etc/salt/minion" people do things like submit an 'at' job to run "service salt-minion restart", or run the minion under something like daemontools.

It would be better if minion control were managed directly by Salt without recourse to operating-system- or distro-specific tools.  You should be able to command the minion to change masters; it should attempt to join the new master and fallback to its previous master if the join attempt doesn't succeed within a timeout.  You should never lose contact with a minion through any normal operation, because if you do then you have to individually go fix that machine -- and avoiding doing so is the entire motivation behind Salt.

**Comment by lrhazi** [comment]
Has this been implemented in latest git version?

**Comment by basepi** [comment]
This has not yet been implemented.

**Comment by lrhazi** [comment]
Not sure if this is the same thing or not but, it would be nice, unless already possible, to allow a minion to run states against a new master, temporarily. It could be used to have a salt-master test server, where all changes are pushed to first... then on a minion:

salt-call sls.state some_state_we_want_to_test  master=salt-master-test

**Comment by DanyC97** [comment]
+1  great idea !!

**Comment by jettero** [comment]
I managed to get this to work with ordinary statelists... but it's unsatisfactory because the minion has to then be accepted by the new master. I haven't worked out that bit yet. The minion also has to be removed from the old master. I solved that last bit with an event a reactor …

If it was built in, I could remove all these little things and never have to solve that middle problem.

I wish there was more master-master -> {syndics} -> minions key management help.
