### ISSUE TITLE
allow include in /etc/salt/roster

### ISSUE THREAD

**Issue by pille** [saltstack/salt#11233]
please implement either this, or #9139
both will fit my needs.

**Comment by eht16** [comment]
:+1:

**Comment by eht16** [comment]
One more comment on this describing the (still existing) need for this feature:
in our case we have multiple team members working together and some of them have some local environments which are referenced in our global roster file and sometimes this conflicts with items of others and so on.
Having the possibility to include a custom, local-only roster file in the global roster file or, as suggested in #9139, as roster.d directory, would be reall awesome and probably not that hard to implement.

Thanks.

**Comment by kiemlicz** [comment]
The need for this feature didn't vanish in the ether
Please re-open

**Comment by snlnspc** [comment]
I was surprised to learn that roster.d/ isn't supported already. this would be very useful.

**Comment by kiemlicz** [comment]
gladly reopen the issue.

**Comment by dmurphy18** [comment]
@pille Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt (currently 3006.3) and if still an issue, please open a new issue, which will have metrics in tracking issues.

This looks more like a feature request, if still interested, can you open a feature request using the new template, this allows for matrices from the template to track issues and allows for more information as to what problems are encountered or requested.

Also can I suggest you take a look at Heist which is the new way to do agent-less with Salt, see https://github.com/saltstack/salt-ext-heist and https://heist.readthedocs.io/en/latest/
