### ISSUE TITLE
State progress events still too slow

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#11242]
Ref #10798 

State progress events are still substantially slowing down large state runs.  We turned them to "off" by default, but we need to find ways to further optimize if we want to be able to have them "on" by default for Halite.

**Comment by Oloremo** [comment]
@Ch3LL Could you please tell if this issue still valid or was it fixed in one way or another? it's very strange that such important issues closed as stale...

**Comment by Ch3LL** [comment]
I do see a slight slowdown during my test. i'll go ahead and re-open

**Comment by dmurphy18** [comment]
@basepi Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 if still interested and if still an issue, please open a new issue, which will have metrics in tracking issues.

Going through trying to clear out old issues, and this is from 2014, and Salt has changed too much since then to keep it open.
