### ISSUE TITLE
Allow gitfs config to specify an ssh key

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#11548]
Currently it's necessary to add a key to ~/.ssh/id_rsa, but for many systems this key is used for other things as well. It would be ideal to be able to specify an ssh key to use.

**Comment by terminalmage** [comment]
Revisiting this issue, we now support key auth (including passphrase) when using pygit2 to provide gitfs.

Additionally, passphraseless auth can be supported in GitPython, and an alternate key can be specified using ``~/.ssh/config`` for the user under which the salt-master is running:

```
Host foo.com
    IdentityFile /home/foo/.ssh/id_rsa_bar
```

GitPython does not at this time support passing credentials, so this is as good as it gets right now if GitPython is being used.

Since multiple options exist to fulfill this request, I will close this.
