### ISSUE TITLE
salt.cloud is out of date for new google compute engine dashboard and API

### ISSUE THREAD

**Issue by jcockhren** [saltstack/salt#11669]
With the release of API v1, the current instructions for using GCE with salt cloud no longer apply. ~~Namely, in the new google cloud console, there is nolonger an option to create server certificates.~~ But rather one creates an API key to interact with the API (relative to a project).
[The current docs](http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.gce.html#module-salt.cloud.clouds.gce) say there's a "Register App" button. Within the new developer console, this is no longer the case.

**Comment by rallytime** [comment]
I am making my rounds through some old issues with salt-cloud. @jcockhren and @erjohnso I am wondering if this issue still needs to be addressed, or if this has been updated since this was opened.

@naegelin Are you still running into that problem with the stacktrace on a newer version of salt? We're currently on `2015.5.1`. If so, do you think a new issue should be filed about that, or is that close enough to the original request?

**Comment by naegelin** [comment]
We're using 2014.7.4 and when using a FQDN we get :
```The following exception was thrown by libcloud when trying to run the initial deployment:
{u'domain': u'global', u'message': u"Invalid value for field 'resource.name': 'salttest.spotflux.com'.  Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'", u'reason': u'invalid'}
Error: There was a profile error: Failed to deploy VM```

**Comment by rallytime** [comment]
OK thanks very much for the update!

ping @erjohnso

**Comment by rallytime** [comment]
I have been digging into the FQDN issue a bit today. I can certainly reproduce your error on 2015.8.0:
```
[ERROR   ] Error creating host123.mydomain.com on GCE

The following exception was thrown by libcloud when trying to run the initial deployment:
{'domain': 'global', 'message': "Invalid value for field 'resource.name': 'host123.mydomain.com'.  Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'", 'reason': 'invalid'}
Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/cloud/clouds/gce.py", line 2124, in create
    node_data = conn.create_node(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 2396, in create_node
    self.connection.async_request(request, method='POST', data=node_data)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 929, in async_request
    response = request(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 120, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 692, in request
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 799, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 145, in __init__
    self.object = self.parse_body()
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 271, in parse_body
    raise InvalidRequestError(message, self.status, code)
InvalidRequestError: {'domain': 'global', 'message': "Invalid value for field 'resource.name': 'host123.mydomain.com'.  Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'", 'reason': 'invalid'}
Error: There was a profile error: Failed to deploy VM
```
The thing that I don't understand is whether or not this is an upstream bug, a salt bug, or something that just isn't supported by GCE. 

At the top of the `create` function in `salt.cloud.clouds.gce.py` we're checking against the regular expression:
```
def create(vm_=None, call=None):
    '''
    Create a single GCE instance from a data dict.
    '''
    if call:
        raise SaltCloudSystemExit(
            'You cannot create an instance with -a or -f.'
        )

    if not GCE_VM_NAME_REGEX.match(vm_['name']):
        raise SaltCloudSystemExit(
            'The allowed VM names must match the following regular expression: {0}'.format(
                GCE_VM_NAME_REGEX.pattern
            )
        )
```
Where `GCE_VM_NAME_REGEX` is the same regex listed in the error from libcloud: `GCE_VM_NAME_REGEX = re.compile(r'(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)')`

We pass this check without raising a salt-cloud error, but then later the error bubbles up from GCE through libcloud when we call `node_data = conn.create_node(**kwargs)` further down in the function.

@erjohnso Could you pop in here and provide some insight to what the intended/expected behavior should be?

**Comment by tbaker57** [comment]
CGE doesn't support periods in VM names, only letters, numbers and hyphens:

![gce](https://cloud.githubusercontent.com/assets/8262456/9870212/57fc832c-5bcd-11e5-9db0-0dd6c64d2629.png)

**Comment by rallytime** [comment]
That would do it, then! Thanks for confirming that @tbaker57. So the fix here is to make sure we're catching minion names the way we think we should be before sending the creation event to GCE, and of course providing a helpful error. 

@naegelin Once that nasty stacktrace gets cleaned up, would you considered this issue resolved since it appears GCE doesn't support using FQDN for minion ids?

**Comment by jcockhren** [comment]
nice! Good find @tbaker57

**Comment by rallytime** [comment]
I've fixed the check in the regex to make sure we're checking to make sure "dots" aren't getting passed to GCE from salt-cloud and hides the stacktrace from liblcloud. I also provided a more useful error for the user.

Sound good @jcockhren and @naegelin?

**Comment by naegelin** [comment]
sounds good to me :)

**Comment by tbaker57** [comment]
As a workaround, if you really want your minion id to be a FQDN using GCE, you can add 

```
...
  minion:
    append_domain: foo.bar.com
```
in your GCE salt-cloud profile to get your minion id in the form of a FQDN while still respecting the GCE restrictions on VM names.
