### ISSUE TITLE
lxc module incompatible with LXC -> 0.9.0

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#11712]
lxc-version was last bundled with LXC 0.9.0. 1.0.0 was released on the 20th of February, but salt v2014.1.1 (which has this issue) was tagged on the 18th of March.

It looks like this is no longer an issue on the develop branch, but that has not been merged into any stable release branch yet. The develop branch docs say "You need lxc >= 1.0 (even beta alpha)", but the v2014.1.1 release says no such thing AFAICT.

It would be great to know (and have documented) exactly which version of LXC the v2014.1.1 release (and future releases) was tested to work with.

**Comment by basepi** [comment]
Based on the initial issue stating that this wasn't an issue on the develop branch, the age of this issue, and the fact that the lxc support has been thoroughly rewritten since that point, I'm going to assume this is no longer an issue. Happy to re-open if that assumption is incorrect. Sorry we weren't more proactive on this one.
