### ISSUE TITLE
allow custom runners in "_runners" directories

### ISSUE THREAD

**Issue by jcockhren** [saltstack/salt#12511]
[The current approach for enabling custom runners](http://docs.saltstack.com/en/latest/ref/runners/#writing-salt-runners) requires modification of the `runner_dirs` on the master. I think an additional `_runners` directory in the file_roots should be considered as well. Basically, in the same manner custom modules are allowed, however not sent to minions.
This will allow runners to be updated and managed in a workflow similar to every other customization point, via gitfs, for example.

Thoughts?

**Comment by whiteinge** [comment]
Cross-ref #13842.

**Comment by Lothiraldan** [comment]
Any news about this issue?

**Comment by basepi** [comment]
Unfortunately, no, we haven't had a chance to implement this yet.

**Comment by basepi** [comment]
When we add runners here, we need to also make sure the outputters are being loaded by the master as well. (The syncing is already in place for the outputters)

Really the master should load all custom code.

**Comment by whiteinge** [comment]
The master respects `/srv/salt/_outputters`? Wow.  (o_O)

Seconding your last statement: If we do this the loader should check `/srv/salt/_XXX` for all module types.

**Comment by basepi** [comment]
It's `_output`, but yes. I think it's been pretty much always broken, but rallytime fixed it today. Still doesn't sync to the master, though.

**Comment by rallytime** [comment]
Here's a list of [Dynamic Modules](https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html) that I found today when checking this stuff out. The docs were [updated recently](https://github.com/saltstack/salt/pull/27410). There will be more listed there as the change merges forward and the docs rebuild. I also discovered we can sync all kinds of things down to the minion (such as outputters) in saltutil with some nifty [sync_* functions](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_all).

**Comment by gtmanfred** [comment]
@terminalmage does your PR from a couple weeks ago close this?

Thanks

**Comment by jcockhren** [comment]
@gtmanfred which PR is that? I'd love to take a peek. ;)

cc @terminalmage

**Comment by gtmanfred** [comment]
I believe this one should be able to close this
https://github.com/saltstack/salt/pull/30647

**Comment by terminalmage** [comment]
Yep, this is implemented now and will be available in 2016.3.0. To sync runners to the master, you can run the following:

```
salt-run saltutil.sync_runners
```

However, the update to 2016.3.0 will bring about one non-compatible change that affects some people. This will be included in the release notes but I'll state it here too. Before this runner module was added in my pull request, custom runners could be added by creating ``/var/cache/salt/extmods/runners`` and dropping your runners there. In 2016.3.0, this location has been moved one level down (i.e. ``/var/cache/salt/master/extmods/runners``). The reason for this is to reduce confusion since the minion's synced modules go under ``/var/cache/salt/minion/extmods``.

Anyone who had been manually placing custom runners will find they are no longer available, and should use the new runner command I noted above to sync them.

**Comment by terminalmage** [comment]
Since this is implemented now, I will close this.
