### ISSUE TITLE
[Feature Request] Batch mode in orchestrate runner

### ISSUE THREAD

**Issue by donatello** [saltstack/salt#12556]
It would be good to have the batch mode in orchestrate runner's "state specifications".

For example - the following would run the `update_nginx_config` on only 2 minions matching the "web*" glob.

```
webserver_update:
  salt.state:
    - tgt: 'web*'
    - batch: 2
    - sls:
      - update_nginx_config
```

This would make upgrading code a very simple process through salt.

Is this perhaps already possible? I could not find it anywhere in the documentation.

**Comment by piffio** [comment]
:+1: for this one. any news about a potential release target for this feature?
To me, not being able to specify the batch parameter to the orchestration module makes it unsuitable for real orchestration outside a test / staging environment

**Comment by basepi** [comment]
We aren't targeting a specific release at this time, but we do want to get this in. The biggest issue is deciding where and how the batching is implemented. Orchestrate itself runs on the master, and then calls down to the minions to do work. If you have a batch flag on the top level call to `salt-run state.orchestrate`, does that mean that all salt.function and salt.state calls inside of the orchestrate will be batched the same? Or do we just add a batch argument to each of these state functions so that they can be configured for batching individually?

**Comment by piffio** [comment]
In my opinion, we should be able to specify the batch parameter per state function, since this will allow extreme flexibility in the configuration, and additionally couple this with a "default" flag that could be sent through `salt-run`.
The latter is less important to me, and we could accept that the default is "no batch", so that only those who require special batching configuration will have to declare it in the orchestrate file.

**Comment by basepi** [comment]
I agree, per-state is the way to go.

**Comment by CashIsClay** [comment]
Just came across this. Big +1 here. A common example for this need would be RMQ clustering, which requires installing and starting RMQ first before running the cluster commands (this is why Orchestrate is necessary), then the cluster commands require that other nodes' rabbitmq-server service is running when executed (batch would solve this part).

Until then, my provisioning process is two separate steps: highstate + rmq cluster sls

**Comment by ahammond** [comment]
+1 and I agree it belongs in the individual states. For example, I want an orchestration where I can batch through the slowish deployment of a bunch of rpms containing content so that my rpm repo doesn't get clobbered and then, once they're out, run a state across the entire cluster to tweak a symlink.

**Comment by nleib** [comment]
is there some kind of work around, lets say I want to restart my web tier as part of my orchestration.
of course I wouldn't want to restart them all at once.
anybody have some kind of work around till batch will be available ?

**Comment by ahammond** [comment]
Nothing elegant, but you can of course do the batching manually in your orchestration. In order to do (roughly) 10% batching, I'm using search terms that take advantage of the fact that our servers are numbered, so they end with *0, *1, *2, *3, ... *9. Hokey, but it works.

**Comment by nleib** [comment]
another thing I thought of is batching through cmd.run on the salt master, for example:
``` yaml
cmd.run:
  salt.function:
    - tgt: YourSaltMaster
    - arg:
      - " salt -G 'kernel:Linux' cmd.run -b 10% ' YOUR CMD TO RUN' "
```
of course you can you and kind of targeting and any kind of salt function.

**Comment by nleib** [comment]
@basepi any estimation when this feature will be available ?

**Comment by kevinquinnyo** [comment]
I know you all have a lot on the development plate, but this feature would be very helpful for me too.  Sometimes I want to target a group by a minion-id glob, but I may not know in advance how many there are -- in a horizontally scalable cloud environment for instance, and a task may require non-concurrent (one server at a time) execution in certain cases.
