### ISSUE TITLE
salt-cloud custom functions/actions

### ISSUE THREAD

**Issue by Katafalkas** [saltstack/salt#12587]
Hey,

Would it be a good idea to have similar thing for salt cloud as you do for `_states` directory ? `_clouds` directory for custom cloud functions and actions that would overwrite the default ones ?

**Comment by rallytime** [comment]
@Katafalkas Did you ever get this working? I was thinking about documenting this, but I don't think I quite have this configured correctly as I can't get salt-cloud to pick up my custom driver.

**Comment by bricewge** [comment]
I tried `_clouds`, `_cloud` and `_cloud/clouds` in my `file_roots` to overwrite files in `/usr/lib/python2.6/site-packages/salt/cloud/clouds/` but it didn't worked. 

However adding the line `cloud_dirs: [/srv/salt-dirs/cloud]` to my master config worked. I just had to put the proxmox driver form develop in `/srv/salt-dirs/cloud/proxmox.py` to get proxmox 4.0 support in salt `2016.3.3` I got the idea for the issue #31206.

BTW this issue is related to #24058

**Comment by rallytime** [comment]
Thanks for the update here and for the work around. I'll update the labels here since this still isn't working and I wasn't able to get it to work before, either.

**Comment by amendlik** [comment]
The problem seems to be that salt://_clouds does not get sync'ed to the external modules directory (`/var/cache/salt/master/extmods`). That is addressed in this recent commit: f7a6f353707

**Comment by rallytime** [comment]
Closed via #40944 and #42616
