### ISSUE TITLE
Peer running is difficult, create a salt-peer utility to simplify

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#12610]
Peer calls are basically a minion acting as a master. The general format of the calls should be basically the exact same as the salt command, but instead it needs to occur through salt-call publish.publish with mangled inputs. We should have a salt-peer command that has basically the same behavior as the salt command, but uses the publish.publish interface.

**Comment by boltronics** [comment]
There hasn't been any activity in a long time (or ever, as far as code activity goes, AFAIK anyway), but I think Ryan's idea is still a good one.

**Comment by basepi** [comment]
@saltstack/team-triage

**Comment by boltronics** [comment]
I don't think such a utility yet exists.

**Comment by dmurphy18** [comment]
@ryan-lane Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt (currently 3006.3) and if still an issue, please open a new issue, which will have metrics in tracking issues.

This looks more like a feature request, if still interested, can you open a feature request using the new template, this allows for matrices from the template to track issues and allows for more information as to what problems are encountered or requested.
