### ISSUE TITLE
Add top files to /srv/salt/_{grains, modules, states, etc}

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#12637]
I'd like to add "top" files to the custom distribution directories to better control which modules get distributed to which minions.  Currently, all modules get distributed to all minions. It's not possible to limit to certain minions. An example use case would be in a multi cloud environment I would like to distribute EC2 specific grains in '/srv/salt/_grains' only to my EC2 minions and not my Rackspace or bare metal minions.

Here's how I propose this would work:

A directory such as '/srv/salt/_grains' that does not have a top file will continue to work as the current behavior.

If I drop a top file in there I could control which minions get which grains.

Example top file:

```
base:
  '*':
    - mycustomgrain
  'ec2*':
    - ec2grain
  'os:Ubuntu':
    - match: grain
    - myubuntugrain
```

Possibly if there's a grain in the '/srv/salt/_grains' directory that isn't addressed in the top file it should be distributed to all minions.

I'd love to hear other people's thoughts on how this should work.

**Comment by roflmao** [comment]
Anything new here? Some custom grains modules just shouldnt run on all nodes in my case.

**Comment by UtahDave** [comment]
I still think this is something worth working on.

**Comment by UtahDave** [comment]
I still think it would be important to be able to selectively sync

**Comment by UtahDave** [comment]
still would be good to have

**Comment by roflmao** [comment]
@UtahDave++ for keeping this alive

**Comment by dmurphy18** [comment]
@UtahDave Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt (currently 3006.3) and if still an issue, please open a new issue, which will have metrics in tracking issues.

This looks more like a feature request, if still interested, can you open a feature request using the new template, this allows for matrices from the template to track issues and allows for more information as to what problems are encountered or requested.

And @UtahDave would love a PR on this :+1: , but if still want it, please open a new Feature Request
