### ISSUE TITLE
Default docs.saltstack.com to latest release version and call out latest docs

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#12754]
docs.saltstack.com and the default for salt on readthedocs is to present the user with the latest docs from develop. This can be a tremendous source of confusion and frustration for new users, as these are typically the first hits in Google, and reference the user to features and functionality that does not yet exist.

When Salt was younger this was probably a good strategy, but as Salt has matured and I expect much of the userbase has moved to using Salt packages from their package managers it would seem best to present the documentation default as the latest *release* version of Salt.

At the very least whether the default presentation changes, the development docs should have a large banner calling out the fact that they are for the development version. A good example of this is the Django docs. docs.djangoproject.com gives you the latest release, and docs.djangoproject.com/en/dev/ gives you the development docs with a very noticeable banner.

**Comment by bemeyert** [comment]
Any news on this? AFAIK only the "latest" aka "devel" docs are per default accessible under http://docs.saltstack.com/en/latest/. Since if you go to docs.saltstack.com you will be automatically redirected to the "devel" documentation. Since caused me already a lot of trouble and headaches. Not every new feature(meaning it's in devel not in stable) is marked as such. All in all I can't rely on using "latest" docs, since there are too many pitfalls.
The only reliable documentation seems to be to use the docs runner on our servers. This is not very usable/accessible. And I don't like to figure out how to build the docs myself. Although I guess sooner or later I have too...

So please, make the documentation for the stable release available/accessible.

Cheers

**Comment by whiteinge** [comment]
Still on the roadmap. We've made some progress on this as of the week after SaltConf. Just need to find a little time to get it over the finish line.

Looping in @jacobhammons.

**Comment by bemeyert** [comment]
@whiteinge Thanks for the response. If I could I would send you some time ;)

**Comment by gravyboat** [comment]
Looking forward to this one being completed! Thanks for the update @whiteinge.

**Comment by jacobhammons** [comment]
This was fixed with the version selector we added recently.

@dnd if you think this is sufficient please close, thanks!

**Comment by gravyboat** [comment]
:+1: @jacobhammons

**Comment by dnd** [comment]
@jacobhammons I think this looks great. The only thing I would still suggest is on the docs for "develop" to have a colored banner or something across the top, just so people can avoid accidentally cutting themselves. The fact that latest defaults to latest release works to mitigate that though.

**Comment by gravyboat** [comment]
@dnd That's actually a really good idea. Maybe one of those 'corner cut' style banners like the fork me on github ones?

**Comment by jacobhammons** [comment]
@dnd @forrest would you want it there for develop only?

**Comment by dnd** [comment]
Yes, I think it should be for develop only. That way it completely stands
out on its own.

**Comment by gravyboat** [comment]
@jacobhammons @dnd Yeah just for develop so that you realize you may have stumbled into the wrong version.

**Comment by jacobhammons** [comment]
@dnd @gravyboat I added a tag that shows as you scroll any topic in develop, let me know if you think this is sufficient. Thanks!

**Comment by dnd** [comment]
@jacobhammons That's pretty tiny. I didn't even see it at first, and I went to the page explicitly looking for it. 

I'm thinking more like something like I mentioned in my original message. See how Django does it. https://docs.djangoproject.com/en/dev/ It is not terribly aesthetically pleasing, but that's because it's not supposed to be. It let's you know in no uncertain terms you are looking at dev docs. Make it red, blue, whatever. It should be bold and stand out, not be small, and fade into the page.

**Comment by jacobhammons** [comment]
@dnd ahh, OK, that makes sense. I'll make some updates here.

**Comment by jacobhammons** [comment]
@dnd @gravyboat I replaced the dev tag with a notification bar, take a look and let me know if you think this solves the issue. Thanks!

**Comment by gravyboat** [comment]
@jacobhammons This looks pretty good! I think that right now it fits into the theme a bit too much color wise, it might also be good to make it extend across the whole screen. I modified it a bit below (obviously the nav needs to slide down for this):

![develop_doc_warning](https://cloud.githubusercontent.com/assets/1396878/8224218/483b93e6-1538-11e5-85c7-94bf722234f0.png)

**Comment by jacobhammons** [comment]
@gravyboat red is typically used to show an error condition (the job failed, file could not be saved, server is reporting a disk failure). Yellow is used for warnings (server could not be reached -- maybe you are offline and this is expected, otherwise you better take a look).

I consider this an 'informational' message, since there isn't anything wrong with using the develop docs, you just need to be aware that the feature you are reading about might not be in a formal release. I also don't think the size needs to be increased, I'd be pretty surprised if someone didn't see it. I'll run it past our UX guy here to get his thoughts, but I plan to leave it as is for now. Thanks for your help with this.

**Comment by rallytime** [comment]
@dnd @gravyboat Do you consider this fixed now? Can this issue be closed?

**Comment by gravyboat** [comment]
@rallytime :+1: to closing this.

**Comment by dnd** [comment]
Yes, I think this satisfies the original request. Thanks.
