### ISSUE TITLE
Extended state info not shown in salt.state.show_* functions.

### ISSUE THREAD

**Issue by cheuschober** [saltstack/salt#12812]
When a state is extended I would normally expect to see the extended state information in show_sls() or, at the least, show_low_sls().  I'm uncertain whether to call this a bug that should be changed; cases could be made either way for displaying states pre-extension or post-extension, however, if the functions are to remain as-they-are, then I'd strongly recommend that the documentation for the salt.state.show_\* functions and the extend docs be updated to explicitly alert users that extended states will not be displayed in show calls.

**Comment by eliasp** [comment]
Besides improving the docs, I'm also strong in favour of "fixing" this, as one expects the `.show*` functions to display the datastructure of states how they'll be applied.

Information added by `extend` are IMHO crucial here, otherwise there's no real way to tell whether `extend` worked as expected or not (besides actually applying the state).
