### ISSUE TITLE
Progress report for orchestrate runner

### ISSUE THREAD

**Issue by livenson** [saltstack/salt#12867]
Hi,

not sure if this is a proper question, but I was wondering about how it's possible to get a run-time progress report from an orchestrate runner. Currently it's only visible after the orchestration has finished. Any hints?

Thanks!

**Comment by pgnattar** [comment]
I have just working on salt and switching from ansible. Please let me know if this feature is still being considered.

**Comment by Oloremo** [comment]
This feature is very needed.

**Comment by basepi** [comment]
@gtmanfred Pinging to get a current salt employee on this ticket

**Comment by BlaineAtAffirm** [comment]
+1 

we actually wrote our own simplified version of the now deprecated overstate runner when the switch to orchestrate happened. partially for want of this feature. This feature would be very helpful in migrating to orchestrate

**Comment by Oloremo** [comment]
not stale

**Comment by anitakrueger** [comment]
This would be really useful in a lot of places.

**Comment by dmurphy18** [comment]
@livenson Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt (currently 3006.3) and if still an issue, please open a new issue, which will have metrics in tracking issues.

This looks more like a feature request, if still interested, can you open a feature request using the new template, this allows for matrices from the template to track issues and allows for more information as to what problems are encountered or requested.
