### ISSUE TITLE
git.present should work like git.latest

### ISSUE THREAD

**Issue by diegows** [saltstack/salt#13317]
The state function git.present should have the same parameters that git.latest has. For example, sometimes you only needto be sure that the repository is present, if not, clone it. But after that, you could be using alternative methods to update the clone, like CI tools.

If you use latest, the repo will be upgraded when highstate is applied, and sometimes is not the desired behavior.

**Comment by terminalmage** [comment]
@diegows In the 2015.8 branch I have recently added a new argument called ``update_head``. If set to ``False``, then if the repository does not exist, it will be cloned, but otherwise, if there are updates available the local HEAD will not be modified. Fetches will still be performed. Does this satisfy your use case?

**Comment by diegows** [comment]
No, because there are cases where I update the minion state without
updating the code. Usually this is controlled by Jenkins. Think in prod
envs for example, I want to control code deploy from Jenkins only.

Makes sense?
