### ISSUE TITLE
pkgrepo should only run refresh_db once

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#13361]
Currently pkgrepo.managed will run apt-get update for every PPA added and it's necessary to do workarounds with module.wait:

https://gist.github.com/ryan-lane/085ec4fd14f337a6b09f

It would be nice if pkgrepo.managed only ran refresh_db once all pkgrepo states have run. It's actually the module and not the state that does this in the develop branch. Maybe aggregates is a way to handle this?

**Comment by terminalmage** [comment]
This is worth doing, I'm going to keep it open.

**Comment by terminalmage** [comment]
After looking at this again, a mod_aggregate solution would require that pkgrepo be able to support multiple repos, in the way that `pkg.installed` supports multiple packages via the `pkgs` argument. What the `pkg` state module does in `mod_aggregate` is takes all of the arguments from all the states and merges them into a single low chunk with all the packages passed through in the `pkgs` argument. There's no equivalent available for `pkgrepo`.

**Comment by dmurphy18** [comment]
@ryan-lane Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.

AS per @terminalmage https://github.com/saltstack/salt/issues/13361#issuecomment-762381966 comment, this looks more like a feature request.  Please create a new feature request for this if still interested, given this was originally opened in 2014.
