### ISSUE TITLE
no way to disable salt-cloud from adding minion key

### ISSUE THREAD

**Issue by jaloren** [saltstack/salt#13420]
When salt-cloud boots a VM, it always places the virtual machine's public key in /etc/salt/minion. --no-deploy does NOT disable this option.

There should be an option that the user can specify in salt-cloud that says "do not add pub key for minion set up."

Also, i do not think that --no-deploy should be the way this is done. I should be able to control whether a key is added or not, regardless of whether i want to run a boot script.

**Comment by rallytime** [comment]
This looks to have been fixed since this bug was filed:

1. Create VM using --no-deploy: `salt-cloud -p ec2-ubuntu-14 nt-cent7 --no-deploy`
2. Creation was successful.
3. Check directories to see if minion key shows up:
```
# ls /etc/salt/pki/master/minions
nt-master  nt-test
# salt-key
Accepted Keys:
nt-master
nt-test
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```
And on the created minion:
```
$ ls /etc/salt
ls: cannot access /etc/salt: No such file or directory
```
Versions Report:
```
# salt-cloud --versions
            Salt: 2015.5.1-97-g88a997e
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.17.0
```
I'm going to close this. If this pops up again, please leave a comment and we can re-open. Thanks!
