### ISSUE TITLE
Support Hyper-V for salt-cloud provisioning and salt virt

### ISSUE THREAD

**Issue by jaloren** [saltstack/salt#13449]
This is a feature request to support Hyper-V as a cloud provider and in salt virt. Hyper-V is a native hypervisor written by Microsoft.

**Comment by ernstae** [comment]
+1 here too

**Comment by menzow** [comment]
Any progress on this?

**Comment by abrinded** [comment]
+1 here, wondering if there's any news on this.

**Comment by Duvrazh** [comment]
+1
Anyone worked on this?

**Comment by basepi** [comment]
@Duvrazh Not that I know of. Unfortunately we're pretty focused on bug fixes so we haven't had much time for features.

**Comment by gnubyte** [comment]
+1

I saw some similar work being done for OpenStack, but not SaltStack.

**Comment by dmeiser** [comment]
Terraform is looking at adding this:  https://github.com/hashicorp/terraform/issues/3004

Perhaps salt could learn from some of the existing integrations over there.

**Comment by aboe76** [comment]
This should not be closed

**Comment by dractyl** [comment]
+1

**Comment by ITJamie** [comment]
+1

**Comment by gee456** [comment]
+1

**Comment by dmurphy18** [comment]
@jaloren Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.

This looks more like a feature request, can you open a feature request using the new template, this allows for matrices from the template to track issues and allows fo
r more information as to what problems are encountered or requested.
