### ISSUE TITLE
Windows Registry Key Problem on 64bit Machine

### ISSUE THREAD

**Issue by ironwilliamcash** [saltstack/salt#13513]
The problem occurs when trying to add a registry key to a Windows 64bit machine. 
Example from SLS file: 
![image](https://cloud.githubusercontent.com/assets/7818483/3305038/404c1428-f651-11e3-84e9-42c5876033f5.png)

This key would be added in the "WOW6432Node" path instead of the one specified in the SLS file. There doesn't seem to be a way to force it to the 32bit path, which Windows actually uses for the auto-login. 

There should be a method of forcing the path to be registry key so that it doesn't get added to the WOW6432Node instead. 

Tagging @UtahDave , as per recommendation from IRC forum. 

Thanks

**Comment by enwony** [comment]
I made some analysis of this issue (got same problem):

*Reflection property* description "On 64 bit machines a duplicate value will be created in the Wow6432Node for 32bit programs. This only applies to the SOFTWARE key. This option is ignored on 32bit operating systems. This value defaults to True. Set it to False to disable reflection."

[In saltstack reg module](https://github.com/saltstack/salt/blob/8c204a45ab93711c4263e35c5470546c4f343266/salt/modules/reg.py) (unneeded code cut):
```
self.reflection_mask = {
  True: _winreg.KEY_ALL_ACCESS,
  False: _winreg.KEY_ALL_ACCESS | _winreg.KEY_WOW64_64KEY,
}

def set_value(hive, key, vname=None, vdata=None, vtype='REG_SZ', reflection=True):
...
    access_mask = registry.reflection_mask[reflection]
...
    handle = _winreg.CreateKeyEx(hive, key, 0, access_mask)
    _winreg.SetValueEx(handle, vname, 0, vtype, vdata)
    _winreg.CloseKey(handle)
```

getting deeper in [_winreg module of python](https://github.com/python-git/python/blob/715a6e5035bb21ac49382772076ec4c630d6e960/PC/_winreg.c) (part of code)
```
PyOpenKey(PyObject *self, PyObject *args) // function
if (!PyArg_ParseTuple(args, "Oz|ii:OpenKey", &obKey, &subKey, &res, &sam))
rc = RegOpenKeyEx(hKey, subKey, res, sam, &retKey);
...
PySetValueEx(PyObject *self, PyObject *args) // function
if (!PyArg_ParseTuple(args, "OzOiO:SetValueEx",&obKey,&valueName,&obRes,&typ, &value))
rc = RegSetValueEx(hKey, valueName, 0, typ, data, len);
```

getting more deeper in MSDN:
[RegOpenKeyEx](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms724897(v=vs.85).aspx)
[RegSetValueEx](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms724923(v=vs.85).aspx)
[Meaning of KEY_WOW64_XXKEY - Accessing alternate value keys from MSDN](https://msdn.microsoft.com/en-US/library/aa384129.aspx)

First of all, *it's all about 64 bit windows systems*
Second, probably, they run 64 bit salt minion (maybe not always?).

*minion runs registry* commands with:
reflection: True - KEY_ALL_ACCESS - mean just use salt minion node - x32 or x64; most chance x64
reflection: False - KEY_ALL_ACCESS | KEY_WOW64_64KEY - mean access to 64 bit node only

*Checking*: (using salt's python on x64 bit machine) - reporting "Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32"
```
import _winreg
# created key in 64bit SOFTWARE node, but not in Wow6432Node/SOFTWARE
h1 = _winreg.CreateKeyEx(_winreg.HKEY_LOCAL_MACHINE, "SOFTWARE\\atest1", 0, _winreg.KEY_ALL_ACCESS) 

# created key in 64 bit SOFTWARE node, but not in Wow6432Node/SOFTWARE
h2 = _winreg.CreateKeyEx(_winreg.HKEY_LOCAL_MACHINE, "SOFTWARE\\atest2", 0, _winreg.KEY_ALL_ACCESS | _winreg.KEY_WOW64_64KEY)

# created key in 32 bit Wow6432Node/SOFTWARE node, but not in 64 bit SOFTWARE
h3 = _winreg.CreateKeyEx(_winreg.HKEY_LOCAL_MACHINE, "SOFTWARE\\atest3", 0, _winreg.KEY_ALL_ACCESS | _winreg.KEY_WOW64_32KEY)
```

That all means that *no way to create 32bit key by reg.present if salt minion is 64 bit* (3rd example not exists in the code).

Moreover, [reflection](https://msdn.microsoft.com/en-US/library/aa384235.aspx) was removed since [windows 7](https://msdn.microsoft.com/en-US/library/aa384253.aspx) 

We can mimic old behavior by calling create/delete/enum functions twice (with _32 and _64 flags), but looks like it never work, so we can safe remove this option and replace it to UseWOW: 32/64/both/native or something like this. 

Any suggestions?
