### ISSUE TITLE
Using git submodules in gitfs

### ISSUE THREAD

**Issue by batulin-s** [saltstack/salt#13664]
Using git submodules in gitfs would be possible to separate access between independent states for different groups of minions. In this case We have one repo with the common states and some submodules for user-dependent states and We can allowing access to the submodule without access to all states.
As far as I could see this feature can be implemented  in fileserver/gitfs.py 
in git-python part. I can do it, but have a one question. Is submodules pulled in all cases or if defined special variable in config (like pull_with_submodules)?

**Comment by eliasp** [comment]
:+1: for this…
I'd like to use submodules to have a repository containing stable/tested versions of public salt formulas.
Then I could easily keep them in sync with upstream after testing the latest commit in a `dev` branch.

**Comment by bechtoldt** [comment]
:+1:

**Comment by terminalmage** [comment]
I have an idea on how to implement this. I was investigating Pygit2's submodule support and unfortunately it wouldn't work for gitfs because it requires that a branch is checked out. We don't checkout a branch because we have to be able to support any branch/tag at any time as a fileserver environment, so we just fetch git objects and assemble files from the blob data. That way, if one minion wants a file from branch ``master`` and another wants one from branch ``dev``, we don't run into a race condition.

A better solution for gitfs would be to read in ``.gitmodules`` and fetch each configured submodule into its own separate cachedir underneath ``/var/cache/salt/master/gitfs``. Then, each GitProvider object would have an attribute listing its submodules, each of which would link to the separately-fetched repo.

Doing it this way *should* make it possible to support submodules irrespective of the ``gitfs_provider`` being used, but I can't promise anything until I start playing around in a python shell and figuring out how to implement it.

I'm going to tentatively target this for the next feature release, but there are higher-priority issues I'm committed to doing for this release so it may not make it in until the one after next.

**Comment by Heiko-san** [comment]
+1 ... pleeeeeeaseeeeee , we really^n need this

**Comment by terminalmage** [comment]
@Heiko-san This is targeted for the feature release after the upcoming one.

**Comment by cliffrowley** [comment]
@terminalmage which release would that be, the 2016.x?

**Comment by terminalmage** [comment]
It would be targeted for this fall.

**Comment by terminalmage** [comment]
In other words, not the imminent release.

**Comment by mrichar1** [comment]
For info, an alternative approach to delegating access in this way can be achieved using the mountpoint option on a repo with different access:

```
gitfs_remotes:
  - https://git.example.com/top.git:
  - https://git.example.com/devolved.git
    - mountpoint: salt://devolved
```

You can then do things like:

```
include:
  - devolved.foo
```

Note however that this only works for gitfs, not for git_pillar (see #34210)

**Comment by akatrevorjay** [comment]
This issue was obviously not meant to be closed, can you reopen? Thanks!

**Comment by phineas42** [comment]
Agreed. This issue should be reopened.

**Comment by iavael** [comment]
Up

**Comment by esilva-everbridge** [comment]
Is this still being worked on? It's something that has become important to us recently.

**Comment by esilva-everbridge** [comment]
If anyone can point to where in the codebase the functionality exists I'd love to take a look.

**Comment by terminalmage** [comment]
Yeah I'm sorry but I never got the opportunity to start this. All of the gitfs code is in salt/utils/gitfs.py. It's quite a large file, so you'd need to take some time to familiarize yourself with it. salt/fileserver.gitfs.py will create instances of the `GitFS` class, and each `GitFS` instance will have multiple `Pygit2` or `GitPython` class instances, one per entry in gitfs_remotes.

You'll also want to know how to add a new configuration parameter to gitfs so that you can toggle whether or not salt tries to list submodules This configuration loading happens in the `GitProvider` class (parent of both `Pygit2` and `GitPython`) `__init__` function.

**Comment by nandhaece07** [comment]
could you please help me on this feature request? anyone working on it.

**Comment by esilva-everbridge** [comment]
I started to look at this but priorities at work have shifted, so I can't focus on it at the moment. @terminalmage gave a good overview of what and where to look to start working on it but I can't spare the time. :(

**Comment by vps-eric** [comment]
Is this issue still in progress?

**Comment by dmurphy18** [comment]
@batulin-s Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.

This looks more like a feature request, if still interested, can you open a feature request using the new template, this allows for matrices from the template to track issues and allows for more information as to what problems are encountered or requested.

**Comment by IvanShokin** [comment]
Is this issue still in progress?
