### ISSUE TITLE
cmd.script - multiple arguments doesn't seem to work

### ISSUE THREAD

**Issue by Supermathie** [saltstack/salt#13941]
I'm trying to do this from a salt module:

```
__salt__['cmd.script']('salt://win/files/ImportUsers.ps1', args=(realfile, oupath), shell='powershell')
```

What happens is that the arguments listing doesn't get properly expanded and stuffed into argv of the invoked process - it gets turned into a Python string that confuses Powershell:

```
[INFO    ] Executing command "Powershell -executionpolicy bypass -File c:\\users\\admini~1\\appdata\\local\\temp\\1\\tmp95zpqa.ps1 ('c:/salt/var/cache/salt/minion/files/base/win/files/testusers.csv', 'OU=Users,dc=ad2012r2,dc=storagelab,dc=netdirect,dc=ca')" in directory 'C:\\Users\\Administrator'

Import-Csv : Cannot find drive. A drive with the name '('c' does not exist.
```

My job submission looks like:

```
salt 'host' storagelab.import_users salt://win/files/testusers.csv oupath='OU=Users,dc=ad2012r2,dc=storagelab,dc=netdirect,dc=ca'
```

**Comment by twangboy** [comment]
@Supermathie The problem here is how you're passing the `args` parameter. `args` needs to be a string, not a tuple. So you would make it something like this:
```
args='C:\path\to\file.csv "OU=Users,dc=ad2012"'
```
But it looks like you're defining these values before the `__salt__` call, so you'll want to make sure that the `oupath` has double quotes (`"`) surrounding the container value like this:
```
oupath = '"OU=Users,dc=ad2012r2,dc=storagelab,dc=netdirect,dc=ca"'
```
And finally, to make sure salt doesn't try to escape the args, you'll need to pass `python_shell=True`. So, you're final block of code should look something like this:
```
    realfile = 'c:/salt/var/cache/salt/minion/files/base/win/files/testusers.csv'
    oupath = '"OU=Users,dc=ad2012r2,dc=storagelab,dc=netdirect,dc=ca"'
    return __salt__['cmd.script']('salt://args.bat',
            args=' '.join([realfile, oupath]),
            python_shell=True)
```
