### ISSUE TITLE
Feature request: "Leader election" 

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#14074]
This feature request is to open a dialog about a request feature for "leader election".

The basic idea is that in the master config you can specify a target of some type, such as `G@os:Ubuntu` and Salt would automatically select a minion from that targeted group at random and assign it to be a leader. Perhaps that means a grain is set on that specific minion.

Then you could target a command such `as  salt -G 'os:Ubuntu' --leader db.upate`   and that command would only be run on the leader of that targeted group.

If the leader doesn't respond to the master, then the master would automatically choose another minion from that targeted group and promote it to leader.

What would be the best way to implement this? Is there a better way to set up the interface to use this?

**Comment by RobertFach** [comment]
Hi, what is the status of this feature request, any progress here?

I really like the description and points of @UtahDave. 
Right now, I'm working on a replicated filesystem which I would like to be fully automatically managed by Salt. This requires, as already mentioned by @malinoff, that one of the nodes is considered to be a leader. I don't like to have to specify a grain or a pillar which tells salt which of the nodes is a "leader", which in that case only means that some commands have to be run only on one node. Therefore if an inherent feature (this should be a fully integrated leader election protocol, capable of dealing with different failure models [crash failures, byzantine?], masking different number of failures (up to N nodes) - by design) of salt would provide such a feature would be really beneficial.

Maybe, one could also live with the following idea:
- add an optional external service which implements features like leader election (and more), like Zookeeper, i think there are also pure python based solutions for quorum based leader election etc.
- provide salt modules/reactors that will interface that external service to provide the basic functionality required in the formulas, etc.
