### ISSUE TITLE
modularize lxc.init

### ISSUE THREAD

**Issue by mgwilliams** [saltstack/salt#14193]
lxc.init is 400 lines and performs several tasks. I propose that the creation and basic configuration be broken out into an lxc.configure function, that lxc.init invokes. This will, for example, allow the creation of an lxc without being forced to start it. The current option to 'not start' a container is functionally equivalent to invoking lxc.stop at the end of the process. In developing integration tests, certain invalid configurations need to be tested, but this is being complicated by lxc.init trying to start the (invalid) configuration.

**Comment by Sjd-Risca** [comment]
I think that the lxc.init is not suffering from a modularization problem but from a lack of configurability. By now is still not possible to parametrize the container set up and creation of too many parameters (like lxc.cap.drop, id.map, etc.), some of which also very critical!

Instead there is a reason why `The current option to 'not start' a container is functionally equivalent to invoking lxc.stop at the end of the process`, it is so because the lxc.bootstrap needs a working environment.

Please for reference read also: [here](https://github.com/saltstack/salt/issues/30576#issuecomment-206362389) and #21931
