### ISSUE TITLE
Feature Request: provide retry functionality for API Calls

### ISSUE THREAD

**Issue by colinbjohnson** [saltstack/salt#14383]
### Feature Request:

Provide the ability to retry API calls to third party services such as AWS. The ability to retry calls would be used to mitigate throttled responses or responses that return inconsistent data.
### Use Case - Mitigate Eventual Consistency Errors

To reproduce a situation where this would be useful:
1. Create a security group using boto_secgroup Module.
2. Authorize rules for the newly created security group using the boto_secgroup Module.
3. If authorize rules fails because of `InvalidGroup.NotFound` error, retry a number of times (see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/query-api-troubleshooting.html, search on `InvalidGroup.NotFound`)
--- I performed some tests earlier this week - if a "create security group" is followed by a "delete security group" the failure rate of the delete call (with `InvalidGroup.NotFound` is about 30%)
### Use Case - Ensure API calls Produce Consistent Result Despite Throttling
1. Create an AWS resource.
2. If response to request is `Rate Exceeded` then backoff and retry.
   --- I don't know what the API call limit is.
### Note:

For mitigating eventual consistency and throttling outside of Salt modules I've been using the "Retrying" python module (https://pypi.python.org/pypi/retrying) - would rather have Salt make a retry decorator (or another method of retry and/or backoff) available.

**Comment by Reiner030** [comment]
Hi, I think this is an "urgent" feature request... when searching for "Throttle" you find minimum
* a 2nd approved feature request for it: https://github.com/saltstack/salt/issues/21372
* my Route53 from May https://github.com/saltstack/salt/issues/23358
and perhaps some more already closed or without this keyword (Route53 API timeouts e.g.)... 

It seems that in route53 calls and salt-cloud is already a retry function implemented but it's missing completely for all other boto requests.

Actually I have e.g. states written to setup several ELBs but after 4,5 ELB setups "it's done" and I get only errors back (actual temporary fixed with sleep call which is very noisy  https://github.com/saltstack/salt/issues/29764 :) )

**Comment by blueyed** [comment]
This gets done in the cloud module already: https://github.com/saltstack/salt/blob/5c65b77b1a9f13b4c9cacb5ffcf19b94aa2b174c/salt/cloud/clouds/ec2.py#L412-L421

**Comment by max-arnold** [comment]
Something generic like this would be useful in the core: https://github.com/apache/libcloud/blob/trunk/libcloud/utils/misc.py#L276
