### ISSUE TITLE
Salt Cloud 2014.7 Provider issue

### ISSUE THREAD

**Issue by lparmentier-quatral** [saltstack/salt#14799]
Hi,

Here is my version:
```
root@edge-dev-hvmhost01:/etc/salt/cloud.providers.d# salt-cloud --versions
            Salt: 2014.7.0-630-g7eb1ad6
          Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
          Jinja2: 2.6
        M2Crypto: 0.21.1
  msgpack-python: 0.1.10
    msgpack-pure: Not Installed
        pycrypto: 2.6
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 13.1.0
            RAET: Not Installed
             ZMQ: 3.2.3
 Apache Libcloud: 0.15.1
```

Here is my provider conf:
```
root@edge-dev-hvmhost01:/etc/salt/cloud.providers.d# cat proxmox.conf
my-proxmox-config:
  provider: proxmox
  user: root@pam
  password: pass
  url: edge-dev-hvmhost01.edgeofcommand.com
```

Here is the problem:
```
root@edge-dev-hvmhost01:/etc/salt/cloud.providers.d# salt-cloud --list-providers 
[WARNING ] The profile 'proxmox-debian' is defining 'proxmox' as the provider. Since there's no valid configuration for that provider, the profile will be removed from the available listing
[INFO    ] salt-cloud starting
[WARNING ] The cloud driver, 'proxmox', configured under the 'my-proxmox-config' cloud provider alias was not loaded since 'proxmox.get_configured_provider()' could not be found. Removing it from the available providers list
Error: There was an error listing providers: There are no cloud providers configured.
```

I could do nothing, i can't create VM. I've install salt-cloud from a build package create from branch 2014.7. I've check if there is proxmox.py:
```
root@edge-dev-hvmhost01:/etc/salt/cloud.providers.d# find / -name proxmox.py
/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py

root@edge-dev-hvmhost01:/etc/salt/cloud.providers.d# cat /usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py | grep 2014
.. versionadded:: 2014.7.0
```

So what is the problem ?

**Comment by vtomasr5** [comment]
I've the same problem. I defined the profile and the provider as follows and I get the same result.

provider:
```
proxmox-config:
    user: root@pam
    password: password
    url: 192.168.13.10
    provider: proxmox
```
profile:
```
proxmox-debian:
    provider: proxmox
    image: local:vztmpl/debian-7.0-x86_64.tar.gz
    technology: openvz
    host: debian7
    ip_address: 192.168.13.20
    password: password
    cpus: 2
    memory: 1024
    swap: 512
    disk: 10
    nameserver: 8.8.8.8 8.8.4.4
```

```
$ sudo salt-cloud -p proxmox-debian debian7test
[WARNING ] The profile 'proxmox-debian' is defining 'proxmox' as the provider. Since there's no valid configuration for that provider, the profile will be removed from the available listing
[INFO    ] salt-cloud starting
[ERROR   ] Profile proxmox-debian is not defined
Error:
    Profile proxmox-debian is not defined
```

versions:
```
            Salt: 2014.7.0
          Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
          Jinja2: 2.6
        M2Crypto: 0.21.1
  msgpack-python: 0.1.10
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 13.1.0
            RAET: Not Installed
             ZMQ: 3.2.3
            Mako: 0.7.0
 Apache Libcloud: Not Installed
```

I've installed the latest versions of IPy and requests.

**Comment by vtomasr5** [comment]
That works well though.
```
$ sudo salt-cloud --list-images proxmox-config
```

**Comment by vtomasr5** [comment]
Any news about this?

**Comment by vtomasr5** [comment]
With debug option:
"""
$ sudo salt-cloud -p proxmox-debian mydebian -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.scip.local
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/proxmox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/proxmox.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/proxmox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/proxmox.conf
[WARNING ] The profile 'proxmox-debian' is defining 'proxmox' as the provider. Since there's no valid configuration for that provider, the profile will be removed from the available listing
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[ERROR   ] Profile proxmox-debian is not defined
Error:
    Profile proxmox-debian is not defined
"""

**Comment by pguay** [comment]
I know it's been mentionned before but i had the same problem. It just needed the right packages :

sudo apt-get install python-ipy

It now works like a charm!

**Comment by techhat** [comment]
It looks like ipy is documented in the docstring as a dependency for proxmox, so that would make sense. @vtomasr5, do you have python-ipy installed?

It looks like the dependencies are not documented in `doc/topics/cloud/proxmox.rst` as they should be.

**Comment by vtomasr5** [comment]
Yes, I've installed the package python-ipy and python-requests. I've even tried the lastest version installed via pip. But it didn't work for me.

**Comment by niq000** [comment]
@vtomasr5 try changing "provider: proxmox" in your profile to "provider: proxmox-config"

**Comment by vtomasr5** [comment]
Sorry for taking so long.

It kinda worked, but I'm having other little problems:
```
[ERROR   ] Error creating debiantest on PROXMOX

The following exception was thrown when trying to run the initial deployment:
500 Server Error: proxy loop detected
Error: There was a profile error: Failed to deploy VM
```

**Comment by rallytime** [comment]
I think the original issue here is actually resolved by knowing that the python-ipy package is required, so I am going to close this issue for now, since the docs have been updated.

@vtomasr5 If you are still having problems, please feel free to open a new issue. 

Thanks all!
