### ISSUE TITLE
2014.1.10 Zombie Processes

### ISSUE THREAD

**Issue by jessecollier** [saltstack/salt#14836]
Pretty much the same as https://github.com/saltstack/salt/issues/10867

```
~$ salt-minion --versions-report
           Salt: 2014.1.10
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```

```
root     14947 29.0  0.4 466384 36132 ?        Ssl  20:37   0:00   /usr/bin/python /usr/bin/salt-minion
root     15012  0.0  0.0      0     0 ?        Z    20:37   0:00     [salt-minion] <defunct>
root     15013  0.0  0.0      0     0 ?        Z    20:37   0:00     [salt-minion] <defunct>
root     15014  0.0  0.0      0     0 ?        Z    20:37   0:00     [salt-minion] <defunct>
```

**Comment by jhgg** [comment]
Seeing this on Ubuntu 14.04 using 2014.7.0 as well:

```
~$ salt-minion --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

```3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux```

```Ubuntu 14.04.1 LTS```

**Comment by cachedout** [comment]
@jhgg Can you pin down which operations on the minion cause the zombies? Is it a highstate, a particular single state, or a module call? It's tough to diagnose these without narrowing things down some.

**Comment by jhgg** [comment]
Hmm, 

I think it had something to do with the bootstrap script. It looks like it installs it to init.d and upstart, so two different salt-minions were running. I'm doing some more testing and diagnosis. I was meaning to file a bug report for that as well. It looks like on the servers where I had salt-minion start from init.d instead of upstart, I'm not seeing anymore zombies. But only time will tell...

**Comment by cachedout** [comment]
Ahh, OK. That's actually the second time I've heard that problem mentioned this morning so I'll see if we can figure out what's happening with bootstrap. Nice catch!

**Comment by jhgg** [comment]
Yeah, running two salt-minions at the same time seems to cause a lot of havoc. I've seen a lot of weird issues stem from it, like, the server hangs on shutdown because it can't terminate the zombie processes, salt-master intermittently returning duplicated results for minions, the login shell (this is the weirdest one) appearing/disappearing. 

The login shell is a really weird one, I use XenServer 6.2 for a lot of server deploys and when freshly installing a salt minion, I will use the console functionality and I'll login (you know, on this screen)

![image](https://cloud.githubusercontent.com/assets/5489149/5820290/189ceb6e-a092-11e4-8361-2def07c2e15c.png)

And right after I enter the credentials and log in and am dropped into bash, the login prompt will come up again. But... I'll be in bash AND in the login shell at the same time. It's really obscure. It stops happening once I ssh in and kill salt-minion though. And it seems to only happen when more than one salt-minion is running.

**Comment by ssgward** [comment]
@ev0rtex - is this still an issue with the latest salt? If not an issue, can this be closed?
