### ISSUE TITLE
unnecessary dependency for 2014.1.10 salt-common package for ubuntu 10 and 12

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#15200]
Hi,

salt-common 2014.1.10 packages for lucid and precise that can be found here http://ppa.launchpad.net/saltstack/salt/ubuntu/pool/main/s/salt/ have python-requests dependency, which is not necessary for salt-minion. Official ubuntu repository contains outdated python-requests package, which overriden python-requests installed via pip. Because of this installation of salt-minion caused issues for applications, that were using newer version of python-requests. Since python-requests is used only by salt-master would it be possible to remove this dependency from salt-common package and add it to salt-master instead?

Thanks,
Kirill.

**Comment by rallytime** [comment]
Since the 2014.1 branch is no longer in active development and we won't be packaging anything there again, is this issue ok to close? Another thing to note, in regards to all of the `requests` discussion, the hard dependency on requests is being removed in the upcoming 2015.2.0 release. The only releases that have `requests` as a dep are the 2014.7.x packages.

**Comment by dlindquist** [comment]
Hmm, I took a look at 2015.2 branch.  Unless I'm missing something, it looks like the python-requests system package is still listed as a required dependency:
https://github.com/saltstack/salt/blob/2015.2/debian/control

**Comment by basepi** [comment]
That particular document has not yet been updated, I think, with the new requirements (or lack thereof).

**Comment by rallytime** [comment]
I've updated the document in the pull request above. Thanks all!
