### ISSUE TITLE
Support upgrading Ruby Gems in place

### ISSUE THREAD

**Issue by cmeisinger** [saltstack/salt#15325]
Currently, if you have a gem of version .7 and you try to update it via salt to say .8, you end up with multiple versions, one activated and one not.

As an example, I deploy passenger via salt.  If I want to upgrade passenger, I have to first run a `salt \* cmd.run 'gem uninstall passenger` and THEN I can highstate everything to start the build.

Ideally, when gem.installed sees a version mismatch, it will uninstall the existing version and install the required version.  If no version is specified, no action taken.

**Comment by kmwhite** [comment]
So, this does play well enough with the ruby paradigm for gems (typically, multiple versions of gems can be installed, but are pinned to versions in `Gemfile.lock`, similar to best practices with `pip` and `requirements.txt`), but can be confusing when maintaining disposable systems.

I'd be happy to take a stab at fixing this, if wanted. I was thinking an argument to the state of `uninstall_old_versions`, rather than enforcing the behavior all the time...

**Comment by job** [comment]
A `uninstall_old_versions` argument sounds good and useful to me.
