### ISSUE TITLE
Add Salt Cloud syntax checker

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#15836]
We need to provide some way to check the syntax on Salt Cloud config files; check YAML validity, warn if old options are being used, warn if invalid options are being used, etc.

**Comment by johanek** [comment]
It would be really great to have salt.loader.states return info about the state functions, with inspect.getargspec I'm going to have to make a lot of workarounds to things like this: https://github.com/johanek/salt/commit/e9a757e072ab4d33a7e6da5ca3a3291797077527

Also, I started trying to write tests, but hit a problem straight away because my module calls __salt__['state.show_sls'] and __salt__ isn't defined when trying to call it during the test runner.

**Comment by whiteinge** [comment]
This missing grains -> states thing has me stumped. I'm going to escalate this at the Salt office tomorrow. I'll let you know what I find out. :-P

**Comment by whiteinge** [comment]
@johanek sorry I missed you on IRC, I was at lunch. I got a sanity-check here at the office yesterday. Going to take another stab at this today...soon as I can scrape together a few minutes to try. :-P

**Comment by whiteinge** [comment]
@johanek thanks for the ping on IRC. I'm on sporadically throughout the day. Feel free to ping me whenever you jump on; it's not a bother at all.

I found the missing piece! Behold:

```python
>>> import salt
>>> import salt.config
>>> import salt.loader
>>> __opts__ = salt.config.minion_config('/etc/salt/minion')
>>> __grains__ = salt.loader.grains(__opts__)
>>> __salt__ = salt.loader.minion_mods(__opts__)
>>> 'pkg.install' in __salt__
False
>>> __opts__['grains'] = __grains__
>>> __salt__ = salt.loader.minion_mods(__opts__)
>>> 'pkg.install' in __salt__
True
```

I will get this added to the docs.

**Comment by whiteinge** [comment]
#20365

**Comment by johanek** [comment]
Thanks for the update @whiteinge - when I get some time I'm going to have another look at this!

**Comment by johanek** [comment]
I've updated my lint module to use the updated code you pasted, and that seems to be working. It's definitely solved the problem with alternatives.set vs alternatives.set_ that I highlighted previously, but I'm still having to work around a couple of things:

- pkgrepo.managed and pkgrepo.absent not defined
- rabbitmq_plugin, rabbitmq_vhost and rabbitmq_user not defined
- reload argument not available in service.running

There could be more things like that, but that's all the errors I've identified with the states that I'm using.


Also, now that I'm using salt.utils.argspec_report rather than inspect.getargspec I'm getting errors for states that include pillar data

```
    Rendering SLS 'base:ssh' failed: Jinja variable 'dict object' has no attribute 'ssh'
```

Doing some debugging, it seems like the `__pillar__` dict is available right up to when I call `__salt__['state.show_sls']` at https://github.com/johanek/salt/blob/lint/salt/modules/lint.py#L130 - afterwards it's empty. 

I guess this is because of the use of `__salt__` and `salt.loader` in the `_getschema` function - but I don't really understand why. Do you have any pointers here? Is calling `__salt__['show_sls']` the best way to approach the rendering of the state or is there a better alternative? Doing this has caused problems with trying to run tests as I mentioned in an earlier comment.
