### ISSUE TITLE
exception on master when trying to publish to a node group

### ISSUE THREAD

**Issue by alex-solidfire** [saltstack/salt#15946]
Hi,

I have defined a node group in my master file which I can use ok from the master.

I have peer enabled and I'm able to publish commands between minions via this master as well.

What I am not able to do, is publish a peer command to a node group.

Here is the command I am trying to run:
`salt-call publish.publish boulderqds cmd.run 'grep 874521 /var/log/syslog'`

Here is the exception I am seeing on the master
2014-09-18 21:57:04,796 [salt.master      ][ERROR   ] Error in function minion_pub:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1701, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1591, in minion_pub
    jid_fn = os.path.join(auth_cache, ret['jid'])
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'int' object has no attribute 'startswith'

**Comment by boltronics** [comment]
Confirming I'm seeing this exception in my master log file quite a lot too.
```
           Salt: 2014.1.13-3-gb325b92
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```
Identical versions on master and minion everywhere.

**Comment by cro** [comment]
@alex-solidfire -- We are looking through old issues and trying to clean things up a little. Do you still see this behavior in the latest 2015.5 releases? Thanks.

**Comment by alex-solidfire** [comment]
Sorry for the delay @cro , yes I can confirm that I still see this on 2015.8.0rc2.

```
root@zdc-minion:/etc/salt/cloud.providers.d# salt-call --version
salt-call 2015.8.0rc2 (Beryllium)
root@zdc-minion:/etc/salt/cloud.providers.d# salt-call publish.publish minion_group cmd.run 'hostname'
[INFO    ] Publishing 'cmd.run' to tcp://192.168.0.100:4506
local:
    None
```

**Comment by The-Loeki** [comment]
This problem still exists on 2015.8.

I've no idea about the stack trace though, mine is rather different:

```
2016-04-14 15:32:02,115 [salt.utils.minions][ERROR   ][22072] Failed matching available minions with nodegroup pattern: glrun
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 627, in check_minions
    minions = check_func(expr, greedy)
TypeError: 'NoneType' object is not callable
```

Which makes total sense considering `check_minions` doesn't *do* nodegroups.

That makes this closely related to https://github.com/saltstack/salt/issues/12580 and https://github.com/saltstack/salt/issues/6602. 

It's also majorly inconvenient considering the minions need to know the exact match used in order to get usable results.

Considering nodegroups are basically compound match 'shortcuts', what's the problem in just looking up that shortcut and translate the nodegroup name to it before passing on in `check_minions`? 
That approach might clear up a lot of nodegroup related problems seemingly rather easy?
