### ISSUE TITLE
Include minion IP in auth event data

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#16251]
It would be useful to have the minion IP address included with auth events. A use case for this is EC2 autoscaling. A reactor would call a runner, which would do a boto lookup on the IP, the name and the autoscaling group to ensure the key in question matches the node that should be generating it. Without the IP it's basically impossible to securely sign a key without SSHing into the node.

**Comment by andrejohansson** [comment]
I would very much like this feature too, and my cents are not regarding a security feature but for finding errors. 

I would say there is a case for both internal and external ip to be included. I'm right now trying to trace a minion gone rouge within our internal network (our master is in azure). So from the master in azure I can only see that one of our internal minions are spamming me with auth requests (they all have same external ip from the masters point of view).

In the normal case I could identify them with the minion id. But due to my failed attempt to auto update the salt minion on windows, all minions got the same id. So no luck there. 

Sidetrack: why is it allowed to have two minions with same id? Feels like salt breaks down if you happen to startup two minions with same id and key (which could easily happen if you clone a virtual machine).
