### ISSUE TITLE
file.absent - Failed to remove directory if the directory have to much files in it

### ISSUE THREAD

**Issue by myg0v** [saltstack/salt#16289]
Minion OS: Windows Server 2008 R2
Master OS: CentOS 6
Salt-Version: 2014.1.10

file.absent is not working if the directory have too much files (11233 files) and directories (2392 directories) in it.

```
win:
          ID: delete_directory
    Function: file.absent
        Name: C:/test
      Result: False
     Comment: Failed to remove directory C:/test
     Changes:   
```

If I use the following cmd.run function, the deletion process is working fine:

rmdir "C:/test" /s /q

**Comment by twangboy** [comment]
@myg0v I have been able to successfully remove a directory on windows in both 2015.5 and 2015.8 versions of salt. I had a directory containing 24,576 Files and 12,290 Directories. I ran file.absent and the folder deleted successfully.

I was able to reproduce your error in two ways:
1. Open one of the files in an editor that creates a lock. (I used VIM)
2. Open a cmd prompt in one of the directories

If this was a problem in Salt 2014.1.10 it has been fixed in current versions.
