### ISSUE TITLE
wrong disk.usage reported for very big RAID disk

### ISSUE THREAD

**Issue by o1e9** [saltstack/salt#16508]
Hi,

I am running 2014.1.10 on both server and client (Windows Storage Server 2008 R2).  'disk.usage' runner, it seems is using 32bit int variables to report 1K blocks so the result for 28Gb filesystem would be:

```
# salt nasserver disk.usage

D:\:
        ----------
        1K-blocks:   
            -5184028680192
        available:   
            4890295828480
        capacity:
            194%
        filesystem:  
            D:\
        used:
            -10074324508672
```

It seems to me that 64bit values need to be used to report disk usage.

Cheers,
Oleg

**Comment by ozej8y** [comment]
Hi Everyone,

I have been working on some scripts to report on disk.usage from a Windows VM. 
I have just discovered this bug. :(

Any updates on this bug fix ?

I am using the latest and greatest versions of salt-master and salt-minion.

**Comment by davidjb** [comment]
Just created a PR here: #22485

This issue comes from the usage of GetDiskFreeSpace -- this (method)[https://msdn.microsoft.com/en-us/library/windows/desktop/aa364935%28v=vs.85%29.aspx] returns LPDWORDs, pointers to 32-bit unsigned ints which is why this method is reporting incorrect values for larger disks.   The solution is to use (GetDiskFreeSpaceEx)[https://msdn.microsoft.com/en-us/library/windows/desktop/aa364937%28v=vs.85%29.aspx] which returns large integers.  This method also has the added bonus of avoiding to perform manual calculations with sector sizes and the like.

These are the values reported by the library when called against a 20 TB (terrabyte, not a typo) NTFS disk on Windows Server 2012:

```
>>> win32api.GetDiskFreeSpace('D:')
(16, 512, -1624837516, -1610629377)
>>> win32api.GetDiskFreeSpaceEx('D:')
(21873703157760L, 21990096232448L, 21873703157760L)
```
The first is clearly wrong, with negative short integers, but the second is correct.

**Comment by davidjb** [comment]
Reading more into this, these figures of capacity are only what the *executing user* has access to.  The salt minion will be run as a service, and runs using the local system account, but I don't know what effect that has if disk quotaing is enabled -- eg whether the figures reported will be the entire disk as available space or not I don't know.  Similarly, if there was a situation where someone might change the salt-minion service to run using a less-privileged account, this could affect the figures reported too.  

My thinking is that it's good enough, but just a heads up in case this ever comes up in the future.
