### ISSUE TITLE
salt-cp fails with large files, cp.get_file succeeds 

### ISSUE THREAD

**Issue by spo0nman** [saltstack/salt#16592]
salt-cp of files larger than 1MB fails no matter how big a --timeout value is used. The minion never gets a job/jid, small files copy just fine. 

On the same host and minion combination salt 'minion' cp.get_file salt://file /tmp/file succeeds. 

```
$ sudo  salt-call test.versions_report
```

local:
               Salt: 2014.1.11
             Python: 2.7.8 (default, Oct  2 2014, 17:06:07)
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.11
              PyZMQ: 14.3.1
                ZMQ: 4.0.4

**Comment by arthurlogilab** [comment]
hey, we get this bug too and we're interested in this bugfix too.

**Comment by cchriste** [comment]
Perhaps the documentation can be updated to reflect the current limitation. Google only brought me here after time-wasting frustration.

**Comment by zerthimon** [comment]
Can we expect salt-cp fixed any time soon ?

**Comment by DanielYWoo** [comment]
I have the same problem, hopefully we can get it fixed soon.

**Comment by pardoc** [comment]
This is totally also blocking Windows package management (relying on salt-cp); installers aren't copied anymore and the job is stuck.

**Comment by ajbothe** [comment]
Any updates on this?

**Comment by mohamadashi** [comment]
any update on this guys?

**Comment by cconrad** [comment]
+1

**Comment by ajbothe** [comment]
I have found that cp.get_file is a good work around. Just setup a symlink in the salt files directory to whatever files you want copied. When you're done, unlink it if you don't need it any more.

**Comment by rickh563** [comment]
ZD-1399

**Comment by terminalmage** [comment]
The reason this is failing is that it is hitting [max_event_size](https://docs.saltstack.com/en/latest/ref/configuration/master.html#std:conf_master-max_event_size). This config option has only been tunable since 2014.7.0 and was hard-coded as 1MB before that.

The solution here is to do the following:

1. Modify salt-cp so that it does not attempt to send an event in excess of max_event_size. This will involve adding an additional parameter for all chunks of a file after the first one, to signify that this data should be appended to the file on the minion rather than writing a new file.

2. Modify [cp.recv](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.recv) to accept and understand this new parameter, and conditionally open the destination file for appending rather than writing.

**Comment by UtahDave** [comment]
I wouldn't mind seeing `salt-cp` deprecated.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/41216.

**Comment by cachedout** [comment]
Nicely done, @terminalmage
