### ISSUE TITLE
salt-cloud configs: allow for dynamic data

### ISSUE THREAD

**Issue by craig5** [saltstack/salt#16850]
The salt-cloud configs are just static files. There is a fair amount of overlap in the data in those files with other things. (Eg. the AWS keys are needed in those files and in the salt configs.)

In our case, even just the list of providers is used elsewhere. (In both states and pillars.)

I would like some way to dynamically generate the salt cloud configs. Jinja would go along way. But, being able to write python code to generate the providers and/or profiles would be great.

Another use case is being able to check in the configs. I am working on getting all of our files stored in an SCM. Checking in the AWS keys is not a good idea. Currently, we are encrypting part of our pillars and then decrypting post-checkout. We would like to move to the GPG renderer. This is just another example of where I need to dynamically render the data in the config.

Happy to provide more details/thoughts.

**Comment by gladiatr72** [comment]
I adapted this pillar (https://github.com/saltstack/salt-contrib/blob/master/pillars/lookup.py) to accommodate gpg encrypted data within the pillar system.  Rather than processing a tagged value for the purpose of executing a function, it uses that tag as an index to decrypt a GPG encrypted file somewhere (the version I put together just had them stored on disk).  That model maintains the structure of the pillar data and allows for bits to be encrypted that need to be encrypted.

It looks like the SDB keyring module does pretty much the same thing and then there's the inline version that @steverweber showed.  Regardless of the process at this level, I think one of the unmentioned parts is how such a mechanism would safely propagate sensitive data elements to syndics or parallel masters.

**Comment by gladiatr72** [comment]
I would like to see the pillar cloud:* be supported in the same fashion as the on-disk configuration when it comes to the salt-cloud CLI.  A salt-cloud system is almost always going to run a salt-minion.  If there is a reason why the salt-cloud CLI couldn't spin up a local client to check for/retrieve such data, I'd love to talk about it.  

@tehmaspc extends only works with on-disk configuration.  I actually spent a couple days building an external pillar to support the _extends_ directive because purposefully creating duplicate pillar data in such quantities made me want to cut myself.

I'm working with a model that would have a cloud controller that could be quickly deployed to a particular provider/location that would only have access to the (salt)provider/profile elements relevant to that provider and/or location, so propagation of such data by way of pillar is very appealing.

**Comment by techhat** [comment]
@gladiatr72, most of our users use Salt Cloud on the master, not on a minion. The biggest reason is that Salt Cloud is designed to auto create and accept keys, which it can't do from a minion.

If you have a secure method for auto-transferring keys from an arbitrary minion to the master, it would go a long way here.

**Comment by steverweber** [comment]
I'll be one of them that will always manage the cloud through a minion,

i use the /master/minions_autosign dir.... its kinda cheating but I trust minions with a know name that come knocking at the door within 30mins... I create some nice states for managing the autosign files.

Its kinda like telling your wife that a repairman will be coming to the house soon and his name is joe... but.. if someone hijacked that phone call 'joe' might come nocking at the door before joe.  good thing that call is AES encrypted... but the dhcp server that labels the mac address of joe might be snooped.

but just wait we have this deploy thing so we can setup a ssh key for the templates... this way we can have the cloud minion deploy the minion and grab the minion key... why cant the cloud minion not then pass that key to the master or a minion running on the master... seems possible to me... perhaps i'll wire that up in a few months. /when i got the time.

**Comment by steverweber** [comment]
@gladiatr72  see https://github.com/saltstack/salt/blob/develop/salt/modules/nacl.py
its a nice module that can do that encrypted stuff vs that hacky openssl stuff.

**Comment by techhat** [comment]
Good stuff @steverweber. You know, now that we have beacons, maybe we could use them to establish some sort of trust between the master and specific minions. This is a very recent addition that we didn't have access to before.

**Comment by techhat** [comment]
Duh. We have access to the event system, which we've had for a long time. But we still need to decide on a secure way to establish trust.

**Comment by steverweber** [comment]
i figured the trust was already there AES... or is the event system not secure... can someone report a minion report a custom minion name in the event?

**Comment by steverweber** [comment]
anyway ill need to investigate this latter this year.

**Comment by techhat** [comment]
It's not a matter of whether the transport is secure (which I believe it to be), it's a matter of how much trust we assign and to whom.

**Comment by steverweber** [comment]
I trust my cloud minion. and the transport so all is well.

**Comment by techhat** [comment]
When Salt Cloud finishes spinning up a machine, it fires a `salt/cloud/<minion_id>/created` event. If you trust that event, you could build a reactor that accepts the key.

I think this issue has kind of veered from what was originally intended, but I think it has some great info.

**Comment by gladiatr72** [comment]
@steverweber Nice!   I still like the idea of not having to manage the hash data directly in the pillar data, though, so I might just incorporate that into my external pillar.  Regardless, good stuff!

@techhat, I was actually thinking about this--the amount of load that would be imparted on a master if it was responsible for doing masterly things as well as spinning cloud minions up and down (in any great number) could be prohibitive.  I do understand the convenience factor behind generating a new minion's key on the salt-cloud system that kicks it off; however, the salt-cloud minion (being a minion and all) could just as easily be instructed to send a key-acquisition event to its master that would then carry out the key creation.  The key would then be pushed to the salt-cloud instance for installation during the salt bootstrap.  Since the key would be generated on the master, trust would not be an issue.  Any tampering, upstream of the master, would just mean that the affected minion(s) would be unable to auth properly.

As far as trust in the cloud minion, I have to say that I don't much trust the providers (technically, not ethically)  Blocks of ESB aren't exactly zero'd out when an EC2 instance is brought down, ya know?

**Comment by tehmaspc** [comment]
@gladiatr72 - FWIW, I've got my salt-cloud on my salt-master server which also runs a minion because I have my entire salt-master configs under salt control.

We have gotten to the point where we have so many cloud.map and cloud.profile files that we are now probably going to create a separate salt-cloud formula that will still get applied to our salt-master host but we will do some templating or something to better manage and lay down our cloud.map/profile files.

I don't have a need or desire at this time to have my salt-cloud setup separate from my salt-master setup for some of the reasons @techhat mentioned.

**Comment by cetanu** [comment]
I can't really tell, but was this ever figured out?

I'm currently trying to use pillar via salt-cloud.

From what I read it can only be accessed via `salt.modules.cloud` which is super inconvenient. It doesn't extend profiles, so I wrote something which pre-extends my profiles, but this still doesn't work as `salt.modules.cloud.profile` complains about one of my arguments being a bool, when they are both clearly strings (profile, names)

At this point the only choice I have left is to write another tool which takes my map files, and does lookups on my pre-extended profiles, so that I can fillout the map with all information from every profile, meanwhile leaving a minimal profile in my on-disk config.

There has to be a better way to do this???

**Comment by dharmab** [comment]
You can write Pillar files in Python. Our VMware Salt Cloud configuration looks something like this:

```python
#!py|gpg

def run():
    return {
        'cloud': {
            'providers': providers(),
            'profiles': profiles()
        }
    }

def providers():
    # Code which generates and returns providers

def profiles():
    # Code which generates and returns profiles
```

You could potentially use this to generate configuration dynamically. I'd be concerned about Pillar rendering performance, though.

**Comment by cetanu** [comment]
That's really interesting. I'll try that out.  Performance isn't too much of an issue for me for this.

**Comment by NagarajGond** [comment]
@dharmab Your solution looks great. Still wondering where to keep the python file? Should I keep it under pillar directory? 
And is to possible to get only provider details from pillar files and profiles from .conf file?

**Comment by dharmab** [comment]
@NagarajGond We have a state using `file.serialize` to write the salt cloud configs to disk.
