### ISSUE TITLE
Make documentation mandatory on config-options

### ISSUE THREAD

**Issue by felskrone** [saltstack/salt#16869]
Looking back i am sort of blaming myself here, buts its for the best :-)

Too many options for tweaking things are not yet (fully) documented. Some are documented in the config files, but not in the docs.

Just a few examples i stumbled upon while tweaking things on my minions.

Minion:
```yaml
auth_tries
auth_timeout
rejected_retry
master_alive_interval
```
These are just the ones that i use that have no documentation in the minion docs:

https://github.com/saltstack/salt/blob/develop/doc/ref/configuration/minion.rst

I think it would be great, that if people setup pull requests that change/add config settings, also have to add matching documentation commits. Yes, its a pain sometimes, especially the formatting and having to rebuild the docs after changes. But the options above are useful for everyone and really should be in the official docs. 

Also telling users (on IRC, etc.) that they have to use undocumented for their problems does not reflect very well to salt in general.

I dont know if thats feasible or if it will scare too many great contributors away. I just wanted to propose it once and see what you think.

**Comment by bechtoldt** [comment]
Why not automating it? Wouldn't it be possible to grep for something like ``opts.[A-Za-z0-9_]`` or similar?

References like the config options or those in #20039 are _IMPORTANT_ for the users. Seriously, there are a lot of config options, state and execution modules (https://github.com/saltstack/salt/pull/20039/files) that don't appear in the references. 

I know many Salt beginners that have problems with incomplete documentation.

**Comment by rallytime** [comment]
Hi guys - I have created a list of all of the minion and master config options that are missing from the `*.rst` docs and have started going through that list to get everything documented. (I opened up that issue before I knew this one was here.)

As part of completing that issue, we also have tasks to add tests to look for including docs for new config options.

Since #32400 has a more extensive list of config options that needed to be documented, I am going to close this issue in favor of the other one so we can keep track of all of this in one place. Thanks!
