### ISSUE TITLE
win_path state needs a update_minion attribute

### ISSUE THREAD

**Issue by myg0v** [saltstack/salt#17062]
Salt-version: salt 2014.1.10 (Hydrogen)
OS: Windows Server 2008 R2

I think the win_path state needs an "update_minion" attribute (like environ.setenv) to apply the PATH-environment changes to the salt-minion process.

Because if you add something to the PATH environment variable and you want this new value available in the same salt state.

Here is a good example to illustrate the problem:

````
set_path:
  win_path.exists:
    - name: 'C:\tmp\Tools\Java\jdk1.6.0_35\bin'

test_output:
  cmd.run:
    - name: java -version
````

Output:
````

          ID: set_path
    Function: win_path.exists
        Name: C:\tmp\Tools\Java\jdk1.6.0_35\bin
      Result: True
     Comment: 
     Changes:   
              ----------
              added:
                  C:\tmp\Tools\Java\jdk1.6.0_35\bin was added at index 7

          ID: test_output
    Function: cmd.run
        Name: java -version
      Result: False
     Comment: Command "java -version" run
     Changes:   
              ----------
              pid:
                  1592
              retcode:
                  1
              stderr:
                  Command "java" not found or wrong written
              stdout:
````

If you reboot now the system or restart salt minion, the new PATH value is available for the minion and you receive the following correct result:

````
          ID: set_path
    Function: win_path.exists
        Name: C:\tmp\Tools\Java\jdk1.6.0_35\bin
      Result: True
     Comment: C:\tmp\Tools\Java\jdk1.6.0_35\bin is already present in the PATH at the right location
     Changes:   

          ID: test_output
    Function: cmd.run
        Name: java -version
      Result: True
     Comment: Command "java -version" run
     Changes:   

              pid:
                  12
              retcode:
                  0
              stderr:
                  java version "1.6.0_35"
                  Java(TM) SE Runtime Environment (build 1.6.0_35-b10)
                  Java HotSpot(TM) 64-Bit Server VM (build 20.10-b01, mixed mode)
              stdout:
                  
````

**Comment by deuscapturus** [comment]
Has anybody figured out how to do this?  Even a workaround would be nice.

**Comment by deuscapturus** [comment]
When enviroment enviroment variables are updated by states those enviroment changes are not known by the salt-minion.exe or salt-call.exe and are therefore not inherited by any subsequent states.

When the new path is added to the windows registry, salt is broadcasting the change with WM_SETTINGCHANGE.  This makes the new path variable available to application running in explorer like salt-call.exe, but not salt-minion.  This is why the new path is available when locally running salt-call after closing then reopening the shell, but must reboot to make them available to salt-minion.exe (executed from the master) 

This explains why this is more difficult in Windows https://msdn.microsoft.com/en-us/library/windows/desktop/ms682009%28v=vs.85%29.aspx

salt-call.exe and salt-minion.exe need to update their own path variable [here](https://github.com/saltstack/salt/blob/30faaaf9e542ef3c579f7703a4fbaa1864d8f8e9/salt/modules/win_path.py#L133) (without shelling out!) with os.environ

#### Here's an example

tests.sls
```
include:
  - tests.code

#update paths without shelling out
show_paths:
  cmd.run:
    - name: echo %PATH%
    - order: last
```

code.sls
```
#!py

def run():
  import os
  path = "c:\some\path"
  if path not in os.environ["PATH"].split(os.pathsep):
    os.environ["PATH"] += os.pathsep + path
```

Note:  There is some weirdness with this method depending on the content of the path string.  See what happens when you try adding the path "c:\try\a\this\a\path".

**Comment by deuscapturus** [comment]
This might work http://fpaste.org/186724/20467314/

I don't have a Windows build environment of Salt, so I cannot test this.  Could somebody else take it from here?

**Comment by deuscapturus** [comment]
Tested this.  The weirdness I spoke of in my earlier post only happens when executing from an sls file as in my example.  I added the below code to https://github.com/saltstack/salt/blob/develop/salt/states/win_path.py to add this feature.  I think a lot of rewrite work will be needed to implement it properly.

I'm still hoping that somebody better than I will take over from here.

```
    import os
    localPath = os.environ["PATH"].split(os.pathsep)
    if path not in localPath:
      localPath.insert(0, path)
      os.environ["PATH"] = os.pathsep.join(localPath)
```

**Comment by obestwalter** [comment]
@jfindlay just following up on this: Is this resolved in 2015.5.3?

**Comment by jfindlay** [comment]
@obestwalter, I don't think so.  The best person to talk to about this would be @twangboy.

**Comment by twangboy** [comment]
@obestwalter @deuscapturus Not sure if this is possible. It looks like the salt-minion service inherits its environment from the services.exe process. Services.exe receives its environment settings when windows starts. Services.exe apparently ignores WM_SETTINGCHANGE broadcasts.
Might be something in here (https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653(v=vs.85).aspx) that we could use to modify the environment for the salt-minion service.
See: https://support.microsoft.com/en-us/kb/821761

**Comment by twangboy** [comment]
@obestwalter @deuscapturus Changing the environment for the salt-minion service using a module or a state is going to be impossible. Salt spawns a new instance to run these and any environment changes are lost once the function finishes.

However, there may be another option that will do what you need it to. The following state will set the path and restart the minion, only if the path is changed:
```
set_path:
  win_path.exists:
    - name: C:\tmp\Tools\Java\jdk1.6.0_35\bin

restart_minion:
  service.running:
	- name: salt-minion
    - watch:
	  - win_path: set_path
```
Then, anything that requires java after this will have the correct path.

**Comment by obestwalter** [comment]
Sorry, if this is a dumb question, but I don't know much about the salt internals yet:

 If I do this as part of some big highstate: will the minion restart itself and then pick up the processing right at the "next" state?

**Comment by twangboy** [comment]
It will if you have it set up to do a highstate when the minion starts.
