### ISSUE TITLE
Salt minions time out

### ISSUE THREAD

**Issue by gigaroby** [saltstack/salt#17100]
Hi,
I am running a salt-master (2014.1.13) with about 20 minions on amazon aws (a couple of them are in another datacenter).
The master is at version 2014.1.13 and the minions are at versions ranging from 0.17.5 (which are running ubuntu 12.04) to 2014.1.13.
The problem is that most of the time more than half of the machines time out during execution of simple command like `salt 'sensu_enabled:True' test.ping`.
I attach a run of said command with `-l debug` but I can not see anything wrong with it.

```
root@saltmaster:~# salt -l debug -I 'sensu_enabled:True' test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] LocalClientEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LocalClientEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Loaded no_out as virtual quiet
[DEBUG   ] Loaded json_out as virtual json
[DEBUG   ] Loaded yaml_out as virtual yaml
[DEBUG   ] Loaded pprint_out as virtual pprint
machine1:
    True
... a few more like this first one
[DEBUG   ] Checking whether jid 20141103084048917026 is still running
[DEBUG   ] get_returns for jid 20141103084058939881 sent to set([<8 machines here>]) will timeout at 08:41:03
[INFO    ] jid 20141103084058939881 minions set([<4 machines here>]) did not return in time
```

Is anybody else having this issue? (also, is there a way to count how many machines have a specific pillar without relying on test.ping?)

Please let me know if I can provide additional details to help diagnose this.

**Comment by vad** [comment]
@basepi an update about this bug. We (I work with gigaroby) upgraded to `salt 2014.7.1 (Helium)` on a new machine and we still have timeouts.

A way we use to reproduce the bug is to create a new machine (with salt-cloud, but who cares) and run an highstate. After 10 seconds the client times out but the minion keeps running the highstate. At the end of the highstate, `salt-run jobs.lookup_jid <jid>` returns the correct result. Using the LocalClient:

```
client = salt.client.LocalClient()
ret = client.cmd(name, 'state.highstate')
```

`ret` is empty.

Is there something I can do to debug this problem? Tracing python code execution?

Our file_root is 60M, could that be a problem?

Thanks

**Comment by vad** [comment]
If i remove the .sls that loads a 60M jar, the `file_root` is just a few kB and the highstate runs fine.

Seems to be a problem with the sync of "large" `file_root`s.

**Comment by basepi** [comment]
@vad Interesting. I wonder if the large file sync is causing the minion to not respond to the `saltutil.find_job` query.
