### ISSUE TITLE
docker.create_container port binding documentation unclear

### ISSUE THREAD

**Issue by Anthonyhawkins** [saltstack/salt#17130]
The documentation and example on how to create a docker container and expose ports is documented very poorly.  Using the examples it's unclear how exactly port bindings should be passed.  

For example closest thing I was able to get to exposing 80:80 was running

salt '*' docker.create_container anthonyhawkins/lablocal:apache-test-2.4 name=test-apache-instance-1 ports=[80]

this leaves me with:

06c4296a6422        anthonyhawkins/lablocal:apache-test-2.4   /opt/httpd/bin/apach   23 minutes ago      Up 5 minutes        0.0.0.0:49154->80/tcp   test-apache-instance-1

What I'm looking to do is: 

06c4296a6422        anthonyhawkins/lablocal:apache-test-2.4   /opt/httpd/bin/apach   23 minutes ago      Up 5 minutes        0.0.0.0:80->80/tcp   test-apache-instance-1

**Comment by jacobhammons** [comment]
It appears that this was fixed since I see a reference to "port_bindings" in the docs at https://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html#available-functions

Either way, since the dockerio module is now deprecated in favor of dockerng, I'm going to close this since additional changes are not being made to dockerio.
