### ISSUE TITLE
Compound matching matches all minions that do not have a data.p cache file

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#17203]
It appears that using compound matching specifically with mine and publish functions that if the minion does not have a data.p file on the master, the compound will match all minions that both match the compound search and all minions that do not have a data.p file.

**Comment by deuscapturus** [comment]
@basepi I agree with the abort.  log an error and have the user fix the cache.  never return false positives or incomplete mine results.

**Comment by basepi** [comment]
Thanks for the input. I also think that's the right path.

**Comment by DanyC97** [comment]
@basepi @thatch45 was any agreement on this? i saw notes saying to document and not sure if that has been done, on which doc version and on which section.

**Comment by basepi** [comment]
I do not think there has been a final decision here, but thanks for the ping, we need to get this resolved even though most people won't run into it.

**Comment by clarkperkins** [comment]
I know I'm a little late here, but I've run into this issue quite often.  We have an automated system that uses salt-cloud to provision hosts and then uses the orchestrate runner to configure them.

The main reason we have this issue is when one set of hosts is still launching under salt-cloud when we're configuring another set of hosts at the same time - meaning the set of launching hosts doesn't yet have a data.p file, and they get matched when running state.orchestrate (using compound matching) on another set of hosts.

This may be something that should be fixed on the salt-cloud side of things (i.e. the pre-seeded minion keys don't get added to the master until the associated minion is up and running or something), but I figured I'd mention it here.

**Comment by basepi** [comment]
That's really good to know. I'm thinking if a minion has not yet checked in, and so doesn't have a data.p file, we should eliminate it from the match. I think it's the safest way to handle it.
