### ISSUE TITLE
grains & pillar: maybe we need some doc to burn in marber

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#18095]
I was used to use __grains__ inside exec module which were in turn used inside an ext_pillar module.

Until one month earlier, those grains used to resolve to the master __grains__, but are now resolving to the minion which is asking for it's pillar.

Is that the wanted behavior, or just the emergence of a new regression ?

**Comment by basepi** [comment]
I don't actually think this needs to be explicitly documented -- I think having minion grains in ext_pillar calls is intuitive, as that's how it works in normal pillar as well. The reason this caught you is because you came to rely on the behavior that was a bug.

Based on that, I'm going to close this issue. Please comment if you disagree.
