### ISSUE TITLE
Proxy Minion documentation missing grains example

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#18273]
http://docs.saltstack.com/en/latest/topics/topology/proxyminion/index.html

> To add more grains to your proxy minion for a particular device, create a file in salt/grains named [proxytype].py and place inside it the different functions that need to be run to collect the data you are interested in. Here's an example:

Then there is no example.

**Comment by kevinquinnyo** [comment]
Is there any update on this?

I am just familiarizing myself with salt / testing, and one of the first things I want to do is create a proxyminion to manage cisco switches.  That grains example is still missing.

Also does anyone know of an actual example of a user created proxyminion setup (not the juniper or rest api example since those actually come packaged with salt)?

Even after reading the [Proxyminion documentation](http://docs.saltstack.com/en/develop/topics/topology/proxyminion/index.html) several times, I still can't seem to figure out which files are supposed to be on the salt-master and which on the proxyminion.  It's probably because I'm still learning salt, and I know this is not an "out of the box" feature but some additional clarification sure would help me.

**Comment by rallytime** [comment]
@kevinquinnyo I am not very familiar with proxy minion, so I am not the best one to answer those questions. @cro will know, though. I don't think he was able to get around to this one yet, but I've added some extra labels to help us remember to come back to this one. Thanks for the bump!

**Comment by kevinquinnyo** [comment]
@rallytime Thanks!  @cro (and anyone else) I know the issue tracker is not for support / help, but if you can point me in the right direction I would appreciate it immensely.  I believe I do understand the concept here.  The proxytype connection class is essentially used as an 'adapter' class so that a dumb device, or some remote api, or anything really can be communicated with, but also adapt to the interface that salt expects when dealing with a traditional host.  I just can't figure out how to configure things / where to put things.  Thanks a lot if anyone can help.  Also if I can eventually figure out how to create a proxyminion + associated modules and friends that can do useful things with a Cisco device and it's robust enough, I'd be happy to PR it back to salt core.

**Comment by arthurlogilab** [comment]
I've recommended minion proxies to a few people and actually trying it out seems to indicate it's totally broken. Hoping for this situation to improve in the near future for a few use cases and so the people I recommended it to can use it.
