### ISSUE TITLE
RAET port documentation request

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#18309]
Please add RAET port description in following discussion thread.

https://groups.google.com/forum/?fromgroups=#!topic/salt-users/5HZoPc8gscs

**Comment by jryberg** [comment]
Hi,

Can still not find any information about RAET in the documentation (http://docs.saltstack.com/en/latest/topics/tutorials/firewall.html).

As I understand, it should be enough to only allow UDP 4510 salt master. Since it UDP it should be open from both directions. Is this the only requirement for running RAET?

Best regards Johan Ryberg

**Comment by rallytime** [comment]
@jryberg I don't think anyone has amended the docs about this issue yet, and I am not exactly sure what the port requirements should be. I think that sounds correct, but I'd like to confirm your question with either @cachedout or @thatch45 first.
