### ISSUE TITLE
2014.7: Failed to authenticate message logging flood

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#18359]
While debugging #18316 I noticed a log flood on the master:
```
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Failed to authenticate message
```

After restarting this is fine for some time but then it happens again and never seems to be ending.

**Comment by 7oku** [comment]
We are still getting this with 2014.7.0 (Helium) stable. We see this when running salt-master -l debug.

Using tcpdump/ngrep I can find the minion(s) causing this (you see a lot of packets from these specific machines). 

The packet flooding seems to be initiated by the salt-minions, each packet looks like this (encrypted?):
https://gist.github.com/7oku/a6520ebf0277cc4eeb8b

Restarting their salt-minion service helps. But it is a pain, to find them and restart their services everytime you need to have to debug salt-master.

We cannot bring the salt-minion to foreground for debugging, because once we restart them they work fine ... 

Any further hints on this?

**Comment by basepi** [comment]
Yep, the packets definitely should be encrypted, all salt communication is encrypted on the wire.

I would love some debug logs from a misbehaving minion if anyone can provide those.

**Comment by 7oku** [comment]
@basepi It turns out that this is not easy for us. We found it is a hanging state.highstate (with test=True, not sure if that matters), which is run by a python script. Attaching gdb with python to that process shows:

```
(gdb) py-bt
[... lots of private stuff ...]
    result = client.function('state.highstate', test=True)
(gdb) 
```

Going further into that shows:

```
(gdb) py-list
 991                if not data['data']:
 992                    if not fn_ and data['dest']:
 993                        # This is a 0 byte file on the master
 994                        with self._cache_loc(data['dest'], saltenv) as cache_dest:
 995                            dest = cache_dest
>996                            with salt.utils.fopen(cache_dest, 'wb+') as ofile:
 997                                ofile.write(data['data'])
 998                    if 'hsum' in data and d_tries < 3:
 999                        # Master has prompted a file verification, if the
1000                        # verification fails, re-download the file. Try 3 times
1001                        d_tries += 1
(gdb) 
```

Seems it's hanging at the cache! But that happens every day to 5-10 minions in our infrastructure - not always the same ones ... and also to minions just installed just the day before. Salting them works well without any issues, the automatic highstate is being run a lot of times and the next morning they are suddenly in that state.

So what's in cache_dest? Well, we are using the openssh formula and it seems to be writing the sshd_config ... and stops!

```
(gdb) py-print cache_dest
local 'cache_dest' = '/var/cache/salt/minion/files/base/openssh/files/sshd_config'
```

Not sure what this has to do with the message authentication fails, but if we kill all that processes on that minions, the flooding on the master disappears. I will report more as we find something out, any further hints for finding the issue are welcome.

**Comment by basepi** [comment]
It would be great if you could put a subset of your minions into debug log mode and then when this happens grab the log off of the misbehaving minion. Though this debug information you pulled is very useful, but I'm not sure what's going on here.

**Comment by tehmaspc** [comment]
FWIW,

I just came across this issue after performing recent upgrades to our Salt Master and the most recent being an upgrade to 2014.7.5.

Using the 'ngrep' tip above, specifically <code>ngrep -t '' 'tcp and port 4506'</code> on the Master I was able to find a Minion that was connecting to the Master in a bad way. The interesting thing was the from the Master this Minion was checking in fine and communicating. Getting on the Minion I discovered there were multiple instances of salt-minion running and the process connecting to the Master in a bad way must have been an old version that never exiting cleanly. Killing all the salt-minion pids and restarting and additionally restarting the Master stopped the Master from continuously spewing this log message: <code>'[DEBUG   ] Failed to authenticate message'</code>

**Comment by frogunder** [comment]
@syphernl, @kelchm, @7oku - Is this still an issue for you?

**Comment by 7oku** [comment]
@frogunder 

Well, this was about 3 versions ago, and I think that time we could workaround it by a cronjob restarting the master every night. However, we were not sure why restarting the master fixed that for a period of time.

Now, we are at salt 2015.8.3 (Beryllium), there are still some occurances of Failed authenticate messages in our logs, but no continous spamming of the master log any more. I assume this has somehow been fixed in the last upgrades, but I cannot name the commit. Maybe a change in zmq? 

Since this issue is specific to 2014.7, I suggest closing it.

**Comment by basepi** [comment]
In 2015.8 much of the transport layer was refactored, making it more pluggable. That's probably where this got fixed. Thanks for the update, @7oku
