### ISSUE TITLE
Salt 2014.7.0 Windows Minion Silent Install Error

### ISSUE THREAD

**Issue by findtopher** [saltstack/salt#18362]
Master: RHEL 6 running salt-master 2014.7.0
Slave: Windows 7 running salt-minion 2014.1.7 upgrading using Salt-Minion-2014.7.0-AMD64-Setup.exe retrieved on 11/19/2014

When we try to perform a silent install of the 2014.7.0 Salt-Minion on Windows systems inside our corporate firewall the installation never completes; running the installation manually results in a "Salt Minion v 2014.7.0 Setup" pop-up error "VC redist package download failed: resolving hostname".

Pre-installing Microsoft Visual C++ 2008 x64 SP1 redistributable (as suggested here http://docs.saltstack.com/en/latest/topics/installation/windows.html ) does not eliminate this pop-up error (screenshot attached).

![salt-2014 7 0-install-error](https://cloud.githubusercontent.com/assets/6401385/5143317/39d9564a-7154-11e4-8ef1-192219f5595b.png)

With about 150 Windows systems to upgrade this represents a pretty significant barrier for our move to 2014.7 - I was hoping that someone had a workaround or proposed solution for being able to perform a successful silent install.

We have confirmed that this same error occurs on a system with no salt-minion at all, so this is not specific to upgrades.

**Comment by lorengordon** [comment]
Did you happen to find a way to suppress this error? I'm having the same issue. I have a minion that is not connected to the Internet, I've installed vcredist separately, but I get the same error message popup, "VC redist package download failed: resolving hostname".

Verifying the issue is quite easy with a VM. I made sure vcredist was installed, disconnected the NIC, logged into the console session, and launched the salt installer. The popup error is generated regardless of whether the silent install option is used. Then the installer continues and does seem to install salt after all. Even with the silent install option, the install hangs on the popup and waits for user input.

-Loren
