### ISSUE TITLE
Install and run Salt within a virtualenv

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#18791]
Instead of providing system packages such as python-requests, python-gitdb etc. which replace system provided packages please include a virualenv for Salt with all required packages pinned. This should make it easier to support different distributions as only one packge will be provided for each distribution also it will not introduce the possibility of breakage due to updated system packages.

Rant on the subject: https://hynek.me/articles/python-deployment-anti-patterns/

**Comment by diepes** [comment]
Found this due to salt pip issue running salt 2018.3.2

Is there a recommended way to have a apt installed salt environment use a virtual environment in production ?

In my case most of the python pip modules installed is for use by salt for other states, docker, mongo, Maria, boto3 etc.

Changes to the python environment seem to regularly break our salt highstate.  (Multiple environments including developer Linux laptops)

**Comment by steverweber** [comment]
wish this was done... too many times I have had an issue with zeromq that this might have saved me from...
