### ISSUE TITLE
gitfs appears to not coordinate cache updates between salt-master workers

### ISSUE THREAD

**Issue by wt** [saltstack/salt#18875]
The git fileserver module does not appear to coordinate updates to the cache. By this, I mean that every worker seems to try to independently update the cache. This also appears to happen with the s3fs module.

**Comment by wt** [comment]
Here is proof that it's happening from more than one process:
# netstat -tp | grep s3
tcp        0      0 ip-x.ec2.inte:58283 s3-1-w.amazonaws.com:https  ESTABLISHED 6537/python         
tcp        0      0 ip-x.ec2.inte:44296 s3-1-w.amazonaws.com:https  ESTABLISHED 6523/python         
tcp        0      0 ip-x.ec2.inte:58334 s3-1-w.amazonaws.com:https  ESTABLISHED 6534/python         
tcp        0      0 ip-x.ec2.inte:58305 s3-1-w.amazonaws.com:https  ESTABLISHED 6535/python

Those processes are all master processes a few minutes a fresh restart. They are configured to use the s3fs filesystem backend.

Also, salt-minion highstating against this master are much slower.

**Comment by terminalmage** [comment]
A simple netstat command does not prove that the file cache is being re-downloaded by multiple worker threads. Again, this is *impossible*, due to how fileserver updates work.

A secondary inspection of the s3 fileserver backend reveals that the s3 metadata (a data structure including all files in the configured S3 buckets) is being retrieved in several of the functions which are used in serving files. This would appear to correlate with what you are seeing. These redundant queries can be eliminated using caching, in much the same way we have done for gitfs.

I'll update you once this has been done.

**Comment by wt** [comment]
Fair enough. Thanks for looking into the caching issue.
