### ISSUE TITLE
possible problems with locale.gen_locale

### ISSUE THREAD

**Issue by tomashavlas** [saltstack/salt#18936]
I think there are few problems in code for generating locale, especially in localemod.py on lines 205-210
```__salt__['file.replace'](
'/etc/locale.gen',
'# {0} '.format(locale),
'{0} '.format(locale),
append_if_not_found=True
)
```
first is the append_if_not_found=True, according to documentation function takes argument int format 'en_US.UTF-8', however /etc/locale.gen has locales listed in format like 'en_US.UTF-8 UTF-8', and appending incorrect format locale in file results invalid locale.gen file and generation of such locale fails

second problem (I may be wrong) is that match string and replace string have spaces at the end, however, when I have tried to run file.replace with such conditions (with salt 2014.7) result was incorrect, because the space was removed, example:
I run salt minion `file.replace '# en_US.UTF-8 ' 'en_US.UTF-8 '` on file containing line `# en_US.UTF-8 UTF-8` and result was `en_US.UTF-8UTF-8` (the space between en_US.UTF-8 and UTF-8 was missing)

**Comment by jfindlay** [comment]
Sorry for all the noise; github will show your cards before you make a pull request.  @tomashavlas, @TaiSHiNet, this should fix this issue.  The fix will go into the 2014.7 branch and so will be in 2014.7.2 onwards.

**Comment by TaiSHiNet** [comment]
@jfindlay thanks for the fix! Not sure when will 2014.7.2 will hit ubuntu, but I guess I can backport it anyway :P

**Comment by jfindlay** [comment]
@TaiSHiNet, yes, you can always install from pip.  We are also working on setting up more upstream packaging so that distro packages will be available as soon as we release.  That way the distros can still take their time to curate new salt releases but we can also offer packages to our users who want the latest releases when they become available.  Our QA process has improved a great amount in the last several months, so running the latest releases should not be as problematic as it used to be.

**Comment by TaiSHiNet** [comment]
@jfindlay Thanks for the info and the fix, I'm using your own PPAs, since offical Ubuntu repos are way too outdated.
