### ISSUE TITLE
State output

### ISSUE THREAD

**Issue by TimJones** [saltstack/salt#19066]
Salt master supports the `state_output: mixed` mode, but I think it would be better to either include the full output when a state fails or is changed, rather than just on failure.

This seems most useful when doing a `test=True`, as seeing exactly what changes will be applied is great for a test.

Can another `state_output: mixed_with_changes` or verbose printing for changed states when called with `test=True` be implemented?

**Comment by rallytime** [comment]
@TimJones I just came across this issue again. I think actually what you're looking for here is to use something like `state_output: changes`. Basically what `changes` does is "terse output will be used if there was no error and no changes, otherwise full output will be used."

Or another option you could use here that is also along these lines is setting `state_verbose: False`. This means "setting this to False will instruct the highstate outputter to omit displaying anything in green, this means that nothing with a result of True and no changes will not be printed."

I think either of these options will accomplish what you're looking for.

**Comment by rallytime** [comment]
I'm going to go ahead and close this. If you have questions about the suggestion above, please leave a comment! Thanks!
