### ISSUE TITLE
Wait for a service to really start in service.running

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#19084]
If I have a dependency on a running service, it is not necessary that it is completely ready when another service starts running. For example, service could create virtual interfaces, or prepare files, make database ready, etc. So there should be some way to tell salt state that the service should be really ready, not just running. Or at least to specify some delay time. So that I could say that service should be running for at least 10 seconds before it would be seen as running service.

One example is for example Docker. We start Docker, and have another docker pull state to download few images. But that second state regularly fails because Docker is not yet ready immediately after it was started (or restarted).

cc @kostko

**Comment by cachedout** [comment]
While I consider these primarily to be upstream bugs that should be filed with packagers of a given service, it was easy to add a flag to do this. I've done so in #19793

**Comment by mitar** [comment]
Great!

**Comment by cachedout** [comment]
@mitar If you're happy with this change, I'll go ahead and close this issue. If it's not resolved to your satisfaction, let me know and we'll re-open it. Thanks!

**Comment by mitar** [comment]
@kostko: Can you check if this addresses our issues?

I think the waiting is a good first approach. But even better it would be if it would be possible to specify a command to test if a program is running, and then a parameter that it should return true for 10 seconds.

**Comment by kostko** [comment]
Well in our case where we need this for Docker daemon startup, I have worked around this like so:
```
docker-available:
  cmd.run:
    - name: while ! docker ps; do sleep 1; done >/dev/null
    - timeout: 15
    - require:
      - service: docker
```

And the SLS in which this state resides is a dependency for all other states which require Docker to actually be up. This is possible because `docker ps` will only succeed when the Docker daemon is up and is answering API requests on its UNIX socket.

So this approach should be generalizable if a separate `cmd` would not be necessary, but if this was an attribute of the `service.running` state.
