### ISSUE TITLE
Have salt-cloud use boto_* modules for AWS support

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#19302]
salt-cloud and the boto_\* modules have overlapping and disparate functionality, but their aim is towards the same goal. For the most part, the boto_\* modules have way more functionality than salt-cloud, but a few simple things aren't implemented (like non-asg instance management, EBS management, etc). It would be ideal if salt-cloud started basing its AWS support on boto_\* modules and eventually moved away from reimplementing the client API.

**Comment by techhat** [comment]
@ryan-lane, as you and I discussed a few months ago, the `aws` driver is the place to do this, unless you'd like to create a new driver called `boto`.

**Comment by ryan-lane** [comment]
@techhat I'm not volunteering to implement this for salt-cloud. I don't use salt-cloud since I don't use a master, so I don't have the proper experience to implement this. I also don't have the time, since it's not something we're actively using.

That said, the pace of development for the boto_* drivers is much faster, mostly because it's using the boto library. Right now for AWS people have to choose between using salt-cloud, which doesn't have great AWS support, and using the boto_* modules, which won't automatically connect their minions to their masters and doesn't have a CLI.

It would be ideal if we worked towards the same goal here, since we're basically implementing the same thing.

**Comment by cro** [comment]
ZD 357

**Comment by DanyC97** [comment]
I second what @ryan-lane said.
I've been using salt-cloud/master on OpenStack and now on AWS (business decided to move in that direction) however now i'm at the point where i hit the ceiling wrt salt-cloud:

* i cannot create any ELB via salt cloud, nor Route53 zone, nor IAM roles/ policies etc etc (the list is a long one...)

However **boto_** modules are great but there are few problems with it:
* the only expert in the entire Salt community/ employees is @ryan-lane  and if he is out bang, you are blind should you seek help
* many modules are using boto v2 rather than boto3 and that shows up in the quality/ robustness 

Now i need to implement some boto states and modules as there is still a lack of features (hopefully we'll be able to contribute as soon as i get more experience on AWS)
