### ISSUE TITLE
Output switches return "salt-cloud: error: no such option:"

### ISSUE THREAD

**Issue by theherk** [saltstack/salt#19453]
Using the switch `--raw-out`, `--text-out`, `--yaml-out`, or `--json-out` returns `salt-cloud: error: no such option:`. I am using the dda3b0dfa2.

**Comment by techhat** [comment]
@theherk these have all been replaced with `--out`. Are those others still documented somewhere?

**Comment by theherk** [comment]
At [readthedocs](https://salt-cloud.readthedocs.org/en/latest/), the [main documentation](http://docs.saltstack.com/en/latest/ref/cli/salt-cloud.html#cmdoption-salt-cloud--yaml-out), and in the [man page](https://github.com/saltstack/salt/blob/develop/doc/man/salt-cloud.1#L174).

**Comment by techhat** [comment]
Thanks @theherk. The readthedocs page that you linked to is for salt-cloud 0.8.11, which is well over a year old and no longer maintained, since salt-cloud has been merged into salt.

The main docs definitely need to be updated. When they are, and a new release is cut, the man page will be auto-generated with the fixes.

@whiteinge, what can we do to either get rid of the old RTD for salt-cloud, or at least update it to refer people to the correct docs?

**Comment by whiteinge** [comment]
Pull req sent in saltstack/salt-cloud#922.

**Comment by techhat** [comment]
Merged, thanks @whiteinge
