### ISSUE TITLE
salt-ssh 

### ISSUE THREAD

**Issue by cjbarnes18** [saltstack/salt#19757]
Using ssh ProxyCommand seems to confuse salt-ssh

With the following (simplified)  ssh config

```
Host net-a 
  HostName host-a

Host host-b
  ProxyCommand ssh net-a -W %h:%p 
```

I get the following output

```
$ sudo salt-ssh host-b test.ping
Permission denied for host host-b, do you want to deploy the salt-ssh key? (password required):
[Y/n] 
Password for root@host-b: 
host-b:
    Permission denied, no authentication information
```

salt-ssh net-a test.ping works fine.

I can ssh to the host-b without difficulties so I know the config is good, and I can see that the key is being added multiple times to authotorized_keys so authorization is succeeding.

To get around the issue I had create a local port forward and point the roster to the local port, but this is not practical for ongoing use.

I use ssh ProxyCommand extensively to access remote hosts and this is issue presents a significant hurdle for me.

I see a request to specify a gateway/proxy has been added in #18540.   This may be a partial solution to my problem but I often need to use multiple hops to get to a destination server.

**Comment by rallytime** [comment]
Thanks for the report @cjbarnes18 - we will take a look!

ping @basepi

**Comment by gebi** [comment]
We are also using ProxyCommand extensively, though we let never let salt-ssh run as root. The different ssh jump-hosts even have different ssh keys, and we did not configure anything for salt.
Strangely enough salt-ssh copied a completely wrong ssh key into the pki directory, though it seems to work anyway.

Our setup currently uses salt-ssh 2014.7

**Comment by cjbarnes18** [comment]
@gebi Are you saying that for you salt-ssh works through ssh proxies OK?
an examle of your config would be appreciated :)

As far as root is concerned, I wouldn't normally, just trying to simplify to resolve the issue.

I think the key that gets installed is Salts own key.  Maybe their is a discrepancy between using salts key and the users for the proxy...

**Comment by cjbarnes18** [comment]
Just confirmed it, in order to make ProxyCommand work with just salts own ssh key to the ssh config.
 
```  
Host net-a 
  HostName host-a
  IdentityFile /etc/salt/pki/master/ssh/salt-ssh.rsa

Host host-b
  ProxyCommand ssh net-a -W %h:%p 
```

If you run as non root then you need to set the path to your alternate pki directory.

This info would be valuable in the the documentation.

**Comment by gebi** [comment]
@cjbarnes18 sure! We've never used salt-ssh in another setup as no salt client is directly reachable in our case.
Though we did _no_ configuration regarding salt-ssh and keys and are also not using the salt-pki directory (i've no idea what this should be for!).

Just plain ~/.ssh/config and ssh key access only through a running ssh-agent.

**Comment by cjbarnes18** [comment]
@gebi thanks,  In your case I expect you never had the issue because users keys where pre-installed on the gateway.

In my case I went from clean install with nothing but a root password to access each host.

In reality you could use any key to authenticate at the proxy.  I just specified the salt ssh key as that is the only key installed on these hosts.  I use salt to configure users and their keys...

The documentation discusses the recommendations for running as non root here http://docs.saltstack.com/en/latest/topics/ssh/index.html#running-salt-ssh-as-non-root-user

**Comment by gebi** [comment]
@cjbarnes18 yes you are right, keys are already there on all hosts (ssh jumphosts and salt clients)

**Comment by basepi** [comment]
Thanks for the good detective work, @cjbarnes18 and @gebi! I'm glad we seem to have figured out the main issue, I wasn't sure how to proceed on this one, I'm not very well-versed in ProxyCommands.

**Comment by colinnewell** [comment]
To clarify as I came across this and didn't realise what was happening here,  salt-ssh does work with your ssh config and will make use of ProxyCommand.  It's just that commonly you only have your jumps and ssh agent setup properly for your current non root user.  If you try sudo ssh host and it works, then it should work for salt-ssh.  If it doesn't then it could be one of a number of things, from not being able to pick up the key or talk to the ssh agent, to trying to connect as the wrong user on one of the hops.

The notes about running salt-ssh as non root are worthwhile, and would probably avoid some of this confusion, but the fundamental thing to note is that salt-ssh does appear to work fine with the ssh config and deal with ProxyCommand.

The simplest thing you could do that would have clarified it for me is to change the 'The IP address or DNS name of the remote host' to mention that this could be a host name from your ssh config file.  As it was I made the incorrect assumption that this was a salt problem, rather than my own ssh config problem.
