### ISSUE TITLE
List of states that support check_cmd?

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#19788]
Is there a list of states that support `check_cmd`? I was attempting to use it with `cmd.run` but the option appeared to be ignored. I checked the source for 2014.7 and develop, and `check_cmd` isn't present. The example in the documentation uses `file.managed`, so I looked at that as well and the check_cmd code was easy enough to spot.

**Comment by lorengordon** [comment]
Ok, I no longer need this as I opened my eyes and realized I could write the cmd.run statement to perform the check itself and set an exit code that would force the state to succeed or fail.

But it still would be nice to have the list. I'm also not sure the documentation is correct. I looked again and it references `file.replace` but in the source the only function that accepts `check_cmd` is `file.managed`.

- http://docs.saltstack.com/en/latest/ref/states/requisites.html#check-cmd
- https://github.com/saltstack/salt/blob/2014.7/salt/states/file.py

**Comment by jfindlay** [comment]
From what I understand of [the code](https://github.com/saltstack/salt/blob/develop/salt/state.py#L1549), check_cmd should be available to any state.  If it doesn't work, then what you've encountered might be a bug.

**Comment by lorengordon** [comment]
Ok, let me know if you need more information. Like I said, I moved passed it, but I can try to recreate what I was trying.

**Comment by jfindlay** [comment]
Thanks, @lorengordon.

**Comment by jfindlay** [comment]
@lorengordon, if you have further problems with this, please comment here and I'll reopen the issue.

**Comment by neilramsaybp** [comment]
Hi @jfindlay,

I am seeing a similar issue with the `file` state module, where the check_cmd appears not to be working.
I am running `salt 2015.8.8 (Beryllium)` on `Ubuntu 16.04.1 LTS`.

In [this Gist](https://gist.github.com/neilramsaybp/22e80edf9d6d09722773f249d88e82e2), I have a state file, that should fail at every stage, because the `check_cmd` directive is contrary to the change made.
I have also included the debug output of calling `salt-call --local -l debug state.sls test.file 2>&1 | less`. This indicates the `check_cmd` is not being processed at all.

I have successfully tested the `check_cmd` with the `pkg` state module.

Cheers,
Neil

**Comment by miromode** [comment]
Also experiencing this problem with `salt-call 2016.3.3 (Boron)`. I have a `file.exists` in an SLS with a `check_cmd` and the check command does not appear to run at all.

**Comment by gtmanfred** [comment]
Does this work for file.managed?

Because if so, then this is working as expected, and the existance of the `mod_run_check_cmd` is keeping the global `check_cmd` from being run, instead it needs to be specified in the state.

Only state modules in salt.states.git salt.states.file and salt.states.cmd, which implement calls to their `mod_run_check_cmd` functions will get the `check_cmd` capability.

https://github.com/saltstack/salt/blob/2017.7/salt/states/file.py#L2446
