### ISSUE TITLE
Cron.file uses 'name' to define source file location instead of 'source'

### ISSUE THREAD

**Issue by MarkMarine** [saltstack/salt#19878]
This is inconsistent with the rest of salt file.managed. If you write:

```
new_cron:
  cron.file:
    - source: salt://cron/new_cron.file
```

salt fails to render the sls, saying there are duplicate source entries. Took me a while to figure out why, I need to write this:

```
new_cron:
  cron.file:
    - name: salt://cron/new_cron.file
```

which is clearly in the docs, but it is different than the rest of salt.

**Comment by basepi** [comment]
It should be noted that every state function in salt has `name` as its first argument. There is no exception. If `name` is not provided, then the ID (`new_cron` in the case of your state above) is used as the `name`.

The difference here is that we don't have to define the destination file. The cron state knows what it is. So it makes less sense to have both a name and a source. And because every state must have a name, it makes sense to use it here for the source file. Yes, it's confusing when you compare it to file.managed, but `name` isn't a particularly intuitive name for that argument for a lot of states. (cmd.run, for example)

So yes, it doesn't follow the pattern of file.managed, but a lot of states don't. Early on the `name` argument was created and standardized, and it results in some counter-intuitiveness, but I just think of it as the "main" argument for a given state.
