### ISSUE TITLE
pam.read_file command not working on any minions.

### ISSUE THREAD

**Issue by jayeshka** [saltstack/salt#19942]
When I run command from master to salt:
```
$ sudo salt \* pam.read_file /etc/pam.d/login
```
I get an output :
```
'pam.read_file' is not available.
```
My salt version is:
```
$ salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by rallytime** [comment]
Thanks for filing this report @jayeshka! We'll take a look.

**Comment by jayeshka** [comment]
Thank you Nicole.

**Comment by jfindlay** [comment]
@jayeshka, when salt reports that `<module>.<function>` is not available, it is usually because the `__virtual__` function in that module is returning False.  In this case it appears that the `__virtual__` for libpam is quite naive in how it checks for pam being installed.  libpam.so could legitimately be in many places besides /usr/lib/libpam.so

**Comment by jayeshka** [comment]
Thank you @jfindlay.

Got the solution for the module. Unit test case is working fine.
Please review.
