### ISSUE TITLE
Restarting a salt-minion via atd sets the nice of salt-minion to 2

### ISSUE THREAD

**Issue by belvedere-trading** [saltstack/salt#19962]
Testing on CentOS 6.2/6.4 using Salt 2014.7.0

If you restart the salt-minion via atd (for example following the advice here: http://docs.saltstack.com/en/latest/faq.html#id15 ) the salt-minion process will end up with a nice of 2.  If you manually restart the salt-minion service it will (correctly) end up with a nice of 0.  When the nice of the salt-minion is set incorrectly, it causes processes that are started by it to also be set incorrectly.

I've worked around this issue by pre-pending a 'nice --2' to the restart, but this could impact users who don't notice the change in priority.

Note:  I don't know (and haven't tested) how this interacts with other systems (Debian, etc...) but having looked at the atd source I suspect that it has the same issue.

**Comment by oldmantaiter** [comment]
This appears to be an atd related issue where it always starts jobs with a nice=2. I agree that the information might be missed by some, but for most the change in nice value will not be noticeable.

**Comment by belvedere-trading** [comment]
I agree that the root issue is atd.  The recommended way of having salt restart salt could either include the 'nice --2' to counteract the atd issue, or mention that this is a possiblity.

**Comment by rallytime** [comment]
Thanks for the report @belvedere-trading and for the help @oldmantaiter. We should add a note to our docs explaining this behavior with something like: "atd starts the salt-minion with nice=2. If this is a problem, please add `nice --2` to the command" or something along those lines.

**Comment by oldmantaiter** [comment]
@rallytime @belvedere-trading  I was looking into setting nice values when daemonizing salt (master/minion), and trying to take into account the cross platform requirements of the project, just need a bit more time to get really familiar with the MixIn classes and such. Could be something to it where, depending on the nature of the server (if priority is to go to the application), nice level modifications could be useful to ensure salt doesn't interfere with what was already running there in the first place.

Since this has been given the low-hanging fruit label, I'll put it on the backburner and give it some thought.

**Comment by lordcirth** [comment]
Where are we at with this?  I think the referenced docs may have changed, as I don't see a reference to using 'at'.
