### ISSUE TITLE
Add positional argument support to RunnerClient's cmd* methods

### ISSUE THREAD

**Issue by rakai93** [saltstack/salt#19996]
I'm trying to invoke a custom runner via the salt-api /run route. After setting up the permissions, firing a POST request from a REST client plugin to https://host:port/run with the following payload works fine:

```
client: local
tgt: *
fun: test.arg
arg: some arg
arg: another arg
username: theuser
password: secretpassword
eauth: pam
-------
client=local&tgt=*&fun=test.arg&arg=some+arg&arg=another+arg&username=theuser&password=secretpassword&eauth=pam
```

Trying to request a runner returns a 200 OK response, but the contents shows an exception:

```
client: runner
fun: some.custom_runner
arg: some required arg
username: theuser
password: secretpassword
eauth: pam
-------
client=runner&fun=some.custom_runner&arg=some+required+arg&username=theuser&password=secretpassword&eauth=pam
```

Response:

``` json
{"return": ["Exception occurred in runner some.custom_runner: SaltInvocationError: custom_runner takes at least 1 argument (0 given)"]}
```

I've tried to change arg to args or pass some kwarg(s), but nothing changed.

Tested with salt version 2014.7.0

**Comment by whiteinge** [comment]
Runners don't accept positional args. I'm not sure why. Use kwargs instead:

client=runner&fun=some.custom_runner&somearg=someval+arg&username=theuser&password=secretpassword&eauth=pam

**Comment by basepi** [comment]
@whiteinge should the lack of positional args be considered a bug?

**Comment by whiteinge** [comment]
I'd label it a feature addition instead. It's somewhere in RunnerClient and
has been like that since the beginning. It doesn't prevent any usage. Most
programmatic function calling in Salt uses kwarg syntax (states, reactor,
overstate, mine_functions, etc), the main place positional args are used is
at the CLI.

**Comment by rakai93** [comment]
Okay, just using "arg_name=param" in the payload worked. But it still is a little confusing, since the "client=local" version of the command takes the "arg" and every example in the documentation shows the runner without any arguments.

**Comment by whiteinge** [comment]
More examples would be good for sure. The salt-api interface (which the rest_cherrypy netapi module uses) sort of expects that you know the difference between LocalClient() and RunnerClient() from Salt's Python API and that relationship isn't explained very strongly in the docs. A few cross-references would work well here too.

**Comment by whiteinge** [comment]
Updated title to reflect RunnerClient addition. Issue related to #32778; first steps toward fixing this taken in #32938.

It looks like the `arg` array still needs to get run through [parse_input](https://github.com/saltstack/salt/blob/bd0790f/salt/utils/args.py#L43-L72) function in order to close this issue. That step is currently getting skipped over: https://github.com/saltstack/salt/blob/bd0790f/salt/runner.py#L80
