### ISSUE TITLE
Move topfile rendering to master

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#19991]
When running Salt-minion in debug you'll see that the whole topfile gets pushed to the Minion which evaluates which apply to it. 
This may lead to excessive data leakage since it will show hostnames/minion id's of those other than itself.

This is not desirable in environments where customers or thirdparties have access to the server and its logs, since they'll be able to see which servers and states are available.

It would make more sense if the master deals with this and simply pushes only the matched data to the minion.  This would be the same behavior as pillar data right?

**Comment by basepi** [comment]
This does make some sense, and might be doable since it's how salt-ssh operates. But it doesn't really solve the problem. Minions have access to anything they want out of the master file_roots. They can list every file in the fileserver and request them at will, with no access control. This makes the fileserver very fast and relatively lightweight. This is why any data you don't want all your minions to have access to should be stored in pillar.

So moving topfile compilation to the master will actually do nothing, unless we moved the topfile out of the fileserver altogether, because the minions could still ask for, and receive, the topfile. Even if we moved it compeletly out of file_roots, that would only obscure minion IDs, not the available states.

Anyway, with all of that said, I'm not convinced that this would be worth the work required. I'm wondering if you could obscure those minion IDs by targeting on some other value, maybe a customer ID stored in grains or similar? Anyway I'd appreciate your thoughts, given the information above.

**Comment by syphernl** [comment]
Hmm, that's a little trickier than I thought. 

Storing stuff in grains is not recommended since they can be altered by anyone with access. Simply changing `customer_id: 123` => `customer_id: 124` and presto you can do a lot more than you actually should :) Sure, it could be a hash or something like that but if that would help much? 

Regarding files, it's probably also worth considering adding a layer of security to that too. 
Generally files in the file_roots do not contain information that should not be public. That should always be in the pillar and optionally inserted into the files via `file.managed` or something like that.

Puppet provides some level of security on their fileserver allowing "mount points" to be restricted to specific hosts and also offers "private" folder e.g.: `files/private/%h` where %h will allways be the agent's name so it cannot read any of the other files that do not belong to them.

**Comment by basepi** [comment]
Yep, it's true, grains cannot be considered secure.

So I talked to @thatch45 and the topfile compilation should be fairly straightforward, we could do it master side through an external top module.

Access control on the main fileserver is something people have been asking for for a long time, but we've never come up with an elegant spec or solution. Pillar works out well because it ends up being fairly lightweight to maintain, unlike an access control list.

Anyway, I'm going to mark this as approved, but it may be some time before we have time to implement it.

**Comment by damon-atkins** [comment]
What needs to be prevented, is someone breaking into the system and changing the servers role (i.e. the set of software, sudo rules, passwords for apps,etc), from this breaking into more systems or gaining more access. Providing only the bits of the top file required, to the client is part of doing this.

**Comment by basepi** [comment]
@damon-atkins That's already prevented. Obviously if your master is compromised, then your whole infrastructure is compromised. But the way salt is set up, if a minion is compromised the damage it will be able to do is very limited. It can't get the pillar data of any other minions, and cannot tell other minions to run commands unless the peer publishing is turned on (it is off by default).

**Comment by syphernl** [comment]
Please keep this open, thanks.

**Comment by MTecknology** [comment]
It sounds like you might want to consider using a syndic master for each client. Each client/syndic master could have their own git repo with their special states/top.sls and be connected to a master of master for administrative orchestration/management.

I can't really picture any other way to securely achieve the level of segregation that it sounds like you're after.
