### ISSUE TITLE
How to determine a salt job is successed or failed? How do I fire a callback? 

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#20043]
Ansible has running_on_failed or success feature which points out one job is successed or failed, and then, do different callback job at on-failed or on-success.

Look at saltstack, I still cannot find how to exactly determine a job final status, and what should I do to fire a callback job?

Wishes your reply, Thanks.

**Comment by basepi** [comment]
Depends on what part of Salt you're talking about.

If you're talking about the state system (which I think you are, it's the closest match for playbooks), this is straightforward. You can run a state if another state fails by using the `onfail` requisite. You can run a state if another state succeeds using the `require` requisite. Both are documented here:

http://docs.saltstack.com/en/latest/ref/states/requisites.html

Keep me posted if that doesn't answer your question.

**Comment by Colstuwjx** [comment]
I'm still confused about the `require`,`onfail`,`watch` etc. 
May I custom define the action while match `watch` or `require`.

For instance, I defined a sls, and salt could call this sls after `watch` is matched.
I still cannot find any document about this.

Thanks.

**Comment by basepi** [comment]
Requisites allow you to map dependencies between different states. So you can run one state only when another state runs successfully (`require`), or you can run one state only when another state fails (`onfail`). `watch` is a little bit more complex, because it actually acts like a `require` but can add additional behavior when changes are made by the watched state. Most often we use this to restart a service when a file changes, with `service.running`. There are a number of examples of how to use these requisites in the document I linked. There are also examples in [the state tutorials](http://docs.saltstack.com/en/latest/topics/tutorials/index.html#states).

**Comment by Colstuwjx** [comment]
Sorry, but as I known, I think it's not flexible enough. How I define the custom code when `watch` fired? How I define the custom code when `onfail` or `require` fired? Combine with reactor? I still cannot find a polite way to do our custom requirements.

**Comment by basepi** [comment]
Easy. Create a custom state module with your custom code, and then put it in your state run with an `onfail` requisite. When the original state fails, your custom state will be run.

http://docs.saltstack.com/en/latest/ref/states/writing.html

**Comment by Colstuwjx** [comment]
cool!!
Many thanks..
