### ISSUE TITLE
cache if not cached (and hash match)

### ISSUE THREAD

**Issue by ghostsquad** [saltstack/salt#20078]
There seems to be some basic functionality missing from Salt, either that or I'm doing it wrong. Essentially, I want to deploy (ie. copy) some files to a minion, in order for a command to work, but ONLY if those files have not yet been deployed or are older/different than what's on the minion. To state the obvious, this is to avoid copying files (needlessly), every time a particular execution module (which needs this script) is invoked on the minion. The 'single file from cache' implementation might look like this:

``` Python
def _get_script(salt_path):
    script_path = __salt__['cp.is_cached'](salt_path)
    if script_path == '' or __salt__['cp.hash_file'](salt_path) != __salt__['cp.hash_file'](script_path):
        script_path = __salt__['cp.cache_file'](salt_path)
    return script_path
```

I found `cp.get_dir` but that's going to copy files from the master no matter what. I found `cp.cache_dir`, that's essentially the same as `cp.get_dir` where the root of the destination is the minion cache folder. Neither of these functions try to save time, by only caching/downloading files that are not already cached/downloaded with the same hashcode.

I thought about implementing this myself, but I can't find a _public_ function that recursively returns a list of files in a directory on the master (e.g. `foo.list_files('salt://my/path')`). I found `cp._render_filenames`, but I don't want to use that, because it's "private", and may change or is not expecting to be called by client code.

**Comment by basepi** [comment]
Hrm, I could have sworn that `file.managed` only caches the file from the master if the checksum changes. Have you tried that function? It's possible I'm missing something, I haven't been deep in that particular part of the code in awhile.

**Comment by ghostsquad** [comment]
@basepi - file.managed STILL copies the file to the minion before comparing
https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L1418

even if this were the case, I don't know how to use this state from another state module or execution module, there's no documentation for that.

**Comment by basepi** [comment]
Interesting, seems like we could get some good performance improvements here. I'll approve this as a feature, thanks!

**Comment by basepi** [comment]
Wait, except that code doesn't actually do what you think it's doing. It's copying from the minion cache, I think. A few lines above, when we call `file.get_managed`, that's where the retrieval from the master is happening, and where the caching that I mentioned would be happening.

**Comment by ghostsquad** [comment]
if file.managed does what you say, how do I call that *state* from another state module or an execution module? I can't fine the documentation for that.

**Comment by basepi** [comment]
Well, ideally you would use a `file.managed` state and then have your second state which relied on that file being there use a `require` requisite to make sure the `file.managed` state ran first and ran successfully.

The `file.get_managed` function is actually available as a normal remote execution module function through the `__salt__` dictionary. The problem is that I think it was designed primarily for the use of `file.managed`, much like `file.manage_file` was, and so is probably not very user-friendly. We should add a user-friendly, easy-to-use file caching function for this purpose.

**Comment by ghostsquad** [comment]
How can a state be called from an execution module or another state module?

**Comment by basepi** [comment]
@ghostsquad You cannot call state modules from other state modules nor from execution modules. But you shouldn't need to -- states are designed to be standalone. If you want to make sure one piece of state has been applied before another piece of state, you just use a `require` requisite to enforce the ordering.

If there's a repeatable task that can be used as a building block for other more complex tasks, that's the kind of thing that belongs in an execution module, which is then available to be called in state/execution modules. For example, `file.managed` goes through the whole process of caching and comparing and templating files, while `cp.cache_file` just does one small part of that, and is a building block function.

Which is why I stated above:

> We should add a user-friendly, easy-to-use file caching function for this purpose.

The function will be in an execution module, so it can be called from state/execution modules.

**Comment by ghostsquad** [comment]
The problem I'm trying to avoid is having to type this require statement _everywhere_:
```
barState:
  - mystatemodule:
     require:
       - sls: myFoo
```

Someone writing a new state that uses `mystatemodule` should not need to know about the requirements it has. _It_ should know what it's dependencies are, and try to fill them automatically.

And things like the file.managed state contain a LOT of business logic, which I'd rather not recreate.

If there was a 1-1 relationship between state modules and execution modules, and a 1-many relationship between execution modules and other execution modules, with a state module only doing the bare minimum like error handling and output msgs, then this problem wouldn't exist.

**Comment by basepi** [comment]
But it doesn't make *sense* for there to be a 1-1 relationship between state modules and execution modules. They are fundamentally different in purpose.

But yes, I see your point that we need to have the ability to do a `file.managed`-like operation from within a custom state module.

Which, *again*, is why I stated:

> We should add a user-friendly, easy-to-use file caching function for this purpose.

I'm *agreeing* with you. There's a valid use case for having an execution module function which puts a file in place if it's not already in place.

**Comment by ghostsquad** [comment]
I was merely responding to:

>  If you want to make sure one piece of state has been applied before another piece of state, you just use a require requisite to enforce the ordering.

Do I understand it correctly, that the original design was that states (sls), were supposed to be place where the dependency tree is built?

:+1:

**Comment by basepi** [comment]
Yes, the dependency tree generally belongs in the SLS files.

**Comment by ghostsquad** [comment]
The part of this problem is that we are using SLS files wrong, or making some assumptions. We've talked about having Salt run HighState every hour to ensure machines are configured properly at all times. Back to the original question. Easy-To-Use file caching would be awesome! Thanks for all your help by the way!

**Comment by basepi** [comment]
No worries, sorry if I sounded frustrated. I thought we weren't on the same page, but it was just miscommunication. =)
