### ISSUE TITLE
pygit2 for pillars

### ISSUE THREAD

**Issue by gczuczy** [saltstack/salt#20100]
Hello,

I'm not sure whether this is a bug or feature request, the only things I'm sure of, it's an issue here.

I would like to build our workflow as the pygit2 gitfs works with states, and taking advantage of the branches-as-environments feature as allowing engineers to create personal sandbox branches where they are able to add new stuff (make changes), then merge these back to dev/qa/uat/prod/etc. However, currently with ext_pillar not supporting (2014.7 here) pygit2, all the branches:environments mappings have to be made explicitly in the master config, which just doesn't make it possible to dynamically allocate sandbox environment for feature development.

Right here, pillars and states are kept in the same repo, and because states are referencing pillars it's impossible to make sandboxing branches, because they will not be able to access their pillars.

Could you please also add pygit2 for gitfs pillars, with the feature that allows us to dynamically treat branches as environments?

**Comment by basepi** [comment]
I think @terminalmage has long desired to rewrite the git external pillar to match the gitfs fileserver, in both functionality and configuration. But he has been so busy he hasn't had time. But yes, I think this would be a great change to make.

**Comment by bahadir** [comment]
I've started refactoring fileserver.gitfs code so we can make it a utils module: https://github.com/bahadir/salt/commits/gitfs-utils

My plan is to make git pillar work like git fileserver backend.

**Comment by julienlavergne** [comment]
Any news about this feature?

**Comment by terminalmage** [comment]
It is currently being targeted for the next feature release, 2015.8.0.

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/25595 adds pygit2 support for git_pillar, and will be part of the 2015.8.0 release.

I'm going to close this issue.

**Comment by terminalmage** [comment]
@gczuczy It looks like one major feature you want will not be part of the rewrite. Branches must still be specified in the master configuration. The reason for this is that git_pillar updates its git repos in the same maintenance thread as gitfs. With gitfs though, we don't actually checkout the repos like we do with git_pillar, we just grab files as they are requested out of the fetched git objects. With git_pillar though, we need to have the files checked out so that the top file can be compiled.

I think this is still a good feature to have though, we'd just need to think of the best way to accomplish it. Can you open a new issue for that specific feature?

**Comment by gczuczy** [comment]
@terminalmage here you go: https://github.com/saltstack/salt/issues/25926
Does it cover properly what's left out here?

**Comment by terminalmage** [comment]
Yes, that looks great.
