### ISSUE TITLE
0.10.2-2 yumpkg fails to correctly skip_verify when custom repo has gpgcheck set

### ISSUE THREAD

**Issue by halberom** [saltstack/salt#2011]
We've got various local repo's defined in /etc/yum.repos.d - some of these had gpgcheck enabled as a local config setting.

Attempting to install unsigned packages from these custom repos failed whether skip_verify was True or not.

looking at the code (https://github.com/saltstack/salt/blob/develop/salt/modules/yumpkg.py#L235), I'm guessing its setting the global yum config variable (i.e. /etc/yum.conf), which I'm double guessing is then being overridden by specific repo config. i.e.  /etc/yum.repos.d/my-repo.repo also sets gpgcheck=1. 

Removing the gpgcheck=1 from the custom repo definition resolved the issue

Not sure if it's worth the coding to handle individual repo definitions, if not, probably worth documenting somewhere/somehow and pointing out that skip_verify only impacts the global setting.

Cheers

**Comment by terminalmage** [comment]
Revisited this long-open bug today and confirmed that this has been fixed for quite some time. In all supported releases, we are adding ``--nogpgcheck`` to the yum command that is run when ``skip_verify`` is True.

It looks likely that this issue was with the (now-removed) execution module written to use the buggy Python bindings for yum. At the time of the original post, there were two yum execution modules: ``yumpkg.py``, which used the Python bindings, and ``yumpkg5.py`` which simply wrapped yum and was used for RHEL5 only (which had Python bindings written in Python 2.4 and were thus unusable in Salt). 

Some time ago, after having to work around a number of problems with the bindings, we ended up removing the old ``yumpkg.py`` and renaming ``yumpkg5.py`` to ``yumpkg.py``, and now we have just the one module.

Sorry for leaving this open so long.
