### ISSUE TITLE
[2015.2][salt-cloud] VMs created with salt-cloud are not seen as created

### ISSUE THREAD

**Issue by traxair** [saltstack/salt#20199]
`salt-cloud -m my_map.map`
-> creates my_vm
```
$ salt-cloud -m my_map.map
...
The following VMs will be created: [my_vm]
```

Running the command n times creates n VMs with the same name.

**Comment by traxair** [comment]
Adding `rename_on_destroy: True`to the provider configuration file should fix the issue.

It came from the fact that `salt-cloud -f list_nodes_min ec2-config` was not seeing all the VMs because of dupplicate names.

On AWS I had 4 instances:
```
 - vm_1: running
 - vm_1: terminated
 - vm_1: terminated
 - vm_2: terminated
```
And `list_nodes_min` returned:
```
  vm_1: terminated
  vm_2: terminated
```

**Comment by ssgward** [comment]
Thanks for the report.

**Comment by rallytime** [comment]
I have submitted #26479 which should fix this bug.

The default behavior on other cloud drivers is to not allow instances to be created if the new instance has the same name as other instances. This fix duplicates this behavior for EC2, even if the instance is in the ``terminated`` state. The fix also makes ``rename_on_destroy`` default to True in order to clean up those terminated instances in case you forgot to set it in your cloud config.
