### ISSUE TITLE
Create an acceptance test suite for salt

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#20239]
Currently Salt is tested either by the CI which has unit and functional suites but no actual integration/acceptance suite or in production where bugs like [these](https://github.com/saltstack/salt/issues?q=is%3Aopen+is%3Aissue+label%3A%22High+Severity%22) happen.
In order to ensure that salt works on all cases an acceptance test suite should be created.
The suite will use an actual salt instance and will execute the different components that salt is made of such as highstates or modules.
Some of these tests can be run as part of the CI process for each commit since they are supposed to run in a timely fashion e.g.:
- When booting a machine with a salt minion/master/syndic is available and running
- Salt master is accepting keys and all minions responds to test.ping 
- All CLI commands that salt provides are available and functional.
- The common states are functioning correctly on the most common operating system salt is deployed on.

Some of these tests can only be run on a nightly basis e.g.:
- Run all states on every supported operating system to ensure they behave exactly the same.
- Run the cloud related states and ensure that they can create an instance and operate it and that salt is installed and responding in that instance.

And the rest of the tests can be run before release or before merging an important feature in order to check regressions e.g.:
- Ensure that a memory leak has not occurred when salt performs X many many times.
- Ensure that timeouts don't occur when a master has a lot of minions.

In order to implement an acceptance test suite I'd use [test-kitchen](https://github.com/test-kitchen/test-kitchen/) which allows me to boot virtual machines using [Vagrant](https://github.com/test-kitchen/kitchen-vagrant), run [salt operations](https://github.com/simonmcc/kitchen-salt) and test them using [serverspec](http://serverspec.org/), [bats](https://github.com/sstephenson/bats) and any other testing software you can think of if you are able to implement a simple plugin with [kitchen-busser](https://github.com/test-kitchen/busser).

I'm willing to contribute at least a part of this suite but it requires cooperation on your part as well.
Each cloud provider you support should be tested in order to ensure that salt-cloud and all cloud related states work so API keys with limited permissions needs to be set up. You might decide that you don't want to share them publicly and that's fine but it means that saltstack is responsible for running these tests in order to ensure nothing breaks.
It also requires some modifications to your CI process and what should be installed on the CI machines in order for these tests to be able to run.

What do you guys think?

**Comment by rallytime** [comment]
@thedrow Thanks very much for this detailed issue! I think you have some great ideas here, some of which we have already implemented, some of which are in the works for being implemented, and some of which are new.

We actually already have integration tests working with quite a few tests running (the majority of the test suite are integration tests). These run along with the unit tests and are run each time someone submits a pull request on Ubuntu 14 VMs and CentOS 7 VMs. We also have many other VMs running these tests on each actively maintained branch where about 10 different OSs run the test suite on each branch. Now, the way these work currently is we are running 2 masters, 2 minions, and 1 syndic on one machine while we run the test suite where many of the things you've suggested are tested and evaluated. We do this in order to insulate test failures to the salt code instead of things like network availability, etc. 

In addition to the unit and integration tests that are constantly running on VMs through our Jenkins set-up, we also have a suite of manual tests that we run intermittently to make sure things like multi-master, syndic, key acceptance, etc., are in working order. 

As to your point about nightly cloud tests, we actually already have those, too! :D They run nightly and just do a simple "Can we provision and delete machines on this provider?" test on the majority of our high-use cloud-providers. (Currently we are running this on Rackspace, Linode, EC2, Azure, and Digital Ocean. I have plans to write more for GCE, Joyent, and some others. If you view the tests result on jenkins, you'll see that we have some failures there. I am working to get those cleaned up and fixed as we speak. I also need to add the 2015.2 branch to these tests.) 

It should be noted that we definitely have a lot of work to do in all of these areas. As you pointed out in your link to the high severity issues label, we have plenty of things we can write more automated tests for and add to our manual test suite. We are working on getting more and more tests added as soon as we can so we can bolster the stability of salt and the release process. We also have plans to create more resource-intensive, high-load, and long-running nightly and even weekly tests. We should definitely incorporate looking for memory leaks and testing scale, as you've suggested.

If you'd like to see some of what I am talking about, and you haven't seen it already, you can check out our jenkins set-up here: https://jenkins.saltstack.com/ where you can view the test status of each branch as well as the cloud nightly builds. 

Anyway, I think you've hit a lot of really great points and we'll check out what you've suggested to tie in with what we are already doing and have plans to implement in the future. Did I miss covering anything?

**Comment by rallytime** [comment]
ping @ssgward @jfindlay @pitatus

**Comment by jfindlay** [comment]
@thedrow, we are in the process of upgrading and expanding our QA infrastructure.  Right now our main concern is to stabilize the tests we do have before venturing in new directions.  We've (and by we, I mean @rallytime and @cachedout) been working very hard to track down and eliminate some subtle, deep inconsistencies that cause intermittent failures.  Once these are gone and our current tests are reliably passing on all the distros we support, we will begin to apply resources to the kind of issues that you've mentioned.

**Comment by thedrow** [comment]
@rallytime 
I can't find the integration tests anywhere in the repository. Is that intentional?
One of the things that made developing the boto VPC module really hard is the fact that I didn't have a way to verify that it really works on AWS. Sure I used moto to mock AWS but that doesn't mean that what I did will work as expected due to a moto bug.
That's one reason I think we need a more open direction to integration testing.
The other reason is that salt contributors make a habit of contributing without testing (other then testing it in staging/production) which is a problem if something breaks for someone else on production. By the time it did break you've caused the decision makers to put trust less trust in Salt which will make the devops lives harder. I've seen it happening with other software to the point where I had to resort to fabric because that's "what the CTO knows that works". I don't want to go through that experience again.
I think that requiring contributors to contribute a few integration tests that prove that the feature they are introducing does work is less rigid and won't slow down contributors then requiring a full unit and functional test suites which might or might not require a lot of work.

The tools I mentioned above provide a easy and quick way for testing your changes.

I have no idea how do you guys make something out of this output.
I guess I'm accustomed to Travis which takes care of formatting very well.
It's something that also bothered me. I understand why Salt uses Jenkins. It's the best CI software besides Travis but the UI is horrible unless heavily customized.
It's really hard to understand anything from it unless you know exactly how the process was built.
This is important since kitchen allows you to ssh into failed machines in order to figure out what's wrong.
There's a [plugin](https://wiki.jenkins-ci.org/display/JENKINS/Remote+Terminal+Access+Plugin) for that which isn't installed as far as I can see.
I can open another issue about Jenkins and what's needs to be done in order to make it more appealing to the end users.

@jfindlay I realize that your resources are limited which is exactly why I offered to help implementing these tests.

**Comment by thedrow** [comment]
So I really want to help make this happen. I've been referencing some issues that are related.
I think that @rallytime should set up test kitchen on EC2 and set up Jenkins to run it and I'll start providing some tests for it.

**Comment by obestwalter** [comment]
I started thinking about a subset of this for testing vagrant and the salt provider and windows guests. For this combination there is the added problem that it has never really worked (at least since last spring - since I am trying to use it) due to numerous bugs in both projects. 

I am prepared to put some time into this over the summer to get things going and Instead of creating my own island solution for this, maybe we could join forces and get this off the ground together.

Would your setup with kitchen-salt and the other mentioned tools work also for the combination Vagrant on a Linux Host (using VirtualBox and salt provider) + Windows Guest? I never worked with any of those tools.

I think the Windows platform needs these kind of acceptance tests desperately. In my experience with Salt and Windows over the last year it looks like Windows is often overlooked and really evil blocker bugs slip through into the releases, that could have been caught by just exercising the code on a Windows platform.

I started collecting my thoughts on this public Trello board: https://trello.com/b/vywwuncS/ci-for-salt-vagrant-windows

pinging @UtahDave and @jfindlay for input on this as I have been in mail conversations with them about this during the last few days.

**Comment by jfindlay** [comment]
Autotesting windows is on my list of things to do, but I haven't had time to get to it yet.  It will likely be a significant amount of work, so any progress is appreciated.  My first goal is to get the unit and then integration tests running on windows.  Once that mostly works, we can add it to our branch tests and once we've cleared up most of the issues there, I'd like to get it running on pull requests.  Other people at salt may disagree with me there, but I think windows is a different enough platform that we ought to be testing it at greatest frequency so that people will better be able to see the consequences of their code changes on a diverse set of platforms.

**Comment by thedrow** [comment]
@obestwalter Since VirtualBox can run Windows and test-kitchen supports WinRM starting from version 1.4.0 then yes it is possible to create an acceptance suite for Windows.
However, I think that it will be more useful to integrate this stack with Jenkins.

**Comment by obestwalter** [comment]
> However, I think that it will be more useful to integrate this stack with Jenkins.

@jfindlay More useful then what? Whatever we use: it definitely should be integrated with Jenkins. But Jenknis is just the test orchestrator, runner and results collector, so the underlying tools would be the ones that you suggested, I guess. Or is it not possible at all to let Jenkins handle tests like you originally suggested and you changed your mind and have a different plan now?

And like I said: atm this particular combination I mentioned is completely broken (as in: unusable). This is why I think it's important to get this running. At the moment I feel like I am the only guy on the planet who ist trying to use a windows guest with vagrant on linux + Salt ...

**Comment by thedrow** [comment]
What I mean is that we need to provide a PR against salt-jenkins (or maybe the new repo for jenkins) instead of being able to run test kitchen manually.

**Comment by thedrow** [comment]
@jfindlay The first step here would be to have test kitchen and the plugins installed on the CI environment. Where do you want the PR to be directed at?

**Comment by obestwalter** [comment]
I don't know anything about the Salt testing infrastructure yet, so this is something @rallytime or @UtahDave could answer?

**Comment by thedrow** [comment]
Probably.

**Comment by obestwalter** [comment]
Sorry ... deleted my last answer - I didn't realize that you are actually not talking to me :)

**Comment by obestwalter** [comment]
> Other people at salt may disagree with me there, but I think windows is a different enough platform that we ought to be testing it at greatest frequency so that people will better be able to see the consequences of their code changes on a diverse set of platforms.

Thank you! I agree with you that the huge amount of Windows-Breakage(TM) due to complete ignorance of the fact, that it should run on windows is the major problem here I think. I am using Salt since beginning of last year on Linux, Mac and Windows and Windows is just one blocker bug making it into releases after the other. 

That is why I think it would be a good idea to get it to work with vagrant, so it's easily possible to run the windows tests while developing before making a pull request. If the unit tests run in the same vagrant environment on your end there is always a working windows development environment available as a free side effect of that, which would make the hurdle to start developing and testing on windows much lower.

**Comment by lorengordon** [comment]
This would be great! At the least, I think with each PR Jenkins should spin up a Windows minion to execute the integration tests. That would catch a lot of bugs due to Windows-specific implementations of various modules (and identify others where Windows-specific implementations are needed!).

**Comment by jfindlay** [comment]
@thedrow, I've never heard of test kitchen.  The main thing making any progress difficult in this area, at least for the salt project itself is that our current CI setup is not very, reproducible or development friendly.  It was setup back when salt had less than ten employees, none of whom had enough time to keep up with everything, so it has been somewhat neglected until recently.

@s0undt3ch is working on a new setup that is more modular and flexible that allows us to stage our CI development and will much more easily allow for major feature development such as has been discussed here.  Until this system has taken over from what we currently have, there are not many changes that we can make without potentially interrupting the normal flow of pull requests and branch tests.

**Comment by obestwalter** [comment]
> The main thing making any progress difficult in this area, at least for the salt project itself is that our current CI setup is not very reproducible or development friendly.

What is speaking against building up this new testing functionality (especially for windows) independent from the old busted stuff?

**Comment by jfindlay** [comment]
@obestwalter, you are right, getting tests to run on windows is a separate problem from integrating windows into our automated tests and you are welcome to contribute whatever you can to this effort.

**Comment by obestwalter** [comment]
@jfindlay cool - what I can contribute is getting a Windows guest vagrant box set up that bootstraps a development environment and maps the code of the Host into the guest. This is not much work anymore thanks to https://github.com/saltstack/salt-windows-dev - I tried his today and got it to work. All is left to do is to "vagrant enable" that repository and provide publicly available vagrant boxes.

**But**: due to the proprietary nature of the M$ Windows Operating System this is where you as a company would come in: One could build vagrant boxes from [free evaluation ISOs](https://www.microsoft.com/en-us/download/details.aspx?id=11093) and make them available in the vagrant cloud, but I don't know about the legal implications of this. If this is not allowed, the vagrant box building has to be automated as well with e.g. packer and everybody has to use their own licenses to spin up test boxes. This is something I did not try yet, but would be prepared to look into if necessary.

**Comment by obestwalter** [comment]
FYI: I [forked](https://github.com/obestwalter/salt-windows-dev) *salt-windows-dev* and created a vagrant configuration and started adusting it to work standalone and in vagrant. There is an issue with detailed instructions to create a public box for it, if somebody wants to help moving this forward: https://github.com/obestwalter/salt-windows-dev/issues/5

**Comment by obestwalter** [comment]
@jfindlay @UtahDave I would propose that we move the discussion about getting a seed for the automated Windows testing with vagrant [over here](https://github.com/saltstack/salt-windows-dev/issues/12) - for me the two topics of an automated, portable development environment that doubles as a test environment overlap almost completely and both are important to have for Windows. 

The next step would be to somehow plug this into your CI pipeline. This is where @thedrow with his test-kitchen maybe comes into play? I am still not clear how your test-kitchen approach would play into that as I did not get my head around it's concept yet, but maybe you can clarify that in the context of the ongoing work in salt-windows-dev.

**Comment by jfindlay** [comment]
@obestwalter, fine with me.  I'm sorry I really haven't spent any time on this.  We're bringing in new QA engineers, who will take off some of the load on me in a few months.  I still really want to fully integrate windows into our regular automated testing.

**Comment by thedrow** [comment]
@obestwalter test-kitchen comes into play by creating the test machine and running salt on it.
According to the [kitchen-vagrant plugin documentation](https://github.com/test-kitchen/kitchen-vagrant#-vagrant) you need to have [vagrant-winrm](https://github.com/criteo/vagrant-winrm) installed and a vagrant box with windows and then you can run any kind of tests on it.

**Comment by obestwalter** [comment]
@thedrow o.k. the penny dropped testhat sounds good. As soon as [this issue](https://github.com/saltstack/salt-windows-dev/issues/12) is resolved this repo can be used as the base for running tests with test-kitchen.

**Comment by dragon788** [comment]
Have you guys considered using AppVeyor for the Windows portions of this assuming their free for open source applies to SaltStack since you guys only provide consulting/support and the project itself is open source? AppVeyor currently runs 2012R2 but they have 2016 in a trial mode, for full integration/regression testing you would probably still need to use something like Vagrant or Azure/GCE/AWS with a CI system triggering tests against the various versions of Windows that you actively support.

**Comment by cachedout** [comment]
@dragon788 Oddly enough, that is actually on my short list to investigate. That's funny that you mention it!

cc: @twangboy

**Comment by lorengordon** [comment]
I've had pretty good luck with appveyor. I use it in alongside travis, using `tox` as the task runner, so the same tests run the same way on both linux and windows.

**Comment by obestwalter** [comment]
Hey @stale bot, I think this is still unresolved, so hold your robot horses for now :)
