### ISSUE TITLE
State 'service.... found in SLS ... is unavailable - Ubuntu 14.04, with salt 2014.7.0 (Helium)

### ISSUE THREAD

**Issue by v6** [saltstack/salt#20242]
None of the following work on my Ubuntu 14.04 machine: 

`service.running`
`service.enabled`
`service.enable`
`service.reload`
`service.restart`

However, the CLI commands via salt-call on the minion run just fine: 

http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.service.html

My sls sample follows: 

        nexusService:
          service:
            - name: nexus
            - start

A small amount of my output follows: 

        local:
        ----------
                  ID: nexusService
            Function: service.start
                Name: nexus
              Result: False
             Comment: State 'service.start' found in SLS 'nexus' is unavailable
             Started:
            Duration:
             Changes:

        Summary
        ------------
        Succeeded: 0
        Failed:    1
        ------------
        Total states run:     1
        The following SSH command responded with a non-zero exit status.
        Vagrant assumes that this means the command failed!

        salt-call state.highstate --retcode-passthrough  --log-level=debug --force-color

        Stdout from the command:

        local:
        ----------
                  ID: nexusService
            Function: service.start
                Name: nexus
              Result: False
             Comment: State 'service.start' found in SLS 'nexus' is unavailable
             Started:
            Duration:
             Changes:

        Summary
        ------------
        Succeeded: 0
        Failed:    1
        ------------
        Total states run:     1

If anyone asks for a full trace I'll make one. 

I think this issue may be similar to this: 

https://github.com/saltstack/salt/issues/13703

**Comment by v6** [comment]
Tried with atd as well, in case it was just nexus being weird. 

The whole durned STATE is unavailable. WOE.

**Comment by v6** [comment]
Here are the lines I tried with atd: 

        atd:
          service.start

**Comment by nmadhok** [comment]
@v6 I noticed you're using some of the module functions in your state. The service state module only has the following functions available:
```
dead
disabled
enabled
mod_watch
running
```

If you will try to use module functions in your state directly, it will give you the error that they are unavailable. For example, in your example, you are trying to use ``service.start`` which is not a state function but a module function.

**Comment by v6** [comment]
Ah. How can I enable modules, as opposed to states? 

I have read through the introductory documentation, but it's unclear how to reference or install them. 

I seem to have figured out formulas, for the most part.

**Comment by nmadhok** [comment]
@v6 I have updated my comment above to tell you how you can use module functions within your state. Let me know if you have any more questions/confusion.

**Comment by v6** [comment]
Perfect. Thanks.

**Comment by nmadhok** [comment]
@v6 You're welcome! Glad you got it resolved!

**Comment by terminalmage** [comment]
@v6 Execution modules contain functions which are designed to be run on the CLI using something like the following syntax:

```
salt minion-id module.function
```

States contain logic that seeks to enforce a specific configuration. Under the hood, they use many of the same functions you can run on the CLI like the example above. The example @nmadhok provided shows how to run these functions in an SLS file. You can click [here](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html#execution-of-salt-modules-from-within-states) for more information, including an explanation of why ``m_name`` must be used instead of ``name`` in his example.

Also, one thing to keep in mind is that the ``module.run`` state is not idempotent. That is, it will run every time the SLS file is executed. For that reason, if you just want to ensure that a service is running, you probably want a [service.running](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html?highlight=states.service#salt.states.service.running) state:

```yaml
atd:
  service.running:
    - enable: True
```

If this state is run, then if atd is already running Salt will take no action, whereas when @nmadhok's module.run example is used Salt will attempt to start the service every time the module.run state is run.
