### ISSUE TITLE
Add support for built in key rotation of new ssh into salt ssh

### ISSUE THREAD

**Issue by thatch45** [saltstack/salt#20284]
http://blog.djm.net.au/2015/02/key-rotation-in-openssh-68.html

**Comment by basepi** [comment]
Unless I'm missing something, this shouldn't actually affect salt-ssh, because we use the system's version of ssh, we're not reimplementing ssh ourselves. Reading this, it seems to me that it's designed to be invisible and work automatically, assuming the client's SSH version supports the auto-rotate.

Please correct me if I'm wrong.
