### ISSUE TITLE
ntp for linux

### ISSUE THREAD

**Issue by francis2211** [saltstack/salt#20387]
Will be nice to have ntp support for linux http://docs.saltstack.com/en/latest/ref/states/all/salt.states.ntp.html#module-salt.states.ntp

**Comment by eliasp** [comment]
Until recently, there was no standard API to do this on Linux.

Now, with systemd being used by nearly every distribution, this could be supported on all of them using systemd-timesyncd/timedatectl or the [respective D-Bus interface](http://www.freedesktop.org/wiki/Software/systemd/timedated/) of `timedated`.

This should be only supported on systems with systemd >= 216 due to this change in release 216:

        * timedated no longer reads NTP implementation unit names from
          /usr/lib/systemd/ntp-units.d/*.list. Alternative NTP
          implementations should add a

            Conflicts=systemd-timesyncd.service

          to their unit files to take over and replace systemd's NTP
          default functionality.

Otherwise, a lot of additional checks, workarounds e.g are required for older versions.

See also #20392

**Comment by jfindlay** [comment]
Thanks for the feature request.  ntp support will definitely be something good to have.

**Comment by johnnybubonic** [comment]
please reopen; this is still desired.
