### ISSUE TITLE
Broken arg parsing on state.highstate

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#20507]
Using 2014.7 branch

```
# salt '*' state.highstate test_state saltenv=prod test=False
ipm1039.doman.de:
    TypeError encountered executing state.highstate: highstate() got multiple values for keyword argument 'test'. See debug log for more info.
```

**Comment by jfindlay** [comment]
@bechtoldt, will you provide the output of `salt --versions-report` and also the log output as indicated if there's anything interesting there?  Thanks.

**Comment by cachedout** [comment]
I can confirm that this is broken on 2014.7 as well as develop.

**Comment by rallytime** [comment]
@bechtoldt Did you mean to try `state.sls` instead of `state.highstate` in your command? `state.highstate` doesn't take positional arguments and the error you are seeing is expected behavior for `state.highstate`. 

For more info, check out these docs: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.highstate

**Comment by bechtoldt** [comment]
@rallytime 

> TypeError encountered executing state.highstate: highstate() got multiple values for keyword argument 'test'. See debug log for more info.

The argument 'test' was given once only. See above. I think the right message would be something like "unknown arg 'test_state'".

**Comment by rallytime** [comment]
Oh, I see what you mean. It's the wording of the error, not necessarily the fact that error happens. We can clean that up for sure.
