### ISSUE TITLE
Bower state module

### ISSUE THREAD

**Issue by aspyatkin** [saltstack/salt#20587]
Hello, SaltStack team!
Would it be possible to add a state module for Bower package manager support? I don't need all of commands, just `install` and `uninstall` commands (something like `salt.states.npm` - it has `bootstrap`, `installed` and `removed` commands).

**P.S.** I suppose I can work on this new state module. I have read the code for the `npm` state module and have found it pretty straightforward. I think it would not be too hard to implement the feature (just some time and proper testing, you know).

**Comment by jfindlay** [comment]
@aspyatkin, awesome, feel free to submit a pull request, thanks.

**Comment by aspyatkin** [comment]
@jfindlay, I made one commit in my `salt` fork - https://github.com/aspyatkin/salt/commit/b24c5bd5feacc582b589c67a66c39f122ce43136. It adds
1) bower module with `install`, `uninstall` and `list` functions  
2) bower state with `installed`, `uninstalled`, `bootstrap` functions

However, I have some questions. First, I used `dir_` variable instead of `dir` (to make pylint's score higher for these 2 files). I suppose that's contrary to other modules in SaltStack. So, should I change it?

Second, about tests. I saw a lot of testing code in salt repository, which one I should start with (unit, integration)?

Third, I have noticed that salt repository changes very quickly. And I already have some commits behind saltstack/salt in my fork. Before I finally submit a pull request, should I rebase all my commits to place them in order, one by one?

**Comment by jfindlay** [comment]
Salt has a mechanism for translating user-exposed function names that collide with builtin names:
```python
__func_alias__  = {
    'dir_': 'dir',
}
```
but for user-exposed function argument names, as you've said, overriding builtin objects to provide the user with a sane and consistent interface is generally preferred over the opposite and is recommended despite what pylint might think. :-)

You are very welcome to write tests for your submitted code, or really anything.  Unit tests are more abstract and therefore more difficult to think through, but are simpler to write otherwise, whereas integration tests are naturally easier to structure, but have more execution overhead because they require a bunch of salt daemons to be running before they can be run.  There are several examples of each for both execution modules and state modules.  If you want to talk about this further, I can try to find some specific examples for you to look at or also review your tests.

I recommend always fetching salt and rebasing on the branch you're going to submit a pull request to.  Obviously there may be some code change causing conflicts that will require some manual resolution, but also transient test problems may occur on the test runs because the pull request branch has old (broken) copies of some tests or pylintrc.

**Comment by aspyatkin** [comment]
Got it. I will take this into account.
