### ISSUE TITLE
Windows Installer (Separation/Downloader/Contains VC++)

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#20678]
The needs of the many out way the needs of the few.
Salt:
* Needs to be able to install by pulling itself from the salt master, e.g. the boot strap for windows.
* Needs to be able to upgrade itself and roll back. ( a mini minion/care taker which checks which version to run, or is kick off by salt minion)
* Needs to be able to install without internet access. i.e. not download VC++ (e.g. installer contains it) !!!!

Or put Leon Hedding suggestion in the doco, and support it as best practice. 
https://groups.google.com/forum/#!topic/salt-users/JXPET9Mzp2E
Cheers

**Comment by ssgward** [comment]
Great ideas @damon-atkins. Also, feel free to make this happen through contributing if others haven't.

**Comment by lorengordon** [comment]
Related: https://github.com/saltstack/salt/issues/18431

**Comment by twangboy** [comment]
@damon-atkins 

The VCRedist is no longer a prerequisite for salt.

The problem with salt upgrading itself has been an issue for a while. The problem is that the first thing the installer does is stop the salt-minion service. That in turn kills all processes associated with the salt-minion service, including the installer. We ran into this problem with the service module (service.restart) when you would try to restart the salt-minion service. The restart command is actually a stop and then a start. Restarting the salt-minion service would issue the stop command and die... The work around was to use the windows task scheduler to issue the command. This has worked well for restarting the salt-minion service.

So, I've implemented something similar with the above PR (https://github.com/saltstack/salt/pull/27991). It allows you to set a `use_scheduler` option in the software definition for salt (or any other installer that may need to use it). When set to True, the installer will be run by the task scheduler and will continue to install after the salt-minion service is stopped.

Because the salt-minion service is stopped, however, it will not return that the installation was successful. Instead you will see `Minion did not return. [Not connected]`. After the install is complete the salt-minion service will reconnect with the master and will continue to listen for commands.

This will only fix this problem for versions 2015.8.2 and newer.

**Comment by TheBigBear** [comment]
@twangboy, thanks for doing this, the disability to do upgrades of the minion has been a long standing nuisance.

And a  related questions, any rough idea as to when a 2015.8.2 windows minion installer might see the light of day? (and will this already include the newer python 2.7.10 base, to help with all the current download issues?)

**Comment by twangboy** [comment]
@TheBigBear Python 2.7.10 is included in 2015.8.1. I think we're trying to do a release every month or so... but there's usually something that delays to getting those out on a consistent schedule. Mostly building for all the different platforms. I think we wanted to get 2015.8.1 out two weeks after initial release. It ended up being more like a month. There's what we intend to do and then what actually happens. I don't think we've officially stated that we put out a new release every month so we're not held to that.... but that's kind of what we're trying to do.

**Comment by damon-atkins** [comment]
See also #30964 Provided a way to mange Windows Minion Updates (duplicated one of my dot points)
