### ISSUE TITLE
salt-winrepo root_dir has only limited effect

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#20736]
This is merely a question, and I probably got it wrong, but on a windows masterless minion with "`file_client`" set to "`local`" I would expect the "`c:\salt\conf\minion`" entry for "`root_dir`" set to "`c:\salt`" to have the effect that "`/srv/salt/win/repo`" thereafter refers to "`c:\salt\srv\salt\win\repo`" and not to "`c:\srv\salt\win\repo`" ?

So "`/`" should be assumed to now be pointing to "`c:\salt\`" because of the value of "`root_dir`"? No?

What is the `effect` or purpose of the `root_dir` setting otherwise?

It just seems "`wrong`" to me to having to refer to the local salt files as "`/salt/srv/salt/...`"? (is it just me?) 
I know the "`c:\salt\conf\minion`" "`root_dir`" entry does say it is the prefix for "`pki_dir, cachedir, log_file, sock_dir, pidfile`" but shouldn't it be for more than those?

**Comment by rallytime** [comment]
Thanks for the report @TheBigBear. I am not familiar with windows questions, but I know that @UtahDave or @shanedlee might be able to shed some light on your questions.

**Comment by twangboy** [comment]
@TheBigBear I assume you mean from the perspective of winrepo... as in when you're specifying the location of installer files stored locally, you would like to pass just from the `root_dir` and not the entire path. For example, instead of passing `c:\salt\srv\salt\win\repo` you could just pass `srv\salt\win\repo`. I believe you have to pass the entire path because your installer may not be in a location that is in the `root_dir`. For example, you may host the file on a file server, or on the web. Therefore, you must specify the full path to the installer.
