### ISSUE TITLE
Automatically check unless/onlyif condition after cmd.run

### ISSUE THREAD

**Issue by cmthornton** [saltstack/salt#20794]
`unless` and `onlyif` conditions should also be checked after the command in `cmd.*` states. The purpose of `unless` and `onlyif` are to prevent subsequent executions of the command, for example:

```
# install pecl "pkg" unless it's already installed
yum install -y php-devel && yes '' | pecl install pkg: # exits with non-zero status if pkg is already installed
  cmd.run:
    - unless: php -r 'if (!extension_loaded("pkg")) exit(1);'
```

Normally when salt executes this state it does the following:
- execute the `unless` condition
- execute the command, unless the `unless` condition succeeded
- continue onto the next salt state

I think the above flow leads to mistakes that aren't caught until the next time the state is executed. For example, if you replace the above `unless` condition with something that always fails, then the first time this state is executed, it would do what you expected it to do---install the package. But, the second time the state runs, it still attempts to install the package, and now the state fails. (`pecl` exits nonzero if the pkg is already installed).

_`unless` and `onlyif` should be like light switches that must change their state after the command has executed._ It's a programmer mistake/logic error in cases where an `unless` (or `onlyif`) condition is checked, the command gets executed, but a second check of the `unless` (or `onlyif`) condition shows that it is still in the same state that it was in, before the command was executed. If the second check of the `unless`/`onlyif` condition is the same as the first check, that means that the changes caused by the command have no effect on the `unless`/`onlyif` condition---but the `unless`/`onlyif` condition is what's used to check if the command should even be executed. That's a mistake.

I find this error to be especially problematic because it's not caught until the state is executed a second time, which means that an initial hightstate will succeed, but subsequent highstates may not.

I think the flow should instead be:
- run the `unless` command
- run the command, unless the `unless` command succeeded
- if the command was executed, run the `unless` command again, and this time it must succeed
- continue onto the next salt state

and similarily for `onlyif`.

To get the execution flow I think `cmd.*` states should have, I'm duplicating the `unless` and `onlyif` condition in the command, like so:

```
# install pecl "pkg", unless it's already installed
yum install -y php-devel && yes '' | pecl install pkg && php -r 'if (!extension_loaded("pkg")) exit(1);':
  cmd.run:
    - unless: php -r 'if (!extension_loaded("pkg")) exit(1);'
```

Appending `&& <unless command>` to the command has become an idiom in `cmd.run` states that I write, and it ensures that the `unless` condition does what I expect, without having to execute the state a second time to check. This reduces debugging time, and causes less surprises later on. But this isn't ideal either because now changes in 1 location need to be made in both.

My guess is that there are probably legitimate reasons---but unknown to me---for not checking the `unless` or `onlyif` condition to make sure it has changed after the command has been executed. If that is the case, then is there any way to get the behavior I (and I think many others) expect without having duplicate commands/conditions?

**Comment by basepi** [comment]
So I have a few thoughts on this.

I understand your use case and frustration -- I think the most common use case for `unless` and `onlyif` is to check for a "problem" or state, and then fix that state before moving on.

However, it's far from the only use case, and assuming that someone doesn't the state run to continue because the `unless` hasn't changed is something we don't want to do.

So no, I don't think we're going to change the behavior of `unless` in this way.

All of that said, your use case is a valid one, so we need to make sure there's a good, clean way to implement this in the state system.

I think the behavior you're describing is really just the behavior of states in general -- we check for state, if the state isn't correct, we fix the state, and then we often will check the state again to generate changes. A good example is `pkg.installed`. We check if the package is installed; if not, we install it; then we check if it is installed again, and choose our return status based on that.

So, my number one recommendation would be to create a custom state. It's fairly straightforward, and you have a lot of great tools to leverage the rest of salt: http://docs.saltstack.com/en/latest/ref/states/writing.html

If you really just want to check the `unless` or `onlyif` after the state, I would add a [test.fail_without_changes](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.test.html#salt.states.test.fail_without_changes) state with the `unless` or `onlyif` on it, and set `failhard: True` in your config. That way if your `unless`/`onlyif` doesn't change, the test.fail state will run, and your state run will abort.

Hopefully that helps.

**Comment by cmthornton** [comment]
Thanks for taking the time to look into this, and for advice on how to resolve the issue. I will look into writing a custom state shortly.

>
> so we need to make sure there's a good, clean way to implement this in the state system.
>

I agree. 

Commands have numerous side effects that must be considered before and after execution. There will never be a generic `cmd.*` that handles every case, that's why more specialized states, like `mysql.grants`,`pkg.installed`, etc., exist.

However, I do think having a `cmd.<something>` state that checks `unless`/`onlyif` conditions after the command has executed would lead to more predictable behavior, because this `cmd.<something>` state would not cause an unexpected failure on subsequent highstate runs for the use case I described above.

**Comment by basepi** [comment]
I suppose we could do something like add a `will_succeed` arg or something to `cmd.run` which checks if the `will_succeed` command succeeds after the command is run... Hrm, I'll have to think on this.
