### ISSUE TITLE
file.uncomment state does not support multi-character comment markers

### ISSUE THREAD

**Issue by Bilge** [saltstack/salt#20857]
[`salt.states.file.uncomment`](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.uncomment) appears to only support single character comment formats.

Attempting to uncomment a line beginning with `//` with either of these configurations:

* `- char: /`
* `- char: //`

...gives the following error.

> Expected uncommented lines not found

**Comment by jfindlay** [comment]
After having looked through the salt/modules/file.py file, I cannot see anything that would prohibit multichar comment symbols, but I did find that file.comment and file.uncomment are using file.sed, which is deprecated, rather than file.replace.  @Bilge, will you post the output of `salt --versions-report`?  Thanks.

**Comment by rallytime** [comment]
I am going to close this since we never heard back. If this problem lingers, please comment below and we will certainly re-open this and address any concerns. Thanks again!

**Comment by shallot** [comment]
This might have been an undiagnosed case of https://github.com/saltstack/salt/issues/40827
