### ISSUE TITLE
develop: highstate interfers with __opts__ (breaks at least tls mod)

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#20908]
I think by the lazyloader stuff,  __opts__ is not more global for all modules
```

(Pdb) __salt__['tls.set_ca_path'].__globals__['__opts__'] is  __salt__['config.option'].__globals__['__opts__'] 
False
```

**Comment by kiorky** [comment]
cc @jacksontj

**Comment by jacksontj** [comment]
Just because they aren't the same object doesn't mean they dont contain the same items. There was some code in the old version of the loader which will *update* any __opts__ dict defined in the module (instead of clobbering it).

**Comment by kiorky** [comment]
Problem is that for immutables, it's a problem as overloading a value from one module is not reflected in the __opts__ of the other one.

**Comment by kiorky** [comment]
problem is here: https://github.com/saltstack/salt/blob/develop/salt/loader.py#L831

**Comment by kiorky** [comment]
(in other words, config.option is now useless when you try to change something in __opts__, it wont be picked up)

**Comment by jacksontj** [comment]
I'm not disagreeing that it is confusing, but it has existed forever (https://github.com/saltstack/salt/blob/2014.7/salt/loader.py#L540)-- I kept it around to maintain backwards compatibility.

**Comment by kiorky** [comment]
Nope, before __opts__ was the same object, without that the tls module could never work. (and i use it a lot)

**Comment by kiorky** [comment]
maybe https://github.com/saltstack/salt/blob/develop/salt/loader.py#L689 & https://github.com/saltstack/salt/blob/develop/salt/loader.py#L705 should try to use the same obj rather than reinstancing ?

**Comment by jacksontj** [comment]
As I mentioned in my last comment, that is the *exact same function* from the old loader. Maybe someone has added a reference to __opts__  in the global namespace since last you used the module? If so it would change the behavior.

Also, why do you say that the tls module wouldn't work if they weren't the exact same object? Modules should care about the contents of the dict *not* that they necessarily point to the same space in memory.

**Comment by jacksontj** [comment]
If your tls module isn't working it might be more productive to paste the command and output from the failed command run.

**Comment by kiorky** [comment]
Damn, i think i have a problem otherwhere, closing this for now ...
But to reprocude at first my idea was this simple function:
```

def ssl():
    __salt__['tls.set_ca_path']('foo')
    return (__salt__['tls.cert_base_path']())


```

**Comment by jacksontj** [comment]
Hmm, looks like https://github.com/saltstack/salt/blob/develop/salt/modules/tls.py#L60 should be using __opts__ instead of __salt__['config.option']

**Comment by kiorky** [comment]
nope, that's intended to also look in pillar or grains

**Comment by kiorky** [comment]
Damn, i think this is a context problem, because in a highstate, i really have a problem
```

```

**Comment by kiorky** [comment]
so to reproduce:

/srv/salt/_modules/my.py
```
def ssl():
    __salt__['tls.set_ca_path']('foo')
    return (__salt__['tls.cert_base_path']())

```
/srv/salt/_states/my.py
```
def ssl(name):
    __salt__['my.ssl']()
    return {'result': True,
            'changes': {},
            'name': name,
            'comment': __salt__['tls.cert_base_path']()}

```

/srv/salt/a.sls
```

foo:
  my.ssl: []

```

INCORRECT state.highstate see pki
```
local:
----------
          ID: foo
    Function: my.ssl
      Result: True
     Comment: /etc/pki
     Started: 00:21:29.490412
    Duration: 0.655 ms
     Changes:   

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1

```

state.sls (CORRECT):
```
local:
----------
          ID: foo
    Function: my.ssl
      Result: True
     Comment: foo
     Started: 00:23:58.383938
    Duration: 0.619 ms
     Changes:   

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1

```

**Comment by kiorky** [comment]
So, we see that with highstate, we have not the same behavior that with calling sls, something in highstate changes how that __opts__ dict is dealt.

**Comment by kiorky** [comment]
@jacksontj this diff seems to resume the initial behavior, but i am not sure yet of it is right or not.

```
diff --git a/salt/loader.py b/salt/loader.py
index 7721d72..71cf5f3 100644
--- a/salt/loader.py
+++ b/salt/loader.py
@@ -118,6 +118,7 @@ def minion_mods(opts, context=None, whitelist=None, include_errors=False, initia
                      pack={'__context__': context},
                      whitelist=whitelist)
     ret.pack['__salt__'] = ret
+    ret.pack['__opts__'] = opts
     if notify:
         evt = salt.utils.event.get_event('minion', opts=opts)
         evt.fire_event({'complete': True}, tag='/salt/minion/minion_mod_complete')
```

**Comment by jfindlay** [comment]
@kiorky, I know there was some effort recently to make `__opts__` immutable on develop, whereas it wasn't previously.  Do you think the tls module is broken because it now produces inconsistent results now that `__opts__` is immutable?

**Comment by kiorky** [comment]
yep, that is the goal of this commit, an opts copy is shared amongst exec mods (self.functions) and one amongst states mods (self.states)

**Comment by jacksontj** [comment]
@kiorky as @jfindlay mentioned, the opts dict is (by design) immutable. In the past it was just a dict, which has caused some confusion (such as this) since *some* places pass copies, some pass references, or some do whatever they want. __opts__ (in the loader) has *nerver* had a gaurantee of consistency across modules, nor is it intended to. If modules need to share context between execution they should use __context__ (which *does* guarantee consistency correctly now).

**Comment by kiorky** [comment]
well, i know of tls mod and it can switch over to context yes, but we may have broken here others modules with that change, i ll have a look tomorrow to switch tls mod to context.

**Comment by kiorky** [comment]
did you saw the related PR which allow to conserve the old behavior where opts was somewhat shared.

**Comment by kiorky** [comment]
cc @thatch45 , do you have any feeling on this ?

**Comment by kiorky** [comment]
(my first intention on that PR was to make something transparent for consumers (exec mods) & backward compatibility)

**Comment by jacksontj** [comment]
@kiorky that PR doesn't "preserve old behavior" it changes the old behavior. If you look at how the old loader packed the opts the new one uses a complete copy-paste of the method (https://github.com/jacksontj/salt/blob/2014.7/salt/loader.py#L647 vs https://github.com/jacksontj/salt/blob/2015.2/salt/loader.py#L963 for example). 

The problem you are running into is that since it isn't guaranteed many *many* things can mess it up:

- Loading plugins in a different order
- Using the same process to load the module twice
- a module with __opts__ defined

And probably a bit more that I can't think of.

**Comment by kiorky** [comment]
@cachedout @jacksontj @thatch45 i think #29014 is afterall not on the line salt is going.

Im going to fix the tls mode to also use context retrieval.

Im also reverting that stuff in our local install.

**Comment by cachedout** [comment]
Thanks @kiorky

**Comment by kiorky** [comment]
fixed !
