### ISSUE TITLE
No module named cli.caller

### ISSUE THREAD

**Issue by masterkorp** [saltstack/salt#20924]
Hello,

After an apt-get update salt is totally broken.
When trying to run the ``postgres.version``` module:

```
root@salt-master:/srv/saltstack# salt "mydbserver*" postgres.version
Traceback (most recent call last):
  File "/usr/bin/salt", line 6, in <module>
    from salt.scripts import salt_main
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 17, in <module>
    import salt.cli
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 13, in <module>
    import salt.cli.caller
ImportError: No module named cli.caller
```

```
root@salt-master:/srv/saltstack# salt --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt", line 6, in <module>
    from salt.scripts import salt_main
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 17, in <module>
    import salt.cli
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 13, in <module>
    import salt.cli.caller
ImportError: No module named cli.caller
```

Using ``Ubuntu 14.04 LTS`` here is the version of the package.

```
root@salt-master:/srv/saltstack# dpkg -s salt-common 
Package: salt-common
Status: install ok installed
Priority: extra
Section: admin
Installed-Size: 8660
Maintainer: Joe Healy <joehealy@gmail.com>
Architecture: all
Source: salt
Version: 2014.7.1+ds-3trusty1
Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), python-dateutil, python-jinja2, python-apt, python-yaml, python-pkg-resources, python-requests (>= 1.0.0)
Recommends: lsb-release, python-mako
Suggests: salt-doc (= 2014.7.1+ds-3trusty1)
Breaks: python-mako (<< 0.7.0)
Conffiles:
 /etc/bash_completion.d/salt-common ec159a8aed32a921713dea4d8a2a8883
 /etc/ufw/applications.d/salt.ufw 05b63e0432aa816e5e9e73e11f2e977c
 /etc/logrotate.d/salt-common c4a63a8a6030f7b82d8e957bd47e3c72
Description: shared libraries that salt requires for all packages
 salt is a powerful remote execution manager that can be used to
 administer servers in a fast and efficient way.
 .
 It allows commands to be executed across large groups of
 servers. This means systems can be easily managed, but data can
 also be easily gathered.  Quick introspection into running
 systems becomes a reality.
 .
 Remote execution is usually used to set up a certain state on a
 remote system. Salt addresses this problem as well, the salt
 state system uses salt state files to define the state a server
 needs to be in.
 .
 Between the remote execution system, and state management Salt
 addresses the backbone of cloud and data center management.
 .
 This particular package provides shared libraries that
 salt-master, salt-minion, and salt-syndic require to function.
Homepage: http://saltstack.org/
```

**Comment by jfindlay** [comment]
@masterkorp, I have had this problem before but only from installing different git revisions with pip.  It is caused by .pyc files leftover from the previous version.  I have not seen this happen with distro packages.  Did you install with pip at any time on this system?  The solution is to ensure that all .pyc and .pyo files are removed/regenerated.  You can try something like:
- `find /usr/lib/python2.7/dist-packages/salt/ -name '*.py?' | xargs rm -v`, or
- `sudo aptitude purge salt-* # ensure that you've backed up your configs that this might remove`

**Comment by masterkorp** [comment]
Hello @jfindlay 

I did this, and the problem still persists.

**Comment by masterkorp** [comment]
Ok, only removing the whole ``salt`` folder. on ``dist-packages`` did the job. Thanks.

You can close this issue. But I would like to see proper solution for this.

**Comment by hobakill** [comment]
This helped me out just now. Thanks!

**Comment by rallytime** [comment]
The `cli` stacktrace that you are seeing here is due to some large refactors that are present on 2015.2 branch and not on the 2014.7 branch. When you switch from 2015.2 (or newer) code back to 2014.7, the compiled .py files need to be replaced. I have to switch back and forth several times a day, and this is definitely frustrating. However, the good news is that it should not be an issue when installing from packages, and will no longer be a problem as we move away from the 2014.7 branch within the next couple of weeks when 2015.2.0 is released.

Thanks again for the report, and I am glad that the work around we provided helped you guys.

**Comment by 0xPaul** [comment]
:+1: `sudo rm -rf /usr/lib/python2.7/dist-packages/salt` worked for me.

**Comment by ashmckenzie** [comment]
After experimenting with different versions on Mac, I found I had to remove everything salt:

`sudo rm -rf $(brew --prefix)/lib/python2.7/site-packages/salt*`

This solved the problem for me :)

**Comment by lichtamberg** [comment]
I also had to remove the whole build folder, following worked for me on OSX:

```shell
sudo rm -rf $(brew --prefix)/lib/python2.7/site-packages/salt
# in build dir of salt
sudo rm -rf build
```

**Comment by rallytime** [comment]
Awesome! Thanks for posting that info @lichtamberg.

**Comment by ross-p** [comment]
This just happened to me on a brand new VM.  I tried to install Salt via bootstrap-salt.sh and install 2014-7, and it was giving me this error.

When I do the install, I specify salt 2014.7 and I specify to use pip when installing.  The salt bootstrap script is pretty buggy though, it rarely ever installs the correct git version the first time.  So apparently now it's installing 2015.2 by default and then trying to revert back to 2014.7 which is giving this error.

To fix it I took the advice from above and ran (Debian wheezy):

```bash
sudo rm -rf /usr/lib/python2.7/dist-packages/salt
```

And then bootstrap-salt again and finally it's installed.
