### ISSUE TITLE
postgresql: user roles are never updated

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#20980]

**Comment by notpeter** [comment]
@kiorky This change made it so that every postgres_user.present (even no change) can result in dozens of SQL queries. Your code queries for the list of roles, iterates through that list in python issuing one query per role present on the server.

So instead of querying like this inside the for loop (1 query for each server role)
````
select rolname from pg_user
join pg_auth_members on (pg_user.usesysid=pg_auth_members.member)
join pg_roles on (pg_roles.oid=pg_auth_members.roleid)
where pg_user.usename=\'{0}\'
````
It could instead issue a single query outside the loop and get the same results for all users:
````
select rolname from pg_user
join pg_auth_members on (pg_user.usesysid=pg_auth_members.member)
join pg_roles on (pg_roles.oid=pg_auth_members.roleid)
where pg_user.usename IN ['user1','user2','etc']
````
