### ISSUE TITLE
Import not possible for custom module with dependencies inside another custom module

### ISSUE THREAD

**Issue by matdrapeau** [saltstack/salt#21029]
Related to this issue:
https://github.com/saltstack/salt/issues/16556

With such example:

```
# cat > ping.py
from ling import *

# cat > ling.py
def ping():
    return True
```

Running this command from master `salt 'machine1' ping.ping` is returning this error:

```
machine1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1133, in _thread_return
        sys.modules[func.__module__].__context__['retcode'] = 0
    AttributeError: 'module' object has no attribute '__context__'
```

possible fix: https://github.com/saltstack/salt/pull/20998

**Comment by matdrapeau** [comment]
Inside ```_load_module``` function, the ```mod``` that is returned by ```imp.load_module``` will contain the actual function ```ping``` and when calling the ```__module__``` of that function, it will return ```ling```.

So the ```__module__``` is not referring to the module that has been loaded.

Then if you load ```ping``` before ```ling```, the later won't be loaded since it will added to the list of loaded module already even if not.

A bit hard to explain, you need to follow the trace and load ```ping``` before ```ling```

**Comment by basepi** [comment]
The function called from the CLI must be defined within the file in question, so that the loader can provide the correct magic variables. For example, I would expect this to work:

```
# cat > ping.py
import ling

def ping():
  return ling.ping()

# cat > ling.py
def ping():
    return True
```

Because the loader does a fair amount of magic with called functions, I wouldn't recommend doing a `from module import *` and then try to call those modules in their newly-imported form.

**Comment by matdrapeau** [comment]
Hello Colton,
I'm aware of your suggestion except that the provided fix is handling
legitimate python imports too.
There is plenty of other examples using similar imports that could be
useful, but the example I provided was a simplistic way to expose the
problem.

**Comment by jacksontj** [comment]
@basepi FYI there was some discussion about this in #21146

**Comment by basepi** [comment]
I am not a fan of black magic. =\

**Comment by matdrapeau** [comment]
I am a big fan of DRY principle
Since you cannot import functions from another module you end up repeating yourself!

**Comment by basepi** [comment]
@matdrapeau So something like this won't work?

```
import mymodule

def myfunction():
    return mymodule.another_function()
```

assuming that `another_function` is defined in that other module?

**Comment by jacksontj** [comment]
@basepi If I'm not mistaken, the problem was that in "mymodule" __salt__ (or some other injected global) was used. Since in your example above it was imported using the python importer "mymodule" will have access to none of those globals-- hence the problem :)

**Comment by basepi** [comment]
Ah, yes, that is a problem. I think we're not going to support importing helper modules which use salt magic variables. We already have a very easy mechanism in place -- custom modules are loaded into `__salt__`, so if you ship `mymodule` as a custom module as well, then you can do this:

```
def myfunction():
    return __salt__['mymodule.another_function']()
```

Since there's already a great mechanism in place, I don't think we're going to write all the magic required to make those imports work.
