### ISSUE TITLE
master_type failover does not failover on DNS errors

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#21082]
With the following minion configuration:
```sls
master:
  - salt.mydomain.com
  - 24.25.26.28

master_type: failover
```

If the first server cannot be resolved by DNS, the minion continuously logs
```
DNS lookup of 'salt.mydomain.com' failed.
Master hostanme: 'salt.mydomain.com' not found. Retrying in 30 seconds
```

It never fails over to the second entry.

**Comment by jfindlay** [comment]
@clinta, thanks for the report.

**Comment by rickh563** [comment]
ZD-342

**Comment by DmitryKuzmenko** [comment]
This works as the following: if minion gets a list of masters it loops through the list trying to connect until the first success. If dns lookup fails minion retries infinitely with interval set by retry_dns config option. If retry_dns is set to 0 it works as expected: minion tries the second entry after dns lookup failed.

What's expected behavior if retry_dns is non-zero in failover case? Shall minion just ignore retry_dns in this case? Or shall it connect to the second master but still periodically check the first one?

**Comment by DmitryKuzmenko** [comment]
The fix isn't for this issue but related because master list case doesn't work even if all masters in the list are accessible.

**Comment by DmitryKuzmenko** [comment]
As discussed PR #25404 forces retry_dns to 0 if master_type is set to failover.
