### ISSUE TITLE
Recommended project repository structure

### ISSUE THREAD

**Issue by dtoubelis** [saltstack/salt#21124]
I'm starting a new project for managing large scale deployment spanning multiple datacenters. I have Chef background but I want to try SaltsStack for this one. Obviously, I want to keep all code in a repository (git for this project) and I couldn't find a definitive answer to what is the recommended repository structure for saltstack project?

It seems that SaltStack does not support versioning but relies on external tools for this instead, so I was thinking about having different branches in git repository for dev,qa and prod environments. However, I could not wrap my head around how to fuse this all together. I went through documentation several times with no avail. It seems that SaltStack treats states, pillars, formulas, reactors and configurations separately and each in it's own way as if they are not intended to work together.

Please help.

**Comment by terminalmage** [comment]
Can you tell me what you mean by "configurations"?

Pillar environments have no relation to fileserver environments. Pillar environments are just a way to organize your pillar data. When pillar data is compiled, all pillar environments are evaluated and the result is a dictionary of pillar data for a given minion.

I made some recent additions to the fileserver backend documentation, they're not merged forward to develop yet (and thus not on docs.saltstack.com), but [here](https://github.com/saltstack/salt/blob/2014.7/doc/ref/file_server/backends.rst) is a link to them. [This page](http://docs.saltstack.com/en/latest/topics/tutorials/states_pt4.html) shows some of the same information from the previous link, but shows how files can be laid out in the default fileserver backend.

For what you want to do for git, the best way of achieving this would be to use a "merge-forward" git workflow. For example, changes are made first in dev, then merged into qa, then merged into develop. Never from dev directly to develop. In the git fileserver backend, branches and tags map to fileserver environments, so when a commit is pushed to dev then that change is only available to the "dev" fileserver environment. This goes both for git repos containing source code for your projects, but also for states you may have configured in git.

For instance, assuming that you have the following state configured in each of the ``dev``, ``qa``, and ``prod`` branches, within a file called ``deploy.sls`` in the root of the git repo:

```yaml
my-awesome-webapp:
  file.recurse:
    - name: /var/www/awesomewebapp
    - source: salt://webapps/awesomewebapp
    - clean: True
```

If you run the command ``salt devweb01 state.sls deploy saltenv=dev``, then the effective fileserver environment for the command is ``dev``. This means that the SLS file that is processed will be deploy.sls from the ``dev`` branch of the repo containing your SLS files, and any states which deploy files will use the ``dev`` environment (that is, the ``dev`` branch in git) to do so, meaning that the ``dev`` branch of the repo containing your webapp will be used.

Note that, by default, salt will address files in git starting at ``salt://``, so files in the root of the repo would be ``salt://foo.txt``, ``salt://bar.txt``, etc., and files in a subdirectory ``bar`` would be ``salt://bar/file1``, ``salt://bar/file2``, etc. If you are using Salt 2014.7.0 or later though, you can set a "mountpoint" to better organize your gitfs remotes. See [here](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#mountpoints) and [here](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#per-remote-configuration-parameters) for examples of how to configure mountpoints. Using mountpoints would allow you to use ``salt://webapps/awesomewebapp`` to refer to your webapp's files instead of needing to have the leading directory (or directories) sitting in the root of your webapp's git repo.

**Comment by terminalmage** [comment]
I added the Documentation tag here because I think we could describe this better in the docs. I'll try to get some iteration of the above explanation to the walkthrough.

**Comment by dtoubelis** [comment]
I was planning to use pillars for datacenter specific configuration (i.e. network CIDR, database URL, etc.) and making states datacenter agnostic. However, I want pillars to be versioned as well in a sense that for states in `prod` branch use pillars from `prod` branch too.

By configurations I mean everything that goes under `/etc/salt`. Since GitFS configuration is tightly related to minion targeting I want to keep it in the same repo.

Do you by any chance have a working example of repository structure for similar project?

**Comment by terminalmage** [comment]
I don't, but that would be another good example of something that could be added to the docs.

With regards to the git external pillar, be advised that it is separate from the git fileserver backend and is slated for a rewrite for the next feature release (due late spring 2015). It doesn't yet have nearly the same featureset as gitfs.

**Comment by terminalmage** [comment]
How are you planning on deciding how your pillar variables should be assigned? By server naming convention? Some other algorithm? Perhaps I can get you pointed in the right direction.

**Comment by dtoubelis** [comment]
Yes, servers in each datacenter will have specific prefixes, so I can target by datacenter. Server names will also include environment and function, so I should be able to use them for targeting states. Still do not have complete picture how it may work.

**Comment by terminalmage** [comment]
OK. This data seems static enough that Grains might be a better place for it.

If you can write python, you might consider writing a custom grains module and dropping it in the ``base`` environment's ``_grains`` directory. This will allow you to keep the grain data in version control, and also scales better (both in terms of efficiency and in terms of maintainability) than a long chain of jinja blocks in a pillar file.

Note that the docs there say ``file_roots`` but I'm pretty sure this works for any fileserver backend. That piece of the documentation is old and predates the modular fileserver backends.

**Comment by terminalmage** [comment]
Whoops, forgot to put the link to the docs in my earlier comment, edited it.

**Comment by dtoubelis** [comment]
Are you suggesting to use custom grains instead of pillars? It is actually not a bad idea but I wnated to confirm :-)

**Comment by terminalmage** [comment]
Yes, just a suggestion. The types of data to which you were referring aren't likely to change often, so they are a good fit, IMO, for a custom grain. The potential downside of a custom grain versus Pillar data is that you'd need to write Python code for it, and not everyone is able to do that.

Just offering another option for you. :smile:

**Comment by dtoubelis** [comment]
Sounds good, I can write python, not a problem. Also, could you confirm that `top.sls` always served from base environment and there is no way to keep it versioned?

**Comment by kiorky** [comment]
Depending on your needs, you can also have a look to ext_pillars.
For example, here we use this: https://github.com/makinacorpus/makina-states/blob/master/mc_states/pillar/mc_pillar.py which use under the hood: https://github.com/makinacorpus/makina-states/blob/master/mc_states/modules/mc_pillar.py

**Comment by kiorky** [comment]
The inputed configuration from this ext_pillar is based on https://github.com/makinacorpus/mastersalt-pillar/blob/master/database.sample.yaml

**Comment by dtoubelis** [comment]
I tried different options based on suggestions above and I ended up having a separate repository for pillars to keep secrets separate from configuration and I keep states in a separate repository. Now I need to worry about keeping branches/tags consistent between the two but this is something we can live with. But then we have `top.sls` files that are still not under version control. It seems like they  logically belong to configuration but functionally tied to states and as a result do not fit anywhere. The similar situation is with reactors. It looks like a total mess so far and I don't see any way around it.

Systems like `saltstatck` are intended to fulfill "configuration as a code" principle and code belongs to repository, so if `saltstack` configuration cannot be saved in repository in any sensible way then it is a design flaw. I think this area needs substantial and urgent improvement.

**Comment by kiorky** [comment]
Nothing is preventing you from versioning something into the salt file_roots.
Nothing is also preventing you from versioning you pillar, which indeed needs to reside in another, more limited access repo.

Here at @makinacorpus we have made a small layer upon salt which links a special dir  (``.salt``)from our repo into the salt dir and is dedicated to the deployment (sls, modules, & other files), along side with another repo dedicated to the pillar which would also linked into the pillar root.

eg: https://github.com/makinacorpus/corpus-django, see the .salt folder (this implements https://github.com/makinacorpus/corpus.reactor/blob/master/doc/spec.rst and is implemented by https://github.com/makinacorpus/makina-states/blob/master/mc_states/modules/mc_project_2.py).

**Comment by dtoubelis** [comment]
Yes, I think 2 repository configuration is a way to go for states and pillars. Not sure what to do with top.sls though. I saw some suggestions to put it in a  separate repository but it works only half way and looks silly. What about salt-cloud configurations? Is there a sensible way to keep them in a repository?way

**Comment by DanyC97** [comment]
@terminalmage i guess nothing was added to docs?

**Comment by satellite-no** [comment]
Just stumbled upon this and was curious if a recommended git repo project structure was defined anywhere?
