### ISSUE TITLE
cmd.run_chroot can maybe be improved

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21192]
Regarding in detail this function, the mount & umount step should maybe more careful (checking & acting only if necessary), the umount should also only umount if the previous mount mounted something

cc @terminalmage 
refs saltstack/salt#21190 saltstack/salt#21189

**Comment by basepi** [comment]
Running a `umount` with nothing mounted shouldn't be a problem, should it? It will just report that there was nothing to unmount.

But yes, it would probably be useful to check before mounting whether the mounting needs to actually happen. Though if something's already mounted there we should probably just fail, because we won't be sure that the right thing is mounted...

Anyway, this function appears to be very new, and probably needs a little bit of TLC.

**Comment by kiorky** [comment]
This is not a problem or mount or umount but of state preserval.
Here we call a chrooted cmd in an arbitrary mountpoint which could have been used (and stiff used) by something else.

My idea so far is to keep the previous state of activation for each touched mountpoint when we have run back to the state we have initially (mounted or umounted).

**Comment by kiorky** [comment]
We also maybe should mount sys, & dev/pts
