### ISSUE TITLE
Vote to move zcbuildout module and state to salt-contrib

### ISSUE THREAD

**Issue by thatch45** [saltstack/salt#21209]
I am going to try something new, I might regret it though, as I don't want decisions to be made by casting open votes all the time. But I just want to guage the interest here, so this is a bit of an experiment.

I am leaning toward the removal of zcbuildout from the mainline modules, it has been a problem in the test suite since it was introduced, has been problematic for users and is not widely used. So far it has been heavier to maintain then we think it is worth.

So I propose that we move the zcbuildout module and states into salt-contrib. But I would like to take a vote on who would like to see it stay or if I am miss reading the situation.

**Comment by thatch45** [comment]
+1

**Comment by terminalmage** [comment]
No objection from me on that. It's easy to deploy modules via ``_modules``, and the test suite would thank us for it.

**Comment by cro** [comment]
+1

**Comment by techhat** [comment]
+1

**Comment by kiorky** [comment]
Guess what, i will be the silent majority.

**Comment by kiorky** [comment]
cc @regilero @toutpt @fle @gagaro @jpcw @ebrehault @davisp1 @gutard @leplatrem

**Comment by s0undt3ch** [comment]
+1

**Comment by cachedout** [comment]
I think votes are a tricky way to manage these issues but I do think it would be a good idea to figure out how to extend the test runner to optionally test contrib modules.

**Comment by s0undt3ch** [comment]
The test runner for external modules is an almost complete feature, but not yet ready, branch on my fork.

**Comment by cachedout** [comment]
I should have known you were already on it! Thanks, @s0undt3ch

**Comment by thatch45** [comment]
The main problem here is that the zcbuildout module has been built for the specific use case of @kiorky and his team, and I don't think that the core team should be responsible for it is all, it is not hard to add it to _modules on your salt masters.
@kiorky you don't need to fork ALL salt modules! Salt is made to allow for plugins like this. I am not trying to take the module away from you, I am trying to free up Salt's resources so that we can focus on general purpose code, not special use case code.
Please just use _modules @kiorky:
http://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

The problem we keep running into is that your special use cases are not generic enough to be distributed in mainline salt.

**Comment by kiorky** [comment]
@thatch45, thx,
i already now about '*_dirs',  btw we are going to fork on our salt infra all core modules that break over time to get stabilization ourselves as we just feel morons here, we wont bother you again, nevermind.
We certainly are going on a monkeypatch to patch what's needed in salt core, like the utf8 handling in vt, or the horrible hardfail on highstate which is coming in next release.

**Comment by thatch45** [comment]
We changed the hardfail on kwargs, and we will get the vt patches in, it is not all or nothing.

**Comment by kiorky** [comment]
Also,
I don't think that zc.buildout is @makinacorpus specific, don't i.

All the failures that had gone over time were legit and because of others changes, and i mainly fix most of them.
If you are concerned about the extensive test suite of the module, you can also disable it ;).
If will be not as there was not any untested code on salt-core, where will be the difference ;).

For the kwargs/hardfail, what's @s0undt3ch got in is temporary until a release, in other words run back in order to give a better jump forwards on hardfailing again, soon or later it will bite again.

**Comment by thatch45** [comment]
Right, we want to hardfail on these, this is in high demand and has been in high demand for a long time. we are extending the time and changing the error messages to make it more visible. This will make every state be seen that will be hardfailing.

**Comment by kiorky** [comment]
Where it is a oneline for the final user to change the behavior based on a config opt, how awsome could it have been.

**Comment by thatch45** [comment]
I have no problem making this configurable. But you prefer to fight me instead of presenting solutions.

**Comment by s0undt3ch** [comment]
I'm late to the conversation but a configurable option will just help @kiorky and it will also help users to continue maintaining wrong states. I still think that two major releases should be time enough for users to update their states.

@kiorky what's wrong with making your states accurate?

**Comment by kiorky** [comment]
@thatch45 ??? i proposed the toggle options for 21 days (the date at which i did discover the deprecation path), no one did give me a go on it.
I'm not for maintaining wrong states, i'm just against hardfalling and losing the users where the warning is more friendly for them.
I agree that position may not be mainline, but it is easy here in the implementation to make it configurable.

**Comment by s0undt3ch** [comment]
If you are getting the warnings, then yes, you have wrong, old, non updated, states. If you're sure you don't have them, then it's probably something we missed and a file report should be filed to correct that.

**Comment by thatch45** [comment]
Where did you propose it? It was not in your PR. I am all for making it a config option.

**Comment by s0undt3ch** [comment]
Also, the idea of the `warnings` in the state returns will not go away, but once the hard-fail stage starts, the warnings will be exclusive for upcoming deprecation notices.

**Comment by kiorky** [comment]
@thatch45 #20227 
https://github.com/saltstack/salt/issues/21120#issuecomment-76562539
https://github.com/saltstack/salt/issues/21120#issuecomment-76465446
https://github.com/saltstack/salt/issues/21120#issuecomment-76433268
https://github.com/saltstack/salt/issues/21193#issuecomment-76640771

**Comment by basepi** [comment]
@kiorky:
> btw we are going to fork on our salt infra all core modules that break over time to get stabilization ourselves as we just feel morons here, we wont bother you again, nevermind.

Please refrain from name-calling. It's not acceptable behavior.

**Comment by kiorky** [comment]
@basepi, sorry, but i was answering to @thatch45 , there is no name-calling or personal nuisance intention here.
if you had read better the sentence, you should not have continue to post here as yes, you slapped us, and yes we are now just reacting.
This reaction is at the moment to fork and lower down our noise on our contributions (tickets/pr/code) on yours as it seems more to annoy you than being beneficial for the both of us.

**Comment by basepi** [comment]
Sorry I misread, @kiorky. Sometimes there's a bit of a language barrier, since you're not a native English speaker. =)

Anyway, your contributions are not always annoying. But you have to realize that this is a project with many thousands of users. So we as project maintainers need to make sure that we ship the best product possible for our users as a whole. This may mean we go in a direction that doesn't best fit your use case, and we apologize for the inconvenience that might cause. Anyway, I'll follow up more via e-mail.

**Comment by kiorky** [comment]
Please stop making fud about zcbuildout tests.
That modules has always been maintained in time, once it fails the tests, and this mostly by me.
The ''runas'' deprecation was also done partly by me and there for a while, we are speaking about the reintroduction of it because it can really be harmful not to have it anymore on old and not upgraded setups.

Indeed, you may know that running buildout with another user that the one inquired can be a disaster, the more on production.
That's why i wanted to reintroduced 'runas', yesterday, as the damages that it would inflict, eg on a zope cluster, can really be disastrous.
Really, for me, i wouldn't care, i would know how to fix my mistakes here.
Most of my coworkers in case of an highstate fail will cry, at best fix, but they wont run because their deployment procedure ended up with a trace, just with a failure report.
On the other hand, with a trace, they just think that it's too complicated whenever it breaks (even for a 5 states sls files...). Most of them are likely not using salt for that (and other) use case anymore.

A twoliner deprecation warning that we don't remove and does not harm will save salt user time & experience.

Again, zcbuildout was/is neither makinacorpus or @kiorky dependant specific use case, nor how was written the module. The module fetch bootstrap, intellegitently combine the buildout bootstrap args (there is a matrix of hell about buildout/distrbute/setuptools versions that can be used together or not) and run buildout. Nothing specific. Most of the tests were also about testing that matrix of hell.

I'm +1000 on cleaner & QA enforcement, but it does not prevent in my opinion from helping users with compat glue, whenever it is possible, or it already exists and does not harm.

**Comment by basepi** [comment]
> we are speaking about the reintroduction of it because it can really be harmful not to have it anymore on old and not upgraded setups.

Agreed. But we have to have a mechanism by which we can break backwards compatibility in a calculated way or else Salt will be so wrapped up in legacy code it will be impossible to maintain. There have been warnings for something like 9 months of salt releases. That seems like enough time to prepare for the deprecation to me.

> A twoliner deprecation warning that we don't remove and does not harm will save salt user time & experience.

Technically true. However, hundreds of two-liner deprecation warnings make salt bloated and confusing. The warnings are there for 9 months, and then we remove them and start erroring. It's a classic deprecation path, and plenty of time to get code changed accordingly.

**Comment by kiorky** [comment]
Your mechanism just failed yesterday, and many times.
This is maybe my only problem wth salt, from the beginning, although it outperforms everything else on the market for me.
Some of our coworkers use salt not extensively, some others just forget a lot, and some others wont learn it and only rely on the gitpush/like hooks workflows we have to deploy.
When it comes to write states, or understand error, salt moves way too fast for them.
And when the errors arise, it is often too late for a simple emergency plan, and here our backup policy saves more that once ;).

For the bloat of warnings, it depends on the use case and the risk, and i prefer an handled & triggered warning that a broken production.

**Comment by basepi** [comment]
Sorry to hear that some of your coworkers didn't get their states changed. Luckily, changing `runas` to `user` should only take a few minutes, even for large state runs.

**Comment by kiorky** [comment]
At the condition to understand & interpret the error without the behalf of a salt expert, any other case will result in frustration ;).
