### ISSUE TITLE
State rabbitmq_plugin missing proper error handling

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#21216]
Whenever an error occurs within the `rabbitmq_plugin` state it returns a dictionary into the Comment field instead of a sensible error. 

An example of what it would put into this field:
```
{"pid": 8105, "retcode": 1, "stderr": "erlexec: HOME must be set", "stdout": ""}
```

Perhaps it should only put the `stderr` (and maybe also `stdout`) content into the Comment field as a string rather than a dictionary.

Version info:
```
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by syphernl** [comment]
Also see #15096

**Comment by rallytime** [comment]
Thanks for this report @syphernl.

**Comment by rallytime** [comment]
@syphernl I've submitted #28270 to fix this issue. I refactored much of the state to make sure stateful-ness is maintained when using test=true functionality, as well as returning changes in the changes dictionary and error stings instead of dictionaries in the comment lines. 

Can you give this change a try and make sure it is working appropriately for you?

**Comment by rallytime** [comment]
Since we haven't heard back in a while on this, I am going to close it. If you run into any problems with this change, please leave a comment here and we can re-open, or feel free to open a new issue. Thanks!
