### ISSUE TITLE
salt-ssh verbose output

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#21254]
I actually liked the normal salt-minion output of salt.

Would it be possible to have such output when using salt-ssh as well?

**Comment by basepi** [comment]
> normal salt-minion output of salt.

What do you mean? The output should look very similar to normal salt output. And `-v` is supported with `salt-ssh` commands, though it won't show quite the same output, since the job flow is different. (It doesn't have to check to see if the job is still running at intervals.)

You can also turn on debug logging, thought that's *very* verbose.

**Comment by srkunze** [comment]
Thanks. I need to give that "debugging logging" a try tomorrow.

However, IIRC, -v yields a lot more output on the original `salt` command than `salt-ssh`. Anyway, I will check that tomorrow.

**Comment by srkunze** [comment]
Okay, checked it right now out of curiosity. You are right. Thanks for the `-l debug` hint.
