### ISSUE TITLE
salt-cloud vSphere snapshot capabilities

### ISSUE THREAD

**Issue by jryberg** [saltstack/salt#21280]
Hi,

It would be great to add the option to save snapshot, list snapshots and also revert to a snapshot.

My user case is regarding R&D and automated test deployments. Right now we are using bash scripts to handle VMware and everything else with salt. It would be great to be able to handle snapshots as well with salt.

**Comment by jfindlay** [comment]
@jryberg, thanks for the report.  I know there is more that can be done with the VMware support, and given more time, it'll be done. :-)  Please feel free to submit a pull request if you desire.

**Comment by dmyerscough** [comment]
@jryberg You can now create snapshots too #22008

**Comment by rallytime** [comment]
@jryberg It looks like some of this functionality has been added to the vsphere driver, as mentioned above.

However, please note that the vshpere driver is on a deprecation path and will be officially removed in Salt Carbon (see #24487 and #24504). As such, we'd recommend moving to the new vmware. Since we have a much more robust and clean driver, we won't be spending time cleaning up bugs or implementing new features for vsphere. We will instead be focusing on the new vmware driver. However, we will of course be accepting fixes from community members as they are submitted.

@nmadhok Do you know if this functionality exists in the new vmware driver?

**Comment by nmadhok** [comment]
@rallytime Currently the following functionality exists in the VMware driver:

Create Snapshot:
https://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.vmware.html#salt.cloud.clouds.vmware.create_snapshot

List Snapshots:
https://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.vmware.html#salt.cloud.clouds.vmware.list_snapshots

Revert to Snapshot:
https://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.vmware.html#salt.cloud.clouds.vmware.revert_to_snapshot

Remove all snapshots:
https://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.vmware.html#salt.cloud.clouds.vmware.remove_all_snapshots

More snapshot capabilities can be added to the driver based on feature requests.

**Comment by rallytime** [comment]
Thanks for the update @nmadhok! 

Since some of the mentioned functionality has been added to the vsphere driver and the fact that vsphere is being deprecated, as well as various snapshot capabilities in the new vmware driver, I am going to close this issue. If more snapshot functions need to be added to the vmware driver, newer issues/feature requests can be submitted. Thanks!
