### ISSUE TITLE
Add support for clusters in the postgresql modules and states

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#21293]
For salt.modules.postgres and salt.states.postgres_* add some support for postgresql clusters. 

One would like to be able to say : 

```
frank:
  postgres_database.present:
    cluster: 9.1/main
```

**Comment by jfindlay** [comment]
@arthurlogilab, can this issue be closed since your pull request has been merged?

**Comment by arthurlogilab** [comment]
@jfindlay I would leave it open since we can't ask for a specific cluster for a database (yet).

**Comment by anitakrueger** [comment]
I have been using the postgres_cluster state (thanks for that!) and have just added the correct db_port to connect to in my postgres_database.present states. That way, the database will be created in the correct cluster. Not sure how the postgres_database state would ever know about a cluster...(since that's really just a name/port/data_dir configuration.

**Comment by arthurlogilab** [comment]
@anitakrueger thanks for the heads up on your use of our contribution

@anitakrueger the execution module deb_postgresql has a cluster_list in which you can get the port information from a cluster name. In this way you can avoid relying on storing the port in your configuration. 

I'm not sure if you comment is just "we use this" or if it's a bug you're talking about. Can you be more specific ?
