### ISSUE TITLE
Reactor Payload Size

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#21354]
From today's "Introduction to Salt's Event Reactor System" lecture at SaltConf15 we discussed the fact that a minion can send an unlimited amount of data in a payload to the master providing a potential avenue for any compromised minion to bring down the master.

This issue is to find a solution to that, and should be a high priority.

@techhat

**Comment by jfindlay** [comment]
@alexthegraham, I was in that class, thanks for remembering.

**Comment by cachedout** [comment]
I'm not certain this is true. We added a limit to payload sizes a while back. Has this been confirmed by anybody?

**Comment by cachedout** [comment]
For reference, the relevent configuration option is ```max_event_size```. This limits the size of a payload a minion can send to a master.

On the master side, we could enable ```ZMQ_MAXMSGSIZE``` [http://api.zeromq.org/3-2:zmq-setsockopt] and make it a configurable option to enable it.

@jacksontj and @thatch45 Any input here?

**Comment by jacksontj** [comment]
@cachedout that option limits how large the events are that we'll fire across the master/minion event bus-- but even that is a client-side limitation (which isn't sufficient). So in addition to the event system not limiting the size of messages properly (read: publisher side) we should (as @alexthegraham mentions) put a size limitation of the master to minion payloads. 

A few thoughts about adding a size cap:
- we have to keep in mind that sometimes it is intended to ship large files, so it definietely should be configurable
- we also have to determine what attack vector(s) we want to defend from-- bandwith exhaustion (rate limit)? memory exhaustion (size cap)?
- we should give feedback to the minion: the zmq approach just disconnects the minion-- which will mean the minion will wait the max timeouts *and* retry, not ideal but I'm not sure zmq can do any better for us.

I am in the middle of re-writing the whole transport stack for salt-- so it might be better to put into that modular system (since all of the transport is nicely abstracted out). In there we could do smarter things for transports that will allow it.

**Comment by msteed** [comment]
Also see #24001. The effect of that change is to limit payload sizes on the master side to `max_event_size` as well. It looks like it was intended to work that way.
