### ISSUE TITLE
Pillar environments get compacted. 'env=dev or env=qa or env=prod' is ignored.

### ISSUE THREAD

**Issue by aidanjl** [saltstack/salt#21359]
Pillar environments don't work like salt formula environments.
Eg:
```
salt '*' state.sls redis3 env=dev
```
The above command will use formula from 'dev' environment but when it grabs pillar data that pillar data will be a munge of all environments pillar data, not just 'dev'.

Expected behaviour:

Only pillar data from the 'dev' environment is available to the formula.

**Comment by eliasp** [comment]
`env` is deprecated. Use `saltenv` now.

**Comment by aidanjl** [comment]
same result with 'saltenv'.

Note the state files work as expected and only grab from specified environment. Its the pillar data that is always compacted across all environments.

**Comment by aidanjl** [comment]
Just wanted to add that this behaviour is present in 2014.7 and was reproduced by Erik Johnson at saltconf using whatever version Erik uses (probably 15.2+).

**Comment by jfindlay** [comment]
@aidanjl, thanks for the report.

**Comment by samart** [comment]
i think we are affected by this as we try to figure out environments in general.  this + the top file compilation issue.

**Comment by amendlik** [comment]
There is a feature request to support selecting the pillar environment using a command line argument: #18808.

I disagree with the 'expected behavior' stated above, which says the pillar environment should be selected based on the state environment. There is nothing that ties together state environments and pillar environments, and there is a lot of value in being able to select them separately.

I use state environments to indicate the quality/readiness of the formula code (dev, qa, prod, etc.), and pillar environments to configure the systems according to their location (us-east, us-west, sandbox1, etc.). I would like to be able to run something like this:
```salt '*' state.sls redis3 saltenv=prod pillarenv=us-east```

**Comment by thatch45** [comment]
Yes, @amendlik is right, I am assigning #18808 as a feature for the next release, but this is expected behavior, pillar environments and state environments are different.

**Comment by aidanjl** [comment]
Agreed pillar environment should be its own switch.

Don't agree this is 'expected behaviour'. Why do pillar environments even exist right now if they always get merged no matter what. I would call this a bug. But glad its being addressed so thank you.

**Comment by aidanjl** [comment]
Just realized this fix isn't targeted for Lithium but the next release Beryllium. 

I really think this should be higher priority, I'm introducing salt to my team and this is core functionality that should just work. Same with the related top file issues, I can handle some cloud integration features missing but this stuff is critical to how salt operates.

**Comment by jfindlay** [comment]
@aidanjl, Lithium is about to be released.  We're waiting on one or maybe two blockers.  Since we've started testing and verifying releases last year, our release cycles have gotten shorter while maintaining or (hopefully) improving the stability of the code.

**Comment by aidanjl** [comment]
Thanks, appreciate all the hard work.
