### ISSUE TITLE
Pre-Highstate formula

### ISSUE THREAD

**Issue by I3olle** [saltstack/salt#21350]
If it isn't already possible I would like to request the feature to have state file be executed before a highstate run. My usage would be to have a formula to generate the /etct/salt/grains file, sync the grains and have all custom grains available in the highstate already. At the moment, actions based on these grains are only available in the second highstate. In my opinion this would also quite easily solve the old grains chicken or egg problem.
That is of course if there isn't a better solution already?

**Comment by techhat** [comment]
Hi @I3olle. Take a look at state.top and state.sls.

**Comment by I3olle** [comment]
@techhat I don't really get what you are trying to tell me. Maybe I was misunderstood. I want a formula to be executed before anything else within a highstate. Including something in the top file would not do this.

**Comment by techhat** [comment]
@I3olle, state.sls allows you to run individual states, rather than combining them together into a single highstate. If your pre-highstate stuff is small enough, this may be the best way to execute it before running a highstate

The state.top function allows you to use an alternate top file to compile your state together. This is often favored by users in larger environments that rely on subsystems like gitfs, but want to use a separate top file per environment (rather than the default model of the top file defining environments, and therefore being shared across repos). If your pre-highstate states are large enough, this may feel more appropriate.

There is also the option of just using the order or other requisites to ensure that the states that you need to run first, run first. Since states should be declared idempotently anyway, this may theoretically be enough.

**Comment by I3olle** [comment]
@techhat sorry for the late response. Yes, I could indeed start a specific sls by hand everytime. And effectively that's what I want to be done automatically whenever I start a highstate on a server. I want this to be an implemented feature. Not me telling everyone to remember to execute the sls before the highstate. All automatically. I say highstate, and the highstate first runs the sls and then starts his entire highstate process pulling the grains and pillars out of the cache and going throigh the top file. But first the sls.
And as I said, that would also solve the so called grains chicken or egg problem for which I haven't found any solution anywhwere.
Having multiple top files wouldn't really help with that either. We already have those through git. But on an unrelated note, is it possible to split the top file into smaller parts? I tried to use "include" and "import" once but to no avail.
