### ISSUE TITLE
Replace `fileinput` in `file.replace`

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#21362]
Replacing `fileinput` has been mentioned a few times in comments on other issues, or as part of a fix to other issues, but I can't seem to find a good issue to track work, so I'm creating this one.

**Comment by rallytime** [comment]
@lorengordon Thanks for filing this to keep track of this, as well as submitting the pull request. Since your PR has been merged, can this issue be closed? Or is there more work to be done here that we should be tracking?

**Comment by lorengordon** [comment]
@rallytime, heh, it was merged a little more quickly than I expected but it's ok; the PR was fully functional. I just had questions about whether anyone preferred a different approach, style, or exception handling. But if you like it as is, then it works for me. I'm fine working those questions separately.

**Comment by rallytime** [comment]
Heh, yes we move code quickly here and we probably just missed the comments about holding off. Sorry about that. But yeah, feel free to fix those issues as you get to them, since the PR was functional. :)

I'll close this then, but if you want to keep tracking new questions here, that's fine. Let me know I can re-open it. Thanks!
