### ISSUE TITLE
FreeBSD CI Tests

### ISSUE THREAD

**Issue by kev009** [saltstack/salt#21418]
Hi @rallytime @cedwards,

We talked at SaltConf about making the test suite a thing on FreeBSD for salt CI.

Can we use this issue to plan and work on what is needed?

**Comment by cachedout** [comment]
+1

**Comment by rallytime** [comment]
@kev009 Definitely! Thanks for filing this.

**Comment by kev009** [comment]
Any ideas for stuff to start working on?

**Comment by rallytime** [comment]
@kev009 There are several things that need to take place to get the salt tests running in an automated fashionon Jenkins with our testsutie. The first is just getting the test suite up and running on FreeBSD at all. I haven't spent a lot of time doing this yet, but there is definitely some work to be done. There are some docs on how to run the test suite [here](http://docs.saltstack.com/en/latest/topics/development/tests/). 

Once the tests can run, then we'll need to clean up the tests to see what tests are passing/failing. Are the failures legitimate problems with the salt code, or does something need to be worked out in the tests themselves?

Then, once that is ready, we'll need to get the jenkins integration working with freebsd so we can spin up a FreeBSD image in the cloud, install the testing dependencies (this is done through the states in this repository: https://github.com/saltstack/salt-jenkins), and execute the test suite. 

For this last step, some work needs to be done to get salt-cloud working with freebsd. I just tried to spin up a VM on rackspace using salt-cloud using salt's current HEAD of develop and I got the following error:
```
*  INFO: Running install_freebsd_10_stable_post()
 *  INFO: Running install_freebsd_restart_daemons()
Starting salt_minion.
[DEBUG   ] Starting salt_minion.
 *  INFO: Running daemons_running()
[DEBUG   ]  *  INFO: Running daemons_running()
Connection to 104.130.139.221 closed.
[DEBUG   ] Connection to 104.130.139.221 closed.
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
[DEBUG   ]  * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 root@104.130.139.221 \'/tmp/.saltcloud-2e2d095b-fb04-47fa-b2df-9b71bcf618e7/deploy.sh -c \'"\'"\'/tmp/.saltcloud-2e2d095b-fb04-47fa-b2df-9b71bcf618e7\'"\'"\'\'' failed. Exit code: 1
```

I think it might be useful to start with the salt-cloud/bootstrap errors, since it would be helpful for using salt-cloud to set up the testing environments the same way Jenkins does, and then from there move on to getting the test suite running. But that is just my two cents.

**Comment by thedrow** [comment]
Ref #20239
