### ISSUE TITLE
Runner executions should be recorded in the job cache

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#21451]
Currently runner executions are logged, but they don't show up in the job cache.

It would be very useful for auditing purposes for runner executions to also be recorded in the job cache, whether that's the local job cache, or master job cache. Whatever job cache is configured.

If this could be added so that the runner system doesn't have to know what type of job cache is configured, but just add the job, that would be most desirable.

**Comment by UtahDave** [comment]
Per a conversation with @cachedout , we should check for the master_job_cache option and send the runner output or return to the master job cache.

**Comment by kiorky** [comment]
ping @jacksontj, i think we already added this recently

**Comment by jacksontj** [comment]
@UtahDave @kiorky Yea, I believe this is already in 2015.2

**Comment by ckochenower** [comment]
Both Runner and Wheel clients use SyncClientMixin. SyncClientMixin's low (function) calls salt.utils.job.store_job. The current implementation of salt.utils.job.store_job requires all returners implement save_load.

We need to put some protection around the following code and only call it if the returner implements save_load. Otherwise, we must require ALL returners implement save_load.

Excerpt from job.py:
...
        # save the load, since we don't have it
        saveload_fstr = '{0}.save_load'.format(opts['master_job_cache'])
...

@cachedout  also suggests that the Runner and Wheel docs need to mention/describe this new functionality.

**Comment by jacksontj** [comment]
I'd also recommend test coverage before documentation-- since without tests its more of a coincidence :)

**Comment by cachedout** [comment]
Well put. :]

**Comment by UtahDave** [comment]
@basepi fixed this.
