### ISSUE TITLE
master job cache needs paging when querying

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#21450]
When using the master job cache, data is kept around for as long as the sysadmin desires. This could become quite large. The following command returns ALL jobs in the job cache.
```
salt-run jobs.list_jobs
```

This can be quite large and resource intensive.
`salt-run jobs.list_jobs` and similar should have some kind of paging mechanism if they're built on top of a database.

Some ideas that I think would be useful in order of utility:

 - [ ] Return the jobs for the last 24 hours (probably should be the default)
 - [ ] Return jobs between two dates.
 - [ ] Return all jobs
 - [ ] Return the last 100 jobs (possible option)

Any others we should add?

**Comment by DmitryKuzmenko** [comment]
@UtahDave 
The second idea is already there:
salt-run jobs.list_jobs start_time="2015-07-06 17:41" end_time="2015-07-07"
But it is implemented as a python level filter after all jids are fetched from DB.
Is this issue about to implement paging/filtering at the returners level in the most efficient way for each returner?

**Comment by basepi** [comment]
The best solution performance-wise would probably be returner-side. But it mostly depends on the end goal. Master-side filtering would help a little with performance (printing to the screen is generally a bottle-neck), and would make the function more useful to admins wanting to find/analyze recent jobs. If they just want to limit what's printed and aren't worried about the query from the database, doing it in the jobs runner would be the quicker and easier solution. Otherwise we'll have to implement this across all returners, or at least the most popular returners.

**Comment by DmitryKuzmenko** [comment]
Hm. Am I understood you correctly that for now it's enough to implement output filtering on runner level at this moment? I mean in scope of this issue?

**Comment by basepi** [comment]
I do not know, we'll need to coordinate with @UtahDave and the zendesk issue. I was just exploring the issue and the potential solutions, I do not know which is right.

**Comment by DmitryKuzmenko** [comment]
Got it. Thanks. Thus I've added the proper label

**Comment by UtahDave** [comment]
+1

**Comment by basepi** [comment]
Talked to @UtahDave about this. For our initial implementation, we're going to add something along the lines of a new runner function called `jobs.list_jobs_filter`. In the long run we can support a lot of different types of filters on this function, but to start we should support two arguments.

The first is a required argument for the number of jobs to return, starting from the most recent job. The second is an optional argument that defaults to True, and if it is True we should filter any instances of `saltutil.find_job` out of the results (`filter_find_job=True`). We use `find_job` every 10 seconds during long-running jobs, and we rarely care about those jobs when we're listing jobs.

So, `salt-run jobs.list_jobs_filter 100 filter_find_job=True` should return the latest 100 jobs that do not have the function `saltutil.find_job`.

This will also require some returner-side modification to help performance. To start, we will only modify the `mysql.py` and `local_cache.py` returners, as they are the most popular. Basically, we should use the SQL query in `mysql.py` to filter, rather than fetching all data and then filtering it ourselves. This should be much faster (and limit the amount of data salt has to deal with).

In the future, we can add additional functionality to filter by timestamp and other info. We will not be adding explicit paging at this time, because it's easy enough to pipe the output into `less` or similar programs.

This will not be a simple undertaking, so if it slips to Boron instead of Beryllium, it is probably not an issue.

**Comment by whiteinge** [comment]
Great call adding a new runner function instead of trying to bolt-on to the existing.

Please return a sorted list of job dictionaries instead of a single, monolithic dictionary.

**Comment by UtahDave** [comment]
I agree with @basepi's @whiteinge's comments.

I'd love to have the `find_job` filtering, but if it adds too much complexity, I'd rather drop the `find_job` filter in order to get this into Beryllium.

**Comment by DmitryKuzmenko** [comment]
Added ```jobs.get_jobs_filter``` runner function with the following arguments:
- ```count```: the number of jobs in output
- ```filter_find_job=True```: filter out saltutil.find_job

Also it supports ```ext_source```, ```outputter``` and ```display_progress``` optional arguments as ```jobs.list_jobs```.

To support this I've added ```get_jids_filter(count, filter_find_job=True)``` functions to ```local_cache``` and ```mysql``` returners.
```local_cache``` implementation walks through the cache directory structure, we can't avoid it, all benefit is that now it keeps the only the specified count of most recent jobs keeping them sorted. So it uses less RAM.
```mysql``` implementation uses sql query selecting last ```count``` of jobs sorted by jid (that represents creation time) and filtered by load field with ```'%"fun": "saltutil.find_job"%'```. Since in the current scheme loads are kept as string we have no more efficient way to filter it. Probably for future it's better to change the scheme for jids table splitting values we'd like to filter by in separate columns.

Also I made ```get_jids_filter``` runner returning results as list instead of dict. Output example:
```
$ ./scripts/salt-run jobs.list_jobs_filter 3 filter_find_job=False 
|_
  ----------
  Arguments:
      - jobs.list_jobs
  Function:
      saltutil.cmd
  JID:
      20150716181523163190
  StartTime:
      2015, Jul 16 18:15:23.163190
  Target:
      *
  Target-type:
      glob
  User:
      dimm
|_
  ----------
  Arguments:
      - 20150716135059798015
  Function:
      saltutil.find_job
  JID:
      20150716181543764286
  StartTime:
      2015, Jul 16 18:15:43.764286
  Target:
      *
  Target-type:
      glob
  User:
      dimm
|_
  ----------
  Arguments:
  Function:
      test.ping
  JID:
      20150716181557182567
  StartTime:
      2015, Jul 16 18:15:57.182567
  Target:
      *
  Target-type:
      glob
  User:
      dimm
```

**Comment by DmitryKuzmenko** [comment]
Also I'm not sure should I add stub implementation of ```get_jids_filter``` returning string like "Not implemented" to all other returners? Without it returner will throw an exception.

I.e. what's expected output for this (not implemented) case:
* Key Error:
```
$ ./scripts/salt-run jobs.list_jobs_filter 3 filter_find_job=False 
Exception occurred in runner jobs.list_jobs_filter: Traceback (most recent call last):
  File "/home/dimm/projects/salt/git/salt/salt/client/mixins.py", line 337, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/home/dimm/projects/salt/git/salt/salt/runners/jobs.py", line 348, in list_jobs_filter
    ret = mminion.returners['{0}.get_jids_filter'.format(returner)](count, filter_find_job)
  File "/home/dimm/projects/salt/git/salt/salt/utils/lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'local_cache.get_jids_filter'
```
* String
```
$ ./scripts/salt-run jobs.list_jobs_filter 3 filter_find_job=False 
Not implemented for this returner yet
```

**Comment by cachedout** [comment]
We need to do something like create a `NotImplemented` exception for returners that don't have all the required methods written out and catch it higher up and through critical (but non-fatal) errors. This is going to bite us sooner rather than later if don't do so, IMHO.

**Comment by DmitryKuzmenko** [comment]
@cachedout good suggestion. So we'd have a way to explain the problem and return non-zero from salt-run.

**Comment by cachedout** [comment]
@DmitryKuzmenko For sure. We defnietely need to avoid just throwing KeyErrors and stacktracing back up to the user.
