### ISSUE TITLE
Probably pillar/fileserver problem

### ISSUE THREAD

**Issue by skint** [saltstack/salt#21548]
I've tried to setup simple installation of salt-master/minion, and can't figure out, where i am wrong.

This is in /etc/salt/master:

```
file_roots:
  base:
    - /srv/salt

pillar_roots:
  base:
    - /srv/pillar
```

I create file /srv/salt/top.sls with following content:

```
base:
  '*':
    - common
```

Then, when i do `state.show_top`, i've got in terminal:

```
master# salt myhost state.show_top
myhost:
    ----------
    base:
        - common
```

That's okay, i suppose. If i do `state.highstate` - the state is apply.
Then i create file /srv/pillar/top.sls with this:

```
base:
  '*':
    - packages
```

And when i do `state.show_top` again, i get that:

```
master# salt myhost state.show_top
myhost:
    ----------
    base:
        - packages
```

States now use pillar's root path, and get data from there.
Also if i try to `state.highstate`, minion try to use pillar as a state:

```
master# salt myhost state.highstate
myhost:
    Data failed to compile:
----------
    State 'packages' in SLS 'packages' is not formed as a list
```

but `pillar.items` shows me a right data:

```
salt myhost pillar.items
myhost:
    ----------
    packages:
        ----------
        vim:
            vim-enhanced
```

So, is it misconfiguration, bug or my inattention? Thank you.

**versions**

```
master# cat /etc/redhat-release
CentOS release 6.5 (Final)
master# salt --versions
           Salt: 2014.7.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.5
   msgpack-pure: 0.1.3
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 1.0.1
```

**Comment by rallytime** [comment]
@skint What does your packages state look like?

**Comment by skint** [comment]
@rallytime I have on state 'packages'. just pillar.

```
master# cat /srv/pillar/packages/init.sls 
#!mako|yaml
packages:
  % if grains['os_family'] == 'RedHat':
  vim: vim-enhanced
  % else:
  vim: vim
  % endif
```

**Comment by basepi** [comment]
Weird! Can you please double check that your master config you posted above is indeed the master config on your master? And can you please restart your master to make sure it has taken effect?

`state.show_top` should only apply to state topfiles, not pillar topfiles. So somehow something is misconfigured such that salt is looking for state data in your pillar directory. But your configuration shown above looks right, so I'm worried it may be stale configuration or something because you didn't restart your master.

**Comment by skint** [comment]
All uncommented lines from my master config file:

```
master# cat /etc/salt/master | grep -v -E '^#|^[[:space:]]*$'
interface: 0.0.0.0
publish_port: 4505
user: root
max_open_files: 100000
worker_threads: 5
ret_port: 4506
file_roots:
  base:
    - /srv/salt
fileserver_backend:
  - roots
pillar_roots:
  base:
    - /srv/pillar
pillar_opts: False
log_level: debug
log_level_logfile: info
```

so, restart:

```
master# service salt-master restart
Stopping salt-master daemon:                               [  OK  ]
Starting salt-master daemon:                               [  OK  ]
master# salt myhost state.show_top
myhost:
    ----------
    base:
        - packages
```

i've tried to make it work in different ways, but..
if you once set pillar top.sls - you have it in states, does not matter, restarted or not.
also, if you do ``` echo -n > /srv/pillar/top.sls``` - state.show_top shows you empty top.sls (as it is in pillar):
```
master# echo -n > /srv/pillar/top.sls 
master# salt myhost state.show_top
myhost:
    ----------
master#
```

only if you remove /srv/pillar/top.sls - then /srv/salt/top.sls comes back, but only after restart.

anyway, i thought that the pillar (and states also) is dynamic. am i wrong?

and yes, i've tried to clean cache, on master and on minions, i also reinstall salt from centos repos (2014.7.0), and from pip (2014.7.2), i've done `rm -rf /var/cache/salt` on both..

looks like when master find top.sls in pillar_roots (for same environment, for example 'base') - it overrides variable where file_roots path is in.

**Comment by basepi** [comment]
Yes, this is *very* strange. Pillar shouldn't be interfering with states in any way, and changes to either should not require a master restart.

Any chance you could test on a fresh box? Curious if it may be something in your environment. I've never seen behavior like this before.

**Comment by skint** [comment]
I have no totally fresh box yet, so i make new setup on another box, and got the same result.
I'll try to find fresh box (or VM) today, and tell about results.

**Comment by kleinsasserm** [comment]
Yes, thats true. We have the same problem here. We are trying to use pillar for information distribution. That works like a charm.

eg:
    ou:
        ----------
        salt-ii:
            True

but when running salt '*' state.highstate we get:
    State 'ou' in SLS 'ou-salt-ii' is not formed as a list

and:
   Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is 'ou' and is found in SLS ....

This seems that the pillar top.sls and inlcuded sls are beeing used as state sls?

**Comment by boernieat** [comment]
we (kleinsasserm & i) tried it on a fresh debian 7.8 vm
-> 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux

**Comment by basepi** [comment]
What kind of system are you using @skint? And how did you install salt?

**Comment by skint** [comment]
No, from epel without testing.
Also, i tried to `pip install -U salt` on my first master, when i recognize it does not work.
Today morning i've installed it on another box, without `pip` things, with same result.

**Comment by terminalmage** [comment]
This was a regression that I'm pretty certain has been fixed. can you try using the latest code from the 2014.7 or 2015.2 branches?

**Comment by skint** [comment]
Okay, done.

In 2014.7 (2014.7.2-336-g14efe70) it is broken (pillars becomes to be states)
In 2015.2 (2015.2.0rc1-157-gcc9d294)  it works as expected

**Comment by kleinsasserm** [comment]
Confirmed! tag v2015.2.0rc1 works as expected. We installed it via salt-bootstrap on the master.

**Comment by terminalmage** [comment]
@kleinsasserm thanks, could you also test on the latest from the 2014.7 branch?

**Comment by terminalmage** [comment]
Oh, I see that @skint has tested on 2014.7. I'll investigate, thanks.

**Comment by basepi** [comment]
I'm still stumped on how to cause this issue -- I still can't reproduce. But it sounds like @terminalmage is on the case. =)

**Comment by boltronics** [comment]
I've just been banging my head against this problem trying to setup a new staging environment, not knowing what the heck the problem was (as I have many similarly named pillar and state files). I'm seeing this in 2014.7.5, currently in the repos. I can't run highstate without getting the "State... is not formed as a list" errors, which unfortunately pretty much renders this release useless. This is using the official deb packages on a fresh but fully updated Debian Wheezy install.

```
master# salt --versions
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.5+ds-1~bpo70+1
```
So in the meantime, what should I be using in production? I need to bring up a new environment tomorrow (I'm already well behind schedule now). I assume 2014.7.1 is the last in the 2014-series that worked? And I understand anything older than 2014.7.4 has some security concerns. I'm assuming  2015.2 isn't safe to use, so what's the solution?

@terminalmage If I have to build a 2014-series package myself with a patch, so be it, but is there a known patch you can point us to? It sounded like you knew the cause.

**Comment by kleinsasserm** [comment]
All I can say is, that we are using salt 2015.2.0rc1 (Lithium) since my last post. All we are using from salt is working for us in this version...

**Comment by boltronics** [comment]
Thanks @kleinsasserm. In that case, I might give it a try if building packages for it isn't too different and nobody can offer a better solution.

It's extremely annoying that this has happened a few times now - we can't use older versions in production due to a security issue, but current versions are broken. It really makes us lose trust in the project. Can't Salt just have a stable release branch that gets security fixes and critical bug fixes, and nothing else?

**Comment by boltronics** [comment]
I skipped ahead to 2015.2.0rc2.

Just spent a few hours building the packages for Wheezy (since I had to package python-libcloud 0.14.1 to satisfy dependencies). I basically took the debian directory from 2014.7.5+ds-1~bpo70+1 and the rest from the 2015.2.0rc2-1 tagged release, removed one of the patches which was no longer necessary and updated the changelog, which actually worked pretty well.

```
abolte@ip-172-31-0-10:/srv/salt$ salt --versions-report
                  Salt: 2015.2.0
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2015.2.0rc2-1
abolte@ip-172-31-0-10:/srv/salt$ salt-call --versions-report
                  Salt: 2015.2.0
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2015.2.0rc2-1
abolte@ip-172-31-0-10:/srv/salt$ 
```

I'm testing the master and minion on the same machine.

Except... same issue!! This is not resolved at all. :((

Here's the frustrating thing: It appears to work, but it only works for a while. A restart seems to get it working again for a while.
```
abolte@ip-172-31-0-10:/srv/salt$ sudo salt-call state.show_top | grep -E '(common|system)'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://top.sls'
        - system
abolte@ip-172-31-0-10:/srv/salt$ sudo /etc/init.d/salt-master restart
[ ok ] Restarting salt master control daemon: salt-master.
abolte@ip-172-31-0-10:/srv/salt$ sudo salt-call state.show_top | grep -E '(common|system)'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'top.sls'
        - common
        - bad_filesystem_check
abolte@ip-172-31-0-10:/srv/salt$
```

(where ``common`` is a state file, and ``system`` is a pillar file).

Then some time later:

```
abolte@ip-172-31-0-10:/srv/salt$ sudo salt-call state.show_top | grep -E '(common|system)'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://top.sls'
        - common
        - bad_filesystem_check
abolte@ip-172-31-0-10:/srv/salt$ sudo salt-call state.show_top | grep -E '(common|system)'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'top.sls'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltRenderError: Unable to render top file. No targets found.
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 225, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 998, in show_top
    top_ = st_.get_top()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2416, in get_top
    return self.merge_tops(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2357, in merge_tops
    raise SaltRenderError('Unable to render top file. No targets found.')
SaltRenderError: Unable to render top file. No targets found.
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 225, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 998, in show_top
    top_ = st_.get_top()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2416, in get_top
    return self.merge_tops(tops)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2357, in merge_tops
    raise SaltRenderError('Unable to render top file. No targets found.')
salt.exceptions.SaltRenderError: Unable to render top file. No targets found.
abolte@ip-172-31-0-10:/srv/salt$ sudo salt-call state.show_top | grep -E '(common|system)'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'top.sls'
        - system
abolte@ip-172-31-0-10:/srv/salt$
```

That's just running exactly the same command three time! I had no other SSH sessions to the box or anything running the background. Absolutely nothing changed!

@kleinsasserm Did you switch distributions or states/pillar/configuration or something when you upgraded to the release candidate? Would you kindly be able to run the output of ``salt --versions-report``? Thanks.

In the meantime, what are my options? I have to revert back to an ancient version with known vulnerabilities and put myself even further behind schedule. @terminalmage if you have any ideas or suggestions, now would be a good time.

**Comment by boltronics** [comment]
Same deal on 2014.7.1.
```
abolte@ip-172-31-0-10:/srv/salt$ sudo salt-master --versions-report
           Salt: 2014.7.1
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
abolte@ip-172-31-0-10:/srv/salt$ sudo salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
abolte@ip-172-31-0-10:/srv/salt$ sudo salt-call state.show_top | grep -E '(common|system)'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://top.sls'
        - system
abolte@ip-172-31-0-10:/srv/salt$ 
```

**Comment by kleinsasserm** [comment]
Our pillar files resides in an own path, eg. /srv/pillar
Theres the top.sls:
```
base:
  '*':
{% include "nantan.sls" %}
```

We are generating all pillar files via script. Therefore the nantan.sls is generated by script and filled with the generated pillar.sls:
```
    - ou-test-net10
    - ou-test-net11
    - ou-test-net12
```

Inside the pillar sls for example ou-test-net10.sls the pillars are set:
```
{% if
grains["fqdn"] == "<fqdn here>" or
grains["fqdn"] == "<fqdn here>"
%}
ou:
  test-net10: True
{% endif %}
```

Overall we have 196 sls files for 458 server. We are not using salt for configuration management, only for execution because Puppet is missing an execution environment. Configuration management is done via Puppet -- ugly but more bullet proof in our opinion...

Version:
```
          Salt: 2015.2.0rc1
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```

**Comment by boltronics** [comment]
Thanks @kleinsasserm for that quick response. Interesting approach you have, but looks good to me. I've just finished packaging 2015.2.0 and am about to test that.

I basically dumped all states from our production git repo into this new staging setup, so I know the states are good. But many depend on pillar data and it's possible I didn't add everything required by those states. The original plan was to just add the pillar until all states stop complaining, documenting what was required as I go. We've got 213 sls files, but nowhere near as many servers (and in this setup I'm only testing a master and minion on the same machine!).

It originally thought there must have been some significant incompatibility with one of the states or modules salt provides (since I did a significant version jump at the same time), or maybe something calling missing pillar data and failing in some wacky way, which is why it took me a long time to figure out I'm actually hitting a Salt issue. I basically had to scrap everything, and start adding things one tiny state at a time until I figured out my assumptions were completely wrong.

However comparing our versions, `` msgpack-python: 0.1.10`` is the only stand-out. I might see if changing that makes a difference for me after I finish a few other tests.

**Comment by boltronics** [comment]
I can even reproduce this in 2014.7.0.
```
           Salt: 2014.7.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```

This time it was working correctly for a while so I thought we found a winner here. But no, it just took some time for the symptoms to show.

**Comment by kleinsasserm** [comment]
Good idea to fit it together step by step. It took us a whole day to get the yaml sls files correctly structured with the needed information. Why? Theres more than one way to organize the sls files -- we had the problem, that the parsers wasn't able to parse the sls files if the `{% if }` part contains to long lines, to much lines or the sls files are too long and so on and so on... resulting in parsers error messages and other misbehaviour.

**Comment by boltronics** [comment]
Yaikes! That would have been a hard one to diagnose for sure.

**Comment by boltronics** [comment]
I think we've got a winner!
```
abolte@ip-172-31-0-10:~$ sudo salt-master --versions-report
           Salt: 2014.1.13-3-gb325b92
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
abolte@ip-172-31-0-10:~$ sudo salt-call --versions-report
           Salt: 2014.1.13-3-gb325b92
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
abolte@ip-172-31-0-10:~$ 
```

Actually, I knew that would work if it really was a bug in Salt itself and not some weird environment issue on the machine itself, since I use that same packaged version elsewhere without issue (although I really need those security updates...). So I guess the msgpack-python version isn't related after all.

But it's absolutely amazing there have been so many releases without this problem being addressed.

**Comment by boltronics** [comment]
Scratch that. I was finally able to trigger the problem on 2014.1.13 as well! It just took a very long time to show itself. Argh!! Okay, so it's probably something special about my environment. But this is a completely clean Wheezy install (although some components were upgraded to support the newer version of Salt I was originally going to use). How frustrating.

**Comment by boltronics** [comment]
For now, I have rolled everything in the staging environment back to 2014.1.13 with an old AMI. That's working so far. I used the same script to generate the old and the new AMI, so everything should be almost identical. The only obvious differences are a few packages rebuilt from Jessie to meet the requirements of the newer Salt releases which I experimented with.

When I have time, I'll see if I can do more testing, gradually changing one thing at a time. But it's hard when the problem doesn't necessarily show itself for quite some time.

**Comment by boltronics** [comment]
I'm running newer Salt releases and a combination of jessie and stretch hosts. I haven't ran wheezy in a long time, and it's no longer supported by Salt anyway. I also don't remember the last time I saw this issue, but it possibly went away around the time I upgraded to Jessie. Feel free to close. Thanks.

**Comment by rallytime** [comment]
Thanks @boltronics for the update. I'll close this.
