### ISSUE TITLE
What's different with Salt's version of python-urllib3_1.7.1-1~bpo70+1_all.deb?

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#21776]
I am using aptly to mirror various apt repositories, including wheezy and saltstack. I would like to merge the saltstack repo into our local wheezy repository but it appears I cannot do it because the md5sum of ```python-urllib3_1.7.1-1~bpo70+1_all.deb``` from Salt is not the same as md5sum of the same package in Debian.
```
[aptly@specials ~]$ wget -q -4 http://debian.saltstack.com/debian/pool/main/p/python-urllib3/python-urllib3_1.7.1-1~bpo70+1_all.deb
[aptly@specials ~]$ wget -q -4 http://mirrors.kernel.org/debian/pool/main/p/python-urllib3/python-urllib3_1.7.1-1~bpo70%2b1_all.deb
[aptly@specials ~]$ ls -l python*
-rw-r--r-- 1 aptly users 49562 Nov 17 06:54 python-urllib3_1.7.1-1~bpo70+1_all.deb
-rw-r--r-- 1 aptly users 49552 Oct 29  2013 python-urllib3_1.7.1-1~bpo70+1_all.deb.1
[aptly@specials ~]$ md5sum python*
8c31fce3b9146e399747f68352746a7c  python-urllib3_1.7.1-1~bpo70+1_all.deb
a573623d1cd516b0dd40c77abd7fb00c  python-urllib3_1.7.1-1~bpo70+1_all.deb.1
```
Where does the Salt's version of this package comes from? Shouldn't it be the same as Debian's version, which is available in wheezy-backports?

**Comment by pitatus** [comment]
Not sure..  The Debian packager is a community member, perhaps he can clarify for us.  ping @joehealy

**Comment by joehealy** [comment]
I suspect they are "practically" identical. The difference in md5 is likely to be due to build timestamps.
My workflow will have been to download the source package and rebuild so that I could import the whole lot into the repo at once.

A quick check of the contents of the source package indicate they are identical.

So - they should be identical and you could use either. Unforunately debian does not yet do reproducible builds - see https://wiki.debian.org/ReproducibleBuilds for details.

**Comment by ksalman** [comment]
Okay, thanks.
