### ISSUE TITLE
salt -L is case sensitive (default salt command is insensitive) 2014.7.1

### ISSUE THREAD

**Issue by FeatherKing** [saltstack/salt#21897]
I think this was working in 2014.1 but when i pass a csv list of servers using

``` python
salt -L 'server,list,here' test.ping
```

it is not matching if the server names are not case sensitive.

example using 3 servers with the following case sensitive minion ids:
1. server
2. List
3. HEre

this works:

``` python
salt server test.ping
    server: True
salt list test.ping
    List: True
salt here test.ping
    HEre: True
```

this doesnt

``` python
salt -L 'server,list,here' test.ping
    server: True
```

nothing gets returned from the insensitive minion ids

**Comment by jfindlay** [comment]
@FeatherKing, I am unable to target minions either using ordinary globbing or with `-L` in a case-insensitive manner.  Have I done it incorrectly?

```
centos-7-main ~ master # salt '*' test.ping
ubuntu-14:
    True
centos-7-main:
    True
centos-7-main ~ master # salt -L 'CentOS-7-main,Ubuntu-14' test.ping
No minions matched the target. No command was sent, no jid was assigned.
centos-7-main ~ master # salt CentOS-7-main test.ping
No minions matched the target. No command was sent, no jid was assigned.
centos-7-main ~ master # salt Ubuntu-14 test.ping
No minions matched the target. No command was sent, no jid was assigned.
centos-7-main ~ master # salt -L 'centos-7-main,ubuntu-14' test.ping
centos-7-main:
    True
ubuntu-14:
    True
```
```
centos-7-main ~ master # salt --versions
           Salt: 2014.7.2
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```
```
centos-7-main ~ master # salt '*' test.versions_report
ubuntu-14:
               Salt: 2014.7.2
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.0.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: 0.9.1
centos-7-main:
               Salt: 2014.7.2
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.4
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
centos-7-main ~ master #
```

**Comment by FeatherKing** [comment]
I was working with windows minions that day and I think it actually might be different behavior based on minion os. Windows minions are insensitive and linux are sensitive based on these results.

Example server name of a windows minion TestServer

all uppercase
```bash
salt TESTSERVER test.ping
TestServer:
    True
```

all lowercase
```bash
salt testserver test.ping
TestServer:
    True
```

actual hostname
```bash
salt TestServer test.ping
TestServer:
        True
```
```bash
salt TESTSERVER test.versions_report
TestServer:
               Salt: 2014.7.1
             Python: 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed

```

Example linux minion name QA1
```bash
salt qa1 test.ping
```
```bash
salt Qa1 test.ping
```
```bash
salt QA1 test.ping
QA1:
    True
```
```bash
salt QA1 test.ping
QA1:
               Salt: 2014.7.1
             Python: 2.7.3 (default, Dec 18 2014, 19:03:52)
             Jinja2: 2.6
           M2Crypto: 0.21.1
     msgpack-python: 0.1.10
       msgpack-pure: Not Installed
           pycrypto: 2.4.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.5.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
```

Like you I am getting the same results on either glob or list rendering. What should be the default behavior. Looking at this discussion https://github.com/saltstack/salt/issues/8965 it seemed like insensitive should be the default targeting

**Comment by jfindlay** [comment]
That makes sense, since hostnames, domainnames, dns names, etc. are traditionally case insensitive.  That is the greater contextual convention that I think we should conform to.

**Comment by jfindlay** [comment]
@FeatherKing, do you think this is a duplicate of #8965, such that discussion on minion ID case insensitivity could be consolidated there?  Thanks.

**Comment by FeatherKing** [comment]
I wouldnt say its a duplicate, but the discussion needs to happen. I would still call this a bug because the experience for the user seems to be unexpected and different depending on what OS the minion is running. 

Regardless of how the discussion goes (sensitive or non) i feel like the behavior should be consistent

**Comment by jfindlay** [comment]
@FeatherKing, sounds good to me.

**Comment by FeatherKing** [comment]
Also it is worth noting that even in the windows minions only, the glob and list are working differently (glob = insensitive, list = sensitive)

```bash
salt testserver test.ping
TestServer:
    True
```

```bash
salt -L 'testserver' test.ping
```

**Comment by memotype** [comment]
I came here because I came across this same issue and was checking to see if an issue was already opened.

So, I noticed the discussion is considering whether or not Salt should treat minion IDs consistently case-sensitive, or case-insensitive, and I figured I'd throw my 2 cents in. I'd like to suggest case-insensitivity across the board. By internet standard RFCs 921 ("Case is not significant."), 952 ("No distinction is made between upper and lower case."), 1035 ("Note that while upper and lower case letters are allowed in domain names, no significance is attached to the case.  That is, two names with the same spelling but different case are to be treated as if identical." as well as section 2.3.3 which is very clear about this.), 3986 ("The host subcomponent is case-insensitive."), etc, etc. Every other application, protocol, standard, etc, treats host names this way, I see no reason Salt should do otherwise.

To emphasize this here is a use-case where this would be significant. Currently I am writing some scripts and Salt modules that pull host data from our asset tracking system. The hostnames listed in this system are manually entered by our staff, and some people like to enter the hostnames with varying case-schemes (all uppercase, CamelCase-style, etc) and these schemes do not necessarily correspond to the hostnames configures on the servers themselves (which is where Salt pulls the minion ID from). Of course, I could work around this in my scripts, but it would be pretty kludgy, involving tricks like reading the full list of keys from salt.key, converting everything in that to lower-case, then converting the input from the assets system to lowercase, finding the match, then finding the corresponding entry in the original keys list, just so I can know what case-senstitive name to use with salt.

A simpler use-case for this is the obvious "I know the hostname of the server I want to target on the command line, but can't remember how it's cased in Salt, so I have to do "salt-key | grep -i 'some-hostname'" just to know what to put on the salt command line" scenario.

So, I think the case for (pun intended) case-insensitivity is pretty clear. :)

**Comment by basepi** [comment]
Relevant: https://github.com/saltstack/salt/issues/8965

**Comment by cachedout** [comment]
I think @memotype has analyzed this issue extremely well and I fully agree.

Obviously, we do need to consider how we proceed here. I don't think we'll be willing to accept a PR that just forcefully changes this behaviour. Instead, we'll want to config-gate this initially and set a target release for a full cutover. I'd say that we should begin this work on the develop branch and target Boron for the config-gate option, and then carbon for switching over fully.

cc: @basepi, @s0undt3ch, @thatch45

**Comment by s0undt3ch** [comment]
I agree with the case insensitive approach going forward, however, as @cachedout suggested, this behavior needs to be gated as a config option for some releases after which we could start warning about the behavior change or just default to being case insensitive(a **lot** of major releases).
