### ISSUE TITLE
Support lxc unpreviliged containers

### ISSUE THREAD

**Issue by slomo** [saltstack/salt#21931]
Neither the lxc modules nor the [lxc states](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.lxc.html#module-salt.states.lxc) allow currently to give a user as argument. Although this would be useful in order to setup [unpreviliged containers](https://www.stgraber.org/2014/01/17/lxc-1-0-unprivileged-containers/).

It would be super to see support for this. My current solution is to use the lxc command line tools instead.

**Comment by rallytime** [comment]
Thanks for the suggestion @slomo.

ping @terminalmage

**Comment by Sjd-Risca** [comment]
Hi, please consider also to modify the available option (as described [here](https://github.com/saltstack/salt/issues/30576#issuecomment-206362389)), because still some relevant options required by unprivileged containers (like map.id) are still not manageable via the lxc.init or cloud provisioning.

Thanks!

(see also #14193)

**Comment by mirko** [comment]
After having read this issue, the linked one (https://github.com/saltstack/salt/issues/30576) and the linked one in there (https://github.com/saltstack/salt/issues/14193) as well as the LXC tutorial (https://docs.saltproject.io/en/latest/topics/tutorials/lxc.html): is there now support for unprivileged LXC containers? Because I can't find any hint there is. Technically more precise: is there by now a way of specifying per container variables such as id.map?
