### ISSUE TITLE
Question about Customizing output

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#22075]
how the output of state.sls is customized ( unlike the output of grains.items , there is no dash - or pipe l ) pluse it have colors in case of success or failure.

How to make the output of my custom module looking the same ?

**Comment by basepi** [comment]
The state system uses a special outputter called the [`highstate` outputter](https://github.com/saltstack/salt/blob/develop/salt/output/highstate.py).

You can define the outputter for a command with `--out=highstate`. However, this won't work in your case, because the `highstate` outputter is designed for the very structured output of the state system.

So what I recommend is writing your own outputter. You can use the other outputters (https://github.com/saltstack/salt/tree/develop/salt/output) as examples.
