### ISSUE TITLE
Unit of `disk.usage` shall be bytes and documented

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#22549]
Disk capacity can be represented in multiples of 1,000 bytes(kB MB GB TB ...) or 1,024 bytes (KiB MiB GiB TiB ...).

I started to understand [from this pull request](https://github.com/saltstack/salt/pull/22492) that the unit of `disk.usage` is KiB (kibibyte). 

I consider KiB as problematic.
- it complicates representation (should you want to represent capacity in GB you first must divide by 1,024)
- Neither 1,000 nor 1,024 are intuitive.

I kindly propose that `disk.usage` uses 1 byte as unit.
This separates calculation from representation. 

Finally, I kindly propose to include the unit of capacity in the documentation of `disk.usage`  http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.disk.html#salt.modules.disk.usage

**Comment by techhat** [comment]
What you say makes sense, but there is a piece that is missing here. This function was originally designed to be a wrapper around the Unix/Linux `df` command, which returns information in blocks, which defaults to 1K in Linux (512 bytes in POSIX). I've never been a fan, but that's what it's always been (and therefore is intuitive in Linix), and I'm not the right person to go against the grain.

Rather than forcing it to 1 byte, I would rather make it configurable (this can be done with `-B`/`--block-size` in Linux), and ensure that a unit is provided with the return data. The next questions is, what is the most reasonable default for Windows? 1 byte, I assume?

**Comment by markuskramerIgitt** [comment]
Yes, and byte is also the unit for capacity currently reported on Windows. Only the pull request of @davidjb is going to "harmonize" that to kibibyte.

It is problematic that one need to remember the history of `disk.usage` as a wrapper for `df` and the slightly unfortunate fact that `df` defaults to 1K in Linux  and 512 bytes in POSIX.

To make the unit of `disk.usage` configurable to me seems a way for keeping backward compatibility: if there is a Linux-program that calculates with the output of `disk.usage` it assumes it to be kibibyte. Let's hope no Windows-program uses `disk-usage` because it is going to break with the pull request.

When I saw `available` in `disk.usage`  I did not know the story of `df` and the default block-size on Linux. I was not alerted by the value `1K-blocks`. 
The cleanest solution I can think of are new values (`available_byte` and `used_byte`) and depreciation of the current ones.
This is as documented as it can get and maybe also appreciated. 

So far 3 people out of 3 are uncomfortable with the kibibyte unit.

**Comment by techhat** [comment]
I agree: I think using 1K blocks is stupid. But it is the way it is... in Linux. Change it there, and it will cause problems for the average Linux user.

Fortunately, Windows functionality is provided by an entirely different file, so making it correct in Windows will not break Linux. And I see no reason not to just specify things in bytes instead of blocks on Windows, because that's what people are used to in Windows.

**Comment by davidjb** [comment]
@techhat -1 on making disk.usage inconsistent between platforms. That's breaking the abstraction that Salt is providing, imagine trying to work with targets of mixed platforms.

+1 to @markuskramerIgitt solution or similar; it makes the units obvious and deprecates the confusing existing behavior.

**Comment by davidjb** [comment]
As per #23840, whatever we do here, the type of values returned must be consistent.

**Comment by techhat** [comment]
How about this? Implement `disk.usage_bytes` and `disk.usage_blocks` for all platforms, and deprecate disk.usage. Because as nice as it is to be consistent between all platforms, the fact of the matter is that blocks doesn't make sense for Windows, but defaulting to anything else doesn't make sense in Unix and Linux. This presents both behaviors in all platforms, but requires users to be explicit in which one they choose.

Exposing consistent behavior in Salt is nice and all, but there are plenty of cases where trying enforce the behavior of one upon to other, just in the name of consistency, is asking for trouble.

**Comment by davidjb** [comment]
I definitely agree that both units are needed for those reasons, but is there a need to split the functionality?  As per @markuskramerIgitt's suggestion above, having the one function returning both bytes/blocks values at once feels more flexible -- whatever is consuming the returned structure can make the choice of data required rather than trying to decide ahead of time when calling the module.

**Comment by davidjb** [comment]
Please reopen; still an issue at last check.

**Comment by davidjb** [comment]
Bump

**Comment by markuskramerIgitt** [comment]
@davidjb, please continue without me.
