### ISSUE TITLE
cmd.run should have a filter

### ISSUE THREAD

**Issue by atkinsd** [saltstack/salt#22558]
To make cmd.run safer it should have a filter on the commands which can be run a
black list and a white list system.

e.g. it should be able to prevent
```bash
salt \* cmd.run "rm -fr /tmp /*"
```
Or many be a white list/black list for a group a person belongs too.???

**Comment by jfindlay** [comment]
You can use [client ACL](http://docs.saltstack.com/en/latest/ref/clientacl.html) to whitelist execution modules per user.  For example, you could whitelist `state.sls` and then ensure that the states applied to the minions have been peer reviewed,
```yaml
# /etc/salt/master
...
client_acl:
  saltadm:
    - state.sls
...
```
Another solution you can try is to run the minion process as a non-root user and use the ACL mechanisms provided by sudo to prevent `rm -fr /`, for example.

**Comment by tehmaspc** [comment]
+1

I would like to see this as well after realizing that one can destroy their infrastructure if they don't know what they are doing.
I think a whitelist option would be best - that way I could additively add safe commands as I needed over time. I'd rather cmd.run be unusable at first till I add the ability to run x,y,z commands.

**Comment by maschinetheist** [comment]
+1 this as well. I would love to whitelist cmd.run 'sudo' commands.

**Comment by damon-atkins** [comment]
+1 this is a good start, but something more is needed.
```
client_acl:
  saltadm:
    - state.sls
```
Unfortunately this does not control the name of the state file for example.  An example might be restricting what  Jenkins can do. e.g what states it can run and what cmd it can run. 

I think part of the problem is every state or execution module is different and has different needs

Maybe modules are provide with enough information (username, saltenv) , they could use a function to request an ACL and then process it, itself.

e.g.
```
client_acl:
  saltadm:
    -  state.highstate:
      - jenkins.sls
```
Inside state.highstate code it calls
salt.utils.fetch_acl which  returns 'jenkins.sls'   

It would not stop someone altering the code directly on the minion to allow it.

Hope this sparks an idea.

**Comment by rickh563** [comment]
ZD-797 Writes:

----------------

Since we cannot disable the "cmd.run" function (we use cmd.run a lot in our states), but we want to avoid accidentally execution of some commands that could cause a disaster such as the one below.

sudo salt "*" cmd.run 'rm -rf /'

We are looking for a way to configure salt (master or minion) such that only certain commands can be run with cmd.run (a whitelist) or to prohibit certain commands to run with cmd.run (a blacklist), ideally both.

----------------

**Comment by thatch45** [comment]
Let me know if you all think that this PR looks good for this

**Comment by damon-atkins** [comment]
Thanks for looking at my request

**Comment by thatch45** [comment]
yes, basically it is hard to know if the cmd.run is being called as a module cross call or as part of a state, but we do know if it is from remote-ex or salt call, so we really can't restrict state files in the same way, but I also don't think this issue is a worried about state files, since I think the main thing here is making sure you don't fat finger something crazy
