### ISSUE TITLE
Use of sys.exit in salt.crypt module

### ISSUE THREAD

**Issue by a-wildman** [saltstack/salt#22811]
The salt.crypt module has more than one place where sys.exit() can be invoked.  I've run into an issue where instantiating a salt.client.Caller winds up triggering that, which is problematic given that salt.client is being used as a library.  Some sort of exception should be raised by salt.crypt instead.

**Comment by basepi** [comment]
Oh ya, that's no good in this case. We'll re-evaluate these instances.

@thatch45 ping

**Comment by cachedout** [comment]
Well, technically an exception *is* being raised, since that's what ```sys.exit``` does. :] https://docs.python.org/2/library/exceptions.html#exceptions.SystemExit

That said, I'm sure we could improve this somewhat. Could you catch SystemExit and log a traceback for us to take a look at? Then we can take a look and see if it makes sense to raise something more specific or move the exit to another location. Thanks!

**Comment by a-wildman** [comment]
Bouncing the keys on all of our minions made whatever the underlying problem was go away -- so unfortunately I'm unable to reproduce it (and generate a traceback).  

While I appreciate that sys.exit *technically* raises an exception, library modules should probably stick to raising something inheriting from Exception, IMHO ;)

**Comment by cachedout** [comment]
Yes, fair enough. I agree.

We just need to move the sys.exit call up a few layers and keep the Salt API easy to use. We'll take care of it. :]

**Comment by bkruger99** [comment]
Not sure if this is the right place, but using salt.client.Caller, with a minion that doesn't have an accepted key on a master, will pretty much just hang forever.   I was trying to write some code to detect if the minion has a valid key with the master or not. 

If you execute:  
salt-call saltutil.revoke_auth (via command line) and then run the script

import salt.client
caller = salt.client.Caller()
caller.cmd('status.master')
