### ISSUE TITLE
Is the saltstack/zeromq COPR still being maintained?

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#22827]
When I was checking the saltstack/salt COPR repo to see if salt 2014.7.5 was available there yet (it is!), I noticed that zeromq and python-zmq had also been built in that COPR repo. Previously, they were in the saltstack/zeromq COPR repo.

Which is the way ahead, for zeromq and python-zmq to be available in the saltstack/salt COPR or the saltstack/zeromq COPR? (The keys are different for each repo, so it makes a difference where the packages come from when trying to automate the creation of offline repos for internal use...)

**Comment by rallytime** [comment]
Thanks for the question @lorengordon. I **think** the way forward is for zeromq and python-zmq to be maintained in the saltstack/salt COPR. The RHEL/CentOS 5 builds had to be separated out from the regular saltstack/salt COPR because Python 2.6 support for CentOS 5 was removed from EPEL, so we had to create the CentOS5 COPR to become the primary CentOS 5 source of salt. I think that was when we moved the saltstack/zermq COPR over to the saltstack/salt COPRs.

However, @terminalmage is the one who maintains these COPR repos, so he probably should give the definitive decision here.

**Comment by terminalmage** [comment]
@lorengordon I'm going to remove them from the saltstack COPR, I just built them the other day to try to address some odd COPR build errors in the test suite.

They should be primarily retrieved from the zeromq COPR.

**Comment by terminalmage** [comment]
@lorengordon I've removed the zeromq4 builds from the saltstack COPR, and built the newest zeromq 4 and pyzmq on the zeromq4 COPR.

I'm going to go ahead and close this. Thanks for bringing this up.

**Comment by lorengordon** [comment]
Thanks @terminalmage!
