### ISSUE TITLE
Question regarding the use of the variable "state" within a state module

### ISSUE THREAD

**Issue by Anthonyhawkins** [saltstack/salt#22879]
Ran into an interesting issue, wondering if there is an easy fix or I just need to choose a different variable name.

I'm in the process of working on a state module for F5 BigIP and it's common in F5 language to refer to  the "state" of various entities such as virtual servers, nodes, pool-members etc.  I'd like to use the parameter "state" within the various functions within the module but running into this issue here:

```python
def manage_node(hostname, username, password, name, address,
                connection_limit=None,
                description=None,
                dynamic_ratio=None,
                logging=None,
                monitor=None,
                rate_limit=None,
                ratio=None,
                session=None,
                state=None):
```
If I output the value for state I get back "bigip" not the value which I set in the sls file such as "user-up, user-down etc"

```python
    ret['comment'] = state
    return ret
```

```python
local:
----------
          ID: my-awesome-node-1
    Function: bigip.manage_node
      Result: False
     Comment: bigip
     Started: 02:08:48.414262
    Duration: 1.281 ms
     Changes:
```

Seems like the variable "state" is used somewhere else during the execution process. Also if there a doc which mentions any special variables etc. I wouldn't mind looking over it to avoid future conflicts.

Thank You.

**Comment by gtmanfred** [comment]
This isn't really going to be able to be changed, because it is one of the state runtime frozen key words

https://github.com/saltstack/salt/blob/develop/salt/state.py#L69

And then when it loads those modules and variables, it injects the name into the state module for use in other actions.

https://github.com/saltstack/salt/blob/develop/salt/state.py#L835
https://github.com/saltstack/salt/blob/develop/salt/state.py#L799-810

when everything is loaded, those bigip.manage_node you are using is referenced inside the modules dictionary by the data['state'] + data['fun']

https://github.com/saltstack/salt/blob/develop/salt/state.py#L849

This is a full list of everything that can be injected and is reserved for use in the loader/states.py

https://github.com/saltstack/salt/blob/develop/salt/state.py#L48-98

I do not believe there is an explicit list of all those inside of the documentation at this time.

**Comment by Anthonyhawkins** [comment]
Thank you for the detailed response.  This answers my questions.

**Comment by gtmanfred** [comment]
No problem. :)
