### ISSUE TITLE
Add listen_onchanges requisite

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#23022]
Edit: see a few comments below for the proposed solution

Consider the following state:

``` sls

/etc/file1:
  - file.managed:
    - source: salt://file1

echo 1:
  - cmd.wait:
    - listen:
      - file: /etc/file1

echo 2:
  - cmd.wait:
    - listen:
      - cmd: echo 1
```

When `file1` changes I'd expect both `echo 1` and `echo 2` to run at the end of the state, with `echo 2` running last. What happens is that `echo 2` never actually runs.

**Comment by basepi** [comment]
I think this is expected behavior, based on the way that listen/watch and `cmd.wait` are implemented.

Basically, listen/watch are supposed to trigger additional behavior when there are changes made in the target state. `cmd.wait` was designed to use this to approximate "only do this when changes are made" behavior. (These days, `onchanges` is the way to go) It does this by having the base `cmd.wait` state be a no-op, just return success. Then the `mod_watch` function does the actual work when the listen/watch are triggered.

So, the problem is that the second listen is watching the base, no-op version of the `echo 1`. It never sees the changes, because requisites can't act on the results of `mod_watch`. Pretty sure there's another issue similar to this somewhere, but I can't find it at the moment.

I'm not sure what the solution is, it may take some serious work in the state compiler, or it may be an easy fix. I'll probably have to get @thatch45 involved.

**Comment by basepi** [comment]
We also will have to have a discussion on whether this *should* be fixed. Other states which have real default behavior (as opposed to a no-op), and additional behavior in their mod_watch will complicate this, because then you don't know which function run you want to target with your listen/watch.

**Comment by clinta** [comment]
I prefer to use `onchanges` whenever I can. But as far as I'm aware `onchanges` does not move the state execution to the end like listen does.  A new requisite like `listen_onchanges` would meet my use cases, and it would work for states that don't support `wait`.

**Comment by basepi** [comment]
Good call. I'll mark this as a feature.

**Comment by basepi** [comment]
BTW, an `order: last` may help as a workaround for now.
