### ISSUE TITLE
Module and Function Naming standard

### ISSUE THREAD

**Issue by atkinsd** [saltstack/salt#23133]
Salt is growing.   It needs to consider a naming standard

For example
<vendor/platform>.<module>.<function>
linux.sysctl.show
win.reg.Registry   # Should all functions be lower case.
linux.rhel.license

Anything which is two levels is generic e.g.  disk.usage  and design to be compatible with all platforms

Before you grow much more come up with a standard. Rename all the modules to that standard with aliases for backwards compatibility.

Should the module directory structure be flat or contain cpu type or platform. 
e.g. linux.sysctl.show be linux/sysctl.show

Think about what it would be like if you had thousands of modules instead of the current 100 or so.

**Comment by basepi** [comment]
We're well aware that the list is beginning to get unwieldy. However, the loader expects a flat directory structure, and so will have to be refactored. Eventually we'll have to settle on some sort of namespacing, or stop packaging *all* modules with salt by default. However, there's no hurry in making these decisions yet. =)

**Comment by damon-atkins** [comment]
Disagree with the hurry bit. I would have thought  @thatch45 would hope for strong growth and many people contributing. 
Every day you leave it:
* More people start to use salt, and develop yaml with old standard, increase the number of impacted people
* More discussion will be required because of the impact to your customer base.
* Less likely it will be ever fixed due to the impact. 

Plan for success, rather than waiting for it to happen.

**Comment by whiteinge** [comment]
There is some evidence to suggest that we have [strong growth](https://github.com/saltstack/salt/pulse/monthly) and [many contributors](https://github.com/saltstack/salt/graphs/contributors). YMMV. :-)

Your core complaint is indeed correct. The [module index](http://docs.saltstack.com/en/latest/salt-modindex.html) is not at all sufficient to display the breadth of platform support for each module. The detailed docs on each module are not sufficient either. Since we support more than simply Linux and Windows a top-level, static, filename-based namespacing would not at all be sufficient.

Our current plans are to fill out and augment the field lists in the docstring for each module (and potentially each function) with more information. Most modules currently have `:configuration:` and `:depends:` and `:optdepends:` information. Adding a list of supported platforms (SUSE, FreeBSD, OS X) to each module will allow us to build out indexes and sub-pages in the documentation for specific platforms. This is a flexible approach that can handle a mix-and-match approach to platform support and can even be used for non-platform related modules, such as grouping all AWS-specific modules regardless of module type. This is structured data that is also available at the CLI that could be used to self-document and guide beginning Salt users through the process of constructing a command.

**Comment by damon-atkins** [comment]
Some more thoughts to add

You need a module naming standard.  It appears to be 
https://github.com/saltstack/salt/tree/develop/salt/modules
<OS>_<ProductName|Module>  however not all modules are named like this.

For example solarisips.py vs yumpkg.py

SmartOS uses the package Manager from NetBSD, even though SmartOS is very much like Solaris/Illumos. http://www.netbsd.org/docs/software/packages.html

This comes now to module naming standards, which allow support for multiple OS and the fact some software is available on multiple OS. java naming standard like maybe. Then the layer on top of this is the virtual names and their standard functions every module must implement and then optional functions it must implement. If you call the solaris one solars_system the linux one should be called linux_system and aix_system etc.

When someone wants to add a new os, what is the standard they should follow and the expected functions, so that all VIRTUAL Modules support the same functions.

In some respects naming modules as <Function Group>_<OS> would be better. And the Virtual  Name would be the "Function Group".
e.g
pkg_yum.py Fedora, RHEL, CENTOS
pkg_ips.py  Solaris 11+ and illumos
pkg_apt.py
pkg_dnf.py Fedora
pkg_Solsvr4.py Solaris 2-10
pkg_pkgsrc.py http://www.netbsd.org/docs/software/packages.html SmartOS and NetBSD and many others.
etc.
system_linux.py
system_netbsd.py
system_solaris.py
system_aix.py
system_hpux.py
firewall_ipf.py  Solaris
firewall_iptables.py  Many OS
firewall_nftables.py  Many OS to come
firewall_firewalld.py (maybe)
splunk.py (i.e. as all the code supports splunk on multiple OS) and if it needs to be split up one day it will still fit the naming standard.
Keep in mine Solaris 11 still supports SVR4 package system.

**Comment by damon-atkins** [comment]
.

**Comment by damon-atkins** [comment]
.

**Comment by damon-atkins** [comment]
.

**Comment by sagetherage** [comment]
Assigning myself to see if I can get traction on a discussion this week.

**Comment by thatch45** [comment]
This should be superseded by a SEP with an attached action plan
