### ISSUE TITLE
improvement: salt has problem to restart salt-minion systemd service with "successful" output

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#23257]
Hello,

... like he does for init.d restarts.
Manual restart of service works fine - exept there is not output anymore in compare to init.d:

```
root@test-nosql04(380):~# salt-call --version
salt-call 2014.7.5 (Helium)
root@test-nosql04(381):~# service salt-minion status
● salt-minion.service - The Salt Minion
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled)
   Active: active (running) since Fri 2015-05-01 15:10:49 UTC; 6s ago
 Main PID: 14019 (salt-minion)
   CGroup: /system.slice/salt-minion.service
           ├─14019 /usr/bin/python /usr/bin/salt-minion
           └─14115 /usr/bin/python /usr/bin/salt-minion

May 01 15:10:53 test-nosql04 salt-minion[14019]: [ERROR   ] Function cmd.run in mine_functions failed to execute
root@test-nosql04(382):~# service salt-minion restart
root@test-nosql04(383):~# service salt-minion status
● salt-minion.service - The Salt Minion
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled)
   Active: active (running) since Fri 2015-05-01 15:11:15 UTC; 30s ago
 Main PID: 14249 (salt-minion)
   CGroup: /system.slice/salt-minion.service
           └─14249 /usr/bin/python /usr/bin/salt-minion

May 01 15:11:18 test-nosql04 salt-minion[14249]: [ERROR   ] Function cmd.run in mine_functions failed to execute
```

check restart by master:

```
roo@saltmaster(1136):~# salt test-nosql04 cmd.run "service salt-minion restart"
test-nosql04:
    Minion did not return. [No response]
root@saltmaster(1137):~# salt --version
salt 2014.7.5 (Helium)
```

=> but on instance service was restarted:

```
root@test-nosql04(386):~# service salt-minion status
● salt-minion.service - The Salt Minion
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled)
   Active: active (running) since Fri 2015-05-01 15:17:20 UTC; 56s ago
 Main PID: 14717 (salt-minion)
   CGroup: /system.slice/salt-minion.service
           └─14717 /usr/bin/python /usr/bin/salt-minion

May 01 15:17:24 test-nosql04 salt-minion[14717]: [ERROR   ] Function cmd.run in mine_functions failed to execute
```

With other services the response is successfull (even if empty):

```
root@saltmaster(1138):~# salt test-nosql04 cmd.run "service postfix restart"
test-nosql04:
```

**Comment by jfindlay** [comment]
@Reiner030 did the minion return as expected in the non systemd case?

**Comment by gfa** [comment]
i have the same problem, salt 2014.7.5 does not restart my services when i'm using systemd on debian jessie. if i boot using sysvinit everything works as expected.


sysvinit output
          ID: mysql
    Function: service.running
      Result: True
     Comment: Service restarted
     Started: 14:31:53.690397
    Duration: 3469.817 ms
     Changes:   
              ----------
              mysql:
                  True

systemd output

          ID: mysql
    Function: service.running
      Result: True
     Comment: Service mysql has been enabled, and is in the desired state
     Started: 14:29:29.584260
    Duration: 347.826 ms
     Changes:   
              ----------
              mysql:
                  True

on both cases /etc/mysql/my.cfg was modified.

state file:

mysql-server:
  pkg.installed:
    - name: mysql-server
    
mysql:
  service.running:
    - name: mysql
    - enable: True
    - restart: True
    - watch:
      - file: /etc/mysql/my.cnf
    - require:
      - pkg: mysql-server

/etc/mysql/my.cnf:
  file.managed:
    - source: salt://mysql/my.cnf.ubuntu
    - template: jinja
    - defaults: 
      hostname: {{ salt['grains.get']('fqdn') }}

**Comment by gfa** [comment]
at least on debian jessie, you can use service status, service start and stop to manage services, native systemd and lsb legacy services

from a different system
$ sudo systemctl stop smbd
$ sudo service smbd status     
● smbd.service - LSB: start Samba SMB/CIFS daemon (smbd)
   Loaded: loaded (/etc/init.d/smbd)
   Active: inactive (dead)

May 03 23:00:45 io systemd[1]: Unit smbd.service cannot be reloaded because it is inactive.
$ echo $?                 
3

$ sudo systemctl stop ipsec 
$ sudo systemctl status ipsec
● strongswan.service - strongSwan IPsec IKEv1/IKEv2 daemon using ipsec.conf
   Loaded: loaded (/lib/systemd/system/strongswan.service; enabled)
   Active: inactive (dead) since Sun 2015-05-03 23:13:55 CST; 15s ago
  Process: 31097 ExecStart=/usr/sbin/ipsec start --nofork (code=exited, status=0/SUCCESS)
 Main PID: 31097 (code=exited, status=0/SUCCESS)

May 03 23:13:55 io ipsec[31097]: 07[CFG]   esp=3des-sha1
May 03 23:13:55 io ipsec[31097]: 07[CFG]   dpddelay=30
May 03 23:13:55 io ipsec[31097]: 07[CFG]   dpdtimeout=150
May 03 23:13:55 io ipsec[31097]: 07[CFG]   mediation=no
May 03 23:13:55 io ipsec[31097]: 07[CFG]   keyexchange=ikev1
May 03 23:13:55 io ipsec[31097]: 07[CFG] left nor right host is our side, assuming left=local
May 03 23:13:55 io ipsec[31097]: 07[CFG] added configuration 'yy-unicom'
May 03 23:13:55 io ipsec[31097]: 00[DMN] signal of type SIGINT received. Shutting down
May 03 23:13:55 io ipsec[31097]: charon stopped after 200 ms
May 03 23:13:55 io ipsec[31097]: ipsec starter stopped
$ echo $?                    
3
