### ISSUE TITLE
Unable to destroy host using proxmox cloud: There was an error destroying machines: 501 Server Error: Method 'DELETE /nodes/pmx1/openvz/openvz/100' not implemented

### ISSUE THREAD

**Issue by pruiz** [saltstack/salt#23364]
Hi,

While testing salt-cloud's proxmox provider I've found I cant destroy/delete a host due to the following error: There was an error destroying machines: 501 Server Error: Method 'DELETE /nodes/pmx1/openvz/openvz/100' not implemented

By looking at the request it looks like 'openvz' is being passed twice as part of the resource URI.

I think I've spotted the error and I will be sending a pull-req soon. Let this issue serve as marker for it.

**Comment by pruiz** [comment]
Ok, I've just checked develop and it looks like it is fixed.

I am closing this issue.

**Comment by rallytime** [comment]
@pruiz Glad that this is fixed on develop and thanks for looking into this. If you end up finding where the fix was and it is a relatively simple fix, maybe we should backport it and get it into a release branch, or apply the fix to 2014.7 or 2015.2?

**Comment by pruiz** [comment]
Sore, If I am not wrong, the changeset fixing this issue should be: https://github.com/saltstack/salt/commit/5927138f49be283cb051b5777a25636120be22a3

**Comment by pruiz** [comment]
I just found a gotcha on current develop code: destroy fails if the host is not running/has already been stopped with:

[ERROR   ] There was an error destroying machines: 500 Server Error: CT 100 not running

Looks like it tries to stop the node, but as has yet been stopped.. it goes kaboom.. ;)

**Comment by pruiz** [comment]
Yeah, confirmed, the call to 'stop' withing destroy(..) should be wrapped by a condition like:

```
        # stop the vm
        if get_vm_status(vmobj['vmid'])['status'] != 'stopped':
            stop(name, vmobj['vmid'], 'action')
````

**Comment by rallytime** [comment]
@pruiz I think you're right about the changes you linked in your first comment since I labeled everything. However, it looks like that change *did* make it into the 2015.2 branch. (The line on the 2015.2 branch is [here](https://github.com/saltstack/salt/blob/8837d0038e422189101ad5d8050c37d9df321edf/salt/cloud/clouds/proxmox.py#L848))

It would be awesome if you'd like to submit a pull request with the change you've suggested for fixing the 500 server error you're hitting with the condition. If you're able to do so, please submit the change against the 2015.2 branch, if you could. Otherwise, one of us can pick up this change later.

I am going to reopen this ticket until the not running error is resolved. Thanks again!

**Comment by pruiz** [comment]
@rallytime Sure, I'll make a pullreq. Should it be against develop and/or 2015.2?

**Comment by rallytime** [comment]
Please make it against 2015.2 (which has now been renamed 2015.5, to reflect our actual release date.) The 2015.5 branch is merged into develop every couple of days, so there is no need to make the change against both. (You can read more about this process [here](http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch), if you'd like.) Thanks @pruiz!
