### ISSUE TITLE
DOCUMENTATION(minor): pillar_refresh vs refresh_pillar

### ISSUE THREAD

**Issue by tkent-xetus** [saltstack/salt#23613]
A minor issue that I noticed when doing a copy/paste from the docs:

The [saltutil module docs](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html) have a title of `pillar_refresh` for the function (which is wrong) and the example shows `refresh_pillar`.

I assume it's a 2 second swap for someone.

**Comment by cachedout** [comment]
I think this is actually coming from the alias for the function that was added. Since the docs are autogenerated from the module itself, it's a little tricky.

I played around a little bit with trying to modify the loader to accept multiple function aliases, but it just made things more complex and didn't really solve the problem. There might be a way, instead, to just get the docs generators to skip the incorrect alias.

cc: @whiteinge for any ideas on that.

**Comment by whiteinge** [comment]
We could certainly modify our autodoc subclass to do something smart
here. The quickest fix is to edit the generated .rst file for that
module and just add aliases or other things to the `exclude-members`
field list. E.g.:

https://raw.githubusercontent.com/saltstack/salt/670625c/doc/ref/modules/all/salt.modules.win_system.rst
