### ISSUE TITLE
file.recurse doesn't do symlinks

### ISSUE THREAD

**Issue by LeTink** [saltstack/salt#23621]
# environment

master & minion are Ubuntu 12.04, salt version on all is 2015.5.0+ds-1precise1
# problem

Trying to push minicom configuration out to a set of minions with multiport serial cards doesn't work as expected.  On the master we have a directory with both config files and symlinks to these.
# state file

``` YAML
{% if salt['match.pcre']('^oob-.*') %}
push_minicom:
  file.recurse:
    - name: /etc/minicom
    - force_symlinks: True
    - user: root
    - group: root
    - source: salt://minicom/minicom
    - file_mode: 644
    - sym_mode: 777
{% endif %}
```
# directory listing on master

``` Shell
ls -l minicom/minicom
total 32
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.dfl -> minirc.ttyS4
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.port1 -> minirc.ttyS4
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.port2 -> minirc.ttyS5
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.port3 -> minirc.ttyS6
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.port4 -> minirc.ttyS7
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.port5 -> minirc.ttyS8
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.port6 -> minirc.ttyS9
lrwxrwxrwx 1 root root  13 Jan 22  2014 minirc.port7 -> minirc.ttyS10
lrwxrwxrwx 1 root root  13 Jan 22  2014 minirc.port8 -> minirc.ttyS11
-rw-r--r-- 1 root root 558 Jan 22  2014 minirc.ttyS10
-rw-r--r-- 1 root root 558 Jan 22  2014 minirc.ttyS11
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS4
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS5
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS6
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS7
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS8
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS9
```
# executing the state

```
salt oob-lab\* state.sls minicom
oob-lab.reannz.co.nz:
----------
          ID: push_minicom
    Function: file.recurse
        Name: /etc/minicom
      Result: True
     Comment: Recursively updated /etc/minicom
     Started: 09:34:28.046360
    Duration: 348.033 ms
     Changes:   
              ----------
              /etc/minicom/minirc.port1:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /etc/minicom/minirc.port2:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /etc/minicom/minirc.port3:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /etc/minicom/minirc.port4:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /etc/minicom/minirc.port5:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /etc/minicom/minirc.port6:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /etc/minicom/minirc.port7:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /etc/minicom/minirc.port8:
                  ----------
                  diff:
                      New file
                  mode:
                      0644

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
# directory on the minion after the state

``` Shell
ls -l /etc/minicom
total 64
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.dfl -> minirc.ttyS4
lrwxrwxrwx 1 root root  13 Feb  4  2014 minirc.ex3300-1 -> minirc.ttyS11
lrwxrwxrwx 1 root root  13 Feb 24  2014 minirc.ex4550-1 -> minirc.ttyS10
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.mlx4 -> minirc.ttyS5
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.mlx-4 -> minirc.ttyS5
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.mlx8 -> minirc.ttyS4
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.mlx-8 -> minirc.ttyS4
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.mx-80-1 -> minirc.ttyS6
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.mx80-1 -> minirc.ttyS6
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.mx-80-2 -> minirc.ttyS7
lrwxrwxrwx 1 root root  12 Jan 22  2014 minirc.mx80-2 -> minirc.ttyS7
**-rw-r--r-- 1 root root 557 May 13 09:34 minirc.port1**
**-rw-r--r-- 1 root root 557 May 13 09:34 minirc.port2**
**-rw-r--r-- 1 root root 557 May 13 09:34 minirc.port3**
**-rw-r--r-- 1 root root 557 May 13 09:34 minirc.port4**
**-rw-r--r-- 1 root root 557 May 13 09:34 minirc.port5**
**-rw-r--r-- 1 root root 557 May 13 09:34 minirc.port6**
**-rw-r--r-- 1 root root 558 May 13 09:34 minirc.port7**
**-rw-r--r-- 1 root root 558 May 13 09:34 minirc.port8**
-rw-r--r-- 1 root root 558 Jan 22  2014 minirc.ttyS10
-rw-r--r-- 1 root root 558 Jan 22  2014 minirc.ttyS11
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS4
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS5
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS6
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS7
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS8
-rw-r--r-- 1 root root 557 Jan 22  2014 minirc.ttyS9
```

**Comment by tinkster** [comment]
# update

I added a centos 6.6 minion to the experiment, and still get files instead of symlinks.

**Comment by jfindlay** [comment]
@tinkster, thanks for the report.

@lorengordon, forgive me if I am wrong, but did you do any work related to the file state/module and symlinks?

**Comment by lorengordon** [comment]
@jfindlay, I only worked within `file.replace` module. I hadn't looked at the code for the `file.recurse` state. A quick glance looks like they share nothing.

I see in the [docs](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.recurse) that `file.recurse` accepts a `keep_symlinks` parameter that defaults to `false`. Perhaps try setting it to `true`?

```yaml
{% if salt['match.pcre']('^oob-.*') %}
push_minicom:
  file.recurse:
    - name: /etc/minicom
    - force_symlinks: True
    - keep_symlinks: True
    - user: root
    - group: root
    - source: salt://minicom/minicom
    - file_mode: 644
    - sym_mode: 777
{% endif %}
```

**Comment by tinkster** [comment]
Hi @lorengordon @jfindlay 

I had that keep_symlinks in there, too, but it doesn't make a difference.
Tried several permutations.
The way I understand the doco keep_symlinks only means to not replace
existing symlinks w/ files; that is really not what I want in the first place, though.

**Comment by lorengordon** [comment]
@tinkster, shoot. I wasn't sure what that parameter was supposed to do from reading the doc. As written, it could have referred to keeping symlinks on the minion, or it could have meant keeping symlinks when copying them from the master to the minion. I skimmed the code and was hopeful that it was the latter, but apparently not. :/

**Comment by tinkster** [comment]
An interesting observation from IRC was that it seems to work as expected
on Centos (master and minion both running 6.5).

And, the problem was the same with 2014.7.5 ( I upgraded half-way through
the trouble-shooting in the hopes it would go away):



<andrej> So, I've been fighting with file.recurse for two days now ... I
have a load of minicom port config files & syml
inks sitting in /srv/salt/minicom/minicom ... pushing this out via the
state creates all files, no symlinks.  Why?
�� SignOff nyx_: #salt (Quit: My MacBook Pro has gone to sleep.
ZZZzzz�<80>�)
<andrej> http://pastebin.com/rghSJ54b
<andrej> http://pastebin.com/3pAS40hw
�� adfafqwdefqae [3b64cbd6@gateway/web/freenode/ip.59.100.203.214] has
joined #salt
<andrej> The first paste is the init.sls, the 2nd is the directory on the
master
�� Not_ [~Hex_Offen@208.167.254.55] has joined #salt
<andrej> this is the result on the minion http://pastebin.com/Cptsk6PT
�� Cottser|away is now known as Cottser
�� ErKa [~keryell@50-1-112-167.dsl.dynamic.fusionbroadband.com] has joined
#fai
�� SignOff aparsons: #salt (Quit: My MacBook Pro has gone to sleep.
ZZZzzz�<80>�)
�� SignOff gwmngilfen: #salt (Ping timeout: 240 seconds)
�� rojem [~rojem@pool-71-174-215-156.bstnma.fios.verizon.net] has joined
#salt
�� SignOff spookah: #salt ()
�� joeto [~joeto@smtp.homebg.org] has joined #salt
�� SignOff hybridpollo: #salt (Quit: WeeChat 0.4.2)
�� SignOff ErKa: #fai (Ping timeout: 480 seconds)
�� SignOff TOoSmOotH: #salt (Ping timeout: 256 seconds)
�� SignOff ageorgop: #salt (Ping timeout: 255 seconds)
<iggy> andrej: protip: gist.github.com allows multiple files per paste
�� linjan [~linjan@213.8.240.146] has joined #salt
<iggy> the indentation looks messed up to
�� SignOff murrdoc: #salt (Quit: Leaving.)
�� rideh [~rideh@unaffiliated/rideh] has joined #salt
�� SignOff rideh: #salt (Client Quit)
�� SignOff subsignal: #salt (Remote host closed the connection)
�� rideh [~rideh@unaffiliated/rideh] has joined #salt
�� SignOff rideh: #salt (Client Quit)
�� pdayton [~pjdayton@63.251.sfcn.org] has joined #salt
�� dfinn [~Adium@c-50-160-35-73.hsd1.ut.comcast.net] has joined #salt
�� SignOff dfinn: #salt (Client Quit)
�� rdas [rdas@nat/redhat/x-lddoqmljwggtlngw] has joined #salt
�� pav5088__ [~markp@ppp118-208-44-176.lns20.bne7.internode.on.net] has
joined #fai
�� SignOff pav5088_: #fai (Ping timeout: 480 seconds)
<VR-Jack> andrej: umm, what's the problem again?
�� SignOff Not_: #salt (Quit: Leaving)
<VR-Jack> n/m
�� SignOff adfafqwdefqae: #salt (Quit: Page closed)
�� SignOff linjan: #salt (Ping timeout: 256 seconds)
�� ramteid [~textual@83-64-52-210.fadingerstrasse.xdsl-line.inode.at] has
joined #salt
�� SignOff amcorreia: #salt (Ping timeout: 250 seconds)
<VR-Jack> andrej: works on centos6.5 master and minion w/ salt 2014.7.5
using salt '*' state.sls from master, ZMQ transp
ort.
<VR-Jack> I didn't have the jinja in mine. no reason for it in testing
<andrej> iggy, thanks for the pro-tip :}
<andrej> I never claim to be professional ;}
<manfred> Ryan_Lane:  it used to be .keys()
<manfred>
https://github.com/saltstack/salt/commit/152154df5701b269d4e7d8bd32a79afec5a367ec
<Ryan_Lane> well, it's unnecessary to use .keys()
<andrej> VR-Jack : the state doesn't carry the symlinks to the minion as
symlinks, but rather creates files.
<mirko> (repost from earlier today) i think i'm having an issue with
"file.recurse" - the directory to copy over contain
s an empty one which is skippsed. although "include_empty: True" is
specified.
<manfred> sure
<andrej> iggy : when you said the indentation looks messed up ... could you
be more specific?
<VR-Jack> andrej: it made symlinks on mine
<andrej> VR-Jack : what does your state look like, do you mind sharing?
<VR-Jack> andrej: copied yours, but here you go.
https://gist.github.com/vr-jack/7cc4444c6b6ba6132686
<kunersdorf> andrej: does your code render right in yaml renderer?
�� Setsuna666 [~Setsuna66@modemcable170.119-37-24.static.videotron.ca] has
joined #salt
�� florinandrei [~florinand@64-79-119-126.static.wiline.com] has joined
#salt
<manfred> Ryan_Lane:  it almost sounds like minion is a dictionary already,
and is being passed as the key for parts?
�� solidsnack [~solidsnac@pdpc/supporter/active/solidsnack] has joined #salt
<Ryan_Lane> I think they may be running mixed versions
�� Cottser is now known as Cottser|away
�� baweaver [~baweaver@173.230.196.25] has joined #salt
�� SignOff solidsnack: #salt (Max SendQ exceeded)
�� SignOff dfinn1: #salt (Quit: Leaving.)
<manfred> Ryan_Lane:  http://ix.io/iw7
<andrej> VR-Jack - what does the content of salt://test look like?
<andrej> Thanks for the paste, btw
<andrej> kunersdorf : how do I assess that?
�� solidsnack [~solidsnac@pdpc/supporter/active/solidsnack] has joined #salt
�� rap424 [~rap424@nat.jaspersoft.com] has joined #salt
<kunersdorf> paste your yaml into a tool like this:
http://yaml-online-parser.appspot.com/
<kunersdorf> if yaml is good, no red text
<VR-Jack> andrej: updated that jist
�� RedundancyD [~Redundanc@fw.encs.vancouver.wsu.edu] has left #salt []
�� SignOff solidsnack: #salt (Max SendQ exceeded)
�� chiui [~chiui@2001:5c0:1400:a::8b] has joined #salt
�� RedundancyD [~Redundanc@fw.encs.vancouver.wsu.edu] has joined #salt
�� solidsnack [~solidsnac@pdpc/supporter/active/solidsnack] has joined #salt
<andrej> Thanks VR-Jack  ... that's confusing. It might be an ubuntu issue
�� seev [~seev@c-73-163-172-107.hsd1.dc.comcast.net] has joined #salt
<VR-Jack> andrej: could be. selinux? fs type? etc etc



On 14 May 2015 at 08:01, Loren Gordon <notifications@github.com> wrote:

> @tinkster <https://github.com/tinkster>, shoot. I wasn't sure what that
> parameter was supposed to do from reading the doc. As written, it could
> have referred to keeping symlinks on the minion, or it could have meant
> keeping symlinks when copying them from the master to the minion. I skimmed
> the code and was hopeful that it was the latter, but apparently not. :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/issues/23621#issuecomment-101797030>.
>



-- 
Please don't top post, and don't use HTML e-Mail :}

http://www.georgedillon.com/web/html_email_is_evil.shtml

**Comment by arr2036** [comment]
Seeing this on RHEL6 also, exact same behaviour.

**Comment by nlm** [comment]
It's not exactly the same problem, but probably the same bug:
This is still not working with salt-ssh 2016.3.3 (Boron)

The cache directory (/var/tmp/.xxxxxxxx_salt/running_data/var/cache/salt/minion/) already has lost the symlinks and has them replaced with regular files

**Comment by viccuad** [comment]
I can reproduce this on 2016.11.2 on Debian.

I've tried `rsync.synchronized` as a workaround, but sadly it falls short, since
I need to set the user, group and permissions too.

**Comment by dynek** [comment]
Has any new issue been opened since then?
I'm having a similar issue (the target of the symlink don't exist on the master though).
And it fails with `Source file salt://[..]?saltenv=base not found in saltenv 'base'`
Other files (non symlinks) are replicated without any issue.

**Comment by Daemonslayer2048** [comment]
Has anyone else also ran into this issue in the 3000 releases? This issue still appears to be a problem, one can use follow symlinks to set the other end of the link but the symlink itself will not change group permissions.
