### ISSUE TITLE
Installing .deb package does not handle recursive dependencies

### ISSUE THREAD

**Issue by moloney** [saltstack/salt#23735]
I came across issue #10107, but only direct dependencies are handled. Having salt do this recursive dependency checking seems like we are trying to recreate functionality already built in to apt.

**Comment by tweenk** [comment]
This issue is completely wrong, please close it. The module works as intended.

apt-get, the high level package manager, resolves dependencies, but cannot install standalone files - only files which are in repositories. dpkg, the low level package manager, installs .deb files directly but does not handle dependency resolution. To correctly install a standalone .deb file, you need to first install its dependencies with apt-get (which will take care of recursively resolving dependencies) and then install the file itself with dpkg. This is exactly what the module does right now.

**Comment by jfindlay** [comment]
@moloney, you can either host the package in a repository so that you can use the apt state to install it (and handle dependencies), or figure out what the full dependency list is and create states that install them along with your package.  The dpkg util cannot handle recursive deps, and from what I know, apt cannot handle package files.

**Comment by tweenk** [comment]
@jfindlay No, it's not necessary to create any states that install the dependencies.

When Salt installs a .deb file, its list of dependencies is read, each of them is installed with apt-get and marked as an automatic dependency with apt-mark, and finally the .deb file is installed with dpkg.

The only thing I'm not sure about is whether only newly installed dependencies are marked as automatically installed, or all of them are marked as such. The second behavior would be a bug.

PS I did not write the above code, I only read it. :)

**Comment by moloney** [comment]
Sorry, there was some user error involved here.  Initially I was missing a needed .deb which caused subsequent apt-get calls to spit out errors, even after I included it.  After resetting everything to a clean state things work as expected. Sorry for the noise!

**Comment by jfindlay** [comment]
@tweenk, thanks for the explanation.  @moloney, I'm glad you got this sorted out.
