### ISSUE TITLE
Amazon Linux shouldn't get the RedHat os_family grain

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#23778]
Recent versions of Amazon Linux have adopted a completely different numbering scheme than RHEL/CentOS. This causes breakage when using version numbers that are expected to fit the RHEL numbering scheme.

One example:

``` repo.sls
nginx_yum_repo:
  pkgrepo.managed:
    - name: nginx
    - humanname: nginx repo
    - baseurl: 'http://nginx.org/packages/rhel/$releasever/$basearch/'
    - gpgcheck: False
    - enabled: True
```

$releasever right there is expected to be a single digit {5,6,7}. Instead on Amazon Linux it ends up being 2015 or so.

**Comment by rallytime** [comment]
Thanks for the report @iggy.

@terminalmage ping

**Comment by iggy** [comment]
I'm guessing this would have to be a long term goal. Changing it now would likely negatively impact a lot more than it would help.

**Comment by lorengordon** [comment]
I'm not sure changing the os_family grain would be the right approach here, anyway. I'm pretty sure on RHEL 6 and 7, the yum variable for `$releasever` maps to `6Server` or `7Server`, respectively, rather than a single digit. Only CentOS uses a single digit. And on Amazon Linux, `$releasever` defaults to `latest` (though their [docs](http://aws.amazon.com/amazon-linux-ami/faqs/#lock) do tell you how to change it). At least, these were my findings when doing some testing around these things last week.

**Comment by rallytime** [comment]
Good input @lorengordon. I'm not as familiar with this stuff as @terminalmage, but I'll add the "Pending Discussion" label for now until a "best approach" can be reached.
