### ISSUE TITLE
[docs] 2015.2 release notes aren't in the 2015.2 docs

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#23799]
http://docs.saltstack.com/en/latest/topics/releases/2015.2.0.html

**Comment by iggy** [comment]
Also not working:
http://docs.saltstack.com/en/develop/topics/releases/2015.5.0.html

If anybody needs them:
https://github.com/saltstack/salt/blob/v2015.5.0/doc/topics/releases/2015.5.0.rst

**Comment by rallytime** [comment]
@iggy I think the 2015.2.0 release notes should be a 404 on that very first link, since that "version" doesn't exist anymore. However, I've also discovered that by changing the `2` to `5` in the first link does have the release notes for 2015.5.0 here: http://docs.saltstack.com/en/latest/topics/releases/2015.5.0.html

@jacobhammons We should get the second link from @iggy working. I also noticed that the 2015.5.x release notes are missing from the release notes ToC: http://docs.saltstack.com/en/latest/topics/releases/

**Comment by jacobhammons** [comment]
I've fixed these links and also set up a redirector from 2015.2.0.html to 2015.5.0.html (in case someone had a bookmark). Did that fix the issue @iggy ?

**Comment by iggy** [comment]
It was probably pulling .2 from my browser history (I still have machines on 2015.2rcSOMETHING fwiw). Thanks for doing the forwarding rule. Fixed.
