### ISSUE TITLE
Some Questions about SaltStack

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#23831]
I have two questions one about the reactor and the other one about developing in salt.

The Reactor Question:

If the minion send an event to the master tagged by "run/foo/state/", how can I know that foo state executed correctly or there were errors ?! is there a way to follow or something ?! 

The Developing in salt Question:

If I have a feature I want to add it to salt. but this feature will need some configuration at the minion config file. so how can i add new configuration which will be availabe in `__opts__` ?

**Comment by cachedout** [comment]
Regarding the reactor, you have a couple options. You could setup the minion(s) to use a returner and examine it. Or, you could use the jobs runner to examine the result of the job, but only if you've retreived the job ID from the minion log. We could probably come up with a cleaner way to do that. Maybe others have some ideas?

Regarding the second question, you'll need to add the appropriate values to `salt/config.py`. You'll see a few data structures there that declare value types and default values. Should be pretty straightforward. :]

**Comment by techhat** [comment]
@Code-Vortex, let me expound on @cachedout's second comment. You can add any arbitrary value to either the master or minion config, and it will show up in `__opts__` for that service. However, if you want to set defaults, that's when you need to edit `salt/config.py`.

**Comment by Code-Vortex** [comment]
@cachedout I will try to checkout how can i handle the reactor through returners and also will try to check the result of the job.

@techat so after adding the default settings that i am looking to have inside ```salt/config.py``` will it available immediately to reuse it inside a module because i will use the opts when modifying the ```state module``` ? , because if i could make it work as expected i wish it could be shipped with saltstack during setup so it could be available for everyone.  its a feature about having some access control list if you would like to restrict a state from running on that minion , so if you are going to use ```salt '*' state.sls foobar``` , the access control list (if you activated it from the minion config ) will handle your request to check if minion X allowed to accept the foobar state or not and also it will have a file where you add the state that you want minion X to reject it

**Comment by tbaker57** [comment]
@Code-Vortex I think your idea of access control checks on state modules is a great one. The thing that keeps me (and probably others) up at night is how to prevent a compromised master (or compromised git/svn server if running masterless) from compromising all connected minions which would be devastating to say the least. The ability to disable execution modules on the minion (http://docs.saltstack.com/en/latest/ref/configuration/minion.html#disable-modules) goes part of the way[*]. And controlling which states can be executed on a minion also helps. However, even if you control which states get executed, an attacker on a compromised master (or git server in masterless mode) can obviously modify 'permitted' state files to include whatever nefarious actions they desire (add users, open up ports, etc etc). To prevent this, you really need the concept of 'signed' state files. The signing obviously has to take place outside of the master, and the verification public key also has to be distributed to the minions without the help of the master (otherwise an attacker would just alter the pub key used for verification to suite them). 
Perhaps a custom renderer could be used to do this - this would be different from the existing GPG renderer (which does encryption only, and also performs its operations on the master). Assuming one was using clear-signed GPG signatures, the renderer would just verify the signature, strip the signature off the state file and then pass the state file onto the state compiler. Pub key verifications are much less computationally expensive than priv key signing operations, so this shouldn't be a big performance overhead (additionally the 'verified' state files will stay in the minions cache, so verification would be an infrequent event).

cheers,
Tim

[*] There is a remark in the docs about not being able to disable the 'sys' module  ( AFAIK, there is no salt 'sys' module - perhaps 'sysmod' or 'system' was intended ?) and I don't know what it (or an attacker abusing it) can do on a minion.

**Comment by Code-Vortex** [comment]
@tbaker57 As start I can go with just restrict list, the main reason for me currently that some minions have custom configuration and i need to avoid running a state that could change these configuration. (and it will help me in my case so it could help others too who face the same case that why i wish to contribute with it in Salt) and the more I learn the more I will try to improve the module, also may others in Salt Community helps in improving these module if they like it. To be honest currently I don't know how should I make the verification thing, so I will try to achieve the first target through a file where you can add the disabled SLS files., Is that will be ok with Salt standard to start this feature without the existence of verification you mentioned ?

**Comment by tbaker57** [comment]
@Code-Vortex. I think the idea of a restriction list on the minion for states (like there currently is for modules) is still a good one even without any integrity checks on state files. But it might be good if one of the SaltStack people chimed in here - they might have such a feature already on their radar and might be able to give some pointers as to what they'd like to see implemented in order to benefit the widest audience.

cheers,
Tim

**Comment by iamfil** [comment]
@cachedout is there any documentation/samples on doing "You could setup the minion(s) to use a returner and examine it." ? Not to hijack this issue, but i have a similar issue where i'd like my minion to know if the master processed an event fired from the minion.

**Comment by cachedout** [comment]
@iamfil I am not aware of any documention on that. It would be a build-your-own approach as it sits right now.
