### ISSUE TITLE
deprecate/remove start_action from salt-cloud, document using reactor instead

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#23873]
`start_action` is an experimental feature that has never worked and is superseded by better functionality in reactor.

**Comment by aphor** [comment]
Maybe we should consider even more ambitious changes to leverage reactor?

#25555
https://github.com/saltstack/salt/issues/25555#issuecomment-153553006

**Comment by jfindlay** [comment]
@aphor, indeed.  There are some ideas to be explored here.  I created this issue at the request of @techhat.

**Comment by cmclaughlin** [comment]
I think start_action is a really nice feature and don't want to see it go.  I use it to apply my custom boto state before the reactor runs highstate on new instances... that way I can remove the old rpm version of boto and pip install a much newer version.

If I remember correctly, this was the code that wasn't working until I started installing boto with start_action:

	include:
	  - boto
	  - hostname

	{% from "aws/elb_register_instance_map.jinja" import conf with context %}
	{% set elb = salt['pillar.get']('elb') %}
	{% set instance_id = salt['boto_ec2.get_id'](
	  name=grains['id'], region=conf.region, keyid=conf.keyid, key=conf.key) %}

I thought including my boto state would have made sure it was installed before the rest of this state is applied... but I think the jinja template is rendered first... so boto_ec2.get_id failed before my boto state was included.

Maybe there's other ways to fix problems like this, but start_action worked very well for me. I actually found this issue because I was thinking of using it for something else, so I was looking for the docs on the feature :)

**Comment by cmclaughlin** [comment]
Reading the docs a bit more, I see a suggestion to use startup_states instead.  My problem with that is I wouldn't want to reinstall boto every time the minion restarts.

I don't think I could solve this problem with the reactor either... I'm probably just lucky that start_action runs before my highstate reactor.  I assume if I tried to apply my boto state via the reactor, I couldn't guarantee it would run before the highstate reactor.
