### ISSUE TITLE
Enable calls to state modules from state modules or make it possible to not refresh modules from state.single

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#23927]
We have a pattern where some states will also manage other states (boto_asg manages boto_lc, boto_elb manages boto_route53, pagerduty can manage boto_sns). We do this for syntactic sugar. For instance, boto_asg will create and destroy launch configurations automatically and associate them with the autoscale group.

Right now we're calling state.single, which actually works fine, except that it refreshes the modules every time it's called, which makes things incredibly slow.

**Comment by ryan-lane** [comment]
We also have a custom state that just manages the contents of a set of files, but we're making a nice interface for it (and also adding a mod_watch to be able to trigger some actions on listens). We're calling file.managed for each a bunch of times, so it's really adding up on the module loading time. We're probably going to go out to the file.manage function in the execution module, but it's more complex.

**Comment by garethgreenaway** [comment]
Maybe something as simple as a flag to state.single that tells it not to refresh the modules?

**Comment by jfindlay** [comment]
I am not an expert, but I looked through the state execution module, and the module reload penalty happens because `state.single` needs to instantiate a state object in order to run the single state function, so it is likely not possible to setup a general purpose state compiler without going through all of the module and data (re)loading.  I could be wrong, but for me to learn differently would take me more time than I have right now. :-)

**Comment by jacksontj** [comment]
This actually kinda fits into something I was thinking of making. One of the problems I'm running into is with pkg installs taking forever if they are stripped across many high state objects-- because (in RHEL land) it has to run repoquery a million times. I was thinking of adding some per-state-execution caching (and in there we could potentially cache modules etc. for your use case as well.). Haven't had a lot of time to think through it or dig through the core yet on that one, just a thought ;)

I definitely see the use for what you are doing (states managing states), especially in the world of containers!

**Comment by basepi** [comment]
Refs https://github.com/saltstack/salt/issues/21214

**Comment by aneeshusa** [comment]
This was fixed by the addition of `__states__` in #26747 and can be closed.
