### ISSUE TITLE
Salt caller raises CommandExecutionError when grains loader can't find a command

### ISSUE THREAD

**Issue by thenewwazoo** [saltstack/salt#24085]
This may be related to/a duplicate of #23342 

When making a call (`salt.client.Caller()`) if the grains loader (specifically, `grains.update(_virtual(grains))`) attempts to execute a command (e.g. `dmidecode`), and the command cannot be found, a `salt.exceptions.CommandExecutionError` is raised all the way up to the caller. I believe this to be a bug because other entry points to salt treat this as a warning.

In my specific case, the execution environment (cron) does not have a `$PATH` to `/usr/sbin/dmidecode`:
```
Traceback (most recent call last):
  File "/usr/local/bin/dynamic_cfg.py", line 205, in <module>
    add_salt_hostgroups(disp_hosts)
  File "/usr/local/bin/dynamic_cfg.py", line 152, in add_salt_hostgroups
    caller = salt.client.Caller()
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 1617, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 298, in __init__
    opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 508, in grains
    ret = fun()
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 1240, in os_data
    grains.update(_virtual(grains))
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 500, in _virtual
    ret = __salt__['cmd.run_all'](cmd)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 555, in _run_all_quiet
    saltenv=saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 391, in _run
    .format(cmd, kwargs, exc)
salt.exceptions.CommandExecutionError: Unable to run command ['dmidecode'] with the context {'with_communicate': True, 'shell': False, 'env': {'LANG': 'en_US.UTF-8', 'LC_ALL': 'C', 'SHELL': '/bin/sh', 'PWD': '/root', 'LOGNAME': 'root', 'HOME': '/root', 'PATH': '/usr/bin:/bin'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -1, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
```

The relevant code is:
```python
caller = salt.client.Caller()
known_salt_minions = caller.sminion.functions['mine.get']('*', 'test.ping')
```

This can also be duplicated at the command line:
```bash
$ sudo PATH=/bin:/usr/bin salt-call mine.get '*' test.ping
```

Which gives a similar stack trace.

This is on:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.5 (wheezy)
Release:	7.5
Codename:	wheezy
$ salt-call --version
salt-call 2015.5.0 (Lithium)
```

**Comment by jfindlay** [comment]
@thenewwazoo, thanks for the report.

**Comment by DmitryKuzmenko** [comment]
This behavior was introduced as a fix for #7990. But it's incorrect to lookup outside the environment PATH inside salt logic. If somebody needs to have additional directories in PATH or hide something he have to update the environment before run salt.

**Comment by thenewwazoo** [comment]
I don't see `_which()` involved in the call path to `cmdmod.run()`, which is the function that's throwing the `CommandExecutionError` when it (presumably) gets an `OSError` from `subprocess` (which is called by `utils.timed_subprocess.TimedProc`'s constructor). My approach would have been to catch the exception in the grains loader level and remove whatever exception handling lives elsewhere; how does this fix work? (I haven't tested it, fwiw)

**Comment by DmitryKuzmenko** [comment]
@thenewwazoo the issue is in the wrong decision that we have 'dmidecode' executable available in the system. It happens before cmdmod._run() is called in grains.core._virtual():493. If salt.utils.which() returns None cmd.run will not be called. In your case utils.which() returns '/sbin/dmidecode' so we decide it's in the system and try to run 'sh -c dmidecode' but sh doesn't see it in the $PATH. It's because there is extra logic in utils.which() that additionally always looks for a binary in /bin, /sbin, /usr/bin, /usr/sbin and /usr/local/bin. This is incorrect, which must not lookup outside the PATH specified by environment. That is what I fixed. Now in your case salt just will think that your system have no dmidecode and will work without it.
If you want to unhide dmidecode from salt you have to update your environment, how it could be done in crontab is described in my last comment in #7990
