### ISSUE TITLE
-names option for file.absent should be documented

### ISSUE THREAD

**Issue by aneeshusa** [saltstack/salt#24150]
This is a very useful option, but it's not listed in the documentation; I was lucky enough to search for it amongst the issues and find out that it had already been implemented.

**Comment by rallytime** [comment]
Oh, yes we should definitely get this documented. Thanks @aneeshusa!

**Comment by cachedout** [comment]
Hi @aneeshusa and thanks for the suggestion.

The reason for this is that `names` isn't specific to this function and is actually a feature of the state compiler itself. It is documented here: http://docs.saltstack.com/en/latest/ref/states/highstate.html#names-declaration

As such, I'm going to close this since it would be redundent to document it every function that it is supported in (which would be all of them).
