### ISSUE TITLE
Add examples and tests to the wheel key module functions

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#24200]
The functions in the wheel module all need examples added to the docs as well as tests.

Should the `key.delete_dict` function delete rejected/denied keys directly or is it missing the CLI equivalent of the `--include-all` flag as a kwarg?

[Relevant salt-users discussion.](https://groups.google.com/d/topic/salt-users/qe7FY5HexM0/discussion).

**Comment by rallytime** [comment]
@whiteinge Docs were added just the other day [here](https://github.com/saltstack/salt/pull/35824)
and tests were added [here](https://github.com/saltstack/salt/blob/develop/tests/integration/wheel/key.py), [here](https://github.com/saltstack/salt/blob/develop/tests/integration/wheel/client.py), and [here](https://github.com/saltstack/salt/pull/33414).

The `key.delete_dict` function only takes a `match` arg, which needs to be a dictionary of the keys to delete. I could be wrong, but I don't see where the `--include-all` flag is used in `salt.key.delete_key`, which is the function the wheel key module calls out to.

The `reject` function has `include_accepted=False` and `include_denied=False` as optional kwargs, but not `delete` or `delete_dict`. I am not sure if this is intentional or not, but the `salt.key.delete_key` doesn't have an option to pass something like that along. There is a separate function in `salt.key.py` named `delete_den` that deletes _all_ denied keys. But that doesn't take a match or any args.

Perhaps the solution to the problem in the salt-users discussion is to add a flag to `wheel.key.delete` and `wheel.key.delete_dict` like `delete_den=False`, and when that is set to `True` it also calls the `salt.key.delete_den` function. Was it only the denied keys we're concerned with here?

**Comment by whiteinge** [comment]
Awesome! Very awesome.

Re-reading that thread, if `delete` or `delete_dict` can nuke keys that have been denied or rejected I think that fulfils the use-case. I just tested both on 2016.3 and it can. This is good to close.

Thank you!
