### ISSUE TITLE
Add minion kwarg to state.show_highstate

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#24289]
It would be nice if this function could also show *all* states applied to a given minion instead of just the current one. One could use `salt 'minion'  state.show_highstate` but this requires that the minion is actually alive. 

I'd like to be able to query from the master which states will be applied to a minion, without having to ask the minion. Since the master has access to the states and topfiles it should be able to come up with that without having to ask the minion (which then asks the master again which seems very suboptimal)

**Comment by basepi** [comment]
> It would be nice if this function could also show all states applied to a given minion instead of just the current one.

I don't know what you mean by this. `show_hightstate` will show all the states applied to a minion in a highstate.

> I'd like to be able to query from the master which states will be applied to a minion, without having to ask the minion. Since the master has access to the states and topfiles it should be able to come up with that without having to ask the minion (which then asks the master again which seems very suboptimal)

We could potentially do this master side, but it would be in the form of a runner. Execution modules don't run master-side, so we won't be able to use the `salt` command, but rather `salt-run`.

However, we will not be able to do this for minions which are not reachable. Because jinja templating can run execution modules, the minion must be reachable so we can run these modules. Salt-SSH has master-side state compiling, but it still creates new SSH sessions to run execution module calls in the template phase.

With that fact in mind, I'm still loathe to approve this feature. It would be a lot of work, with very little return and a lot of master-side load that's unnecessary (since the minion must be available anyway).

Thoughts?

**Comment by syphernl** [comment]
I have been attempting to implement this via a runner. It seems to work(!) except that it is terribly slow even though its all local communication (Reported in #24326). Assuming what I did is "the way" It shouldn't be too hard to implement this :-)

I understand that this wouldn't work for the states that use execution modules but in our environment we're not using any.

**Comment by basepi** [comment]
The problem at that point is that the feature doesn't support all states. I'm definitely not a fan of functionality that only works with some states but not all. Hopefully if we can resolve your reported #24326 then you'll be golden.

**Comment by basepi** [comment]
I'm going to close this one, for the reasons stated above. We still need to resolve #24326 which should make your workaround viable.
