### ISSUE TITLE
Allow salt-stack's ext_pillar to be evaluated once for all minions in a selected set

### ISSUE THREAD

**Issue by oakad** [saltstack/salt#24355]
When doing state modifications and such, ext_pillar is evaluated for each minion. In many cases, though, the dynamic pillar data will be identical for all selected minions, while the number of selected minions can be pretty large. This results in "ext_pillar" functions being evaluated multiple times in rapid succession, which can be highly undesirable for performance or other resource limits.

It would be great, if salt either:
1. supported an approach to evaluate the ext_pillar function only once per salt request invocation
2. or, at least, passed an additional argument to ext_pillar which could be used to cache pillar specific data for the current salt invocation

**Comment by basepi** [comment]
We've run into this issue with git_pillar external pillar as well. Basically it will run a fetch for every minion, rather than just fetching once, or on a schedule. I could have sworn there was an open issue for that, but I'm having a bear of a time finding it. Anyway, this is definitely something we want to support, thanks for the request!

**Comment by cachedout** [comment]
@dmurphy18 Could you please explain why the Boron label has been applied to this issue?
