### ISSUE TITLE
Could not deserialize msgpack message - unpack(b) received extra data

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#24351]
I get the following error on FreeBSD 10.1 when trying to use ``salt-run jobs.list_jobs``:

```
emma ~ # salt-run jobs.list_jobs
[CRITICAL] Could not deserialize msgpack message: ��fun_args��jid�20150602172346608736�returnçretcode�successãcmd�_return�_stamp�2015-06-02T23:23:46.770520�fun�test.ping�id�amyaThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/runners/jobs.py", line 211, in list_jobs
    ret = mminion.returners['{0}.get_jids'.format(returner)]()
  File "/usr/local/lib/python2.7/site-packages/salt/returners/local_cache.py", line 282, in get_jids
    for jid, job, _, _ in _walk_through(_job_dir()):
  File "/usr/local/lib/python2.7/site-packages/salt/returners/local_cache.py", line 67, in _walk_through
    job = serial.load(salt.utils.fopen(load_path, 'rb'))
  File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
```

```
emma ~ # salt --versions-report
           Salt: 2015.5.1
         Python: 2.7.9 (default, Apr  8 2015, 07:01:13)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.2
         PyYAML: 3.11
          ioflo: 1.2.4
          PyZMQ: 14.5.0
           RAET: 0.6.3
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by afletch** [comment]
I'm having the exact same issue. CentOS 7.
```
 salt --versions-report
           Salt: 2015.5.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

**Comment by mquirion77** [comment]
I had the issue too. 

I was able to get rid of the problematic jobs by deleting them using the JID like this : 

```
sudo grep -ilrn "20150521134825823123" . | sudo xargs rm
```

**Comment by afletch** [comment]
Yep, I've just taken a similar approach and renamed the job files.

**Comment by cedwards** [comment]
After upgrading to 2015.5.2 this issue has disappeared. I'm going to close the issue. Please re-open if anyone else continues to see the same problem.

**Comment by aaltemara** [comment]
I am seeing the same problem, and am on 2015.5.2.

[CRITICAL] Could not deserialize msgpack message: ��fun_args��20150719132221877305�jid�20150719132309922568�return��retcode�successãcmd�_return�_stamp�2015-07-19T17:23:10.128272�fun�saltutil.find_job�id�sanitizedminion1.domain.tld)�pid�=Σret��user�sudo_sanitizeduser�arg��yum -y update --security�fun�cmd.run�retcode�successãcmd�_return�_stamp�2015-07-19T17:23:10.129310�fun�saltutil.find_job�id�sanitizedminion2.domain.tldThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/runners/jobs.py", line 211, in list_jobs
    ret = mminion.returners['{0}.get_jids'.format(returner)]()
  File "/usr/lib/python2.6/site-packages/salt/returners/local_cache.py", line 282, in get_jids
    for jid, job, _, _ in _walk_through(_job_dir()):
  File "/usr/lib/python2.6/site-packages/salt/returners/local_cache.py", line 67, in _walk_through
    job = serial.load(salt.utils.fopen(load_path, 'rb'))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.

 salt --versions-report
           Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

**Comment by wiloyee** [comment]
This Problem has a  blocking criteria. 
a big advantage for salt is that you can reconstruct all salt commands ...
with this bug it's not longer possible

[CRITICAL] Could not deserialize msgpack message: ��fun_args��20151002154148704505�jid�20151002170016944880�return��retcode�successãcmd�_return�_stamp�2015-10-02T15:00:17.457835�fun�saltutil.find_job�id�izi-tux-15.ribolution.localsuccessãcmd�_return�_stamp�2015-10-02T15:00:17.458112�fun�saltutil.find_job�id�izi-tux-08.ribolution.localThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) recieved extra data.

                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: 3.1.1
 Debian source package: 2015.5.3+ds-1trusty1

**Comment by Karunamon** [comment]
I can confirm this is happening on 2015.5.3 as well. It might be bogus data already in the job cache, but if that's the case, I'm not sure how to delete it.

```
                Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```
