### ISSUE TITLE
lack of documentation around Denied Keys

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#24510]
http://docs.saltstack.com/en/latest/ref/cli/salt-key.html

Search for "denied". Nothing found.

Then do something stupid, like say register two hosts with the same id, and you'll see "Denied Keys"

**Comment by rallytime** [comment]
@ahammond Yes - we should get this documented for sure. 

@felskrone If you're around, this was your change I believe. It'd be great if you could add some docs about this change if you have a moment. If not, we can get it added.

**Comment by ahammond** [comment]
It'd be cool to have a way to delete only one of the two keys, too, but not that valuable, I guess.

**Comment by felskrone** [comment]
Im not sure where to add it. The salt-key documentation should mention denied keys, but should not explain them in detail.

What page should i add it to?

Denied keys occur, if a minion tries to login with a key that differs from the one the master already has for that minion. It was added to be able to tell, which minions were denied from logging in.

salt-key will not be able to tell, which of the two the valuable one is. That depends on your infrastructure and your key-authority. If the key was denied and placed in 'minions_denied', it might be, because someone else used the wrong minion id on his system.  Or a someone forgot to delete the accepted key in 'minions' before booting the newly installed minion. 

Either way, salt-key would not be able to tell, which of the keys the valuable one is.

**Comment by rallytime** [comment]
I was just looking around to see if we had ANY documentation on what the various salt-key categories mean. I know "Accepted" and "Rejected" seem obvious, but "Denied" is less obvious. It would probably be good to have some more documentation about this. I think the best place to put this would probably be at the top of http://docs.saltstack.com/en/latest/ref/cli/salt-key.html. 

If some docs are added about salt-key to that page, the added benefit is that information will be included in the man pages as well.

**Comment by felskrone** [comment]
I added the documentation. But building the html-documentation to check the layout fails (not due to my changes) with:

```bash
salt01-vagrant:/vagrant/source/salt/doc (denied_keys_doc) $ make html
No need to update translations. Skipping...
sphinx-build -b html -d _build/doctrees    . _build/html
Running Sphinx v1.1.3
/usr/lib/python2.7/dist-packages/pygments/plugin.py:39: UserWarning: Module M2Crypto was already imported from /dev/null, but /usr/lib/python2.7/dist-packages is being added to sys.path
  import pkg_resources
/usr/lib/python2.7/dist-packages/pygments/plugin.py:39: UserWarning: Module MySQLdb was already imported from /dev/null, but /usr/lib/python2.7/dist-packages is being added to sys.path
  import pkg_resources

Extension error:
Unknown event name: env-before-read-docs
```

This is a wheezy-vagrant vm with sphinx 1.1.3, do i need a newer version for the doc to build properly?

**Comment by rallytime** [comment]
I am not sure which version you need. @jacobhammons or @whiteinge - can you point @felskrone in the right direction?

**Comment by jacobhammons** [comment]
@felskrone You need sphinx 1.3 or later, you should be getting a warning though (we are using the `needs_sphinx=1.3` configuration setting). Do you mind updating your sphinx version to see if it builds correctly? Thanks!

**Comment by jacobhammons** [comment]
@felskrone sorry to bug, but did you get the build working OK? If not you can go ahead and submit a pull request agains 2015.5 and I'll take a look at it. Thanks!

**Comment by jacobhammons** [comment]
I can also add this info based on your great explanation above, just didn't want to step on your pull request :)
