### ISSUE TITLE
State run errors on file.managed when test=True

### ISSUE THREAD

**Issue by romlok** [saltstack/salt#24564]
When running one of my states from the command line with test=True, I receive an error:

```
[INFO    ] Executing state file.managed for /foo/bar.conf
[ERROR   ] Unable to cache file 'salt://foo/bar/conf.jinja' from saltenv 'base'.
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1406, in managed
    **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3129, in check_managed_changes
    __clean_tmp(sfn)
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 84, in __clean_tmp
    if sfn.startswith(tempfile.gettempdir()):
AttributeError: 'bool' object has no attribute 'startswith'
```

However, running the state without test=True produced the expected result (in my particular case, an error that the source file didn't exist).

---

```
root@potash:~# salt-call --versions-report
                  Salt: 2015.5.0
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2015.5.0+ds-1~bpo70+1
```

**Comment by cachedout** [comment]
I assume this is a `file.managed` state? Can this be reproduced or did it only happen once and not again?

**Comment by raumkraut** [comment]
Yes, this is perfectly reproducible for me:

test.sls:
```
/tmp/foo.bar:
  file.managed:
    - template: jinja
    - source: salt://foo.bar.jinja
```
```
# salt-call state.apply test test=true
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test.sls'
[INFO    ] Running state [/tmp/foo.bar] at time 07:26:48.519321
[INFO    ] Executing state file.managed for /tmp/foo.bar
[ERROR   ] Unable to cache file 'salt://foo.bar.jinja' from saltenv 'base'.
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1406, in managed
    **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3129, in check_managed_changes
    __clean_tmp(sfn)
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 84, in __clean_tmp
    if sfn.startswith(tempfile.gettempdir()):
AttributeError: 'bool' object has no attribute 'startswith'

[INFO    ] Completed state [/tmp/foo.bar] at time 07:26:48.524602
```
After some further experimentation, I only see this occur when 1) the source file does not exist, and 2) the source file is a (jinja) template.

**Comment by tbaker57** [comment]
I think the problem lies in get_managed() in https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L3158
```
    if template and source:
        sfn = __salt__['cp.cache_file'](source, saltenv)
        # exists doesn't play nice with sfn as bool
        # but if cache failed, sfn == False
        if not sfn or not os.path.exists(sfn):
            return sfn, {}, 'Source file {0!r} not found'.format(source)
```
If something goes wrong calling cp.cache_file, sfn=False, (a bool not a string) which is then returned to check_managed(), and so in https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L3457
```
        if comments:
            __clean_tmp(sfn)
```
 __clean_tmp bombs out after being passed a bool. Would the fix be to change this to
```
        if comments and isinstance(sfn, str):
            __clean_tmp(sfn)
```
? I'm happy to submit a pull request to this effect if you agree that's the best fix.

As to why the call to cp.cache_file is failing for @raumkraut in the first place, it's a mystery - maybe a corrupt cache ?

cheers,
Tim

**Comment by raumkraut** [comment]
> As to why the call to cp.cache_file is failing for @raumkraut in the first place, it's a mystery - maybe a corrupt cache ?

FWIW, I just tried stopping master and minions, deleting /var/cache/salt on both master and minion, and then restarting everything. I still get the exact same result.

**Comment by tbaker57** [comment]
Yes, it's weird, especially since it works fine when 'test=false'. What are your file_roots ? Local directories on the master or a remote fs like gitfs ?
I think you really need to stick some debug statements deep in fileclient.py to figure out why the initial 'unable to cache file...' error is being thrown.

**Comment by raumkraut** [comment]
My file_roots contains just the default `/srv/salt/` for the single base environment.

> why the initial 'unable to cache file...' error is being thrown.

The "unable to cache file" message is showing up because the source file does not exist.

When this happens, it seems returning `False` is simply what `RemoteClient.get_file()` does: https://github.com/saltstack/salt/blob/develop/salt/fileclient.py#L967 (also if the destination dir is absent at ~L1041).

---

After some more poking, I found that the error only occurs during a test, because it is actually being triggered by `file.check_managed_changes`, which is being called directly by the file state when testing:
https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L1387
https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L4230

Whereas, I expect that the code which leads to `file.check_managed` is more robust, and doesn't actually call it without a valid `sfn`.

**Comment by steverweber** [comment]
+1 this is annoying.
