### ISSUE TITLE
Feedback request on changes to mysql returner

### ISSUE THREAD

**Issue by kaithar** [saltstack/salt#24603]
I'm tweaking the mysql returner to be more searchable when integrating and I need to make a change to the schema to do that.  So two questions...

Firstly should this be put in as a second mysql returner or as a non-default option to the current one?  I don't want to break anyone's tables by making this a default behaviour.

Secondly, does salt have any constraints that should influence this?  Do any of these columns need to be bigger, can any be smaller?

This is the schema I'm looking at for jid:

``` sql
CREATE TABLE `jids` (
  `jid` varchar(255) NOT NULL,
  `load` mediumtext NOT NULL,
  `tgt_type` varchar(255) DEFAULT NULL,
  `cmd` varchar(255) DEFAULT NULL,
  `tgt` varchar(255) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `fun` varchar(255) DEFAULT NULL,
  UNIQUE KEY `jid` (`jid`),
  KEY `tgt_type` (`tgt_type`), 
  KEY `cmd` (`cmd`), 
  KEY `tgt` (`tgt`), 
  KEY `user` (`user`), 
  KEY `fun` (`fun`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by cachedout** [comment]
I'm going to route this request over to @ckochenower who has been doing a lot of returner schema work lately and might have good insights.

**Comment by ckochenower** [comment]
@kaithar - The `jids` table is designed to be a DB persistence layer supporting Master/External Job Cache within Salt. `save_load` and `get_load` are part of the Master Job Cache interface. 

http://docs.saltstack.com/en/latest/ref/returners/#master-job-cache-support

`get_jids` is part of the External Job Cache interface. 

http://docs.saltstack.com/en/latest/ref/returners/#external-job-cache-support

The inputs and outputs to these entry points must not change.

Essentially, it looks like you have broken the `load` up into searchable/indexed fields. The DDL change by itself doesn't seem to break anything with the existing mysql returner (save_load, get_load, get_jids), due to the fact that they are null-able fields.

The `save_load` could be enhanced to populate the new columns and you could introduce a number of additional entry points to take advantage of the new fields w/o breaking existing Master/External Job Cache interface(s).

Another returner with a different name entirely would be a viable solution as well. It just won't be the default mysql returner.

**Comment by ckochenower** [comment]
@kaithar - As far as column sizes are concerned. varchar is space efficient and 255 is almost certainly sufficient for all of the new fields.

**Comment by ckochenower** [comment]
@cachedout - Do you agree?

**Comment by cachedout** [comment]
So long as any migration between versons of salt is handled cleanly. (i.e., we provide schema migrations), this is fine with me.

**Comment by kaithar** [comment]
@ckochenower 
> The inputs and outputs to these entry points must not change.

Nope, not interest in changing the input/output of them, though adding *optional* a search/filter keyword arg to `get_jids` might be a good thing.  I'm after making it so that I can find specific jobs without having to get a full list and iterate, which is horrible when I'm looking through many hundreds or thousands of jobs.
The change to save_load I've already done and tested.

I'm specifically aiming to have this non-default behaviour, initially at the very least, to avoid breaking existing installs.

It doesn't have save/get_load, but elasticsearch_return.py does have a good precedent for splitting out information for easier queries.

**Comment by ckochenower** [comment]
@kaithar - As long as we maintain backward compatibility and provide a sufficient migration strategy, I'm okay with your changes.
