### ISSUE TITLE
salt-ssh - non-thin execution using salt-call

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#24623]
I'd like to see a non-thin-based `salt-ssh` operation mode which utilizes an already installed `salt-call` on the Minion.

Basically a replacement for:
- `rsync -av ~/dev/salt-repos/* root@minion:/srv/salt/`
- `ssh root@minion "salt-call state.highstate"`

So `salt-ssh` would be used for:
- managing connection params through the roster
- transferring states, pillars, localmods etc. to the Minion using SSH
- executing `salt-call` on the Minion

As I have a few environments where I can't run a Master and Minion as services, but having `salt-call` present + SSH access is fine, this would provide a quite dramatic speedup compared to building the complete thin tarball each time.

**Comment by thatch45** [comment]
I originally wrote salt-ssh with this in mind, but fell out of it because of complications. So I think that this would be a great thing to add!
It would, yes, dramatically speed things up, the main issue with the thin time wise is sending it over the wire, and while we do cache the remote thin so that it does not need to be reused over and over again this would still help. This idea would also allow salt to maintain state on the remote system

**Comment by eliasp** [comment]
Should be kept open IMHO.
