### ISSUE TITLE
Raet: long time in sending event to master

### ISSUE THREAD

**Issue by victors2709** [saltstack/salt#24784]
Hi,

I have tested sending events from a salt-minion to a salt-master and I observed that ZMQ is much faster than RAET (aprox. 7 time faster).

Following salt execution module was used for testing:

send_event.py:

```
def do_something():
    # do something!
    for i in range(0,100):
      __salt__['event.send']('myco/my_custom_module/finished', {
        'finished': True,
        'message': "The something is finished!",
    })
```

Time when using ZMQ:

```
[root@sminion salt]# time salt-call send_event.do_something
local:
    None

real    0m3.290s
user    0m0.406s
sys     0m0.131s
```

Time when using RAET:

```
[root@sminion salt]# time salt-call send_event.do_something
local:
    None

real    0m20.775s
user    0m0.519s
sys     0m0.131s
```

Versions used:

```
[root@sminion ~]# salt-minion --versions
           Salt: 2015.5.2
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.3
         PyYAML: 3.10
          ioflo: 1.1.7
          PyZMQ: 14.3.1
           RAET: 0.6.1
            ZMQ: 3.2.5
           Mako: Not Installed
```

**Comment by jtand** [comment]
@victors2709 Thank you for providing this information.

**Comment by cachedout** [comment]
@DmitryKuzmenko Can you replicate these results?

**Comment by DmitryKuzmenko** [comment]
In the next sprint, OK?

**Comment by DmitryKuzmenko** [comment]
@victors2709 thank you for the report and your interest in raet.

I performed some tests. Unfortunately you are right. Raet takes about 20 secs with default configuration. After I tuned ioflo and raet options I got 2.5 seconds, but ioflo became eating CPU because of an extra cycle loops. Related config options are (default vaues are in brackets)
```
ioflo_period: 0.001 (0.1 for master, 0.01 for minion)
raet_road_bufcnt: 100 (2)
raet_lane_bufcnt: 100 (100)
```
Please don't follow this example as an instruction. Try to change the values comparing performance and CPU loading in your actual cases. The most relevant option for small systems is ioflo_period. Ioflo main loop is timer ticks based and decreasing of this value should help. Road and lane bufcnt could help when you have large cound of minions with high traffic between minions and master.

**Some words about the problem itself.**

Actually raet should work much better on a huge count of nodes. This is what it designed for. So it's not worth to compare it to ZMQ or TCP transports in 1 to 1 configuration. It will be slower by design.

Also raet protocol in Salt wasn't well tested from the performance perspective and at this moment raet transport has some bugs as I've seen during this research.

** Possible roadmap. **

First we should determine all the scope of work around raet transport, prioritize and implement(fix) it. Then we should work on performance testing and developing related recommendations for end-users.
