### ISSUE TITLE
Bring git_pillar to feature parity with gitfs

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#24876]
Add pygit2/dulwich support, etc.

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/25595 has been opened to satisfy this issue. Unfortunately, due to dulwich's lack of a function to execute a git checkout, I was not able to add dulwich support. But, pygit2 support is there now, including all the same authenticated repo support that gitfs has enjoyed since 2014.7.0.

**Comment by TronPaul** [comment]
Trying to use pygit2 with ext_pillar, but it seems this check is still in `salt.pillar.git_pillar.__virtual__`
```
if not HAS_GITPYTHON:
                log.error(
                    'Git-based ext_pillar is enabled in configuration but '
                    'could not be loaded, is GitPython installed?'
                )
                return False
```

@terminalmage I know you've been working on this and wasn't sure if you had finished adding pygit2 to ext_pillar. If you have I can make an issue and PR for this bit, otherwise I'd love to help you finish it up if you have things that need doing that could be started.

**Comment by terminalmage** [comment]
@TronPaul You'd only see that if you hadn't updated your ext_pillar configuration. See [here](http://docs.saltstack.com/en/develop/ref/pillar/all/salt.pillar.git_pillar.html#configuring-git-pillar-for-salt-releases-before-2015-8-0).

**Comment by terminalmage** [comment]
Sorry, [this](http://docs.saltstack.com/en/develop/ref/pillar/all/salt.pillar.git_pillar.html#configuring-git-pillar-for-salt-releases-2015-8-0-and-later) is the actual link I wanted to share (the section below the one to which I linked in my previous comment).
