### ISSUE TITLE
-T, --make-token flag does NOT work- LDAP Groups

### ISSUE THREAD

**Issue by bocig** [saltstack/salt#24910]
The salt "-T (--make-token)" token flag fails to work with the "external_auth" enabled. This seems to only happen when specifying the LDAP group.  For example:

external_auth:
  ldap:
    mygroup%:
      - '*':
	- .*

On another note, it would be great to have the CLI pick up the user directly from the shell, thus having to avoid specifying --username. Thanks!

**Comment by ssgward** [comment]
Thanks bocig. 

What version of salt are you using? ``salt --versions-report``

**Comment by bocig** [comment]
Salt: 2014.7.6
Python: 2.6.6 (r266:84292, Jul 10 2013, 22:48:45)
Jinja2: 2.7.3
M2Crypto: 0.22
msgpack-python: 0.4.6
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: 1.2.4
PyZMQ: 14.6.0
RAET: Not Installed
ZMQ: 4.0.5
Mako: 1.0.1

**Comment by ssgward** [comment]
@jacobhammons - please document for Beryillium

**Comment by DmitryKuzmenko** [comment]
There was a fix for token authentication: if salt command is issued by the user owning salt process it uses master key instead of the token. But the fix looks incompleted because further logic checks: if there is no 'token' being passed to master then it's needed to ask the creds again.

My change: don't ask the creds in both cases: either if there's 'token' or 'key' set.

@bocig could you please take a look or best apply the fix and try on your environment because your description is not too detail and I'm not sure I've fixed your issue.

I'll look tomorrow what we can do regarding "--username" arg.

**Comment by DmitryKuzmenko** [comment]
> it would be great to have the CLI pick up the user directly from the shell, thus having to avoid specifying --username

There are 2 cases how you can pass username to salt for eauth.
1. as a cmdline arg ```--username=homer```.
2. interactively from keyboard (if username arg is missing).

What we can do here?
1. Add another cmdline option to pick the current user name (```--current-user```)
2. Handle empty username as a request to use the current user (```--username=''``` or empty cmdline input)
3. Change nothing.
4. *More ideas?*

@cachedout @basepi what do you think?

**Comment by basepi** [comment]
(2) is the most convenient for the end user, assuming that's a sane default. I can't think of any security concerns off the top of my head with that solution, but I want to hear @cachedout's opinion.

**Comment by DmitryKuzmenko** [comment]
@cachedout if you like the 2nd solution it's here: https://github.com/saltstack/salt/pull/28441
