### ISSUE TITLE
Custom grains modules do not have access to __salt__

### ISSUE THREAD

**Issue by sergeyfd** [saltstack/salt#24997]
In Salt 2015.5.0 custom grain modules do not have access to `__salt__`.

**Comment by cachedout** [comment]
This would break a *lot* of installations. Can you provide a custom grain that demonstrates this behaviour, please?

**Comment by sergeyfd** [comment]
Here's an example, please note that this is just an example:

```python
#!/usr/bin/env python

def yourfunction():
     # initialize a grains dictionary
     grains = {}
     # Some code for logic that sets grains like
     grains['yourcustomgrain']=True
     grains['anothergrain']='somevalue'
     grains['thirdgrain']=_salt_['cmd.run'](['ls', 'tmp'])
     return grains
```

Result:
 ```
# salt-call -l debug grains.anotheritem
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: minion-1.salt
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[CRITICAL] Failed to load grains defined in grain file test.yourfunction in function <function yourfunction at 0x28b1938>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 518, in grains
    ret = fun()
  File "/var/cache/salt/minion/extmods/grains/test.py", line 9, in yourfunction
    grains['thirdgrain']=__salt__['cmd.run'](['ls', 'tmp'])
NameError: global name '__salt__' is not defined
```

**Comment by syphernl** [comment]
I'm seeing the same happening here in 2015.5.2 as well.

**Comment by sergeyfd** [comment]
It looks like it's a design feature cause even core grain modules do not have access to the base __salt__ object but define their own. This is a quote from disks.py grain:

```python
# Solve the Chicken and egg problem where grains need to run before any
# of the modules are loaded and are generally available for any usage.
import salt.modules.cmdmod

__salt__ = {
    'cmd.run': salt.modules.cmdmod._run_quiet
}
````

**Comment by cachedout** [comment]
@sergeyfd is correct. In case the chicken-and-egg problem isn't clear, the basic problem is that we need to have grains fully populated in order to have fully functional execution modules. Without this, we couldn't dynamically load modules based on the capability of a given system, nor would many functions inside execution module be able to operate. As @sergeyfd as already noted, there are cases wherein grains do call out to execution modules by importing them *directly* instead of using Salt's loader. This creates a fairly brittle tight-coupling and should be avoided IMHO, but is one way to workaround this issues. Figuring out how to support this inside the Salt loader itself, however, would be a much more involved task.

**Comment by PierreR** [comment]
I have had to deal with wicket side effects while updating `grains` with the ones from facters.

Is there a simple way for custom grains to indicate it wish not to overridden any existing grains (just appending new one) ?

My idea was to do it manually but well as it is said here I don't have access to the salt grains (I actually need the keys only).
