### ISSUE TITLE
1st or top FAQ entry on 'is-salt-open-core' needs amending from 'no' to 'yes'

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#25060]
The very first FAQ entry deals with the very important question of whether salt is fully open source or 'only' open-core. 

With the announcements on salt enterprise 4.0 and it's GUI, it is clear that the answer to this question has `now changed from 'no' to 'yes'`, salt is now 'open-core' and to get the web GUI one now needs to buy the enterprise product. 

see the current 1st topic entry on the FAQ at:

```
http://docs.saltstack.com/en/latest/faq.html#is-salt-open-core
```

**Comment by kaithar** [comment]
Interestingly, this entry has actually changed of late... it used to mention Halite which was deprecated as it wasn't entirely the best GUI in the world (sorry guys).

As open-core has been one of my biggest reasons for not touching puppet I have to say that announcement concerned me greatly, having read it carefully I'm slightly less concerned though would still appreciate some clarifications.

I'll preface the following with a disclaimer: I'm not an employee of SaltStack, I don't have access to an enterprise install (I'd never get the funding approved lol)... this is based on reading and some logical deduction.

Salt is, so far as the definition goes, still fully open source.  Salt enterprise's differentiation is pretty much entirely in the GUI and some extra documentation.
The reason that doesn't make Salt open-core is because the GUI isn't part of Salt, it's a separate product that runs on top of Salt, much like SaltPad.
Additional things that make it open source include that it doesn't have any kind of CLA that would allow SaltStack to make chunks private; the Apache 2 licence contains fully licence and patent grants, including commercial use; their current development model (I make no assertions about future models) doesn't appear to withhold any features from salt proper in order to sell the enterprise version.

Open-core is really fuzzily defined, which makes it hard to say with certainty what is and isn't matching the definition... a strict interpretation would include anything where the primary developer had paid modules as well.  It seems to be intended as an open source version of crippleware, where a company open sources the framework their product is built on but charges for the modules that make it actually useful.
A good example of a product that follows open-core methodology is [metasploit](https://community.rapid7.com/docs/DOC-2287) where all the really good features are in the paid versions.

As I said, I'd certainly appreciate some clarifications from the team on the differentiation and their stance on where they're drawing the line... I'm not too worried about Salt being intentionally crippled though.  Not like they're about to make improved security or audit logging a paid feature, like certain other projects I could mention.

**Comment by TheBigBear** [comment]
@kaithar interesting indeed. 

From at least version 0.17.0, and onwards, this part of the FAQ used to specifically say that the web UI was included in salt as an open sourced component. But sometime between the docs for the current stable 2015.5.2 and the develop branch the mention of Halite (and/or the web gui) has silently been dropped.

Under 2015.5.2 and before since 0.17.0 it used to say:

```
Is Salt open-core?

No. Salt is 100% committed to being open-source, including all of our APIs 
and the 'Halite' web interface which was introduced in version 0.17.0. 
It is developed under the Apache 2.0 license, allowing it to be used in 
both open and proprietary projects.
```


So is it surprising that some developers or contributers to 'salt' feel cheated, by having contributed to a project over time that 'used to promise or assure' it users in the very 1st FAQ entry that ALL of it was open source including the Web GUI (then called Halite). Only to find that the Halite web GUI has been depreceated and instead there is now a saltstack enterprise 4.0 GUI that is NOT open source. 

I as one would also appreciate clarification from the team how come they think this is an OK change to "silently" make? Hold a carot in front of open source developers to keep them loyal abnd committing and then when the product get's released simply remove the carot and re-classify the whole thing?

**Comment by kaithar** [comment]
My suspicion is that the GUI that they're shipping is completely different from Halite.  Having used that GUI, it would likely be easier to simply write from scratch.  It was pretty but it was still relatively primitive.  I think it would be fair to call it more a graphical console than anything else, though I can't actually remember what the project tab does.

In case you were curious, the code is still at https://github.com/saltstack/halite along with the note that it is deprecated.  From the screenshots you can get an idea of how limited it was.  There's also a link to an email thread with better information: https://groups.google.com/forum/#!msg/salt-users/rmMWLSaw0RY/N5PGRqDkwQgJ

**Comment by thatch45** [comment]
Thank you for raising these concerns. I understand where you are coming from. Please allow me to outline our model which hopefully will clarify things.

The Salt project is open source, not open core. The definition of open core we follow means that we hold back features and work from one branch of a project for customers and another branch of that project for open source. This is not the case, the salt project itself is completely open source and we do not hold features back from it, nor do we maintain a separate codebase of Salt with enterprise features.

The SaltStack Enterprise Console is a completely separate codebase and separate system. At SaltConf I explained our relationship with open source and proprietary code very clearly:
https://www.youtube.com/watch?v=eGPMDSJEn9c

There are many companies creating proprietary products on top of Salt that do not benefit the community or SaltStack Inc. the company. SaltStack Inc. has invested millions of dollars into the Salt project and continues to invest in it. Can we as a company not create a separate proprietary product when others are allowed to do so?
Simply because a company chooses to create ancillary products alongside an open-source project does not change the definition of the open source project itself.

Again, I understand your concerns, we consider Salt to be 100% open source, not open core, because there is no separate codebase of Salt and we will never reject pull requests for features into Salt, and we are willing to ship a GUI inside Salt if it is contributed.

So the question I pose is this, how can we, SaltStack Inc, the for profit corporation, make the community not feel cheated? Please let us know what more we can do.

**Comment by kaithar** [comment]
I, personally, consider the enterprise console a perfectly fair method of generating revenue from the project.

A particular project I referred to above holds back features that I would have expected to be in the open source version as critical security features... things like better audit logging.
Another has made authentication a paid for feature, the free version being full access for all users with the ability to make requests against it.
I won't name either, since I'm not in to bad mouthing projects, however it's a nice contrast against Salt which doesn't hold back from trying to make the best product it can and still follow good open source practices.   Making money by essentially selling products to make Salt more "suit friendly" is a good way to fund things and grow the community without detracting from the overall project.

While I'd love to hear some of the technical details of how you interfaced with Salt, to possibly improve my own front end code, I fully appreciate the need for maintaining "company secrets" like that and don't feel particularly cheated by the current status.

**Comment by nmadhok** [comment]
Totally agree with @thatch45 !
