### ISSUE TITLE
VMware salt-cloud driver should be able to bootstrap minions without doing an ssh

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#25061]
Working on adding functionality into the driver so that it doesn't use ssh to bootstrap the minion and put the desired keys/files etc. Using VMware tools instead which get's around the problem where siloed networks are present and there's no connectivity between those networks. In this case, VMware api should be used which is also faster than the traditional ssh approach

**Comment by jtand** [comment]
@nmadhok I look forward to the PR!! Thanks!

**Comment by fishhead108** [comment]
After a little research, I found that there is only way to get output from executing a process is to redirect output to a file, then copy it and read. 

So the workflow could look like: 

1) VM is booting
2) Copy bootstraper script  to VM by VM tools 
3) Executing bootstrap.sh by VM Tools 
4) Redirect bootstrap.sh output to the log (for example /tmp/salt/bootstraper.log) 
5) If exit code code 0: print('Installation successful') 
6) Else: copy bootstraper.log, parse it, print("The reason is {}".format(reason_of_fail))

If it ok, I'll implement it.
