### ISSUE TITLE
grain virtual  & docker

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#25101]
It looks that docker container is recognized as physical machine on centos7.

```
salt-call grains.item virtual virtual_subtype
local:
    ----------
    virtual:
        physical

cat /proc/1/cgroup  |grep docker
8:blkio:/system.slice/docker-3aab1d9949fe27dedee095f8e0803e745dfea7b04c37022c86bb1fb34674f75a.scope
6:freezer:/system.slice/docker-3aab1d9949fe27dedee095f8e0803e745dfea7b04c37022c86bb1fb34674f75a.scope
5:devices:/system.slice/docker-3aab1d9949fe27dedee095f8e0803e745dfea7b04c37022c86bb1fb34674f75a.scope
4:memory:/system.slice/docker-3aab1d9949fe27dedee095f8e0803e745dfea7b04c37022c86bb1fb34674f75a.scope
3:cpuacct,cpu:/system.slice/docker-3aab1d9949fe27dedee095f8e0803e745dfea7b04c37022c86bb1fb34674f75a.scope
2:cpuset:/system.slice/docker-3aab1d9949fe27dedee095f8e0803e745dfea7b04c37022c86bb1fb34674f75a.scope
1:name=systemd:/system.slice/docker-3aab1d9949fe27dedee095f8e0803e745dfea7b04c37022c86bb1fb34674f75a.scope

salt --versions-report
           Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

uname -an
Linux minion6 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jfindlay** [comment]
@msciciel, thanks for the report.

**Comment by eousphoros** [comment]
To add a little flavor to this. I ran into a potentially similar issue to this today after my virtual machine had been up for a couple of days.

The issue turned out to be due to docker not allowing access to /dev/mem (so no dmidecode) the core grain (_virtual) falls back to string matching in dmesg. While this works for some time, soon as the dmesg buffer starts to fill up, eventually the string (in this case VirtualBox) falls out of the buffer. The grain at this point reverts to the initialized value of physical. (Was initially VirtualBox).

My temporary workaround was to hard code the virtual grain under /etc/salt/grains to the value I was expecting.

**Comment by rallytime** [comment]
@msciciel does the fix from @eousphoros help alleviate this issue for you?

**Comment by rallytime** [comment]
I'm going to close this since we haven't heard back. If this remains a problem, leave a comment and we will be happy reopen. Thanks!

**Comment by msciciel** [comment]
Which release will include this fix ?

**Comment by jfindlay** [comment]
@msciciel, this went into develop.  There are some complications backporting it that @eousphoros was going to look into.

**Comment by msciciel** [comment]
I was trying to run develop branch on centos6 to test it but without success. I will try again in this week.
