### ISSUE TITLE
Generate doc module references automatically

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#25176]
Maybe during general doc compilation?

related issues/ PRs:
#25173
#24421
#21880
#20039
#21879
#19262
#25019

**Comment by bechtoldt** [comment]
ping @techhat / @jacobhammons :)

**Comment by bechtoldt** [comment]
#20489

**Comment by whiteinge** [comment]
There's two parts to this:

1. The autodoc extension requires that a static file be written to the file system that specifies where in the code to look for docstrings.
2. The autosummary extension [generates those static files](http://sphinx-doc.org/ext/autosummary.html#sphinx-autogen-generate-autodoc-stub-pages) based on a static list of modules to look for.

It is possible to bypass both those behaviors by writing Sphinx extensions (or subclassing the autodoc extension). Rather than using the default Python paths and imports we would need to make an extension that used Salt's loader instead.
