### ISSUE TITLE
pkg.refresh_db broken on windows

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#25282]
I'm not sure where the real issue lies, whether it is because of windows or fileclient generally.
```yaml
jmoney-main ~ master # salt jmoney-windows-12 test.versions_report
jmoney-windows-12:
    Salt Version:
               Salt: 2015.8.0rc1-10-g9e90603
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.6.0
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2
                ZMQ: 4.0.5
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
           pycrypto: 2.6.1
     
    System Versions:
               dist:   
            machine: AMD64
            release: 2012Server
             system: 2012Server 6.2.9200  Multiprocessor Free
```
```yaml
jmoney-main ~ master # salt jmoney-windows-12 pkg.refresh_db
jmoney-windows-12:
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1037, in _thread_return
        return_data = func(*args, **kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 375, in refresh_db
        cached_files = __salt__['cp.cache_dir'](repo, saltenv, include_pat='*.sls')
      File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 444, in cache_dir
        path, saltenv, include_empty, include_pat, exclude_pat
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 232, in cache_dir
        fn_ = self.cache_file(salt.utils.url.create(fn_), saltenv)
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 154, in cache_file
        return self.get_url(path, '', True, saltenv)
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 539, in get_url
        return self.get_file(url, dest, makedirs, saltenv)
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 1056, in get_file
        data = self.channel.send(load)
      File "C:\salt\bin\lib\site-packages\salt\utils\async.py", line 77, in wrap
        ret = self._block_future(ret)
      File "C:\salt\bin\lib\site-packages\salt\utils\async.py", line 87, in _block_future
        return future.result()
      File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 216, in result
        self._check_done()
      File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 294, in _check_done
        raise Exception("DummyFuture does not support blocking for results")
    Exception: DummyFuture does not support blocking for results
```

**Comment by twangboy** [comment]
@jfindlay @UtahDave I only see this error when salt-minion is running as a service. It works fine when running from console in debug mode.

**Comment by twangboy** [comment]
@jfindlay @UtahDave Nevermind. It had nothing to do with the log_level. It happens when the cached repo is empty. The first time it runs it pulls everything down. If you run it again it still fails. If you restart the service and run it again then it works as expected.

**Comment by twangboy** [comment]
[minion | uploaded via ZenHub](https://files.zenhub.io/55ba45d49a0bd3e52bf21cfa)
@UtahDave I've attached the entire minion log for this test.
The minion finishes booting at: 358
It starts doing the refresh_db around: 377
It starts pulling down .sls files around: 381
Thunderbird is the last one it does: 1026
Then it throws the exception: 1033
The service is stopped: 1069
The service is started: 1070
The minion is up: 1430
It starts doing the refresh_db around: 1430
It starts pulling down .sls files around: 1453
The first files are skipped because they're already downloaded. This continues on through Thunderbird at line: 1840
Then it downloads the rest of the files ending with xampp at: 2010
Then it sends the .sls files through the renderer and creates the winrepo.p starting at: 2015
Finally ends with xampp on line: 5620
Then it dumps some wierd windows thing that should probably be removed at line: 5624
And returns the results at line: 5632
The salt-minion is stopped: 5635
eof

**Comment by twangboy** [comment]
@cachedout Do you know what's going on here? Is it something to do with Tornado? We're running Tornado 4.2.1.

**Comment by alxbse** [comment]
I think this isssue is related to #25836, after manually applying that commit to 2015.8.0rc2 windows minion pkg.refresh_db and pkg.install works like intended for me.

**Comment by jfindlay** [comment]
Thanks, @alxbse.  If I encounter this issue again, I'll reopen.
