### ISSUE TITLE
Ability to traverse within relative includes in state files

### ISSUE THREAD

**Issue by davidjb** [saltstack/salt#25477]
I've got a situation where I have this structure of states:

```
├── pi/
    ├── camera.sls
    ├── common/
        ├── ntp.sls
        ├── reboot.sls
        ├── rtc/
            ├── ds3231.sls
            └── init.sls
```
I need to include ``pi.common.ntp`` inside of the ``pi/common/rtc/ds3231.sls`` and want to use relative includes.  Because this state is a sibling of the folder where ``ds3231.sls`` resides, the current relative include mechanism doesn't allow something like this inside ``pi.common.rtc.ds3231``:

```
include:
  - ..ntp
  - ..reboot
```
Whilst absolute includes work instead to solve this issue, this relies on the states being aware of the global structure.

Being able to move to a parent (eg ``..`` or ``...`` etc) would suffice in solving this issue; being able to arbitrarily traverse at any point in the ``include`` is overkill.  In absence of any other suggestions, the way [Python](https://www.python.org/dev/peps/pep-0328/#guido-s-decision) handles imports would fit the bill & fits with the current relative include process. 

For note, there's #5035, which handled relative imports, but only adjacent to or beneath the state file doing the import.

Thoughts?

**Comment by basepi** [comment]
Yeah, I think this is something that just has not been implemented. We explicitly disable accessing the parent directory in `salt://` paths for security reasons (a minion could otherwise escape /srv/salt on the master). I don't immediately recognize any security implications that would come from implementing this, since it's all master side, so a compromised minion couldn't use this to get out of the file_roots.

That said, it could still be an issue because the master runs as root. I could see a situation where someone could include a file outside of file_roots that they didn't have read access to (but they have write access to /srv/salt). The state will fail to render, but the logs would expose that included file in the error. If this were implemented, we would need to carefully make sure that the included paths didn't get outside of the file_roots. It's a hard problem to solve correctly, and as such will probably not be on our immediate radar. For the time being I recommend you just use absolute includes to get around this issue.

**Comment by lorengordon** [comment]
This would be useful for me as well.

@davidjb, perhaps in the interim, if you have flexibility to dictate the directory structure, another workaround would be to flatten the structure somewhat so relative includes work:

```
├── pi/
    ├── camera.sls
    ├── common/
        ├── ntp.sls
        ├── reboot.sls
        ├── rtc.sls
        ├── rtc-ds3231.sls
```

*pi.common.rtc-ds3231*:
```
include:
  - .ntp
  - .reboot
```

**Comment by davidjb** [comment]
Thanks @basepi.  File access shouldn't be an issue because the includes are only traversing within the running Salt state namespace.  The current ``include`` code for the highstate changes relative includes into absolute includes when rendering an sls, so traversing upwards is just a slight reworking of that.

In light of that thinking, I've put together a pull request for this change at #25578. 

There's a description over on the PR as to the change.  All backwards compatibility is maintained with the existing relative includes.  See what you think.

**Comment by cachedout** [comment]
The PR in #25578 is excellent work and we merged it this morning. @davidjb did an excellent job with it! As a result of his great work, I'm going to go ahead and close this. Of course, comments are still welcome if there is a need for continued discussion. Thanks!

**Comment by DanyC97** [comment]
:+1:
