### ISSUE TITLE
boto_dynamodb state should document that it doesn't do updates, or it should support updates

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#25571]
Currently the dynamodb module will create tables, but it won't update throughput or indexes. We should document this or support updates.

**Comment by ryan-lane** [comment]
We should probably do both. Document the thing that can't be updated, due to the dynamo api and add support for the things that can be updated.

**Comment by danielhochman** [comment]
If the description of the resource does not match the resource then salt should fail. If salt cannot manage the resource or parts of the resource, correct the description to match or make some changes to the resource manually so that it will match the description. Adding documentation somewhere that the description may not match the resource due to complexities of the API or an incomplete implementation of the API is very confusing. It goes against every expectation I have of a salt. If I run salt, and it passes, all resource should match my descriptions.

**Comment by jfindlay** [comment]
@ryan-lane, @danielhochman, thanks for the report.
