### ISSUE TITLE
Configuring a path outside root_dir

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#25655]
I'm using salt-ssh, which automatically sets root_dir to `/tmp/.user_hash__salt`, which is where the thin client is deployed. This is fine, except I'd love it if it was possible to define a path (specifically the log path) outside of the root dir.

The problem is that the [`salt.utils.path_join` function](https://github.com/saltstack/salt/blob/b6f42ca951a2439bce024dc0c40c6a89d8149468/salt/utils/__init__.py#L839-L861), used when [parsing paths in the config](https://github.com/saltstack/salt/blob/b6f42ca951a2439bce024dc0c40c6a89d8149468/salt/config.py#L1388-L1400), behaves differently from `os.path.join`.

```
>>> import os.path
>>> os.path.join('/foo', '/bar')
'/bar'
>>> import salt.utils
>>> salt.utils.path_join('/foo', '/bar')
'/foo/bar'
```

This means I can't just put `log_dir: /var/log/salt/minion` into the config and expect it to work. On the other hand I can't imagine this can be changed, as a lot of current code relies on this behaviour (correct me if I'm wrong).

Could there be a way to configure a path to be outside the root dir?

**Comment by basepi** [comment]
Hrm, you're absolutely right about the fact that we can't just change this behavior, as it would break existing code...

I'm not sure of the best way to fix this, but I'm thinking it might be to not use the root_dir to put salt-ssh into `/tmp/.user_hash__salt`, but rather override each of the individual paths to that directory, but only if they're not user-specified.

But this would require additional changes to the configuration, as we'd have to default a lot of these paths to `None` or something in order to be able to detect whether the path was user-specified or default.

I'll have to think about this a bit.

**Comment by anlutro** [comment]
A couple of alternatives off the top of my head, for the sake of brainstorming:

Add a `relative_dirs` boolean setting that controls whether paths are forced into relative to `root_dir`. Defaults to the current behaviour.

Paths starting with two slashes are parsed as to be outside of `root_dir`. For example: `log_dir: //var/log/salt.log`

**Comment by basepi** [comment]
I like the two slashes idea. The `relative_dirs` idea would make it so everything in salt-ssh tried to go outside of `/tmp`... (`/etc/salt`, `/var/cache/salt`, etc) so it probably isn't a good fit.
