### ISSUE TITLE
Formalize/Cleanup Salt's HA/Multi-Master 

### ISSUE THREAD

**Issue by jacksontj** [saltstack/salt#25700]
# Background

Earlier this year I spoke at saltconf about some of our operability challenges from the last year--  one of which was salt Multi-Master (http://www.slideshare.net/ThomasJackson4/salt-stack-at-web-scale-better-stronger-faster).
# Current state of the world

So, lets start with the state of the world today. You can do one of the following to scale out the master:
- shard the masters
- layer of top-level masters and syndics below that, with minions attached below.

As of 2015.5 there is a `hack` (that I mention in my presentation) to do clustered masters, but it isn't really ready for prime time, since it has a _lot_ of caveats about when it works (and more interestingly-- when it doesn't).
# Problems with the current state

The problems today fall into two main categories (1) gotchas-- that doesn't work like you think and (2) major code complexity.
## 1. Gotchas

In my presentation I mentioned that there are actually a _lot_ of options to make salt's publish system more robust with the current code-- but they all have some drawbacks that aren't necessarily obvious (primarily in their interactions with other features). For example, MultiMinion works well, all the way up until you put a syndic in the mix-- if the minion is connected to the master _and_ the syndic you can get double publishes-- which isn't necessarily a good idea.
## 2. Code complexity

In addition to the weird interactions, we've amassed specialized subclasses for each variant out there (Minion, MultiMinion, Syndic, MultiSyndic) in addition to the duplication of code some of the features exist across some or all of them (such as failover)
# Where can we go?

Although the current state is... complicated to say the least there is good news! The main reasons for the code complexity was due to the lack of a good async programming methodology within salt (which makes doing stuff like multiminions somewhat difficult-- or require threads etc.) Now that we are all tornado-d up we have a robust async programming model. In addition we are well on our way to decoupling salt from zmq which will make the job even that much better/easier.
# What can you do?

At this point I'm finalizing a couple other projects on salt (at the moment primarily the IPC work), but I need your help. I'd like to build a robust HA system for salt-- and to do so I need some input on what people expect/want/need from salt's publish system. Do you use syndics? If so, what for? The intent here is to gather requirements to hopefully come up with a solution which will work well for everyone. I'll try to maintain a list of requirements here at the bottom of this description.
### Requirements
- Single point of publish: the user shouldn't have to publish the job twice
- Single point of return: the user should be able to get the job returns on the same host that the job was published on 
- Quick minion failover: I don't think we need to guarantee that minions will be available 100% of the time, but in the event of a master disconnect it should re-connect quickly to another master.
- Shared salt-key among clustered masters: This way we can stop asking people to turn auto-accept on, or install a clustered filesystem
- Topology testing: in addition to the regular integration tests we need a more comprehensive test suite for publish topologies.
### Wants
- Removal of syndic_wait: syndic_wait is basically just a sleep configured all over creation to make syndics kinda work-- but in general its caused quite a few problems-- but the problem it is solving is quite a bit more complex. That being said I'd like to look into removing the need for it.
- Option for separate keys per master: meaning the minion can have a list of masters it can trust (based on keys) instead of requiring the masters to all have the same key.
### Outstanding questions
- What are people use syndics for? Are they solely used as a scale out mechanism (which is what we use them as)? Or are they used to connect disparate colo's masters together? Could this be replaced with a `clustering` mechanism within the master?
- How complex of master setups do people currently use? Since we more-or-less allow for arbitrary topologies the question becomes how much should we account for? For example, if you create a loop with syndics-- should the masters/syndics solve that for you?

**Comment by jacksontj** [comment]
cc @cachedout @terminalmage @jodv @thatch45 @techhat @rallytime

**Comment by DanyC97** [comment]
@jacksontj great topic

**Comment by bechtoldt** [comment]
@jacksontj I can provide anything I can do (testing, documentation) to support this project because soon I'll need a HA solution for future projects that is reliable and maintainable, though I haven't tested any yet.

> What are people use syndics for? Could this be replaced with a clustering mechanism within the master?

Separation of network zones or tenants. Think of the separation of LAN, DMZ and extranets.



@felskrone are you interested on participating on this topic?

**Comment by felskrone** [comment]
I would love to yes. I will happily provide testing of things but with very limited time (due to my family growing) i will not be able to contribute any coding (which has gotten pretty hard anyways with the code evolving rapidly and getting more and more sophisticated).

Here is how we use salt as of today:
- Total of 6 Masters 16.000 minions
- Multimaster-PKI with seperate Keys per Master, one Master-Sign-Key and NFS-shared PKI- and Cache-Dirs
- All Minions have all 6 Masters configured and failover as needed 
- Minions report periodically to their master (firing a "presence" event), a reactor writes that event into a database to keep the minion<->master mapping up to date
- a seperate API-Server offers a HTTPS-API which allows talking to individual minions. The API looks up the curent minion<->master mapping and publishes the request to the salt-api on the corresponding master 
- All events and returns are written to the mentioned database for historical data
- salt-eventsd collects events (im not sure if its still needed but we are sticking to it for now)

- we do not publish jobs for all minions, by grains-matching or anything like that. We usually run salt-calls via distributed ssh on specific server-groups
- we do not use syndics or any other Multimaster/MultiMinion-Features due to scaling and usage issues (syndic_wait, Auth-Floods on Key-Rotation) when trying them last year (i think)

My wishlist for a HA-solution is pretty much up there already:
- a Minion-Failover which does not rely on looking up an existing network-connection with netstat but comes from the underlying system (i know this cant be done with zmq, but this is a whislist! :-) )
- No limit on the number of shared-masters, i guess if you can have 3, 10 would be pretty much the same thing
- Shared-Master-Key or easier Setup of Multimaster-PKI with the latter being my preferred approach
- Minion<->Master-Mapping should be 1:1, in my opinion the MultiMinion does not solve any of the problems jacksontj mentioned above
- KISS (keep it simple and stupid), my gutt says that any MultiMaster-HA-approach that requires multiple layers like Syndics, MultiSyndics or MultiMinions is too complicated for the majority of users to implement or debug (that includes me), but thats just another gut-feeling and might be terribly wrong.

Thats my 2 cents, hope it helps.

**Comment by jodv** [comment]
Thanks for getting the discussion rolling @jacksontj.  Overall, I agree with your requirements -- which is unsurprising, since we've spoken at length about this topic many times ;)

The move towards Tornado and away from ZeroMQ is very exciting and I absolutely think that we should move towards a clustered model.  IMHO, in a large scale environment with a rapid rate of growth, users and clients shouldn't have to care about the topology and administrators should be able to scale at-will without impacting overall functionality.

My high-level vision is a scenario where minions could be affiliated with a cluster of masters and receive jobs from any of the member masters either by direct communication from any arbitrary master or some sort of router/broker.  Likewise, minions could return data to any of the member masters, which would then be available be a centralized, shared job cache.  In the event of a single master failing, minions would continue to receive jobs from and send returns to the other masters in the cluster.  There are some questions to be answered with regard to how more tiered/less flat topologies would fit into this picture, naturally.

I agree with @felskrone that the current HA functionality introduces unnecessary complexity and is not intuitive.  I would also like to see the excellent work that's been done so far to reduce unnecessary overhead continued, since our bottlenecks occur primarily with CPU resources involved in crypto when handling auth requests and processing job returns.  To that end, I would prefer to see us avoid broadcasting payloads as much as possible, which is something the current syndic/multi-master implementation does quite a bit.

I'm definitely aware of the additional complexity that would be involved in creating a more streamlined Salt-HA solution, but IMHO Salt has gained enough widespread acceptance and usage in large scale environments that it's a necessary step for Salt's continued success.

**Comment by mimianddaniel** [comment]
My requirement :) Other than whats mentioned above: 
I hope that new HA solution has no bearing on the underlying protocol, ZMQ or RAET and can be used in any topology.  Unless ZMQ or Syndic is going to be completely phased out.  

We have about 12 masters ~15k minions and have syndic in 2 tier setup, 1 MoM and syndics on the rest. 
Adding more syndic in multi-layer setup has caused grieves in our setup. Unlike @felskrone, we do run against wide range pattern matchings and so far i find that events are reaching the minions under 4secs at 180 requests per min which is not too shabby. I am all for new HA clustered solution @jacksontj  (asked him about it at the conf too) but would like to see more hard data and i can help testing this as well.

**Comment by sjmh** [comment]
We're trying to implement Salt here for around 29k minions, so the syndics and HA are definitely a hot topic for us as we design the architecture for the project.

Our requirements for this portion have been:

- No single point of failure
- Able to scale horizontally as needed
- The user shouldn't care which master he's on ( single PoR, single PoP ), even across DC's.

We intend to use syndics, as I believe they solve the scale issue.  Using syndics then means minions pointed multiple syndics in failover, with the syndics pointing at multiple top level masters.

The interesting bit has been when we discuss how/where we place the syndics and I think it's brought up another use of syndics - logical business unit separation.  With multiple business units within the company, some of them are big enough ( and have enough political strength ) to want their own set of masters.  This stems from the need to make sure that what other BU's are doing doesn't affect them - from a load perspective, but also from a 'your mistakes can't touch my servers' view. Also, a BU may have systems in both DC's that they want to manage with single salt calls, which means masters in each DC.

We also have BU's that have to reach across the entire infrastructure, such as our OS patching team, which would be issuing commands from the top level masters.

So while a simple clustered view may solve some issues ( such as scale and spof ), I think there still needs to be the idea of command&control that allows parent clusters to broadcast commands to child clusters and receive that data back.  I think it'd be a common scenario where you have different customers who need to target different portions of the infrastructure, some of which may encompass another customer's portion.

**Comment by sjmh** [comment]
To clarify, after talking with @jacksontj, our goal is to run a normal 'tiered' setup.  A master-of-masters in each DC, with a pair of syndic masters in each hosting zone, talking to all the MoM's.  The minions in each hosting segment are configured for failover/shuffle to their local syndics.

The caveat is that we then have large business units that want their own pair of masters, talking to the minions on the servers they own.  This is useful to them, from a logical permission separation and sometimes, from a load/outage perspective.  However, as we all know, organizations within a company are volatile and a business unit that's here today may be merged into another tomorrow or split into two, etc.  We can't have that affecting and realigning the core infrastructure.

Normally, we'd be able to run the minion in multi-master mode.  Just connect the minion to our masters and the BU's masters.  However, because one set of those masters are syndics, we run into double publish issues.

It'd be useful if the minion could operate in a 'hybrid' mode of multimaster and failover.  In essence, the minion would be able to connect to multiple masters concurrently as it can today, but would also have ability to failover a specific master to another if one was to fail.

In our specific use case, this would mean that a minion would be connected concurrently to both the BU's masters and one of the syndic masters.  If the syndic master were to fail, it would failover that connection to the other syndic master.  Something along the lines of:

```
master:
  - BUmaster1
  - BUmaster2
  - syndicmaster1, syndicmaster2
```

This is useful for other things in any multiple tiered setup using multiple syndics, since to avoid the double pub as of today, the minion has to be configured in failover.

**Comment by davidone** [comment]
Do you guys have any update on this (double publishing issue)?

**Comment by jacksontj** [comment]
@davidone as long as a minion is only connected to one master in the cluster you should be fine (no double publishes). There is a usecase to have "failover groups" which I hope to get around to soon-- such that you could have multiple MM-tiers as the "master"-- for different BUs etc.

**Comment by davidone** [comment]
Thanks @jacksontj. I was looking at using multi-syndic as master for a specific set of minions. Is it something that will be addressed by 'failover groups'?

**Comment by jacksontj** [comment]
@davidone First off-- sorry for the horrific delay ;) Somehow the notification got missed, and as I'm cleaning out my email today I found it :)

The "failover groups" would be to allow a minion to be attached to multiple "groups" of masters. The thought being that you may have a "global" cluster of masters-- as well as maybe a "team specific" master for some subset of minions. If you want specific minions attached to specific master that is already supported today even in failover-- the change would be to allow the minion to attach to multiples of those groups.

Hopefully that clarifies some

**Comment by davidone** [comment]
@jacksontj cool, thanks.

**Comment by Oloremo** [comment]
sad to find dead issues like this. A lot of proposed features sounds so good
