### ISSUE TITLE
Allow a minion to manage multiple running containers on the same machine

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#25729]
Docker has introduced the `docker exec` command in 1.3 which has been around for quite a while now.
If a user would like to modify a running container (in order to apply a hot fix for example) using Salt he is not required to install Salt inside the container.
Instead, the Salt minion should be aware that the container is running and instead of executing the command on the host it will use `docker exec` to execute it on the running container.

We can use the hostname or the running container's name as the minion id for that container.

**Comment by basepi** [comment]
This seems like a reasonable idea. Have you checked out our new dockerng module? It's basically a complete rewrite of our docker support and may support this (I'm unsure.)

**Comment by thedrow** [comment]
Yes, the execution module does support docker exec and other methods of changing a running container but that's not what the issue is about.
The issue is about allowing the minion to recognize multiple hosts on the same machine and assign them with different ids.
So if I call:
```
salt-call state.highstate webserver1.container1
```
All the states that are applied by the highstate would be applied using using the docker execution module, modifying the running container instead of modifying the host.

**Comment by basepi** [comment]
This would actually be a pretty cool feature! It's going to be a lot of work, however.

Basically this will function a lot like salt-ssh, and will be a similar amount of work, but with the current hype around docker, I think it's definitely something that would be awesome to have.

Once we have that functionality of running jobs via docker exec, we could add support to the orchestrate runner and similar to allow it to be used in conjunction with vanilla salt (and even salt-ssh).

Thank you for the request, @thedrow!

**Comment by cachedout** [comment]
+1 This would be awesome.

**Comment by thedrow** [comment]
Do you guys think it's worthwhile to support the same kind of feature in LXC containers? Does it exist already?

How can we introduce this kind of functionality? Which component of the system fits for this kind of extension?

**Comment by kaithar** [comment]
:+1: on this.

How about just extending salt-ssh's rosters to allow it to do smarter things?  I'm thinking something along the lines of...
* Upgrade `sudo` key to accept a username so you can switch to a different user.
* Some kind of `via` key to specify a list of jump hosts, for when you can't connect directly.
* A `docker` key to specify the container to enter after connecting via ssh.  Can also specify stuff like docker-exec driver.  I would imagine that this can also be done for other vm/container techs that support console entry like BSD jails, LXC and OpenVZ.  
* A `chroot` key to instruct it to chroot to a specific directory.

Each of these cases could be implemented easily if file transfer were done via a call to `cat > filename` rather than scp and would make salt-ssh much more powerful.  Thoughts?

**Comment by thedrow** [comment]
@kaithar I don't think we want sshd in containers.
If you do have it, I think it's already possible to manage containers using the ssh module (if it exists).

What we need to do is to use the docker client to get the list of running containers and add them to the list of minions. That way, when a minion gets a request it can redirect it to the correct container or the host.

**Comment by kaithar** [comment]
@thedrow That's not what I was suggesting... I'm suggesting making it so that salt-ssh can connect to the docker host then enter the container before executing the shim script.

**Comment by thedrow** [comment]
Oh right. I read it wrong. Sorry about that.
