### ISSUE TITLE
Need to build local Redhat 6 repository for salt and its associated dependencies.

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#25878]
Need to build local Redhat 6 repository for salt and its associated dependencies.

**Comment by clarkperkins** [comment]
From the discussion on #25502, an up-to-date python-crypto package was supposed to be included here for centos/rhel 6.  However, it does not appear to exist (https://copr-be.cloud.fedoraproject.org/results/saltstack/salt/epel-6-x86_64/).  I'm running salt v2015.8.0.

**Comment by dmurphy18** [comment]
@clarkperkins The latest dependencies for Salt 2015.8.0 for Redhat 5, 6 & 7 are freely available from http://repo.saltstack.com/yum, subdirs rhel5, rhel6 and rehl7 respectively.  This includes python-crypto version 2.6.1 and others such as python-tornado v 4.2.1.  The EPEL and Fedora repositories have not yet been updated due to time pressures of other work.  Note, EPEL 6 currently does not contain a version of python-crypto sufficient for Salt 2015.8.0.  The later version of python-crypto allows for removal and use of dependency m2crypto.

**Comment by clarkperkins** [comment]
@dmurphy18 Ok, thank you for the information.  I guess I may have commented on the wrong ticket then - my real issue is with `salt-bootstrap`.  It doesn't successfully install a minion on RHEL/centos 6 because of the bad version of python-crypto, and I figured this ticket was supposed to solve that.  I only reference that EPEL repo because that's what `salt-bootstrap` pulls in.
