### ISSUE TITLE
Targeting with the result of a module execution

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#25889]
This is a bit far fetched, but I'm going to submit it anyway. 

Would it be feasible to have some way of doing targeting based on the result of a module execution ? 

A few examples I can think of : 

```
salt --module-execute 'ps.cpu_percent > 75' test.ping
salt --module-execute 'status.loadavg > 1' test.ping
salt --module-execute 'len(status.w) != 0' system.reboot 
```

While writing this, I'm thinking maybe this could be expressed in jinja 

```
salt --jinja-module-execute '{{ salt['ps.cpu_percent']() > 75}}' test.ping
salt --jinja-module-execute '{{ salt['status.loadavg']()['15-min'] > 1' test.ping
salt --jinja-module-execute '{{ len(salt['status.w']()) != 0 }}' system.reboot 
salt --jinja-module-execute '{{ len(salt['cmd.run']('checkrestart')) }}' system.reboot 
salt --jinja-module-execute '{{ salt['pkg.version']('apache2') }} state.sls monitor.apache 
```

**Comment by jfindlay** [comment]
@arthurlogilab, I don't think so.  I was even talking with @plastikos about something very much like this a few days ago.

**Comment by cachedout** [comment]
+1

I am a big fan of this approach.

**Comment by plastikos** [comment]
I have what I call a dynamic targeter.  It can target based on a programatic expansion.  It can do the same thing as this, but is quite a bit different.  I stopped developing it because it had several problems due to it expanding hosts names rather than being target statements:

   * It grew to a huge list on our installation of 30k minions
   * It did not work well with syndics
   * It took a long time for each minion to decide if it fit the match.

I like the idea that @arthurlogilab outlines here, but the devil is in the details of how the operators match the results of the module execution.

**Comment by plastikos** [comment]
One challenge with this approach is that because the target is "dynamic" the master has no idea which minions will respond and so ``CkMinions`` won't be applicable and progress and summary accounting won't apply.  For this type of targeting it would be nice if *each* minion responded either with a ``NACK`` or results - that way response accounting would be accurate.
