### ISSUE TITLE
Duplicate AWS instances can be created if one with the same name exists as terminated

### ISSUE THREAD

**Issue by nghgd** [saltstack/salt#25893]
If an EC2 instance named foobar was terminated, in some cases it is possible to use salt-cloud to re-create an instance named foobar many times.

Where it checks for a machine already existing, it appears to me that the code expects machine names to be unique, so it only checks the one instance it hits first to see if it is terminated.

If that first one it finds is terminated, it allows creating the instance, over and over and over.

This issue oddly seemed more reproducible when making the salt-cloud call using subprocess within a python shell rather than a bash shell.

```
salt-cloud --versions-report
                  Salt: 2015.5.2
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
       Apache Libcloud: 0.14.1
 Debian source package: 2015.5.2+ds-1trusty1
```

**Comment by rallytime** [comment]
Interesting. Thanks for the report @nghgd. There should be a naming collision occurring when you try to create the new instance. Can you also post the output of `salt-cloud --versions-report` here, just to help us keep track of when this was reported.

The best work-around for this problem is to use `rename_on_destroy: True` in your provider config so the duplicate names can't exist. Though we should definitely 

@techhat You might be interested to learn about this one as well.

**Comment by nghgd** [comment]
Updated with version report.

I did set rename on destroy to true after I realized what was going on.

AWS does allow multiple instances to share the same name and each instance has a randomly generated unique identifier as a key instead of the instance name. My guess is that this code may have been written originally with other providers in mind which require unique instance names.

**Comment by rallytime** [comment]
@nghgd You're spot on. I just thought that we had some nice and handy "You can't do that, there's already a name there" warnings in place and the rename on destroy parameter gets you around the error. 

The bug is in the "so it only checks the one instance it hits first to see if it is terminated" section. We shouldn't be allowing that to happen on subsequent calls. Thanks again!

**Comment by techhat** [comment]
Unless I'm unaware of, or forgetting something, Salt Cloud should always refuse to create nodes with the same name, regardless of provider. EC2 itself allows it, since its concept of naming is no more than a `Name` tag which is not programmically useful to their internals. (This is as opposed to instance IDs, which are the randomly-generated codes of which you speak, and which are used extensively internally in EC2.)

The reason `rename_on_destroy` is there is because EC2 instances usually take about an hour to clean up, and it's obnoxious to have to wait.

**Comment by codehotter** [comment]
cloud/clouds/ec2.py has list_nodes_min, which returns a dict:

```
3141     for instance in instances:
3142         if isinstance(instance['instancesSet']['item'], list):
3143             for item in instance['instancesSet']['item']:
3144                 state = item['instanceState']['name']
3145                 name = _extract_name_tag(item)
3146         else:
3147             item = instance['instancesSet']['item']
3148             state = item['instanceState']['name']
3149             name = _extract_name_tag(item)
3150         ret[name] = {'state': state}
3151     return ret
```

On line 3150, I think VMs with duplicate names simply overwrite each other in the ret.
If you're unlucky, you might overwrite a running instance with the terminated one.

Then in cloud/__init__.py, there are several places which check for "terminated" status.
For example, around line

**Comment by codehotter** [comment]
What happens if you just don't return Terminated nodes in the node list?
Will users ever want to interact with Terminated nodes?

**Comment by nghgd** [comment]
To my knowledge, terminated instances have no useful function, I would just skip them entirely when getting the list of instances.

**Comment by techhat** [comment]
@nghgd, if they show up in the web console but not Salt Cloud, then we're basically lying to people. I would be up for making an option to hide them, but not just hiding them.

**Comment by nghgd** [comment]
A person (or salt) can do literally nothing with a terminated instance. It's just sitting in a queue to be permanently deleted.

**Comment by codehotter** [comment]
These issues might be related.

https://github.com/saltstack/salt/issues/18863
https://github.com/saltstack/salt-cloud/issues/916

You can do something with a terminated instance, namely see that there used to be an instance, and that it was terminated. This is useful, and probably why Amazon chooses to report these instances.

However, if it simplifies the rest of the salt-cloud code to hide these instances from salt-cloud, I don't think there's much harm done. "Basically lying to people" overstates it. An instance going missing after being terminated is not likely to lead to a lot of confusion. People will just assume that terminated instances are not visible to salt because you cannot interact with them.

**Comment by techhat** [comment]
In my tests, it has proven to be very helpful to know which instances I have deleted recently.  While I may default Salt Cloud to not showing terminated instances, I would never use that default myself.

**Comment by codehotter** [comment]
I agree that it is sometimes useful to see the terminated instances. Salt currently does not give a full picture, because it makes the assumption that there will be only one instance with a certain name, hiding the rest. It can hide the terminated instance we both say is useful to see, if it hits the running instance first.

The behavior is unpredictable.

Do we have any other options besides these? None of them is perfect.

1. Forbid the creation of instances with the same name as a terminated instance.
2. Make salt-cloud aware of the possibility of multiple instances with the same name and handle gracefully.
3. Filter Terminated instances in the ec2.py driver rather than in main salt-cloud code.

1) is guaranteed to annoy some users, especially if the instance was terminated in the AWS console, so rename_on_destroy has no effect. It would also be a feature regression, as salt currently supports this.
2) could be an API-breaking change, because you can no longer pass list of instances as dict-by-name, so all providers would potentially have to be changed. Alternatively, main salt-cloud code would check the return type.
3) This has the disadvantage of hiding terminated instances even when just viewing.

Be careful about adding too many configuration options. It increases complexity for you, because you have to maintain the extra code and documentation, and also for your users, because they have to read about many (to them, irrelevant) options when trying to do what they want.

**Comment by codehotter** [comment]
What happens if we filter Terminated instances in list_nodes_min, but leave them in the other list_nodes functions?
Would that achieve salt-cloud --query showing the instances, while other salt-cloud commands do not get confused?

**Comment by rallytime** [comment]
@techhat and I have been discussing this and I have submitted #26479 to fix it.

The default behavior on other cloud drivers is to not allow instances to be created if the new instance has the same name as other instances. This fix duplicates this behavior for EC2, even if the instance is in the ``terminated`` state. The fix also makes ``rename_on_destroy`` default to True in order to clean up those terminated instances in case you forgot to set it in your cloud config.
