### ISSUE TITLE
ER: Allow pkg.installed to require a pkgrepo.

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#25939]
From the documentation for require_in under [states.pkg_repo.managed](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html):

"require_in: Set this to a list of pkg.installed or pkg.latest to trigger the running of apt-get update prior to attempting to install these packages. Setting a require in the pkg will not work for this."

Why does this work:

``` saltstack
nginx:
  pkg.installed:
    - require:
      - pkg_repo: nginx

nginx_repo:
  pkgrepo.managed:
    - ppa: nginx/stable
```

While this does not:

``` saltstack
nginx:
  pkg.installed

nginx_repo:
  pkgrepo.managed:
    - ppa: nginx/stable
    - require_in:
      - pkg: nginx
```

Is there any logic why the dependency definition only works in one direction?  Are there other places which have a similar (or reverse) limitation? If this is something that's really not fixable, should it also be documented in [Requisites and Other Global State Arguments](http://docs.saltstack.com/en/latest/ref/states/requisites.html)

**Comment by jfindlay** [comment]
I think you may be understanding `require` and `require_in` backwards.  Personally, I think the names are backwards, but there is nothing we can do about that at this point and the documentation is probably also confusing the matter.

If you want to install a special repo for nginx before installing nginx, there are two equivalent requisite configurations you can use:
```saltstack
nginx repo:
  pkgrepo.managed:
    - name: nginx_repo
    - ppa: nginx/stable

nginx pkg:
  pkg.installed:
    - name: nginx
    - require:
      - pkgrepo: 'nginx repo'
```
and
```saltstack
nginx repo:
  pkgrepo.managed:
    - name: nginx_repo
    - ppa: nginx/stable
    - require_in:
      - pkg: 'nginx pkg'

nginx pkg:
  pkg.installed:
    - name: nginx
```

**Comment by notpeter** [comment]
@jfindlay Ugh. Sorry I messed up my copy pasta, but I've now edited it.

I understand requires/requires_in, but my real question is WHY pkg's can't require a pkg_repo.  Why MUST the dependency go the other way?  I have definitely run into this before (multiple times in fact) and unless it was recently fixed the documentation is correct...I'm just looking for an explanation why requiring a pkgrepo doesn't work while when a pkgrepo has require_in pkg it does.

**Comment by jfindlay** [comment]
@notpeter, from my understanding, both of your examples should work.  Are you getting an error running the second state?

**Comment by notpeter** [comment]
Neither will error; my second state functions properly. Whereas my first state installs nginx from my main sources.list repo (not from the PPA).  The documentation says this it's because only the require_in triggers the necessary `apt-get update` (indexing the newly added PPA) before running `apt-get install nginx`. Just because the behavior is documented doesn't mean it's not a bug.  I strongly feel it's counter intuitive that your choice of requires/requires_in for linking two states results in divergent behavior (B require A != A require_in B).

**Comment by basepi** [comment]
So there are a couple of factors at work here.

(1) A state doesn't know which other states (if any) are requiring it. However, it does have access to its list of global state arguments, including requisites. So, a pkgrepo.managed can only know to trigger an `apt-get update` with require_in. We don't want to make it so that if a pkg.installed state requires any other state, we do an `apt-get update` -- that would be performance suicide.

(2) I assume a decision was made at some point not to run `apt-get update` after each pkgrepo.managed state, probably because of performance concerns. This is the questionable decision in my mind -- how often are you changing pkgrepos, and how many pkgrepo states are in an average state run? I'm thinking pkgrepo.managed just needs an argument to run `apt-get update` after changes are made. Thoughts?

Hope that clears things up. I think the last part of my (2) is probably the solution we should go for.
