### ISSUE TITLE
[2015.8.0rc2] pillar merge strategy default behaviour change

### ISSUE THREAD

**Issue by tbaker57** [saltstack/salt#25954]
Not sure whether this is a bug or "I'm doing it wrong". Anyway, the behaviour of the pillar merging strategy seems to have changed in 2015.8.0rc2 when the same pillar gets included multiple times.
A minimal example to reproduce:
```
/etc/salt/minion:
-----
id: dev
grains:
  roles:
    - role1
    - role2


/srv/pillar/top.sls:
-----
base:
  'roles:role1':
    - match: grain
    - xxx

  'roles:role2':
    - match: grain
    - xxx

/srv/pillar/xxx.sls:
----
xxx:
  yyy:
    - name: zzzz

```
With 2015.8.0rc2 I get
```
[root@dev ~]#  salt-call --local pillar.get xxx
local:
    ----------
    yyy:
        |_
          ----------
          name:
              zzzz
        |_
          ----------
          name:
              zzzz
```
whereas with 2015.5.2 I get
```
[root@dev ~]# salt-call --local pillar.get xxx
local:
    ----------
    yyy:
        |_
          ----------
          name:
              zzzz

```
I'm guessing this is related to the http://docs.saltstack.com/en/latest/ref/configuration/master.html#pillar-source-merging-strategy. The default appears to be 'smart' in both 2015.5 and 2015.8, but as alluded to in #23044 it is unclear what 'smart' actually means. It certainly looks like it has changed (at least for the masterless setup I've tested).

cheers,
Tim

**Comment by jfindlay** [comment]
@tbaker57, thanks for the report.

**Comment by basepi** [comment]
I can reproduce this. Now I just need to figure out if the `smart` strategy was broken and then fixed, or vise versa.

**Comment by basepi** [comment]
Alright, I've tracked this down.

https://github.com/saltstack/salt/pull/25358 introduced this behavior, and I think it makes a lot of sense. If you want it to recursively merge the data structures, it should merge lists as well. The workaround for you will probably be to either stop including multiple times, or set the merge strategy to `overwrite`.

In any case, I'm going to call this expected behavior, but am happy to continue discussing.

**Comment by deuscapturus** [comment]
This can't be expected behavior.  The top file may use several different targeting methods to assign a pillar.  This may result in a pillar being assigned to a minion more than once.  The merge behavior isn't the problem.   It should be expected behavior that a pillar can only be applied to a minion one time.

**Comment by merll** [comment]
I have to agree that it is not expected behavior, and the merge is not the problem. However it seems that this issue got fixed in ``salt.utils.dictupdate`` by not merging but overwriting lists by default, related to #27890 / #27891. The behavior prior to that change is now reflected in the ``recurse_list`` strategy.

Nevertheless I think it would be a good idea to deduplicate pillars already at the time they are selected from the top files, i.e. in ``salt.pillar.Pillar.top_matches()``. That way it would be possible to merge lists intentionally from multiple pillar .sls files, but as @deuscapturus suggested, avoid rendering and merging the same .sls files more than once.
