### ISSUE TITLE
Cron identifier does not default to state ID as documented

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#25958]
[These lines of code in states/cron.py](https://github.com/saltstack/salt/blob/dcc6883b248dc2a0506d59ebe4127eb2877a7600/salt/states/cron.py#L255-L261) speak for themselves.

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.

**Comment by anlutro** [comment]
I can easily submit a pull request for this, but should defaulting to the state ID really be the default? I think it should, but would like confirmation.

Also, this might break existing states - but if any existing states didn't define a cron identifier they're likely already broken as duplicate cron jobs will be generated as the cron job parameters change.

Should this be fixed in 2015.5 or 2015.8?

**Comment by jfindlay** [comment]
It really depends on how many people are using the state, it is a minor change to a parameter that is technically part of the API, but the change would be to fix a minor flaw in how that parameter is handled.  Since the documentation says it will be the state ID, I think it will be fine to put it into 2015.5.

**Comment by anlutro** [comment]
Closing as #26219 is merged
