### ISSUE TITLE
`neutron` exec-functions aren't modeled after Neutron CLI Tools, are missing features

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#26099]
While execution modules for other OpenStack components like Glance and Keystone mostly look like their CLI counterparts the current neutron module does not. 

I would suggest adding/merging missing features from the [neutron module](https://github.com/fraunhoferfokus/openstack-formula/tree/master/_modules/neutron.py) in the [openstack-formula I'm working on](https://github.com/fraunhoferfokus/openstack-formula/) and also provide the more neutron-CLI-like interfaces*.

This should add most of the missing features mentioned in #25306 and would make the addition of [my various state modules for Neutron](https://github.com/fraunhoferfokus/openstack-formula/tree/master/_states) pretty easy.

CC: @whytewolf @yuji-azama

*) With the usual transitional period, of course.

**Comment by whytewolf** [comment]
well one thing to keep in mind. with neutron, nova and swift the exec module is split into 2 parts. [ i believe because they are also part of the salt-cloud stack. ] there is the exec module in modules. however all the heavy lifting is done in utils/openstack 

I did start the work earlyer with https://github.com/saltstack/salt/pull/24963 and put in a issue with subnets. https://github.com/saltstack/salt/issues/25306

also, keep in mind backwards compatibility is VERY important.

**Comment by jfindlay** [comment]
@0xf10e and @whytewolf, thanks for documenting this.  Your descriptions of the proposed changes sounds great.

**Comment by 0xf10e** [comment]
Thx, @jfindlay

@whytewolf keeping wrappers emulating the old behavior until [Carbon](https://github.com/saltstack/salt/blob/develop/salt/version.py#L83), i.e. for ~1 year, would be enough?
I would be fine with Nitrogen, too, as long as I can use my newer interfaces and features in Boron or even 2015.8.(>0).

**Comment by whytewolf** [comment]
one thing to keep in mind and this was a major problem with your glance update. DON'T change the authentication keyword. it is keystone on all the other modules for a reason. this was not an inconsistency. keystone is the name of the authentication system for all of openstack. by naming the keyword keystone, all of the modules can use the same profiles. right now because of the glance change i have 2 sets of settings. one for glance one for everything else. and they have the exact same data in them. this is inefficient.

**Comment by 0xf10e** [comment]
Would be difficult to keep previous behavior when I'd change those keys, wouldn't it?

**Comment by 0xf10e** [comment]
OK, this one won't go in Beryllium.0 anyway, so I don't have to fix this, right now, right?

**Comment by whytewolf** [comment]
@0xf10e other than glance, which you already have a ticket and code being worked on, i don't think so. my setup gets around the neutron issues by using cmd.run. I'm not happy about the cmd.runs but i can live with it.
