### ISSUE TITLE
Salt better rotate its logs.

### ISSUE THREAD

**Issue by crocket** [saltstack/salt#26195]
Since system administrators very often forget to make a logrotate configuration for programs, some logs can grow large and fill up file systems. I had it happen before.

If Salt(minion, master) rotated its own logs and system administrators are notified that Salt rotates its own logs, system administrators will have one less moving part to worry about.

**Comment by jfindlay** [comment]
@crocket, thanks for the feature request.  This seems like a good idea and should be easy to implement.

**Comment by anlutro** [comment]
The `salt-common` debian package has a logrotate.d file.

**Comment by damon-atkins** [comment]
Any software which writes logs to a file system, should manage its own logs, so it does not need to be restarted or send its own signal and works on all OS, with and without the existence of  logrotate.
It's best if it rotates them based on MByte size (even if middle of the day), or end of day or both.  (Line count based rotations requires the file to be read vs quick fstate & time() calls)

**Comment by anlutro** [comment]
I disagree. logrotate is a linux standard by now, and the logrotate configuration file can be overwritten if users need to rotate more or less often.

**Comment by tiramiseb** [comment]
I disagree with damon-atkins too.
Logrotate is largely standard, all our logs are rotated by logrotate. It makes logrotation way easier.

By the way, rotation "based on MByte size (even if middle of the day)" is the worse way logs may be rotated. It's perfect when you want to be lost in your logs... The only viable logrotation policy in a decent environment is time-based.

Logrotate allows creating homogeneous logrotation rules among many logfiles from different tools.

That being said, using syslog would still be way better.

**Comment by damon-atkins** [comment]
Their are current issues with salt and logrotate see issues above.

logrotate is not on every platform e.g. windows event logs which are KB size limited.   10-15 lines of code to add self log rotation, base on parameters in a salt minion config file.  

I agree syslog is a good choice on most platforms as the logs can be push to a remote server. Server these days can last only a few hours and when terminate you need to collect any local logs before they are terminated.

In the end logrotate and syslog are not everywhere and salt is trying to be **everywhere**.

Salt needs support log rotation by others (e.g. logadm on solaris, logrotate on Linux, etc) or itself or both..

PS MB logs size tests to determine if a file should be rotated at midnight results in heavy logging logs kept for a shorter amount of time and slow logging logs for longer. In general you end up with logs being kept longer instead of the semi standard of about 10 days..  I said the middle of the day for salt as it can log a lot, but general stick to midnight tests.

**Comment by tiramiseb** [comment]
As I said, the minion dealing with its own logfiles seems perfectly logical, mostly because it is multiplatform. But it must not make it impossible to use other tools for logs rotation or management (see #11716 and #13558) : it should honor SIGHUP, like the vast majority of daemons honor it. However it is not the subject of this thread.

**Comment by cachedout** [comment]
I also do not believe that Salt should do this. My vote is for logrotate and/or loggers like syslog.

**Comment by lorengordon** [comment]
I don't think this should be a salt feature either. If you want logrotate on Windows, use another third-party package. A quick Google search turns up several.

**Comment by damon-atkins** [comment]
Adding log rotation into Salt gives the users an option they can use or not use.  Let the user/customer decide.   People that want to use the option will be happy, and the people do not not want to use the option will be happy to disable it or send it somewhere else. Everyone will be happy :-)

e.g.
class logging.handlers.RotatingFileHandler(filename, mode='a', maxBytes=0, backupCount=0, encoding=None, delay=0)¶

Or for windows as a extra option
class logging.handlers.NTEventLogHandler(appname, dllname=None, logtype='Application')¶

More and more Syslog apps do their own log rotation now.

**Comment by lorengordon** [comment]
It is also likely to introduce more bugs for a non-critical feature, taking dev time away from more important things. And the feature can be provided by other packages that have a focus on providing that capability. Why pull those bugs into salt when there are other options that already do it? Just use salt to configure one of those options. ;)

**Comment by crocket** [comment]
Log rotation has to be done. Otherwise, logs will fill up storages. I use logrotate, and it feels somewhat awkward to keep logrotate in sync with various other programs. Sometimes, I forget to apply logrotate to some programs, and my storage devices become full.

It'd help system administrators to turn on log rotation by default in SaltStack.

**Comment by jalons** [comment]
Would this be adding in support for ```TimedRotatingFileHandler``` and/or ```RotatingFileHandler``` in addition to the existing ```FileHandler```? So the complexity would reside in the configuration of when to enable which of the above named classes?

If that's the case, the complexity would be in how to handle the configuration, since from what I can see the majority of the logging gotchas are for the temporary logging handlers that don't apply to file based logging. It's a trade off for sure, but log rotation on windows is super annoying. 1G+ minion files are common if you run at debug for any length of time in a busy or large environment. I'd much rather use python's built in methods than try to leverage additional software, and can take a look at adding support for the additional [file handlers](https://github.com/saltstack/salt/blob/develop/salt/log/setup.py#L45)
