### ISSUE TITLE
group members setting fails with obscure error message on FreeBSD

### ISSUE THREAD

**Issue by fullermd** [saltstack/salt#26207]
I have a state along the lines of

        somegroup:
          group.present:
            - members:
              - abc
              - def

When trying to run it, I get a failure that winds up ending with a backtrace like

                File "/usr/local/lib/python2.7/site-packages/salt/states/group.py", line 154, in present
                  __salt__['group.members'](name, ','.join(members))
                File "/usr/local/lib/python2.7/site-packages/salt/utils/lazy.py", line 90, in __getitem__
                  raise KeyError(key)
              KeyError: 'group.members'

This is presumably because there is no 'members' function defined in modules/pw_group.py, and so doing this is actually unsupported on my platform.

**Comment by jfindlay** [comment]
@fullermd, usually a KeyError on an exec module function, like `group.members` means that that function has not been loaded by the loader into `__salt__`.  Since this error is coming from the loader itself, something else might be going on.  The typical reasons the loader doesn't add an exec module's functions to `__salt__` are:
- the module contains a syntax error,
- the module's `__virtual__` function returned `False`.

**Comment by jfindlay** [comment]
Or
- the state is calling an exec module function that doesn't exist.
I should have read the code, thanks @silenius.

**Comment by rallytime** [comment]
This is fixed by #26237
