### ISSUE TITLE
Tracking issue: missing function detection

### ISSUE THREAD

**Issue by vr-jack** [saltstack/salt#26208]
We need to have a process to detect missing or empty functions in the code base. This is especially true for the various operating systems or where docs has add a function that was missing but left it with just documentation.

When the missing or empty function is detected, we should add/update it and have it properly error with unsupported function. This will at least immediately notify a user with good information. In addition, this would allow detection that functionality is missing and a choice of fixing it if it is something that should be there.

See:
https://github.com/saltstack/salt/issues/26207
and
https://github.com/saltstack/salt/issues/26017
and
https://github.com/saltstack/salt/issues/25318

**Comment by jfindlay** [comment]
@vr-jack, this is a good idea, thanks for reporting.  I have never thought of this because I've always known why a function is unavailable:
- the module's `__virtual__` function returns `False`
- the module has a syntax error

We should detect these reasons in the loader and provide an appropriate message to the user.
