### ISSUE TITLE
salt v2015.5.3 gitfs.py using newer pygit2 feature than required minimum

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#26245]
Salt [v2015.5.3 gitfs docs](http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html) state that we need pygit2 0.20.3 as a minimum version. 

It appears that salt v2015.5.3 gitfs.py is using pygit2.errors - which doesn't appear until pygit2 0.21.0. This causes errors such as as this for those not up to pygit2 0.21.0 when there are problems with gitfs:

```
[DEBUG   ] Set lock for git@github.com:bradthurber/salt-formula.git
[DEBUG   ] gitfs is fetching from git@github.com:bradthurber/salt-formula.git
[ERROR   ] Exception ''module' object has no attribute 'errors'' caught while fetching gitfs remote git@github.com:bradthurber/salt-formula.git
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/fileserver/gitfs.py", line 1162, in update
    except pygit2.errors.GitError as exc:
AttributeError: 'module' object has no attribute 'errors'
```

It looks like the requirement for pygit2.errors.GitError was removed at some point in salt develop. Possible fix options for 2015.5:
a) Update the gitfs doc page to state pygit2 0.21.0 is the minimum version required 
b) backport portions of salt develop gitfs.py to avoid use of pygit2.errors.GetError.

**Comment by jfindlay** [comment]
@bradthurber, thanks for the report.  @terminalmage will have the best idea of what to do here.

**Comment by terminalmage** [comment]
Backporting is the only option here. 0.20.3 is the newest available in a couple major distros.

**Comment by terminalmage** [comment]
Fixed by #26419 and #26420.

This issue still existed in the 2015.8 and develop branches, contrary to what @bradthurber suggested earlier. He just wasn't aware of the refactoring done to gitfs. The offending code still existed, it was just now in salt/utils/gitfs.py.

The first pull request fixes this for the 2015.8 and forward, while the second fixes it for the 2015.5 branch.

Sadly, @bradthurber, this *just* missed making it into 2015.5.4. Our next release will be 2015.8.0, and this fix will be in that release.

Thanks again for reporting this! I originally developed the pygit2 support on newer pygit2 and must not have tested it on 0.20.3.

**Comment by terminalmage** [comment]
@bradthurber Actually, our QA team found issues with the 2015.5.4 release after we tagged it, so this fix will make it into 2015.5.5. 2015.8.0 will follow soon after.

**Comment by bradthurber** [comment]
@terminalmage - thanks for the update!

**Comment by terminalmage** [comment]
No problem, and thanks again for bringing this to our attention.
