### ISSUE TITLE
Salt Cloud creates key for VM even if VM creation fails

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#26321]
```
[root@theserver ~]# salt-cloud --versions-report
Salt Version:
            Salt: 2015.8.0rc3

Dependency Versions:
 Apache Libcloud: 0.15.1
          Jinja2: 2.8
        M2Crypto: 0.21.1
            Mako: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.3.1
          Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 3.2.5
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
        pycrypto: 2.6.1
         timelib: Not Installed

System Versions:
            dist: centos 7.1.1503 Core
         machine: x86_64
         release: 3.10.0-229.1.2.el7.x86_64
          system: CentOS Linux 7.1.1503 Core
```

When attempting to spin up a VM on DigitalOcean I inadvertently included an underscore in the VM name, which is an illegal character for VMs on DigitalOcean. Salt Cloud gave me a nice error stating clearly what characters are allowed. Nice!

```
 salt-cloud -p do_cent7_4gb web____test
```

Then I noticed that `web____test` showed up in my list of accepted keys on my salt master when running `salt-key -L`

I would expect that if a VM fails to build on a cloud for some reason, Salt Cloud shouldn't leave keys around. So either Salt Cloud should create the keys AFTER successful VM creation or delete the keys if VM creation fails.

**Comment by techhat** [comment]
The very first thing Salt Cloud does is create keys, so if a VM doesn't get created, it should delete them.

**Comment by phoenixNull** [comment]
Hi there, although it's my first post i'd like to weigh in on this as I'm writing/using my own cloud provider. I would really appreciate it if salt didn't create anything. As it stands, during the create(vm_) it runs the salt.cloud.gen_keys which calls the salt.crypt.gen_keys which overwrites the keys on the pki_dir. 

It would be far more useful if salt-cloud didn't touch the pki_dir until it needs to, instead of cleaning up after it fails,say, by using a temp dir and just pass the pub/priv data in the vm_ and let programmers manage it and place the keys afterwards. 

Aside from the case in which a build fails, there is the case where the VM might already exist. Although it is can be managed (prompting for oversight and action), we still have no way to save the old key because it got overwritten and we need to re-send the new keys for something that might been a simple check and pass.

**Comment by aphor** [comment]
#26498 is complimentary to this issue

**Comment by anitakrueger** [comment]
@techhat @jfindlay 
Is it possible to re-open this issue please? I've been running into this for years, but always cleaned up the keys myself. Now I am creating instances in a far more automated fashion and in higher volumes and if any instance creation fails, I have a bunch of keys lying around that somehow the salt master thinks are accepted minions.
salt-cloud should either delete the keys for instances it wasn't able to create or only use them temporarily and then copy them later as @phoenixNull pointed out.

**Comment by rallytime** [comment]
@anitakrueger Definitely. Thanks for chiming in!

**Comment by anitakrueger** [comment]
I don't believe this has been fixed, has it?

**Comment by anitakrueger** [comment]
4 years later...still an issue :(

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
