### ISSUE TITLE
It's hard to find the current stable version of Saltstack

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#26425]
**Problem:** It's hard to find the current stable version of Saltstack.

**Background:** I've found nothing on:
 * http://saltstack.com/
 * http://saltstack.com/community/
 * http://docs.saltstack.com/en/getstarted/

Finally I found it 4 clicks later on https://pypi.python.org/pypi/salt. I think. But is that the stable version or a beta? Who knows! ;)

**Solution:** Make it more clear on initial page what the latest stable version is and preferably also a sentence on beta, release candidates, alphas etc.

**Comment by JensRantil** [comment]
Actually, the Debian repos I am using for my saltstack installation delivers 2015.5, so the PyPi package must be out of date...

**Comment by rallytime** [comment]
Thanks for the feedback - we should be able to make that more clear.

ping @jacobhammons

**Comment by terminalmage** [comment]
Yeah, we used to have this in a persistent location on docs.saltstack.com, but this is no longer present after our docs redesign. Should be a very easy thing to correct.

**Comment by badele** [comment]
I confirm the @JensRantil remark,

I don't know if i'm  off topic, for me, i have pratically the same problem, i try use the good version for use proxmox provider.

- In the default salt version (2015.5.3) we have the the  problem with SSL verification => https://github.com/saltstack/salt/issues/25652
- In the latest pre-release (v2015.8.0rc3), i have a problem with the msgpack => https://github.com/saltstack/salt/issues/26705

Too bad, i think the saltstack is the good tools, I have not had time to test salt, because, i have lost time for find the good version and debugging the problems for specific version, each version fix a problem, but not all :)

I know the proxmox provider is developed by the salt community and that is not supported by the saltstack compagny.

But i think a good idea for the (state, module, provider etc ...) we know if that run with a special version ( I know it's difficult  that implement the unit tests for the providers )

I am eager to test salt with proxmox and can be subsequently contribute to salt.

**Comment by DanyC97** [comment]
@badele @JensRantil  from the main page http://saltstack.com/ if you click on Software -> Documentation you do get to the latest page which shows on the right hand side the last 2 stable releases + the develop (bleeding) version (not released)

Isn't that enough ?

**Comment by JensRantil** [comment]
Wouldn't it make sense to also have it under "Software -> Downloads"? Also, the page should probably also refer to the PIP version, right?

> Isn't that enough ?

I'm sorry, but I would never have found those versions in the top right corner of the page unless I looked for them _a lot_. I still think it needs a more explicit place.

**Comment by DanyC97** [comment]
@JensRantil fair points, no need to say _sorry_ ;)

**Comment by jacobhammons** [comment]
@JensRantil The current stable release is now listed on https://repo.saltstack.com/ and https://docs.saltstack.com/en/latest/

If you agree that this fixes the issue please close. Thanks!

**Comment by rallytime** [comment]
Several improvements have been made to make this more obvious, as @jacobhammons stated above. As such, I'm going to close this. If a more specific example of where this could be improved is provided, we can certainly re-open this. Thanks!
