### ISSUE TITLE
salt-call winrepo.update_git_repos fails with "Key Error: 'git.latest'" on masterless minion

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26460]
I have a masterless minion and when I invoke:
```salt-call --local winrepo.update_git_repos``` I get:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'git.latest'
```
Full ```debug``` level log is:
```
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.10 or later must be installed before this module can be used.']
[DEBUG   ] Error loading module.victorops: No VictorOps api key found.
[DEBUG   ] LazyLoaded winrepo.update_git_repos
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Could not LazyLoad git.latest
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'git.latest'
Traceback (most recent call last):
  File "c:\python27\scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt==2015.8.0', 'console_scripts', 'salt-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 224, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 50, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\win_repo.py", line 150, in update_git_repos
    result = __salt__['git.latest'](remote,
  File "c:\salt-dev\salt\salt\utils\lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'git.latest'
Traceback (most recent call last):
  File "c:\python27\scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt==2015.8.0', 'console_scripts', 'salt-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 224, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 50, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\win_repo.py", line 150, in update_git_repos
    result = __salt__['git.latest'](remote,
  File "c:\salt-dev\salt\salt\utils\lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'git.latest'
```
My minion is: ```2015.8.0``` and the versions-report is:

```
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
           RAET: 0.6.3
        Tornado: 4.2
            ZMQ: 4.0.5
          ioflo: 1.3.8
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: AMD64
        release: 8
         system: 8 6.2.9200  Multiprocessor Free
```
other relevant lines from my windows minion conf file might be:
```
file_client: local
winrepo_cachefile: c:\\salt\srv\salt\win\repo\winrepo.p
winrepo_dir: c:\\salt\srv\salt\win\repo

winrepo_remotes:
  - 'https://github.com/saltstack/salt-winrepo.git'
```

**Comment by ssgward** [comment]
I get an exception, too, although different. I'm using 2015.8.0rc3 minion. 
```
C:\salt>salt-call --local winrepo.update_git_repos
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
KeyError: 'win_repo'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 224, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 98, in upd
ate_git_repos
    repo = __opts__['win_repo']
KeyError: 'win_repo'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 224, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 98, in upd
ate_git_repos
    repo = __opts__['win_repo']
KeyError: 'win_repo'
```

**Comment by ssgward** [comment]
I'm on Win 7, too, by the way. Looks like the original bug was on Win 8

**Comment by TheBigBear** [comment]
@ssgward same client as me then. Did you set any of the newly named keys in the minon conf file?

win_repo_cachefile ->  winrepo_cachefile: 
win_repo -> winrepo_dir: 
win_gitrepos (already fiorgotten what it sued to be called ??) -> winrepo_remotes:

**Comment by ssgward** [comment]
no, actually. did you?

**Comment by ssgward** [comment]
Just updated my minion config with the needed winrepo entries, restarted my minion service and still get the errors.

**Comment by TheBigBear** [comment]
OK, strange. It's the same error you got on the just closed #20734. Which I referred to as a environment setup diff. Still think this is what it is.

**Comment by TheBigBear** [comment]
@ssgward strange, jsut tested it on a win 7 and also got key error 'win_repo'.
so there is a diffenrence between win 8 and win 7 when it comes to this. will verify #20734 from that angle and re-open it if need be.

**Comment by ssgward** [comment]
@TheBigBear let me know if we need to re-open #20734

**Comment by TheBigBear** [comment]
@ssgward ok, I played some more I did not have the win_gitrepos key (or the new winrepo_remotes key for that matter) defined in my windows 7 minion, once I defined that I then got back to the "Key error: 'git.latest'" same as on the win 8 platform.

So the "Key error: 'win_repo'" just get's chedke first and if that is OK and setup it proceeds to check on the win_repo key. 

So our diffenrences were environment setup differences afterall.

**Comment by TheBigBear** [comment]
@ssgward, will do. 
For completeness, this is the different error I get on win 7 platform for same function
```salt-call --local winrepo.update_git_repos```
I get: ```KeyError: 'win_repo'``` whereas on win 8 I get ```KeyError: 'git.latest'``` (see 1st post above for full details)

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'win_repo'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 224, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 98, in update_git_repos
    repo = __opts__['win_repo']
KeyError: 'win_repo'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 224, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 98, in update_git_repos
    repo = __opts__['win_repo']
KeyError: 'win_repo'
```

**Comment by TheBigBear** [comment]
and on win 7 my ```salt-call --versions``` are:
```
Salt Version:
           Salt: 2015.8.0rc3
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86
        release: 7
         system: 7 6.1.7601 SP1 Multiprocessor Free
 ```

**Comment by TheBigBear** [comment]
OK, I get past that now. On my win7 32-bit the new win_repo configs are not yet know, or read, so I had to go back to the old naming and now it comes up with ```"Key error: 'git.latest'```
```
winrepo_cachefile: values set back to -> win_repo_cachefile: 
winrepo_dir: -values set back to > win_repo:
winrepo_remotes: values set back to -> win_gitrepos:
```
I will document this as a separate bug tomorrow.

**Comment by TheBigBear** [comment]
For the record, this is the debug log for the current issue on a win 7 machine:
```
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.10 or later must be installed before this module can be used.']
[DEBUG   ] Error loading module.victorops: No VictorOps api key found.
[DEBUG   ] LazyLoaded winrepo.update_git_repos
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Could not LazyLoad git.latest
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'git.latest'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 224, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 112, in update_git_repos
    result = __salt__['git.latest'](gitrepo,
  File "C:\salt\bin\lib\site-packages\salt\utils\lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'git.latest'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 224, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 112, in update_git_repos
    result = __salt__['git.latest'](gitrepo,
  File "C:\salt\bin\lib\site-packages\salt\utils\lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'git.latest'
```

**Comment by terminalmage** [comment]
@TheBigBear Yeah the new parameters only apply to the runner, not to masterless. I still need to get masterless working.

**Comment by terminalmage** [comment]
Also, the new parameters only apply to the upcoming 2015.8.0 release.

**Comment by TheBigBear** [comment]
@terminalmage 

oh ok, I am still a bit confused by the different parts. 

I created my own version of ```masterless```, "accidentally", I think. ;-) 

I created a ```c:\salt\srv\salt\win\repo``` directory, 
changed to it and ran ```git clone https://www.github.com/saltstack/salt-winrepo.git salt-winrepo```
followed by ```salt-call --local winrepo.genrepo```
followed by ```salt-call --local pkg.refresh_db```

If there is anything I can do to test or even help the proper masterless ```winrepo.update_git_repos``` to work, let me know. I do have time and am willing, so if you can spare the time for a few basic instructions on wat and where, I might be able to get this off the ground with some oversight and help.

**Comment by terminalmage** [comment]
@TheBigBear OK, I need to do some work to get masterless using some of the code I wrote recently for the runner, but if you have cloned a repo into that directory, you *should* be able to update it... Did you install Git for Windows so that it is accessible from the Command Prompt, or just the Git Bash application?

**Comment by terminalmage** [comment]
Oh, actually no, you can't just clone something into that dir and update it, ``update_git_repos`` would be looking for a list of repos in ``the win_gitrepos`` parameter.

Some of these parameter names are changing for 2015.8.0 as well. The develop branch docs for the winrepo might clear some of this up for you: http://docs.saltstack.com/en/develop/topics/windows/windows-package-manager.html

**Comment by terminalmage** [comment]
Also, I can see what is causing that KeyError. This will be fixed too with 2015.8.0, but in the meantime you'll have to manually do a git pull on the repo and then do a ``salt-call winrepo.genrepo``.

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/26541 fixes this KeyError, so I'm going to close this out.

In the meantime, I think I can see where your confusion lies, @TheBigBear, and I added quite a bit of documentation to our Windows Repo page to hopefully make this more clear.

So, you shouldn't be using ``winrepo.update_git_repos`` unless you have configured repos in the ``win_gitrepos`` parameter (this parameter's name is changing to ``winrepo_remotes`` in 2015.8.0, the docs I added explain this change). However, using this function at all is totally optional. We just have it there as a convenience so that updating the repos can be managed easily within Salt. Unfortunately, due to this error message you were seeing, it's impossible right now to actually manage winrepo git repos using Salt, but this is one of the things I fixed for 2015.8.0.

In the meantime, if you place your repo data, set the following config param:

```yaml
win_repo: 'C:\salt\srv\salt\win\repo'
```

Then you should be able to do a ``salt-call winrepo.genrepo`` and a ``salt-call pkg.refresh_db`` and be good to go.

If you still have problems, I recommend waiting for 2015.8.0. The winrepo code underwent a lot of fixes for this release, and should be *much* more stable for you.

**Comment by terminalmage** [comment]
Note: the above explanation assumes 2015.5.x or earlier is installed, I didn't realize until you commented a few mins ago in #26461 that you're running an RC for 2015.8.0.

**Comment by liyingbo** [comment]
I have the same same issue 
C:\salt>salt-minion --version
salt-minion 2015.8.0-385-gfb4d21b (Beryllium)
C:\salt>salt-call state.highstate -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.highstate
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'top.sls' to resolve 'salt://top.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\top.sls' to resolve 'salt://top.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://top.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\top.sls
[DEBUG   ] Jinja search path: '['c:\\salt\\var\\cache\\salt\\minion\\files\\base']'
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\top.sls:
base:
  '*':
    - webserver
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('base', OrderedDict([('*', ['webserver'])]))])
[DEBUG   ] compound_match: myteamcity ? *
[DEBUG   ] compound_match myteamcity ? "*" => "True"
[DEBUG   ] LazyLoaded saltutil.sync_all
[DEBUG   ] Syncing all
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\beacons'
[INFO    ] Syncing beacons for environment 'base'
[INFO    ] Loading cache from salt://_beacons, for base)
[DEBUG   ] LazyLoaded cp.cache_dir
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[INFO    ] Caching directory '_beacons/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_beacons'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\modules'
[INFO    ] Syncing modules for environment 'base'
[INFO    ] Loading cache from salt://_modules, for base)
[INFO    ] Caching directory '_modules/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_modules'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\states'
[INFO    ] Syncing states for environment 'base'
[INFO    ] Loading cache from salt://_states, for base)
[INFO    ] Caching directory '_states/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_states'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\grains'
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_grains'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\renderers'
[INFO    ] Syncing renderers for environment 'base'
[INFO    ] Loading cache from salt://_renderers, for base)
[INFO    ] Caching directory '_renderers/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_renderers'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\returners'
[INFO    ] Syncing returners for environment 'base'
[INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_returners'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\outputters'
[INFO    ] Syncing outputters for environment 'base'
[INFO    ] Loading cache from salt://_outputters, for base)
[INFO    ] Caching directory '_outputters/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_outputters'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\utils'
[INFO    ] Syncing utils for environment 'base'
[INFO    ] Loading cache from salt://_utils, for base)
[INFO    ] Caching directory '_utils/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_utils'
[INFO    ] Creating module dir 'c:\\salt\\var\\cache\\salt\\minion\\extmods\\log_handlers'
[INFO    ] Syncing log_handlers for environment 'base'
[INFO    ] Loading cache from salt://_log_handlers, for base)
[INFO    ] Caching directory '_log_handlers/' for environment 'base'
[DEBUG   ] Local cache dir: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\_log_handlers'
[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded saltutil.refresh_modules
[DEBUG   ] LazyLoaded event.fire
[DEBUG   ] SaltEvent PUB socket URI: tcp://127.0.0.1:4510
[DEBUG   ] SaltEvent PULL socket URI: tcp://127.0.0.1:4511
[DEBUG   ] ['Traceback (most recent call last):\n', '  File "C:\\salt\\bin\\lib\\site-packages\\salt\\modules\\event.py", line 99, in fire\n    listen
=False)\n', '  File "C:\\salt\\bin\\lib\\site-packages\\salt\\utils\\event.py", line 127, in get_event\n    return SaltEvent(node, sock_dir, opts, lis
ten=listen)\n', '  File "C:\\salt\\bin\\lib\\site-packages\\salt\\utils\\event.py", line 193, in __init__\n    self.connect_pub()\n', '  File "C:\\sal
t\\bin\\lib\\site-packages\\salt\\utils\\event.py", line 301, in connect_pub\n    self.sub.setsockopt_string(zmq.SUBSCRIBE, u\'\')\n', '  File "socket
.pyx", line 450, in zmq.core.socket.Socket.__getattr__ (zmq\\core\\socket.c:4619)\n', 'AttributeError: Socket has no such option: SETSOCKOPT_STRING\n'
]
[DEBUG   ] In saltenv 'base', looking at rel_path 'webserver.sls' to resolve 'salt://webserver.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\webserver.sls' to resolve 'salt://webserver.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://webserver.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\webserver.sls
[DEBUG   ] Jinja search path: '['c:\\salt\\var\\cache\\salt\\minion\\files\\base']'
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\webserver.sls:
nginx:
  pkg:
    - installed
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('nginx', OrderedDict([('pkg', ['installed'])]))])
[DEBUG   ] LazyLoaded cmd.run
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg.installed
[DEBUG   ] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.10 or later must be installed before this module can be used.']
[DEBUG   ] Error loading module.victorops: No VictorOps api key found.
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init
[INFO    ] Running state [nginx] at time 19:36:47.577000
[INFO    ] Executing state pkg.installed for nginx
[DEBUG   ] Could not LazyLoad pkg.hold
[ERROR   ] Package nginx not found in the repository.
[INFO    ] Completed state [nginx] at time 19:36:47.592000 duration_in_ms=15.0
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\77586272 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: nginx
    Function: pkg.installed
      Result: False
     Comment: Package nginx not found in the repository.
     Started: 19:36:47.577000
    Duration: 15.0 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  15.000 ms

C:\salt>salt-minion --version
salt-minion 2015.8.0-385-gfb4d21b (Beryllium)

C:\salt>

**Comment by terminalmage** [comment]
@liyingbo This does not look like the same issue at all, as you are not getting the traceback reported in the initial post. Furthermore, you're not even running the same function from the original post. This bug was occurring when updating the git repos using ``winrepo.update_git_repos`` function.

You may be misunderstanding how our Windows software support works, I'll link you to our documentation so you can read up a bit.

https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html

**Comment by TheBigBear** [comment]
@liyingbo if you do end up creating a salt for windows winrepo sls pkg file for ```nginx``` please be sure to submit it to the ```salt-winrepo``` git repo at either https://github.com/saltstack/salt-winrepo or https://github.com/saltstack/salt-winrepo-ng . You would be fulfilling an old request and closing a long outstanding issue. https://github.com/saltstack/salt-winrepo/issues/29 Thanks in advance.
