### ISSUE TITLE
Vsphere getting started guide should be updated/totally deprecated

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#26560]
It looks like http://docs.saltstack.com/en/latest/topics/cloud/vsphere.html is still alive even though it has a link to the vmware docs. This document should probably be removed, or a getting started guide written for the vmware stuff (in addition to what currently exists doc wise) that this can link to.

**Comment by jfindlay** [comment]
@gravyboat, thanks for the report.  The vmware driver hasn't been officially released yet.  Once 2015.8.0 is released, we can probably add more warnings on it though.  As long as the code continues in salt, ostensibly until 'Carbon', I think we should keep the legacy docs in as well.  What do you think?

**Comment by gravyboat** [comment]
@jfindlay The docs for vmware are showing 2015.5.4, might be good to update that as well. I'm fine with keeping the legacy stuff in, but we should try to duplicate the getting started content I think.

**Comment by rallytime** [comment]
I agree with @jfindlay that we should keep the vsphere docs around since the driver will be available until Carbon.

The new VMWare driver was *supposed* to come out with 2015.8.0, but we had to backport it due some other (unrelated to vsphere) deprecation paths. So, vmware is available in 2015.5.4/5, and there are already getting started docs for the vmware driver here:
http://docs.saltstack.com/en/latest/topics/cloud/vmware.html

@gravyboat What do you mean by "we should try to duplicate the getting started content"?

**Comment by gravyboat** [comment]
@rallytime I'm an idiot and didn't see the vmware guide link to the right and only followed: http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vmware.html#module-salt.cloud.clouds.vmware, ignore that portion, I'm going to close this since I just can't read. :-1:

**Comment by rallytime** [comment]
@gravyboat No worries! :)

I was just confused. Thanks again!
