### ISSUE TITLE
creating & loading sub-modules

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#26596]
I'm working on a custom module that itself needs to be broken up into sub-modules. I'm not clear how to write this such that I would be able to call `salt '*' foo.bar.baz`, where:

`foo` is the parent module
`bar` is the sub-module
`baz` is the function within the `bar` sub-module

Is something like this possible? Am I thinking about this the right way?

**Comment by jfindlay** [comment]
For a compound module, your assumptions seem reasonable.  I know that it is possible, and there are some already, but it is discouraged mainly because of the complexity it imposes on `__salt__` and the users thereof.  You can look at [this](https://github.com/saltstack/salt/tree/develop/salt/modules/inspectlib) for an example of how to do it.

**Comment by cedwards** [comment]
That module doesn't appear to demonstrate use of a compound module in the way I suggested. From what I can tell it provides a couple of libraries for the node module and simply drops them into a subdirectory to keep things clean.

I'll consider some alternatives in pursuing this. Meanwhile I think this ticket can probably be closed.

**Comment by jfindlay** [comment]
It is the only exec module that I know of that is nested.  I didn't look too closely at your requirements.  If you have more questions, I think either @cachedout or @jacksontj would be able to give better advice than I.

**Comment by jacksontj** [comment]
Salt's loader supports infinitely deep submodules (https://github.com/saltstack/salt/pull/20481) but it doesn't expose the names you were talking about ('module.submod.func'). Doing something like that isn't impossible, but it is a bit complicated-- primarily with how does the loader know what to include in the dict? If you included some dependant library, it would cause problems since it would have global methods that don't start with '_'.

As far as addressing stuff like that-- it is *completely* possible and actually supported. The `__salt__ dict` has the naming of modulename.methodname-- and is okay if methodname itself contains periods. So, with that and the `__func_alias__` feature of modules, we can do something like:

```
__func_alias__ = {'test': 'bar.test'}
def test():
    return True
```
And you can address this method by MODULENAME.bar.test. This does mean that your __init__.py will have to address all of the methods you want internally, but this can *also* be done in code-- enforcing whatever naming scheme or decorators or w/e to determine what methods to expose.

Hopefully thats helpful and not just me rambling ;) If you have questions feel free to ask here or on IRC!
