### ISSUE TITLE
salt.state.host.present does not preserve order with multiple names

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#26624]
In Ubuntu (and possibly other distributions), the order of host names in a line in `/etc/hosts` matters, at least for 127.0.1.1.

For example, the following causes `dnsdomainname` to return `example.com`:

    127.0.1.1 foo.example.com foo

while the following does not:

    127.0.1.1 foo foo.example.com

With an SLS file that contains the following:

    foo:
      host.present:
        - ip: 127.0.1.1
        - names:
          - foo.example.com
          - foo

I expect Salt to ensure that the hostnames are listed in `/etc/hosts` in the given order.  Alas, if `foo` is already present, `foo.example.com` is appended.

**Comment by jfindlay** [comment]
@richardhansen, thanks for the report.  What version of salt are you using?

**Comment by richardhansen** [comment]
I'm running 2015.5.3 (from the [saltstack/salt PPA](https://launchpad.net/~saltstack/+archive/ubuntu/salt)) on master and minions.  The master and minions are running Ubuntu 14.04 64-bit server.

I did some digging in the code and it looks like it will not be trivial to change `salt.states.host.present()` to behave as I had originally expected.  This is due to the way the [names declaration](http://docs.saltstack.com/en/latest/ref/states/highstate.html#names-declaration) works.

I have an idea on how to get the behavior I want; I'll submit a merge request when I have the time to put it together.

**Comment by rallytime** [comment]
@rhansen Does your pull request above resolve this issue for you?

**Comment by rhansen** [comment]
Technically PR #26688 does not solve this bug as reported, but it gives me a way to work around it to accomplish what I need.

Given the difficulty of fixing this bug properly, and the likelihood that the new `hosts.only` function from PR #26688 will be a sufficient workaround for any issues people encounter, I'll go ahead and close this bug report.  If someone comes across a situation where PR #26688 isn't sufficient they can reopen this bug.
