### ISSUE TITLE
Release Salt Bootstrap Script in sync with salt or merge script into salt repo.

### ISSUE THREAD

**Issue by mooperd** [saltstack/salt#26697]
It is quite problematic having salt-bootstrap out of sync with saltstack as it is difficult to know which version of salt that the bootstrap has been tested with. 

The current release of salt-bootstrap does not seem to work with any of the older releases of salt. As there is currently no integration testing this is very difficult to manage.

For example: Fixes to issues like this one: https://github.com/saltstack/salt/issues/25335 break provisioning for (slightly) older version of salt.

**Comment by s0undt3ch** [comment]
The issue that you refer has nothing to do with the bootstrap script.

Each stable version of the bootstrap script gets included into salt.

How is the bootstrap script not working with older versions of salt? Is it because the script pulls more deps? Managing deps per salt version in a shell script is not impossible but right now its unreasonable work to add that kind of support. There are plans to switch the bootstrap script to python(leaving just enough shell script to get python installed) at which time its totally feasible to keep per salt version dependencies.

**Comment by s0undt3ch** [comment]
The reason why the script is not included into salt is because its possible to release faster stable releases of the script than salt itself. Imagine that a breakage is found on the script which ships with salt, releasing another version of salt because of the script seems unreasonable(nothing was broken within salt itself), specially because salt can even update to the last stable version of the script, just pass `-u` to the `salt-cloud` CLI.

**Comment by mooperd** [comment]
Recently passing -u to the salt-cloud cli broke 2015.5.3 (and other version) for me. 
Salt failed to start on the minion with

```
2015-08-21 13:27:35,595 [salt.minion      ][ERROR   ][1916] Invalid keyword 'standard' for variable 'master_type'
```

I believe this variable is set so be the most recent release of salt-cloud. The minion started once I deleted this line from the minion configuration file.

**Comment by s0undt3ch** [comment]
And that's a problem specific to salt(already addressed on the 2015.8 and develop branches), its not related to the updated bootstrap script.

**Comment by s0undt3ch** [comment]
I believe that problem is actually narrowed to the 2015.5.3 version.

**Comment by mooperd** [comment]
Older version of bootstrap work well with 2015.5.3.

**Comment by s0undt3ch** [comment]
That log message which stopped the minion from starting has nothing to do with what the script does.
That's a setting that salt cloud passes to the new minion's configuration. The script just places that config file in the right place.

**Comment by rgardam** [comment]
Just hit this bug. 
Things really need to be released together. At least publish stable releases that are actually stable with each other.
