### ISSUE TITLE
Docs - "Full State Module Example" is not really and other doc issues

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#26792]
The State Module docs have a "[Full State Module Example](http://docs.saltstack.com/en/develop/ref/states/writing.html#full-state-module-example)". One starts working through it to find that, yes, it is a full state module, but it needs an Execution Module to actually do anything.

Ah, they must have put it on the [Execution Modules](http://docs.saltstack.com/en/develop/ref/modules/index.html) page - but no such luck.

Some possible suggestions:
a) add the Execution module to the "Full State Module Example" section 
b) add the Execution module to the Execution Modules page and link to it from the State Module page

Also, it would be helpful to know that we can use our own custom State Modules/Execution Modules in formulas. There is guidance on the [Formulas page](http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html) saying "easy on the Jinja" and "avoid heavy logic and progamming. Jinja is not python". Ok fine. I'll take it easy on the Jinja but if I need to use heavy logic, then give me an outline of how to put it together. The guidance on the formulas page is to use the python renderer or similar. While this is nice and "configurey", the pure python renderer also doesn't appear to allow access to map.jinja that is central to the formula pattern - and it doesn't allow requisites (that I can see anyway). It seems a much better recommendation would be to show how to write custom python state/exec modules and bundle them with the formula. 

This is the viewpoint of someone who needs to do some "heavy logic" in states and has been struggling to figure it out. I may still be missing something key about how this stuff is supposed to be put together.

**Comment by jfindlay** [comment]
@bradthurber, thanks for the report.  In my experience, if you are already writing custom exec and state modules, it is easiest and most maintainable to write the heavy logic in the custom modules: integration logic in the exec module and the salt logic in the state module.  By 'use our own custom State Modules/Execution Modules in formulas', do you mean that you want to pick stock salt-formulas to use with your custom exec and state modules?

**Comment by bradthurber** [comment]
@jfindlay thank you for the response. 

The main point of this issue is that the "full state module example" is incomplete because it is missing the execution module. I'm probably taking things too literally here, but when I see the words "full" and "example" my brain thinks that it should be something that I can type in and it works. 

The secondary point is that it was not obvious to me anyway how to include my own custom python modules in my own custom formulas (or ostensibly to contribute to public formulas). I agree now that custom modules sound like the way to go and I think I understand how to do it - but the formulas docs page does not explain the "how" very well - and lead me down the dead-end path (for my purposes anyway) of a pure python renderer.

**Comment by ksalman** [comment]
I was also looking to find a full example, including the execution module.

**Comment by whiteinge** [comment]
@bradthurber @ksalman execution modules are Python functions that return JSON-serializable data. They're really that open-ended and they don't have a defined structure.

For example, this is a complete execution module:

```python
# /srv/salt/_modules/foo.py
def foo():
    return 'Foo'
```

This is accessible at the CLI via `salt '*' foo.foo`, or in Jinja via `{% set return = salt.foo.foo() %}`.

The page you linked above titled [Writing Execution Modules](https://docs.saltstack.com/en/latest/ref/modules/) has additional details for optional features, such as opting not to load the module if some requirement is not met (`__virtual__()`) or how to cross-call other execution modules (`__salt__`), but that knowledge is not required to write or use them.

Since you both are coming at this with a fresh set of eyes, what changes would you recommend that would make that document more clear? Or, better yet, if you're interested [that document can be edited directly on GitHub here](https://github.com/saltstack/salt/blob/develop/doc/ref/modules/index.rst) -- we'd love a pull request with clarifications or an addition. 😄
