### ISSUE TITLE
documentation of `changes` in state module return value unclear/incomplete

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#26861]
I'm writing a custom state module.  The [documentation for state module function return value](https://docs.saltstack.com/en/latest/ref/states/writing.html#return-data) does not answer the following questions:

  * What should the `changes` part of the return value be if `__opts__['test']` is `True`?  Should it show the changes that would have been attempted had `test` been `False`?   Should it be `None`?  Should it be an empty dict?  Should `old` and `new` be identical?
  * What should `changes` be if the state change is partially successful (e.g., some but not all packages were installed successfully)?  (I'm assuming it is sometimes acceptable to have partially successful state changes, and that functions are not always required to roll back any partial changes if there is an error.  Please correct me if I'm wrong.)  Should `changes` only reflect the successful changes?  Should it contain all of the attempted changes?  Should it be `None`?  Should it be an empty dict?  Something else?

**Comment by jfindlay** [comment]
@richardhansen, those are very good questions.  I think that for a test run it is desirable to see what the changes are going to be if possible.  Not all changes can be predicted in a test run, though.  This is a [known problem](https://github.com/saltstack/salt/issues/24938).

If the state is partially successful, I think that it is reasonable for the state to make changes until it fails, show the changes it has made, and then report the failure.  I don't know of any state that attempts to undo the changes it has made in the event of a failure.  Since a failure can occur at any point in the state, the logic for this could easily become very difficult and complex.

**Comment by richardhansen** [comment]
> @richardhansen, those are very good questions. I think that for a test run it is desirable to see what the changes are going to be if possible.

I agree.

> Not all changes can be predicted in a test run, though. This is a [known problem](https://github.com/saltstack/salt/issues/24938).

Yes, of course.

> 
> If the state is partially successful, I think that it is reasonable for the state to make changes until it fails, show the changes it has made, and then report the failure.

I agree.

> I don't know of any state that attempts to undo the changes it has made in the event of a failure.

It's good to know that there isn't an undocumented convention to roll back any changes before returning failure.

> Since a failure can occur at any point in the state, the logic for this could easily become very difficult and complex.

Very true, and in some cases it might not even be possible to roll back state changes.  So rolling back changes can't be a hard requirement, but I was wondering if it was a strong recommendation.  It sounds like it is up to the module authors to do whatever they think is best, which I think is good.

I thought of another question:

  * What should go in `'old'` if an item was created (or `'new'` if an item was deleted)?  Should the `'old'` (or `'new'`) key not exist in the dict?  Should it be mapped to `None`?  Should it be mapped to some other object that appropriately represents an absent item (e.g., empty string/list/dict if `'new'` is a string/list/dict)?

**Comment by jfindlay** [comment]
@richardhansen, I think that would be a decision made by the author of the state, but there could be a little more guidance as you suggest.  For an example, the `file.managed` function in this case only shows `New file`:
```yaml
----------
          ID: state_file
    Function: file.managed
        Name: /srv/salt/states.sls
      Result: True
     Comment: File /srv/salt/states.sls updated
     Started: 19:29:31.557424
    Duration: 8.687 ms
     Changes:   
              ----------
              diff:
                  New file
```
If you feel that any of the issues discussed here should added to and help elucidate the state writing documentation, then I can add the documentation label so that they are not forgotten.  For further reference I have also created #25143.

**Comment by rallytime** [comment]
@rhansen There is some documentation regarding what the expected returns should be when writing state modules [here](https://docs.saltstack.com/en/latest/ref/states/writing.html#return-data).

I think that mostly covers all of your questions. What goes in `old` and `new` as stated in the comment above largely depends on the functionality of the state. For example, when updating packages to the latest release, the state may contain and old package name that was replaced, and the new package name that it was upgraded to. If no package is found, the value is an empty string. Other states might be more complicated and contain entire dictionaries or lists inside `old` and `new`. 

I am going to close this for now, but if you'd like to discuss this further, or if you think those docs could use more clarifying information, please let us know!
