### ISSUE TITLE
Feature: manage standalone ESXi host with Salt Cloud 

### ISSUE THREAD

**Issue by ernescz** [saltstack/salt#26902]
For now `salt.cloud.clouds.vmware` module allows managing of ESXi hosts that are connected to a vCenter. It would be great if `salt.cloud.clouds.vmware` module could be enhanced to manage a single ESXi host without vCenter. 
 It could be used to handle virtual machines on the host, specifically - create/destroy machines, restart, take snapshots, shutdown/restart etc. Basically all actions that can be done with a virtual machine through vSphere client. If possible (this is secondary) managing ESXi host settings like local firewall rules etc. Of course some features would be useless like putting host in maintenance mode because there is only one physical host.
 
 I believe that there are many use cases where a standalone ESXi host is a better solution than full vCenter or bare-metal install, for example lab-testing setup, maybe specific solution that requires several virtual machines in mixed Linux/Windows environment or perhaps an internal security system without outside access with the benefit of virtualization. Also this could help on reducing licensing costs for vCenter.
 If I'm not mistaken then this could be achieved through salt-minion running on the host (preferable) or with salt-ssh. 
*(please tag with: feature, salt-cloud)*

**Comment by ssgward** [comment]
@ernescz - good idea. Thanks.

**Comment by alxbse** [comment]
In the current version the VMware driver requires a vCenter installation due to the fact that vms are created by cloning, an operation that is not supported on standalone ESX hosts. The driver uses the pyVmomi library which lists support for standalone hosts but sort of assumes that there is a vCenter installation available.

I'm interested in the possibility of using salt cloud and esxi without vcenter, I'll start by testing if creating vms without cloning is even possible in the pyVmomi library.

As far as I know it is not possible to install a salt-minon directly on an ESXi host, atleast not while remaining supported. All management should be via the official APIs.

**Comment by nesnub** [comment]
This feature would be of great interest to me as well. In way it would allow us to replicate part of the management functionality of vCenter (for free) with salt-cloud.

You may already be away of it, but VMWare Fusion 8 Pro (just released) now has integration with single-hosts-ESXi in a way we're talking about here. Looks quite nice so far. If the API is open it looks like it would be a good candidate for inspiration.

**Comment by rallytime** [comment]
Implemented in #27324

**Comment by rallytime** [comment]
@alxbse Thanks for the fix! Looks great so far.

@ernescz and/or @nesnub Can you give this implementation mentioned above a try? Feel free to close this if it is working for you.

**Comment by enver** [comment]
So after a few bumps I managed to get my request submitted, but I got "Operation not supported" error. I even used evaluation license to test and still did not get it to work. Did anyone managed to use this?

**Comment by ipsecguy** [comment]
Two years down the road, same error on creation. Is VM creation supposed to work on the free ESXi or not?
