### ISSUE TITLE
Manage Salt Cloud map files through GitFS

### ISSUE THREAD

**Issue by chopper** [saltstack/salt#26916]
It would be great to be able to manage all Salt Cloud files through GitFS, so that you can call

```
sudo salt-cloud -m salt://map.sls
```

**Comment by ssgward** [comment]
Great idea. Thanks.

**Comment by DanyC97** [comment]
+1

**Comment by aphor** [comment]
#2555 might cover this issue

**Comment by DanyC97** [comment]
@aphor why you think #2555 might cover this issue?

**Comment by aphor** [comment]
@DanyC97 if the suggestion I made on #2555 is implemented, or even anything that sanely fits the existing salt approach, the cloud config data will go in pillars which can already be rooted in gitfs.

**Comment by DanyC97** [comment]
@aphor thanks, let's hope it will be the case (though i'm a bit pessimistic due to lack of spot light on features vs bug squash)

**Comment by aphor** [comment]
Actually there are a few painful bugs reported in issues with salt-cloud managing VMs with ancillary configuration items like floating/EIPs, DNS records, extra cloud storage volumes. Salt cloud, IMHO, needs a redesign because of data model issues and a divergence from the way everything else in SaltStack works. This issue would be icing on the cake if that other stuff were addressed.

**Comment by DanyC97** [comment]
i doubt anyone will redesign Salt cloud and while i agree with you 100% i'd happily accept this small improvements... otherwise terraform from hashicorp can be an alternative imo.
