### ISSUE TITLE
Titles of Documenation Pages for SEO

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#26954]
When searching for grains, it is not clear to me from seeing a Google result whether the page is about "Targetting Minions".

Would it harm to add the super category to the title of the page?

https://www.google.de/search?q=salt+grains

**Comment by jfindlay** [comment]
@srkunze, that seems like it could be a good idea to me.  What do you think, @jacobhammons?

**Comment by jacobhammons** [comment]
I think this is a great idea, though I'm not sure if sphinx can do this since it probably requires some knowledge of the topic's position in the TOC. @whiteinge do you happen to know?

**Comment by whiteinge** [comment]
I can't think of a way to do this directly since a folder with an index.rst file isn't special in the Sphinx TOC hierarchy. We could add [metadata](http://sphinx-doc.org/markup/misc.html#metadata) to each page and make that available in the document title.

All that said, I think the best solution may just be replacing single-word top-level headings with more meaningful text as we come across them.

**Comment by srkunze** [comment]
> All that said, I think the best solution may just be replacing single-word top-level headings with more meaningful text as we come across them. E.g., "Grains" isn't terribly descriptive but "Targeting with Grains", or "How Grains are Generated", or "Salt's Default Grains" would be. That would also help users when browsing the TOC since it is quite long.

I would love that.

**Comment by srkunze** [comment]
Solved. :)
