### ISSUE TITLE
Netapi + eauth should allow another PAM service besides "login"

### ISSUE THREAD

**Issue by pcn** [saltstack/salt#26961]
This was discussed on the [salt-users google group](https://groups.google.com/forum/#!searchin/salt-users/netapi/salt-users/fRTGHDARrDE/HMLejTD1AAAJ).  I believe strongly that the salt-api needs to be able to be restricted to using a configured PAM service when a specific service is configured.  My case is that I want a local user to be created with a specific password that will be used for authentication.  I do not want other users to be able to be specified via an alternative auth backend/service.

I'll work on the PR for this, but I want to raise this as an issue based on the scenario I described in the thread in salt-users.

**Comment by whiteinge** [comment]
I'm looking forward to seeing what you come up with. Keep in mind it must be backward-compatible with the existing functionality -- or config-gated if that is not possible.

I strongly feel the right place for this is in Salt's eauth system rather than salt-api since salt-api is just a thin wrapper around Salt's public Python API. All the same eauth semantics that apply to salt-api also apply to the CLI via `salt -a <eauth>`. Let us know if we can assist navigating those waters.

**Comment by zerthimon** [comment]
+1, I'd like to have the possibility to configure a specific pam service just for salt (like other linux services, sshd, etc.)

**Comment by pcn** [comment]
Looks like this may have been obviated in https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-3176.  Can someone correct me if I'm wrong?

**Comment by whiteinge** [comment]
@pcn you are correct. The change happened in #31827. Thanks for updating this issue.

**Comment by zerthimon** [comment]
So is it possible to configure a specific pam service (besides login) which will be used to authenticate with ?

**Comment by whiteinge** [comment]
Yes, see the PR linked above for details but you can now put `auth.pam.service: login` in your master config.
