### ISSUE TITLE
Windows Minion installer allows multimaster

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#26990]
Currently I use
`Salt-Minion-2015.5.3-2-x86-Setup.exe /S /master=Foo`
to install a salt-minion that has Saltmaster "Foo".

It would like to install a salt-minion that has the **two** Saltmasters "Foo1" and "Foo2".

But when I tried
`Salt-Minion-2015.5.3-2-x86-Setup.exe /S /master=Foo1,Foo2`
it resulted (in file `c:/salt/conf/minion`) as the wrong entry

```
master: Foo1,Foo2 
```

while the correct entry is 

```
master: 
 - Foo1
 - Foo2
```

I kindly propose that the value of  `master` is parsed for , (colon) or ; (semicolon) and splitted into multiple masters.

**Comment by jfindlay** [comment]
@markuskramerIgitt, thanks for the report.

**Comment by rickh563** [comment]
ZD-1757

**Comment by twangboy** [comment]
## Handling config files and directories:
- Nullsoft Installer will detect an existing Config (`minion` file and/or `minion.d` directory)
- If existing config is NOT found, the Config page will be displayed
- If existing config is found, the user will be prompted to use the existing config or not (Yes/No)
- If Yes, the Config page will be skipped and salt will be installed without modifying existing config
- If No, the `minion` config file and the `minion.d` directory will be removed. The Config page will be displayed. All settings will be written to `salt/conf/minion`
- From the command line a new Switch will be added: `/UseExistingConfig=[1/0]` The default will be to use the existing config (`1`)

## Handling multimaster:
- User will be allowed to specify a single master or a multimaster setup on the Config page
- A single master will be specified by a single string without a comma. The output to the config file would be:
```
master: hostname
```
- Multiple masters would be specified using a comma delimited list. The output to the config file would be:
```
master:
  - hostname1
  - hostname2
```
- Using the command line will follow the same functionality. You will be able to pass multiple masters using a comma separated list (`/master=hostname1,hostname2`)

## Documentation
This will all need to be documented:
https://repo.saltstack.com/#windows
https://docs.saltstack.com/en/latest/topics/installation/windows.html

## Develop
Since this is a major change, it will go on the Develop branch and will not be available until the next major release.
