### ISSUE TITLE
Salt Master as single point of failure

### ISSUE THREAD

**Issue by ns-phennessy** [saltstack/salt#27088]
I've been searching for a while for someone talking about this, so far nothing. Maybe it's not a big issue as I seem to think it is.

I can't get over the idea that if my Saltmaster were to be compromised by a hacker, he would then have root-level access to potentially hundreds, if not thousands of servers running Saltminions, meaning that my Saltmaster would be a high profile target. Given that multiple admins might need to deliver changes with Salt, each person able to run Salt commands is a security risk. I know about Salt ACL's, but I don't believe that addresses the underlying issue.

Does Saltstack address this in any way? Is there an architecture that could mitigate this risk?

Sorry if this is wrong place to post; I couldn't find any kind of community discussion boards anywhere.

**Comment by jfindlay** [comment]
@ph7vc, these are good questions.  There is an [irc channel](irc://irc.freenode.net/#salt) and a google group called [salt-users](https://groups.google.com/forum/#!forum/salt-users) that you can also try.  There are multimaster features that can possibly be used in a solution designed to help prevent the issues you have listed:
https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html
https://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html

**Comment by ph7vc** [comment]
Thanks for the response @jfindlay! 

I'm hoping that talking about it might lead to the development of best practices for large scale infrastructure security.

**Comment by whiteinge** [comment]
@ph7vc you are very correct to identify the Salt Master as a high-priority target for attackers. How you best secure and harden that system will depend heavily on how you use Salt, where you use Salt, how your team is structured, where you get data from, and what kinds of access (internal and external) you require. It's great that you're thinking about this -- good security requires constant vigilance!

Here is some broad advice:

* Don't expose the Salt Master any more than you have to.
* Harden the machine as you would with any high-priority target.
* Keep the system patched and up-to-date.
* Use tight firewall rules.
* Restrict who can directly log into the machine.
* Keep close tabs on SSH keys (enforce your team uses SSH keys with passphrases) and any other login credentials you and your team need to gain access the machine.
* Use a hardened bastion server or a VPN to restrict direct access to the Salt Master from the internet.

Here is some broad Salt-specific advice:

* Subscribe to salt-users or salt-announce so you know when new Salt releases are cut. Keep your systems up-to-date with the latest patches.
* Use Salt's Client ACL system to avoid having to give out root access in order to run Salt commands.
* Use the ACL system to restrict which users can run what commands.
* Use external Pillar to pull data into Salt from external sources so that non-sysadmins (other teams, junior admins, developers, etc) can provide configuration data without needing access to the Salt Master.
* Make heavy use of SLS files that are version-controlled and go through a peer-review/code-review process before they're deployed and run in production. This is good advice even for "one-off" CLI commands because it helps mitigate typos and mistakes.
* Use salt-api, SSL, and restrict authentication with the external_auth system if you need to expose your Salt Master to external services. Again, make sure your system is fully patched and up-to-date.
* Make use of Salt's event system and reactor to allow minions to signal the master without requiring direct access to the master.
* Run the salt-master daemon as non-root.
* Disable which modules are loaded onto minions with the `disable_modules` setting. (I.e., disable the `cmd` module if it makes sense for you.)
* Look through the fully-commented sample master and minion config files. There are many knobs and dials for securing an installation available.
* Run Masterless-mode minions on particularly sensitive minions. There is also salt-ssh or the sudo module if you need to restrict a minion further.

Hopefully that gives you some ideas. We could benefit from a "Hardening Salt" addition to our documentation.

**Comment by ph7vc** [comment]
Excellent suggestions @whiteinge!

Along the lines of disabled modules; I would wonder if there is a way to output attempts to use disabled execution modules to log files, could be a low tech IDS for Salt, or could fit into an existing monitoring system; trigger security alerts, etc.

**Comment by whiteinge** [comment]
I think trying to run disabled modules does show up in the logs. I know trying to run modules that have been blacklisted via the ACL system write to the logs.

You're right about potentially re-enabling modules from the master. It's critically important to keep in mind when securing Salt which processes are running as root, who has access to said processes, and what the limitations on that access are. If someone has unfettered root access then sky's the limit, as you know. If someone has unfettered minion access then they also have root access on the minion. Disabling modules on the minion-side is useful when they don't have the kind of access required to re-enable it (though that setting is often used just to prevent accidents). Blacklisting modules and restricting users via the ACL system is a common way to lock things down from the master-side operations.

Weigh your team requirements and workflows against your exposed surface area and lock down everything that makes sense to lock down.
