### ISSUE TITLE
Saltcloud virtualbox provider

### ISSUE THREAD

**Issue by LoveIsGrief** [saltstack/salt#27089]
Hello everybody,

For those of us that don't have a cloud provider available, it would be nice to provision VirtualBox machines. This would come in handy to e.g test saltcloud before going live (my case) or simply having an environment on one machine.

As the guidelines says I'm asking for this before starting implementation as I haven't seen this implemented yet.

I'm looking forward to comments, suggestions and whatnot e.g if this fits in the philosophy of saltcloud.

Cheers

**Comment by ph7vc** [comment]
I usually use Vagrant spin up virtual machines, perhaps that would work for you?

**Comment by LoveIsGrief** [comment]
As far as I understand that would be if saltcloud isn't being used. Saltcloud doesn't seem to have a vagrant or virtualbox provider in order to manage VMs.

**Comment by jfindlay** [comment]
@LoveIsGrief, thanks for the report.  I think the typical salt approach with VM management software like virtualbox or qemu is to handle them with execution and state modules.  You may be able to get at least some of what you need by using the vbox_guest modules.  It doesn't look like they yet support full virtualbox functionality.

**Comment by LoveIsGrief** [comment]
Hi @jfindlay 

I was looking for the ability to call `salt-cloud --list-providers` and see virtualbox in the output. Of course with the same functionality as other providers e.g. define a provider config for virtualbox (for a local virtualbox hypervisor as well as a remote one) and profiles to later call create VMs according to these profiles.

The goal behind all this is be able to cheaply test a salt and salt-cloud configuration locally before pushing everything to different environments without the need for AWS, Azure, linode or any of the other providers.

Don't know if anybody else has started implementing the salt-cloud plugin but I have in [LoveIsGrief/saltcloud-virtualbox-provider](https://github.com/LoveIsGrief/saltcloud-virtualbox-provider)

**Comment by jfindlay** [comment]
@LoveIsGrief, from what I understand, that means you have virtualbox configured somewhere under `/etc/salt/cloud.providers.d/` even though salt-cloud does not support it yet. I am looking forward to your pull request though. :-)

**Comment by DanyC97** [comment]
@jfindlay i'm curious - how you guys test salt-cloud ? i find it very hard to test it w/o having a virtualbox provider (every other provider adds additional dependencies/ costs)

**Comment by LoveIsGrief** [comment]
That's exactly what I'm struggling with right now. I have only been able to do manual tests of salt-cloud. Still trying to find a way to write proper unit tests.

**Comment by rallytime** [comment]
@DanyC97 and @LoveIsGrief We need to write more unit tests for salt cloud. Those should be easy to add to the test suite as they should be using mock data to test against.

We have some integration tests that [run nightly](https://jenkins.saltstack.com/view/Cloud%20Nightly/) on our Jenkins installation. These run on a nightly basis because of the cost factors you're describing. The code for these tests is located in `salt/tests/integration/cloud/providers/` if you want to see how we're doing it.

**Comment by DanyC97** [comment]
@rallytime thanks for feedback, appreciated!
However i hope you guys won't give up on vbox driver :)

**Comment by rallytime** [comment]
Nope! Still a great feature request. We just haven't had time to tackle to many features since we're working on getting the bug count down first.

**Comment by DanyC97** [comment]
@rallytime fair point

**Comment by LoveIsGrief** [comment]
# `--list-images` and `--query`

While implementing this, I noticed that virtualbox doesn't have templates per se. Therefore I'm not sure if the [`avail_images()`](https://docs.saltstack.com/en/latest/topics/cloud/cloud.html#the-avail-images-function) should be implemented. So far it has the same implementation as the [`list_nodes()`](https://docs.saltstack.com/en/latest/topics/cloud/cloud.html#the-list-nodes-function), which simply lists all VMs known to the virtualbox hypervisor.

Is the `salt-cloud --list-images my-cloud-provider` function absolutely necessary? Or can it simply be ignored? And what about `--query` ?

# Remote hypervisors

I'm not sure this version will be able to support remote hypervisors. I don't have any other machines and am not sure if I can go inception-style and install virtualbox in a guest and target it. I wouldn't know how to put that into the integration tests.

# Full integration tests

That brings me to **templates in integration testing**. So far the way I'm testing is by creating a VM on the fly for the tests. The VM doesn't have a HD or any data and is basically just an empty husk. To do full testing one would need a running VM with an installed OS for e.g testing deployment scripts.

It would be bonkers to add a VM file in the repo, so I'm thinking of using vagrant to provide template VMs. My question is should I go that far? This could significantly increase testing time for full integration testing. I don't know if there's a CI for the project...

**Comment by techhat** [comment]
Sorry to come so late to the party.
Hi @LoveIsGrief. You can skip `--list-images` if it's not appropriate, so long as you clearly document what is needed to accomplish that task. However, I would consider the `--query` options to be critical to Salt Cloud; every operation performs that query on each configured provider, in order to assess what the environment looks like. This lets it know what machines already exist and can be managed, as well as which machine names are already being used by other instances.
As for remote hypervisors, everything that Salt Cloud manages should be remote. If disparate remote endpoints cannot be logically connected to each other, then they can be configured as separate providers.
As you've already said, Salt Cloud shouldn't be used for local hypervisors. If what you're trying to manage is local in nature, then the `virt` execution module should be used instead.
I believe VirtualBox is supported by libvirt, which is in large part what the `virt` module uses. If you put `salt-api` in front of a machine that can manage libvirt via salt-virt, then you have a web API that can be used by Salt Cloud. `virt.list_domains` can be used for `--query`. I don't see anything in there to cover for `--list-images`, but like I said, you can skip that if necessary.

**Comment by LoveIsGrief** [comment]
Hi @techhat 

Thanks for joining the party :) I'll try and document as much as possible what I have done.

Thanks for making me aware of `virt`. It does look interesting, however I'm not sure it suits my needs as `salt-cloud` does (I might be wrong of course). Specifically testing configurations in multiple environments e.g having multiple test environments that create their own VMs from the map files in `salt-cloud`. A simple change to the map file would change the test environments. Furthermore developers would be able to simulate the test environments (which actually simulate production very closely) locally.

Simple use-case: it has been decided to use a tech that will necessitate a new machine on production. We cannot simply start making changes to pre-production, so a developer wants to start testing this change locally. Using `salt-cloud` a migration could possibly be 3 steps in the salt orchestration: premigration actions, migration ( salt-cloud map -> spin up new vm, new salt minion, key exchange, yada yada), postmigration actions.  
If I understand this correctly, using `virt` would force one to write different states for dev and production environments.

Maybe the next question is dumb, but would a salt cloud virtualbox-provider even be considered for a merge given that it can also create VMs on the local host? I see an LXC provider, so I assume it shouldn't be a problem.

**Comment by UtahDave** [comment]
We would definitely welcome a virtualbox provider. In fact, I would use it myself!  :)

**Comment by rallytime** [comment]
The virtualbox cloud driver was added a couple of months ago:
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/virtualbox.py
