### ISSUE TITLE
Data sharing (grains/values/files) between minions and salt-master

### ISSUE THREAD

**Issue by Semyazz** [saltstack/salt#27156]
How should I share data generated on minions between themselves? I mean here grains, files or output of different commands generated on minions during SLS's execution.

The easiest case is an IP address. For instance I want to provision `Minion-01` using `minion-01.sls` and after that I'd like to obtain it's IP address and pass it to `Minion-02` and to it's `minion-02.sls`, so I can use that IP (variable) in jinja templates. I'd like to do something like `{{ salt['grains.get']('minion-01','fqdn_ip4') }}` to obtain that in `minion-01.sls`

Should I use grains for that? if yes then how can I access `minion01`'s grains in `minion-02.sls` which is executed on `Minion-02`

Should I use pillars here? But how can I generate a dynamic pillar value on salt-master injected to pillar visible to `Minion-02` based on for instance grains from `Minion-01`

Generally I don't want to be restricted to values in Grains only. I want also for instance generate some files or whole directories trees (or tar/gzip) on one minion and after that process is done, pass it to another minion's SLS. Basically I'm curious how I should implement a messages passing solution between minions through salt-master or between themselves. Preferable it should be a secure values/files transfer, so I can limit who can send data to whom. So no sensitive data will leak to unprivileged minions.

**Comment by jfindlay** [comment]
@Semyazz, I am not an expert on advanced salt setups, but if I needed to do something that involves interaction between minions I would use the [orchestrate runner](https://docs.saltstack.com/en/latest/topics/tutorials/states_pt5.html#orchestrate-runner).  You could also look at the [reactor](https://docs.saltstack.com/en/latest/topics/reactor/) to perform event-based management, and the [peer](https://docs.saltstack.com/en/latest/ref/peer.html) system if you want the minions to communicate directly with each other.

**Comment by mpease-ascend** [comment]
Me too... would love to have an answer to this. Two days so far of the typical "google the heck out of it", no results.

**Comment by whiteinge** [comment]
For sharing data between minions you definitely want [Salt Mine](https://docs.saltstack.com/en/latest/topics/mine/). It caches the return from any arbitrary command, runs it on a regular interval, and makes the result available to all minions.

To share files you can use the [cp.push](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.push) and `cp.push_dir` commands to push files from a minion to the master, then the master can push those files to other minions. If you do this frequently you might also want to look into the [minionfs fileserver backend](https://docs.saltstack.com/en/latest/topics/tutorials/minionfs.html#tutorial-minionfs) which provides some conveniences around this workflow. Often, I'll fire a custom event after pushing a file to the master in order to notify the master the file is ready so the Reactor can automatically push it to other minions from there.

**Comment by Ch3LL** [comment]
@Semyazz has your question been answered? Are you okay to close this issue?
