### ISSUE TITLE
Simplify/remove salt.utils.http

### ISSUE THREAD

**Issue by jacksontj** [saltstack/salt#27405]
cc: @techhat @terminalmage 

Previously salt.utils.http was introduced to work around dependancy problems (since we didn't want to add a hard dep to a single http lib). With 2015.8 we require tornado-- and the backend has been added to the library. Now that we require tornado (which has a full featured http client) I'm of the opinion that we should at least simplify salt.utils.http to only support a tornado backend, or remove the library all together.

Thoughts? I'm relatively new to this utils library, but from a quick look it doesn't seem to do much more than make a few versions of http libraries compatible-ish :)

**Comment by techhat** [comment]
The big thing that I use the library for is simplifying API calls, since it can decode JSON and XML automagically for me. We've since also added functions for managing certificates, cookies (since Tornado's client is not in fact full-featured and doesn't do cookies), and sanitizing URLs.

I don't think we're ready to get rid of the library yet. But I would like to simplify the `query()` function.
