### ISSUE TITLE
URL scheme for Ubuntu repositories is suboptimal

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#27542]
Much like the Debian repository layout discussed in #27041 the scheme chosen for Ubuntu suffers from *exactly* the same problem.

We now have:

```
precise   → $BASE_URL/apt/ubuntu12/dists/precise/
trusty    → $BASE_URL/apt/ubuntu14/dists/trusty/
                          ^^^^^^^^
```

which is neither necessary nor helpful. Just use `$BASE_URL/apt/ubuntu/dists/$DIST/` and be done with it.

**Comment by jfindlay** [comment]
@babilen, thanks for the report.

**Comment by dmurphy18** [comment]
@babilen I understand the sub-optimal layout for Ubuntu 12.04 and 14.04, however it was the layout decided upon after discussion, given time constraints. Hopefully this can be adjusted in the future, once the time constraints have been reduced

**Comment by richardhansen** [comment]
Even better would be to consolidate the Debian and Ubuntu repos into a single URL.  From [my comment](https://github.com/saltstack/salt/issues/27159#issuecomment-143074521) in issue #27159:

> I recommend [eliminating] the `debian` and `ubuntu` subdirectories (just put everything under `/apt`).  For example, Debian Jessie users would do the following:
>
>     deb http://repo.saltstack.com/apt jessie main
>
> while Ubuntu Trusty users would do this:
>
>     deb http://repo.saltstack.com/apt trusty main
>
> The `jessie` and `trusty` disambiguate the files, allowing them to peacefully coexist within the same base URL.  For compatibility you can add `debian` and `ubuntu` symlinks that just point to `.`.
>
> Advantages of laying out the repository this way:
>   * it's easier to script—just use `$(lsb_release -sc)` or `{{grains.oscodename}}` and it'll work regardless of whether you're using Debian, Ubuntu, or Mint (assuming the repo has packages available for the machine's distribution and release)
>   * it avoids duplicate tarballs between the repos
>   * if a new distribution/release is compatible with another, you can simply drop a symlink in the `dists` subdirectory to support the new distribution/release (e.g., you can instantly support Mint 17.3 users by creating a symlink named `rosa` pointed at `trusty`, assuming the `trusty` packages seamlessly work on Mint 17.3)
>
> Useful links:
>   * https://wiki.debian.org/RepositoryFormat 
>   * https://www.debian-administration.org/article/286/Setting_up_your_own_APT_repository_with_upload_support

**Comment by richardhansen** [comment]
In [a comment](https://github.com/saltstack/salt/issues/27159#issuecomment-143077444) in issue #27159, @jfindlay wrote:
> We're working on just getting the repos and packages out and then publishing the state files we use to generate them. At that point you will be able to read over the states themselves and submit pull requests, not that you'll have to submit feedback that way, but we're hoping that this will ultimately make packaging more transparent and more of a community effort.

Have the state files used to generate the repos been published anywhere?  I would like to help fix this.

**Comment by jfindlay** [comment]
@richardhansen, https://github.com/saltstack/salt-pkg-tests.

**Comment by dmurphy18** [comment]
@richardhansen There is a need for multiple repo's due to the need to
provide different versions of the Salt packages,
for example: salt v2015.5.6 and v2015.8.0. But a repo cannot have two
versions of the same package for the same architecture,

see
http://anonscm.debian.org/gitweb/?p=mirrorer/reprepro.git;a=blob_plain;hb=HEAD;f=docs/FAQ
Question 3.1

This would be a problem with what you suggest, since the FAQ implies we
would need to incorporate a version in the paths to the repositories for
each release. Similar issues would occur for the dependencies that the
different versions for Salt packages use.

If there is a way to mitigate this, I have been unable to find it, but
would welcome any advice or suggestions.

David Murphy
Unix Engineer
SaltStack

3400 North Ashton Blvd., Suite 110 | Lehi, UT 84043, USA

office 801-207-7440 | mobile 385-333-1060
dmurphy@saltstack.com |  www.saltstack.com
*SaltConf16 - Salt Lake City - April 19-21, 2016​ - www.saltconf.com
<http://www.saltconf.com/>​*

**Comment by richardhansen** [comment]
@dmurphy18,

> But a repo cannot have two versions of the same package for the same architecture

The repo format does support multiple versions in the same repo.  From [the repository format docs](https://wiki.debian.org/RepositoryFormat#Duplicate_Packages):

> A Packages index may contain multiple versions of one binary package, for the same architecture and/or multiple architectures (that is, `all` and the native architecture). In the official Debian archive, this is used to keep around old versions of an `Architecture: all` package that is still needed by the other packages.

It sounds like the limitation is with the reprepro tool itself.

Regardless, putting multiple versions of Salt in the same suite-type-component-architecture tuple isn't the right way to support multiple versions, as it requires users to use the little-known and somewhat complicated apt pinning feature to select the non-latest version.

> the FAQ implies we would need to incorporate a version in the paths to the repositories for each release.

That's how people offer multiple versions at the same time with Ubuntu PPAs.  For example, there are three versions of Git offered by the [git-core team](https://launchpad.net/~git-core):

  * http://ppa.launchpad.net/git-core/ppa/ubuntu for the latest release
  * http://ppa.launchpad.net/git-core/candidate/ubuntu to also get release candidates
  * http://ppa.launchpad.net/git-core/v1.8/ubuntu for the old v1.8.x versions

However, because you run your own repository that you can configure however you want, it's probably better to separate the versions via components:

    deb http://repo.saltstack.com/apt trusty stable        # latest release
    deb http://repo.saltstack.com/apt trusty daily         # nightly build of develop branch
    deb http://repo.saltstack.com/apt trusty 2015.5        # latest 2015.5 release
    deb http://repo.saltstack.com/apt trusty 2015.5-daily  # nightly build of 2015.5 branch
    deb http://repo.saltstack.com/apt trusty 2015.8        # latest 2015.8 release
    deb http://repo.saltstack.com/apt trusty 2015.8-daily  # nightly build of 2015.8 branch
    etc.

This approach should be supported by reprepro.

**Comment by dmurphy18** [comment]
@richardhansen Thanks for the advice and ideas, I shall take a deeper look
at this.

David Murphy
Unix Engineer
SaltStack

3400 North Ashton Blvd., Suite 110 | Lehi, UT 84043, USA

office 801-207-7440 | mobile 385-333-1060
dmurphy@saltstack.com |  www.saltstack.com
*SaltConf16 - Salt Lake City - April 19-21, 2016​ - www.saltconf.com
<http://www.saltconf.com/>​*

**Comment by dmurphy18** [comment]
@babilen now that you have salt-pack, and can make suggestions or see better ways to fix how the packages are built, can this issue be closed ?

**Comment by babilen** [comment]
Well, it can be more easily addressed by the community, but it is still valid. It would, IMHO, still make sense to use distributions (in the apt sense) more as suggested by @rhansen. Not sure if I necessarily want to mix Ubuntu and Debian in the same repository, but to a certain degree that decision is simply cosmetically.

A distribution scheme as detailed on http://debian.saltstack.com/ is still a great idea.

**Comment by dmurphy18** [comment]
@babilen I understand from a developer's point of view, codename for the distribution is easy, but for consumer's it is Ubuntu 14.04.  It would be great to accommodate both in some fashion. I was hoping that we could possibly do with symbolic links.

I think keeping Debian and Ubuntu separate is better, if only because of the different schemes used, Debian (Stable, Testing, Experimental, etc.) and Ubuntu (main, contrib, universe, etc).  I liked the scheme in debian.saltstack.com for the particular versions of Salt, but we are now also providing the dependencies too, hence that didn't seem as appropriate as for just the Salt packages.

One of the other issues mentioned internally, was the issue of mirroring Debian/Ubuntu repo's where some of them maintain versions which are considerably   
end-of-life'd, thus delaying replication completion (taking forever to finish), costs, amount of disk space (I know it is cheap, but still have to wade through it), and the desire to limit to just those in active use.

I am all for community support in making this better and what fulfills their needs, is what should drive how the repo should function, both for Redhat/Centos, Debian/Ubuntu, Freebsd and other communities, noting that different communities have different needs which may conflict at times.

Having been building packages for the last two months, I have not had time to adequately improve the infrastructure architecture as I would have wished.  Perhaps with the community now able to improve it, we can get it to a state which satisfies their needs better.

**Comment by dmurphy18** [comment]
@babilen Can this issue be closed, now that the community has access to salt-pack and can improve how packages are built.

**Comment by babilen** [comment]
@dmurphy18 It might make sense to move it over to salt-pack, but the issue is still valid, isn't it?

**Comment by rallytime** [comment]
@babilen If this issue is still present, but is more pertinent to salt-pack, then I think it makes sense to move it there.

**Comment by dmurphy18** [comment]
@babilen I have been thinking about this and wanted to get your ideas on the following scheme, using debain.saltstack.com as a guide. All of the following symbolic links start from the repo.saltstack.com/apt area:

jessie-saltstack -> http://repo.saltstack.com/apt/debian/8/amd64/latest
jessie-saltstack-2016-03 -> http://repo.saltstack.com/apt/debian/8/amd64/2016.3
jessie-saltstack-2015-08 -> http://repo.saltstack.com/apt/debian/8/amd64/2015.8
jessie-saltstack-2015-05 -> http://repo.saltstack.com/apt/debian/8/amd64/2015.5

Similarly for xenial, trusty, precise.  wheezy is EOL'd and while we could add wheezy too, do not wan tot encourage its use.

A problem I have with the above is that it does not allow for architecture or 64|32 bitness (still hoping to eventually fix that support) in the path, noting that debian url has their support under main etc.
