### ISSUE TITLE
The salt-bootstrap script installs old version

### ISSUE THREAD

**Issue by edwardsgs** [saltstack/salt#27553]
If I go through the process on page: https://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html and use the bootstrap script I wind up with an older version of SaltStack, 2015.5.2.

I have to install directly from the repo to get the current release, 2015.8.0. 

I'm installing on CentOS 6.6

**Comment by Ch3LL** [comment]
@edwardsgs thanks for reporting the issue. Would you mind re-opening this issue at https://github.com/saltstack/salt-bootstrap

**Comment by rallytime** [comment]
This is somewhat "expected behavior". The bootstrap script, by default, should install the latest release available in the repo, which for CentsOS 6, is our [COPR repo](https://copr.fedoraproject.org/coprs/saltstack/salt/) where the "current release" is 2015.5.2, which of course is behind our 2015.8.0 release. The fix should be for the bootstrap script should point to our new package repo, http://repo.saltstack.com, instead.

I've filed https://github.com/saltstack/salt-bootstrap/issues/668 to track this in the salt-bootstrap repository.

As such, I am going to go ahead and close this issue here so we can track the issue in salt-bootstrap. Thanks for letting us know @edwardsgs!

If you want to install 2015.8.0, you can pass `git v2015.8.0` to your bootstrap command and it will install the correct version from the git tag instead of from the COPR repo.

FYI @dmurphy18
