### ISSUE TITLE
git.latest seems to ignore the user argument in 2015.8

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#27703]
Since the upgrade to 2015.8 the user argument to git.latest doesn't make the state use the user's .ssh/id_rsa credentials and clones fail with permission denied. Adding in the identity argument is a workaround, but it would be nice if the user arg wasn't broken.

**Comment by SunPowered** [comment]
+1 I just ran into this.  

Although at first it appeared as though the `user` argument in the `git.latest` state was being ignored,  I noticed in my minion logs that the error actually occurs at the following cmd:

`git ls-remote <repo_url>`

which polls the repository for revision information.  This command was being run by root (or the salt minion user) in directory, `/root`.  

When the root user's SSH creds are included in the repository deployment keys, the state runs without error, even cloning the repository as the expected user.  

I think the bug is `git.latest` not running all git commands on the repository as the desired user.

**Comment by jfindlay** [comment]
@ryan-lane, @SunPowered, thanks for the report.

@terminalmage

**Comment by terminalmage** [comment]
@SunPowered Can you post the relevant minion logging?

**Comment by terminalmage** [comment]
Nevermind, I reproduced the issue and have submitted a fix in https://github.com/saltstack/salt/pull/27799. Sorry guys, thanks for reporting.

**Comment by terminalmage** [comment]
Fix was merged, closing.
