### ISSUE TITLE
Pin minions to pillar environments

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#27709]
I can't figure out how to do this, so I'm listing this as a "It'd be nice to have..".

We plan on having several organizations using the same salt-master to do their work, but within a multi-tenant environment, we need to make sure that groupA isn't affecting groupB's servers.

Some of this is ACLs and which hosts certain groups can issue commands on, but other parts ( namely pillars ) don't seem to have any 'walls' that we can slide in place.

We can certainly do something like:

```
pillar_roots:
  - groupA:
    - /srv/pillar/groupA
  - groupB:
    - /srv/pillar/groupB
```

And then allow groupA access to the /srv/pillar/groupA folder, same for groupB.

But, it seems with pillar data, if some engineer accidentally ends up targeting '*' in any of those pillar SLS files in his/her environment, it affects every minion, even minions that are environment pinned in the minion config.  Obviously, there are some other ways to try and negate this ( education, linting, code reviews or an ext_pillar that handles it.. ), but it'd be nice if there was some way to restrict the pillar data a minion got based on environment.  It seems the file_root stuff has this capability, but not the pillar.

**Comment by babilen** [comment]
I think your main problem is that you've chosen a suboptimal design for your infrastructure as it would, probably, make more sense to use one master per distinct tenant. You can use syndics for this if you still want to have a single master to sit on top of all of this.

**Comment by sjmh** [comment]
@babilen - that's a rather broad stroke to paint with, but, since you asked...

We, in fact, did consider going with a per BU salt-master pair.  But, at last count, we have approx ~150 BUs.  I don't have budget for 300 salt-masters, nor would I want to manage that many.  Normally, BU's pay for their own servers, but that's more in the case of 'I want to use this', where as this is more of the 'You have to use this'.  Lastly, often times BU's share infrastructure, so even if we got the BU's to buy their own servers, the BU's may make a deal to share the servers - which leads us right back to a multi-tenancy issue.

As I said, this would be a 'nice to have'.  You can already pin a minion to an environment for the file server.  You can restrict what minions a user can touch.  It'd be nice to extend this separation to pillar data and have some way of restricting what minions a user can shove pillar data onto.  Not a game-breaker by any means, but still something we'd find useful in our environment.

**Comment by basepi** [comment]
All pillar compilation is master side. The fileserver stuff you're talking about is a minion side config, that the minion chooses to obey. If we implemented some sort of environment control on the master side for pillar, what would that look like? A dictionary full of minion names and assigned environments? I could potentially see supporting something like this, so that topfile editing wouldn't be as dangerous (though the topfile editing would be more restricted). Just curious what it looks like in your mind.

**Comment by sjmh** [comment]
@basepi - that's a good question.

The answer may be that instead of trying to fix it for pillars, and then using a combination of environment fileserver pinning, a pillar solution, and ACL's for hosts, to instead look at the larger picture of how to implement true separation between different customers on the same salt server and I think that probably requires another level of abstraction on top of the 'environment' idea.

Something along the lines of a 'org' or 'customer', where targeting is namespaced.  So for CustomerX, 'salt \*' really means 'all minions belonging to CustomerX', as well as any targeting in state or pillar files.

I realize that's a bigger scope than just pinning pillar data, but it may end up being a better solution, rather than trying to cobble together multi-tenancy with ACL's, environment pinning and pillar hacks.

In any case, regarding the pillar stuff - perhaps some way of doing subtargeting within pillar?  For instance, we use a 'org' grain to do the ACLs.  If we could borrow that and do something like:

/etc/salt/master
```
pillar_orgs:
  base:
    - 'G:org:customerx':
      - /srv/pillar/customerx
    - 'G:org:customery':
      - /srv/pillar/customery
```

And they could create their own top files within their own directory, but it would actually create a compound matcher with the matchers from pillar_orgs ( and if they specify * in the sub-targets, just toss it out, since 'G:org:<orgname>' would match everything in their org anyways. )

/srv/pillar/customerx/top.sls:

```
base:
   '*':
    - common
   'web*':
    - customerxweb
```

Thoughts?

**Comment by basepi** [comment]
One thing I'll note right off the bat is that because grains are minion-controlled, targeting sensitive data by grains other than `id` is technically insecure. A compromised minion which knows the name of one of your other customers could get data it's not supposed to get.

Your suggested syntax is interesting, and probably would work. We could do it in such a way that for a given minion, the master would check the rules in order, and take the first one it found for a minion (this way you could have fall-through for default data). It's an abstraction on top of existing environments.....

I think likely we would use existing environments.

```
pillar_orgs:
  - 'G:org:customerx':
    - customerx
  - 'G:org:customery':
    - customery
  - '*':
    - base
```

However, I'm unsure of the amount of work this would take, and have to admit this will likely not be on our radar for a little while. (Tons of open bug work that takes priority over most feature work)

**Comment by basepi** [comment]
Oh, and I didn't address your larger idea. It is a decent one, though one that is already accomplished for many people using syndics. But it would be nice to be able to have such separation on a single master. It would just be a huge architectural change...

**Comment by sjmh** [comment]
@basepi - that's a good point ( re: compromised minion ).  I suggested the 'org' grain because that's what we use to control the ACL's for users via AD groups, since pillar data doesn't work so hot with ACL's ( in that you can't target subsets of the pillar match ).

But, if we had some external pillar that we were using for the targeting, I think that should still work ( as long as the external pillar is evaluated before this )?

Totally understand about the timeline ( bugfixes yay! :) ) and I wouldn't mind taking a crack at this myself.  I'm rather new to the codebase but a pointer in the general direction ( ie - where does the target expansion stuff happen master-side ) could help a lot to get that started.

**Comment by basepi** [comment]
I think `salt/pillar/__init__.py` will be a good place to start. That's the entry point for pillar compilation, IIRC.

**Comment by babilen** [comment]
I like the ability to build more security into the setup of a multi-tenant master, but am not sure if it really is a good idea to target pillars (which *will* contain security relevant information) by information  the master can't trust. In particular grains are a problematic choice, in that they are not secure and a compromised minion could alter them in order to gain access to restricted information.

The idea of external pillar or, as suggested in #23910, static pillars would make this viable however.
