### ISSUE TITLE
Custom execution module cannot access salt__ and __grains__ from certain places

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#27784]
Following the 2015.0 release, a custom execution module that uses dunder grains or dunder salt in certain places will fail as those are no longer made available.

**Scenario 1**
Accessing dunder grains in the top-level of the module used to work in 2014.7 but now fails in 2015.0 and above.

*my_test.py*
```
# This fails now but used to work
host = __grains__['host']

def my_func():
    # This works as expected
    host = __grains__['host']

    # This also works as expected
    data = __salt__['pillar.get']('dummy_key', None)

    return data
```

**Scenario 2**
Accessing dunder grains or dunder salt from within a module imported by custom execution module used to work in 2014.7 but now fails in 2015.0 and above.

For example, if an execution module shares a common core with a command-line wrapper script then the included module needs to know if it is running under salt or not. This used to be possible using a try/except placed at the top of the module which accesses the dunder grains data but now it always thinks it is not under salt as it cannot access that data.

*my_test.py*
```
import my_test_core

def my_func():
    # This fails as jph_test_core fails to load
    data = my_test_core.execute()

    return data
```
*my_test_core.py*
```
# This sets UNDER_SALT=False every time as __grains__ is not available.
UNDER_SALT = True
try:
    __grains__['host']
except:
    import socket
    UNDER_SALT = False

def execute():
    # This fails with "NameError: global name '__salt__' is not defined"
    data = __salt__['pillar.get']('dummy_key', None)

    return data
```

The above has broken backwards compatibility with our custom execution scripts and means we are stuck at 2014.7 until a fix or workaround is made available.

**Comment by jfindlay** [comment]
@Tanoti, thanks for the report.

**Comment by fphhotchips** [comment]
Adding to this - and I'm not sure whether this is *exactly* the same - but it seems close. 

When I have a module that sits directly under /_modules/, __grains__ and __salt__ behave as described by @Tanoti. However, when they sit in a subfolder (and are imported into  __init__.py - otherwise they aren't available), __grains__ and __salt__ are never defined, even inside the called function.

**Comment by DmitryKuzmenko** [comment]
@Tanoti thank you for report.

A few words about how Salt loader works. When you've ask salt to run a module modules loader finds the module in modules directory and loads with the following steps:
1. Load module. Module global context is initialized here, all global variables are set.
2. Init module injecting salt context data including: ```__pillar__``` and ```__grains__``` dicts and ```__salt__``` loader instance allowing to call other module functions.
3. Call module ```__init__(opts)``` function if exists. Here ```opts``` contains minion configuration dict.
4. Process ```__virtual__()``` function if exists.
Most of this information is described in the doc: https://docs.saltstack.com/en/latest/ref/modules/index.html

**Scenario 1**
If it's implemented exactly as you've described it wouldn't work and wasn't ever work in salt. It's because as I described on 1st step loader loads the module and python initializes globals. At this step no grains data injected and you are getting NameError.
***Fix***
Init globals in the module init function:
_my_test.py_
```python
# Declare global
host = None

def __init__(opts):
    # Init global
    global host
    host = __grains__['host']

def my_func():
    # Use global
    return host
```

**Scenario 2**
I see two points here.
1. Use a module using ```__grains__``` from another module. Salt way to do this is don not import the module directly but instead call it using salt loader that will inject the globals.
2. Detect if the module run by salt. This could be done with ```__init__``` function.
***Fix***
*my_test.py*
```python
def my_func():
    # Call module function with salt loader
    data = __salt__['my_test_core.execute']()
    return data
```
*my_test_core.py*
```python
# We're not under salt unless __init__ will be called after module load
UNDER_SALT = False

def __init__(opts):
    UNDER_SALT = True

def execute():
    if UNDER_SALT:
        host = __grains__['host']
        data = __salt__['pillar.get']('dummy_key', None)
    else:
        import socket
        data = do_job_standalone()
    return data
```

**Scenario 3** by @fphhotchips 
Two points here:
1. As I said to keep salt flavor let salt loader to import and init modules and run functions using ```__salt__```.
2. Regarding modules file layout you have the following options. Here ```my_test``` is the module name and ```my_func``` is a function name, so it will be called as ```__salt__['my_test.my_func']()```:
  * Standard module layout: implement ```my_func()``` in a file named ```my_test.py``` and place it into ```salt/modules/``` direcotry.
  * Module subdirectories: implement ```my_func()``` in a file named ```__init__.py``` and place it into ```salt/modules/my_test/``` directory
  * Custom module direcotries: implement ```my_func()``` in any of the above ways and place somewhere you want, say ```/srv/salt_custom_mods/my_test.py``` or ```/opt/salt_custom_mods/my_test/__init__.py``` and set ```module_dirs``` config parameter in minion config:
```yaml
module_dirs:
    - /var/lib/salt/modules
    - /opt/salt_custom_mods
```
Anyway modules naming structure has the only 2 levels: <mod_name>.<function_name>

**Comment by DmitryKuzmenko** [comment]
**TODO:** Salt Execution Modules documentation that is here
https://docs.saltstack.com/en/develop/ref/modules/index.html
lacks information about ```__init__(opts)``` function. Has to be updated.

**Comment by Tanoti** [comment]
Dmitry, thanks for the information as I now understand better how a module should be used under Salt. I have implemented the UNDER_SALT example above with it being set in the init function but I had to declare it as global in both the init and the functions where it was used for it to be seen.

**Comment by DmitryKuzmenko** [comment]
@Tanoti right! Just with a note: you have to declare global only if you assign the variable, it doesn't required to read.
There was a missing global in the sample with UNDER_SALT in my examples. I've just updated the code.
