### ISSUE TITLE
Salt-cloud doesn't wait long enough

### ISSUE THREAD

**Issue by EDanee** [saltstack/salt#27836]
Hi!

I just started to use salt and salt-cloud and I run into an issue that I can't solve.
I use DigitalOcean as a provider and very often I get the following error during the VM creation:
Too much failures occurred while waiting for the IP address

In these cases it really takes more time for DO to create the VM but I want salt to wait for it anyway.

Is there a way to increase the number of tries?

I tried to add some options to the /etc/salt/cloud file like:

``` salt
 wait_for_ip_timeout: 600
```

But it did not help.

Thanks!

```
salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by rallytime** [comment]
@EDanee Hrm. I feel like digital ocean is usually pretty speedy when it comes to initially deploying a VM. Are you deploying many VMs (via a map file or something) at once?

Also, can you tell us more about your cloud configs? Specifically, do you know if you're using the `digital_ocean.py` driver or the `digital_ocean_v2.py` driver? 

If you run your provisioning command with `-l debug` does anything interesting pop up in there? I think the `Too much failures occurred while waiting for the IP address` line could be indicating something going wrong somewhere in the process before you're actually hitting the timeout limit.

**Comment by EDanee** [comment]
Hi!

Thanks for the reply!
I'll have to collect the details but I think I'm using the older DO driver.
The reason: I'm 2015.5.3 and in the salt-cloud config I have to user the provider parameter instead of driver.
How can I check for sure which version I'm using?
I'll try to post the debug logs soon.

**Comment by rallytime** [comment]
I ask about the drivers because Digital Ocean is removing support for their original API on November first. So, in the 2015.5.x releases there are two salt-cloud drivers listed in `salt/cloud/clouds/`. The first is `digital_ocean.py` which supports DO's APIv1. You can find docs for those [here](https://docs.saltstack.com/en/2015.5/ref/clouds/all/salt.cloud.clouds.digital_ocean.html#module-salt.cloud.clouds.digital_ocean). The second is `digital_ocean_v2.py` which supports DO's APIv2. Docs for those are found [here(https://docs.saltstack.com/en/2015.5/topics/cloud/digitalocean.html#getting-started-with-digitalocean).

I think the easiest way to tell which one you're using is to compare the settings you have in your salt-cloud provider configs to the ones required in the various docs. If you set this up on a version of salt before 2015.5.0 was released, you're likely on the first/original driver.

**Comment by aphor** [comment]
IMO, if DO takes too long to spin up a VM, you might be deploying to overloaded infrastructure. FWIW, I would expect better results from failing the first slow VM creation attempt in a reasonably short time and retrying soon afterwards. I've built out clusters for testing load testing scripts and had crazy discrepancies (averaged over several minutes) between the performance of one identically sized cluster node vs. another deployed to a different VM host.

**Comment by aphor** [comment]
OP was having problems using the old DO cloud driver.
@EDanee did the new v2 DO driver clear up the problem?

**Comment by aphor** [comment]
Unless you can reconfirm @EDanee, with recent code, This should be closed.

**Comment by EDanee** [comment]
Hi guys,

I have to admit I totally forgot about this issue. Sorry about that!
As I have no such issue with the newer DO driver, I'll close this one.

Thank you!
