### ISSUE TITLE
Setting up Multiple Environments

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27862]
We are about to use salt for multiple environments. We call them 'base', 'deploy' & 'release'.

So, I edited `/srv/salt/top.sls`, added `deploy` and `release` environment keys and added the appropriate sls modules for each env.

However, salt-ssh tells me:

        - No matching salt environment for environment 'release' found
        - No matching sls found for 'home' in env 'release'

I found out that I needed to add `deploy` and `release` in the /etc/salt/master conf file.

Is that really necessary? For now, all envs use the same directory tree.

**Comment by jfindlay** [comment]
@srkunze, thanks for the report.  Yes, unfortunately, you are right.  My first reaction upon seeing this issue was 'Oh great, another saltenv issue'.  The meaning of saltenvs has been overloaded to the point of it being confusing in exactly the manner you describe.  In 2015.8.0, [some config options](https://docs.saltstack.com/en/latest/ref/states/top.html) were added to top file handling of saltenvs is better than is used to be to help reduce some of this confusion.

**Comment by srkunze** [comment]
I am sorry. :) Are there some plans to clear things up?

What I can see are three kinds of solutions:

1) fix those error messages: refer to the /etc/salt/master and file_roots when needed
2) make optional, i.e. defaulting to 'base' env
3) separate saltenv out into two distinct concepts: file trees and state orchestration

NOTES:
1) a quick fix
2) a possible work around
3) the prime solution

**Comment by jfindlay** [comment]
Part of the challenge is to not break backwards compatibility.  There are people who have thought more deeply and thoroughly about this issue than I, such as @whiteinge and @cachedout, who would be able to offer a more discriminating opinion.  I wonder whether we could get by with more clarity and some thorough, well-motivated examples in the documentation.

**Comment by srkunze** [comment]
I think we can close this.
