### ISSUE TITLE
[Doc] Better Nagivation in Topic Hierarchy

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27915]
1) shorter top level doc
2) sensible order of the toplevel topics
3) better visible doc hierarchy (distinguishing topics and subtopics and so on and so forth)
4) able to open and close subtopics independently, to look around easily and not just a single one

Background: there has been many examples in the past, where patient salt devs such as @jfindlay, @rallytime or @basepi who pulled out doc pages that I've never seen before; which are about topics of which I thought I should have come across them many many times before but did not.

**Comment by jfindlay** [comment]
Thanks, @srkunze.

**Comment by rallytime** [comment]
Great suggestions @srkunze! I agree that there should be some better ways to see what goodness lies within the docs. Oftentimes if you don't know something is there, you'll never find it because certain pages take a couple of tries to find what you're looking for.

@jacobhammons This one has your name on it! :D

**Comment by jacobhammons** [comment]
@srkunze I think this is solved by the new landing page and nav in the 2016.3 docs, if you think this is sufficient please close. Thanks!
