### ISSUE TITLE
The new Debian Salt repository seems to be having issues

### ISSUE THREAD

**Issue by marnovdm** [saltstack/salt#28007]
This used to work (been using it all week) but suddenly this morning on a 'pkg.upgrade refresh=True' of our development environment:

    servername.domain.dev:
    ERROR: W: Failed to fetch http://repo.saltstack.com/apt/debian/dists/jessie/contrib/binary-amd64/Packages  404  Not Found
    
    E: Some index files failed to download. They have been ignored, or old ones used instead.

And when applying the pkgrepo.managed state to new deployed minions:

      Name: deb http://repo.saltstack.com/apt/debian jessie contrib - Function: pkgrepo.managed - Result: Changed
              ----------
          ID: salt-repo
    Function: cmd.wait
        Name: wget -O - https://repo.saltstack.com/apt/debian/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
      Result: False
     Comment: Command "wget -O - https://repo.saltstack.com/apt/debian/SALTSTACK-GPG-KEY.pub | sudo apt-key add -" run
     Started: 07:53:23.708892
    Duration: 811.9 ms
     Changes:   
              ----------
              pid:
                  6312
              retcode:
                  2
              stderr:
                  converted 'https://repo.saltstack.com/apt/debian/SALTSTACK-GPG-KEY.pub' (ANSI_X3.4-1968) -> 'https://repo.saltstack.com/apt/debian/SALTSTACK-GPG-KEY.pub' (UTF-8)
                  --2015-10-16 07:53:23--  https://repo.saltstack.com/apt/debian/SALTSTACK-GPG-KEY.pub
                  Resolving repo.saltstack.com (repo.saltstack.com)... 198.199.77.106
                  Connecting to repo.saltstack.com (repo.saltstack.com)|198.199.77.106|:443... connected.
                  HTTP request sent, awaiting response... 404 Not Found
                  2015-10-16 07:53:24 ERROR 404: Not Found.
                  
                  gpg: no valid OpenPGP data found.
              stdout:

This happens on Debian 8 VM's on multiple locations (seperate internet connections etc) so I think this issue could be on the Salt repo infra? Please let me know if I can supply any more information.

**Comment by cybacolt** [comment]
http://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/ 
is now:
http://repo.saltstack.com/apt/ubuntu/ubuntu14/2015.8/dists/

its the same debian too.

**Comment by marnovdm** [comment]
Thanks, I updated my sources.list entry to:

deb http://repo.saltstack.com/apt/debian/latest/ jessie main
(used to be: deb http://repo.saltstack.com/apt/debian jessie contrib)

and now it works again! The docs on https://docs.saltstack.com/en/latest/topics/installation/debian.html don't reflect this change yet, I think they should be updated.

**Comment by cybacolt** [comment]
i think the repo is in flux is its not supposed to be production ready until the next stable... i'm sure it'll be fine after that.

**Comment by cybacolt** [comment]
looks like theres other stuff broken - pip now has two package paths after apt-get install pip:
python -c "from pkg_resources import Environment;print(Environment()['six'])"

getting weird 'Owned by OS' errors when i try to install/uninstall

**Comment by babilen** [comment]
@cybacolt It might not be a bad idea to create a separate issue for that problem.

**Comment by cybacolt** [comment]
@babilen ignore me, seems to be something fubar with a package ubuntu are offering (1.5.4-1ubuntu3). downgrading fixed it (1.5.4-1)...

hopefully saltstack repo with offer python-pip as well?

**Comment by alxbse** [comment]
@cybacolt If the repo is not yet production ready this should really be made more clear in the documentation. Right now it is listed at the top of the debian installation instructions and I assumed it was the recommended way to install the salt minion on debian. 

Woke up today with a mailbox full of failed jenkins builds due to this repo change.

**Comment by dmurphy18** [comment]
The repo had to change due to support for 2015.8 and 2015.5 branches, for both Debian and Ubuntu.  I expect further possible changes with the repo's once we publish how they are built and the community has had a chance to improve how packages are built for Debian and Ubuntu, but hopefully they shall be backwards compatible.

**Comment by hal58th** [comment]
@dmurphy18 I noticed that the major versions are now missing their older minor versions. ie, 2015.8.1 is there but 2015.8.0 is missing. Wasn't that the whole goal of these repos? To have the old minor versions still available? I think I am going to make a bug about this.

**Comment by dmurphy18** [comment]
@hal58th we are working on getting the old minor versions to stay around, in process of determining the most appropriate layout for this.

**Comment by babilen** [comment]
Please, please, please, don't break the repositories by shipping multiple versions of the same package at the same time.

**Comment by hal58th** [comment]
Well, that would be true for latest, how does it break a repo by having
multiple versions in it for example the 2015.8 repo? You just have to
specify which package you want to install.

**Comment by babilen** [comment]
Well, generally speaking a Debian repository is designed to only contain a single version of any given package at a particular point in time. Tools have been developed with this assumption in mind and not adhering to it might cause all sorts of hard to debug and tricky problems.

One can do it, but it means that the repository doesn't comply with the specification. The precise nature of the problems are, naturally, hard to specify in toto.

The way to do this properly is to provide different packages for each *branch* you want to ship (such as python2, python3, python2.7, ....) which allows you to release new versions of the package for each branch independently.

**Comment by dmurphy18** [comment]
@marnovdm Given the new layout and hopefully we didn't break backwards compatibility this time, can this issue be closed.

**Comment by marnovdm** [comment]
@dmurphy18 since this report I've been using 'deb http://repo.saltstack.com/apt/debian/latest/ jessie main' without issues.

I see the documentation now mentions the 'deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main' - does it matter which one I use?

**Comment by dmurphy18** [comment]
@marnovdm I would use 'deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main' since eventually there should be wheezy packages (that is debian/7).

Also the specific versions are now archived so that you can ignore the latest if so desired, e.g. 'deb http://repo.saltstack.com/apt/debian/8/amd64/archive/2015.8.3 jessie main'

Just recently Salt open-sourced on github https://github.com/saltstack/salt-pack.git  how packages are built using salt states/execution modules (see states/pkgbuild.py, and debbuild.py & rpmbuild.py in modules).  These is still a lot of work to do, make Debian/Ubuntu side use pillar data similar to Redhat/Centos, non-root builder, automated package signing, etc.  
Also want to support more than just Intel architectures, e.g. arm, power, etc.

There shall be an announcement about it in the new year, just too close to Christmas now.

**Comment by marnovdm** [comment]
@dmurphy18 thanks for the explanation, I've tested the configuration mentioned in the documentation and it's working fine for me, so I think this can indeed be closed now :) Thanks!
