### ISSUE TITLE
Parallel invocations of salt-ssh on the same set of minions will result in errors

### ISSUE THREAD

**Issue by m7v8** [saltstack/salt#28124]
When executing salt-ssh in parallel, lets say in different terminals:

```
salt-ssh '*-[aw]*' pkg.version postgresql93
```

and

```
salt-ssh '*-[aw]*' pkg.version python-pip
```

Both will fail with

```
retcode:
    12
stderr:
    8335b595aebdaf2dc84614e3df42911e84ee57f3
    78eddc4997f1b6856738ba3c658fbd9d0a890f7f
    WARNING: checksum mismatch for "/tmp/.root_dcdf8c_salt/salt-thin.tgz"
stdout:
    ERROR: The salt thin transfer was corrupted
```

or

```
retcode:
    11
stderr:
    WARNING: Unable to locate current thin  version: /tmp/.root_dcdf8c_salt/version.
stdout:
    ERROR: Failure deploying thin: /usr/bin/scp
    _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
    deploy

    WARNING: Unable to locate current thin  version: /tmp/.root_dcdf8c_salt/version.
```

With just one minion it will work, but with a set of minions I see this behaivor.
This seems to go away when the transfer of the thin client (not sure how it's called) to all minions is completed. 
That it works with one minion may be a coincidence. I may have picked a minion where it was already transfered.

**Comment by jfindlay** [comment]
@m7v8, thanks for the report.  What we should probably do here is set a lock file during the thin transfer.

**Comment by thatch45** [comment]
Yes, I can confirm that this works once the thin is deployed. I can also verify that running the commands with `-W` also solves the problem, as that prompts salt-ssh to deploy the thin to a specific location. I am also seeing that the problem is harder to reproduce with https://github.com/saltstack/salt/pull/34831.
I can also verify that once the thin is deployed then all is well with parallel commands and the change in 2016.3 to move the thin dir to /var/tmp means that deployment of the thin tarball is minimized.
I am going to leave this open and lower it to low severity sine it is easily worked around and the footprint has been lessened.
