### ISSUE TITLE
Permit pillar data targeting via EC2 tag

### ISSUE THREAD

**Issue by QuinnyPig** [saltstack/salt#28160]
I'd like to target pillar data based upon what an instance is tagged with inside of EC2.

From a security perspective, setting tag data as a grain is problematic, as a compromised node could impersonate other nodes to gain access to data it shouldn't have. Ergo we should probably have some mechanism by which the tag determination is done by the master, not the minion...

**Comment by basepi** [comment]
This seems like it might be a job for an external pillar. Can look up the EC2 tag itself or something, go around the grains.

**Comment by joelacrisp** [comment]
As an additional request, is it possible to implement this feature in an abstracted way so that we may have backends for OpenStack, Softleyer etc? Currently we duplicate all our tag data into grains so that we have a consistent view across heterogeneous clouds.  We do this on Rackspace by injecting a precanned "grains" file on nova boot and on aws with a rehydration script that builds the grains file from the AWS tags using boto. Thx!

**Comment by basepi** [comment]
Thanks for the suggestion, @joelacrisp. That seems like a great idea if we can figure out how to do it.
