### ISSUE TITLE
http module needs explanation 

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#28179]
Hello,

I am trying to use http module with this kind of requests:

API URL example

```
https://foo.bar.com/api.php?api_id=API_ID&api_key=API_KEY&call=addTicket&client_id=CLIENT_ID&subject='Hello World'&body='Managed by SaltStack'
```

I have tried the following:

```
salt-run http.query https://foo.bar.com/api.php method=GET api_id=API_ID api_key=API_KEY call=addTicket client_id=CLIENT_ID subject='Hello World' body='Managed by SaltStack'
```
but its not working , is there a specific way to achieve this ? by salt-run or by sending an event from the minion to the master so master can trigger it

Thanks

**Comment by techhat** [comment]
Hi @mostafahussein. Just send the URL as a URL; don't break it into components. For `POST` requests, you can break the pairs into a `dict` called `data`.

Since passing in a `dict` on the command line can be a hassle, you can pass a file name to `data_file` instead. You can use any file format that Salt's renderer supports, but JSON is probably best.

**Comment by jfindlay** [comment]
@mostafahussein, does @techhat's comment answer your questions?

**Comment by mostafahussein** [comment]
I am still trying to test what @techhat said but i couldn't make it work until now , how could i change the backend to `requests` instead of `urllib2` ?

**Comment by techhat** [comment]
@mostafahussein which version are you running? In older versions you would set `requests_lib=True`, but in more recent versions you will use `backend=requests`. You can set both at the same time without a problem.

**Comment by mostafahussein** [comment]
thanks for explanation @techhat !
