### ISSUE TITLE
Docs: Difference between modules.cron.rm_job and modules.cron.rm

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#28202]
What is the difference between modules.cron.rm_job and modules.cron.rm?

The docstring for both methods are identical: copy+paste typo?

If both methods are identical: which one is preferred and which one is deprecated?

**Comment by jfindlay** [comment]
@guettli, neither is deprecated and the docs are identical because cron.rm is [an alias](https://github.com/saltstack/salt/blob/v2015.8.1/salt/modules/cron.py#L529) for cron.rm_job..

**Comment by guettli** [comment]
First: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cron.html#salt.modules.cron.rm
Second: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cron.html#salt.modules.cron.rm_job

The end user does not see notes about both being an alias. Is this alias really need?

Would it be possible to apply the deprecation policy?

Or leave the docs from one command empty and just provide a link with this title: "cron.rm is the alias of cron.rm_job"

**Comment by jfindlay** [comment]
@guettli, what do you think about https://github.com/saltstack/salt/compare/2015.8...jfindlay:alias?

**Comment by jfindlay** [comment]
@guettli, using  #28348, I get this
```console
# salt <minion> sys.doc cron.rm
cron.rm:

This function is an alias of ``rm_job``.
```

**Comment by guettli** [comment]
@jfindlay I looked at the patch. It looks good. It not just solves this issue, but a lot of aliases. Great!

One question left: Why are two functions needed? Why not deprecate one?

**Comment by jfindlay** [comment]
@guettli, there are a few reasons to have two names for the same thing.  One is that a shortcut can be useful (like `ls -s` vs `ls --size`).  Both cases are useful in different circumstances.  Another is that users may have been using one name for a function when another name could be descriptive/helpful.  It is ultimately a matter of opinion.  Personally I think we should keep both `cron.rm_job` and `cron.rm` as an instance of the first case I have mentioned.  If you think you have a compelling argument otherwise, then we can deprecate one in favor of the other.  There are certainly examples in the codebase, mainly having to do with the use of underscores (`network.hw_addr` vs `network.hwaddr`, for example) where consistency could be an evolutionary goal by deprecating one form in favor of another that conforms to a global style.  The merit of this consistency, however, always must be balanced against the magnitude of the effort and willingness of the installed user base to update in the time given.

**Comment by guettli** [comment]
My reason to have **one** and not two: it's redundant. Quoting:
https://github.com/timoxley/best-practices#reducing-the-amount-of-code-in-your-product-should-be-a-goal

> "I hate code, and I want as little of it as possible in our product." – Jack Diederich

My personal opinion: Docs which contain "or" waste my time. There is should be one way to do it. If I want an alias, I can create one myself.

And: Test driven development goes: red, green, refactor. Not red, green, new feature. Keeping code clean is important.

Thank you for your interest and response. I said what I wanted to say. I close this issue, since it is not very important.
