### ISSUE TITLE
Update nodegroup docs to explain how to target via nodegroups

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#28268]
Currently the nodegroup docs (https://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html) don't explain that you actually CAN target nodegroups if you turn on `master_opts` as noted here: http://grokbase.com/t/gg/salt-users/148t6kk89m/if-condition-on-nodegroups#20140906fw7s4m5kxkpnzodsr7ru7njqbu.

The docs should be updated to note this, as well as a huge warning regarding how this is could potentially put data on the minions you don't want. @sdm24 says they will handle this. There are already many issues regarding supporting this in a more efficient way for nodegroup targeting itself, but this should suffice for now.

**Comment by jfindlay** [comment]
@gravyboat, thanks for reporting.

**Comment by sdm24** [comment]
After playing around with this, it seems like the {% if grains.id %} part will only match if the nodegroup is set explicitly with a list of IDs. If I have a nodegroup set with ``group1: 'G@os:Debian and L@debmin1,debmin2,winmin1' ``, and then have a state file with
```YAML 
{% if grains.id in salt['pillar.get']('master:nodegroups:group1', []) %}
test.ping:
  module.run
```
then debmin1, debmin2, and winmin1 will all run test.ping, even if winmin1 is running Windows instead of Debian. To make sure that only the correct minions are targeted, you would have to do
```YAML
{% if (grains.id in salt['pillar.get']('master:nodegroups:group1', [])) and (grains.kernel in salt['pillar.get']('master:nodegroups:group1', []) %}
```
It seems that you need to include Jinja statements for each unique matcher. When I was testing, I ran into a strange issue where if multiple IDs are defined, such as ``group1: 'G@id:debmin1 and L@debmin1,debmin2,winmin1' ``, then all 3 minions will pass the jinja statement, while only debmin1 will be in the nodegroup. I'm not sure if this really matters, since it seems pointless to target IDs like that in a nodegroup.

**Comment by DanyC97** [comment]
@sdm24 thanks!
