### ISSUE TITLE
pkg.installed not available

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#28401]
hello
I've just wanted to make sure the vim-common package is installed on the system but the pkg.installed module doesn't work. 
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html

 
salt 'host' pkg.installed 'name=vim-common'
host:
    'pkg.installed' is not available.
ERROR: Minions returned with non-zero exit code

**Comment by rallytime** [comment]
Hi @BalintSzigeti - Thanks for the report. You're seeing that error because the command that you should be using to execute the install should be `pkg.install`, not `pkg.installed`.

The difference here is that `pkg.install` is the remote execution command to use the [execution module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pkg.html) to install a package. Whereas `pkg.installed` is the command to be used in the [state module](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html) to install a package. Does that help?

**Comment by BalintSzigeti** [comment]
thank you your help but I think you misunderstood my goal. I wanted to 
check the package is installed or not. I don't want to install it at 
once just collect the info.

yes I would use cmd.run 'rpm -qa |grep vim-common' but isn't there a 
salt solution for this?

**Comment by jtand** [comment]
@BalintSzigeti I think `pkg.version` is what you're looking for. 
```yaml
salt minion pkg.version vim-common
minion:
    7.0.109-7.el5
```
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.yumpkg.html#salt.modules.yumpkg.version

**Comment by BalintSzigeti** [comment]
yes, you are right. the pkg.version is the command that I searched. 
how could I configure its return value?  Its return value always 0 regardless the  package is installed or not?
Should I open another feature request for pkg.version module?

**Comment by BalintSzigeti** [comment]
thank you, that module what I searched. I'll open another ticket for REVs.
