### ISSUE TITLE
dockerng environment variables as file

### ISSUE THREAD

**Issue by mo-mughrabi** [saltstack/salt#28483]
Currently there is no way to pass dockerng a environment file to use at run time, variables are defined individually into formula. 

It would be great if we can use `--env-file` option at docker `run` to specify the env file to load

**Comment by jfindlay** [comment]
@mo-mughrabi, thanks for the feature request.

**Comment by tspecht** [comment]
Any news on this?

**Comment by jfindlay** [comment]
@tspecht, not that I know of, but it seems like something that should be relatively easy to add.

**Comment by ticosax** [comment]
This is not a feature supported by docker-py client.

Providing environment variables from the pillars is the way to go.

**Comment by jfindlay** [comment]
@ticosax, but it still should be possible to supply a file containing environment variable definitions to the dockerng execution or state module at which point it could be translated into the command environment?

**Comment by ticosax** [comment]
@jfindlay Sure, we can.

Does it make sense ?
Not from my point of view.
Because `sls` are already files. What would be the motivation to store `Env` in a separate file then to parse it and to make it a python dict ?
I'm failing to see a valid use case here.

@tspecht what is your use case ? Can you tell us more ?

**Comment by hjc1710** [comment]
I know this is a bit old and I'm not the original author, but I would love for this feature to be implemented. I'll tell you my use case.

For us, we want to be able to run our docker containers with, or without Salt. Asking all of our developers to install an entire Salt client on their host machine isn't ideal, and we don't want Salt to be a run time dependency when Docker can function just fine on it's own. But, we definitely want Salt to manage our Docker containers when they get to production.

When writing the scripts that run the Docker container manually, you obviously have to specify environment variables via args and we also want those environment variables to be the same ones that Salt uses. So, due to the latter requirement, that leaves you with two possible options:

1. Template the `start_docker.sh` shell script via Salt, providing all the `-e` values yourself from pillar.
2. Have a single `env.list` file that both `start_docker.sh` and Salt use to seed their environment.

The former, still requires Salt to work, so you may as well have Salt run Docker. The latter, is currently impossible.

As per the Docker docs:

>Regardless of the order of these three flags, the --env-file are processed first, and then -e, --env flags. This way, the -e or --env will override variables as needed.

So, by supporting an `envfile` option, you can have a stock `env.list` in your project that can be run via Docker directly, and can then be consumed via Salt to use the same environment variables. When you then go to deploy your Docker apps to production, you can override the values in the `env.list` file by just adding extra values to the `environment:` key in your Salt state. This way, you still have the full strength of Salt and it's Pillars, via `environment`, but you can also easily run the exact same Docker container from your shell by passing in your `env.list` file.

Does that use case make sense/sound valid?

**Comment by ticosax** [comment]
@hjc1710 thank you for the detailed explanation. Within our team we are using [envdir](https://pypi.python.org/pypi/envdir) to provision environment variables within the containers when we start them locally.
So, yes your use case seems sensible. However I'm not joining you among users who need this feature, because we are solving the same problem by different means.

You'd love to see this feature implemented ?
go ahead !

**Comment by hjc1710** [comment]
@ticosax - oooo, I haven't heard of `envdir`. I'll look into that and it might help me for the time being.

I'll see about contributing. The salt codebase is pretty intimidating, but [HACKING.rst](https://github.com/saltstack/salt/blob/develop/HACKING.rst) looks like it will get me going!
