### ISSUE TITLE
repo.saltstack.com to host armhf and armel binary distributions

### ISSUE THREAD

**Issue by arthurzenika** [saltstack/salt#28742]
I was great to have armhf and armel binary distributions on debian.saltstack.com, now trying to switch to repo.saltstack.com but only amd64 is built. This is a pretty big regression in my opinion for all the small devices that could have a salt-minion (raspberrypi for example, but also a bunch of NAS etc.). Promoting salt as a very versatile solution is getting harder. _Please_ re-enable these architecture. For reference the list of archs on the previous repos is : 
- i386
- amd64
- i686
- mips
- armel
- armhf

**Comment by jfindlay** [comment]
Related issues:
#27228
#27189
#24955

**Comment by bbinet** [comment]
+1
could debian.saltstack.com be updated with latest salt versions until repo.saltstack.com is ready for all architectures and all debian distributions?

**Comment by job** [comment]
This issue is affecting me as well, I would like up-to-date `armhf` binaries to be published on repo.saltstack.com - or alternatively motivate a community member to bring the `debian.saltstack.com` repository in sync with a more recent release.

**Comment by jfindlay** [comment]
@job, you are welcome to add support to https://github.com/saltstack/salt-pack.  That is what is used to generate the packages that are hosted on repo.saltstack.com.  The process still isn't fully automated yet, but we are making progress.  Also, with the addition of a platform, we will need to work out automated package testing for that platform in https://github.com/saltstack/salt-pkg-tests.  Those tests are usually run against cloud VMs for each relevant platform.  Unless arm VMs are available to SaltStack, we may have to defer that testing to the community.

**Comment by damon-atkins** [comment]
rpm -ivh https://repo.saltstack.com/yum/redhat/salt-repo-2015.8.el7.noarch.rpm
Results in trying to fetch from https://repo.saltstack.com/yum/redhat/22/armhfp/latest

To meet salts current dependency need Fedora 23 for python-tornado >= 4.2.1
I suggest you split out your code vs others people code.  So people have a choice if to use OS vendor supplied or saltstack supplied.    It's good your supplying it for older OS.

After upgrading to 23 I will try https://repo.saltstack.com/yum/redhat/latest/x86_64/latest/   dnf should ignore the x86 rpms.

**Comment by ksze** [comment]
Looks like somebody at University of Science and Technology of China made an apt-repo with the latest Salt built for armhf:

http://mirrors.ustc.edu.cn/salt/apt/debian/8/armhf/2016.11/

The next important question is: do you trust it?

**Comment by furlongm** [comment]
`apt/debian/9/armhf/latest/` for stretch gives a 404. Would it be possible to build armhf debs for debian stretch? This is holding me back from upgrading a number of boxes to from jessie to stretch.

**Comment by chrisbertsch** [comment]
+1 for Debian 9 armhf packages

I am trying to upgrade from Debian 8 but it looks like packages are not built for Debian 9 armhf.

**Comment by damon-atkins** [comment]
WIndows on ARM will be next :-)

**Comment by arthurlogilab** [comment]
up

**Comment by oeuftete** [comment]
ZD-6212.

**Comment by damon-atkins** [comment]
There is also AWS Linux 2 ARM64

**Comment by sagetherage** [comment]
After careful review of this ticket for the Aluminium release, we do not have enough resources to commit to the work in the release cycle. This issue has been opened for sometime and currently the direction is to make use of single binary packages using Tiamat. I will leave this issue open and get a session together with key Core Engineers to discuss the future and update in the near future.

**Comment by ScriptAutomate** [comment]
## Debian / Raspbian `armhf` `salt` releases: Where are they?

For Debian/Raspbian `armhf`, these are currently created and can be found under:
- https://repo.saltstack.com/#raspbian

The directory listing path being:
- https://repo.saltproject.io/py3/debian/9/armhf/

I wasn't around for `debian.saltstack.com`, but I think that can now be broken down into:
- https://repo.saltstack.com/#raspbian
- https://repo.saltstack.com/#debian

Looking at the [directory list for debian](https://repo.saltproject.io/py3/debian/9/), it looks like Salt Project has the following:
- `amd64`
- `armhf`

**Debian 8 is no longer a supported OS for `salt` when it comes to packaging, [due to Debian 8 "Jessie" reaching EOL](https://www.debian.org/News/2020/20200709)**. Salt Project won't be creating anything newer than what can be found on the archives, when it comes to Debian 8. These are unsupported, and we highly recommend _not_ using them:
- https://archive.repo.saltproject.io/apt/debian/ (Python 2 versions of `salt`)
- https://archive.repo.saltproject.io/py3/debian/ (Python 3 versions of `salt`)

For `salt`, all newer Python 3 packages will be available within the following directory listing:
- https://repo.saltproject.io/py3/
- Only Python 2 releases of `salt` version `v3000.x` are published here: https://repo.saltproject.io/apt/
  - Reminder: After **Aug 31, 2021**, `v3000.x` of `salt` exits Phase 3 Support. This means that no new security releases to Python 2 versions of `salt` will be happening anymore.

## Packaging for other architectures

When it comes to other listed architectures for debian releases:

- [x] `amd64` (Example for Debian 10: https://repo.saltstack.com/#debian // directory listing: https://repo.saltstack.com/py3/debian/10/amd64/)
- [x] `i386` (I believe this is provided by the `amd64` path, because of seeing this: https://repo.saltproject.io/py3/debian/10/amd64/3003/dists/buster/main/binary-i386/ - which would mean it should be provided by the general `amd64` path of https://repo.saltstack.com/#debian ? I may be wrong in what I am interpreting there)
- [ ] `i686` (not sure)
- [ ] `mips` (not sure)
- [ ] `armel` (not sure)

I'll have to follow-up on more with Salt Project team for confirmations.

> Related issues:
> - https://github.com/saltstack/salt/issues/55546

**Comment by bryceml** [comment]
The binary-i386 folder was just there so you don't have to put `arch=amd64` in the .list file since a lot of amd64 machines also have i386 enabled too, mostly so they can run 32 bit programs.  As far as I'm aware, centos/rhel 6 has been the only one with i386 support in the past 3 years.

**Comment by bryceml** [comment]
Also, for raspbian on arm64, the vast majority of the packages come straight from debian repos, with just a few packages added on from the raspbian repos on top.

**Comment by sagetherage** [comment]
Many of these packages were created by the community some time ago and the team does not have the manpower to create all of these, but we welcome community packagers - if anyone on this issue or others are interested please contact us at saltproject@vmware.com

**Comment by bryceml** [comment]
arm64 support has been added for debian 11 and ubuntu 20.04.

**Comment by defanator** [comment]
RHEL 8 aarch64 support would be awesome as well.

**Comment by gandihar** [comment]
> RHEL 8 aarch64 support would be awesome as well.

Seconded! Between Rocky Linux and AlmaLinux, there are options for EL8 on aarch64. All it takes is an aarch64 build host and a rebuild.

**Comment by thatch45** [comment]
I am going to close this out since we now have onedir support for aarch64:
https://repo.saltproject.io/salt/py3/onedir/3006/
