### ISSUE TITLE
network.system state ignores test=True on debian/ubuntu

### ISSUE THREAD

**Issue by olfway** [saltstack/salt#28751]
I've tried to configure hostname on ubuntu with:
```salt
system_set_hostname:
  network.system:
    - enabled: True
    - hostname: node-name.node-domain
```
and `salt 'node' state.sls network.config test=True`
ignores test parameter and applies changes unconditionally

It also adds "domain node-domain" line to /etc/resolv.conf which is unexpected
(and actually with resolveconf installed will be overwritten)

I'm using salt 2015.8.1 on Ubuntu 15.10

**Comment by jfindlay** [comment]
@olfway, thanks for the report.

**Comment by abednarik** [comment]
Hi @jfindlay / @olfway 

 Looking at the code and running salt in debug [here](https://github.com/saltstack/salt/blob/2015.5/salt/modules/debian_ip.py#L1816-L1838) i can see that Ubuntu > 12 will match if test and will not go inside else code, that's why test=True is ignored.
 I will spend some tine to see if i can do a PR to fix this.

**Comment by abednarik** [comment]
Hi @olfway 

 If you get the chance, please test this PR #30749

Thanks.

**Comment by lagonix** [comment]
Hi @abednarik 

I have tested PR #30749 from the 2015.8 branch on a Ubuntu 14.04 with success.

**Comment by abednarik** [comment]
Thanks: :)
