### ISSUE TITLE
Enabling and disabling individual beacons that use YAML block sequences ("- ") fails with no comment.

### ISSUE THREAD

**Issue by makearl** [saltstack/salt#28796]
Enabling and disabling individual beacons that use YAML block sequences ("- ") fails with no comment.

Example of the problematic beacon configuration:
```
beacons:
  my_beacon:
    - enabled: False
    - interval: 60
```

When the beacon is configured as above, we don't get any comment that it's wrong but salt does not apply the update:
```
root@5a4791a27ff5:/# salt '*' beacons.enable_beacon my_beacon
minion1:
    ----------
    comment:
    result:
        True
root@5a4791a27ff5:/# salt '*' beacons.list
minion1:
    beacons:
      enabled: true
      my_beacon:
      - enabled: false
      - interval: 60
```

If we change the beacon to use indented YAML notation, it works:
```
beacons:
  my_beacon:
    enabled: False
    interval: 60
```

Is this the expected behavior? If so, I can submit a pull request to update the documentation. If it isn't, I think the problematic section in the code is in [beacons/__init__.py](https://github.com/saltstack/salt/blob/develop/salt/beacons/__init__.py) line 244, we try to update the options as though the beacon config is a dictionary when it could be a list.

Here's the output of my `salt --versions-report`:
```
root@5a4791a27ff5:/# salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.8.0
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.1.12-boot2docker
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@makearl, thanks for reporting this.  I think the better solution is to log and return an error/warning that the beacon data needs to be a dictionary.  Since the difference in data formatting is trivial, I think it would be better to limit the variability for simplicity and stability.

I would probably prefer the list formatting `- ` because it is more similar to the [highstate style](https://docs.saltstack.com/en/latest/ref/states/highstate.html) than the dictionary formatting.  If we did want to enable this form in favor of the other, then we would have to call `salt.utils.warn_until` if the dictionary form was detected.  What do you think?

**Comment by makearl** [comment]
@jfindlay thanks for the feedback. I agree with you that the list formatting would be more consistent with the rest of the system and will work on implementing that change.
