### ISSUE TITLE
inconsistency between os* grains in various SLE distros

### ISSUE THREAD

**Issue by tampakrap** [saltstack/salt#28854]
As seen below, there is quite some mess on the os\* grains in SLE distros:
- SLE11SP3:

```
# cat /etc/os-release
cat: /etc/os-release: No such file or directory

# cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
```

```
os:
    SUSE
os_family:
    Suse
osarch:
    x86_64
oscodename:
    n.a
osfullname:
    SUSE
osrelease:
    11 SP3
osrelease_info:
    - 11 SP3
```
- SLE11SP4:

```
# cat /etc/os-release
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"

# cat /etc/SuSE-release 
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4
```

```
os:
    SLES
os_family:
    Suse
osarch:
    x86_64
oscodename:
    x86_64
osfullname:
    SLES
osrelease:
    11
osrelease_info:
    - 11
```
- SLE12:

```
# cat /etc/os-release 
NAME="SLES"
VERSION="12"
VERSION_ID="12"
PRETTY_NAME="SUSE Linux Enterprise Server 12"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12"

# cat /etc/SuSE-release 
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 0
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
```

```
os:
    SLES
os_family:
    Suse
osarch:
    x86_64
oscodename:
    x86_64
osfullname:
    SLES
osrelease:
    12
osrelease_info:
    - 12
```

**Comment by tampakrap** [comment]
see also https://github.com/saltstack/salt/issues/28855

**Comment by tampakrap** [comment]
if needed, I can provide more output from additional distros (openSUSE, SLED, the upcoming SLE12SP1 etc)

**Comment by jfindlay** [comment]
@tampakrap, also see #28892.  Is there any more work that needs to be done here?

**Comment by tampakrap** [comment]
thanks @jfindlay I will take a look and get back to you. @aboe76 @isbm @darix check it as well please

**Comment by isbm** [comment]
@tampakrap I just today looked at this, because we needed that clear in SUSE Manager, and found [this line](https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L955) is aliasing everything. First, this value [goes into `lsb_distrib_id`](https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L1215) but then never goes overridden, even `/etc/os-release` is present.

We would need to:
1. Decide how do we call `os` and `osrelease`.
2. Make sure all SUSE products are consistent (Leap, SLE 11 and 12 and at least openSUSE 13).
3. Note that the LSB is [no longer cool](https://lwn.net/Articles/658809/).

To be honest, the whole `salt.grains.core.os_data` could be better. :wink:

**Comment by tampakrap** [comment]
@isbm [this line](https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L955) was added by me on #28855 because SLE11SP4 was failing to start services otherwise. Either way, I will update to 2015.8.2 and will resubmit data that I submitted to this ticket's subject

**Comment by tampakrap** [comment]
based on the discussion on https://github.com/saltstack/salt/commit/baf238f270172654d4bb954f3fc21590fda98b47 and here, this ticket needs to be reopened, can somebody with the appropriate rights do it for me please?

**Comment by tampakrap** [comment]
scratch that, I just noticed it is open sorry :(
