### ISSUE TITLE
Attempts at using mine over salt-ssh result in KeyError: 'master_job_cache'

### ISSUE THREAD

**Issue by zer0def** [saltstack/salt#28852]
The entirety of my attempted salt-mine usage is within the exception log. Target machines are Ubuntu 14.04.

```
[ERROR   ] Rendering exception occurred :Jinja error: 'master_job_cache'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 30, in top-level template code
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/wrapper/mine.py", line 52, in get
    for ret in ssh.run_iter(mine=True):
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 450, in run_iter
    fstr = '{0}.prep_jid'.format(self.opts['master_job_cache'])
KeyError: 'master_job_cache'

; line 30

---
[...]
      - service: rabbitmq_service

testing_mine:
  file.managed:
    - name: /tmp/minetest
    - contents: {{ salt['mine.get']('rabbit*', 'network.ip_addrs') }}    <======================

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
[...]
```

```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.10 (default, Oct 14 2015, 16:09:02)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.3.4
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 15.10 wily
        machine: x86_64
        release: 4.2.0-16-generic
         system: Ubuntu 15.10 wily
```

**Comment by basepi** [comment]
Hmm, it shouldn't be stacktracing, so we should look into that.

However, I highly recommend avoiding the mine if you can in salt-ssh. I implemented basic mine support in salt-ssh for feature parity purposes, but it's *super* inefficient. It basically will publish a new job for each mine.get call, since minions can't send up their mine information on a regular basis. Additionally, since each of these state runs are being compiled in a separate process, there's no caching. So if you put a mine.get job in each minion's state files, that job will be run once for each minion, which involves spinning up an exponential number of salt-ssh threads to retrieve those data.

I've been thinking about potential solutions to this. We could potentially have a flag for mine runs which would run a single minion's state run, and cache any mine.get calls that happen during that state run, before running the rest of the minions and using that cache where possible. But syncing those mine runs across processes is a hard problem.

**Comment by zer0def** [comment]
Yeah, I can imagine it being super inefficient. Thing is, one minion's state could differ from the other, depending on conditions in your set of SLSes, not to mention `file` states that could involve templating.

My initial thought late night tired (among other things) thought after reading your response, was to look for `mine` calls within the entirety of the applied SLSes **before templating** and act upon them, before sending actual tasks to your roster, but I'm not entirely certain how viable and/or efficient that would be.
