### ISSUE TITLE
 'useradd' __virtual__ returned False

### ISSUE THREAD

**Issue by farss** [saltstack/salt#28916]
I run useradd.list_users in windows 2008 x64 , and return:

```
[root@localhost salt-winrepo-ng]# salt 172.16.200.7 useradd.list_users
172.16.200.7:
     'useradd' __virtual__ returned False
ERROR: Minions returned with non-zero exit code
[root@localhost salt-winrepo-ng]# salt 172.16.200.7 useradd.list_groups
172.16.200.7:
    'useradd' __virtual__ returned False
```

```
# salt --version
salt 2015.8.1 (Beryllium)
```

**Comment by cachedout** [comment]
That module is for Linux only. The module you are likely looking for is `win_useradd`.

**Comment by jfindlay** [comment]
@farss, or even better,
```console
salt 172.16.200.7 user.list_users
```
Salt execution and state modules have a mechanism called `__virtualname__` that is used to put parallel modules into the same class so that they can be used in an OS agnostic fashion.  For example, the `user` module that loads on linux is `salt.modules.useradd`, whereas the module that loads on windows is `salt.modules.win_useradd`.

**Comment by lburg** [comment]
I just ran into the same issue trying to execute a `pkgrepo.managed` state on Archlinux. I find the error message not helpful, isn't `Operation not supported on this operating system` clearer ? Or maybe that's not the sole purpose of `__virtualname__` ?
