### ISSUE TITLE
Enable setting file and folder permissions on windows

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#28920]
Today the [documentation of file.managed](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed) states that setting group or mode is not supported on windows.

Dealing with NTFS permissions is complex and a mess, but why not let **file.managed** use the official included tool [icacls.exe](https://technet.microsoft.com/en-us/library/cc753525.aspx) to manage setting permissions on windows machines?

**Comment by cachedout** [comment]
This is a question for @twangboy.

**Comment by twangboy** [comment]
@andrejohansson 

As you know file permissions/ownership is quite different in windows. So, I'll try to address this as best I can.

The `group` parameter is only provided for api compatibility. Only the `user` parameter is used to set ownership.

`mode` is unsupported in windows. I recall microsoft offered an add-on, Services For Unix (SFU) that may have added some of that functionality, but I never used it, so I can't say if there was a chmod option that would allow you to set the mode for a file/folder.

As far as using `icacls.exe`, we try to avoid shelling out whenever possible. Mostly because of problems with unicode and poss security issues. Keeping the code in Python helps reduce those problems.

What is the specific problem you are having with `file.managed`? Could you post an example of the scenario that is giving you issues?
