### ISSUE TITLE
force=True documentation for RabbitmqUser is misleading

### ISSUE THREAD

**Issue by belt-ascendlearning** [saltstack/salt#28974]
Reading the code, if the user exists, nothing will happen unless force=True is set... not just for passwords.

**Comment by jfindlay** [comment]
@belt-ascendlearning, is this on 2015.8.1?

**Comment by belt-ascendlearning** [comment]
Yes.

**Comment by rallytime** [comment]
@belt-ascendlearning Looking at the code history, on version 2015.8.1, that was definitely true. However, I updated that function to use `test=true` functionality with PR #28269, and during that change, `force=True` functionality now only affects password changes.

This is fixed in the 2015.8.3 release of Salt. Thanks for the report! I'll go ahead and close this.
