### ISSUE TITLE
salt-call state.highstate and downed syndics

### ISSUE THREAD

**Issue by chjohnst** [saltstack/salt#28978]
In an environment with multiple syndics, if one of my syndics is down when I run 'salt-call state.highstate' on a minion it hangs attempting to connect to the downed syndic and times out after 60s.  If I run this command 4-5x it will eventually bounce to the next syndics that is up and running and works.  Does the minion not keep track of who its current syndic is and use it when you run those commands? (I thought that was in /etc/salt/minion.d/_schedule.conf).    This is using salt 2015.5.5-1.

**Comment by basepi** [comment]
I do not think the minion writes anything about its current syndic to _schedule.conf -- that file is only used for schedule changes with the schedule module/state I think.

The problem here is that salt-call doesn't have any interface with a running minion on the system. It inits its own connection and does its own thing. So even if you have a running minion connected to an online syndic, it's not going to pick up that information, and instead is going to start from scratch.

That said, after the 60s timeout I feel like it should fall back to the next syndic in line. Is this not happening?

**Comment by chjohnst** [comment]
It runs for 60s, than times out, but cycles 7 times and than starts over again but it does not jump to the next one in the list.  I can try this again to be sure, but 60s * 7 is a really long time for an agent on restart to determine if its syndic is up.   Which I think is coming from this value below. 

# Number of consecutive SaltReqTimeoutError that are acceptable when trying to
# authenticate.
#auth_tries: 7

**Comment by basepi** [comment]
Does reducing this number fix your issues?
