### ISSUE TITLE
Best practice: How to keep pillars and states in sync for atomic deployments?

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#29074]
We have the following setup: 

* We have multiple environments (dev, qa, prd). 
* We have states and formulas that are placed in branches for these environments
* We have a separate pillar repo with the corresponding environments
* Or minions run highstate on a scheduled basis every hour

Now consider the following scenario:

If I make changes to a state in dev, that might change some existing configuration, it may add  a new configuration parameter and/or remove some old. I then have to update my pillar in dev in a corresponding fashion. So in other words, there is a strong dependency between the state and how my pillars are setup.

If I now push my changes from dev to qa, I must ensure that the pillars for qa matches the expected layout also. How do I do this in an atomic way?

* If I push the pillars first, then machines break if they run the highstate before I push my state changes
* If I push the state changes first, then machines break if the run the highstate before I push my pillar changes
* Even if I push my changes at the same time, there is still no guarantee that the master and/or minions will sync the changes in a consistent order.

So, how can I do a controlled deployment of anything using states and pillars? What is the best practice?

**Comment by basepi** [comment]
Hrm, this is a very good question, I hadn't thought of it from that angle before.

Honestly, if you're making changes that are that dependent on being atomic, I think my answer would be that you shouldn't use gitfs or git_pillar, but rather should just clone those repos onto the filesystem on the master. At this point you explicitly control when the master pulls from the server. You could even set up cron jobs on the master to pull from the server, and update both repos in the same command. Even the it's not truly atomic, but it's close enough IMO.

You could also set up some sort of versioning system in your pillar. Basically, have a pillar key which defines a version, and have the state system check for that version. If it doesn't match, the state run aborts. This would eliminate the need for atomic operations, as everything will have long since updated by the time the next highstate hits.

Thoughts?

**Comment by andrejohansson** [comment]
Hmm, even if I do get everything up to date on the master at the exact same moment. I still have the problems that the minion have two different loops for syncing states and pillars. Thus they can arrive at the minion at different times anyway.

I think (please confirm this) that highstate is designed to refresh both states and pillars before a run. Is this true?

What if one of them fails, does the highstate continue with a cached version then? If it does...could this be optional to enforce consistency. Eg: `salt <id> state.highstate refreshall=True allowcacheddata=False`

**Comment by basepi** [comment]
Sorry for my late reply here, I lost this in my many tabs.

If the pillar refresh fails, the master will abort. I am unsure of the behavior if the git pull on the states fails. Since it's refreshed in the main master loop I'm not sure the state system knows whether it has failed or not.

**Comment by andrejohansson** [comment]
Thanks for your reply, I think we can close this as an issue and add it as as a future feature request maybe? "Atomic operations". I understand this is a very tough one to implement.
