### ISSUE TITLE
[Docs] for cmd.run. Missing link to details for "stateful"

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#29154]
Current docs for cmd.run kwarg "stateful":

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#salt.states.cmd.run

> stateful:  The command being executed is expected to return data about executing a state

If you are new to salt, you don't get it.

Please provide a link from the kwarg docs to the docs which explain the details.

The same link needs to be made for "wait", "script", "wait_script".

**Comment by lorengordon** [comment]
The description of how to use `stateful` is in that same doc, in the beginning paragraphs because as you noted many functions in the module share the parameter.

- https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#execution-of-arbitrary-commands

Looks for this line and read from there:

> Many state functions in this module now also accept a `stateful` argument. If `stateful` is specified to be true then it is assumed that the command or script will determine its own state and communicate it back by following a simple protocol described below:

But yes, it would be helpful to make an anchored header for the stateful section, and link from the function docs to the anchor.

**Comment by jfindlay** [comment]
@guettli, thanks for the report.  We should add the links that @lorengordon suggests.

**Comment by guettli** [comment]
Thank you for fixing this docs issue.
