### ISSUE TITLE
External logging loads grains even if external logging is disabled.

### ISSUE THREAD

**Issue by adelcast** [saltstack/salt#29175]
The problem is that Salt is getting grains 2 times on startup, which sounds unnecessary. It gets grains on `setup_extended_logging` and Minion init. In our case, we don't have any extended logging enabled, but the way the code is written, grains are loaded anyway. To fix this, I think there are a few options:
- Add a `disable_external_logging` config token
- Implement a function `external_logging_available` that could:
  - Somehow call `__virtual__` on all the external handlers without loading them to check if there are any (not sure if it's possible)
  - Or check `__opts__` for the different config tokens for external logging

This is important since in our use case it will be common to have minions running in private networks (not registered with DNS). The grains load operation takes a long time since socket.getfqdn() is called (and it times-out before it defaults to what gethostname returns).  So, reducing the times grains are loaded is important.

After talking with @cachedout , seems like the most robust solution is to check `__opts__`. Any other opinions or possible solutions?

**Comment by s0undt3ch** [comment]
I'm thinking on adding an extra layer of complexity to the loader....
Deferred loader global variable evaluation, ie, when passing, for example, `'__grains__': <data>`, if said data is a callable, Its only evaluated on first use. In this case, since no handlers would be loaded, the data wouldn't be evaluated....

We could create a class which would get the function to call and its arguments with a `__call__` method which would evaluate and store the result for future uses...

Too much?

**Comment by adelcast** [comment]
I like the idea, as its generic and less brittle that checking __opts__ (adding new external loaders would require a code change on the conditional around the call to setup_extended_logging). But, it sounds pretty involved, @cachedout @jfindlay ?

**Comment by jfindlay** [comment]
@adelcast, @s0undt3ch has already written out more than I might have thought at this point.
