### ISSUE TITLE
Can't disable Job Cache?

### ISSUE THREAD

**Issue by harlanbarnes** [saltstack/salt#29286]
Hi - First off, thanks for all everyone does on this software! It is greatly appreciated.

My issue is that we seem to be unable to disable our job cache. Our salt version is:

```
salt 2015.5.4 (Lithium)
```

Our master configuration looks like this:

```
worker_threads: 10
open_mode: True
job_cache: False
keep_jobs: 0
fileserver_backend:
  - git
gitfs_provider: gitpython
gitfs_remotes:
  - git+ssh://git@github.com/notourrealcompany/salt.git
gitfs_base: master
pillar_roots:
  base:
    - /srv/pillar
```

My process to recreate is:

* Stop the salt-master process
* Remove all directories in `/var/cache/salt/master/jobs`
* Start up the salt-master process
* Lots of directories/uuids/jids return to the `/var/cache/salt/master/jobs` directory

Our use case here is that we have similar symptoms to #10443 and we don't see (or don't currently understand) what the job cache provides us. We've filled up our disk a couple of times and were looking for a more permanent solution than adding a cron task to remove older files in the cache.

Thanks again!

Harlan

**Comment by Grokzen** [comment]
I have seen the same problem kinda. I see alot of the following files that fills up the disk and takes up alot of inodes.

```
e0/bd421bb48fb37bebd0f0223ed3c90b           
e0/bd421bb48fb37bebd0f0223ed3c90b/.load.p   
e0/bd421bb48fb37bebd0f0223ed3c90b/jid       
e0/bd421bb48fb37bebd0f0223ed3c90b/.minions.p
```

Another thing i have noticed is that when the master jobs cache contains all of these files, restarting the sale master takes 1h or more before it starts becuase there is some sanity check at startup that goes through all files in the jobs cache and itterating over all those files takes forever.

**Comment by jfindlay** [comment]
@harlanbarnes, @Grokzen, thanks for reporting.  It seems that some more tuning needs to be provided for the master job cache, and possibly other salt auditing mechanisms.

**Comment by jakehilton** [comment]
I'm also seeing this with 2015.8.3. Seems to ignore the job cache settings and fills up inodes until the system is unusable.

**Comment by rallytime** [comment]
Hi all - After looking over this issue, I think what is happening here is a badly-documented option via the `job_cache` boolean. We can't "turn off" the functionality of creating jid directories in the `/var/cache/salt/master/jobs/` directory because Salt uses those directories to check for jid collisions.

What setting `job_cache: False` does is simply throw away the returns, but keeps the jids. So setting this value to False will reduce the size of the jid dirs, but won't disable their existence completely.

One thing you can do to reduce the size of the job cache dir is to set the cache cleaner to clean more regularly. You can do this by setting the [keep_jobs](https://docs.saltstack.com/en/latest/ref/configuration/master.html#keep-jobs) option to `1`. (Note that the `keep_jobs` option cannot be `0`, or the `local_cache.clean_old_jobs` function will not run.)

I think at the very least the docs for the `job_cache` option needs to be updated.

**Comment by rallytime** [comment]
Oh, also after testing the `keep_jobs` setting, the cache cleaner does remove the jid files from the jid dirs, but it doesn't remove the original directory that was created in `/var/cache/salt/master/jobs/`. 

For example (note that job_cache is set to the default of `True` in this case, and that jid dir `30` has been cleaned, but the newest job, `19`, has not been cleaned yet):
```
root@rallytime:~# ls /var/cache/salt/master/jobs/
19  26  30  51  91  92  d5  d6
root@rallytime:~# ls /var/cache/salt/master/jobs/30/
root@rallytime:~# ls /var/cache/salt/master/jobs/19/
f1cca89613752b2fb9a65b1450bec7
```
That particular behavior is a bug and should be fixed.

**Comment by rallytime** [comment]
@harlanbarnes I think the responses above, as well as my fix in #3328 should help alleviate the troubles you're having with the `job_cache` option. Please let me know if you have any questions or suggestions.

**Comment by harlanbarnes** [comment]
Hi @rallytime - Thanks so much for looking into my issue! Yes, I think this will do it. Again, I appreciate all the work the Salt team does! - hb

**Comment by rallytime** [comment]
Excellent! Glad to hear it. :)
