### ISSUE TITLE
file.managed doesn't manage file on windows

### ISSUE THREAD

**Issue by DenisBY** [saltstack/salt#29332]
```
----------
          ID: C:\Windows\System32\GroupPolicy\Machine\Scripts\Shutdown\remove_monitoring.bat
    Function: file.managed
      Result: True
     Comment: File C:\Windows\System32\GroupPolicy\Machine\Scripts\Shutdown\remove_monitoring.bat is in the correct state
     Started: 14:20:39.438000
    Duration: 47.0 ms
     Changes:   
----------
```

```
# salt 'i-0955e0b5' cmd.run 'type C:\Windows\System32\GroupPolicy\Machine\Scripts\Shutdown\remove_monitoring.bat'
i-0955e0b5:
    C:\Python27\python.exe C:\path\auto_monitoring.py -r --ec2_local_ipv4 10.x.x.x --ec2_instance_id i-0955e0b5 --host dev-win --shinken_host monitoring.eu-central-1.dev --key C:\\path\\shinken_key
```

But:

```
# salt 'i-0955e0b5' cmd.run 'cat C:\Windows\System32\GroupPolicy\Machine\Scripts\Shutdown\remove_monitoring.bat'
i-0955e0b5:
    cat: C:\Windows\System32\GroupPolicy\Machine\Scripts\Shutdown\remove_monitoring.bat: No such file or directory
ERROR: Minions returned with non-zero exit code
```

**Comment by lorengordon** [comment]
Is `cat` recognized in the cmd shell on Windows? I don't think I would expect that to work anyway. Though you could pass `shell=powershell`, as powershell aliases `cat` to `get-content`.

**Comment by DenisBY** [comment]
It doesn't matter. If I try to open file in Explorer it doesn't exist as well.
And yes, cat works on windows. At least on Windows Server 2012 R2.

**Comment by lorengordon** [comment]
Hmm, but by your own output, when you used 'type' it printed the contents of the file, right? Am I misinterpreting your OP?

`C:\Python27\python.exe C:\path\auto_monitoring.py -r --ec2_local_ipv4 10.x.x.x --ec2_instance_id i-0955e0b5 --host dev-win --shinken_host monitoring.eu-central-1.dev --key C:\\path\\shinken_key`

`cat` doesn't appear to work on ws2012r2 in the cmd shell.

![image](https://cloud.githubusercontent.com/assets/8457307/11534550/4c3106a6-98dd-11e5-8a33-384eba00889e.png)

It does work in powershell, because it is aliased to get-content.

![image](https://cloud.githubusercontent.com/assets/8457307/11534622/913b41a8-98dd-11e5-8d94-9466146c72f2.png)

**Comment by jfindlay** [comment]
@DenisBY, thanks for the report.  What version of salt are you using?

**Comment by DenisBY** [comment]
Hi,

```
# salt --version
salt 2015.8.1 (Beryllium)
```

**Comment by cachedout** [comment]
I'm confused by the same thing that @lorengordon is here. If you can display the contents of the file with `type` then it obviously exists and `file.managed` isn't broken.

@UtahDave or @twangboy can you shed some light on this with your Windows knowledge?

**Comment by twangboy** [comment]
I get the following on my windows box:

```
salt '<minion>' cmd.run 'cat c:\temp\caps.txt'
<minion>:
    'cat' is not recognized as an internal or external command,
    operable program or batch file.
```

type works as expected
