### ISSUE TITLE
Running a salt-cloud map should detect when instances are stopped

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#29427]
Currently, when running a salt-cloud map, it the instances are stopped but still have the same name, salt-cloud will not start them.

Salt-cloud should detect if the instances have the same size and start them if they are stopped.

**Comment by techhat** [comment]
I don't know how I feel about this. If I've explicitly stopped an instance, I don't necessarily want Salt Cloud to start it back up for me. It seems like adding a flag like `running: True` (like the `service` state's `enabled: True`) would allow me to better control this.
And since maps were never meant to be stateful, I think I would also prefer this to be in the `cloud` state instead of in maps.
