### ISSUE TITLE
state modules are no longer available.

### ISSUE THREAD

**Issue by paclat** [saltstack/salt#29501]
in the _states directory we had the file 

```
/srv/salt/_states/lcm_boostrap.py
```

that has a python call to...

``` py
def cleanup_formula_artifacts(name):
    do some stuff...
```

Under  `/srv/salt/boostrap` we have a file... `module_bootstap.sls`

That has in it a section that does...

``` sls
module_clean_up_{{ minion_id }}:
   lcm_bootstrap.cleanup_formula_artifacts:
       - name: {{ bs.formula_path }}
       - order: last
```

This code works properly on 2015.5.5.  
On 2015.8.x when we run this we get a module not found error.

**Comment by acgupt** [comment]
Executing custom state modules via  highstate with reload_modules seems to be working fine.

**Comment by jfindlay** [comment]
@paclat, thanks for the report.  Can you verify that the custom state has been synced to the minion before running it?

**Comment by paclat** [comment]
We modified the state to do reload_... as in below and that caused it to function now.  Is that a requirement with 2015.8.3

{{ minion_id }}_{{node_level}}_highstate:
  salt.state:
    - tgt: 'G@oracle_ops:master_level:{{node_level}} and G@oracle_ops:role:master'
    - tgt_type: compound
    - highstate: True
    - reload_modules: True
    - reload_grains: True
    - reload_pillar: True
    - order: 40
    - require:
        - sls: oracle-lcm-bootstrap.oracle-lcm-bootstrap

**Comment by basepi** [comment]
I don't think so. My bet is that there was something weird going on post-upgrade. I think if you removed those reload_ arguments and just did a `salt '*' saltutil.sync_all` it would probably work going forward.

**Comment by acgupt** [comment]
I see very weird behavior even with reload and sync_all  above issue happens  and and its random not reproducible every time and occurring only during high state, here context is just before custom state call there is  salt-master restart,sync_all and cleanup_formula_artifact call in order. My guess here is custom state has dependency on _utils and its not being loaded/not available during call  even after sync due to time in load just after sync? Is there a way to make sure salt has reloaded  state module and call once its available ?

**Comment by basepi** [comment]
Hmmm, that does sound like there may be a race condition of some sort involved....
