### ISSUE TITLE
Building RPMs from the Git sources?

### ISSUE THREAD

**Issue by jefferyharrell** [saltstack/salt#29637]
I can't emphasize this strongly enough: I'm a complete noob.

So #29546 has been fixed and that's fantastic. I know that the fix won't be rolled out into a release for some time, and that's fine. But I can't put Salt into production without the fix, so I need at least to try it out and see if the 2015.8 branch is stable enough for our purposes.

For the past couple days I've been trying to follow the [hacking instructions](https://docs.saltstack.com/en/latest/topics/development/hacking.html), and I've more or less got that worked out on my Salt masters … but the trouble is my minions. Setting up a clone of the Git repo and installing the latest 2015.8 branch into its own virtual env on each minion strikes me as being impractical at best!

So what I _want_ to do is build RPM packages for CentOS and whatever is the best package format for OS X (I haven't gotten that far yet) from the Git sources then distribute them internally. When a new fix becomes available that I want to incorporate, pull the repo, rebuild the packages, push them to the minions. Easy … in principle.

Trouble is I can't figure out how to build the RPMs. Under [salt/pkg/rpm](https://github.com/saltstack/salt/tree/develop/pkg/rpm) there's a spec file, but it hasn't been updated for nine months and it still refers to version 2014.7. So my guess is that that's not the right way to build RPMs.

Am I missing something obvious? Is there a canonical Right Way™ to build packages that I'm just not seeing?

Thanks very much for any guidance you might have.

**Comment by lorengordon** [comment]
If you don't *need* the RPMs and are ok with building from source, you might want to look at the [salt bootstrap](https://github.com/saltstack/salt-bootstrap). That will allow you to install from a branch on the git repo.

**Comment by githubcdr** [comment]
It would be really nice if nightly packages would be available in an automated build, Salt is moving fast but packaging is sometimes slow.

**Comment by jefferyharrell** [comment]
@lorengordon I'm going to look more closely at the bootstrap, but the virtue of RPMs in my situation is that they can be cleanly installed *and removed.*

Here's what I mean: In 477c233365073f415701a8b8ec65a854cbf9d7d5 two new files were added; doesn't matter what they are, I'm just using that commit as an example. Now say I decide to deploy some in-development version of Salt on my minions that's based on a commit *after* 477c233365073f415701a8b8ec65a854cbf9d7d5. My minions will get those two new files installed in `/usr/lib/python2.7/site-packages`.

But what if I want to roll back to an earlier version, or even all the way to the 2015.8.3 tag? I'll have to make sure somehow that the two new files created in 477c233365073f415701a8b8ec65a854cbf9d7d5 are *removed* from all my minions, as well as any other new files that were part of the later version but that are absent in the earlier version to which I'm rolling back.

If I have RPMs, this is no problem; Yum (on my CentOS systems) will take care of that for me, removing the files that shouldn't be there automatically. But with any other type of install, like a script, it becomes an exercise in consistency checking to make sure that *only* the files provided by the *desired* version of Salt are present on both the masters and the minions. On the masters, I can see myself handling that manually by using virtualenv, but on the minions … ugh. And as I alluded before, that doesn't even get into the OS X situation, which I haven't touched yet.

I have *zero* experience doing RPM packaging, and I was hoping that somebody had already cracked this nut. I'm not crazy-go-nuts about the idea of learning it all from scratch and building my own in-house software packaging system. But I'm kind of at a loss for a good alternative right now.

Thanks for your suggestion, though. I will study the bootstrap script very carefully.

**Comment by abednarik** [comment]
The easiest way to build RPM's is to use a Ruby gem called FPM https://github.com/jordansissel/fpm

Hope this helps.

**Comment by jfindlay** [comment]
@jefferyharrell, I am not sure why the spec file in the repo is out of date.  I think it should be kept up to date, but consider that successfully building and using salt packages on your own isn't going to be as simple as packaging salt itself.  Consider https://github.com/saltstack/salt-pack, for example, which is how SaltStack builds release packages, since building salt RPMs from source is not just as easy (or not) as running `rpmbuild` against salt's spec file.  Invariably, there will be a payload of dependencies to worry about, each with their own versions and requirements sagas.

Allow me to complain more generally for a moment.  Currently salt has too many variations on installation methods: pip, git, pip+git, bootstrap, which can source from git or packages, and ordinary distro packages.  The direction we are moving in is for package-based installs for all installation vectors, but this is a multipart effort that requires work on various salt and saltstack infrastructure pieces, such as updating bootstrap to install packages for a requested version and installing from git only if explicitly allowed.  The public release of https://github.com/saltstack/salt-pack is a significant step in the full automation and maintenance of https://repo.saltstack.com/, including, although not directly related to, automated daily builds.

**Comment by jefferyharrell** [comment]
@jfindlay, thanks very much for the link to salt-pack. It's interesting, to say the least. Pretty daunting, though. In our facility we use only Red Hat-type Linux and OS X, so my first inclination would be to debride everything except the parts that generate Red Hat-compatible packages, but that seems like it'd be a lot of work since everything is interdigitated. But I'll study it further and see what I can come up with.

In the meantime, yesterday I spent the day hacking on `pkg/rpm/build.py`, on the assumption that at least in the past it had been useful. I ended up pretty much rewriting it from scratch. Between that and updating the `.spec` file, I got a process that *basically* works for building RPMs through `rpmbuild`. I'm sure it's full of holes, but at the moment it seems to work okay. https://github.com/Charlieuniformtango/salt/commit/bd14b63477e0bb22a6ae87227b06780be427f7f0, if you're curious.

I'm going to keep banging on all this and see what I can make of it. Thank you again, very much, for the link to salt-pack.

**Comment by jfindlay** [comment]
@jefferyharrell, I didn't know `pkg/rpm/build.py` existed until you mentioned it.  The git blame shows that it has been 2.5 years since it was last updated.  If this build method is working for you, then I am glad, but if you have resources to devote to salt packaging, I suggest considering salt-pack as this is the architecture upon which we hope to focus both salt community and enterprise efforts on packaging.  The spec file(s) in salt-pack are uptodate and are the live versions used by SaltStack in building packages.  If you need any guidance or have any questions, please ask and we'll do our best to move this work along.

**Comment by jfindlay** [comment]
Also have a look at `modules/rpmbuild.py` and `states/pkgbuild.py` in the `develop` branch of salt.

**Comment by jfindlay** [comment]
I also suspect that your use case could be solved much more easily by daily rpm builds.

**Comment by jefferyharrell** [comment]
@jfindlay I think you're right, that at least MOST of what I need could be satisfied by daily (or whatever) packages. While I can imagine, in the abstract, that it'd be nice to be able to roll my own package that incorporates some local, in-house-only change, that really doesn't seem like something we'd want to do in real life. Right now everything I'm doing revolves around wanting to get a version of Salt deployed in our facility that incorporates the fix to #29546, since that issue is a stopper for us.

As you say, I'm going to look more at salt-pack and see what it can do for me. In the meantime, once you guys get nightlies or whatever up and running, I will be very happy to use them.

Thanks as always.

**Comment by jefferyharrell** [comment]
@jfindlay, I've had a good look at salt-pack this morning but it's left me stumped. The way it's assembled certainly looks elegant but even after a couple months I'm still not sufficiently fluent in SLS/Jinja idioms to be able to sight-read the salt-pack state files. The bottom line is this: trying to build *any* of the packages throws a key error and I haven't figured out why. The output is enormous so I squirreled it away here: https://gist.github.com/jefferyharrell/eb18a9324cb85a545211. I'm totally aware that salt-pack is a work in progress so I'm not screaming "bug report!" or anything. Just putting it out there.

Ironically, my first instinct is to suspect that building Salt is failing on my system because I'm not running a sufficiently recent version of Salt. That'd be pretty funny.

**Comment by tbaker57** [comment]
@jefferyharrell - According to your gist
```
13:33:55.297 20204: DEBUG: Could not LazyLoad pkgbuild.build
```
most likely means that  (looks like your on RHEL7) rpmdevtools, createrepo and mock are not installed on the system (there's ongoing work in https://github.com/saltstack/salt/wiki/December-2015-Sprint-Beginner-Bug-List to make the module loading mechanism provide more detailed errors as to why the module failed to load)

cheers,
Tim

**Comment by jefferyharrell** [comment]
Yup, that's exactly what it was. I didn't have the necessary prereqs installed. Thanks for that.
