### ISSUE TITLE
salt-api rest_cherrypy /ws websockets get killed by Chrome

### ISSUE THREAD

**Issue by bmcorser** [saltstack/salt#29914]
Trying to stream events to the browser and `rest_cherrypy` looks very promising. I can connect using a Python WebSockets client (as in the docs), but I'm blocked on Chrome's behaviour as regards "masking". I don't know the protocol well, but some Googling seems to point in the direction of the default ws4py stream setting of `always_mask=False` getting overridden somewhere (perhaps by an unrelated CherryPy thing) and causing "masked frames" to get sent to the client (my browser) which means I see the following message:
`WebSocket connection to 'ws://.../ws/...' failed: A server must not mask any frames that it sends to the client.`

Perusing the code, I can't see anywhere `always_mask` is overridden; the Salt subclass of `ws4py.websockets.Websocket` doesn't appear to touch the default for `self.stream` which is where the option would be passed.

I appreciate this is a bit of a chore to reproduce, so I'm going to have a bash with the `rest_tornado` server in the mean time `:)`

**Comment by whiteinge** [comment]
Thanks for the report. The websockets addition needs a bit of love (in both rest_cherry and rest_tornado modules).

If you don't need real-time _bidirectional_ communication take a look at the [/events](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.app.html#salt.netapi.rest_cherrypy.app.Events.GET) endpoint instead of the websockets interface. It allows you to receive real-time events from Salt and you can still make regular ajax requests when you need to send commands to Salt.

The main benefit of SSE is it is _extremely_ simple and robust. Whereas websockets have a metric ton of moving parts by comparison. There's a JavaScript example in the docs but I'll repeat it here since they're a little malformed at the moment for some reason.

```javascript
# Authenticate to salt-api before making this connection or you'll get a 401.
var source = new EventSource('/events');
source.onopen = function() { console.log('opening') };
source.onerror = function(e) { console.log('error!', e) };
source.onmessage = function(e) {
    console.log('Tag: ', e.data.tag)
    console.log('Data: ', e.data.data)
};
```

That's _it_.

You can send jobs async (fire-and-forget via the `local_async`, `runner_async`, `wheel_async` clients) since you'll see the job return come back in real-time via the event stream.

The websockets interface should be fixed, of course. But the SSE interface has seen the lion's share of attention thus far. It maps extremely well to how Salt itself works: sending async commands from the master to minions then listening for job returns.

**Comment by bmcorser** [comment]
Thanks for giving such a comprehensive reply, I wasn't aware of SSE. It
covers my need very well.

I'm happy to close this issue, but will leave it to you guys ...

**Comment by whiteinge** [comment]
Glad to hear SSE will work for you!

The websockets problem is definitely a bug so let's keep this open
until it can be prioritized and fixed.

**Comment by onlineque** [comment]
Hello, I think the bug is still there.
Tested against:
# salt --version
salt 2018.3.3 (Oxygen)

Is there still a chance it will be fixed ? Thanks beforehand !
