### ISSUE TITLE
Salt 2015.5.3 - VALUE_TRIMMED

### ISSUE THREAD

**Issue by my10c** [saltstack/salt#29992]
Somehow output of command are getting trimmed
before the upgrade to 2015.5.2/2015.5.3 I was able to display large output, like tar -ztvf data.tgz
but now this no longer works

I end up changing the the master and minions value to max_event_size to 5242880
however Im getting timeout and sometime : segmentation fault (core dumped)
deeper check: the system ran out of memory (thsi as a vm with 1GB of memory), upgrading
the vm with 2G and the problem goes way

So maybe the module should send/log a better error when this happen?

**Comment by lsuryo** [comment]
more test : if i keep doing this over and over again : Im getting 

```
 Minion did not return. [No response]
```

**Comment by cachedout** [comment]
If the system runs out of memory and python segfaults, throwing an error message from Salt isn't realistic. Could you elaborate a little more on your use case? I'm trying to understand what you're doing here. There might be a better way to accomplish what you need.

**Comment by lsuryo** [comment]
Hi Mike,

That was my first thought, and so I added more memory, and the problem was solved.
Use: case a t2-micro instance in AWS to test simple salt stuff with 3 minions. In the past
this was never a problem...

The 'thing'  is that  the error message was not very helpful, I *think' it would has been nice to
see a out of memory error. Make sense?

As always thanks!

**Comment by phil123456** [comment]
how did you "add more memory" ? do you mean to the machine ?

**Comment by luc-poynt** [comment]
Yes upgrade the instance with one that has more memory
