### ISSUE TITLE
Force salt-cloud to use TLS1.2 in SSL client hello

### ISSUE THREAD

**Issue by Pancm** [saltstack/salt#30104]
Greetings, 

As TLS1.0 is becoming deprecated some hosting providers are disabled connections initiated by client implementations using TLS1.0. 
salt-cloud when being invoked sends the SSL client hello with TLS1.0 and our hosting provider terminates the connection because of that.

Is it possible to force salt-cloud to initiate the SSL connections using TLS1.2?

**Comment by techhat** [comment]
Hi @Pancm. Different drivers in Salt Cloud use different connection libraries. At the very least I know we span requests, urllib2, Tornado, and libcloud. For each of those that have a way to specify the TLS spec, we can add code to do that.

**Comment by Pancm** [comment]
Hi @techhat, moving away from TLS1.0 would be immensely helpful as;
- TLS 1.0 is no more considered PCI compliant
- API connections go exclusively through HTTPS

We are unable to use our deployment scripts since a few days now which use salt-cloud together with the api interface of our hosting provider because of this. 
I think we could expect more problems like this emerging as more vendors will disable client tls1.0 connections.

**Comment by techhat** [comment]
Salt Cloud is not a connection library. Each individual module uses another library to communicate with cloud providers. Sometimes that library is a connection library (urllib2, requests) and sometimes that library itself uses another connection library (Azure, pyvmomi).
It should not be assumed that just because a connection library supports the latest TLS version that a cloud provider also supports it. Once it has been verified that both provide the necessary support, then all that Salt Cloud can do is flip the switch to turn it on.

**Comment by Pancm** [comment]
Greetings, 
This issue can be closed as "invalid" or "wont fix" as upgrading the underlying connection library helped to resolve the issue.

**Comment by techhat** [comment]
Thanks for the update @Pancm.
