### ISSUE TITLE
Module "minion.list" don`t work if the root_dir of the master is different than the minion

### ISSUE THREAD

**Issue by andygrunwald** [saltstack/salt#30174]
In https://github.com/saltstack/salt/pull/28664 i added a new module called `minion.list`.
The goal is to "emulate" `salt-key -L` to be able to get all minions by REST-API.

The module is built to run on the salt-master only, but accessible by REST-API (like cherrypy).

In the module we ask for the `pki_dir`. The `root_dir` is a prefix of the pki_dir.
If we execute the module, it will be executed by the minion that runs on the master.
That means we get the `root_dir` / `config_dir` of the minion.
The information about the registered minions are stored in the `pki_dir` of the master.
If the master has a different root dir configured as the minion the module return an empty list.

Question:
It is possible to request configuration settings of a master by a minion?

Take in mind: This module will be (always) executed on a master machine.

**Comment by jfindlay** [comment]
@andygrunwald, master information is hidden from minions for security reasons, so the minion will have to look this up using its own resources.  Since your minion is running on the same system as the master it should have access to everything you need.  I think there is a way to get the master opts in a masterless minion context, although I am unsure what the best way is to send this to an execution module.  @cachedout would have a much better answer than I.
