### ISSUE TITLE
dockerng run attach

### ISSUE THREAD

**Issue by adithep** [saltstack/salt#30199]
Is it possible for dockerng to start a container via state or module and attach the output to the console until the container stops? In my workflow many container just needs to run once until it stops, then start another state.

If not, is this a viable feature?

**Comment by terminalmage** [comment]
Have you tried using ``detach=False`` when running ``dockerng.create``?

**Comment by adithep** [comment]
Yes I did. And it does not work. This is my sls:

    fillvol:
        module.run:
            - name: dockerng.create
            - detach: False
            - kwargs:
                name: fillvol
                image: hostname/username/git
                client_timeout: 50000
                detach: False
                interactive: True
                tty: True
                cmd: /command.sh
    fillvol-s:
        module.run:
            - name: dockerng.start
            - kwargs:
                name: fillvol

And this is the result of start:

    ID: fillvol-s
    Function: module.run
    Name: dockerng.start
    Result: True
    Comment: Module function dockerng.start executed
    Started: 04:11:52.463182
    Duration: 323.883 ms
    Changes:   
              ----------
              ret:
                  ----------
                  result:
                      True
                  state:
                      ----------
                      new:
                          running
                      old:
                          stopped

It doesn't wait for docker to stop nor does it log any output to the console.

**Comment by terminalmage** [comment]
OK, thanks. I'll have to investigate further, this may be a docker-py limitation. Can you let me know the versions of docker and docker-py that you have installed?

**Comment by adithep** [comment]
Docker version 1.9.1, build a34a1d5
docker-py==1.6.0

**Comment by terminalmage** [comment]
Thanks! I'll let you know what I find. It's possible that docker-py's Client.start() function doesn't wait to return even when attached to stdout, in which case this is probably not possible at this time. If that is the case, then opening an upstream feature request with docker-py would be the next step.

**Comment by terminalmage** [comment]
@adithep As I thought, docker-py returns immediately after issuing a call to the [docker.Client.start()](http://docker-py.readthedocs.org/en/stable/api/#start) function. Additionally, this function returns ``None`` so there is no actual API response for us to interpret.

This doesn't look to be supported by docker-py, and may not even be supported at all in the Docker Remote API.

**Comment by terminalmage** [comment]
It appears that the documentation for docker-py has been updated in the time since the last comment on this issue, it now states explicitly that the attach options are not supported: https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.create_container

@adithep @artem-panchenko you may be interested in the new [docker_container.run](https://docs.saltstack.com/en/develop/ref/states/all/salt.states.docker_container.html#salt.states.docker_container.run) state (new to the upcoming 2018.3.0 release), which is like the `cmd.run` state but for docker containers. The way it handles blocking (in a way that the `docker_container.running` state does not) is by using docker-py's `logs()` API call, which returns a generator of lines of output from the container. This generator only stops iteration when the end of the output has been reached (or when the container exits, if it produced no output).
