### ISSUE TITLE
Persist / retrieve contents of event.send in a scalable environment?

### ISSUE THREAD

**Issue by mmisztal1980** [saltstack/salt#30421]
Hi again,

I have the following scenario:

- I'm supposed to manage a scalable pool of minions
- Each minion is going to have a shared grain and the whole pool is going to be targeted using that grain
- The reactor system is going to be used to handle certain events :
    - The said events will be treated as a change of the environment's state
    - The said events will deploy new configuration files to the scalable minion pool

In an occurence, where the minion pool size is increased, I'd like the new minion to retrieve the list of events that has already been applied to the other members of the pool.

It is my understanding that I need to persist both the event data and the cofig file(s) somehow?

How can I achieve that?

**Comment by jfindlay** [comment]
@mmisztal1980, thanks for the question.  Without more knowledge of your requirements and setup, I would say that you should be able to achieve this with a simple highstate that is applied as each minion joins the pool.  Config files can be served through [`file_roots`](https://docs.saltstack.com/en/latest/ref/configuration/master.html#file-roots), but you'll need to describe how and where they are installed in an sls file.  If you really want to replay previous events, you should be able to get them from the [`master_job_cache`](https://docs.saltstack.com/en/latest/ref/configuration/master.html#master-job-cache), but you would have to do some custom returner work in order to persist the events you want to save from the potential torrent of ephemeral other events.

**Comment by mmisztal1980** [comment]
Thanks :) I'll read those docs :)
