### ISSUE TITLE
Cloning linode server with salt-cloud fails trying to create disk config

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#30444]
Running salt 2015.8.3. I think when a machine is cloned with Linode, the config is automatically configured based off of the existing machine. So when salt attempts to create a new disk config, it gets the following response:

```
{u'ACTION': u'linode.disk.createfromdistribution', u'DATA': {}, u'ERRORARRAY': [{u'ERRORCODE': 8, u'ERRORMESSAGE': u'You do not have enough unallocated storage to create this Disk (24448 requested, but only 0 available)'}]}
```

and throws the following exception:

```
[ERROR   ] Failed to create VM prd-core-cache4. Configuration value 'DiskID' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1249, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/linode.py", line 444, in create
    root_disk_id = create_disk_from_distro(vm_, node_id)['DiskID']
KeyError: 'DiskID'

```

It might be necessary to list the configs when cloning instead of trying to create a new config. I don't think deleting the existing config is an option, because the linode utilities use that to migrate the disk from the cloned node.

**Comment by rallytime** [comment]
@dnd Good catch. We'll get this cleaned up.

**Comment by rallytime** [comment]
In addition to fixing up many issues with the cloning functionality in the linode driver, as outlined in #30432 and specifically [this comment](https://github.com/saltstack/salt/issues/30432#issuecomment-173649971), I've also fixed the issue where the `config_id` was being generated for clones. As you've pointed out @dnd, this isn't necessary since Linode provides a `config_id` for the new VM via the to-be-cloned VM.

See #30508 for more information.

**Comment by dnd** [comment]
Awesome, thanks!
