### ISSUE TITLE
Adding new MySQL users with multiple hosts

### ISSUE THREAD

**Issue by xenuser** [saltstack/salt#30476]
The Salt state module mysql_user should be able to accept multiple hosts parameters and then translate this into adding the user multiple times, but of course with different hosts.

The same goes for the mysql_grants state module.

Example:

``` sls
frank:
  mysql_user.present:
    - host: 10.0.0.1
    - host: 10.0.0.2
    - password: TOPSECRET
  mysql_grants.present:
    - grant: select
    - database: secretdb
    - user: frank
    - host: 10.0.0.1
    - host: 10.0.0.2
```

This would really help since it is not possible to define the user "frank" multiple times within a high state (please correct me if I am wrong).

**Comment by jfindlay** [comment]
@xenuser, thanks for the report, this does not seem to be currently possible, although the syntax will likely be (since arg names to state functions must be unique):
```sls
frank:
  mysql_user.present:
    - hosts:
      - 10.0.0.1
      - 10.0.0.2
    - password: TOPSECRET
  mysql_grants.present:
    - grant: select
    - database: secretdb
    - user: frank
    - hosts:
      - 10.0.0.1
      - 10.0.0.2
```

**Comment by xenuser** [comment]
@jfindlay Thanks for your fast reply! Do you think that there is a general interesting in including such a thing in SaltStack? I would find it very useful and I'd use it very often. I bet that others will aswell.

**Comment by jfindlay** [comment]
@xenuser, good question.  This particular change shouldn't be too hard, but the limiting timescale factor is currently development resources.  Putting it into the `Help Wanted` category both indicates that it should be a simple fix or enhancement and that because of this community developers are encouraged to work on it.

**Comment by abednarik** [comment]
Hi all

 I'm working on this. Code to support multiple hosts is not that hard. I just need to figure out how to handle and format ret['comment'] since today is prepared to only handle one user and we need to report multiple users with maybe different results.
 I will do a PR, just to show my progress and get suggestions/feedback to follow the correct path.

**Comment by xenuser** [comment]
Thanks a lot @abednarik! Really looking forward to your change.

Recently, I asked the same question on serverfault and someone found a workaround:
http://serverfault.com/questions/750529/adding-mysql-user-with-different-hosts-in-saltstack

I remember trying it the same way, but back then, it didn't work (but I can't remember why exactly).

This is how ahus1 did it:
`frank_10.0.0.1:
  mysql_user.present:
    - name: frank
    - host: 10.0.0.1
    - password: topsecret
  mysql_grants.present:
    - grant: select
    - database: secretdb.*
    - user: frank
    - host: 10.0.0.1

frank_10.0.0.2:
  mysql_user.present:
    - name: frank
    - host: 10.0.0.2
    - password: topsecret
  mysql_grants.present:
    - grant: select
    - database: secretdb.*
    - user: frank
    - host: 10.0.0.2`

**Comment by abednarik** [comment]
Thanks for that @xenuser. Like I say before, making the code to support multiple hosts is not that hard. The issue here is when for example salt runs and create 2 users and then fails trying to create another one. Is that Ok? Don't think so...is that a error? yes, but partially the action was executed correctly.

**Comment by xenuser** [comment]
Sorry for the late reply, I completly forgot that I had to reply here.

> The issue here is when for example salt runs and create 2 users and then fails trying
> to create another one. Is that Ok? Don't think so...is that a error? yes,
> but partially the action was executed correctly.

I believe this should be handled like everywhere else (e.g. when Salt tries to create 10 files within different directories, I believe that it will still create the other ones if one file failes (e.g. because a parent directory does not exist).

**Comment by leeclemens** [comment]
@abednarik imo, if it fails in any way, it should set the result to False. The changes key can show which components were changed (old 0 users, new 1 user). Do you have something working in a branch? If so, can you push it to your public account?
