### ISSUE TITLE
Feature: bypass SSL cert validation for vsphere host

### ISSUE THREAD

**Issue by cournape** [saltstack/salt#30501]
This may be a a controversial request, but would it be possible to optionally   bypass cert verification w/ the vmware driver ? This prevents us from using the vmware driver (from the deprecated vsphere).

**Comment by cournape** [comment]
OK, looking at https://github.com/saltstack/salt/issues/29537, I see that this is linked to me using `pyvmomi` `6.0.0`.

But to my horror, downgrading to `5.5` now makes the connection work by default. I am not security expert, but should not that fail by default and cert validation being bypassed only as an optin ?

**Comment by nmadhok** [comment]
@cournape Most people use self signed SSL certs on their vcenter or ESX servers which is the reason that by default the certificate that is presented to the salt-cloud VMware drive is accepted by default.

**Comment by cro** [comment]
@cournape It depends on which Python you are using.  Pythons before 2.7.9 (or 2.7.5 in Cent7, which has the ssl stack backported from 3) actually could not check certificate validity, so pyVmomi 5.5 doesn't check it either.  There isn't really a lot we can do about this for pyVmomi 5.5.  We're struggling with 6.0 because it drops support for Python 2.6 as well, but we still support many customers on 2.6 (Cent/RH6 both have 2.6).

We're entertaining the idea of adding an `ignore_ssl` flag to the provider block for users on pyVmomi >= 6 and defaulting it to False.

**Comment by cournape** [comment]
@cro: I am aware of python differences w.r.t. SSL behaviour, and was confused by pyVmomi behaviour. As a linux distributor myself, I am aware of the struggle w/ python 2.6 and old distributions.

Disabling SSL cert validation as an opt-in sounds like the good default to me as well. I would be happy to test this

**Comment by rallytime** [comment]
I think the `ignore_ssl` flag makes sense. When this is implemented, it would mean a change in current behavior (since the default would need to be `False`), and that would need to be documented heavily.

We also need to be cautious in terms of making sure this change works both with the VMware salt-cloud driver and with the ESXi Proxy Minion.

**Comment by steverweber** [comment]
i also felt there should be an `ignore_ssl` option,

**Comment by estheban** [comment]
:+1:

**Comment by dahrens** [comment]
+1

**Comment by jpsv** [comment]
I could use this as well.

**Comment by rallytime** [comment]
@Ch3LL or @garethgreenaway can you open this one again?

**Comment by ggiesen** [comment]
Any updates on this one? It's painful to deal with when trying to stand up a new vSphere environment using Salt. Even adding the host certs to the trusted store doesn't help as the ESXi default certs expired in 2012.

**Comment by whytewolf** [comment]
this request should be submitted to https://github.com/saltstack/salt-ext-modules-vmware as that is where the vmware modules and support has been moved. Please add the feature request there. 

closing here as the vmware extension is the place of truth for the vmware modules.
