### ISSUE TITLE
[salt-cloud] config parameter in lxc_profile raises AttributeError

### ISSUE THREAD

**Issue by fuzzy-id** [saltstack/salt#30576]
Hi there,
I'm fairly new at salt and still a bit confused about runners, modules, etc. But I think I stumbled over a bug when trying to initialize a LXC container via salt-cloud. The following holds for both the salt-master and the host i try to create the container on:

```
# salt --version
salt 2015.8.3 (Beryllium)
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```

I have the following files:

``` yaml
# /etc/salt/cloud.providers.d:
host03_lxc:
  target: host-03.example.com
  driver: lxc
```

and

``` yaml
#  /etc/salt/cloud.profiles.d/lxc.profile.conf
ubuntu_trusty:
  lxc_profile:
    template: download
    options:
      dist: ubuntu
      release: trusty
      arch: amd64
    backing: btrfs
    # config: /etc/lxc/default.conf
  minion:
    master: 10.0.3.131
```

The given configuration works as expected. But if I comment out the `config` line in `lxc.profile.conf` I get the following error:

```
[INFO    ] Creating container(s) '['bar']' on host 'host-03.example.com'
Exception occurred in runner lxc.cloud_init: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/lxc.py", line 429, in cloud_init
    saltcloud_mode=True, quiet=quiet, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/lxc.py", line 319, in init
    name = kw.pop('name', name)
AttributeError: 'str' object has no attribute 'pop'
```

My first guess is that it has to do with some parameter overlapping in `lxc.create` and `lxc.init`. Because this one succeeds:

```
# salt host-03.example.com lxc.create foo template=download options='{"dist": "ubuntu", "release": "trusty", "arch": "amd64"}' backing=btrfs config=/etc/lxc/default.conf
```

But this one fails:

```
# salt host-03.example.com lxc.init foo template=download options='{"dist": "ubuntu", "release": "trusty", "arch": "amd64"}' backing=btrfs config=/etc/lxc/default.conf
host-03.example.de:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1039, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/lxc.py", line 1379, in init
        salt_config = _get_salt_config(config, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/lxc.py", line 221, in _get_salt_config
        config.setdefault('master',
    AttributeError: 'str' object has no attribute 'setdefault'
```

**Comment by jfindlay** [comment]
@fuzzy-id, thanks for the report.  This seems to be a bug with the lxc driver.

**Comment by pass-by-value** [comment]
Hi @fuzzy-id 

Could you please try with a cloud profile resembling the following?

```yaml
ubuntu-lxc:
  provider: dev-lxc
  lxc_profile:
    template: ubuntu
    #backing: lvm
    #size: 4G
    #vgname: main
    options:
      release: trusty
      arch: amd64
  script_args: -P
  bootstrap_delay: 62
  uses_systemd: False
  network_profile: ubuntu
  minion:
    master: localhost
```

Please let me know how it goes.

**Comment by fuzzy-id** [comment]
Could you elaborate a bit more on what you want me to do? I copy-pasted the snippet into `/etc/salt/cloud.profiles.d/lxc.profile.conf` and ran
```
# salt-cloud -p ubuntu-lxc foo 
[INFO    ] salt-cloud starting
host-03.example.com
    True
[INFO    ] Runner completed: 20160125220148388045
[ERROR   ] Profile ubuntu-lxc is not defined
Error:
    Profile ubuntu-lxc is not defined
```
I guess this is not what you were asking for.

My actual motivation is to run containers unprivileged. That's why I wanted to point to a configuration file `/etc/lxc/default.conf` containing something like
``` ini
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
```
Could this be accomplished in some other way?

**Comment by pass-by-value** [comment]
Hi @fuzzy-id, I'm so sorry about the unclear reply. 

I found [this page](http://docs.saltstack.cn/en/latest/topics/cloud/lxc.html) that mentioning the use of `lxc_conf` section. That _should_ let you specify configurations. 

There is also the lxc module that has an [edit function](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.lxc.html#salt.modules.lxc.edit_conf).

I tried both the above but they didn't work for me.

If anyone familiar with lxc modules and runners has some experience with this please feel free to add to this discussion.

@fuzzy-id  Until then the only thing I could think of  is to update `/var/lib/lxc/foo_bar/config` by hand (which is not optimal, of course).

**Comment by Sjd-Risca** [comment]
Dear programmers, I get kind of the same issue as describe here. First I should apologize for the long answer, but the issue is from my point of view a not optimal interface configuration. Therefore it is not only about solving a bug, but  it is more about **deciding what we want and what we need**. And with hurry, please!

## How it works

Here I'm describing what the code does and what it is missing.
For container creation the default function is **lxc.create** . With this function is possible to:
 * select an lxc template from file (by parameter config)
 * select directly some custom options (like parameters size, image, nic_otps) or indirectly by calling a template (parameters profile and network_profile).

This is a correct implementation because the lxc.create function is just mapping the lxc-create program which could get just those options.

On the other site there is the cloud provisioning that instead works through the **lxc.init** function. In this case the init function is a front end of the lxc.create (for proper host creation), the lxc._LXCConfig (for setting host parameters) and lxc.bootstrap (for installing salt-minion in it).
As it is possible to see from the code (or from the documentation) all of the cloud provisioning parameters are the ones allowed in the lxc.init function (and therefore in its derivates).
About the config parameter, it is clear that it refers to the minion config that is used for setting up the salt-minion via lxc.bootstrap function (and not about the config parameter in the lxc.create as indeed expect by whom has this bug filled!).
The config parameter of lxc.create is instead used by lxc.init for setting - passing through lxc._LXCConfig - all of the options forecast by the lxc module. By now the option dealt by _LXCConfig are still only a few and therefore it is still not possible to set lot  of parameters. 

## What to do
From my point of view, considering that probably it won't be possible to cover all of the lxc available options, it should be allowed through lxc.init function, and therefore via the cloud provisioning system, to:
 * add some parameter from a custom file (like /etc/lxc/default.conf exactly as it is possible via the lxc.create function)
 * let add some custom parameter through _LXCConfig (without check from salt)
 * make the _LXCConfig function more complete of actual lxc configuration options

About the _LXCConfig available option I think that it is to consider that some of them (like id.map, or vgname) could be host aware while others (like image, size, memory) host aware.
