### ISSUE TITLE
Make packaging/build processes for repo.saltstack.com more transparent

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#30735]
Right now, it's completely intransparent to the consumers of `repo.saltstack.com` what's happening with the packaging and builds behind the scenes:
- why are there only packages for Ubuntu LTS releases (currently `12.04` and `14.04`)?
- why are there no up-to-date builds the moment a new release was announced?

If the build process would be more transparent, people could see the reasons for those issues and submit PRs to fix them. Right now, people are left in the dark why there are no up-to-date packages after a new release has been announced or why a certain distribution release is not covered.

**Comment by jfindlay** [comment]
@eliasp, all of your concerns may be resolved by [salt-pack](https://github.com/saltstack/salt-pack).  The reason there are only 12.04 and 14.04 on repo.saltstack.com is because we have limited packaging resources.  The reason there are not up to date packages in ubuntu's repos is that we've lost our community and ubuntu currently has no one on the saltstack packages.  @babilen has offered to work on updating the debian repos, but if you know of anyone who could do ubuntu, please let me know.

**Comment by anlutro** [comment]
When the recent Debian package issue (https://github.com/saltstack/salt/issues/30696) surfaced, I was surprised to find no references to the 2015.8.4 package in the salt-pack repository, nor any references to the dependencies that screwed things up. I hope it's just because someone didn't `git push`.

**Comment by babilen** [comment]
@anlutro I'm quite sure that that's exactly what happened. Would @dmurphy18 be the right one to poke about this?

**Comment by dmurphy18** [comment]
@anlutro @babilen Everything used to build open-source salt is available via github: 

https://github.com/saltstack/salt-pack

It is open-sourced and contributions are welcome, similar to salt on github.

It was open-sourced just before Christmas 2015, announcement of it may have be missed with the festive season.  I shall check about re-issuing the announcement.

As for only LTS releases on Ubuntu, it is due to time and resource constraints. Please take a look at salt-pack and contribute for Ubuntu 15.10.  I am hoping to have support for Ubuntu 16.04 beta, probably in March timeframe.

@anlutro  Lastly if you look at the https://github.com/saltstack/salt-pack/tree/master/file_roots/pkg/salt/2015_8_4/debian8/spec/salt_debian.tar.xz file, you'll find the offending line for salt-master in the file debian/control.

**Comment by babilen** [comment]
2015_8_4 wasn't there the last time I checked, hence the "ping" :)

**Comment by anlutro** [comment]
@dmurphy18 Does this mean that the salt-pack repository doesn't include steps/instructions for building salt_debian.tar.xz?

Why is `debian/control` only available inside a compressed tar?

Wouldn't it make more sense for the salt-pack repository to contain the *source files* making up the tar file, as well as build steps (a state or whatever) for building the tar file?

**Comment by dmurphy18** [comment]
@anlutro this is due in part to historical reasons, and lack of full automation in the build process.  Historically, salt would test and when ready tag and announce to the community who would in turn build that tagged salt for their respective OS/platform.
Salt historically built for Fedora, Epel on Redhat.

It is still done this way, however Salt is attempting to automate this process for the most used platforms, e.g. Redhat/CentOS, Debian, Ubuntu. Some platforms are still built by community or vendors, e.g. BSD and SLES (Suse), and hosted on repo.saltstack.com.  Many times, the fixes to get Salt packaged on a particular platform occurs after the tagging, hence the need for separate salt-pack to accomplish this.  Eventually I would like to get the automation to the point of specific nightly builds with signing, full testing and code coverage reports for all major platforms, such that all of the packaging is in the salt tarball, and can version it and tag it in the same step, but as yet we do not have this for even one platform.

As for salt_debian.tar.xz, it is easier to check for one file and expand it, then multiple files for changes etc.  If you look at salt-pack for debian, the debbuild.py module takes either a .dsc or salt_xxx.xz file to build from.  When I get time, I need to write 'HOWTO' for salt-pack, but what was a point release free February is not turning out to be so.

**Comment by anlutro** [comment]
Right... I have two issues with this. First, if I'm looking for a reference like the one to python-systemd to see why/how it's defined etc., I can't just search the codebase, I have to first find the right tar.xz file and extract it.

Second, if salt-pack actually had complete steps for building packages, I could build packages out of release candidates or nightly builds and test them in our testing environment. I could also get security bugfixes more quickly, which is obviously super important. I'm weary against installing salt from pip or from source because there could potentially be differences between that and installing from a package.

This second point might not have been an issue if it didn't take up to a week for Debian packages to get built after a version is tagged in git.

**Comment by dmurphy18** [comment]
@eliasp I would like to close this issue since salt-pack is available from github and it's README.md now contains instructions on how to utilize it since SaltConf 2016 (mid-April).
