### ISSUE TITLE
If the private_key filespecified in the provider is missing then the driver will be disabled

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#30817]
I have a few ec2 providers configured but if the private key file is missing for one of them then the driver will be disabled completely when I ran things such as --list-providers.

**Comment by rallytime** [comment]
@bogdanr Good point. The private_key and the permissions set on the private key are needed during the bootstrapping process of a new instance, so we're doing a check for that parameter in the ec2 `__virtual__()` function. However, since there are many functions or use cases where one might not be bootstrapping a linux minion (the key shouldn't be needed during windows create, or when --no-deploy is set), we should move this check to a more suitable place.

Thanks for the suggestion!

**Comment by rallytime** [comment]
@bogdanr I've fixed this behavior in #30884. Please give that a try and let me know how it goes!
