### ISSUE TITLE
Docs: does salt.states.service support systemd?

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#30855]
On this page I can't find the string "systemd": https://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html

The page talks about "system init or rc scripts".

I guess systemd is supported, but I am not 100% sure.

**Comment by gtmanfred** [comment]
It does.
https://github.com/saltstack/salt/blob/629c0b2829759030534e63252a05b71c93251dff/salt/modules/systemd.py#L31

**Comment by guettli** [comment]
Great. Good to know that systemd is supported.

**Comment by rallytime** [comment]
I added this clarification to the docs. @guettli Does that help explain this a little better?

**Comment by guettli** [comment]
No. There are plenty init systems. See  https://en.wikipedia.org/wiki/Init

I think a boring list of all supported unix init services would be nice.

**Comment by rallytime** [comment]
I understand that there are many init systems. However instead of maintaining a static list across many Salt versions, I have updated the docs here to include a link to our list of supported service execution modules. I also included a reference to how you can override service modules if the OS grain detection is out of date with newer distros or distros that have updated their init systems.

**Comment by guettli** [comment]
Thank you very much. I think new users now find all they needed, without providing too much. Thank you.

**Comment by rallytime** [comment]
Definitely. Thanks for pointing this out. Better docs == happier users. :) I'll close this since the fix has been merged and the 2015.8 docs have the change live.
