### ISSUE TITLE
Occasional code tags on saltstack formulas

### ISSUE THREAD

**Issue by enver** [saltstack/salt#31211]
Hi, it would be great if occasional tags on all formulas could be created (quarterly, monthly,...) so they could be easily used without risking future updates breaking something. This way users could easily use formulas as:

```
gitfs_remotes:
  - https://github.com/saltstack-formulas/sysctl-formula:
    - base: <Some tag>
```

without creating fork for each formula they use. Then as formulas are updated users could test new versions and pull them in their system in a more controlled way.

[Moved issue from saltstack-formulas](https://github.com/saltstack-formulas/sysctl-formula/issues/11)

**Comment by jfindlay** [comment]
@enver, thanks for reporting.  To me the issue seems to be that formulas would be more useful if, if possible, they were developed in release cycles or at least used occasional tags as you suggest.

Related to #26963.  Ping @whiteinge, @iggy, @babilen.

**Comment by whiteinge** [comment]
Agreed that tags should be added to each repo. This process and cadence should be up to the individual formula repos and maintainers. I suggest opening an issue on relevant repos to raise the discussion there.

Docs on versioning formulas are here:

https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning

**Comment by iggy** [comment]
The thing is... there are a ton of formulas that don't have a maintainer (in fact, I'd argue none of them do). There are basically a handful of volunteers merging patches that don't look obviously wrong. There are very few formulas where one person says they are completely and totally responsible for it. We don't even have a way to mark formulas as "maintained", that's how seldom it happens.

What deserves a tag? Something that's been thoroughly tested by a qualified QA department? Something that has been bug free for X amount of time?

The suggested way to handle formulas is to fork them into your own org/user and use those as your git remote (i.e. https://github.com/iggy/postgres-formula). Then you periodically pull from upstream, test, and release to your own systems.

@puneetk @gravyboat might have some input too.

**Comment by gravyboat** [comment]
I think @iggy covers most of my concerns with this pretty thoroughly.

**Comment by enver** [comment]
My intention was not to ask for guarantee that some tag in formula works. It is just that if i start with some formula on tag X i test it and add it to project. Later after few fixes new tag Y gets available I can test it in my test environment and if it goes ok move it to production. So basically it is more-less same as forking project and pulling fixes occasionally only without need to create forks for each and every formula I use.

**Comment by enver** [comment]
Any update on this?

**Comment by gravyboat** [comment]
@enver I haven't discussed it with anyone past reading what you wrote on the 16th of February. I personally don't see a good way to handle this, and honestly I don't want the job of maintaining multiple tags for all the formulas since maintaining them already takes up way too much of my time. I would like to note that this: `So basically it is more-less same as forking project and pulling fixes occasionally only without need to create forks for each and every formula I use.` idea is not good at all. What happens if one of the accounts of someone who can make pushes to the repo is compromised and they compromise the tag? Then the maintainers somehow become liable/responsible for a negatively impacting deployment of a tag from the formula repos?
