### ISSUE TITLE
minion_id generation doesn't match the newhostname. 

### ISSUE THREAD

**Issue by MalloZup** [saltstack/salt#31383]
Tested on opensuse_leap42.1.

how to reproduce:

In a new installed machine, with new salt-Minion, before setup the minion itself (so minion-salt-service isn't started)
- change the hostname via hostname "NEWHOST"
- change the file etc/hostname = "NEWHOST".
- don't change the file /etc/hosts

```
cat /etc/hosts
...
127.0.0.2 OLDHOSTNAM
```

```
python -c \'import socket;print  socket.getfqdn()\ '
"NEWHOST"
```

start the salt-minion-service.

minion_id = OLD
# 

If i modify the /etc/hosts, with the "NEWHOST", then  ;
minion_id= "NEWHOST"

I don't know if is an issue on the documentation or the network.py file, because 
according  the official one documentation , minion_id is setting:
1)The Python function socket.getfqdn() is run
2)/etc/hostname is checked (non-Windows only)
3)/etc/hosts
- i was thinking that for minion_id was : 1 OR 2 OR 3 and not 1 & 2 & 3  
- issue similar : #25719

**Comment by jfindlay** [comment]
@MalloZup, thanks for reporting.

**Comment by cachedout** [comment]
Hi @MalloZup Take a look at the ordering in `salt.utils.network._sort_hostnames()` and see if perhaps the intended name was being sorted lower down the list than you expect. My suspicion is that this is a documentation issue versus a bug.

**Comment by MalloZup** [comment]
hi cachedout, 
so i tested now on my system, for me it seems that ._sort_hostnames() doesn't filter the right order

THe only change :
```
hostname salt
```
```
import salt-modules necessary for the test....

print "getfqdn: %s" % socket.getfqdn()
hosts=[]
hosts = salt.utils.network.get_hostnames()
print "unsorted hostnames : %s" % hosts

print "first element of unsorted list " + hosts[0]
sortedhost=[]
sortedhost = salt.utils.network._sort_hostnames(hosts)

print "sorted hostnames : %s" % hosts
print "first element of sorted list " + sortedhost[0]

print salt.utils.network.generate_minion_id()
```

```
getfqdn: salt
unsorted hostnames : ['ipv6-loopback', 'linux-6sy7', 'salt', 'ipv6-localhost', 'localhost']
first element of unsorted list ipv6-loopback
sorted hostnames : ['ipv6-loopback', 'linux-6sy7', 'salt', 'ipv6-localhost', 'localhost']
first element of sorted list linux-6sy7
linux-6sy7

```

**Comment by cachedout** [comment]
You might have a typo there. Shouldn't `print "sorted hostnames : %s" % hosts` be `print "sorted hostnames : %s" % sortedhost`?

**Comment by MalloZup** [comment]
yes , :+1:  that's true. i will check this in the environment test.

**Comment by MalloZup** [comment]
Ok,  cachedout, new output doesn't change the stuff.

```
getfqdn: Client1-Minion

unsorted hostnames : ['Client1-Minion', 'x86_64-default', 'ipv6-localhost', 'ipv6-loopback', 'x86_64-default', 'localhost']

first element of unsorted list Client1-Minion
sorted hostnames : ['x86_64-default', 'x86_64-default', 'Client1-Minion', 'localhost', 'ipv6-localhost', 'ipv6-loopback']
first element of sorted list x86_64-default

x86_64-default.
```

**Comment by isbm** [comment]
@cachedout Since a minion ID is basically a host, to which normally admins _also_ just SSH. Thus maybe should it actually follow the network service switch in `/etc/nsswitch.conf` like everything else does? In that regard we could support `dns` and `files` value from the `hosts` directive:
```
hosts:      dns files
```
In this case we look for the DNS name, then files. Or the other way around.

What you think?

**Comment by cachedout** [comment]
@isbm I'm _really_ hesitant to make any change to the ordering. The last time we did this it was a big disaster because people were depending on the ordering. To be honest, my inclination here is to write a series of tests to ensure the behavior is as we believe it is and then adjust the documentation if necessary.

**Comment by isbm** [comment]
@cachedout I am also not sure how to tackle this, but certainly things aren't clear. I am trying to build a test case for this. However, for starter, I would recommend not to use `socket.getfqdn()`, but `platform.node()` instead. First will go off for 40 seconds, once DNS is blocked, for example...

**Comment by isbm** [comment]
@cachedout I am now trying to understand how this works and why this is implemented this way. I was looking how this is implemented and got confused. 😉 So could you help me here a bit why essentially the code just sorting the hostnames into an array and picks the first one? I mean... this is a bit strange.

As of my current understanding, we supposed to end up with only one name, which is not localhost, not local IP, not and internal name, but what is reachable over the DNS/sockets? And if DNS name is not available and only IP, why not just store the IP as it is, but trying to alias it? — at some point one supposed to SSH into it maybe, and this is not by Salt alias, but by IP... 

So currently we have a problem that if someone renames the hostname in the network, the machine id from the Salt is still stays old one. We would like to understand what pitfalls we are going to step on, what are your concerns here (your comment from Mar 4) and what can  be done here.

Can we try fixing this and what are your thoughts on that? Appreciate your insight.

**Comment by thatch45** [comment]
Hi @isbm the main worry is that we have a lot of deployments that are expecting new minions to follow a certain order when getting named, and we should try to keep that consistent, every time in the past when we have changed the order we have had problems. Also, many salt deployments are fairly dynamic, so if the way the ID is assigned changes out from under someone when they just call salt-cloud again this could be problematic.

Personally though, I REALLY like the nsswitch approach, but we also need to make sure that we don't assign the name to localhost of course, since that is unhelpful (likely goes without saying)

So I think that the really clean approach would be to define mechanisms for the ordering of the search, so that the id definition ordering of salt can be configurable like nsswitch (which would then have an option to use the nsswitch order of course)

Let me know if I am reading this correctly....

**Comment by dmacvicar** [comment]
I propose the following path.

@MalloZup  did change the hostname in a "incomplete" way. And only cared about the result of socket.getfqdn() but salt first uses socket.gethostname().

So the real problem is, socket.gethostname() returns the OLDHOSTNAME with the way @MalloZup  changed it.

Lets first investigate what does systemd machinectl returns when following @MalloZup  steps. If it returns the right thing (it can be queried using dbus https://www.freedesktop.org/wiki/Software/systemd/hostnamed/ ), then we can propose upstream to use this value as first option (if systemd is available).

If it does not, I would not recommend we push upstream to change it as changing the order can create a big mess.

Also, I would test what happens if you change the hostname with hostnamectl instead of editing 2 of 3 files like @MalloZup did, and if this makes socket.gethostname() return the right thing, then I would close this bug as INVALID, -EUSE_THE_RIGHT_TOOL.

**Comment by MalloZup** [comment]
Hi @dmacvicar, hostnamectl is only for systemd. The step i used, is because i'm testing systems also that doesn't use systemd. So hostnamectl cannot scale for systems without systemd.

**Comment by isbm** [comment]
Oh well. There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors. :wink:  It turns out, for setting `/etc/salt/minion` like this:
```
minion_id_caching: False
```
...solves the problem completely.

@thatch45 @cachedout I would actually propose to make this option `False` by default inside the Salt's guts. It doesn't really hurt to have that resolved every time minion is restarted, and restarting minion is actually would mean "Re-get things around you". Only if somebody wants that "freezed", can use caching. I personally would also indeed expect minion ID changed, once host/DNS has been renamed. But this happens only if the caching is disabled.

In case, you agree, here are the [PR (develop)](https://github.com/saltstack/salt/pull/33704) and our beloved [PR (2015.8)](https://github.com/saltstack/salt/pull/33703). :wink:

**Comment by dmacvicar** [comment]
@isbm IIRC in @MalloZup example he had not started the minion for first time yet, so this is not about the minion remembering an old name as I understand it.

**Comment by isbm** [comment]
@dmacvicar no, the issue is that the name is not _updated_ and left old. Similar issue is here: #25719

**Comment by dmacvicar** [comment]
>@MalloZup :
>In a *new installed machine*, with new salt-Minion, *before setup the minion itself* (so minion-salt-service isn't started)

**Comment by thatch45** [comment]
While I want to be very cautious about this change I do think it is OK for us to change how the id is determined, but we do need to keep in mind, that the id of a minion should never dynamically change because of an upgrade, this can cause existing deployments serious problems.
Also, as has been stated in this thread, we need to account not only for systemd, but also keep in mind that Salt is used on systems as diverse as AIX, Solaris and Windows, not only old Linux systems, and any change here will need to be very thoroughly vetted on all platforms. Much of the reason for the current behavior is because of years of debate between platforms.

**Comment by isbm** [comment]
@thatch45 @cachedout @rallytime Here some more investigations on this. Getting closer. Your input is highly appreciated.

@ckochenower were editing last time [this function](https://github.com/saltstack/salt/commit/d4b7951d#diff-1bf4591d60becca6e61e4a6d04d45bcaR130)? Unfortunately, **s8weber**, who originally wrote all of that is no longer around here. In fact, this is very... interesting code. :wink: A bit of insight what it does (Master and Minion on the same machine, no `minion_id_caching`) is below. After setting hostname in generic way, I always delete all keys and restart minion. Master just runs.

Here we go:
<pre>
# hostnamectl set-hostname some.here.it.is && hostname
some.here.it.is

# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
<b>some.here.it.is</b>
Rejected Keys:
</pre>

So far, so good, hostname has been changed. Again:

<pre>
# hostnamectl set-hostname something && hostname
something

# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
<b>SLE_12_SP1-x86_64-default.site</b>
Rejected Keys:
</pre>

Nope. Picks from somewhere an original hostname from the cloud image. OK, again:
<pre>
hostnamectl set-hostname somethingverylongandstraingehostname && hostname
somethingverylongandstraingehostname

# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
<b>SLE_12_SP1-x86_64-default.site</b>
Rejected Keys:
</pre>

Nope. Still an original hostname. OK. Let's do it again:
<pre>
# hostnamectl set-hostname what.is.really.going.on.here.guys && hostname
what.is.really.going.on.here.guys

# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
<b>what.is.really.going.on.here.guys</b>
Rejected Keys:
</pre>

Aha. How about this:
<pre>
# hostnamectl set-hostname pick.me && hostname
pick.me

# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
<b>SLE_12_SP1-x86_64-default.site</b>
Rejected Keys:
</pre>

Nope. Bad luck. Again:
<pre>
# hostnamectl set-hostname pick.me.please && hostname
pick.me.please

# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
<b>pick.me.please</b>
Rejected Keys:
</pre>

Kind of success. Again:
<pre>
# hostnamectl set-hostname istilldontgethowthisthingworks.foo && hostname
istilldontgethowthisthingworks.foo

# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
<b>istilldontgethowthisthingworks.foo</b>
Rejected Keys:
</pre>

OK, pretty clear:
<pre>
# hostnamectl set-hostname bad.luck && hostname
bad.luck

# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
<b>SLE_12_SP1-x86_64-default.site</b>
Rejected Keys:
</pre>

Does everyone agree here at this point that it cannot be called as a correct behaviour? I think, yes.

What happens. Basically, [`_sorted_hostnames`](https://github.com/saltstack/salt/blob/develop/salt/utils/network.py#L100) does weird rules, no idea where taken from. Things gets fixed completely (still some tests are coming!), if:

1. Remove this sorting function at all.
2. Do a better job on removing the duplicates than just [converting set (kills order!!) to the list](https://github.com/saltstack/salt/blob/develop/salt/utils/network.py#L249).

I propose PR (in progress due testing) that [does it all here for 2015.8](https://github.com/saltstack/salt/pull/33715).

What do you think?

**Comment by MalloZup** [comment]
hi bofh, i remember time ago, that  i noticed the same behaviour with _sorted_hostnames

**Comment by thatch45** [comment]
I will agree, that we need to cover all of those cases to determine the id in a deterministic way, very nicely done @isbm

**Comment by isbm** [comment]
Update: good news, @thatch45 ! I won't repeat the whole thing above for demo purposes, just a final result from a following cycle:

1. Rename a host
2. Restart a minion
3. Do it all over again for all the names above

```
# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
bad.luck
istilldontgethowthisthingworks.foo
pick.me
sle_12_sp1-x86_64-default.site
some.here.it.is
something
somethingverylongandstraingehostname
what.is.really.going.on.here.guys
Rejected Keys:
```

So all types of hostnames are working fine. Even if I setup an original host name, like **SLE_12_SP1-x86_64-default.site**, it gets lower-case now, unlike before.

Additionally, I've fixed few bugs in the original behavior, e.g. inline comment in `hosts` file could crash the whole exercise on Windows, some IPv6 localhost names were never filtered out etc. And code is now even smaller. I am not sure if getting `/etc/nodename` on Slowlaris is a good idea, since it is not a _hostname_, but the name of the machine (that is, DNS will override this and there is no requirement to be in sync). JFYI. But I've added this too for now.

While I am still testing this and Unit tests are coming, you can [take a look](https://github.com/saltstack/salt/pull/33715).

**Comment by thatch45** [comment]
Thanks, @isbm I think this is sorely needed, because of the broad application of salt across many platforms solving these issues has often grown organically, and then we come back and revamp the code like this.
I know you want this in the 2015.8 branch, but I am still hesitant to do this outside of a major release since it is such a behavior change though

**Comment by damon-atkins** [comment]
If you try to establish a connection to the salt-master you can use the src ip address, and then lookup the name with the ip address before providing the information to the salt-master.  This way you are using the IP address which is facing the salt-master. (if the server has multiple IP on different network) RHEL Linux dropping support for ifconfig and so is solaris. Windows servers normally  join a domain with their Windows computername, which also adds them into AD DNS....

The other option is for the minion to ask the master for the hostname, but the minion would need to pass some information to the master e.g. ethernet address, hostname booted with, etc.  

Maybe some clouds have some standards for passing the hostname that could be checked.

Some thoughts



e.g. Connect to salt master,
 Ask Salt Master the preferred standard for getting the hostname
 a) sends it the hostname to use  e.g. which could be based on the IP address src use for the connection.
 a) provide salt-master with more info and it will provide the hostname e.g. (8k JSON limit)
 b) Salt-master  wants  uname -n/hostname (which ever is the longest)

Maybe the minion should always provide the information it can, and the Salt-Master confirm it on signing  Maybe with a trigger to update the servers hostname if its different. And maybe the signing can also add a role attribute, which is secure as its part of the signed key.      This might be very helpfull for auto signing scripts, which can talk to a 3rd party to confirm that a VM has just been built.

**Comment by isbm** [comment]
@thatch45 No worries for 2018.5 branch, we can adopt it internally. Once I finish testing, I will PR to the develop branch. I am still wondering where those sorting rules comes from...

**Comment by thatch45** [comment]
I am also wondering since I cannot remember, and we should leave a large comment block in here explaining them once they are revamped

**Comment by isbm** [comment]
JFYI: New PR for develop has been opened, previous to the 2015.8 release has been closed. https://github.com/saltstack/salt/pull/34004
