### ISSUE TITLE
[repo] systemd-python required package is missing from RHEL7 archive

### ISSUE THREAD

**Issue by vutny** [saltstack/salt#31402]
Hello!

I would like to install `salt-minion` from [Salt corporate repo](https://repo.saltstack.com/yum/redhat/7/x86_64/latest/) on my RHEL7 EC2 instance _without any subscriptions enabled_. My AMI ID is `ami-2051294a`.

I've configured the repo:

```
[repo-saltstack-el7]
name=SaltStack EL7 Repo
baseurl=https://repo.saltstack.com/yum/rhel7/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://repo.saltstack.com/yum/rhel7/SALTSTACK-GPG-KEY.pub
       https://repo.saltstack.com/yum/rhel7/base/RPM-GPG-KEY-CentOS-7
enabled=1
enabled_metadata=1
```

And disabled all other repositories. Trying to install:

```sh
# yum repolist
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
repo id                                                                                                             repo name                                                                                                            status
repo-saltstack-el7                                                                                                  SaltStack EL7 Repo                                                                                                   77
repolist: 77
# yum install salt-minion
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:2015.8.7-1.el7 will be installed
--> Processing Dependency: salt = 2015.8.7-1.el7 for package: salt-minion-2015.8.7-1.el7.noarch
--> Running transaction check
---> Package salt.noarch 0:2015.8.7-1.el7 will be installed
--> Processing Dependency: systemd-python for package: salt-2015.8.7-1.el7.noarch
--> Finished Dependency Resolution
Error: Package: salt-2015.8.7-1.el7.noarch (repo-saltstack-el7)
           Requires: systemd-python
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

After I downloaded and installed `systemd-python` package manually, the installation of `salt-minion` succeeded.

Please upload `systemd-python` from CentOS7 to SaltStack corp repo for RedHat 7 to make Salt fully installable.
Ping @dmurphy18 Thanks in advance!

**Comment by dmurphy18** [comment]
@vutny Systemd-python is not included in the packages since this would be too large an issue to track.  Typically we only provide packages for dependencies that are not provided as part of the base install of the OS, and systemd is provided as part of the base install.  Also note that systemd and its associated libraries contain an epoch version and as such are tied together. For example: systemd 219-19 works with systemd-python 219-19 and not systemd-python 208-20.  Keeping all of this consistent would be a maintenance nightmare and impossible since as soon as a point release is made and if systemd is updated, then everything in the point release would be out of date in support, as in the example above, the later systemd-python 208-20 would be incompatible with systemd 219-19 installed.

Lastly, systemd is pretty close to the kernel and maintaining that would be too substantial a task. The line has to drawn somewhere and systemd is too close to the base OS for us to provide that as a dependency.  Hence, if the OS platform utilizes systemd for it's functionality, then and its associated libraries must be available / installed for Salt to work.

**Comment by vutny** [comment]
@dmurphy18 I agree, you're totally right.
Maybe we at least should update the documentation with note that `systemd-python` is a pre-requirement for `salt` if you have only `@Core` packages and it will not be installed from Salt corp repo?

**Comment by dmurphy18** [comment]
@vutny I thought the documentation already had that statement, at least it is supposed to have.  I shall check and make sure it is there, and if not add it.  The task to add it may have been over-looked in the rush before Thanksgiving/Christmas.

**Comment by vutny** [comment]
Thanks, @dmurphy18. I can open a PR for this.

**Comment by dmurphy18** [comment]
@vutny Can you close this issue.  Already pinged our documentation person about mentioning systemd

**Comment by vutny** [comment]
@dmurphy18 Saw the update. Thanks!
