### ISSUE TITLE
States do not fail if ext_pillar does not provide any data

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#31541]
### Expected Behavior

If an ext_pillar module does not provide any data a (high-)state should fail. The problem is if we need pillar data from foreman but it doesn't provide any data a minion could go into an unusable state.

e.g.
We define interface information in foreman and a highstate is triggered on a minion, but foreman is currently not available - all interfaces on a minion would be removed.
### Actual Behavior

States do not fail if an ext_pillar module doesn't provide any data.
### Versions Report

```
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty
```
### Workaround

We created a state[1] which checks for a pillar (pillar_available) which is defined in foreman and will be run first. If that pillar key is not available the highstate will fail hard.

[1]

```
check_foreman_pillar_available:
  test.check_pillar:
    - boolean: pillar_available
    - order: 1
    - failhard: True
```

**Comment by jfindlay** [comment]
@L4rS6, thanks for reporting.  If an `ext_pillar` is supposed to be providing data and fails, it should error, not provide empty data.

**Comment by L4rS6** [comment]
@jfindlay I read my bug description again and I'm not sure if it's clear enough. I'm talking about the following cases:

1. ext_pillar provides data => no error, states will run
2. ext_pillar provides empty data => no error, states will run
3. ext_pillar fails => error, states should not run 

The problem is in case 3: Currently it's not possible to throw exceptions which will intercept the execution of states and that's why we added the workaround described above.

Please let me know if you need further information.

**Comment by jfindlay** [comment]
https://github.com/saltstack/salt/blob/v2015.8.7/salt/pillar/foreman.py#L138-L142

**Comment by ketzacoatl** [comment]
@jfindlay - can you comment on the status of this issue? What is the expected behavior in the 2016.x versus 2015.x series? The issue appears to be a WIP, but I see hard failures in 2016.x:

```
[INFO    ] Starting new HTTP connection (1): 127.0.0.1
[CRITICAL] Pillar render error: Failed to load ext_pillar consul: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/salt/shared?recurse=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f273631bfd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[CRITICAL] Pillar render error: Failed to load ext_pillar consul: 'role'
local:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Failed to load ext_pillar consul: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/salt/shared?recurse=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f273631bfd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
----------
    Failed to load ext_pillar consul: 'role'
```

```
# salt-call --version
salt-call 2016.3.0 (Boron)
```

I have been running 2015.5.x for a while (based on the community supported PPA), but I recently updated my build process to use the official deb repo, and I'm now running 2016.3.0 - having made that upgrade, I now see the consul ext_pillar failing hard and killing state.sls or highstate, whereas previously, the consul ext_pillar could fail, but it would not kill the state.sls or highstate that was running. I have been relying on the soft-fail because I do not want `salt-call --local` to fail if consul is not available, and the behavior I see in 2016.x is breaking my deploys.

If this hard-fail is a feature, is this a place where we could put in place a setting to give us the ability to choose whether or not the failure takes everything down?

**Comment by ketzacoatl** [comment]
Lithium works as I expected:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 538, in ext_pillar
    key)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 508, in _external_pillar_data
    val)
  File "/srv/salt-ext/pillar/consul_pillar.py", line 166, in ext_pillar
  File "/srv/salt-ext/pillar/consul_pillar.py", line 188, in fetch_tree
  File "/srv/salt-ext/pillar/consul_pillar.py", line 179, in consul_fetch
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 376, in get
    callback, '/v1/kv/%s' % key, params=params)
  File "/usr/local/lib/python2.7/dist-packages/consul/std.py", line 34, in get
    self.session.get(uri, verify=self.verify)))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/salt/roles/?recurse=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f3d01708cd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
...
local:

Summary
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
```

```
# salt-call --version                                                                                                                                   
salt-call 2015.5.10 (Lithium)
```

**Comment by jfindlay** [comment]
@ketzacoatl, if a hard failure happening when an external pillar is unavailable is a change in behavior, I am going to have to defer to @cachedout or @thatch45.

**Comment by ketzacoatl** [comment]
Sure, that makes sense, I'll look forward to their input.

FTR, I agree that in some scenarios, failing hard is the right thing to do, but it isn't _always_ the right thing, or what you want in a build process. For example, I make heavy use of consul, but it's not always available (for valid reasons), and I rely on pillar/ext_pillar working together gracefully in both states (eg consul is not available vs when it is, the state run should still complete unobstructed).

Upgrading from 2015.5.3 suddenly broke my AWS AMI build and EC2 instance deployment due to this. I've resorted to sticking with 2015.5.x, but importing the pip state/module from 2015.8.x to get fixes from that release (thanks to `extension_modules`!).

Making this behavior a simple configuration option would be ideal (from my perspective).

Also, I'm curious why that change was made - both this issue and #23402 are open / don't seem to make mention of that change as having been decided and set in stone.

**Comment by whiteinge** [comment]
Following up on my comment on the issue linked above: **not** failing a state run is indeed expected behavior. The traceback you posted from the Lithium release looks like a regression to me. 😦

**Comment by whiteinge** [comment]
See [this comment](https://github.com/saltstack/salt/issues/23402#issuecomment-223473681) for various methods of providing pre-flight checks. The method described in OP is a great way to end the run if Pillar is missing.

**Comment by ketzacoatl** [comment]
@whiteinge, I appreciate the notes and references with tricks with pre-flight checks, those are great! 

That said, my question (and problem), is that the `ext_pillar` module fails hard _when consul (the pillar provider) is not available_. That means, if I configured consul as an `ext_pillar` (eg when I build an AMI for AWS with packer), and consul is not yet ready (because the AMI is not yet deployed.. or, if I am in the middle of deploying an instance and consul is not yet connected to the cluster), the whole thing fails hard.

That's a problem, and I would like to consciously tell salt "it's ok if consul is not available, just continue applying states, use the local pillar (.sls) that's been provided". If failing is an expected behavior, it would be great to be able to tell salt when a missing ext_pillar is ok, and salt should not fail in those cases. Wouldn't you agree?

**Comment by whiteinge** [comment]
I do agree. The Consul ext_pillar should not halt the state run -- that need to be investigated -- and if the local Pillar provides those same values (that will be overridden when the Consul ext_pillar is available), then the state run can continue regardless of where the data is coming from. 👍

**Comment by whiteinge** [comment]
I read your comment on the other issue after typing up the above.

> there is a slight difference between "fail if a pillar key is missing", and "fail if an external pillar provider fails"

Very true; there is a difference. I could be convinced that a harder fail config option is needed. The result of such a config option would be straightforward on a masterless setup: halt the salt-call process and don't execute anything else. But less straightforward on a running master daemon; what should it halt or prevent and where or when?

Historically, badly configured ext_pillar modules don't affect anything else in Salt. The Consul traceback above is troublesome. But a config option could be a nice addition for masterless mode.

**Comment by ketzacoatl** [comment]
To clarify, and to ensure we're on the same page... the traceback I posted above is "consul is not available", and the `ext_pillar` (and pillar) module continue on (soft fail), while the logs I posted before that are "consul is not available and everything blows up" (hard fail). The soft fail is from older versions of salt, while the hard failure is from the more recent release (2016.x).

I'm ok with the soft fail (especially b/c I can use the assertions you pointed out in the other ticket), but it's the hard fail that is causing me serious headache. Lastly, the config option I am referring to would tell salt to let the ext_pillar fail (eg, allow a soft fail).

**Comment by ketzacoatl** [comment]
FWIW, I am using the `consul_pillar` external pillar module (https://raw.githubusercontent.com/saltstack/salt/79d7e7059c133812d9bd5e3fe7a1ce5a97275024/salt/pillar/consul_pillar.py) with older versions of salt (2015.5.x), and it "works fine" (in my cases described above, when consul is not yet available on the host). However, that same module does _not_ work fine when consul is not available and when used with a more recent version of salt (which, consequently is the opposite behavior the op describes).

Therefore, at least with my issue, I do not believe the problem is the `consul_pillar` module directly, but either the `ext_pillar` interface or it's interaction with the consul pillar module. Previously, I thought I had found a reference to that change in behavior (in the `ext_pillar` module), but I'm not sure where that is now. 

Also, this issue is specifically about the state run _not_ failing when an `ext_pillar` module is _empty_ (returns nothing). I am seeing the state run fail with 2015.8.x, when the consul external pillar does not provide any data, so I am unsure if I should continue pursing my config option in this ticket or create a new one (as I am now realizing the original op's issue and mine here are different enough).

@whiteinge, how should we proceed here?
