### ISSUE TITLE
test custom modules with test suite

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#31597]
### Description of Issue/Question

Add feature to handle unit and integration tests in the test suite for custom salt plugin modules.  Also add documentation on how to do this.  Where should we put the test code and artifacts?

**Comment by cachedout** [comment]
Can you please clarify which functionality your're trying to test? Just that external modules can be loaded? Or is it something different. I'm confused, because we already utilize `_modules` and `_states` in the test suite under `integration.files.file.base`.

**Comment by jfindlay** [comment]
Users want to be able to write tests for their own custom modules.  If this can already be handled by the test suite, then we should probably document it better.

**Comment by cachedout** [comment]
Ah, OK. We probably just need to add some flags to allow them to specify a custom directory for additional tests can be found and perhaps a way for them to add another directory to sync modules from and we'll be done.

**Comment by cliffrowley** [comment]
Yes please :-)

**Comment by dmacvicar** [comment]
I mean before inclusion in the main salt tree. I am developing a state and execution module that I would like to upstream at some point. Until then, having it in its own git with a easy way to run the tests.

May be it exists, I just did not figure out how.

**Comment by cachedout** [comment]
All done. There's a lot that can be improved here but you can now test custom modules and store all user-defined tests in a directory outside of the Salt repo.

https://github.com/saltstack/salt-testing/pull/92

https://github.com/saltstack/salt/pull/36224

Feedback welcome. I'm closing this issue since the initial specs are done but please feel free to leave comments here and/or open new issues for additional features or bugs. Thanks.
