### ISSUE TITLE
Windows Salt Minion - User Notification

### ISSUE THREAD

**Issue by jeffclay** [saltstack/salt#31624]
### Windows Salt Minion - User Notification

I'm wanting to write something for windows minions that shows the user a progress bar with status and current state/task being executed by salt on that machine. I'm fairly familiar with c#.net but not that familiar with python or the inner workings of the salt minion. I would put this project  on github and contribute it back to the community if someone familiar with salt python and windows would help out. suggestions?

**Comment by jeffclay** [comment]
i'm thinking something in the windows minion sending the information to a process which is running as the currently logged on user. the process then displays a progress bar and a user friendly description of the current state/task being performed by the minion to the user. i don't know where to begin editing the minion to count the states in the state file or how to include a user-friendly name to display along with that state when it's being processed and then passing all of that out to another program.

**Comment by jfindlay** [comment]
@jeffclay, this seems like a useful feature.  I know very little about windows development, but you can get information on what salt is doing by watching the [event system](https://docs.saltstack.com/en/latest/topics/event/index.html#from-python).

**Comment by markuskramerIgitt** [comment]
@jeffclay, excellent idea. I too think that notification is a useful, missing feature.
For the last months, I write Salt execution modules, so far for Windows minions only. I also write on a C# service, to react to Windows events (network connectivity).

Instead of inter-process communication, what do you think of file based communication?
Salt tasks would write into a (log) file, and C# would display the (aggregated) log file.
We would need to specify log format, e.g. for a progress bar or percentage display.

Windows reliably notifies file-changes, so there is no polling involved from the C# side.
I guess that IPC from Python to C# requires modules currently not present in Salt, and I had to learn that Python gets unreliable the closer you come to Windows inner workings. 
If IPC turns out to work, we can always switch to it.

**Comment by damon-atkins** [comment]
+1   e.g. I am installing software.    But I would not limit it to Windows, No reason Unix/Linux workstations can not get the same sort of messages.

**Comment by damon-atkins** [comment]
.
