### ISSUE TITLE
Provide useful error message if OS is unknown

### ISSUE THREAD

**Issue by maxhq** [saltstack/salt#31678]
### Description of Issue/Question

If a Salt minion does not recognize the OS, very strange messages are given to the user like:

```
[ERROR   ] State 'pkg.installed' was not found in SLS 'hypervisor-kvm'
Reason: 'pkg' __virtual__ returned False
```

The real problem is the unknown OS:

```
[DEBUG   ] Error loading module.rh_service: Cannot load rh_service module: OS not in set(['SUSE  Enterprise Server', 'SUSE', 'RedHat', 'CentOS', 'CloudLinux', 'McAfee  OS Server', 'XenServer', 'Amazon', 'OEL', 'ScientificLinux', 'ALT', 'Fedora'])
```

An unknown OS should definitely lead to all further actions being stopped with a proper error message.

The deeper problem seems to be the strange way the Python _platform.py_ module tries to identify the OS by [just querying the first line](https://hg.python.org/cpython/file/2.7/Lib/platform.py#l335) of e.g. `/etc/os-release`. On Rockstor linux this is the content:

```
# cat /etc/os-release 
NAME="Rockstor"
VERSION="3 (Core)"
ID="rockstor"
ID_LIKE="rhel fedora"
VERSION_ID="3"
PRETTY_NAME="Rockstor 3 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:rockstor:rockstor:3"
HOME_URL="https://www.rockstor.com/"
BUG_REPORT_URL="https://www.rockstor.com/"
```

I guess it would be much easier to query the `ID` instead and, if that is unknown, check for `ID_LIKE`.

My current workaround for Rockstor: I statically set the OS name and release info:

```
# cat /etc/salt/minion.d/set-osname.conf
grains:
  os: CentOS
  os_family: RedHat
  osmajorrelease: 7
  osrelease: 7.2
  osrelease_info:
   - 7
   - 2
   - 1511
```
### Setup
- [Rockstor](http://rockstor.com/) installed with Salt minion
- Simple SLS file on master, e.g.

```
mc:
  pkg.installed: []
```
### Steps to Reproduce Issue

Take any system with a Salt Minion installed and do this:

```
cat <<EOF > /etc/salt/minion.d/test-osname.conf
grains:
  os: MyOS 
  os_family: Kelly
EOF

salt-call -l debug --local state.single pkg.installed name=mc
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 3.8.10 Core
        machine: x86_64
        release: 4.3.3-1.el7.elrepo.x86_64
         system: Rockstor 3.8.10 Core
```

**Comment by jfindlay** [comment]
@maxhq, thanks for reporting.  There is an [ongoing effort](https://github.com/saltstack/salt/wiki/December-2015-Sprint-Beginner-Bug-List) to add reason messages to the salt loader info on why a module was not loaded, although this has not been extended to state modules yet.  The proper way to propagate the original message to a dependent module seems to be the way the dockerng state [does it](https://github.com/saltstack/salt/blob/v2015.8.7/salt/states/dockerng.py#L78).

**Comment by lordcirth** [comment]
Is it worthwhile to file an issue with upstream Python to improve platform.py?

**Comment by pullit** [comment]
@jfindlay Hello, new contributor here.  I finished up reading through most of the SaltStack architectural and coding style documentation.  My team uses SaltStack quite heavily so it's not completely new to me.  

Anyway, what's the status with reason messages?  It looks like work was started in 2015 but I'm guessing it's not ongoing?

Is this issue good to be picked up?

**Comment by jfindlay** [comment]
@pullit, the incompleteness of the reason refactor has always bothered me.  We used it as a context to introduce new contributors and I think it was quite successful for that.  I always meant to come back and bulk, uniform update all of the modules (exec, state, returner, etc.) to the more detailed pattern.  The docker state module example shows how to predicate the loading of the state module on that of the execution module while also propagating the reason for not loading back to the user.  This makes sense for many state modules as stating out functionality of execution modules is a very natural design pattern for state modules.  You are very welcome to contribute to this effort.  The only reason I have not done so is that I have been distracted by other things--other jobs, family affairs, solar eclipse, politics, life, squirrels, wolverines--since I worked at salt.

Also, if I am remembering correctly the recommended error message is redundant about the module name because the salt loader also emits it, but that doc was written by me, so har har, I guess.

@lordcirth, I think python might benefit from better platform detection skills.  There is a mixing of functionality in this regard between salt grains and the platform python module.  Salt `grains` draw from `platform` where it makes sense, but some of the extra detection work put into `grains` could definitely be pushed upstream into `platform`.  My memory is that in particular there were things I wished python detected better about windows, but that was a few years ago and I'm not a python developer and have not ever even submitted code changes to CPython, so I can't really give advice on how such changes would be received.
