### ISSUE TITLE
LocalClient.cmd method lames retcode so there is no reliable way to detect an error when using Pepper

### ISSUE THREAD

**Issue by abulkavs** [saltstack/salt#31708]
On result for fake command ''test.fooo' (just to provoke error), issued by pepper, at the following line:
https://github.com/saltstack/salt/blob/develop/salt/client/__init__.py#L578

fn_ret = {'localhost': {'retcode': 254, 'ret': "'test.fooo' is not available.", 'out': 'nested'}}

so 'ret' value returned to the pepper client at the following line :

https://github.com/saltstack/salt/blob/develop/salt/client/__init__.py#L580

is 

ret= {'localhost': "'test.fooo' is not available."}
# _NO RETCODE OR REPLACEMENT!!!!_

salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
           Mako: 0.8.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 5.0.1
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.3.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

**Comment by whiteinge** [comment]
Definitely agree. The best way to get this added to Salt is to add two methods (one sync and one async) to `LocalClient` that are identical to `cmd` and `cmd_async` but don't truncate the return. Then add wrappers for both in `NetapiClient`. Perhaps named `local_full` and `local_async_full`.

If you're interested in putting in the work to get those added, I'd be more than happy to help where I can.

(Not helpful for current Pepper but) that extra return data is *currently* exposed via Salt's event bus. If you set up a listener before you fire an async command you can get the full return including `retcode`. (`curl -NsSi localhost:8000/events`) That functionality would also make a good addition to Pepper. [Listening to the event stream is simple in Python 3](https://gist.github.com/whiteinge/c63be251f80467ed842f) or with Tornado.

**Comment by abulkavs** [comment]
Regarding implementation. I would rather pass extra flag like dont_truncate_retcode (name could be better))) through the kwargs. Based on this flag the retcode would be added to the 'ret'. In this case no need to change/extend any interfaces and even Pepper and Netapi implementations. Also nothing existing so far would be broken. Probably I just don't know the reason why adding two extra methods to the LocalClient and NetAPI + Pepper would be better.

**Comment by whiteinge** [comment]
You're definitely right that adding a kwarg would be less work. I'm not sure one approach is objectively better than the other -- I can see pros/cons for both approaches. The reason adding new methods is my go-to for this is:

1. API stability. Any mistakes, regressions, or unintended consequences in the `cmd()` method is likely to affect a lot of people. This method is used by the Reactor, Orchestrate, salt-api, and many others. This is a small change so it's not likely to cause trouble, but there's a lot of Salt users so you never know for sure.
2. API consistency. Changing the basic return format via passing a kwarg feels odd for a REST API (though less-so for a Python API). I personally prefer that a given endpoint in a REST API return a consistent outer structure and only the inner-bits change based on the return. I know this sounds odd since Salt's execution modules can return _anything_ but see the next point.
3. Future API flexibility. Adding this as a client means we can more easily wrap a new salt-api endpoint around it (like with `/minions`). So that sending requests to, say, a `/full` endpoint could *always* use this client, for example. (Or `/cmd`?

**Comment by whiteinge** [comment]
Oh, and I misspoke about needing `_async` variants of those methods. We only need sync since the full return from the LocalClient async method is _not_ truncated.

**Comment by whiteinge** [comment]
This was added in #39492.
