### ISSUE TITLE
/dev/null becomes a file instead of a device on our salt master

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#31783]
### Description of Issue/Question
/dev/null becomes a file instead of a device on our salt master

### Steps to Reproduce Issue

```
root@salt:~# ls -alh  /dev/null
-rw-r--r-- 1 root root 25 mars  10 11:07 /dev/null
root@salt:~# cat /dev/null
insserv is /sbin/insserv
```
the /dev/null should be : 
```
 crw-rw-rw- 1 root root 1, 25 Mar 2 09:34 /dev/null
```
which is the case at boot time. 

### Versions Report

```# salt-master --versions-report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 2.3.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3 
```

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for reporting.  Do you have any suspicions about what may be causing this?  Was `/dev/null` accidentally deleted somehow?  Is something deleting `/dev/null` and replacing it with an ordinary file?  I am running a 2015.8.7 master on debian 8.3 and `/dev/null` on the system is not a file.

**Comment by damon-atkins** [comment]
If deleted the first process running as root which wants to write to /dev/null will create it as a file and start filling it with data.    You need to find out what deleted it. 

Some one may of configure some software running as root  to write to /dev/null because they did not want the output and did not realise the program deleted the file first before writing to it.  

Search the system for scripts or configuration files with /dev/null i.e. egrep -R '/dev/null' /usr /etc /opt /var  /home /srv    Also double check permissions on /dev to make sure non root uses can not remove it.

Its not a salt stack issue unless salt stack python code is deleting the file.

**Comment by cachedout** [comment]
I agree with @damon-atkins 

I really can't see where we can go with this, especially given that this is a master and not a minion and even less likely to be modifying files on the filesystem. If we can tie this directly to Salt causing this, we can investigate but I see no reason to keep this open without further evidence...
