### ISSUE TITLE
saltutil.runner:  "this function must be run on the master" documentation incorrect?

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#31850]
The documentation for the [saltutil.runner](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.runner) function says that it must be run on the master:

> Execute a runner module (this function must be run on the master)

However, the example shows it being run on all minions:

> CLI Example:
>
>     salt '*' saltutil.runner jobs.list_jobs

So can it be run on minions?

If it must only be run on the master, how does one do that?  If the master is also a minion with ID `master`, I could target the `master` minion (e.g., `sudo salt master saltutil.runner jobs.list_jobs`) but that's running it on a minion that happens to be the same machine that runs the master.  Is that the same thing as "running it on the master"?

**Comment by jfindlay** [comment]
@rhansen, thanks for reporting.  We should get this documentation fixed.

**Comment by cachedout** [comment]
So the idea here is that you might need to utilize the result of a runner (which executes on the master as all runners do) in a state file, for example, on a minion.

The way the documentation describes this as a remote-execution call really isn't very helpful because it's basically saying, "Tell all minions to contact the master and have the master run a runner and then send the minion the results and then have the minion send those results back to the master for display on the CLI". ;]

I'll see if I can't clarify the documentation a little bit. Thanks for the suggestion.
