### ISSUE TITLE
Multiple top file messing up the sequence of states

### ISSUE THREAD

**Issue by shinshenjs** [saltstack/salt#31918]
### Description of Issue/Question

When using multiple environments of same top file, the ordering in top file is messed up. As the code are coming from git, the top file is pretty much the same across branches. I did not use gitfs because we have a differnt way to deploy the codes. 
### Setup

Having this issue on both --local and master setup.

config:

```
file_roots:
  base:
    - /tmp/salt-test/base/salt

  dev:
    - /tmp/salt-test/dev/salt

pillar_roots:
  base:
    - /tmp/salt-test/base/pillar

  dev:
    - /tmp/salt-test/dev/pillar
```

top file on both base/dev env

```
dev:
  '*':
    - a
    - b
    - c
```
### Steps to Reproduce Issue

Run `salt-call --local state.show_top` 

The expected output should be 3 states in a,b,c sequenc. But for some reason it end up like this:

```
local:
    ----------
    dev:
        - a
        - c
        - b
```

If I try to run state.highstate the sequence will be in a->c->b which is not what I expected.

Removing either one of the top file and the problem magically dissapears.

_Include debug logs if possible and relevant._
This is the test sample I run on local mode

```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /tmp/salt-test/base/pillar/top.sls
[WARNING ] Template is an empty file: /tmp/salt-test/base/pillar/top.sls
[DEBUG   ] compile template: /tmp/salt-test/dev/pillar/top.sls
[WARNING ] Template is an empty file: /tmp/salt-test/dev/pillar/top.sls
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.show_top
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /tmp/salt-test/base/pillar/top.sls
[WARNING ] Template is an empty file: /tmp/salt-test/base/pillar/top.sls
[DEBUG   ] compile template: /tmp/salt-test/dev/pillar/top.sls
[WARNING ] Template is an empty file: /tmp/salt-test/dev/pillar/top.sls
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path u'top.sls' to resolve u'salt://top.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path u'/var/cache/salt/minion/files/base/top.sls' to resolve u'salt://top.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://top.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/top.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/top.sls' using 'jinja' renderer: 0.00487589836121
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/top.sls:
dev:
  '*':
    - a
    - b
    - c


[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('dev', OrderedDict([('*', ['a', 'b', 'c'])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/top.sls' using 'yaml' renderer: 0.00870394706726
[DEBUG   ] In saltenv 'dev', looking at rel_path u'top.sls' to resolve u'salt://top.sls'
[DEBUG   ] In saltenv 'dev', ** considering ** path u'/var/cache/salt/minion/files/dev/top.sls' to resolve u'salt://top.sls'
[INFO    ] Fetching file from saltenv 'dev', ** skipped ** latest already in cache u'salt://top.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/dev/top.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/dev']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/dev/top.sls' using 'jinja' renderer: 0.00111794471741
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/dev/top.sls:
dev:
  '*':
    - a
    - b
    - c


[DEBUG   ] Results of YAML rendering:
OrderedDict([('dev', OrderedDict([('*', ['a', 'b', 'c'])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/dev/top.sls' using 'yaml' renderer: 0.00362086296082
[WARNING ] Top file merge strategy set to 'merge' and multiple top files found. Top file merging order is undefined; for better results use 'same' option
[DEBUG   ] compound_match: name.jobstreet.com ? *
[DEBUG   ] compound_match name.jobstreet.com ? "*" => "True"
[DEBUG   ] LazyLoaded nested.output

```
### Versions Report

salt-call 2015.8.3 (Beryllium)

Thanks.

**Comment by babilen** [comment]
I'd *strongly* recommend to use a single top file only and to keep it separate from the rest of your states.

**Comment by jfindlay** [comment]
@shinshenjs, thanks for reporting.  If you don't need multiple top files, it will be easier to use one as @babilen indicates.

**Comment by shinshenjs** [comment]
Well, normally in my case the top file are same but not always...

For example if there is a change in the top file, the one in dev and production will be different, until the changes is push/merge to stage/prodution.

Are there any better suggestion on handling cases like this? I think even gitfs will have similiar problem in this case as well?

**Comment by jfindlay** [comment]
@shinshenjs, I am unsure what to suggest in that case.  Top files can get rather sophisticated fairly quickly.  There were options added to 2015.8.0 to mitigate some of this, but it seems there are still some issues according to the few bug reports I've seen since then.  I still think it's easier to manage the top file separately if it is possible.

**Comment by cachedout** [comment]
I'm not completely convinced that this is a bug.

In complex scenarios, this becomes nearly impossible to reason about. Here's a hypothetical scenario.
```
env1:
  '*':
    - a
    - b
    - c
```
```
env2:
  '*':
     - a
     - b
     - d
```
```
env3:
  '*': 
    - d
    - a
    - b
```
In this scenario, where should `d` end up in the merged list? Some might say it should be at the top, since it's the last file to be merged. Others might argue it should be at the bottom since that's the first appearance. Regardless, then you have the problem of where to prioritize `a`. Should it be at the top or what?

In my view, depending on this type of ordering is just a recipe for disaster. It's *much* better to use requisites inside the state system to handle state ordering on that level, versus trying to manage this.

In my view, this list should remain unordered during a merge.

**Comment by shinshenjs** [comment]
My problem with requisite is that it is very hard to manage when it has a lot dependency. E.g. `a` has 10 states declaration that is all required states in `b`. This is the reason why I'm using top file for ordering at first place

But after reading what @cachedout said, I do agree that it does looks like this problem is impossible to fix. As I'm already using @jfindlay suggestion to solve the problem by managing a single top file separately, I'm ok to close this.

**Comment by GreatSnoopy** [comment]
I'll chime in on this to sustain the idea that this is a bug.
My usage scenario is a bit different, but I get hit by the same issue.
So, i have  a top file. In this, i put something like: 
```
base:
    "*": things_for_everybody
```
However, I also have either an external node plugin or a master tops module that are supposed to give me some states to be applied based on a more complex logic regarding the targeted minions (ex look ups in other databases).
So I still want to have the things_for_everybody state applied first for every node in the infrastructure (and maybe other states on subsets of the minions but which are easily decidable right here) but on the other hand, I want to be able to add other states that as said before are determined by a module.
I would like to be sure that either the order of the aggregated states is consistent by either having first those in the top.sls and then those from the external classifiers or maybe have it lexicographical sorted so that at least I can control the order by the way I name the states.

**Comment by terminalmage** [comment]
@GreatSnoopy The issue you're experiencing is not the same as the one reported. The issue reported here deals with what happens when you have multiple top files, not a combination of top file and master_tops.

However, after looking at how master_tops and top file matches are combined, I found the issue. To ensure no duplicate matches, the master_tops and top file matches are merged together by first converting them to sets, and the combining them using [set.union()](https://docs.python.org/2/library/stdtypes.html#set.union). The problem with using sets is that it usually changes the order. I've just opened https://github.com/saltstack/salt/pull/41709, which removes the set logic and replaces it with list comprehensions to keep duplicates from being included. The top file matches will be executed first, followed by any master_tops matches which were not matched in the top file.

The pull request also adds a new option `master_tops_first`, which defaults to `False`. When set to `True`, the master_tops matches are executed first, followed by any top file matches which were not matched via master_tops.

Given that I have addressed the bug you reported, and that there is a consensus between the core development team that the original issue as reported is not behavior we are going to change, I am closing this issue.

**Comment by GreatSnoopy** [comment]
@terminalmage thanks for the update, sounds great !

**Comment by terminalmage** [comment]
No problem, thanks for helping bring the issue to light. We have a general policy against changing the behavior of the state compiler in point releases, and we're very close to releasing a new feature release, so unfortunately the fix will not be released officially until the _next_ feature release, towards the end of 2017 or early 2018.

**Comment by GreatSnoopy** [comment]
That's not so good any more, luckily we worked around this by only relying on the custom master tops and making that one also refer the "static", common  states. Not the most elegant solution, but at least it gets the job done.

**Comment by terminalmage** [comment]
Well, we do have to consider how this will impact those who have grown used to the current behavior. If you absolutely must have the fix now, you can apply the below patch to your minions, taken directly from the commits in the PR I opened.

```patch
diff --git a/salt/config/__init__.py b/salt/config/__init__.py
index a4dcb81558..6f16fa6cf9 100644
--- a/salt/config/__init__.py
+++ b/salt/config/__init__.py
@@ -723,6 +723,10 @@ VALID_OPTS = {
     # A mapping of external systems that can be used to generate topfile data.
     'master_tops': dict,

+    # Whether or not matches from master_tops should be executed before or
+    # after those from the top file(s).
+    'master_tops_first': bool,
+
     # A flag that should be set on a top-level master when it is ordering around subordinate masters
     # via the use of a salt syndic
     'order_masters': bool,
@@ -1283,6 +1287,7 @@ DEFAULT_MINION_OPTS = {
     'auth_timeout': 5,
     'auth_tries': 7,
     'master_tries': _MASTER_TRIES,
+    'master_tops_first': False,
     'auth_safemode': False,
     'random_master': False,
     'minion_floscript': os.path.join(FLO_DIR, 'minion.flo'),
diff --git a/salt/state.py b/salt/state.py
index 0bd85e6db4..14b38f4123 100644
--- a/salt/state.py
+++ b/salt/state.py
@@ -3120,11 +3120,15 @@ class BaseHighState(object):
                 _filter_matches(match, data, self.opts['nodegroups'])
         ext_matches = self._master_tops()
         for saltenv in ext_matches:
-            if saltenv in matches:
-                matches[saltenv] = list(
-                    set(ext_matches[saltenv]).union(matches[saltenv]))
+            top_file_matches = matches.get(saltenv, [])
+            if self.opts['master_tops_first']:
+                first = ext_matches[saltenv]
+                second = top_file_matches
             else:
-                matches[saltenv] = ext_matches[saltenv]
+                first = top_file_matches
+                second = ext_matches[saltenv]
+            matches[saltenv] = first + [x for x in second if x not in first]
+
         # pylint: enable=cell-var-from-loop
         return matches

```
