### ISSUE TITLE
Logging warning only in debug is not a good practice...

### ISSUE THREAD

**Issue by warden** [saltstack/salt#32006]
https://github.com/saltstack/salt/blob/develop/salt/utils/verify.py#L515-L520

This is an odd practice to log a *warning* only in *debug* mode.
I suggest changing this to debug or to log this in warning too.

**Comment by rallytime** [comment]
That `warning` message to only display in `debug` (or trace or garbage) mode is intentional. The idea being that if you're logging in one of those modes, the warning will display. If you're not in one of those modes, then the message should not display. It isn't necessary as logging with something like `info` isn't an insecure logging format.

**Comment by warden** [comment]
Right, I got the main idea behind it... to actually warn a user about logging insecure data *while* it is logged in above warning... Well, sunday it is. Sorry and thanks!
