### ISSUE TITLE
support gpg secret keys from gpg agent

### ISSUE THREAD

**Issue by elsmorian** [saltstack/salt#32207]
Trying to use gpg to encrypt pillar data as described in the docs.

When attempting to decrypt the data, gpg fails and outputs: "gpg: cannot open tty `/dev/tty': No such device or address":

```
2016-03-29 14:38:49,298 [salt.loaded.int.render.gpg][DEBUG   ][31811] Reading GPG keys from: /etc/salt/gpgkeys
2016-03-29 14:38:49,306 [salt.loaded.int.render.gpg][ERROR   ][31811] Could not decrypt cipher -----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA5tIxGzCwANrAQf/d0LfbSEPoAd1Vq1LeaCNh8w4ZAAziRF7BoVLarOX4xIG
++UeAEWOh7SsIOCCAw1vqax+ieBFl2buM6Tql0NDXURRq2lojokKUcELNsP1/rGU
IsNlMQHQbNfPXn47E9pMb3l7a2xo9eSOUc/FcWq7qMNGRDd0kQtrZU+9jtzuYgKa
gv2icieTqsB3ZxPj+A8pVaOqy6/alMCAR1sEnUDWV0xoNU+0pwBRDjYBQYFvFLX/
IKeMNTBlSZq80cZQFs8mjKyUTxXeaiBCT3ogfFVY0OuhDPno2umIQJkcmyV4MOnF
wdxOLqo1e8BBXUgL3LHy2pNM2LFO379quwp0pI3Tt9JZAYbt/KdsZXHOWd+ARUJU
vZbJdf6kW7Za2Lz0u4+ot8RsFaAaa0i1TcT3zPmEVIr9nYF8pOn0dWD1ZrAF0/5u
QfahE4nLX7UDxPHyRgPDJwneUhv4bQSrSEk=
=FNQ7
-----END PGP MESSAGE-----
, received: gpg: cannot open tty `/dev/tty': No such device or address
```

Have added in the `#!jinja|yaml|gpg` header to the pillar file,and the logs include the raw PGP message which is correct.

``` bash
$ gpg --version
gpg (GnuPG) 1.4.16

$ salt --versions-report
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-58-generic
         system: Ubuntu 14.04 trusty
```

**Comment by elsmorian** [comment]
Thanks to AndreasLutro on IRC who pointed out its probably because my gpg has a passphrase.

In which case please treat this as a feature request for salt to play will with passphrased keys, probably through gpg-agent!

**Comment by jfindlay** [comment]
@elsmorian, thanks for reporting.  Support for gpg-agent would be useful.

**Comment by fbretel** [comment]
@jfindlay this hit me today while attempting to upgrade from 2015.5.10 to 2016.11.2. I can't figure out why/how it is working with 2015.5.10, and I'll try a bisect when I get a chance.

Meanwhile, how about adding `--no-tty` to [the gpg call](/saltstack/salt/blob/develop/salt/renderers/gpg.py#L260) ?

**Comment by fbretel** [comment]
@jfindlay this hit me today while attempting to upgrade from 2015.5.10 to 2016.11.2. I can't figure out why/how it is working with 2015.5.10, and I'll try a bisect when I get a chance.

Meanwhile, how about adding `--no-tty` to [the gpg call](/saltstack/salt/blob/develop/salt/renderers/gpg.py#L260) ?

**Comment by fbretel** [comment]
In my environment, the problem occurs with v2016.11.2 only when started with systemd. Everything works smoothly when salt-master is started from the command line. I couldn't find an easy mean to run a process without `/dev/tty` (none of `nohup`, `disown`, `setsid` worked) to bisect.

But, looking at the changes `v2015.5.10..v2016.11.2`, I'm pretty confident that the cause is in 0db7670f968368: drop of `python-gnupg` ...which was using:
```python
    def make_args(self, args, passphrase):
        """
        Make a list of command line elements for GPG. [...]
        """
        cmd = [self.gpgbinary, '--status-fd', '2', '--no-tty']
        # ...
```

BTW, I think this bug is distinct from enabling gpg-agent: all gpg calls will probably fail with or without an agent. But as @elsmorian, I do also have an encrypted passphrase.

I'll try to provide a patch shortly.

**Comment by fbretel** [comment]
In my environment, the problem occurs with v2016.11.2 only when started with systemd. Everything works smoothly when salt-master is started from the command line. I couldn't find an easy mean to run a process without `/dev/tty` (none of `nohup`, `disown`, `setsid` worked) to bisect.

But, looking at the changes `v2015.5.10..v2016.11.2`, I'm pretty confident that the cause is in 0db7670f968368: drop of `python-gnupg` ...which was using:
```python
    def make_args(self, args, passphrase):
        """
        Make a list of command line elements for GPG. [...]
        """
        cmd = [self.gpgbinary, '--status-fd', '2', '--no-tty']
        # ...
```

BTW, I think this bug is distinct from enabling gpg-agent: all gpg calls will probably fail with or without an agent. But as @elsmorian, I do also have an encrypted passphrase.

I'll try to provide a patch shortly.
