### ISSUE TITLE
Require can to call all the module?

### ISSUE THREAD

**Issue by fuhao009** [saltstack/salt#32324]
Require can to call all the module?

What is the difference between the following two
```sls
require:
  cmd:
require:
  pkg:
```

**Comment by jfindlay** [comment]
@fuhao009, the [conventional formatting](https://docs.saltstack.com/en/latest/ref/states/highstate.html#name-declaration) for highstate data has this form in YAML syntax:
```sls
# /srv/salt/motd.sls
motd perms:
  file.managed:
    - name: /etc/motd
    - mode: 644
```
The top level item is the state ID, the next is the state module and state function joined by a `.`, and the inner list items are the arguments to the function `file.managed`.  When using the [require requisite](https://docs.saltstack.com/en/latest/ref/states/requisites.html#require) to require an individual SLS state rather than an entire SLS file, the format is the same as for many other requisites: `<requisite>: [<state module>: <SLS ID>]`:
```sls
# /srv/salt/db_user.sls
include:
  - motd

db user:
  user.present:
    - name: db_user
    - require:
      - file: motd perms
```
Because of this, state module and SLS ID combinations must be unique for each SLS state across all SLS data.

When you are requiring a `cmd: <SLS ID>`, you are declaring that the SLS state must be run after the `cmd` SLS state having ID `<SLS ID>`.  The same is true for requiring `pkg: <SLS ID>`.

**Comment by fuhao009** [comment]
thinks,i m sorrry,I still have questions
# /srv/salt/motd.sls
motd perms:
  file.managed:
    - name: /etc/motd
    - mode: 644
  cmd.run:
    - name: echo "hello word"

 # /srv/salt/db_user.sls
include:
  - motd

db user:
  user.present:
    - name: db_user
    - require:
      - file: motd perms
What to use here  “file: motd perms” or "cmd: motd perms"

**Comment by jfindlay** [comment]
@fuhao009, you may do either or both, depending on what your needs are.  the `include` statement inserts the contents of  `/srv/salt/motd.sls` into `/srv/salt/db_user.sls` as if it were a single file when the states are applied.  `require` only means that `file: motd perms` or `cmd: motd perms`, whichever you choose must be applied before the `db user` state is applied.  They will all be run, but `require` is used to guarantee that `db user` is applied after the state it requires to be applied first.  You can inspect the rendered SLS data by running `salt '*' state.show_sls db_user` or even the simulated result of applying the data with `salt '*' state.apply db_user mock=True`.

**Comment by rallytime** [comment]
Looks like these questions were answered. Marking this as resolved.
