### ISSUE TITLE
CloudLinux not detected as os_family: RedHat (consequences of #28951)

### ISSUE THREAD

**Issue by afletch** [saltstack/salt#32384]
Due to the change in #28951, all CloudLinux versions now have the os_family grain of 'CloudLinux Server'. This is because the `_OS_NAME_MAP` in `grains/core.py:929` was not updated to be consistent with the change.
The consequences of this, I'm sure you can imagine, are considerable and terminal to state execution.

Curently:
`'cloudserve': 'CloudLinux',`
This would need changing to:
`'cloudlinux: 'CloudLinux',`

This then cascades to also break the grains `osfinger` and `osmajorrelease` because they rely on `os_family`.
nb. Even setting a manual grain in `/etc/salt/grains` on the minion for `os_family: RedHat` does not fix the broken osfinger/osmajorrelease grains, as the test used to set these depends on the value of `os_family` determined earlier in `grains/core.py` (this is, perhaps, another problem; that manual grains are not respected during determination of other values)

```
# salt-minion --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 29 2015, 18:30:53)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.7 Aleksei Gubarev
        machine: x86_64
        release: 2.6.32-673.8.1.lve1.4.3.el6.x86_64
         system: CloudLinux Server 6.7 Aleksei Gubarev
```

**Comment by jfindlay** [comment]
@afletch, thanks for reporting.

**Comment by afletch** [comment]
Did my description get nixed somehow? I definitely provided a full run-down.

**Comment by jfindlay** [comment]
@afletch, that is very strange.  I remember reading your description.  I heard someone else complaining about the same thing on another issue today.  Github may be having some problems.

**Comment by afletch** [comment]
@jfindlay Very odd, fortunately it was open in another tab - I've re-applied it.

**Comment by afletch** [comment]
@jfindlay Could this please have some attention - it's preventing Salt working at all on CloudLinux.

**Comment by jfindlay** [comment]
Ping @cachedout.

**Comment by MadsRC** [comment]
I'm seeing the same thing on CloudLinux aswell. State maps stops working as they matched Red Hat earlier. The pkg module also breaks, as it states that pkg does not exist. I suspect pkg uses os_family to map package manager?

Anyone know why CloudLinux Server got it's own "os_family"? - It's a Red Hat derivative, just like Ubuntu is a Debian derivative - We don't treat Ubuntu any different from Debian?

**Comment by MadsRC** [comment]
@jfindlay - Is this something that will get attention? As @afletch mentioned, it's preventing Salt from working on CloudLinux.

**Comment by afletch** [comment]
It's such a basic change, yet nobody seems willing to make it.

**Comment by jfindlay** [comment]
@MadsRC, I'm not sure what motivated the change.  You may want to ask someone more knowledgeable like @cachedout or @rallytime.

**Comment by MadsRC** [comment]
I seem to have found a fix that isn't a total hack, though would have to test a bit more, and make sure my logic is sane.

I'll send a pull request with the fix once I'm sure it works.

**Comment by afletch** [comment]
@MadsRC When I tested this, all that was required was the change in my original post, if you identify the family correctly then all the other parts fall into place.

**Comment by MadsRC** [comment]
@afletch - I see you mentioned having to change cloudserv to cloudlinux in #28951 - However that doesn't seem to work in my end.

What I had to do to fix it is replace line 1021 in `grains/core.py` with 'CloudLinux Server'. This will correctly map CloudLinux machines to the RedHat family. I checked that the pkg module, aswell as the osfiner and osmajorrelease grains work, and they do.

Still really can't figure out why it works, but I think it has something to do with the regex... It'll be some time before I have the time to do a pull request, so for now I've manually patched my CloudLinux Servers.

**Comment by MadsRC** [comment]
Now I can't seem to reproduce the errors I got with replacing `cloudserve` with `cloudlinux` - In fact it seems to work fine. Guess you can choose whatever fix you prefer :D

**Comment by terminalmage** [comment]
@MadsRC We never "gave" it its own ``os_family``. The way this works is that the ``os`` grain is checked against a mapping of ``os`` grains to ``os_family`` names, and if no match is found, as a fallback we use the ``os`` grain itself as the ``os_family``. It looks like, way back in 2013, the /etc/redhat-release or /etc/os-release or whatever began with ``CloudServer`` or something like that. At some point, this appears to have changed. So, the entry in the ``_OS_NAME_MAP`` no longer matches, which means we don't identify the ``os`` grain as ``CloudLinux``, which consequently means there is no mach in the ``_OS_FAMILY_MAP`` which maps the ``os`` grain to its ``os_family``.

I opened https://github.com/saltstack/salt/pull/36408 to properly identify CloudLinux so that it gets the RedHat ``os_family``.

Also, just FYI, I _think_ it is possible to manually set the ``os`` and ``os_family`` grains using [grains.setvals](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.setvals)

```
salt minionname grains.setvals "{'os': 'CloudLinux', 'os_family': 'RedHat'}"
```

This will add these grains to ``/etc/salt/grains``. I'm not 100 percent certain this solution will work though as I haven't tested it. In other words, I don't know if core grains evaluation happens before or after ``/etc/salt/grains`` is evaluated.

We don't often recommend people manually set important grains like this because it can have unexpected consequences, but this is one of the exceptions to the rule.
