### ISSUE TITLE
Using exclamation marks in SLS

### ISSUE THREAD

**Issue by yee379** [saltstack/salt#32433]
### Description of Issue/Question

I'm using salt to pass some configuration for a ldap query. specifically, i want a 'not' query which would like something like this

`!(objectclass=computer)`

however, the sls doesn't get pas the salt rendering stage.

### Setup

    keystone:
      domains:
        SLAC:
          ldap:
            user: <REDACTED>
            password: <REDACTED>
            tls_req_cert: allow
            url: ldaps://ldap.server:636
            page_size: 100
            chase_referrals: 0
            query_scope: sub
            user_tree_dn: DC=blah,DC=blah,DC=blah
            user_objectclass: person
            user_id_attribute: cn
            user_name_attribute: samaccountname
            user_filter: '!(objectclass=computer)'

### Steps to Reproduce Issue

Trying to execute the sls results in:

       Data failed to compile:
    ----------
        Rendering SLS 'openstack:openstack.keystone.domains' failed: could not determine a constructor for the tag '!(objectclass=computer)'
      in "<unicode string>", line 106, column 24:
                  user_filter: !(objectclass=computer)
                               ^

### Versions Report

               Salt: 2015.5.8
             Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
           dateutil: 1.4.1

**Comment by jfindlay** [comment]
@yee379, thanks for reporting.  Have you tried double quoting the string, `'"!(objectclass=computer)"'` or escaping the special character, `\!(objectclass=computer)`?  I seem to remember double quoting being necessary because SLS data passes through jinja and yaml by default, but I can't find any of the issues I was thinking of.  You can review the rendered state before it enters the state compiler by using `state.show_sls`, or more drastically, you may consider the [py](https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.py.html) or [pyobjects](https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.pyobjects.html) or [pydsl](https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.pydsl.html) renderers for your SLS data.

**Comment by yee379** [comment]
thanks @jfindlay, escaping with `\` results in

                      user_filter:
                          \!(objectclass=computer)

which is undesirable as my config file doesn't like the escape character. but  double quotes works great! coincidentally, i ended up using:

            user_filter: '(!(objectclass=computer))(!(objectclass=contact))'

and that works too.

cheers!
