### ISSUE TITLE
Feature request: provide a state module to manage Consul's content

### ISSUE THREAD

**Issue by multani** [saltstack/salt#32540]
Salt should provide a way to configure Consul content, such as (non-exhaustive list, but they are my needs at the moment):
- K/V values
- ACLs

There are probably other things that can be configured as states, although the other things can be configured via JSON files loaded by the agents.

**Comment by multani** [comment]
I started a branch on top of 2015.8 (which is the version I'm using) with a module to set/remove K/V from Consul, with integration tests for the execution and the state modules, you can have a look here : https://github.com/saltstack/salt/compare/2015.8...multani:feature/consul-state

It's still very simple for now, as it doesn't deal with locks, concurrency issues, or CAS operations. There's no support for tokens yet, I'm not sure how the underlying execution module actually behaves when if it needs to use tokens.

I'm not sure how I should handle the integration tests with an external Consul instance. At the moment I suppose something is running somewhere and the tester has to expose the Consul's URL via an environment variable, but feedback on this would be welcome.

**Comment by jfindlay** [comment]
@multani, that looks great.  You should also be sure to define a `__virtual__` function in the state module so that the salt loader knows how to load it.  You can also consider writing unit tests, if you want the tests to be easier to run.  Be sure to reference https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html on the best practices for salt unit tests.
