### ISSUE TITLE
winrepo/winrepo-ng: package xyz not found in the repository.

### ISSUE THREAD

**Issue by andrebron** [saltstack/salt#32602]
### Description of Issue/Question

salt and salt-call cannot install anything from the winrepos.
The package xyz not found in the repository.

(specifically, trying to install nsclient from the winrepo-ng

### Setup
```sls
file_roots:
  base:
   - /srv/salt/states/base
   - /srv/formulas/nagios-formula
  development:
   - /srv/salt/states/development
  production:
   - /srv/salt/states/production

pillar_roots:
  base:
   - /srv/salt/pillars/base
  development:
   - /srv/salt/pillars/development
  production:
   - /srv/salt/pillars/production
```
Windows Software Repo settings #####
#
Location of the repo on the master:  I had to change this from /srv/salt/win/repo since winrepo-ng and all it's sls files are pulled by git into this directory.
`win_repo: '/srv/salt/win/repo-ng/salt-winrepo-ng'`
#
Location of the master's repo cache file:  This is correct.
`#win_repo_mastercachefile: '/srv/salt/win/repo/winrepo.p'`
#
List of git repositories to include with the local repo:
```
win_gitrepos:   Does this need to be enabled?
 - 'https://github.com/saltstack/salt-winrepo.git'
```

### Steps to Reproduce Issue
salt-call debug logging does not show anything specific to the issue except package xyz not found in the repository.

### Versions Report
```
master:

salt --versions-report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Ubuntu 14.04 trusty
 
minion:

PS C:\salt> .\salt-call.bat --versions-report
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: 2012ServerR2 6.3.9600  Multiprocessor Free
```

**Comment by andrebron** [comment]
I noticed this was requested for another ticket so here it is:

PS C:\salt> .\salt-call.bat pkg.list_available
[INFO    ] Determining pillar cache
local:
PS C:\salt> .

**Comment by damon-atkins** [comment]
I used a symbolic link to to point it to the default location from your file_roots for each environment you have.   In your case /srv/salt/states/base      The other alternative is to add it to file_roots for base.  It's not clear in the doco if you change file_roots what impact is has for other items.

**Comment by damon-atkins** [comment]
I am working on adding pkg.info_installed for windows which should make things easy to work out what is going on.

**Comment by ssgward** [comment]
@andrebron - did you run a ``salt <target minion(s)> pkg.refresh_db? This is a needed step in order to get the minions to see the repo contents.

**Comment by twangboy** [comment]
I see a few things going on here that look a little suspicious to me:

1. You're using the ``win_repo`` instead of ``winrepo_dir``.
2. You're setting the 'NG' repo to the older repo location.
2. You're generating a ``winrepo.p`` file for minions that don't need it.

### A Little History
In 2015.8 we introduced the ability to parse jinja in our software definition files. As a result the sls files are copied to the minion and the winrepo.p file is generated locally on each minion. Because the jinja in the sls files would break older minions (<=2015.5) we had to create a next generation (ng) repository to host the software definitions for the new architecture. As a result we added two new parameters to the master config: 
``winrepo_dir_ng`` which defaults to ``/srv/salt/win/repo-ng/``
``winrepo_remotes_ng`` which defaults to ``

#### Note
The names of some of the parameters have changed. I noticed you're using ``win_repo`` in your master config. Perhaps this is leftover after upgrading from a previous version. Here is how they changed:
``win_gitrepos`` is now ``winrepo_remotes``
``win_repo`` is now ``winrepo_dir``
``win_repo_mastercachefile`` is now ``winrepo_cachefile``

So, you only need to generate the ``winrepo.p`` file if you have minions that are 2015.5.X and lower. Otherwise, you don't need it.

So the default process for Salt is as follows.

### 1. On the master run ``salt-run winrepo.update_git_repos``
This will pull both repos down to the master. 
- Salt-Winrepo will go into ``/srv/salt/win/repo``. (older minions)
- Salt-Winrepo-Ng will go into ``/srv/salt/win/repo-ng``. (newer minions)

### 2. On the master run ``salt-run winrepo.genrepo``
Do this step only if you have older minions you need to support.
This will generate a winrepo.p file based on the contents of ``/srv/salt/win/repo``

### 3. On the master run ``salt '<minion>' pkg.refresh_db``
On older minions this will copy down the winrepo.p file generated in step 2
On newer minions this will copy down all the sls files in ``/srv/salt/win/repo-ng/`` to the minion. The minion will then parse the jinja and generate its own winrepo.p file.

###  So....
The easiest thing to do here would be to remove the customized settings you have for winrepo and just let salt use the defaults.
https://github.com/saltstack/salt-winrepo should sync to ``/srv/salt/win/repo``
https://github.com/saltstack/salt-winrepo-ng should sync to ``/srv/salt/win/repo-ng``

### To disable winrepo for older minions
If you only have 2015.8 windows minions and you don't want to pull the git repo for older minions, set the following in the master config:
``winrepo_remotes: []``

For more details see the documentation.
https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#repository-location

**Comment by andrebron** [comment]
Thank you so much for your timely responses!  I had tried pkg.refresh_db on the windows minion.  I will review all your recommendations, see if it's fixed and get back to you soon.

**Comment by andrebron** [comment]
I followed the recommended changes to the salt master config and followed the steps as well with a fresh vagrant ubuntu salt master but the windows server 2012 minion keeps failing to install any package.

**Comment by andrebron** [comment]
Can someone just post a working salt master config for winrepo/winrepo-ng for the 2015.8 plus salt versions?  I will try that and get back to you.

**Comment by andrebron** [comment]
Hi Salt team.  Please review my last post.  If you post a winrepo working salt master config for 2015.8 plus would be super helpful.

**Comment by damon-atkins** [comment]
Example on the master
-rw-r--r--. 1 root root 409 Mar 25 22:05 top.sls
lrwxrwxrwx. 1 root root  13 Mar  7 03:13 win -> /srv/salt/win
I assume the other way would be to add /srv/salt/win into your file_roots base  or any other environment.   Note that pkg for windows only works for **base ** environment, their is a patch in develop to support multiple environments.

**Comment by andrebron** [comment]
Oh wow.  I thought I had winrepo working before in the past without a symlink from base environment pointed to the win dir.

**Comment by andrebron** [comment]
@damon-atkins  I created a symlink as suggested into the base environment dir:

-rw-r--r--. 1 root root 409 Mar 25 22:05 top.sls
lrwxrwxrwx. 1 root root  13 Mar  7 03:13 win -> /srv/salt/win

Still doesn't install any package.

**Comment by ssgward** [comment]
I use the default master.conf file with these entries (which are default, too, if I remember correctly) and package installs work all the time.
```
# To use multiple backends list them in the order they are searched:
fileserver_backend:
  - roots
  - git
```
AND
```
#####     Windows Software Repo settings for 2015.8 or newer#####
##############################################
# Location of the repo on the master:
winrepo_dir: '/srv/salt/base/win/repo'
winrepo_dir_ng: '/srv/salt/base/win/repo-ng'
```
See if this helps get you further down the package install road.

**Comment by andrebron** [comment]
@ssgward Thanks. Followed your config recommendations.  But it still doesn't work.  I am going to test outside the vagrant virtualbox local environment and see if that has anything to do with the fails...

Otherwise, any other ideas?

**Comment by ssgward** [comment]
@andrebron - no other ideas at this point. Everything that has been posted to this point should have gotten you working. 

If you're using vagrant I guess there is the chance your windows minion may not have a network connection to the outside world, just an internal network between the master and minion. But maybe you've checked that already.

**Comment by andrebron** [comment]
"windows minion may not have a network connection to the outside world"

@ssgward  Interesting! The windows minion does not have a network connection to the internet.  It only has local networking. So, is having internet access a requirement to run winrepo package installations??

**Comment by andrebron** [comment]
@ssgward I checked and the windows minion has internet access...

I am a bit confused because winrepo worked before in other environments and perhaps versions...

I get this error exactly:

Package nsclient not found in repository.

**Comment by ssgward** [comment]
@andrebron - do you have a ``C:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng_git`` folder on your minion? If so, does the folder contain anything?

Exact path may be slightly different on your system/minion due to different config settings than I have.

**Comment by andrebron** [comment]
@ssgward There is a C:\salt\var\cache\salt\minion\files\base\win\repo-ng\winrepo.p file.
But no salt-winrepo-ng_git directory...

**Comment by ssgward** [comment]
@andrebron - the ``salt-run winrepo.genrepo`` followed by ``salt <win minon> pkg.refresh_db`` command will place the ``C:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng_git`` on your Windows minion (which will then allow packages to be installed). If the ``salt-winrepo-ng_git`` folder creation on the minion isn't happening after the commands then attach your master and minion log file (may be too large) or, at least, snippets from the log files with the most recent log entries for further troubleshooting.

**Comment by andrebron** [comment]
@ssgward Making progress here!  What you suggested now works.
Now I get a stack trace and an error like this:

gaierror: [Errno 11001] getaddrinfo failed

I am not sure why this is happening...  Looks like the minion cannot get the package once the state is called in the winrepo.  Any ideas?

**Comment by andrebron** [comment]
Now it works.  Not sure what changed since but it's working now.

Thanks for the help team!

**Comment by ssgward** [comment]
Glad its all working!

**Comment by necroscope** [comment]
in my file_root I had to do this in /srv/saltacmce/base
ln -s /srv/salt/win win

I discovered if you have an non-standard or non default file_root the symlink is the way to get it working as the winrepo is somewhat tied to the traditional /srv/salt

**Comment by SaltMPA** [comment]
I don't want to open a new issue since my issue is very close to this one, although I cannot see what actually did the trick for the poster. I am having trouble making the minion repo sync with the salt master. I basically installed a local Adobe Acrobat Reader package for Windows on the salt winrepo (at /srv/salt/win/repo-ng/salt-winrepo-ng), and did pkg.refresh_db a number of times. I was able to do pkg.install and pkg.remove successfully, but when I tried to make a state file control the installation I keep getting 
Package adobereader-dc-classic not found in the repository:
![stateapplyerror](https://user-images.githubusercontent.com/30290579/28576052-05c10770-7153-11e7-8365-81b3f9e28856.png)

A little digging showed that the minion repository wasn't synced to reflect the master:

![minionnotsynced](https://user-images.githubusercontent.com/30290579/28576179-63a64936-7153-11e7-8e4c-e4b008a2b00b.png)

At one point I renamed the folder containing the package installer on the salt master, but even though I did several salt-run winrepo.genrepo (followed by pkg.refresh_db) the minion always was left with the old folder name, thereby creating the above state.apply error. 

Any suggestions?

**Comment by damon-atkins** [comment]
`salt-run winrepo.genrepo`  and the old /srv/salt/win/repo  is for very old versions of salt.
The only files sync with pkg.refresh_db are *.sls files.    As these are used to create the db on the minion.

**Comment by twangboy** [comment]
@SaltMPA It would be helpful to see the contents of `adobereader-dc-classic.sls`

**Comment by SaltMPA** [comment]
Here is my sls file, adobereader-dc-classic.sls:
![slsfile](https://user-images.githubusercontent.com/30290579/28609033-427d51ec-71e3-11e7-8ea6-661dea4f8f83.png)

In my understanding if refers correctly to the installer path and file (including version) on the salt master, but salt is not able to find it on the minion because the latter still refers to an old folder name, adobereader-dc containing the installer file.
From damon-atkins I now understand that pkg.refresh_db only syncs sls files between salt master and minions. How is the minion then going to get hold of the installer file from the master?

**Comment by SaltMPA** [comment]
Oh, and to make it clear, I am running on an internet-less master, that's why the installer reference is to salt:// and not http(s)://. The local winrepo seems to work, as I am able to pkg.install and pkg.remove. The problem seems related to synchronization between the master and minion repos. At some point, I renamed the folder containing the installer file adobereader-dc -> adobereader-dc-classic on the master and ran pkg.refresh_db expecting that the minion would sync its local folder accordingly. It's clear now that it didn't, leaving the folder naming out of sync (adobereader-dc-classic on the master and adobereader-dc on the minion). I believe that's the reason why salt complains that it cannot find the package when I do state.apply. How do I sync the folder structure of the installer file between master and minion?

**Comment by damon-atkins** [comment]
It general best to paste text rather than past screen images. (FYI to delete a  image you have to ask github)
It downloads from the `installer `location when required. Otherwise you would fill up minions with items they do not need.   You can use an internal web server.

**Comment by SaltMPA** [comment]
I'm sorry, I don't understand the answer. How do I resolve the missing package error I get?

**Comment by SaltMPA** [comment]
I am running remote sessions based SSH connections to the salt master and giving a detailed overview over salt commands and results in the console is easiest to do with screenshots, but I will try to post sls files as plain text.

When I tried to add the refresh parameter to my pkg declaration:
install_adobe_reader:
  pkg.installed:
    - name: adobereader-dc-classic
    - refresh: True

, and execute state.apply, the folder structure now syncs on the minion to the installer resides in the adobereader-dc-classic folder there too. But I still get the same error...("Package adobereader-dc-classic not found in the repository") :/

**Comment by damon-atkins** [comment]
```
cd \salt
salt-call get_repo_data to find out what the processed sls looks like.
salt-call pkg.refresh_db   # optionally add verbose=True
salt-call -l debug pkg.install adobereader-dc-classic  # you can also run the master in debug mode.
```
Its more then likely you do not have the paths correct.

Adding `refresh: True` to a state will have a performance impart, as refresh is an expensive operation on Windows.

**Comment by SaltMPA** [comment]
Running your suggested commands yields:
[root@cloud-salt02 salt]# salt-call get_repo_data
'get_repo_data' is not available.
[root@cloud-salt02 salt]# salt-call pkg.get_repo_data
'pkg.get_repo_data' is not available.
[root@cloud-salt02 salt]# salt-call pkg.refresh_db
local:
    True
[root@cloud-salt02 salt]# salt-call pkg.refresh_db verbose=True
local:
    True
[root@cloud-salt02 salt]# salt-call -l debug pkg.install adobereader-dc-classic
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: cloud-salt02.cloudstack.dk
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Popen(['git', 'version'], cwd=/srv/salt, universal_newlines=False, shell=None)
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'cloud-salt02.cloudstack.dk', 'tcp://172.27.140.49:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8190)
[DEBUG   ] Setting zmq_reconnect_ivl to '8190ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'cloud-salt02.cloudstack.dk', 'tcp://172.27.140.49:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_01b16b30ea_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_01b16b30ea_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_01b16b30ea_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-07-26T09:20:46.174861', 'creds': {'publish_port': 4505, 'aes': 'E2v2pLhe+Ufp4Ef8ZVlmv6dBCqEaNYvXrZeYqF+fsuiQuHmYQACNe4veeMGBmqKix/IWcmj2ybA=', 'master_uri': 'tcp://172.27.140.49:4506'}, 'key': ('/etc/salt/pki/minion', 'cloud-salt02.cloudstack.dk', 'tcp://172.27.140.49:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'cloud-salt02.cloudstack.dk', 'tcp://172.27.140.49:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'cloud-salt02.cloudstack.dk', 'tcp://172.27.140.49:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[DEBUG   ] Failed to get holds, versionlock plugin is probably not installed
[DEBUG   ] LazyLoaded config.get
[INFO    ] Executing command ['systemd-run', '--scope', 'yum', '-y', 'install', 'adobereader-dc-classic'] in directory '/root'
[ERROR   ] Command '['systemd-run', '--scope', 'yum', '-y', 'install', 'adobereader-dc-classic']' failed with return code: 1
[ERROR   ] stdout: Running scope as unit run-12977.scope.
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.dk.telia.net
 * extras: mirror.fysik.dtu.dk
 * updates: mirror.fysik.dtu.dk
No package adobereader-dc-classic available.
Error: Nothing to do
[ERROR   ] retcode: 1
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1377, in install
    info={'errors': errors, 'changes': ret}
CommandExecutionError: Error occurred installing package(s). Additional info follows:

changes:
    ----------
errors:
    - Running scope as unit run-12977.scope.
      Loaded plugins: fastestmirror
      Loading mirror speeds from cached hostfile
       * base: mirrors.dk.telia.net
       * extras: mirror.fysik.dtu.dk
       * updates: mirror.fysik.dtu.dk
      No package adobereader-dc-classic available.
      Error: Nothing to do
Error running 'pkg.install': Error occurred installing package(s). Additional info follows:

changes:
    ----------
errors:
    - Running scope as unit run-12977.scope.
      Loaded plugins: fastestmirror
      Loading mirror speeds from cached hostfile
       * base: mirrors.dk.telia.net
       * extras: mirror.fysik.dtu.dk
       * updates: mirror.fysik.dtu.dk
      No package adobereader-dc-classic available.
      Error: Nothing to do

Does that ring a bell with you? I have no idea, but I see the first error line being:
[ERROR   ] Command '['systemd-run', '--scope', 'yum', '-y', 'install', 'adobereader-dc-classic']' failed with return code: 1

I also find the error line further below quite amusing:
      No package adobereader-dc-classic available.
      Error: Nothing to do
XD

I guess I should stop trying to fix it then ;)

**Comment by damon-atkins** [comment]
`salt-call ` is run on the minion not the master.
Remote Desktop to the minion.
Run cmd.exe / Command Prompt as "Run As Administrator"
```
cd \salt
salt-call ....
```

**Comment by twangboy** [comment]
@SaltMPA The `adobereader-dc-classic.sls` is a software definition file. It tells salt where the installer is, how to install it, how to uninstall it, etc. Salt uses the information within this file to install the software. Since you specified a location on the salt file server using `salt://` the `pkg.install` function will cache that file from the salt master to the minion upon execution. It will then execute that file locally with the installer parameters described in your software definition file.

As Damon said, `pkg.refresh_db` copies only the `.sls` files and generates the local message pack file from those files. This is to avoid copying down every piece of software on the master every time you do a `pkg.refresh_db`.

Some of the common problems I've seen with people trying to get their packages to work is the full_name must match exactly what shows up in `add/remove programs`. Another is the version, which must also match.

The error you're seeing though is produced by the following code:
```
            pkginfo = _get_package_info(name, saltenv=kwargs['saltenv'])
            if not pkginfo:
                return {'name': name,
                        'changes': {},
                        'result': False,
                        'comment': 'Package {0} not found in the '
                                   'repository.'.format(name)}
```
which looks like maybe the name of the package in your state file doesn't match exactly what's in your software definition file. This error is occurring before the minion attempts to cache anything down from the master. It's not finding that package name in the message pack file.

Since I don't know what your state file looks like I would have you check to make sure it's something like this:
```
install_adobe_reader:
  pkg.installed:
    - name: adobereader-dc-classic
```

Another thing to watch is multiple software definition files for the same installer in the repo. Are there other software definition files in the `/srv/salt/win/repo-ng/` directory that also have a name of `adobereader-dc-classic`. It's kind of a last one wins scenario. So, maybe your software definition file is correct, but it's being overwritten by another with the same name.

There could also be a problem with the YAML/JINJA that is causing the software definition file not to render properly and therefore is not included in the message pack file.... This may be more likely. Did you get an errors when you ran `pkg.refresh_db`?

You can check that your sls is parsing correctly by running the following command:
```
salt -G 'os:windows' winrepo.show_sls salt-winrepo-ng.adobereader-dc-classic
```

Anyway, just guessing at a few things here. I hope this is helpful.

**Comment by SaltMPA** [comment]
Thank you @twangboy for your thorough answer.
Your first instinct proved to be correct. It was a case of a silly typo in my state file, which explained why pkg.install worked and applying state didn't.

```
install_adobe_reader:
  pkg.installed:
    - name: adobereader-do-classic


```
After correcting the name to adobereader-dc-classic everything worked like a charm!
Thank you so much! :)

**Comment by twangboy** [comment]
@SaltMPA Excellent! Glad we could help.

**Comment by damon-atkins** [comment]
@twangboy 
Could you organise someone to change the title to something like
`win_pkg: help,  winrepo-ng package not found or no files report with pkg.refresh_db`
Try to make it a bit easier to find, so people can get self help.

@SaltMPA Pls delete/edit https://github.com/saltstack/salt/issues/32602#issuecomment-318005351 as it might confuse anyone who reads this.

**Comment by twangboy** [comment]
@damon-atkins Done

**Comment by SaltMPA** [comment]
@damon-atkins Right, in light of the nature of the problem at hand, it would indeed. Deleted said comment and thanks again for your excellent help! :)
