### ISSUE TITLE
half-baked idea for winrepo

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#32740]
### Description of Issue/Question

Hi salt people,
I'm just pondering an idea for winrepo. There may be reasons why it will never work or why it's
a bad idea.
In the windows registry it is often the case that a program has a non-canonical name that also includes version info (e.g. 'Mozilla Firefox 31.0 (x86 en-US)', instead of just 'Firefox' or 'Mozilla Firefox'). That being said it seems that firefox may be one of the last offenders because other programs are getting better at not doing this sort of thing any more (e.g. Chrome and Adobe Reader DC are now well behaved in this regard.)

My half-baked idea is to have an option to change the display name in the registry as soon as an install is complete, so a state configuration for firefox might look something like:

```
'29.0.1':
    full_name: firefox
    installer: 'http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/29.0.1/win32/en-US/Firefox%20Setup%2029.0.1.exe'
    install_flags: '/s'
    uninstaller: '%ProgramFiiles(x86)%\Mozilla Firefox\uninstall\helper.exe'
    uninstall_flags: '/S'
    msiexec: False
    locale: en_US
    reboot: False
    original_name: 'Mozilla Firefox 29.0.1 (x86 en-US)'
```

So I've added an 'original_name' entry in the specification and if this were to work firefox would be installed and then the display name in the registry would be immediately changed from 
"Mozilla Firefox 29.0.1 (x86 en-US)" to just "firefox". 
[This might break a million things but I wouldn't know. I'm just wondering what other people think of this idea.]

**Comment by hrumph** [comment]
Pursuant to an on-line discussion I realised that I needed to communicate the motivation for this idea. The problem is with the use of allow_updates and firefox. Since firefox doesn't have a canonical displayname it seems to be that if you updated (or autoupdated) firefox to a new version not in the repo list, it simply wouldn't get matched and the new version of firefox wouldn't be recognised by salt so allow_updates won't work. My proposal is one way around this. Another would be some provision for matching on patterns. I haven't tested my assertion that it won't work so it will be awfully embarassing if in fact it does and I don't understand what's going on (I'm away from my test environment right now so I can't test).

**Comment by damon-atkins** [comment]
I know where you are coming from, unfortunately this is a bad idea, as you do not know how it will impact the uninstall program and also impact other audit tools.

I have  developed pkg.info_installed, I am just doing some testing, which will show up a lot of these issues. e.g. to find the version for the software it looks in 3 or 4 places.  My hope once this code is tested by more people it can become source of the version installed for other parts of pkg.* for windows.

Its design to handle the things installers do wrong in the registry.

**Comment by jfindlay** [comment]
Ping @twangboy, @thebigbear.

**Comment by TheBigBear** [comment]
@hrumph I also understand where you are coming from but unfortunately I have to agree with @damon-atkins this is a BAD idea. 

You simply don't know how many other things you are breaking by doing this.

I am aware that we have had an issue with Firefox ESR in particular (and possibly also with Firefox itself) in that I was out of the office for just over a month and simply didn't have the time or internet bandwidth to actively maintain the Firefox sls files in the old and new winrepos.
On top of that I had somehow completelty missed the fact that Firefox (suddenly?) came out with a 45.x series of releases in their ESR branch. I thought this ESR bracnh was ALWAYS a much older version series. But I might be wrong on that, and maybe the ESR series versions were always available parallel to the latest Firefox stable version? 

Anyway, I have now "caught up" and am now maintaining Firefox AND Firefox ESR both in the most recent release versions in the 45.x series.

So the recent snafu of Firefox ESR "upgrading" to a much older 38.x series because winrep and winrepo-ng weren't aware of any 45.x version for the ESR should be a thing of the past.

I like the sound of @damon-atkins  "pkg.info_installed" improvements on catching version numbers by the sound of it out of the actual windows Display name. BUT I have to ask, why omn earth is this even necessary in the first place? As far as I can tell and test, Firefox ARE DOING THE RIGHT THING? i.e. they are properly populating the windows version number, it DOES NOT exist only in the display name, so what I do not understand is why Firefox and Firefox ESR woudl need any help in properly detecting the actually installed version number?

In my mind and understanding, it sounds more like a 'bug' or 'mis-feature' somewhere in the windows salt pkg manager 'update' algorhythms that allows an update from say ver. 45.0.1  to ver. 38.0.3?
 
What am I missing?

**Comment by hrumph** [comment]
@TheBigBear I can see that changing registry values post-install is a crazy idea. It was just something that came to mind but it wouldn't be useful anyway. I'm still away from my test environment so I'm probably just wrong about everything. What I don't understand is how an update can always be recognized when non-canonical display names are being used. For instance if you have "Mozilla Firefox 29.0.1 (x86 en-US)" installed and supposing that "Mozilla Firefox 29.0.1 (x86 en-US)" is in your repo while "Mozilla Firefox 30.0.0 (x86 en-US)" is not in your repo, and then firefox auto-upgrades to "Mozilla Firefox 30.0.0 (x86 en-US)", then I don't see how salt can match the new install to anything in the repo at that time (there is no provision for matching on patterns), thus salt would force a downgrade even with allow_updates set to True.

With chrome and adobe reader-dc we would never have this problem because the display names aren't in continual flux.

**Comment by hrumph** [comment]
@TheBigBear @damon-atkins @twangboy @UtahDave @jfindlay 
Hi again guys,
I decided to test my assertion concerning the central problem I'm having and so far I'm right (unless I have some kind of fundamental misunderstanding). I am sorry for not testing this at when I posted the issue at first but as I said I am away from my test environment.

OK, so let's start out by observing the following:
firefox.sls has the following fragment:

```
  '45.0.1':
    full_name: 'Mozilla Firefox 45.0.1 (x86 en-US)'
    installer: 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/45.0.1/win32/en-US/Firefox%20Setup%2045.0.1.exe'
    install_flags: '/s'
    uninstaller: '%ProgramFiles(x86)%\Mozilla Firefox\uninstall\helper.exe'
    uninstall_flags: '/S'
    msiexec: False
    locale: en_US
    reboot: False
  '45.0.2':
    full_name: 'Mozilla Firefox 45.0.2 (x86 en-US)'
    installer: 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/45.0.2/win32/en-US/Firefox%20Setup%2045.0.2.exe'
    install_flags: '/s'
    uninstaller: '%ProgramFiles(x86)%\Mozilla Firefox\uninstall\helper.exe'
    uninstall_flags: '/S'
    msiexec: False
    locale: en_US
    reboot: False
```

With this in mind, I ensured that firefox 45.0.2 was installed on my minion and I created the following state file to be invoked by top.sls
```
firefox installed:
   pkg.installed:
      - name: firefox
      - version: 45.0.1
      - allow_updates: True
```

I ran state.apply and salt was happy. (Sorry I lost the output in scroll but salt did not attempt to downgrade to 45.0.1).

The next thing I did was remove the 45.0.2 section from firefox.sls. This time when I ran state apply, as I suspected, salt forced a downgrade even though I have allow_updates set to true. This is because salt can no long recognise firefox because "Mozilla Firefox

**Comment by damon-atkins** [comment]
I plan to look at this after I have pkg.info_installed merged into develop.  I need to submit a fix for reg  (registry) Unicode support first, before I submit pkg.info_installed.  @TheBigBear I am using a laptop which is about 5 years old. Its had programs installed and remove and patches etc.  Its a good test.  

Worst thing I have seen so far is program which set version which is meant to be a binary number in the registry and set it to a string type with a string version number.  :-(   Unfortunately the research as taken longer than the programming.

**Comment by hrumph** [comment]
At the very least this should be considered a documentation bug because description of allow_updates is
> Allow the package to be updated outside Salt's control (e.g. auto updates on Windows). This means a package on the Minion can have a newer version than the latest available in the repository without enforcing a re-installation of the package.
The documentation should point out when it's going to work and when it isn't.
