### ISSUE TITLE
[DOCS] Feature Parity Matrix request

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#32846]
### Description of Issue/Question

We need to have a table/matrix that shows which modules/states are available for each OS. This would be good for users as well as for SaltStack to help steer development.

**Comment by damon-atkins** [comment]
+1 its a pitty the doco system can not look to see if more than one module exists for different platforms and present a link to say the Windows version of the doco.

I got try something on windows only to find it was not implemented yet.
e.g. winrepo-ng pkg.upgrade no error message from master for unsupported feature #31889

**Comment by TheBigBear** [comment]
@twangboy really? I understand the point @daemon-atkins is making and actually I fell into the same trap. I also read the docs and believed it was working just as the docu says. But in this case, it is surely more important to actually get ```'pkg.upgrade'``` work  under windows, especially seeing that ```'pkg.list_upgrades'``` already works, instead of adding a warning about this not being implemented?

**Comment by damon-atkins** [comment]
.

**Comment by sagetherage** [comment]
I would love to have this, but it cannot be static documentation. I cannot commit to this in Phosphorous, but will look at the Docs Working Group to see if we can get a plan together.

**Comment by barbaricyawps** [comment]
Closing this issue as Shane now feels it is stale.
