### ISSUE TITLE
__env__  saltenv for non-states

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#33014]
### Description of Issue/Question
Any reason why \_\_env\_\_ can not be set all the time.  i.e. It seems only to be set for states.

And then maybe add to salt-call and salt a way to set it overriding what is in the minion configuration file.

Otherwise I suspect all modules will have to have code/parameters to set saltenv/\_\_env\_\_  ??

**Comment by damon-atkins** [comment]
e.g.  #30763

**Comment by jfindlay** [comment]
`__env__` is an argument internal to the state system.  Execution modules that need to know the saltenv can get it from the command line, for example.

**Comment by damon-atkins** [comment]
Where I am coming from why have hundred of salt function in execution modules handling saltenv a different way, or not handling it at all, when it could be handle globally for execution modules just once available for all functions to use.

**Comment by jfindlay** [comment]
@damon-atkins, salt environments are more tightly coupled to state modules than salt modules because of how the top file or file roots assign states to different minions or sets of minions, whereas with modules, this kind of logic is usually handled with targeting.  The execution modules that use `saltenv` usually need it because they're referring back to some part of the state system.  For example the `cp.list_master` function accepts a `saltenv` argument so it can list files in that environment, and the `state.apply` function accepts a `saltenv` because it needs to know which environment to apply a state unto.

Since `file_roots` and or the top system are the source of authority of what value `__env__` contains, I am unsure how `__env__` would be well-defined or defined at all in every context in which execution modules will be run.  The only context I can think of where it could be well-defined is if an execution module is being run by a state module.
