### ISSUE TITLE
salt-ssh makes too many connections to run salt state

### ISSUE THREAD

**Issue by kt97679** [saltstack/salt#33066]
### Description of Issue/Question
I have very simple salt state which I run using salt-ssh:
<pre>
.uptime:
    cmd.run:
        - name: uptime
</pre>
From the /var/log/auth.log on the target I see that salt-ssh connected 6 times. Please optimize salt-ssh logic and reduce number of connections.

Thanks!

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Sls file is shown above.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run state above using salt-ssh, look into /var/log/auth.log on the target machine to see how many connections were done by the salt-ssh.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
<pre>
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Ubuntu 14.04 trusty
</pre>

**Comment by thatch45** [comment]
The short answer is:
salt-ssh is already very fast and we are happy with the performance, but if you can tell us HOW to lower the number of connections, then we are all ears!
The long answer is:
salt-ssh uses concurrent connections optimized for connecting to large numbers of servers in quick succession, this is the main reason why salt-ssh is so much faster than "other" ssh configuration management tools, the main take away is that many connections does not mean bad performance, it means that we use complex algorithms to increase performance over time. salt-ssh is also optimized for repeat connections and being able to minimize network traffic. So for repeat salt-ssh runs you will find that the number of connections drops because the execution environment gets cached, you will also see that salt-ssh exposes salt's remote execution system (something "other" ssh tools don't even have) and that that first run with 6 connections sets up a persistent system that allows us to always use just one connection for remote execution calls.
Finally we have the fact that salt-ssh can be allowed to make more connections to more servers in a dynamic way, this allows us to use very powerful multi machine orchestration in a non-blocking fashion, also allowing salt-ssh to scale much higher than "others".
Finally, the co-routine argument, since we can maintain multiple ssh connections at the same to time do different work, we are able to multiplex the work to make salt-ssh faster, so more connections actually turns into more performance for very complicated routines.

So right now, it is as fast as I know how to make it, and I spent a great deal of time making it fast, but if you can tell me how to make it faster without sacrificing functionality, I am of course all ears.

**Comment by damon-atkins** [comment]
FYI By default sshd (openssh) defaults to 10 connections which are in the process of authenticating (i.e. the login/password prompt or keys). To stop denial of service attacks.  I have seen batch seems trigger more than 10+ jobs almost at once, and any job after the 10th randomly fails.  (sshd_config:MaxStartups)  Might be worth adding this to the doco.

Big maybe, a  native python implementation, which would allow salt to stop scanning the text for Password: ( see #29422 ) 
http://www.paramiko.org/
AsyncSSH Py3 only https://www.reddit.com/comments/41zycz

**Comment by kt97679** [comment]
Thanks for explanation @thatch45 . Probably I was not clear in the description: I was targeting single machine and I see that salt-ssh did 6 connections to this single machine, so this is not about concurrency and multiple servers.

With all honesty I think that ideal configuration management tool should use single ssh connection for each machine it configures.

**Comment by thatch45** [comment]
Ok, salt-ssh needs python code on the target system when to run the configuration management system, so on that first run it is caching runtime information so that you don't have to make more connections later on. Also since I am more worried about how much data is being sent over the network than number of connections, that caching and checking is used to make sure that we only call the remote system the minimal number of times. So future state runs with salt-ssh will use fewer connections because we have cached grain data and the execution data used the call states.

As for doing configuration management in one ssh call, again, if you can figure out how to do it, securely, reliably and consistently, then I am all ears, but building a software architecture with an overly heavy focus on a single golden concept usually leads to a bad overall design. You need to balance multiple factors when making software, especially complicated software.

@damon-atkins yes, I evaluated paramiko and concluded that it introduced a great deal of complexity, and for the use case of salt-ssh is was actually slower than shelling out (mostly fell down in file transfers and parsing large output over the tty). 

Since this is just an argument about low level architecture and not a bug or feature request I am going to close this issue out
