### ISSUE TITLE
No indication of success/failure in publish

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt#33343]
I'm building a module that uses `publish.runner` to execute some code on the master and fetch the results. As far as I can tell from experimentation and code-diving, there is no way for me to determine if the call fails or succeeds, excepting if it times out. Even if the runner throws an exception, I just get a string representation of the exception back. If the `peer_run` setting is not correctly configured, I get empty string.

First, is this correct, or am I doing it wrong(tm)? If so, is it a hard problem to detecting this and give the caller some better feedback? Currently, between the extremely sparse documentation (try figuring out how to pass multiple arguments without tracing the source a while) and non-existent error reporting, it is very hard to use this feature. If changes would not require too much salt-internals wizardry, I could give a PR a shot.

**Comment by UtahDave** [comment]
I just did some testing since I hadn't used the peer run feature in quite a while. It looks like only the output of the runner execution is returned to the calling minion, so there's no metadata about the success for failure of the runner.

This feels like a feature that could use some attention and polish. It would be very much appreciated if you have any documentation improvements based on your experience. Improvements to the peer run system would also be very appreciated. We would need to try to make sure any changes are backwards compatible, if at all possible. I'd like to see your ideas in code form.

Do you already have specific changes you'd like to see?
