### ISSUE TITLE
salt-cloud saltify should install salt on cloud machines, even if they are visible from other provider

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#33351]
### Description of Issue/Question
If you have legacy machines in a cloud provider, and have configured salt-cloud to connect with and work with that provider, and then you attempt to use saltify to salt your legacy machines... saltify gives up with an "Already running." error message.

### Setup
In digital ocean, manually create a droplet.
Configure salt-cloud digital_ocean provider. Confirm with salt-cloud --query.
Then configure saltify to install salt on that machine.

### Steps to Reproduce Issue
Run salt-cloud -m saltify-my-legacy-cloud-machine and see that all your legacy machines are refused with "Already running." error messages.

### Workaround
Rename your cloud.providers.d/digital_ocean.conf to .backup, saltify, undo.

### Versions Report
```bash
ahammond@salt:~ $ salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.2.1
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.3.8
        libgit2: Not Installed
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: 0.2.4

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.3.1.el6.x86_64
         system: CentOS 6.7 Final
```

**Comment by Ch3LL** [comment]
@ahammond I am able to reproduce this easily, and of course this error is showing up because salt-cloud first checks to see if the VM already exists. And when you attempt to run it with `-p` instead of a map file you will get this error: `ch3ll-ub already exists under digitalocean:digital_ocean`. 

@techhat : do you think the above could be possible? To setup a bypass for saltify to skip this check and install salt on the VM?

**Comment by techhat** [comment]
The problem here is that the name exists in a way that Salt Cloud can see it (via `--query`). What Salt Cloud is expecting to do is grab ahold of a machine that exists but isn't connected to Salt, and then connect it to Salt.

One workaround is to do something to the name that makes it invisible to Salt Cloud during the `saltify` process. Another is to try out the `manage.bootstrap` runner. The version in the `dev` branch might just be a better solution (and if it's not, please let me know where it failed you).

**Comment by techhat** [comment]
To be clear, I would consider `manage.bootstrap` to be the way to do this going forward. We need to deprecate the `saltify` driver.

**Comment by ahammond** [comment]
I'll take a look at the manage.bootstrap runner. Thanks! :)

**Comment by DanyC97** [comment]
@techhat i'm having exactly the same issue, how can i use `manage.bootstrap` from salt-cloud in the same way i use it with `saltfiy` driver ?

**Comment by ahammond** [comment]
Dani, is the workaround I documented in the initial bug report not working
for you?

**Comment by DanyC97** [comment]
@ahammond  opps, i missed that!! It works including, much thanks!!!
