### ISSUE TITLE
Where's the changelog and tag for 2015.8.10 ?

### ISSUE THREAD

**Issue by hgfischer** [saltstack/salt#33392]
I just found out that there are new deb packages for SaltStack in the official repo and I couldn't find changelog, and neither *tags* in the git repo!?

**Comment by PKiman** [comment]
I am wondering why the package from the official repository is 2015.8.10
https://repo.saltstack.com/yum/redhat/6/x86_64/latest/
While there is no release found in 
https://github.com/saltstack/salt/releases
nor 
https://docs.saltstack.com/en/latest/topics/releases/
Shouldn't it be vice versa? Releasing something without changelog is pretty confusing.

**Comment by babilen** [comment]
Releases on GH correspond to tags.

**Comment by babilen** [comment]
I believe that 2015.8.10 does not actually contain the changes it should have contained.

See the following for details:

* https://github.com/saltstack/salt/pull/33381
* https://github.com/saltstack/salt/pull/33383#issuecomment-220577467

and lets wait for people at SaltStack wake up.

**Comment by Ch3LL** [comment]
Shortly after the release of 2015.8.9, we were made aware of some upstream changes to pip's API which broke Salt's support for pip.

Since this is a potentially serious issue for those who use pip in conjunction with Salt, we elected to immediately patch and release a 2015.8.10 version of Salt.

The release notes for 2015.8.10 can be found here:
https://docs.saltstack.com/en/latest/topics/releases/2015.8.10.html

Does that help to clarify any confusion?
