### ISSUE TITLE
apache_module.enable failes when using salt-call 2016.3.0 (Boron)

### ISSUE THREAD

**Issue by moshe0076** [saltstack/salt#33571]
### Description of Issue/Question
apache_module.enable failes when using salt-call 2016.3.0 (Boron)
Works with the same setup but with salt-call 2015.8.10 (Beryllium)
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

ubuntu server 14.04 

```
Enable proxy module:
  apache_module.enable:
      - name: proxy

Enable rewrite module:
  apache_module.enable:
      - name: rewrite
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt-call on minion
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
ubuntu@ip-10-0-11-229:~$ salt --versions-report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.23.4
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.3
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Ubuntu 14.04 trusty
 ```

**Comment by Ch3LL** [comment]
@moshe0076 are you getting an error when it fails and if so would you mind posting the error?

**Comment by abednarik** [comment]
Hi

 I can reproduce this just switching between 2015.8 and 2016.3. This issue is related to [this](https://github.com/saltstack/salt/commit/f3a2b27671459a2a323407ffea4625905e1b7f89) commit.. Here enable and disable was changed to enabled and disabled, which I think is a good change in order to follow salt standards, but in this case documentation was not updated. Have a look [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.apache_module.html).
Also and most important, this changes is not backward compatibility. I don't think salt do this kind of behavior, should be a proper deprecation warning to advise user to 
 I will try to do a PR to update docs and make a proper deprecated message in order to fix this..

**Comment by abednarik** [comment]
[PR](https://github.com/saltstack/salt/pull/33613)

**Comment by rallytime** [comment]
Thank you for the fix @abednarik. I have also back-ported this fix to the 2016.3 branch in #33638.

**Comment by rallytime** [comment]
@moshe0076 A deprecation warning and fix has been submitted in the PR mentioned above so that using both `enabled` and `enable` will work until Salt Nitrogen. The work-around here is to update your states to use the new `apache_module.enabled` function name instead of `enable`, in case that wasn't clear. Apologies for the breakage.

**Comment by moshe0076** [comment]
Hi,

Sorry for the late response.
It works! 
Thanks all for the help!

Moshe
