### ISSUE TITLE
saltutil.sync_all does not sync custom pillar modules to masterless minions

### ISSUE THREAD

**Issue by ketzacoatl** [saltstack/salt#33645]
### Description of Question

In attempting to use the `saltutil.sync_all` module and the `extension_modules` configuration option, and having read various docs ([1], [2] in particular), I am unclear about the semantics and what I should expect from these when used in combination. Herein, I have a couple of questions:

1) If `extension_modules` is _not_ in use, where does `saltutil.sync_all` sync modules too?
2) If using `extension_modules`, when  should I expect `saltutil.sync_all` to remove/delete files that are not in my `file_roots` paths? (`_states`, `_modules`, etc). EG, if I manually (not with salt) put modules into the `extension_modules` path (`/srv/salt-ext` in my case), when will `saltutil.sync_all` remove those modules of mine?
3) If you wish to include a custom pillar (`ext_pillar`), can I expect `saltutil.sync_all` to sync that pillar module from `_pillar` in my `file_roots`? In the past I copied these custom pillar modules into `/srv/salt-ext/` manually.

### Versions Report

I have this setup in masterless mode, primarily:

```
# salt-call --versions-report
           Salt: 2015.5.10
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.5.3
```

### Links

[1] https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_all
[2] https://docs.saltstack.com/en/latest/ref/states/writing.html#using-custom-state-modules

**Comment by Ch3LL** [comment]
By default extension_modules is in CACHE_DIR/minion/extmods. To be exact on my box they are located here: `/var/cache/salt/minion/extmods/modules`

If you remove a file from your file roots in _modules when running `saltutil.sync_all` it should remove it from extension_modules. 

I just did a quick test and it looks like if you are manually adding files to your extension_modules and not your file_roots it will remove the file because its not in the file_roots

To answer your last question there is some valuable information in the docs:

>Salt expects to find your ext_pillar module in the same location where it looks for other python modules. If the extension_modules option in your Salt master configuration is set, Salt will look for a pillar directory under there and load all the modules it finds. Otherwise, it will look in your Python site-packages salt/pillar directory.

So it does not look like sync_all will add the pillar directory there but would have to be done manually. There is this feature request here: #13842 to add the feature to do this exact thing.

Does that help answer all your questions?

**Comment by ketzacoatl** [comment]
Hi @Ch3LL, thank you for your time and attention in helping me out.

There are a few small details I would appreciate confirmation on:
* If I understand correctly, setting `extension_modules` to `/srv/salt-ext`, overrides the default of `/var/cache/salt/minion/extmods/modules`, and that is where `saltutil.sync_all` will put those files that it syncs. Yes?
* Will `saltutil.sync_all` actually _create_ that `extension_modules` path if it does not exist? I see log entries that suggest that as expected behavior, but I don't see it functional unless I ensure that base path exists before running `sync_all`.

**Comment by terminalmage** [comment]
You should never need to set ``extension_modules`` explicitly, nor manage it manually. It is a location within the minion cache where custom types are synced from the salt fileserver via the [saltutil execution module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html).

The ``saltutil.sync_all`` function syncs all custom types to subdirectories under the minion's ``extension_modules`` directory. It is equivalent to running all of the other ``saltutil.sync_*`` functions. If there is a custom module which was synced to the minion, then removed from ``salt://_modules`` (or ``salt://_grains``, etc.), then it will be removed from the minion's ``external_modules`` on the next ``saltutil.sync_all``.

Can you please provide more information on what you're trying to do, and what it is that doesn't appear to work? I'm having a hard time understanding what you're trying to ask. There really isn't a need to manually set ``extension_modules`` to get custom modules to work.

**Comment by terminalmage** [comment]
With regard to pillar, since pillar data is compiled on the master, there is no support for syncing custom pillar modules to minions. As noted [here](https://github.com/saltstack/salt/issues/13842#issuecomment-224122502), the saltutil runner can be used to sync custom pillar modules to the master. It is new to 2016.3.0.

Prior to 2016.3.0, custom modules had to be manually placed on the master, as there was no runner module to do so. Perhaps this is the source of your confusion.

**Comment by ketzacoatl** [comment]
Hi @terminalmage, thanks for the details there. I am running masterless, with `salt-call --local`, but even so, it seems the `saltutil.sync_*` functions do not cover pillar modules - that is why I was using `extension_modules` to begin with. I could skip `extension_modules` if `saltutil.sync_all` supported syncing pillar modules, though I can also continue putting those modules in place manually (it looks like `sync_all` will leave a pillar module, while it will remove the other states/runners/modules that are not present in `file_roots`).

**Comment by ketzacoatl** [comment]
> In the meantime, you can place your custom pillar modules into /var/cache/salt/minion/extmods/pillar manually.

Right, this is what I've been doing (along with setting `extension_modules` to something easier to remember, `/srv/salt-ext`), and it seems the pillar module sync is the one bit missing (from `saltutil.sync_*`) that could be improved upon. Thanks for helping to get this scoped out properly!

**Comment by terminalmage** [comment]
@ketzacoatl That's a good idea, I changed the title of the issue to make it match what we've determined the problem to be.

**Comment by terminalmage** [comment]
@ketzacoatl This is fixed in https://github.com/saltstack/salt/pull/33833. A new ``saltutil.sync_pillar`` function has been added, and ``saltutil.sync_all`` will use this function to include pillar data when invoked on a masterless minion.

The fix will be in the 2015.8.11 and 2016.3.2 releases of Salt. If we do a 2015.5.12, it will also be included in that release.

**Comment by ketzacoatl** [comment]
\o/

That looks great! I will test it out, as it looks like I can drop it into `_modules` and run it on 2015.5.x.

**Comment by ketzacoatl** [comment]
@terminalmage, tests went well here:

```
# salt-call --local saltutil.sync_all
...
[INFO    ] Copying u'/var/cache/salt/minion/files/base/_pillar/consul_pillar.py' to u'/srv/salt-ext/pillar/consul_pillar.py'
local:
    ----------
    beacons:
    grains:
    modules:
    output:
    pillar:
        - pillar.consul_pillar
    renderers:
    returners:
    sdb:
    states:
    utils:
# ls -alh /srv/salt-ext/pillar/                                                                
total 32K
drwx------ 2 root root 4.0K Jun  7 20:08 .
drwxr-x--- 5 root root 4.0K Jun  7 20:08 ..
-rw------- 1 root root 8.5K Jun  7 20:08 consul_pillar.py
-rw------- 1 root root 8.9K Jun  7 20:08 consul_pillar.pyc
```

**Comment by terminalmage** [comment]
@ketzacoatl Thanks for taking the time to test, I really appreciate a second set of eyes on this.
