### ISSUE TITLE
Document That Local Files Can Be Used as a Source for File States

### ISSUE THREAD

**Issue by hjc** [saltstack/salt#33694]
### Description of Issue/Question

Now that #29057 has been merged, all the file states support local files as valid paths for the
`source` argument. That's awesome! Thanks for that!

However... the documentation on the site does not mention this. Instead it only says:

> A single source file to append. This source file can be hosted on either the salt master server, or on an HTTP or FTP server.

And local files aren't mentioned anywhere!

I think it would be super helpful if the docs could be updated to indicate that this is supported
and possibly give an example of using it. For me to find that this was supported, I had to Google
until I found a Closed Issue, read the whole thing until I got to the PR that fixed it, and then test
from there.
### Setup

N/A.
### Steps to Reproduce Issue

N/A.
### Versions Report

N/A.

Thanks as always!

**Comment by Ch3LL** [comment]
@hjc1710 looks like there was some documentation added in the PR on the file state documentation page:

>Source list functionality only supports local files and remote files hosted on the salt master server or retrievable via HTTP, HTTPS, or FTP.

But I think adding some more docs is a great idea. Particularly I think it would be great to add an example. Thanks!

**Comment by hjc1710** [comment]
Oh!!! You're totally right! There was some documentation added for the [`file.managed` state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed)!

However, it's only in the `file.managed` state's section, when the change was definitely made to the `file` module as a whole, which means it should apply to every other `file` state.

Definitely agreed that mentioning this for every `file` state and adding some examples of usage is a great idea. Especially since `file.managed` is not the first state the docs show (in my example, I read the docs for `file.append`, which do not reference using local files).

Thanks!
