### ISSUE TITLE
Creating a master with salt-cloud doesn't install salt-cloud on the new master

### ISSUE THREAD

**Issue by signalsensefred** [saltstack/salt#33768]
### Description of Issue/Question

When I add the `make_master: True` line to a cloud config and run `salt-cloud` to create an instance from it (using Ubuntu 14.04 on AWS, but in the code I can't find anything that seems specific to that), that instance, though it has salt-master, does not have salt-cloud.
### Versions Report

```
Salt Version:
           Salt: 2016.3.0-662-gd90448a

Dependency Versions:
           cffi: 1.4.2
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-36-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@signalsensefred it appears this is expected behavior. In the code `make_master` adds the following to the bootstrap arguments: 

```
                     if make_master is True:                                                                
                         deploy_command += ' -M'                        
```

`-M` with the bootstrap script installs the master not salt-cloud. I glanced at the bootstrap script and i'm not seeing an option to install salt-cloud so this would need to be a post-installation task. Also am not seeing an option within the code for salt-cloud to set it up this way. We could aproach this as a feature request if that works for you? Feature request to add the ability to install salt-cloud using salt-cloud.

**Comment by signalsensefred** [comment]
Doing it as a new feature sounds good to me.
