### ISSUE TITLE
Document and test configs in saltrc

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#33811]
### Description of Issue/Question

Document and test [placing configs](https://github.com/saltstack/salt/blob/v2015.8.10/salt/config.py#L3058-L3064) in `${XDG_DIR}/saltrc` and `~/.saltrc`.

**Comment by jacobhammons** [comment]
Similar issue: https://github.com/saltstack/salt/issues/4542

**Comment by dafyddj** [comment]
Still needs documenting.

**Comment by lowercase00** [comment]
Hi, I've been looking for a simpler to configure Salt (instead of placing an alternative configuration on `/etc/salt/master.d/xxx.conf`. If I understood correctly, Salt will automatically look for a `.saltrc` configuration file in the home directory, or to the path set with `SALT_CLIENT_CONFIG`.
Does this has the same format / key options as `master` default configuration file?
I would be happy to contribute with this, couldn't find much information online.
