### ISSUE TITLE
Rewrite reg.py to use windows API

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#33865]
### Description of Issue/Question

I seem to be running in to this. http://stackoverflow.com/a/33605646

I am unable to pull Chinese Characters out of the registry. Need to look at reworking reg.py to use the windows API directly instead of using _winreg.

- [x] Need to test if this is still an issue with Python 3 (3/13/2017)

**Comment by damon-atkins** [comment]
The solution is to move to Python 3 on windows were the Windows Python API is full Unicode support.

Python 2 does not support Unicode, even thought API it calls does.

I suspect with PY2 in order to work with Chinese Chars I think you would need to change the OS over to Chinese  Language, which would make it hard to use unless you can read Chinese.

**Comment by cachedout** [comment]
@twangboy Given that we'll bundle Py3.5 in Nitrogen is this still an issue? I'm moving it out of 'In Progress' for now.

**Comment by cachedout** [comment]
Need to see if going to Py3 fixes this.

**Comment by damon-atkins** [comment]
If PY3 Windows can talk to a PY2 Linux Master?    Salt could release a beta PY3  with a PY2 version for windows.

**Comment by twangboy** [comment]
It seems that Py3 supports unicode quite nicely.
