### ISSUE TITLE
saltutil.wheel minions.connected does not return anything with remote minions

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#33879]
### Description of Issue/Question
On the head of 2016.3 when testing the fix for issue #32446 there is no return for remote minions. I am expecting the following error: `ERROR: This command can only be executed on a minion that is located on the master.`

### Setup
1. 2 minioins connected to a master. One of them local and one of them remote

### Steps to Reproduce Issue
1. run the following: `salt '*' saltutil.wheel minions.connected`
2. And you will see that the remote minion does not return anything:

```
root@ip-10-95-162-59:~/salt# salt '*' saltutil.wheel minions.connected -lwarning
masterminion:
    - masterminion
    - remoteminion
remoteminion:
```

### Versions Report

```
root@ip-10-95-162-59:~/salt# salt --versions-report
Salt Version:
           Salt: 2016.3.0-47-gbe20ce1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-36-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by rallytime** [comment]
After reviewing the changes in this code from 2015.8 to 2016.3, the remote minion no longer throws a SaltInvocationError when attempting to run wheel commands as it did in 2015.8. Instead of throwing the error, the remote minion returns as "empty".

For example, a `saltutil.wheel minions.connected` command returns an empty list. While this is a correct return, and is expected behavior for a remote minion - it wouldn't have any minions connected to it, it is not necessarily obvious of why this return is empty. 

@Ch3LL and I spoke offline about this and agreed that the solution to this bug is better documentation, as submitted in #34214.
