### ISSUE TITLE
SUSE - no RPM existing on Online Repos

### ISSUE THREAD

**Issue by bigg01** [saltstack/salt#33930]
### Description of Issue/Question

We are syncing your repos and we found out that the new 2016 release is not avaible on the REPO.

https://repo.saltstack.com/opensuse/SLE_11_SP4/x86_64/

http://repo.saltstack.com/opensuse/SLE_12_SP1/x86_64/

cheers

**Comment by Ch3LL** [comment]
@bigg01 We do not actually create or maintain those packages we are mirroring the main suse saltstack repo.

Let me ask around to find out who is now in charge of creating those packages to see what the status is on 2016.3.0 packages for sles.

**Comment by rallytime** [comment]
If the packages are available from Suse, then we probably just need to update our repo.saltstack.com mirrors. 

ping @UtahDave

**Comment by aboe76** [comment]
@isbm do you have any indication?

**Comment by isbm** [comment]
All,
there are only two _supported and tested_ repos we (SUSE)  maintain:

1. [Latest supported public package](https://build.opensuse.org/package/show/systemsmanagement:saltstack:testing/salt) — this one is going to be upgraded to 2016.3 at some point. We will also will rename "testing" to something else.
2. [Latest used in enterprise products package](https://build.opensuse.org/package/show/systemsmanagement:saltstack:products/salt) — this one isn't changing very fast, but we are planning it pretty frequent for the products anyway.

So at some point, 2016.3 will be at No. 1 (I don't know when, because it requires quite a work to setup nearly 20 instances of testing for various platforms/flawours ). Please try to ignore everything else (or do not ask why it doesn't work).

Therefore please get them only from our build service (or mirror them and make sure they are in sync). :wink:
