### ISSUE TITLE
grains.filter_by goes via different code paths under salt-ssh depending on invocation

### ISSUE THREAD

**Issue by xlotlu** [saltstack/salt#33966]
### Description of Issue/Question
Using `salt['grains.filter_by']()` over salt-ssh goes via the wrapper code in `/client/ssh/wrapper/grains.py`. However, using `salt['grains'].filter_by()` or `salt.grains.filter_by()` does not, with no apparent loss of functionality.

I presume this is incorrect behaviour, and it's indicative that the duplicate wrapper code may not even be needed.

See #33911 for background.

### Setup
example1.sls
```
{% set test = salt['grains.filter_by']({}) %}
/tmp/example1:
  file.managed
```
example2.sls
```
{% set test = salt['grains'].filter_by({}) %}
/tmp/example2:
  file.managed
```
### Steps to Reproduce Issue
Edit `def filter_by` under the wrapper to raise an exception:
```
$ salt-ssh '*' state.apply example1
```
fails as expected with `Rendering SLS 'base:example1' failed: Jinja error: ...`, while
```
$ salt-ssh '*' state.apply example2
```
results in `file /tmp/example2 created`.

### Versions Report
Salt: 2016.3.0

**Comment by Ch3LL** [comment]
@xlotlu thanks for the additional investigation work into this issue. Unfortunately I am able to get the both of your examples to work, and do not see a jinja exception. Although I think this test case shows the same thing you are trying to show:

example1(this works):

```
{% set test = salt['grains'].filter_by({
    'default': {'foo': 'bar'},
}, base='default') %}

test-it:
  file.managed:
    - name: /tmp/{{ test.foo }}
```

example2(this does not work, due to the issue you are reporting that its going through a diff wrapper):

```
{% set test = salt['grains'].filter_by({
    'default': {'foo': 'bar'},
}, base='default') %}

test-it:
  file.managed:
    - name: /tmp/{{ test.foo }}
```

The above example I get the default error you reported in the previous issue which shows that its going via a different wrapper. 

Unfortunately my knowledge stops there and cannot answer your question: `I presume this is incorrect behaviour, and it's indicative that the duplicate wrapper code may not even be needed.` ping @cachedout do you have any insight into the need for both this code?

**Comment by thatch45** [comment]
We do need both invocations of the code, it has to do with a quirk in how the loader runs that we really only run into in salt-ssh. So I am going to close this out, thanks!
