### ISSUE TITLE
Make target argument of salt.states.file.symlink optional

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#34058]
I want to ensure that a symlink is owned by the correct user/group _without_ actually caring where it points to. Currently, that's not possible.

I _think_ it'd be possible to just add an `if target and ...` to [this if clause](https://github.com/saltstack/salt/blob/cce6bfaec86996466969d9c162537bb2688abec7/salt/states/file.py#L925) and get it working.

**Comment by Ch3LL** [comment]
@anlutro I think this is a great idea and definitely doable ! I'll go ahead and approve it as a feature request. Thanks!

**Comment by derekmaciel** [comment]
@Ch3LL What about if the symlink doesn't exist? Without the target it will not be able to create it. In my opinion, file.symlink should always be able to create the symlink if it does not exist.

salt.states.file.exists is currently used to ensure a file merely exists without attempting to create it if it does not. What about extending it from:

> salt.states.file.exists(name)
> Verify that the named file or directory is present or exists. Ensures pre-requisites outside of Salt's purview (e.g., keytabs, private keys, etc.) have been previously satisfied before deployment.
> 
> name
>     Absolute path which must exist

to:

> salt.states.file.exists(name, user=None, group=None, force_symlink=False)
> Verify that the named file or directory is present or exists. Ensures pre-requisites outside of Salt's purview (e.g., keytabs, private keys, etc.) have been previously satisfied before deployment.
> 
> name
>     Absolute path which must exist
> user
>     If this setting is applied, the state will fail if the file is not owned by this user.
> group
>      If this setting is applied, the state will fail if the file is not owned by this group.
> force_symlink
>     If true, the state will fail if the file is not a valid symlink

@anlutro Note the restriction in force_symlink for the symlink to not be broken. This is because salt.states.file.exists uses Python's `os.path.exists()`, which allows symlinks but not broken symlinks. If this is undesirable let me know, we might be able to add a `allow_broken_symlink` option (or something with a better name).

**Comment by lorengordon** [comment]
Can file.managed be used to set the user/group/mode on the symlink? We use it for that purpose with regular files all the time.

**Comment by derekmaciel** [comment]
If I understand the code correctly, file.managed would set the permissions to the linked file, not to the symlink.

**Comment by derekmaciel** [comment]
Just wrote a quick state to test this and I confirmed that yes, it sets the permissions on the linked file, not the symlink itself. This is fine for most systems but on some systems the symlink's permissions are important, like on OS X.
