### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#34063]
[Actually I did not find any feature request entry for salt]

Hello,

users state are fine to check a user is present or absent

but what if you want to remove all users not present in a predefined list ??

I could use a cmd to retreive all users on the minion but there is no way (that I know) to use this command output strings list as a jinja/python list and then to generate the appropriate absent states

cut -d: -f1 /etc/passwd

root
daemon
bin
sys
sync
games
man
lp
mail
news
uucp
proxy
www-data
backup
list
...

In case of suspission of a hacker having installed a backdoor, that would be neat to apply a salt state so that all extra users would be removed

any suggestion ?

tahnks

**Comment by Ch3LL** [comment]
If you really do want to take this approach you could add the users to pillar data and run something like the following and instead of cmd.run user.absent:

```
{% set user_list = salt['cmd.run']('cut -d: -f1 /etc/passwd').split() %}
{% set current_users = pillar.get('users', '') %}
```

and then loop through the users and compare it to the list, but this is very hackish and I believe this to be very dangerous because you could remove a user you did not intend. I also am not inclined to add this to the state module for the same reason.

A different approach you could take since this for security reasons you could look at beacons and use the inotify beacon to watch for any new users in /home/ or /etc/passwd and then notify when a user has been added. Does this approach work for your situation?

**Comment by phil123456** [comment]
I dont know, I need to figure new open ports and new created users - last time a hacker installed a bitcoind generator on our machine. not sure if salt is the most appropriate, but as long as all allowed users are in a predefined list, it should work fine

thanks, I'll give it a try

**Comment by cachedout** [comment]
Bear in mind, of course, that if your machine is compromised to the point to the point that new users have been added, it's not safe to rely on something like a Salt minion as a remediation tool since it can no longer be trusted at that point either. Just something to remember. :]

**Comment by Ch3LL** [comment]
@phil123456 are you okay to close this issue?

**Comment by phil123456** [comment]
the whole point is precisely to figure out if the minion is still trustable

yes you can close this one :-)
