### ISSUE TITLE
Define minimum package version

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#3415]
It would be great if pkg.install could be given a version spec such as ">= 0.7.0", causing it to install not a specific version, but any version of a package that satisfies the condition.

**Comment by dharmab** [comment]
This would be very useful to manage CVEs in our environment by being able to specify minimum versions of packages.

**Comment by mikeadamz** [comment]
I was just looking for this.  Did it ever happen? I'm using the yum provider.

**Comment by disaster123** [comment]
Looking at it too using apt. Is it possible?

**Comment by ekle** [comment]
it would be cool if there were also support for a max-version

**Comment by thatch45** [comment]
@terminalmage this has been added to Salt right? I thought we got this in years ago

**Comment by terminalmage** [comment]
This was added a long time ago, but it is not universally supported. It is only supported for package managers which support comparison operators.

From the [docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed):

```
Additionally, ebuild, pacman and zypper support the <, <=, >=, and > operators for more control over what versions will be installed. For example:

mypkgs:
  pkg.installed:
    - pkgs:
      - foo
      - bar: '>=1.2.3-4'
      - baz

NOTE: When using comparison operators, the expression must be enclosed in quotes to avoid a YAML render error.
```

In order to support this more universally, we would need to be able to get a list of the available version(s) of a given package from the remote repository (e.g. the `pkg.list_repo_pkgs` function, which is currently only implemented for yum/dnf, apt, and pacman), and then perform some logic to determine which version best matches the desired comparison expression. We would then need to have a means to target a specific version in the command used to install the package, and this is something that is also not universally supported among package managers.

**Comment by thatch45** [comment]
ok, so it only works for pacman, zypper and ebuild, but not apt and yum/dnf?

**Comment by terminalmage** [comment]
Correct.

It could potentially be added for apt and yum/dnf since we already have a ``list_repo_pkgs`` function for both. We would need our own logic to decide which version to install though, since neither apt nor yum/dnf support passing comparison operators when installing. The logic should already be there to check if a version is installed which matches the expression (i.e. ``>=4.5.6-7.el7``), the issue is that the state will at that time just pass through the version expression (``>=4.5.6-7.el7``) to ``pkg.install``, which since it is not supported, will fail to install. So the ``pkg.installed`` state needs to have logic to resolve which version should be targeted, and then the state needs to also rewrite the values passed to the state so that instead of passing ``>=4.5.6-7.el7`` as the version when we invoke ``pkg.install``, we instead pass the resolved version (e.g. ``4.6.0-1.el7``).

**Comment by thatch45** [comment]
ok, lets try to get this work on the roadmap for an upcoming release

**Comment by terminalmage** [comment]
OK. Now that I think of it, the best place for the logic to resolve the comparison expression is in ``pkg.install`` itself. That way we can just pass through the argument from the SLS file, and the version comparsion operator will still work if ``pkg.install`` is invoked on the CLI (i.e. outside of the ``pkg.install`` state).

**Comment by terminalmage** [comment]
I got this working for yum/dnf this afternoon, getting it working for apt should be easy. I should have this done later this week.

**Comment by terminalmage** [comment]
Implemented for yum/dnf and apt in https://github.com/saltstack/salt/pull/41748.
