### ISSUE TITLE
salt-call default loglevel regression

### ISSUE THREAD

**Issue by ryanwalder** [saltstack/salt#34162]
### Description of Issue/Question

`salt-call` [docs](https://docs.saltstack.com/en/latest/ref/cli/salt-call.html#logging-options) state that the defaut loglevel should be "info" however in 2016.3.1 it does not show info output without forcing `-l info` or `--log-level info` on the command line.

I'm sure it's not just me who uses salt-call for developing salt states, info level output here is essential.

### Steps to Reproduce Issue
Run `salt-call state.highstate` no info log output will show, old behaviour seen with `salt-call state.highstate -l info`

### Versions Report
```
[vagrant@yum01 ~]$ salt-call --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by rallytime** [comment]
Hi @ryanwalder  - the default log-level should actually be `warning`, instead of `info` which was mistakenly changed to `info` as discussed in #33818 and #33821. I think this is also discrepancy in the documentation, and we need to fix that. The doc you pointed to above says `info` while the sample minion config file that is provided says `warning`. 

You can set the log level back to info in your minion config file with `log_level: info` so you don't have to specifically call it with `-l info` from the CLI.

**Comment by ryanwalder** [comment]
Odd, I'm was sure it was `info` since 0.17 or earlier if running `salt-call`, not the end of the world, will just set it to info in my configs!

**Comment by rallytime** [comment]
Thanks @ryanwalder!
