### ISSUE TITLE
Using the runas command do not apply the limits of the user

### ISSUE THREAD

**Issue by DavidCantero** [saltstack/salt#34163]
When we use the runas command to restart a process it restart with the limits of the user that is running the salt-minion process. In the system we have limits for the user of jboss at 60000 and sometimes it restarts with 1000 that are the limits of the salt-minion user, we have temporary fix this by running the salt-minion with root privileges, but when we restart jboss now it recieves the limits of root that are 500.000.

Is this issue a Bug? Is solved in a newer version?

Do someone know how to fix this strange issue???

Best Regards
### Versions Report

Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.09
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Oct 12 2012, 14:23:48)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.4 Santiago
        machine: x86_64
        release: 2.6.32-358.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.4 Santiago

**Comment by damon-atkins** [comment]
You need to provide an example...

runas would only work if you are running the minion as root, otherwise it cannot change to a different user.   However in saying this runas would need to call pam functions in order for limits.conf to be read. I assume salt is calling setuid, which works in 95% of most cases.

You would be better having salt run the startup script which is called at boot time, which I would assume calls su and program name.      Or use run.cmd with su

**Comment by Ch3LL** [comment]
@damon-atkins thanks for the input

@DavidCantero can you respond to @damon-atkins request for an example and suggestions? Thanks

**Comment by DavidCantero** [comment]
Hi,

I have atached 2 files of logs of a execution in Rundeck using saltstack to restart the jboss processes.

Regards

[398564.rdlog.txt](https://github.com/saltstack/salt/files/327204/398564.rdlog.txt)
[398564.state.json.txt](https://github.com/saltstack/salt/files/327203/398564.state.json.txt)

**Comment by damon-atkins** [comment]
So if jboss_check_start.sh does not contain the command su, and you do not have a startup script for the systems which starts jboss and it contains an su 

Then you will need to use
salt abcserver cmd.run '/usr/bin/su targetuser jboss.sh restart all'
OR
salt abcserver cmd.run '/usr/bin/su - targetuser jboss.sh restart all'

su proccess the pam or runuser will also process pam
/etc/pam.d/fingerprint-auth:session     required      pam_limits.so
/etc/pam.d/password-auth:session     required      pam_limits.so
/etc/pam.d/runuser:session              required        pam_limits.so
/etc/pam.d/smartcard-auth:session     required      pam_limits.so
/etc/pam.d/sudo:session    required     pam_limits.so
/etc/pam.d/system-auth:session     required      pam_limits.so

Create test shell script and run "ulimit -a" within.

I would normally call the start up script for the systems
salt abcserver cmd.run 'service jboss  restart'   
But you may not have a system startup script

**Comment by WraithCadmus** [comment]
Hello, I'll try to provide some examples here.

I'm running salt 2016.3.2 master and 2016.3.3 minion on CentOS 7. My example is I'm trying to do an Oracle silent install. Oracle requires a very high hard limit for the number of open file descriptors, so that's set in /etc/security/limits.d/ somewhere and works if you get a login shell as the oracle user (directly or doing a su - oracle). And the system-wide is the usual 4096

```
[oracle@server ~]$ ulimit -Hn
65536

[root@devorainsl01 ~]# ulimit -Hn
4096
```

The minion gets 8192, set in /usr/lib/systemd/system/salt-minion.service

```
[Service]
Type=notify
LimitNOFILE=8192
ExecStart=/usr/bin/salt-minion
```

Here's a cut-down version of my salt statement to install the db

```
oracle-silent-install:
  cmd.run:
    - name: /home/oracle/db_install.sh
    - runas: oracle
    - creates: /u01/app/oracle/product
    - cwd: /home/oracle
    - require:
      - file: oracle-install-script
      - archive: oracle-database-installer
```

And here's the error spat out of the Oracle installer

```
TaskShellLimits:Hard Limit: maximum open file descriptors[ShellLimits_HARD_maximum open file descriptors]:TASK_SUMMARY:FAILED:CRITICAL:VERIFICATION_FAILED
          ERRORMSG(devorainsl01): PRVF-4354 : Proper hard limit for resource "maximum open file descriptors" not found on node "devorainsl01" [Expected = "65536" ; Found = "8192"]
```

So what we're seeing here is that it's still using the limits of the salt-minion process, the ways around I could think would be an option to make a login shell in cmd.run, or I could have a wrapper that drops to the oracle user in a login shell but that feels like a kludge and the runas option makes things like this super clear. I'm reasonably new to salt and don't have enough knowledge of the internals to make confident suggestions.

**Comment by ForaLake** [comment]
Hello, i'm using salt 2016.3.3 on CentOS 6.7 and meeting the same situation as @WraithCadmus .

I just user salt to restart my service. But when i use `salt minion cmd.run 'xxx.sh restart' runas=nonroot` , user 'nonroot' inherits the ulimit info of user 'root'.

```
[xxxx@xxxx /root]$ ulimit -n  
1000
[xxxx@xxxx /nonroot]$ ulimit -n  
5555
```
In this example, my service has the limitation of 1000 after restart.

Is there any easy solution to this?

**Comment by damon-atkins** [comment]
@WraithCadmus  su, login, etc uses pam

Salt just changes the process uid/gid without calling pam.   You are better off having salt run `su user -c 
 your_install_script`.

Also `man pam_limits`

**Comment by rickh563** [comment]
ZD-1709

**Comment by damon-atkins** [comment]
The solution is to use `su` otherwise salt needs to implement this across many platforms.

@ForaLake use `su` instead of salts `runas`

**Comment by deanchina** [comment]
@damon-atkins  
how to use su  in  salt.utils.timed_subprocess.TimedProc()    this function??
