### ISSUE TITLE
What modules should be required for running unit tests?

### ISSUE THREAD

**Issue by eradman** [saltstack/salt#34276]
In addition to `pip install -r requirements/dev_python27.txt` I had to install the following to get all unit tests to pass on Ubuntu 15:

    pyinotify
    python-dateutil
    apache-libcloud

Should these added to a file file called `requirements/dev_linux.txt`?

Many more skip test warnings are eliminated if I install

    jsonschema
    urllib3

Do these belong in `requirements/opt.txt`?

**Comment by jtand** [comment]
@eradman When you did you need pyinotify, python-dateutil, apache-libcloud to simply run the unit tests or were there just failures due to them not installed? We may need to gate the tests better if they are failing without those 3 additional packages. 

The `dev_python2*.txt` should get the basic dependencies to run the test suite. A lot of tests are gated so they won't run if their deps are not installed. We want to keep the requirements file to a minimum. 

However, we have the [salt-jenkins](https://github.com/saltstack/salt-jenkins) repo that has the dependencies to eliminate the rest of the skipIfs and allow all the tests to run. These are the states we use in our jenkins setup, so there are some extra steps besides just installing packages. For example, it create some extra swap space and create /testing/ and put a checkout of salt in to /testing/. This is where our tests run on jenkins. 

I am working on a refactor of these states which will separate out the jenkins setup steps (creating /testing/ and swap space) and the package installs. 

I hope that makes sense. Let me know if you want more clarification.
