### ISSUE TITLE
No error Reporting for pkg.install 

### ISSUE THREAD

**Issue by dgarstang** [saltstack/salt#3433]
With salt version 0.12, comit id g671374a, (both client and server), running the following on the master:
salt stageapi01.us1.foo.com pkg.install name=bci-static version=9

yields the following output on the server:
stageapi01.us1.foo.com:

The version number supplied, '9' was intentionally wrong. That package does not exist to the client. The client logs an error in /var/log/salt/minion indicating as such (which is good). However, the servers output does not contain any of this error output, and there was nothing to indicate (not even $?) that anything went wrong.

**Comment by neimad1985** [comment]
Hi, I'm coming from Ansible and I find that Salt is great but this issue, IMHO, should be closed quickly.
The fact is that if you use a .sls file and require salt to state.apply it, you will get an error reporting that the package that you are looking for does not exist, which is good. I mean at terminal prompt, not by digging into the logs.
But creating a state is not the first thing that you do when trying the product for the first time. The first time you immediately use the pkg.install command line API and you are desappointed when getting no error output when requesting installation of a not existing package. I am used to dig more, so I'm still here, but some people could stop using the product at their first try because this really is not serious (not an agressive remark). Thanks for fixing it quickly, for the sake of the product.

**Comment by terminalmage** [comment]
Closing since this has been implemented for months now and will be part of the upcoming feature release:

```
# salt foo pkg.install asdf
foo:
    ERROR: Problem encountered installing package(s). Additional info follows:

    changes:
        ----------
    errors:
        - error: target not found: asdf
```

**Comment by neimad1985** [comment]
Okay, you just had forgotten to close the issue. Thanks for the good work. Waiting for the upcoming release :)

**Comment by damon-atkins** [comment]
Not sure if this is in the same boat "winrepo-ng pkg.upgrade no error message from master for unsupported feature #31889"
