### ISSUE TITLE
oscodename wrong on Debian 8 (jessie)

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#34423]
On a Debian 8 (jessie) system where lsb-release is not installed, the oscodename is wrong (it should be just "jessie"):

```
$ sudo salt debian grains.items   
[...]
   lsb_distrib_codename:
        Debian GNU/Linux 8 (jessie)
    lsb_distrib_id:
        Debian GNU/Linux
    lsb_distrib_release:
        8
[...]
    os:
        Debian
    os_family:
        Debian
    osarch:
        amd64
    oscodename:
        Debian GNU/Linux 8 (jessie)
    osfullname:
        Debian GNU/Linux
    osrelease:
        8
```

When installing lsb-release, the output will be correct:

```
$ sudo salt debian grains.items   
[...]
    lsb_distrib_codename:
        jessie
    lsb_distrib_description:
        Debian GNU/Linux 8.4 (jessie)
    lsb_distrib_id:
        Debian
    lsb_distrib_os:
        GNU/Linux
    lsb_distrib_release:
        8.4
[...]
    os:
        Debian
    os_family:
        Debian
    osarch:
        amd64
    oscodename:
        jessie
    osfinger:
        Debian-8
    osfullname:
        Debian
    osmajorrelease:
        8
    osrelease:
        8.4
    osrelease_info:
        - 8
        - 4
```

salt 2016.3.0 and the develop branch are affected.

Currently `os_data()` is overly complex and has issues: When lsb-release is not found, it will fill out the lsb_\* values by falling back to various sources. Instead the lsb_\* values should only be set, when lsb-release is available.

Why don't you use `platform.linux_distribution()` if that provides useful information?

I am willing to fix this bug, but I don't want to add another quirk to make the code even less readable.

**Comment by bdrung** [comment]
Maybe it is better to fix ```platform.linux_distribution()``` to provide useful data.

**Comment by Ch3LL** [comment]
@bdrung I was able to easily replicate this and am seeing the same thing you are bringing attention to.

We don't want to refactor grain code too much to ensure we don't change values for others, particularly in a dot release. If you want to refactor a lot of it just make sure to add that to the develop branch and then we can review the PR. 

If ou do want to just approach this by just fixing just this bug you can add that to the 2016 branch. 

I'm not entirely sure if there is a specifc reason as to why linux_distrubtion has not been used in the paste instead. maybe @cachedout do you have any insight into why we aren't using platform.linux_distrubtion() instead?

**Comment by cachedout** [comment]
Using `platform.linux_distribution` seems reasonable to me.

@isbm Do you have any thoughts here?

**Comment by isbm** [comment]
@cachedout as always, Debian guys giving no unit tests and then crying something broke at their kingdom. Ubuntu (unit tests were given by me) works just fine:

```
Your branch is up-to-date with 'upstream/2016.3'.
(saltdevelop)bo@zeus:~/work/salt$ salt saltdevel grains.get oscodename
saltdevel:
    xenial
(saltdevelop)bo@zeus:~/work/salt$ salt saltdevel grains.get osfullname
saltdevel:
    Ubuntu
(saltdevelop)bo@zeus:~/work/salt$ 
```

I can look into this though.

**Comment by isbm** [comment]
@cachedout @Ch3LL Ohwow... What animal ate my bugfix _exactly for this regard_ and how to make it happened back?

https://github.com/saltstack/salt/pull/35227/commits/a69f97f9adf4779bc0f112e56d169deb06056889

**Comment by isbm** [comment]
@bdrung 

> Why don't you use platform.linux_distribution() if that provides useful information?

We [do](https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L1404)

**Comment by isbm** [comment]
```
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.linux_distribution()
('debian', '8.5', '')
```

I don't think this is a problem in Salt.

**Comment by isbm** [comment]
Further investigation shows that `/etc/os-release` in Debian 8 is actually this:
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
So since `PRETTY_NAME` is what Salt calls `oscodename`, I bet on unstable it says `Debian GNU/Linux stretch/sid`. And it is correlates to https://www.debian.org/releases/

I don't think we should care about this, unless we need to make Debian special.

**Comment by isbm** [comment]
Just a note, Ubuntu gets it right:
```
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.linux_distribution()
('Ubuntu', '16.04', 'xenial')
```
Hence `oscodename` gets to be "xenial". What we would _really_ like to avoid is an ad-hoc parsing of strings, like stripping-out "jessie" from `PRETTY_NAME` of `/etc/os-release`, since it may change at any moment. The name should be obtained either from LSB area or `platform.linux_distribution`. And if none returns anything proper, then Salt should not try to fix a broken system.

**Comment by isbm** [comment]
And even further investigation shows that it is a packaing bug in Debian. Because `/etc/lsb-release` has to be in the `base-file` package, just like in Ubuntu. To support the idea it is a Debian's bug, here you go: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829245

I think this issue should be closed, @cachedout Sorry for a long noise investigating this. :wink:

**Comment by bdrung** [comment]
Hey, you found the Debian bug that I open because of this grains bug. :smiley: 

That's the output on unstable:
```
Python 2.7.12+ (default, Aug  4 2016, 20:04:34) 
[GCC 6.1.1 20160724] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.linux_distribution()
('debian', 'stretch/sid', '')
```

`ID`, `VERSION_ID`, `VERSION_CODENAME` are the fields in `/etc/os-release` that are useful for processing by scripts and for using in salt states. `PRETTY_NAME` is useful for presenting to the user, but not for doing matches in salt states. Extracting parts of `PRETTY_NAME` is going to be very fragile.

We use the `oscodename` grain for constructing `apt.sources` entries (which contain the codename like `jessie`, `stretch`, or their aliases like `stable`, `testing`). So having `PRETTY_NAME` (which includes spaces) in there will cause `apt-get` to fail horribly.

I agree that python in Debian should be fixed to return the codename (if present) in the `platform.linux_distribution()` call.

Using 190 lines for detecting the Linux distribution and version is too complex IMO. You call  `platform.linux_distribution()` in there, but overwrite oscodename afterwards:
```
grains['oscodename'] = grains.get('lsb_distrib_codename', '').strip() or oscodename
```
and `lsb_distrib_codename` seems to be always set.

**Comment by isbm** [comment]
LOL, well, I am not a "Debian guy", just happens that support this part sometimes. :laughing: 

So we both agree that Debian should do a better packaging this regard. Let's wait they fix this. Ubuntu seems works just fine because they did include `/etc/os-release` into the `base-files` package. So should do Debian. Right now:

- You have a workaround (install LSB stuff)
- Debian should fix the bug

Let's see later what's up. On ARM it still fails, since there is no codename in general... I would close this issue as invalid for now.

**Comment by bdrung** [comment]
Here you get the test cases for Debian and Ubuntu.
