### ISSUE TITLE
portage_config states: strange config files manipulation/behaviour

### ISSUE THREAD

**Issue by podshumok** [saltstack/salt#34424]
### Description of Issue/Question

salt creates multiple files with .bak.bak.....bak extension when USE flags for some package is changed. This can happen during single run of state.highstate.
### Setup

setup.sh:

```
echo "sys-devel/gcc" > /etc/portage/package.accept_keywords/tmp
echo "sys-deve/gcc fortan" > /etc/portage/package.use/tmp
```

fortran.sls:

```
gcc-fortran:
  portage_config.flags:
    - name: sys-devel/gcc
    - use:
      - fortran
```

multislot.sls

```
gcc-multislot:
  portage_config.flags:
    - name: sys-devel/gcc
    - use:
      - multislot
```
### Steps to Reproduce Issue

Create above `tmp` files, create and run state, that includes both multslot.sls and fortran.sls.
Observe tmp.bak files appeared in /etc/portage/package.{use,accept_keywords}. Notice that two files were created for gcc USE flags.
Run state again - observe tmp.bak.bak files...
and so on
### Versions Report

Reproduced on multiple versions since  >2015.8.3

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Jul  1 2016, 07:05:21)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.1

System Versions:
           dist: gentoo 2.2 
        machine: x86_64
        release: 4.1.6-hardened
         system: Linux
        version: Gentoo Base System 2.2
```

**Comment by Ch3LL** [comment]
@podshumok it looks like we need to add some additional logic to check if we already have those tmp files in that location. Just for clarification am I understanding this correctly:

1. you run the state files and it works correctly adding the tmp.bak file
2. you run it again and where the issue lies is it adds a file named tmp.bak.bak

Any clarification would be appreciated. My understanding of how portage works in gentto is fuzzy.

**Comment by podshumok** [comment]
Hello!

Not always.
The problem is that portage treat these .bak files as normal config files. If you have `-use` flag in such a file and want to add `use` flag. you may not get what you want.
Also, I described an example with two state files, adding different use flags to the same atom. Even without `tmp` file, this setup will end up with .bak file or even with .bak.bak file.

**Comment by ribx** [comment]
I have this problem on all of our Gentoo servers. The `/etc/portage/package.accept_keywords` directory is full of files with several ".bak" endings, e.g. `net-analyzer/prometheus.bak.bak.bak.bak.bak.bak`. I already wrote a command to remove the endings, as a dirty workaround:

`for f in $(find "/etc/portage/package.accept_keywords" -iname '*.bak') ; do mv "$f" "${f/.bak*/}"; done`

Otherwise with every highstate an additional ".bak" is added until the limit of the filesystem is reached. Then the highstate fails.

I debugged the code and it looks like the functions of portage, that are use to parse package atoms, returns "None" if the package/version of the package does not exist anymore. As a result "enforce_nice_config()" raises an unhandle exception:
```$ salt-call portage_config.enforce_nice_config
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'NoneType' object has no attribute 'rfind'
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib64/python2.7/site-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/lib64/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib64/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib64/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/salt/modules/portage_config.py", line 131, in enforce_nice_config
    _order_all_package_confs()
  File "/usr/lib64/python2.7/site-packages/salt/modules/portage_config.py", line 148, in _order_all_package_confs
    _package_conf_ordering(conf_file)
  File "/usr/lib64/python2.7/site-packages/salt/modules/portage_config.py", line 248, in _package_conf_ordering
    append_to_package_conf(conf, string=line)
  File "/usr/lib64/python2.7/site-packages/salt/modules/portage_config.py", line 355, in append_to_package_conf
    pdir = os.path.dirname(complete_file_path)
  File "/usr/lib64/python2.7/posixpath.py", line 122, in dirname
    i = p.rfind('/') + 1```

and you are left with some files that are not cleaned up.

I suggest to remove all lines and atoms, that cannot be parsed by portage.

Btw: the same thing happens if there is a comment or an empty line in one of these files
