### ISSUE TITLE
pkg.install's version doesn't work the same way as apt-get's one which is misleading 

### ISSUE THREAD

**Issue by onorua** [saltstack/salt#34438]
### Description of Issue/Question

I have `prereq` state which should not be run if there is no changes in another state. Unfortunately I've discovered that it doesn't work as expected due to following message:

```
[DEBUG   ] Current version (['1.11.2-0~wily']) did not match desired version specification (1.11.2*), adding to installation targets
```

meanwhile, `apt-get` does support wildcards:

```
apt-get install docker-engine=1.10.2*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Selected version '1.10.2-0~wily' (Docker APT Repository:ubuntu-wily [amd64]) for 'docker-engine'
```

I've checked the code, and it seems wildcards are indeed not supported. For instance here I can see that pkg refresh is always called with wildcards due to:
https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py#L502
I propose to use `fnmatch.fnmatchcase` instead of just "==" which will have backward compatibility of course, but will have `apt-get` compliance. 

You might think that wildcards are not necessary, but that is not always convenient to use full package version. Lets look at `docker-engine` package. They have wily postfix if you use `wily` repository, and xenial if you are using `xenial` repository. But version can be the same. Having bunch of if/else makes state file messy. 

I believe we need to introduce 4th argument = compare function here:
https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py#L635
with proper wildcard match or debian package specific normalizing, because `distutils.version.LooseVersion` doesn't do the job it seems. 

P.S. 
While I'm writing this, I would like to take a chance to comment on another odd thing I've discovered while investigating my problem:
https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py#L636
as you can see there is comparison of version ">=" which returns true (mark package for installation?) when desired version is equal or more than current one. Why do we need to mark package for installation if version is equal? Is this expected behaviour?

**Comment by Ch3LL** [comment]
@onorua thanks for the PR! We will close this once its been reviewed and merged :+1:

**Comment by terminalmage** [comment]
@onorua Per our [discussion](https://github.com/saltstack/salt/pull/34442#issuecomment-269870025), I have added this feature in https://github.com/saltstack/salt/pull/38621.


> P.S.
While I'm writing this, I would like to take a chance to comment on another odd thing I've discovered while investigating my problem:
https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py#L636
as you can see there is comparison of version ">=" which returns true (mark package for installation?) when desired version is equal or more than current one. Why do we need to mark package for installation if version is equal? Is this expected behaviour?

This is definitely expected behavior. The ``pkg.install`` functions for the various providers are designed to be a direct interface to the package manager. If you run ``pkg.install``, you should get an ``apt-get install`` command as a result. It is not the job of a remote execution function to enforce idempotence, that is the job of the state (pkg.installed, etc.).
