### ISSUE TITLE
Windows salt-minion service (created by Nullsoft (nsis) installer) has no description 

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#34440]
### Description of Issue/Question

From a security perspective, each Windows service should contain a description.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Install Salt
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
Open Windows Task manager and see that the service salt-minion has no description or the description salt-minion
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2016.3.1

**Comment by markuskramerIgitt** [comment]
Change https://github.com/saltstack/salt/pull/34205 should add a description to service, but it does not.

**Comment by Ch3LL** [comment]
I'm not very familiar with .nsi files but a quick google search states it helps to create windows installers. So I am guessing the reason you can't see the description of the service name yet is because it would be a part of the package and not a git install. I'm not entirely sure on this at all. ping @twangboy do I understand this correctly? Is this maybe why the service description is not seen yet on develop?

**Comment by twangboy** [comment]
@Ch3LL Yes, it's part of the installer. The above PR adds a description after the service has been registered. This won't happen if someone installs salt through any other means.
