### ISSUE TITLE
Question: Saltstack team's policy for closing issues

### ISSUE THREAD

**Issue by tomlaredo** [saltstack/salt#34480]
### Description of Question
I often see some bugs reports that seem to be fixed but ticket is still opened (eg. https://github.com/saltstack/salt/issues/34001).

What is the SaltStack policy for closing issues? If I think the issue of my ticket is now fixed, could/should I close it?

Regards

**Comment by ahammond** [comment]
Usually I see a comment from @Ch3LL or one of the other salt-stackers along the lines of "hey, we think this is resolved, so unless you confirm that it's still a problem, we're going to close the issue" except, uh, more polite than that. And then I generally confirm that it's resolved and close the issue. If you think your issue is fixed, please comment to that effect and close the issue!

**Comment by rallytime** [comment]
@tomlaredo Yeah, exactly what @ahammond said. :)

If your issue is fixed/resolved to your satisfaction (even if one of us from SaltStack hasn't commented yet to say 'we think this is resolved'), we'd much rather have you close it with a comment saying so. If you close your own issue, you keep the power to re-open it if you need to. If we close it, you'll have to get one of us to open it again. We are of course happy to follow up and close issues when needed.

Perhaps some docs in the [Contributing docs](https://docs.saltstack.com/en/latest/topics/development/contributing.html) would be good to add how this process works and to the [guidelines for contributing](https://github.com/saltstack/salt/blob/develop/.github/CONTRIBUTING.md) file in case others have questions.
