### ISSUE TITLE
Installation documentation for Ubuntu server and Windows minion leads the user to use different salt versions.

### ISSUE THREAD

**Issue by AvinashDeluxeVR** [saltstack/salt#34504]
Hi all,

If you follow the [Ubuntu installation guide](https://docs.saltstack.com/en/2015.8/topics/installation/ubuntu.html) and the [Windows installation guide](https://docs.saltstack.com/en/2015.8/topics/installation/windows.html) you will have a mismatch in master and minion versions, since the latest version for Ubuntu is  2015.5.3 and the latest version for windows is 2016.3.1. 

This causes many issues as the win_repo directories changed significantly between versions.

Ideally these pages should tell new users that they require their minion version and their master version to match.

Thanks,

Avinash.

**Comment by Ch3LL** [comment]
@AvinashDeluxeVR the reason this occurs is because of the community managed repos. It seems 2015.5.3 is the version available in PPA, which we do not manage. We actually manage our own packages now at repo.saltstack.com and I would recommend to use the instructions on that site and you will not run into that issue. 

I think this is the issue I asked you to open in relation to making it more clear for the windows software repo docs [here](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#maintaining-windows-repo-definitions-in-git-repositories) to specify that running a 2015.8 master with 2016.3 would not work. So I think it would be more appropriate to add notes here instead to ensure people going through that walkthrough know those versoins would not work because of the different dir structure.

**Comment by rallytime** [comment]
Docs are fixed with #38650
