### ISSUE TITLE
Failed to authenticate messages are confusing and often wrong

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#34750]
The 'Failed to authenticate' messages are often confusing and conceal the true errors for the failure of the commands.  Here's a few scenarios you'll get them in:

a) You entered the wrong username/password ( This should be ONLY time you get the Failed message )
b) You don't have access to one of the hosts you targeted ( I didn't fail to authenticate, I just didn't have authorization to do that.. )
c) You forgot to issue a command.  For example, if you forgot to say 'cmd.script' and instead ran: salt example.com salt://test.sh, you get the message ( This would be hard to test as a syntax error, but how about something about not having access to the 'command' salt://test.sh.. )

These also fall into some of the returns you get from the API.  For example, there are 13 different scenarios that will return the same exact 'Authentication failure for type "eauth"' message when trying to use the runnerclient, with no information about exactly which of the reasons it failed on.  This makes debugging the problem more difficult than it needs to be.

I think, in general, these log messages need to be overhauled to provide some context as to their failure, in order to provide the user with better feedback as to why their command failed to publish.

**Comment by cachedout** [comment]
The last time I discussed this with @thatch45 (which was a _long_ time ago so my memory could be hazy), one of the reasons that this is the case was to prevent an potential attacker from determining which failure scenario they hit, which could provide some clue about the underlying authentication/authorization configuration.

That said, I tend to agree that there's a lot of room for improvement here. Let's bring in Tom here for some context. :]

**Comment by sjmh** [comment]
Ha, yeah that was on the back of my mind as I wrote it, thinking maybe it was meant to be somewhat obfuscating.

On the other hand - it's causing issues with our users because it's confusing the heck out of them as well.  Perhaps a middle ground to be found there.

**Comment by cachedout** [comment]
Most certainly. Personally, I'm in favor of breaking these out into more explicit messages but I'd like @thatch45 to weigh in.

**Comment by thatch45** [comment]
My original argument to not expose the messages was just me playing it safe in a broader sense.
The main thing to watch out for here is information leakage, now the message returns are not time restrained, but the auth of course is, which is there to prevent timing leak attacks. So I am not worried about time leaks since the auth data would still be relative to the execution path of the code.
The other attack has to do with the nature of the auth being used, but this information is already known to the user and is otherwise secure (protected unix sockets on the local system, TLS for salt-api), so I don't think that this is a concern either.

So I am going to approve adding detailed auth messages, but they do still need to be carefully reviewed to make sure that they do not expose any auth relative information.

**Comment by whiteinge** [comment]
It would be quite helpful to salt-api to be able to differentiate authentication errors from authorization errors. Related issue: #6420.
