### ISSUE TITLE
Reverse DNS can overwrite host and fqdn grains

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#35056]
### Steps to Reproduce Issue

Use a DNS server where you can configure reverse dns. Set the reverse DNS for your minion's IP to something other than the minions hostname.

`salt-call grains.get host` and `salt-call grains.get fqdn` will return the reverse dns address rather than the minions locally configured hostname and fqdn.
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@clinta thanks for the PR. once your PR is merged we will get this closed up. Thanks :+1:

**Comment by clinta** [comment]
So it looks like since 6d21f50a73132eea28ae6629bbf5a39f1c649563 the hostname generation has been re-written. I'm not sure if this is still an issue on develop or not.

**Comment by clinta** [comment]
@isbm can you comment on the changes to generating the hostname in develop? Do your changes fix this issue?

**Comment by isbm** [comment]
Yes, I rewrote this thing exactly because the minion is now what DNS tells all the time. Actually, always been, just was a pretty weird sorting that nobody knew why it was existing. We ran into a trouble with this, where longer names with "more dots" were in priority (which is wrong) and renaming host won't be possible. Now is just an FQDN whatever first returned, if fails, just a hostname. This way your minion will change the hostname only if you change the DNS. Which is fine.

But please test develop as well, and give us a feedback. :wink:
