### ISSUE TITLE
Make doc clearer for state.pip

### ISSUE THREAD

**Issue by byteknacker** [saltstack/salt#35127]
### Description of Issue/Question

When reading through the official SaltStack Documentation on salt.state.pip I noticed that in the title it is written salt.state.pip_state but in the examples, you use pip.installed etc. Due to this, I assumed that it would be correct to say something like:

virtualenv_installed:
  pip_state.installed:
    - name: virtualenv

But this is not the case, it needs to be pip.installed. My question is: why do you put in the title state.pip_state instead of just state.pip?

As a reference, this is the link to the particular page in the documentation: 

[state.pip_state](https://docs.saltstack.com/en/2015.8/ref/states/all/salt.states.pip_state.html)

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Only the documentation is concerned and not the source code.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Only the documentation is concerned and not the source code.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Version is 2015.08.11.

**Comment by Ch3LL** [comment]
@byteknacker `pip_state` is the name of the file `salt/states/pip_state.py`. The reason you use `pip.installed` instead of `pip_state.installed` is because of what we call `virtualname` and the virtual function which is documented [here](https://docs.saltstack.com/en/2015.8/ref/modules/index.html#virtualname) and [here](https://docs.saltstack.com/en/2015.8/ref/modules/index.html#virtual-function)

When salt loads a module it looks for the __virtual__ function. In the case of pip_state that virtual function returns the name of `virtualname`. So you then are able to call the function as `pip.installed`.

**Comment by byteknacker** [comment]
Thanks @Ch3LL, I totally forgot about this virtualname.
