### ISSUE TITLE
salt-api file.copy

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#35164]
hello, i use salt-api to use file.copy,for file that is ok,but for directory,it has a issue as follow:

curl -sSk http://10.10.100.51:8000 \
-H 'Accept: application/json' \
-H 'X-Auth-Token: 61272ed743cc17a513e24a08f04abc7396c2d10fe914060d0a59abf5bf2f86b8f12ae999d8fbb48ad1f80fd43f64944c113e6512cfb3f457a5ae96dcf41f7353' \
-d client='local' \
-d tgt='*' \
-d fun='file.copy' \
-d arg='/tmp/salt/api/test3_move' \
-d arg='/tmp/salt/api/test3_copy' \
-d recurse=True

{"return": [{"minion03": "ERROR executing 'file.copy': Cannot copy overwriting a directory without recurse flag set to true!"]}

but when i use the cmd it is ok:
salt \* file.copy /tmp/salt/api/test3_move /tmp/salt/api/test3_copy recurse=True
minion03:
    True

is this a bug about salt-api?

**Comment by whiteinge** [comment]
salt-api calls Salt's [LocalClient](https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd) interface and so any positional arguments or keyword arguments must be given to the `arg` or `kwarg` parameters that the various LocalClient.cmd* methods accept. These are the arguments that are sent down to the minion. Since LocalClient is often called from the CLI it also has the ability to parse `name=value` strings into `{"name": "value"}` dictionaries.

The above is equivalent to the following and so the `recurse` kwarg never reaches the minion.
```python
LocalClient.cmd('*', 'file.copy', arg=[
    '/tmp/salt/api/test3_move',
    '/tmp/salt/api/test3_copy',
],
recurse=True)
```

Try this syntax instead:
```
curl -sSk http://10.10.100.51:8000 \
-H 'Accept: application/json' \
-H 'X-Auth-Token: 61272ed743cc17a513e24a08f04abc7396c2d10fe914060d0a59abf5bf2f86b8f12ae999d8fbb48ad1f80fd43f64944c113e6512cfb3f457a5ae96dcf41f7353' \
-d client='local' \
-d tgt='*' \
-d fun='file.copy' \
-d arg='/tmp/salt/api/test3_move' \
-d arg='/tmp/salt/api/test3_copy' \
-d arg='recurse=True'
```

salt-api can make use of the same `name=value` splitting the CLI uses, but you don't need to use that and it's often more simple and explicit not to. A good way to visualize this is to send JSON instead of the urlencoded format. The following is functionally equivalent to the above but more explicit:

```sh
curl -sSk http://10.10.100.51:8000 \
-H 'Accept: application/json' \
-H 'X-Auth-Token: 61272ed743cc17a513e24a08f04abc7396c2d10fe914060d0a59abf5bf2f86b8f12ae999d8fbb48ad1f80fd43f64944c113e6512cfb3f457a5ae96dcf41f7353' \
-H 'Content-Type: application/json' \
-d '
{
    "client": "local",
    "tgt": "*",
    "fun": "file.copy",
    "arg": [
        "/tmp/salt/api/test3_move",
        "/tmp/salt/api/test3_copy"
    ],
    "kwarg": {
        "recurse": true
    }
}
'
```

You could even get rid of the `arg` altogether and use the named arguments in the [file.copy](function signature):
```sh
curl -sSk http://10.10.100.51:8000 \
-H 'Accept: application/json' \
-H 'X-Auth-Token: 61272ed743cc17a513e24a08f04abc7396c2d10fe914060d0a59abf5bf2f86b8f12ae999d8fbb48ad1f80fd43f64944c113e6512cfb3f457a5ae96dcf41f7353' \
-H 'Content-Type: application/json' \
-d '
{
    "client": "local",
    "tgt": "*",
    "fun": "file.copy",
    "kwarg": {
        "src": "/tmp/salt/api/test3_move",
        "dst": "/tmp/salt/api/test3_copy",
        "recurse": true
    }
}
'
```

One final note, not related to your question. You can avoid having to manually copy the `X-Auth-Token` by using the `-c` and `-b` flags to curl if you want to. [There an example of that here](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#authentication).

**Comment by SolarisYan** [comment]
@whiteinge Thank you very much for your detailed explanation, i will close it now

**Comment by lvs071103** [comment]
I want to ask a question：file.copy can increase the pill parameters?

**Comment by lvs071103** [comment]
```
# curl -ki https://10.105.51.217:7000/ -H "Accept: application/x-yaml" -H "X-Auth-Token: 129cd452387452a218570c9f3c89f8d9a500fe86" -d client='local' -d tgt='tx_s4_web1' -d fun='file.copy' -d arg='/data/salt/s4_conf.server.php' -d arg='/tmp/conf.server.php' -d arg='recurse=True'
HTTP/1.1 200 OK
Content-Length: 91
Access-Control-Expose-Headers: GET, POST
Cache-Control: private
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Tue, 15 Nov 2016 10:01:47 GMT
Access-Control-Allow-Origin: *
Content-Type: application/x-yaml
Set-Cookie: session_id=129cd452387452a218570c9f3c89f8d9a500fe86; expires=Tue, 15 Nov 2016 20:01:47 GMT; Path=/

return:
- tx_s4_web1: 'ERROR: No such file or directory ''/data/salt/s4_conf.server.php'''
```
why?
