### ISSUE TITLE
Module dependencies not met by saltstack packages

### ISSUE THREAD

**Issue by discotroy** [saltstack/salt#35171]
### Description of Issue/Question

I provision VMs via salt-cloud which installs the (2015.8.8) minion from Ubuntu repos, and then adds in the salt-stack repos and upgrades to the latest version as part of the state.apply.

Seemingly as a result of this process, certain dependencies within the partition module (and possibly others) are not met.  As a result, e.g. `partion.list` fails and is reported as being unavailable.

https://github.com/saltstack/salt/blob/v2016.3.1/salt/modules/parted.py specifies certain dependencies (parted, util-linux) which were not installed by salt-minion either when pulled from Ubuntu repos or saltstack repos.

Installing these packages manually resolves the problem.  Presumably adding them to a state will also resolve.
### Versions Report

Both salt-master and -minion were running 2016.3.2.

**Comment by Ch3LL** [comment]
@discotroy this is expected behavior. We do not install all dependencies for all modules. 

According to the docs partition.list depends on `parted, partprobe, lsblk (usually parted and util-linux packages)`

Sinc you are using salt-cloud you have your minion install those packages as part of hte install process by adding the following to your profile/provider file:
`script_args: -p <name of packages>`

Also to note if you are using salt-cloud it should install the latest salt packages from repo.saltstack.com. Can you run `salt-cloud -u` to make sure you have the latest bootstrap.

Does that workaround work for your issue?
