### ISSUE TITLE
Targets are irrelevant and don't matter when calling `state.show_sls`

### ISSUE THREAD

**Issue by jf** [saltstack/salt#35203]
### Description of Issue/Question

When using `state.show_top`, the output shows things as they'll be applied to the relevant host. However, when using `state.show_sls`, the identity of the targets becomes irrelevant. So even if you pass a state that does not apply to all of your targets, *the report will still come back as if it does apply to every single target/s*.

I'm thinking that this should not be the case, that you only show a state if it applies to a particular target. Intuitively, that makes more sense, does it not?

### Setup

Nothing too complicated, really. Please see description. All you need is one state that does not apply to every single minion.

### Steps to Reproduce Issue

`salt ubuntuhosts* state.show_sls centos-only.state`

### Versions Report

This isn't specific to any particular versions, and still applies to 2016.3.1.

**Comment by thatch45** [comment]
This does behave in the desired way. The idea behind state.sls is that you can apply states that are not in the top file, you don't actually need a top file, since you can always just apply states. You can also run `state.apply <state>` to apply a state that is not defined in the top file.

The benefit here is that it allows for the configuration management system to be used for more, like running arbitrary idempotent jobs, or you can more fluidly mix and match what states apply to what systems.

So I am going to close this out, but the main message is that Salt allows you to manage your systems in a very flexible way, and so many people never even use a top file :)

**Comment by jf** [comment]
I see. Thanks for the explanation!
