### ISSUE TITLE
What is the equivalent of puppet resource command for salt

### ISSUE THREAD

**Issue by bx5974** [saltstack/salt#35204]

**Comment by bx5974** [comment]
as we see in this man page 

https://docs.puppet.com/puppet/latest/reference/man/resource.html

This example uses puppet resource to return a Puppet configuration for the user luke:

` $ puppet resource user luke
user { 'luke':
 home => '/home/luke',
 uid => '100',
 ensure => 'present',
 comment => 'Luke Kanies,,,',
 gid => '1000',
 shell => '/bin/bash',
 groups => ['sysadmin','audio','video','puppet']
}
`

**Comment by Ch3LL** [comment]
i really like this idea. I can't think of something that is currently implemented. So I will approve as a feature request fro now. 

ping @thatch45 @cachedout how difficult do you guys think this would be to implement? Or maybe there is something currently already implemented that I'm not thinking of?

**Comment by bx5974** [comment]
it would be great to have this at salt core!

**Comment by damon-atkins** [comment]
+1 it basically needs to be implemented for every state.  Needs a state_dump.    A naming standard would be required  e.g. pkg.dump_state    And then everyone follows that standard.    It means converting something existing is easier because salt provides the syntax to add into a state yaml.   It also helps with people learning. e.g. how do I describe this user to place into a state yaml.

I change the name of the title however...   "dump existing state"    

I was thinking it would be better for salt if kawgs were used for everything.   e.g. you could use dump=true  against an an existing state function.  Food for thought.

**Comment by cachedout** [comment]
Is something like what you get from `state.show_sls <my_state_file> output=yaml` what you had in mind?

**Comment by damon-atkins** [comment]
The idea is it would output the current state as it exists on the system. You could then cut and paste it into an sls file. e.g.  You have a user on a system and you want to find out its state and then use it to apply to other systems.

**Comment by adam-smith-sundance** [comment]
I'm not sure if this is already in salt but it would be nice to do this for network interfaces too,

I am currently getting a cumulus switch ready to use with Salt and it would be amazing to grab the current configuration off the switch so that it doesn't get changed by accident with a new state.

**Comment by damon-atkins** [comment]
.

**Comment by Jaharmi** [comment]
Has there been any movement toward this? It seems like it would be great for helping to learn / get started with Saltstack. I’ve use “puppet resource” and it is handy, although it didn’t always work in my experience.
