### ISSUE TITLE
Feature Request: Aliases for common Package Names

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#35377]
### Description of Issue/Question

If you target RPM and DPKG bases distributions, you know the problem: Package names do differ.

On one platform the package is called "foobar" on the other it is called "foo-bar"

It would be great, if salt would provide a basic set of aliases.

AFAIK this naming problems gets solved by every user of a configuration management tool again and again.

It would be great if salt would be one of the first to solve this.

The list of aliases is endless and solving all won't work.

But it should be possible to solve most common ones like "http" vs "apache2".

BTW, I am not stupid. I know how to handle conditions in sls files :-) 

I just want to stop wasting our time.

What aliases do you know and how do you solve this up to now?

**Comment by Ch3LL** [comment]
I understand the reasoning behind wanting to implement this, but I guess my concern is this might become a mess to manage. Salt-formulas kind of handle this problem by mapping OS's to packages using jinja, which I understand you stated you know how to handle using that same logic. 

I'd like to get @thatch45 or @cachedout 's opinions on this issue. Do you guys think this would be something you would want to implement into salt? Or should we expect this to be handled by the user?

**Comment by thatch45** [comment]
This is a dup, I am sure, we get asked to do this every few months :)
I have looked into this a few times and automating it would be hard, and by hard I mean, the name differences are unpredictable.
The real way to solve this problem would be to make a python library that was separate from salt that we could dep, that library would likely just be a community maintained mapping of package names. If someone is willing to start this project we will happily tie into it

**Comment by guettli** [comment]
Thank you for your reply. I see, a third party library could solve this.

What do you, the salt expert, advice to new comers?

Imagine your product supports RedHat,  SuSE and Ubuntu. Each in two versions. Do you keep six lists of packages to install?

**Comment by guettli** [comment]
There is already a project which tries to bring sanity in this package naming chaos: https://github.com/unixpackage/unixpackage

It would be nice it salt could use it. This way we could avoid a lot of ugly if-else stuff in our sls files.

**Comment by thatch45** [comment]
that project looks promising, it is AGPL so I can't make it a required dep, it is also limited to a smaller subset of distros then what we support, but they likely hold the key to getting this done. I will set this as an investigation feature for Nitrogen

**Comment by damon-atkins** [comment]
https://github.com/unixpackage/unixpackage.github.io/blob/master/libzmq3.json
Seems not to support different versions of an OS may use different package names.

**Comment by lorengordon** [comment]
Yeah, I don't like that they only map the ubuntu package names.

Also, am I reading it right that requires an active connection to the Internet? Definitely would want a way to disable this, or not default to it, if it becomes a feature.

**Comment by thatch45** [comment]
Right, it we ended up using unixpackage directly it would need to be explicitly enabled, my main goal here is to investigate how they are doing it and determine if we could replicate the baseline process.

**Comment by thatch45** [comment]
As for an internet connection, we would never add a default feature that required an internet connection like this

**Comment by lorengordon** [comment]
Understood, and I figured. Was just raising awareness for use cases this maybe _doesn't_ solve. :smile: 

What they're attempting to do is great, and it would be a convenient feature in salt. Though I'm also content using grains.filter_by and my own mapping.

**Comment by lorengordon** [comment]
Their implementation seems a bit odd, for a library. The database isn't in the library, it's a separate git repo, where each package is defined in a separate json file, and the file is named for the ubuntu package name. So, no straightforward way to just "import" the data mappings as an object.

There's a licensing problem as well, as they've pulled in the [click](https://github.com/pallets/click) package into their project without adhering to the terms of that license. Copyright notice, etc...

**Comment by thatch45** [comment]
Very good points, to make the database useful we would likely need to strip it down and re-organize it, and yes, the project itself is AGPL, not to mention the click issue....

**Comment by crdoconnor** [comment]
Hi,

I'm the author of unixpackage. Thanks @guettli for notifying me of this discussion. I'd be happy to help out in any way I can if you want to use this package.

* Thanks for bringing to my attention the thing about click. I'll fix that tonight.
* Similarly when I picked AGPL I picked as a default I wasn't thinking about inclusion in other projects. I don't see any reason not to switch to BSD.

I put the packages online and made the app request them so that they could easily be updated without needing to update the app. Since an apt-get or yum install requires access to the internet anyway I didn't see this as being a problem (why is it a problem?). The JSON snippets are cached, however (in a ~/.unixpackage directory) - internet access is not required if they are there (except for the actual installing).

There are a number of issues which it doesn't address yet, but which I've been meaning to address:

* Handling versioning in a distro-independent way.
* Not all packages have a one to one relationship with equivalents in other distros. Sometimes it's one->many, many->one.
* Some packages don't have an equivalent. At the moment it fails silently (bad, but worked for my purposes at the time).
* I'd be happy to accomodate other distros provided somebody supplies a working vagrant image for me to test with (and maybe helps out with the package list). The only reason I limited this to the distros did was because I tried a few vagrant images for more obscure distros and they just plain didn't work (e.g. the gentoo image I tried failed to even install firefox, opensuse's package manager froze when installing packages).

>Seems not to support different versions of an OS may use different package names.

@damon-atkins : there is some support for this actually https://github.com/unixpackage/unixpackage.github.io/blob/master/libtiff-dev.json

**Comment by lorengordon** [comment]
@crdoconnor, awesome news on the licensing! :D

As for the issue around Internet access... I mostly work with RHEL-based derivatives, so I can only speak to yum. Yum does not require access to the Internet; it just requires access to the enabled repos. At least for the customers I support, the enabled repos are typically internal, customer-managed mirrors and the servers themselves do not have external access to the Internet.

**Comment by crdoconnor** [comment]
Well, you can bypass unixpackage's need for internet access now by pre-filling all of the json files into a newly created ~/.unixpackage directory. If you do that it won't attempt to access the internet.

I'm open to suggestions on how to improve this process - bearing in mind all the various trade offs. I kept it separate because I believe that the release process for the package itself should be decoupled from the library.

**Comment by thatch45** [comment]
Yes, these are many of the core issues with the general process you are trying to tackle. I think that for 99% of packages things don't change much. I think that the optimal scenario would be to make a many to many relationship of package names since you are currently using a primary key approach (ubuntu package name)
The other problem with Salt is that we really just want the package name lookup, since we have our own wrappers around calling the underlying package manager (apt/yum/zypper/etc). What would you think of us collaborating on the json files and then I build a system to compile your package associations into an sqlite database so we can ship a static db based on unixpackage and then use salt to run the actual install inside of salt?

**Comment by crdoconnor** [comment]
>I think that for 99% of packages things don't change much.

That's a dangerous assumption to build upon.

New packages are being introduced, renamed and deprecated all the time. Moreover a break in terms of user experience should such a thing happen would be pretty awful - deployments that worked yesterday would fail today. This has (sort of) happened to me a couple of times already - except I've been using it where it hasn't mattered as much (setting up dev environments). For your users it matters much more (deployments to production).

To do this comprehensively I think means having a continuous integration environment that periodically tests that all of the packages actually install on virtual machines. I'm happy to set such a system up (the tests are part of the way to being able to do that already) but I wouldn't want to maintain or own the hardware that runs the tests.

You'd also need a contributor (though not necessarily a programmer) who monitors feeds from the different distros of incoming packages, adds packages, sync up the names and finds or builds virtual machines to test new distro versions, etc. That would require an ongoing commitment.

>The other problem with Salt is that we really just want the package name lookup, since we have our own wrappers around calling the underlying package manager

Well, I can easily expose the method that does that via the API tonight. I wouldn't suggest rewriting just for that reason alone.

Do you have some sophisticated code for detecting the environment which the code is running in? (that's another rabbit hole rife with obscure and nasty edge cases).

>What would you think of us collaborating on the json files and then I build a system to compile your package associations into an sqlite database so we can ship a static db based on unixpackage and then use salt to run the actual install inside of salt?

I'd be happy to collaborate but I'd prefer to do it properly if we did - largely meaning setting up a comprehensive QA process and being continuously maintained. Are you willing to help with that?

>I build a system to compile your package associations into an sqlite database so we can ship a static db based on unixpackage 

I'd be wary of doing this unless there is some mechanism for frequently updating the database. All it would take would be one apt-get dist-upgrade (or equivalent) and an out of date database for this to break in a pretty horrible way.

Unfortunately this is a deceptively simple looking problem that is anything but simple.

**Comment by thatch45** [comment]
You have outlined virtually all the reasons why I have not done this! It is a very complicated issue. Your points on package name updates is also very valid, since I have not been working directly on this problem I will cede you your conclusions.
As for environment checks, yes, we do have a very sophisticated way of doing that in Salts grains and loader systems. It is one of the core components of Salt :).

I think that we agree wholeheartedly on this being a very hard problem to solve. I do think that we could have a mechanism to cleanly update the database into environments where they cannot hit the internet directly, which is a very common issue, especially for larger deployments, (we would make a salt runner that would download the db to the salt master and then salt can easily push the updated db down to minions) since they also often have local repository copies.

All in all, I think that this is solvable, although I do think that we might need to refactor some assumptions in unixpackage, but not very much, mostly just adding more awesomeness to something that is already quite awesome.

**Comment by lorengordon** [comment]
I'd be partial to packaging the database so it's available within the library, or as a separate library, and having a good CI/CD setup that automates the release of new versions to pypi. We've been getting familiar with Travis CI, and it's been pretty fantastic at that so far (it is still very new to us, though).

I realize we could setup our own process to download the json files and then distributing the cache. But that's exactly what package managers and repos are for. Why duplicate that?

Having the salt master do the distribution is another workaround, except when it also does not have connectivity to the Internet, or when you use salt purely in masterless mode...

**Comment by guettli** [comment]
@thatch45 you wrote:
> You have outlined virtually all the reasons why I have not done this! It is a very complicated issue.

Yes! I can understand you. This issue is a beast and that's why other solutions (chef, puppet, ..) have not solved it up to now (at least I think so).

Maybe salt should provide some alias mechanism, but should not provide a single alias entry itself. 

Since a single package on one platform can be N packages on a different platform, the alias mechanism should handle this: resolving one alias result in N names.

**Comment by thatch45** [comment]
I agree there, with the idea that we basically create a new package name for packages, I would suggest following the upstream package name and then having that call install all packages under that name. I think that would be a good start, then we could work towards split package names

**Comment by thatch45** [comment]
Basically take the (historic) Arch Linux approach to package naming

**Comment by guettli** [comment]
Thank you for thinking about this issue.

In the long run it would be good to solve this with code.

What can we do now?

I think giving some hints in the docs would help.

Now the question: How to solve this issue (package names and versions differ on different linux plattforms) with the current salt version?

I see several solutions. Should I open a new ticket for this issue (updating docs)?

**Comment by thatch45** [comment]
I think that the best way to do this would be to make a separate project to track package names, as well as build in a hook to salt that allows for a static database of package aliases to be referenced by salt. That way as the package db project matures it can be used as a third party plugin

**Comment by guettli** [comment]
@thatch45 yes, creating a separate project to track package names is a good solution for
the future. Until we get there, I would like a simple guideline for new comers. I guess
there about 10 ways to handle the problem with the current salt version. It would be nice
to have a sane default salt way to do this.

A guideline has the benefit that experts can solve it in they way they are used to and new comers know what to do.

**Comment by thatch45** [comment]
https://docs.saltstack.com/en/latest/topics/best_practices.html#modularity-within-states

Making a jinja map is the recommended way right now

**Comment by guettli** [comment]
I hope this does not offend anyone ... If you put on the new comers glasses and then look at the link you sent (Modularity in SaltStates, from Best Practice), then this looks like black magic. It looks like "we are able to make simple things complicated". I guess most new comers will feel like "I am too stupid for this".

Unfortunately I have no idea how to improve this.

You said "Making a jinja map is the recommended way right now". Is there work in process to make this simpler?
