### ISSUE TITLE
gce: Is there any way to set the password for Windows instance using salt cloud?

### ISSUE THREAD

**Issue by NagarajGond** [saltstack/salt#35479]
### Description of Issue/Question

Couldn't find the way to set/get the password for windows instance. We have option to use sshkey file for  linux instances.

**Comment by techhat** [comment]
Ping @erjohnso.

**Comment by erjohnso** [comment]
Hi @NagarajGond,

Short answer is No, there is no way to reset a Windows instance password using salt cloud.

Since this capability isn't available in salt, you'll need to follow the procedure at https://cloud.google.com/compute/docs/instances/windows/creating-passwords-for-windows-instances to reset the password through our web console or via our `gcloud` utility.

There is a documented procedure [https://cloud.google.com/compute/docs/instances/windows/automate-pw-generation] for writing client-side code to generate a Windows password. There is even a code-snippet in python, so in theory, it would be fairly easy to add this to salt.  However, GCE support in salt is implemented via `libcloud`, so that dep would need to be updated first.

**Comment by NagarajGond** [comment]
Thank you @erjohnso, I will refer the above link.
