### ISSUE TITLE
Can't get status of job when minion is offline (REST API)

### ISSUE THREAD

**Issue by gotsmth** [saltstack/salt#35547]
Hello guys, thanks for the salt!

Let's assume we have one master and one minion which is connected to the master.
I'm sending job request via REST API (cherry) to the master, output is (/jobs/xxxx):
`{"info": [{"Function": "state.sls", "jid": "20160817134856136579", "Target": "host", "Target-type": "glob", "User": "root", "StartTime": "2016, Aug 12 11:48:56.136579", "Arguments": ["some.msg"], "Minions": ["host"], "Result": {}}], "return": [{}]}`
All is fine because remote job is working.

Next try with stopped minion on this remote 'host', output is:
`{"info": [{"Function": "state.sls", "jid": "20160817134856136579", "Target": "host", "Target-type": "glob", "User": "root", "StartTime": "2016, Aug 12 11:48:56.136579", "Arguments": ["some.msg"], "Minions": ["host"], "Result": {}}], "return": [{}]}`
As You can see, output is the same - no matter if minion is online or offline.

If I try to do the same from CLI, I'm getting pretty: **Minion did not return. [Not connected]**
Why REST API did not report such a thing? So, how can I know if this job rly went to the remote host or not? 

Thanks,
Best regards.
### Setup

Test env. One master and one minion.
### Steps to Reproduce Issue

Start new job via REST API on minion which is currently offline.
### Versions Report

salt-minion-2016.3.2-1.el7.noarch
salt-2016.3.2-1.el7.noarch
salt-api-2016.3.2-1.el7.noarch
salt-master-2016.3.2-1.el7.noarch

Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
        PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by whiteinge** [comment]
The "Minion did not return. [Not connected]" output is not part of Salt's Python API, or Salt's outputter system. Rather it was added as a special-case in the CLI wrapper for the Python API. It would be nice if this was centrally available but it would need to be specifically added to each of the netapi modules.

Still it is a good addition. Marking as a feature.

**Comment by gotsmth** [comment]
That is nice, I'm waiting.
Thank you.

**Comment by closepin** [comment]
There any hope of getting this in place any time soon? We are managing minion keys and outages pretty often when a machine is down for maintenance or any other reason we may need to stop the minion, causing jobs that reach out to multiple machines to hang for extended periods of time. Purely because of this.

We're on 2017.7.2 infrastructure-wide.

**Comment by whiteinge** [comment]
An argument to expose the data needed for this check was added to Salt's Python API in 2017.7 called [full_return](https://docs.saltstack.com/en/develop/topics/releases/2017.7.0.html#full-return-argument-in-localclient-and-runnerclient). You can use that immediately to perform the same calculation that the Salt CLI performs -- subtracting minion IDs in that `minions: []` educated guess from the minions that actually return data.

**Comment by closepin** [comment]
Fantastic, I will test that as soon as I can and report back. Thank you!

**Comment by closepin** [comment]
Running on 2017.7.2 VM with our API wrapper extended to have full_return in the request data, I am not receiving the format of the return data as described in your link.
I've attempted this with local, local_async, and with and without a minion offline. Is there any other configuration that may impact the ability of the API to return a full response? I never get a return_code entry for offline minions.

**Comment by whiteinge** [comment]
Oof. I do apologize -- I misremembered what data was included behind that flag.

You should see additional metadata (such as `retcode`) in addition to the job returns themselves, however the `minions` array is _not_ among them. That array is only surfaced via actively watching Salt's event bus. (It may also be written to the job cache on the Master.) You can watch the event bus yourself via the `/events` endpoint ([example](https://gist.github.com/whiteinge/a646d4d937960d3ef306)) -- the `new` job event contains that data -- but that does require some async juggling. If you're in a pinch I'm happy walk you through how to do that now. But that said, this is most ergonomic as an addition to salt-api itself so I'll defer that answer to the Salt team.

**Comment by closepin** [comment]
Thanks for getting back. I was wondering when we'd have to write a direct listener to the event bus - this is annoying enough of an issue that we'll want to build this out to be part of stack. Instantiating this during execution of our tooling and having that be where we watch for event completions seems like a direct enough approach to resolving this issue. 

The other interesting thing is that the minion presence detection logic appears to not detect offline minions at all, the down request with a target will always respond with the nodes that WOULD have responded instead of the ones that will which is unfortunate since presence seems more appropriate than this path.

All that being said, thank you for the example, I'll get something on my teams backlog to build and address this asap.
I am also interested to hear what the Salt team may have to say.

**Comment by closepin** [comment]
We are actually almost exclusively using local_async runners and querying for completion, issue is that downed minions hang forever waiting for results which led to the last few iterations of attempts. If IP address is needed to use manage.present I will attempt to write something into the api for that. I believe we were using manage.down with tgt_types/expr_form as compound since that's what we use for all queries into the API. We were trying to use this to create a list of minions to remove from the list of minions the JID reports would have been hit by the query, so that we can determine completion properly.
I may just need to revisit the completion checking for jobs.get_job in our async loop. It may be that we just missed something in the invoked job to let us know some minions aren't ever going to come back. It seems impossible that this is that big of an oversight in the API.

**Comment by whiteinge** [comment]
Oh, interesting. You may be onto something there. The only part of Salt that hangs for downed Minions is sync calls from the `salt` CLI (which performs that `minions: []` guestimate to give the appearance of synchronous behavior) and Orchestrate (which uses that same sync call). If you're already using `local_async` then Salt itself is never actually waiting for anything -- the 4506 port will accept job returns at any time, and if/when they come in just writes them to the job cache.
