### ISSUE TITLE
When running the master in debug mode and exit, it gives a Traceback in 2016.3.3

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#35612]
### Description of Issue/Question

When running the master in debug mode and exit, it gives a Traceback when exiting.

```
2016-08-19 21:18:51,338 [salt.log.setup   ][ERROR   ][25305] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 3] No such process
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 315, in _exit_function
    p._popen.terminate()
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 171, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 3] No such process
```
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

Run the master in debug mode `salt-master -ldebug`
Exit out of it `CTRL-C`
### Versions Report

```
[root@li229-131 ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.6.3-x86_64-linode70
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

**Comment by tmehlinger** [comment]
This has been happening for a long time and it's not specific to debug mode. If you look in the master log when you stop the master, you'll see this happens all the time.

It's happening because of the shenanigans done to juggle signal handlers in the process module (https://github.com/saltstack/salt/blob/develop/salt/utils/process.py#L697). Basically every process spawned gets assigned SIG_DFL, which for SIGINT, SIGTERM, and SIGQUIT, terminates the process. Furthermore, the master calls `os.setsid()` when it daemonizes, making itself and all its children members of a process group, meaning any signal sent to the parent process will be propagated to all children. The end result is the children die before the master can clean up.

The fix for this would be to assign a custom handler (to either ignore signals, to communicate receipt of the signal to the parent process, do some cleanup, or a combination thereof).

**Comment by cachedout** [comment]
We did have this happening for a while but I can't replicate this against the 2016.3.3 tag at all. Is this happening consistently or just on occasion?

**Comment by tmehlinger** [comment]
It's consistent in 2016.3.2. It's also pretty easy to replicate, just fire up the master in the foreground and then ^c it.

**Comment by tmehlinger** [comment]
I just tested against a fresh 2016.3.3 install in Vagrant on Ubuntu 14.04. Still happens.
