### ISSUE TITLE
Unhandled exception in file.replace

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#35723]
### Description of Issue/Question

I have the following state:

```
pamd-post-ssh-slack-hook:
  file.replace:
    - name: /etc/pam.d/sshd
    - pattern: session optional pam_exec.so seteuid /etc/ssh/slack-ssh-bot.*
    - repl: session optional pam_exec.so seteuid /etc/ssh/slack-ssh-bot {{ salt['pillar.get']('base:slack:webhook') }} {{ salt['pillar.get']('base:slack:channel') }} {{ salt['grains.get']('env') }}
    - flags: []
    - append_if_not_found: True
```

where flags is overridden to fix  https://github.com/saltstack/salt/issues/33118 - but throws an exception which is unhandled in salt:

```
Function: file.replace
    Name: /etc/pam.d/sshd
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
              **cdata['kwargs'])
            File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1651, in wrapper
              return f(*args, **kwargs)
            File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2865, in replace
              show_changes=show_changes)
            File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 1817, in replace
              flags_num = _get_flags(flags)
            File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 1245, in _get_flags
              return reduce(operator.__or__, _flags_acc)
          TypeError: reduce() of empty sequence with no initial value
 Started: 10:01:10.141718
Duration: 2.669 ms
 Changes:
```
### Versions Report

salt-call 2016.3.2 (Boron)

**Comment by lorengordon** [comment]
Can you clarify why you feel overriding flags with an empty list is fixing #33118? That issue was related to using anchors in the pattern, while also overriding flags without passing the `MULTILINE` option. You are not using anchors, nor any flags, so your pattern should work fine without setting flags at all.

The stacktrace seems to be indicating that using an empty list of flags is part of the problem. Probably the `get_flags` function doesn't know what to do with the empty list.

**Comment by Ch3LL** [comment]
Yes can you please clarify how its helping fix that issue. Maybe you are running into another issue without the flags that we can help to investigate? Thanks

**Comment by lorengordon** [comment]
@Ch3LL, I'd like to add that `flags` does accept a list, so an empty list should not cause a traceback. I think there is a bug there.

But if the empty list did not cause the traceback, I am pretty sure the result of the `file.replace` state would not be as @grobinson-blockchain expected since the wildcard at the end of the pattern would match the entire file rather than just the line. :) That's why I think this state will be fine just removing the `flags` key entirely. The `MULTILINE` flag (the default for `file.replace`) restricts a match to a single line. It sounds counter-intuitive, but that's how python's `re` module works.

**Comment by Ch3LL** [comment]
thanks for pointing that out @lorengordon I tested it and yes it seems that the empty list causes the traceback. So i'm going to label this as a bug since we should be sptting out an error related to not being able to find empty flag. In fact when i do something like `- flags: ['doesnotexist']` and i get a stack trace as follows:


```
local:
----------
          ID: pamd-post-ssh-slack-hook
    Function: file.replace
        Name: /etc/pam.d/sshd
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2876, in replace
                  show_changes=show_changes)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 1820, in replace
                  flags_num = _get_flags(flags)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 1236, in _get_flags
                  _flag = getattr(re, str(flag).upper())
              AttributeError: 'module' object has no attribute 'DOESNOTEXIST'
     Started: 21:06:55.191583
    Duration: 5.574 ms
     Changes:   

Summary for local
```

Which I think we need to do some error checking here to spit out that flag does not exist choose from teh follwoing. Thanks
