### ISSUE TITLE
Calling mine.update from Python module fails

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#35936]
### Description of Issue/Question
In my Python module I perform the following tasks:
1. `__salt__['grains.setval'](grain, grainData)`
2. `__salt__['mine.update']` (which should push some of the grains data to the mine)

Expected outcome: the mine is updated
Actual outcome: the mine does not change

If I change my call to `mine.update` to any of the following the mine gets updated as expected:
`__salt__['mine.update']()`
`__salt__['mine.update'](True)`
`__salt__['mine.update'](False)`

If I capture the return value of `__salt__['mine.update']` I get a value of something like `<function update at 0x243a668>`. The other variations return `True`.

The simple answer to my issue could be `__salt__['mine.update']` is invalid syntax - but I would expect a stack trace to be dumped out or some sort of obvious error rather than a silent fail. Alternatively the answer could be `__salt__['mine.update]` is valid syntax and should either work or return `False`.

An aside to this, but relevant - the documentation for `mine.update` provides no information on return values which is why I cannot suggest if the behaviour is right or wrong. In fact return values don't appear to be documented in any great detail for most Salt modules.

### Versions Report
```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

**Comment by Ch3LL** [comment]
@oliver-dungey let me explain what `__salt__` does to help understanding as to why you are getting `<function update at 0x243a668>` instead of a useful error. This is actually a pythonic error and not related to salt. 

`__salt__` is just a dictionary of all the modules available to you with a reference to that module. So to show you a small example of test.ping. The salt loader does a lot of this but I can show you a manual example:

```
>>> __salt__ = {'test.ping': salt.modules.test.ping}
>>> __salt__['test.ping']
<function ping at 0x7f9e6a21e578>
>>> __salt__['test.ping']()
True
```

So that error is actually correct. Its telling you the value of `test.ping` being that its a reference to that module. Now when you add the `()` that is just a normal python way to call a funciton. such as `salt.modules.test.ping()`. 

I hope that clears up why you are runing into that error and not sure how we woud handle a better error return, because it would not be the module returning anything useful. It returns exactly what you told it to return the value of `test.ping`. 

Now to talk about your issue about the docs not including expected returns of  a module. I think its  agreat idea to improve our documetnation but since this is a different issue would you mind opening another issue with exact details of what you would ideally expect in the docs to appropriately show returns of commands and we can use that issue to track the documentation issue. Thanks

**Comment by oliver-dungey** [comment]
@Ch3LL that all makes a lot of sense and is really helpful. In learning Salt I have been remiss and not taken enough time to learn Python properly (coding by stackoverflow has its weaknesses). Thanks for taking the time to write up an explanation.

I will raise another suitable ticket for documenting return values.

**Comment by Ch3LL** [comment]
Glad I could help and my explanation makes sense :)
