### ISSUE TITLE
On Carbon and develop branches Executing a pkg state on Windows causes a pkg repo refresh EVERY time.

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#36088]
### Description of Issue/Question
Executing a pkg state on Windows causes a pkg repo refresh EVERY time. This causes states to be very slow unnecessarily.

### Setup
install Salt from Carbon or Develop branch on Windows.

### Steps to Reproduce Issue
Execute a salt pkg state like this:

```
salt davewintest state.single pkg.installed name=filezilla
```

This was introduced by this PR:  https://github.com/saltstack/salt/pull/35899

**Comment by damon-atkins** [comment]
"This was introduced by this PR: #35899"  **this is not correct**.   Its been in existence for a long time and is on all platforms not just windows.    Other non-windows platforms are smarter at doing a refresh

In fact #35899 added code to allow a minimum time between refresh and warn if a refresh happens with 1 minute, so you can see if the issue is happening. i.e. you will see
`2016-09-07 11:58:30 [salt.loaded.int.module.win_pkg][WARNING ] pkg meta db less than a minute old and been asked to refresh it`

The code is in state/pkg.py which does the refresh  #35899 only change two lines associated with the name space
i.e.
```
-    from salt.modules.win_pkg import _get_local_repo_dir		
-    _get_local_repo_dir = _namespaced_function(_get_local_repo_dir, globals())
```

**Comment by morganwillcock** [comment]
How many sls files are we talking about here?

**Comment by damon-atkins** [comment]
The title should be
pkg state on all platforms causes a pkg repo refresh per individual run of installed or latest.

The look at why this code has existed since version 0.11     it hurts windows the most because its the lowest, but it would also hurt OS with slow connections to a repo

**Comment by damon-atkins** [comment]
@morganwillcock if you use the sls files from https://github.com/saltstack/salt-winrepo-ng  thats about 200 odd files. which are re-fetch every time you do a pkg.refresh_db    due to a lack of smart sync function.

**Comment by UtahDave** [comment]
This issue is better described in #36133 so I'm going to close this issue.
