### ISSUE TITLE
salt-minion fails to start on ubuntu 15.10

### ISSUE THREAD

**Issue by EvaSDK** [saltstack/salt#36229]
### Setup

Using `deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/2016.3 trusty main` in source.list, it seems like 2015.8 at least is affected as well.
### Steps to Reproduce Issue

Add saltstack repository to system, `apt-get update`, `apt-get install salt-minion=2016.3.3+ds-1 salt-common=2016.3.3+ds-1`.
Upgrade fails because daemon fails to start with a timeout:

```
sept. 12 15:50:35 localhost systemd[1]: Starting The Salt Minion...
-- Subject: Unit salt-minion.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit salt-minion.service has begun starting up.
sept. 12 15:50:35 localhost salt-minion[11697]: [INFO    ] Setting up the Salt Minion "localhost"
sept. 12 15:50:35 localhost salt-minion[11697]: [WARNING ] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
sept. 12 15:50:35 localhost salt-minion[11697]: [INFO    ] The Salt Minion is starting up
sept. 12 15:50:35 localhost salt-minion[11697]: [INFO    ] Minion is starting as user 'root'
sept. 12 15:50:35 localhost salt-minion[11697]: [INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_87d412bbb7_pub.ipc
sept. 12 15:50:35 localhost salt-minion[11697]: [INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_87d412bbb7_pull.ipc
sept. 12 15:50:36 localhost salt-minion[11697]: [INFO    ] Executing command ['date', '+%z'] in directory '/root'
sept. 12 15:50:36 localhost salt-minion[11697]: [INFO    ] Updating job settings for scheduled job: __mine_interval
sept. 12 15:50:36 localhost salt-minion[11697]: [INFO    ] Minion is ready to receive requests!
sept. 12 15:50:37 localhost salt-minion[11697]: [INFO    ] Running scheduled job: __mine_interval
sept. 12 15:52:05 localhost systemd[1]: salt-minion.service: Start operation timed out. Terminating.
sept. 12 15:52:05 localhost systemd[1]: Failed to start The Salt Minion.
-- Subject: Unit salt-minion.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit salt-minion.service has failed.
-- 
-- The result is failed.
sept. 12 15:52:05 localhost systemd[1]: salt-minion.service: Unit entered failed state.
sept. 12 15:52:05 localhost systemd[1]: salt-minion.service: Failed with result 'timeout'.
sept. 12 15:52:05 localhost salt-minion[11697]: [INFO    ] The Salt Minion is shut down
sept. 12 15:52:05 localhost salt-minion[11697]: [ERROR   ] 0
sept. 12 16:00:38 localhost systemd[1]: Reloading.
sept. 12 16:00:38 localhost systemd[1]: Stopped The Salt Minion.
-- Subject: Unit salt-minion.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit salt-minion.service has finished shutting down.

```
### Versions Report

```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Oct 14 2015, 16:09:02)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 15.10 wily
        machine: x86_64
        release: 4.2.0-42-generic
         system: Linux
        version: Ubuntu 15.10 wily
```

**Comment by EvaSDK** [comment]
Note that I was previously running Ubuntu's 2015.3 package previously and it worked just fine.
It appears systemd unit file changed from `type=simple` to `type=notify`. I am guessing `type=notify` feature works by using `python-systemd` package however the system has `python3-systemd` installed and the python2 compatible version is nowhere to be found in salstack's ubuntu repository while it is present in saltstack's debian one.

salt-minion is running with python2, not with python3 so it cannot work.

Also, debian's `salt-common` pulls `python-systemd` package while ubuntu's does not (saltstack repositories).

In the end, changing the unit to `type=simple` makes it work again but the proper fix is probably to just build `python-systemd` for ubuntu in saltstack repository and depend on it.

**Comment by Ch3LL** [comment]
ping @dmurphy18 can I get your input here on this issue? I know we do not have official ubuntu15 packages but what do you think about building python-systemd for ubuntu in general?

**Comment by dmurphy18** [comment]
@EvaSDK @Ch3LL SaltStack supports systemd with Ubuntu 16.04 and the control file used to built Salt 2016.3.3 reflects that. The control file for Ubuntu 12.04 and 14.04 does not have a dependency on python-systemd since systemd is not available on those versions of the OS.  On Ubuntu 16.04 python-systemd is available from xenial/universe packages, hence we have no need to build it since it is already available, and I do not think we shall build a one-off python-systemd for a version of Ubuntu which is not LTS, esp. since we do not build for non-LTS.

My suggestion would be to try the version of python-systemd from either Ubuntu 16.04 or Debian 8 (latest) since it currently has python-systemd too, and both systems use systemd, recommend trying Debian 8 version first.  The only difference between the versions of Salt for Ubuntu 14.04 and 16.04 is that the version for 16.04 has a dependency on python-systemd.  

If successful using a version of python-systemd from either Ubuntu 16.04 or Debian 8, you could then try the Ubuntu 16.04 version of Salt 2016.3.3 since it has the dependency for python-systemd.

**Comment by EvaSDK** [comment]
Like I said, debian 8 package works fine, it has all needed dependencies. I use the Ubuntu 14.04 package on Ubuntu 15.10 and this had not the proper dependencies even though the system is using systemd already.

One question comes to mind is why do I have these units installed to begin with. Maybe the previous Ubuntu salt package left them behind.

I'll give a shot at using 16.04 package on 15.10 to see if it would be a valid workaround for other users but I am afraid of what it may try to pull as dependencies.

**Comment by dmurphy18** [comment]
@EvaSDK The packages are built with everything there for convenience of building, in the next point release I shall remove the service unit files for systemd and alter the install files for Ubuntu 12.04 and 14.04 since they are causing issues on releases later than 14.04.  I had not expected them to do so, but I don't test on 15.10. I had on 15.04, but time is short and rather than test on 15.10. I thought better to build and test on the 16.04 beta (it was available when time came available)

Glad to hear Debian 8 works for you.  Having a working system, I would only try Ubuntu 16.04 as an academic exercise knowing that it could cause issues.

**Comment by dmurphy18** [comment]
@EvaSDK Salt 2016.3.4 and Salt 2016.11.0 are now released.  I would like to close this issue unless you have any objections or remaining issues

**Comment by EvaSDK** [comment]
Late feedback, I started migrating my ubuntu installations to LTS since I couldn't find kernel updates to recent kernel vulnerabilities so the issue became moot to me. Thanks for your time and explanations.
