### ISSUE TITLE
Feature request: vmware driver

### ISSUE THREAD

**Issue by ikkaro** [saltstack/salt#36256]
### Description of Issue/Question

Is really interesting to reconfigure some VM parameters in a vsphere environment in powered in virtual machines, for instance:
- Add a disk to a deployed VM
- Add a network card to a deployed VM
- Change the portgroup on a running VM.
- Take/remove an snapshot.
- Modify the VM resource limits, memory, cpu and iops.
- Add memory and CPU. 
### Setup

N/A
### Steps to Reproduce Issue

N/A
### Versions Report

N/A

**Comment by Ch3LL** [comment]
@ikkaro just to make sure do the commands in the cloud module [here]*https://docs.saltstack.com/en/2015.8/ref/modules/all/salt.modules.cloud.html#module-salt.modules.cloud) work when running against vsphere?

Either way I'll approve this as a feature request because even if this cloud module works for volumes/network management it seems there is missing features compared to what you requested.

**Comment by ikkaro** [comment]
@Ch3LL, maybe using the cloud execution modules is hard because vsphere is different that a public cloud providers.  By the way I've executed some commands (cloud.volume_list, cloud.virtual_interface_list, cloud.network_list) and are not working in vsphere.

**Comment by Ch3LL** [comment]
agreed. thanks for trying that! I really appreciate it. Agreed we need to put this in its own execution module

**Comment by cetanu** [comment]
There's a bunch of code in salt/cloud/clouds/vmware.py that are used to modify existing devices, maybe it's worth having a dig around there to see what can be re-used for this.
