### ISSUE TITLE
Eauth permissions fail with subset

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#36349]
### Description of Issue

eauth grain level permissions fail with --subset
### Setup

```
external_auth:
  pam:
    tcowan:
      - 'G@roles:myapp':
        - test.*
```
### Steps to Reproduce Issue

When running without subset everything works.

```
[root@localhost salt]# salt -a pam -G 'roles:myapp' test.ping
username: tcowan
password: 
centos7-2:
    True
192.168.200.248:
    True
```

When I use --subset I get an authorization error

```
[root@localhost salt]# salt -a pam -G 'roles:myapp' --subset=1 test.ping
username: tcowan
password: 
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12 (default, Aug  9 2016, 15:48:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist: fedora 24 Twenty Four
        machine: x86_64
        release: 4.6.6-300.fc24.x86_64
         system: Linux
        version: Fedora 24 Twenty Four
```

**Comment by gtmanfred** [comment]
Thanks for the report @deuscapturus !

I have been able to replicate this issue.

root@salt:~# salt -a pam \* test.ping
username: daniel
password:
salt.c.gtmanfred-1263.internal:
    True
root@salt:~# salt -a pam --subset 1 \* test.ping
username: daniel
password:
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
root@salt:~# salt -a pam --subset 1 \* test.ping -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/conf.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/conf.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.c.gtmanfred-1263.internal
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/conf.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/conf.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.c.gtmanfred-1263.internal
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded pam.auth
username: daniel
password:
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt.c.gtmanfred-1263.internal_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded nested.output
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

**Comment by deuscapturus** [comment]
I've confirmed that this issue is resolved in version ``2016.11.1``

**Comment by deuscapturus** [comment]
I don't have this problem on one salt-master.  But when I create a new salt-master running 2016.11.1 I see this issue again.

I don't know what's special about the master that doesn't have this issue.  Here is it's versions-report
````
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by deuscapturus** [comment]
I found the reason some Salt masters work and some don't

Permissions that are module specific will fail with --subset
```
external_auth:
  pam:
    tcowan:
      - test.*
```

Permissions that are NOT module specific work
```
external_auth:
  pam:
    tcowan:
      - .*
```
