### ISSUE TITLE
cp module questions:

### ISSUE THREAD

**Issue by lkx007** [saltstack/salt#36499]
About cp get_files:

I want to know whether I can use
    salt '*" cp.get_file /root/test.py /tmp/test.py
instead of as follows;
    salt '*" cp.get_file salt:///root/test.py /tmp/test.py
when I want to send /root/test.py to minions ??

About cp push:
when I execute the following command:
    salt 'worker' cp.push /root/show.py upload_path=/root/show.py
I can get file from worker to 
   /var/cache/salt/master/minions/worker/files/root/show.py
but how can I get file from worker to 
 /root/show.py

Thanks a lot.

**Comment by terminalmage** [comment]
You cannot use a ``salt://`` URL to access any file on the master, that would be a horrible security liability.

What you need is [minionfs](https://docs.saltstack.com/en/latest/topics/tutorials/minionfs.html). The docs there are a bit sparse, and new functionality has been added since that walkthrough was written. You should also check [this section](https://docs.saltstack.com/en/latest/ref/configuration/master.html#minion-minionfs-remote-file-server-backend) of the master configuration file docs, which show all of the configuration parameters available to minionfs.

**Comment by terminalmage** [comment]
I took the opportunity today to improve the minionfs documentation, see [this pull request](https://github.com/saltstack/salt/pull/36519).

**Comment by rallytime** [comment]
Hi @lkx007 - Thank you for the question. Do the comments from @terminalmage, as well as his additions to the documentation, clear up this issue to your satisfaction?

**Comment by lkx007** [comment]
The comments from terminalmage helps a lot. I can't thank you any more!!@rallytime,@terminalmage

**Comment by rallytime** [comment]
Awesome! Glad to hear it @lkx007!

**Comment by terminalmage** [comment]
@lkx007 Thanks for helping us by opening this issue, it helped us to get the documentation improved.
