### ISSUE TITLE
startup_states: highstate creates race condition, blocks dpkg

### ISSUE THREAD

**Issue by aronneagu** [saltstack/salt#36599]
### Description of Issue/Question

We are using salt to drive the provisioning of aws ec2 instances. We are using salt-cloud to provision the instance (install salt-minion) and we have noticed that the pkg.install or pkg.latest states would fail with the following error message:

```
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```

It was never the same packages that would fail, but some of them would definitely fail. Running state.highstate from the master would succeed.

The configuration on the minion includes the directive

```
startup_states: highstate
```

so that when the minion starts, it runs highstate by itself. I have traced the problem in the salt-bootstrap.sh script. Briefly, it installs the salt minion, and Ubuntu starts the service automatically, so salt-minion checks the configuration file, sees startup_state: highstate, so it executes highstate (as a separate process). Then salt-bootstrap.sh restarts the salt-minion (the parent process only, and not the one running the highstate), so it reads the configuration file and starts another job running highstate.
Now, there are two prcesses running highstate, so when one is doing pkg.update or pkg.install it is blocking dpkg process, so the other process running highstate would fail when needing to use dpkg.

We are using a python script to run salt-cloud "ec2_autoscale_launh: {runner.cloud.create: vm_list}"
I would like to achieve running a highstate on the minion successfully.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
The relevant section in the log of the minion

```
2016-09-21 12:21:48,428 [salt.cli.daemons ][INFO    ][11171] The Salt Minion is starting up
2016-09-21 12:21:58,743 [salt.utils.parsers][WARNING ][11171] Minion received a SIGTERM. Exiting.
2016-09-21 12:21:59,050 [salt.cli.daemons ][INFO    ][12417] The Salt Minion is starting up
2016-09-21 12:21:59,244 [salt.minion      ][INFO    ][12417] Executing command state.highstate with jid req
```

Relevant output from the debug mode when running salt-cloud

```
Configuration file '/etc/salt/minion'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using current old file as you requested.
salt-minion start/running, process 11171
Processing triggers for libc-bin (2.19-0ubuntu6.3) ...
Processing triggers for ureadahead (0.100.0-16) ...
 *  INFO: Running install_ubuntu_stable_post()
 *  INFO: Running install_ubuntu_check_services()
 *  INFO: Running install_ubuntu_restart_daemons()
salt-minion stop/waiting
salt-minion start/running, process 12417
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@aronneagu this is definitely a peculiar situation because as you stated the minion is doing exactly as you told it to run highstate on startup of the minion. I'm guessing the reason when the bootstrap restarts the minion again that its not killing the process because its probably using salt-call which does not require a minion daemon and can run by itself.

ping @rallytime do you have any ideas on this one? I'm not sure whether this would be a fix on startup_states or the bootstrap? 

Also @aronneagu another solution to running states when creating a VM is implementing a reactor as documented [here](https://docs.saltstack.com/en/latest/topics/cloud/reactor.html) and you shouldn't run into the same issues if reacting off certain events.

**Comment by rallytime** [comment]
@aronneagu I am curious if this was working for you before 2016.3.3, or if this is something new you're trying to do.

**Comment by aronneagu** [comment]
@Ch3LL, I am aware of the alternative to using reactor events to trigger highstate, but as of now this doesn't work in 2016.3.3, but a fix has been provided and will be released in 2013.3.4 [(issue here)](https://github.com/saltstack/salt/issues/36600). When 2016.3.4 will be released I am planning to use this alternative to trigger the highstate.
This could be solved if the bootstrap, when running the install_ubuntu_restart_daemons function, to restart not just the daemon but also all processes started by the main minion process. I am not sure what the side-effects could be though
Another possible solution would be to pass somehow the argument -X to bootstrap script so it won't restart the minion and prevent running the second highstate. But I am using only a cloud provider file, and I have seen that the -X argument can be passed only via the cloud profile 

@rallytime We have had this mechanism in place but not working since several releases, at least as far as 2015.8, but I was able to determine the cause only now. I honestly don't remember if it was working at any point in time or not

**Comment by rallytime** [comment]
> Another possible solution would be to pass somehow the argument -X to bootstrap script so it won't restart the minion and prevent running the second highstate. But I am using only a cloud provider file, and I have seen that the -X argument can be passed only via the cloud profile

You should be able to pass `script_args: -X` via your cloud provider file (though that will be used in any VM you create via salt-cloud). Have you tried adding that option? What command/method are you using to spin up your EC2 vms if you're not using a profile?

**Comment by aronneagu** [comment]
In my config file I have
```
reactor:
  - 'salt/netapi/hook/ec2/autoscale':
    - '/srv/reactor/ec2-autoscale.sls'
```
And the ec2-autoscale.sls is from https://github.com/saltstack-formulas/ec2-autoscale-reactor
Which on line 95-99 has the following code to invoke salt-cloud
```
 ret = {
            'ec2_autoscale_launch': {
                'runner.cloud.create': vm_list
            }
        }
```
As mentioned before, this script is using using only cloud providers, and no cloud profiles.
the vm_ variable has the following key {'provider': 'eu-west-app-api'} (just one example), so this is how runner.cloud.create knows which provider to use

I have tried passing "script_args: -X" in a provider file but it didn't work. Are you sure it's supposed to work from provider files? I tried putting it in the profile and from there it worked.

**Comment by thetoolsmith** [comment]
I have been seeing this same effect but in a slightly different scenario throughout many versions of salt-cloud. I have developed a workaround for my situation, but I don't believe this startup_state race condition/process locking is limited to just running highstate and/or dpkg or other modules.
I think it goes far beyond that.

Sorry for the long thread, but I want to put it all in context. 

I have orchestration automation around the process of AWS vm provisioning (using salt-cloud) as post provisioning tasks (orchestrate states, states etc...) Most of this orchestration is implemented within salt-runners.
When the orchestration if kicked off, it generates cloud provider.conf, profile.conf and map file for whatever it is that we fed into it to build. After the cloud conf file are generated with statup_states and other config, we invoke salt-cloud (in the same runner process). 
Salt-cloud does it's thing with AWS vm's and when returned back to the runner, we need to run post provision orchestration state. The post provision orchestration state (using salt orchestrate module), 
sequentially runs through a bunch of tasks many of which target minions and run additional states. 

This NEVER works when using startup_states. 
The orchestrate states execute fine on the master, but when invoking states on the targeted minions, it never executes properly. 

This is an example of when the exception is:
----------
          ID: common postsetup orchestration
    Function: salt.state
      Result: False
     Comment: Run failed on minions: machine.domain.com
              Failures:
                  machine.domain.com:
                      Data failed to compile:
                  ----------
                      The function "state.sls" is running as PID 10089 and was started at  with jid req
     Started: 13:59:55.563543
    Duration: 337.337 ms
     Changes:
 
It doesn't matter what actions (salt modules etc...) are used in the state that should be applied to the targeted minions. The result is always the same. 
I have written these state is many ways using jinja, calling execution modules directly etc.. It doesn't change the outcome.
If i run the orchestrate state after the runner completes and exits, it work like a champ! all minions side states get applied properly.

I developed the following workaround a while back and it is the only way I can get this to work without invoking another salt command after the provisioning/orchestration runner completes and exits.

Since we have automation around the entire process (i.e. orchestration), I am able to "flag" the automation so that when it's building vm's that have startup_states configured, the automation will simply store this as a "delayed state". I.E. we remove the startup_state list from each vm we are creating, hold it in a map object (vm:states to run) in the runner automation code, so that when salt-cloud is done and handle is passed back to the runner, we can then iterate over the list object and apply the states that each new vm was intended to receive.

Once the states (that were supposed to be startup_states) are complete, we are still in the initial runner process, and the automation then executes the orchestrate state which in turn does some other state apply to the targeted minions. Seem complicated, but it has worked for a long time without a problem.
The reason we need to use post orchestrate state to apply additional states to newly build minions is because we use jinja and many of these states take dynamic pillar as parameters. This requirement prevents us from simply adding the post setup states to the initial startup_state list and avoiding the orchestrate state altogether. 

I know this solution would not work for every case, especially when there is a need to do some network level stuff right when the new vm comes online. But it does provide a way around the problem which seem to be salt-cloud executing startup_states prevents any other minion state from running until the parent process that invoked salt-cloud exits entirely due to minion salt process locking.
