### ISSUE TITLE
letsencrypt client renamed certbot

### ISSUE THREAD

**Issue by kyrias** [saltstack/salt#36638]
### Description of Issue

The old letsencrypt client was renamed certbot a couple of months ago, but the acme module still uses the `letsencrypt-auto` script.  Should it be updated to just support the new versions, or do we want to support the old versions as well still?  I'd much prefer doing the former.

**Comment by Ch3LL** [comment]
@kyrias we always try to support backwards compatibility as described [here](https://docs.saltstack.com/en/latest/topics/development/deprecations.html#deprecating-code) in our docs. If there is good reason for not setting up backwards compatibility then that change still needs to be put onto a deprecation timeline where you would warn the user with enough time that this feature will be removed. I think in this particular situation though we should keep the ability to use either the certbot or old letsencrypt client because I do not see a situation where it should not be supported in case people are using the older client. I will keep this issue open to track adding the certbot client as well to the module. Thanks!

**Comment by vodik** [comment]
There's no reason the old version can't stay supported. They just renamed the command to `certbot`, its completely a drop in replacement for the old command.
