### ISSUE TITLE
disk.usage and disk.percent on broken NFS

### ISSUE THREAD

**Issue by remyd1** [saltstack/salt#36683]
### Description of Issue/Question

disk.usage and disk.percent do not work correctly if there is any NFS error on client side.

### Steps to Reproduce Issue
NFS file handle on client side cause disk.percent and disk.usage to fail on 'isdigit' condition inside the disk module.

### Versions Report

>                   Salt: 2015.5.3
>                 Python: 2.7.3 (default, Jun 22 2016, 03:14:32)
>                 Jinja2: 2.6
>               M2Crypto: 0.21.1
>         msgpack-python: 0.4.7
>           msgpack-pure: Not Installed
>               pycrypto: 2.6
>                libnacl: Not Installed
>                 PyYAML: 3.10
>                  ioflo: Not Installed
>                  PyZMQ: 15.2.0
>                   RAET: Not Installed
>                    ZMQ: 4.1.2
>                   Mako: Not Installed
>                Tornado: Not Installed
>  Debian source package: 2015.5.3+ds-1~bpo70+2

But it seems to appear on every releases (at least for percent method).

### Workaround

Have a NFS client which is working correctly. On the salt-minion code, it should be updated like it is in the usage method on the last version of that file, that is to say :

```python
        while len(comps) >= 2 and not comps[1].isdigit():
            comps[0] = '{0} {1}'.format(comps[0], comps[1])
            comps.pop(1)
        if len(comps) < 2:
            continue
```

**Comment by damon-atkins** [comment]
NFS Client need to talk to the NFS server to find out about disk space. 
Depending how the NFS filesystems is mounted, the thread or process could get stalled until the NFS server comes back.

**Comment by remyd1** [comment]
I know, but then a "try/catch/else" in the code would be a better solution.

**Comment by damon-atkins** [comment]
No try/catch/else would not help.

The process which access the information will hung,  if a hard mount is used i.e. never give up.   If a soft mount is used, it should return with an I/O error.

Under a hard mount if salt runs df, then df will hung in the kernel and salt will wait forever.  If salt has a timeout on the df, you will end up with lots of df running on the systems all hung.  

The best thing to do is ignore remote mounts, at least by default. And also cdrom drivers, usb sticks etc.

These days I mount NFS file systems with a soft mount, as I prefer to get the I/O and have the application fallover rather than wait for the NFS mount to be alive again.

**Comment by remyd1** [comment]
Ok, then I close this issue. 

In fact, I had a script which is running disk.percent every day and I had some errors whith some clients (the NFS file handle...). I thought that a timeout would be a good idea, but it depends hugely on the network and the device...
