### ISSUE TITLE
KeyError: 'name' in salt.state.event

### ISSUE THREAD

**Issue by sebastian-philipp** [saltstack/salt#36687]
### Description of Issue/Question

While running the first stage of [DeepSea](https://github.com/SUSE/DeepSea#steps), I'm getting this stack trace:

```
The minion function caused an exception: Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1320, in _thread_return
    return_data = executor.execute()
File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 942, in sls
    ret = st_.state.call_high(high_)
File "/usr/lib/python2.7/site-packages/salt/state.py", line 2276, in call_high
    ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
File "/usr/lib/python2.7/site-packages/salt/state.py", line 1799, in call_chunks
    running = self.call_chunk(low, running, chunks)
File "/usr/lib/python2.7/site-packages/salt/state.py", line 2163, in call_chunk
    self.event(running[tag], len(chunks), fire_event=low.get('fire_event'))
File "/usr/lib/python2.7/site-packages/salt/state.py", line 1955, in event
    [self.jid, self.opts['id'], str(chunk_ret['name'])], 'state_result'
KeyError: 'name'
```
### Setup

Download and install https://github.com/SUSE/DeepSea then run

```
admin:~ # salt-run state.orch ceph.stage.prep
```
### Steps to Reproduce Issue

Last time, I enabled debug logging, this issue vanished unfortunately.
### Versions Report

```
admin:~ # salt --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.22.0
         Python: 2.7.12 (default, Jul 01 2016, 15:34:22) [GCC]
   python-gnupg: 0.3.7
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2

System Versions:
           dist: SuSE 42.1 x86_64
        machine: x86_64
        release: 4.1.15-8-default
         system: Linux
        version: openSUSE  42.1 x86_64
```

**Comment by wolfpackmars2** [comment]
Looks like a bug in DeepSea. Looking at the SLS you are calling in Step 0 ([prep.sls](https://github.com/SUSE/DeepSea/blob/master/srv/salt/ceph/stage/prep.sls)), there is a state:
`validate failed:
  salt.state:
    - name: just.exit
    - tgt: {{ salt['pillar.get']('master_minion') }}
    - failhard: True
    - order: 1
`

I believe '- name:' should be '- sls:'

This should probably be reported to the DeepSea project - doesn't appear to be a Salt issue.

**Comment by sebastian-philipp** [comment]
Thanks for the quick answer. Unfortunately, this was not the case, as changing `- name` to `- sls` didn't fixed the issue. Also, disabling the whole yaml block didn't changed the exception.

**Comment by sebastian-philipp** [comment]
I just printed `chuck_ret` into the logfile: 
```
{'comment': 'One or more requisite failed: ceph.updates.default.zypper update', '__run_num__': 1, '__sls__': u'ceph.updates.default', 'changes': {}, 'result': False}
```
Very strage.

**Comment by Ch3LL** [comment]
Just to confirm when chaning name to sls did you form it as a list as such:

```
install_nginx:
  salt.state:
    - tgt: 'web*'
    - sls:
      - nginx
```

**Comment by wolfpackmars2** [comment]
With the additional information, that leads us to the file [/ceph/updates/default.sls](https://github.com/SUSE/DeepSea/blob/master/srv/salt/ceph/updates/default.sls)

I'm not familiar with Suse or zypper, but it seems to be a package manager similar to yum and apt. There may be two issues here.

The first one is that the command specified in ceph.updates.default failed, and it appears to have failed because the local package database was out of date. You resolved this by updating the packages (zypper refresh). I'm curious, if you manually run zypper refresh the run stage 0, does it complete as expected? The first problem is likely with DeepSea. If a zypper refresh is required, then DeepSea should add that to their states. Also, Salt has a [Zypper module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.zypper.html). This might be a better way for DeepSea to manage zypper packages - I say might because I don't know enough about Suse/Zypper/DeepSea to confidently give advice on how they should do things :)

The second problem might be with Salt - and that is related to how Salt handles the failure of the cmd.run that was passed to it. However, if zypper is run with --non-interactive, and then an error occurs and zypper pauses for user response, then that to me is a failure of zypper. I'm not sure what kind of response Salt would receive in this case, and how it would react. Maybe using the zypper module of Salt would account for this, versus using cmd.run.

I'm curious what the more knowledgeable (than me) people at DeepSea think about this.

Thanks for the additional information, it has really shed some light on this.

Regarding Salt, what concerns me is that Salt through an exception when it seems like it should simply reported that a state failed. But personal experience has shown me that Salt will usually throw an exception for many things, including errors in the sls files when the SLS files can't be compiled.

**Comment by sebastian-philipp** [comment]
Ya. This seems to be a problem in the zypper module of salt. Not salt itself.
