### ISSUE TITLE
Feature Request: throttle back or disable hyperactive minions

### ISSUE THREAD

**Issue by hightekvagabond** [saltstack/salt#36711]
We recently ended up in a situation where one of our engineers installed a very old version of salt-minion which caused it to not recognize the "special" attribute in cron.present and put a highstate in cron as all asterisks.

The result was a minion that was rapid firing highstates to our master as much as it possibly could. The answer I kept getting in the logs was to add more worker_threads and before I finally diagnosed the problem I got up to 256 worker_threads.

I would like to request that as a hardening factor the salt master should have some sort of defensive mechanism that watches for a minion who might DOS the salt-master by asking for too much work too fast over and over.
### Steps to Reproduce Issue

Create a minion with version: salt-call 2015.5.3 (Lithium)
Create a master with version: salt-call 2016.3.3 (Boron)
create a state that uses the cron.present module to call a startup.sh that has a highstate inside the startup.sh on special: '@reboot'

Here is my old startup.sh which I have now removed (note there is a lot of extra crap in here like clearing the cache manually because I was still trouble shooting the issue and that was part of it):
# !/bin/bash
# stop the salt minion before we clear the cache

/usr/sbin/service salt-minion stop
# clear the salt minion cache

/bin/rm -rf  /var/cache/salt/minion/files/base/*
# restart the minion

/usr/sbin/service salt-minion start
# resync the cache

/usr/bin/salt-call saltutil.sync_all
# make sure everything is in standard working order

/usr/bin/salt-call state.highstate

{last 3 lines removed because they are specific to our application}
### Versions Report

Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-92-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
This seems like an interesting idea, but I'm not sure how we would implement this. ping @cachedout do you think this is something we would want and can implement into salt? I think its a great idea but not sure how we would handle this and wanted to make sure its something we wanted to add before approving. Thanks

**Comment by onorua** [comment]
AFAIK, 0mq which is default transport used by Salt, has only client side rate limit, which will not help with outdated client problem. When you parse msgpack - you have no clue where this message came from, so in order to actually make smart decision about this acting up node, you must parse each and every message which set whole idea of rate limiting under question. 
It is possible to implement rate limiting on client side, but as I said - it will not help you in the problem. 
The problem has the same roots as https://github.com/saltstack/salt/issues/36584 ticket.

**Comment by cro** [comment]
I wonder if a better solution might be to implement version checks that would restrict minions that are too far away from the current master version to a limited set of commands (enough only to self-upgrade the minion).

**Comment by cachedout** [comment]
If we were to do this, I would want to do it as request-tracking by minion ID on the `ReqServer` side. As @onorua points out, we have to unpack and decrypt the message to learn whom it is from. The good news, however, is that this operation is light compared to what would really harm a master in a situation like this, which would be the work performed by the `MWorker` processes.

I'd be hesitant to call this "hardening" since it would be trivial to defeat by simply faking random minion IDs and then flooding the server with auth requests. Though, to be honest, at that point I tend to feel like rate-limiting is a job best left to IP filters on operating system.

Thoughts?
