### ISSUE TITLE
salt-cloud vmware - fails to ssh to guest during provisioning

### ISSUE THREAD

**Issue by ndobbs** [saltstack/salt#36822]
### Description of Issue/Question

salt-cloud vmware provider cannot ssh to machines after provisioning. I have a ESX6 lab running `VMware vCenter Server 6.0.0 build-3634794`, my whole provisioning process seems to be running great, aside from salt not able to ssh into the guest during provisioning. Subsequently salt-minion doesn't get installed // started on the guest. 
### Setup

VMWare ESXi 6 hosts with I have a ESX6 lab running `VMware vCenter Server 6.0.0 build-3634794`.
### Steps to Reproduce Issue

First I have ensured that I have running the correct version of pyVnomi since my system is python sub-2.7. The machine eventually finishes its launch with all of the proper parameters I'd expect, however without a running salt-minion process. I can also directly authenticate to the host once its online with the exact copied credentials I have in my profile.

--- COMMAND ---
`salt-cloud -p vmware test-host`

---OUTPUT---

```
Permission denied (publickey,password).
[DEBUG   ] Permission denied (publickey,password).
[DEBUG   ] Using password authentication
[DEBUG   ] Attempting to authenticate as salt-cloud (try 13 of 15)
[DEBUG   ] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oConnectTimeout=15 -p 22 salt-cloud@10.90.90.41 date'
[DEBUG   ] Child Forked! PID: 1098  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oConnectTimeout=15 -p 22 salt-cloud@10.90.90.41 date
close failed in file object destructor:
[DEBUG   ] close failed in file object destructor:
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IOError: [Errno 9] Bad file descriptor
IOError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 862, in emit
    stream.write(ufs % msg)
  File "/usr/lib/python2.7/codecs.py", line 688, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 352, in write
    self.stream.write(data)
IOError: [Errno 9] Bad file descriptor
Logged from file setup.py, line 1045
IOError: [Errno 9] Bad file descriptor
[ERROR   ] Failed to start Salt on host test-provision
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

```
pip freeze |grep pyvmomi
pyvmomi==5.5.0.2014.1.1
```

`VMware vCenter Server 6.0.0 build-3634794`

**Comment by Ch3LL** [comment]
@ndobbs if you attempt to run the same ssh command as in those logs do you get the same file descriptor error?

Also are you seeing this on multiple hosts? For example if you are cloning from a template if you clone from a different os template are you seeing the same thing? Thanks

**Comment by ndobbs** [comment]
@Ch3LL I only have a single template (ubuntu1404) with vmware tools installed. When I ran the command directly I did not get the same file descriptor error however I did get output I didn't expect. I will test this fully and provide the output once I get the time to do so. It will be today. 

Thank you for your help!

**Comment by ndobbs** [comment]
@Ch3LL Thanks again for your attention. From the salt master I've executed the command and was able to receive the date string. 

```
root@master:~# ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oConnectTimeout=15 -p 22 salt-cloud@10.90.90.41 date
Warning: Permanently added '10.90.90.41' (ECDSA) to the list of known hosts.
salt-cloud@10.90.90.41's password:
Fri Oct  7 16:42:33 EDT 2016
```

**Comment by Ch3LL** [comment]
@ndobbs okay I went ahead and tried setting up a test case and I cannot replicate this issue. Salt-cloud is able to ssh and install salt in the VM. You state that you only have one vm template. Would you be willing to setup a different OS template and seeing if you still see the same error? I understand that might be too much to ask. please let me know thanks

**Comment by Ch3LL** [comment]
Would you also mind  also sharing your sanitized version of profile.d? I can attempt with the current settings  you are attempting to use. thanks

**Comment by jasonp26** [comment]
I would love to know how this turned out I have a similar issue that I am working through. I get these debug outputs after deploying a VM

`salt-cloud -P -m /etc/salt/cloud.maps.d/qa.map -l debug`

Seems to fail at the end of the process

`15 -p 22 root@172.18.102.131 date
[DEBUG   ] Warning: Permanently added '172.18.102.131' (ECDSA) to the list of known hosts.
[DEBUG   ] root@172.18.102.131's password:
[DEBUG   ] Permission denied, please try again.
[DEBUG   ] root@172.18.102.131's password:
[DEBUG   ] Permission denied, please try again.
[DEBUG   ] root@172.18.102.131's password:
[DEBUG   ] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[DEBUG   ] Using password authentication
[DEBUG   ] Attempting to authenticate as root (try 15 of 15)
[DEBUG   ] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oConnectTimeout=15 -p 22 root@172.18.102.131 date'
[DEBUG   ] Child Forked! PID: 10660  STDOUT_FD: 6  STDERR_FD: 12
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oConnectTimeout=15 -p 22 root@172.18.102.131 date
[DEBUG   ] Warning: Permanently added '172.18.102.131' (ECDSA) to the list of known hosts.
[DEBUG   ] root@172.18.102.131's password:
[DEBUG   ] Permission denied, please try again.
[DEBUG   ] root@172.18.102.131's password:
[DEBUG   ] Permission denied, please try again.
[DEBUG   ] root@172.18.102.131's password:
[DEBUG   ] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[ERROR   ] Failed to start Salt on host vfacog
[ERROR   ] Failed to create VM vfacog. Configuration value u'deploy_kwargs' needs to be set`

I feel it is an SSH issue but cannot seem to pin it down being new to Salt. Thanks in advanced.

**Comment by jasonp26** [comment]
This issue for me is now fixed. The issue was I needed to specify the SSH_Username in the Profiles file as shown here (https://github.com/saltstack/salt/issues/23416)

and looks like this:

`ssh_username: example
  password: 'SNIP'`

That got rid of my loop above and completed the build out of the vm.
