### ISSUE TITLE
[docs] comments about targetting execution still correct?

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#36906]
Are the comments in the docs about targeting with execution still correct?
https://docs.saltstack.com/en/develop/topics/targeting/#targeting-with-executions

**Comment by sjorge** [comment]
@rallytime ping, this seems like something up your ally :)

**Comment by Ch3LL** [comment]
Okay I just spoke with one of our engineers offline and he informed me that it was an idea that was never feature-complete due to security issues and due to that was actually removed from the code a long time ago, maybe even 0.17. So this feature is not included and will not be in the future so we definitely need to get this cleaned up from our docs.

Now also as a side note the closest thing to this feature would be dynamic grains which has not been implemented, where grain data is always updated automatically. For example you could target a grain that checks the status of apache service and only run commands against minions that have apache running, but this is a feature thats not even scoped at this point, but is something we would like to implement eventually. So I'll keep this issue open to track the removal of those docs.

**Comment by sjorge** [comment]
SGTM, I just bumped into this and had never heard of it.

**Comment by Ch3LL** [comment]
Yeah me neither. I had to reach out to another engineer. Thanks for bringing it to our attention so we can get it cleaned up :)

**Comment by rallytime** [comment]
I have removed these docs in #36925 for the 2015.8 branch, and in #36926 for the 2016.3 branch. (These docs were refactored in 2016.3, I made 2 PRs to make sure they are fully removed from all of the docs that are live online.)
