### ISSUE TITLE
Accessing environment variables sourced by root/.bashrc

### ISSUE THREAD

**Issue by rehmanzile** [saltstack/salt#36927]
Custom defined variables in /root/.bashrc are not accessible by pillar files.

In /root/.bashrc, I defined:

``` bash
export FOO="hello"
```

The pillar/common/init.sls file get's "None" when it tries to reference it:

``` yaml
test: {{ salt['environ.get']('FOO') }}
```

The question is how are the environment variables sources for salt-master? Do I need to modify /ets/salt/master config file to source everything in /root/.bashrc?

Purpose is to access secrets via environment variables for security.
### Versions Report

```
              Salt: 2015.5.3
            Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
            Jinja2: 2.7.2
          M2Crypto: 0.21.1
    msgpack-python: 0.3.0
      msgpack-pure: Not Installed
          pycrypto: 2.6.1
           libnacl: Not Installed
            PyYAML: 3.10
             ioflo: Not Installed
             PyZMQ: 14.0.1
              RAET: Not Installed
               ZMQ: 4.0.4
              Mako: Not Installed
           Tornado: Not Installed
```

 Debian source package: 2015.5.3+ds-1trusty1

**Comment by gtmanfred** [comment]
If you are storing them in environment variables or in a flat text file in .bashrc, is there any reason it can't be stored in /etc/salt/grains? Which is only readable by the root user, just like /root/.bashrc, but would be available through {{grains.get('FOO')}}.  Alternatively, these could be stored in pillars and sent to specified minions and only have them stored on your master, and not on each individual minion.

**Comment by buildmaster-nyansa** [comment]
How would I define FOO in /etc/salt/grains on salt master? Is it a YAML construct? Can you please point me to an example? Thanks.

**Comment by gtmanfred** [comment]
Grains is a yaml templated file that goes on the minion, https://docs.saltstack.com/en/latest/topics/grains/

for storing static data.  If you are just wanting stuff stored on the master, you should just put it in the pillar file instead of using environment to pull it.  If you still want to use environment, use the /etc/defaults/salt or /etc/sysconfig/salt file that is used in your systemd service unit or init script to put environment variables in there.  If it is systemd, you won't be able to source /root/.bashrc, but you might be able to do that with sysvinit or upstart.

**Comment by buildmaster-nyansa** [comment]
Thanks. I will try it out.
