### ISSUE TITLE
Handling of psutils in the future

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#36935]
### Description of Issue/Question

There are a lot of issues concerning psutil. Too much waste of time.

I see four conditions:
1. The matching psutil is installed (most likely via rpm/dpkg)
2. psutil is not installed
3. A too old version of psutil is installed
4. A too new version of psutil is installed
### Steps to Reproduce Issue

https://github.com/saltstack/salt/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20psutil

Here are the solutions which I see. Please provide additional solutions, if you see more.
### Solution1: Keep several try-except dances in the code

Do it like it gets done in the current code base.
### Solution2: saltpsutils

Create a new file/module which encapsulates all psutils calls. Handle the four conditions from above in one place.
### Solution3: Switch to virtualenv based setup.

Switch to a different way to install salt. Use a virtualenv. This makes it much easier to ensure that the matching version is installed.
### Solution4: Vendor psutil

Add psutil source code into the source code of salt.

**Comment by s0undt3ch** [comment]
1. We should probably focus on and enforce the second approach
2. Partially done [here](https://github.com/saltstack/salt/blob/develop/salt/utils/psutil_compat.py) we probably just have to migrate existing code to use this compat module and make sure new code additions which rely on `psutil` to use the compat module.
3. Although an interesting idea(self-contained installation), we still have compiled binary dependencies which mean creating a virtualenv at least for each architecture instead of a single **source code** tarball. 
4. No(personal opinion, other SaltStack developers might not agree) because then salt itself would include code which needs to be compiled at install time, and this is something we try to avoid at all costs.

This is just my personal opinion which hopefully gets a discussion going on how to address this issue for good

**Comment by guettli** [comment]
I was not aware that `psutil_compat.py` does exist. Thank you for your feedback.
