### ISSUE TITLE
Salt API Log File Issue (missing or documentation is incorrect)

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#37195]
### Description of Issue/Question

According to the documentation at this URL:
  https://docs.saltstack.com/en/latest/ref/cli/salt-api.html
the salt-api service should send salt-api log output to:
  /var/log/salt/api

However, this does not appear to be the case.  Log data may instead be seen in syslog output or by running the salt-api process in the foreground.
### Steps to Reproduce Issue
1. Configure and start Salt API
2. Make RESTful calls.
3. Look for log output at /var/log/salt/api (file not present)
### Versions Report

This was observed on 2016.11.0rc1, 2016.3.2, and 2015.8.3.

**Comment by Ch3LL** [comment]
@grichmond-salt looks like i'm able to replicate this. When I edited [here](https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L1481) to be: `'log_file': '/var/log/salt/api',` it started working because later on when starting up salt-api [here](https://github.com/saltstack/salt/blob/develop/salt/cli/api.py#L40) its looking for log_file not logfile.

ping @whiteinge do you think this is the correct fix?

**Comment by grichmond-salt** [comment]
Thanks for looking into this, @Ch3LL!

This suggests the main issue is that the salt-master and salt-api processes are looking at the /etc/salt/master(.d) configuration for the "log_file" setting.  The setting found for "log_file" is being used for both services, as you referenced here:
    https://github.com/saltstack/salt/blob/develop/salt/cli/api.py#L40

I'd like to ensure that the salt-master and salt-api processes have different log files...

Would it make sense to have a separate configuration option for the salt-api log file?
Perhaps something like "api_log_file" (to make it distinct)?

Thanks!

**Comment by whiteinge** [comment]
@Ch3LL yes, that sounds correct. This may be an artifact from when salt-api and Salt were separate repos.

IIRC, salt-api and Salt were intended to share the same log file since salt-api calls into Salt for almost everything so there just isn't much life in the salt-api log output. I'm fine with either approach.

(Not directly related but seealso: the `log_access_file` rest_cherrypy config option for webserver-specific logging in Carbon.)

**Comment by grichmond-salt** [comment]
@whiteinge,

Thanks for this!  Use of `log_access_file` is going to really help.

Regarding separation of salt-master and salt-api log data, I have had two engagements in the past month where this was a point of concern.  In both cases, the engineers I was working with were emphatic about wanting to separate the log files.

In the first case, a security team wanted to audit API calls separately from typical salt-master log output.  In the second case, an integration engineer wanted to monitor calls being made by the VMware VRO plugin.  Please reach out if more detail would be helpful.

If the effort is not extreme, I'd like to see us separate the salt-master and salt-api log output.  That, combined with use of Carbon's `log_access_file`, would have been the perfect answer to the scenarios described above.

**Comment by KiranGitHubM** [comment]
Hi Ch3LL/whiteinge, Can loudly echo what @grichmond-salt has suggested :). Has there been any further thought on separating logging options for master and api ?

**Comment by whiteinge** [comment]
Thanks for the bump. This has been implemented in the 2016.3 branch (#37455) and will be present in the next point-release.
