### ISSUE TITLE
Salt config files not installed

### ISSUE THREAD

**Issue by rajvidhimar** [saltstack/salt#37250]
### Description of Issue/Question

Pip install doesn't install the configuration files. The ones which are in /etc/salt. Neither the salt folder is made. 
### Setup

Git cloned salt. cd to salt. Issued the following commands:
- pip install .
- python setup.py install

These commands did not make the salt folder in /etc. While apt-get salt-master creates the salt folder and installs the config files (which only has default values but its a good reference)

I am doing this on a Macintosh.

**Comment by gtmanfred** [comment]
I think this is pretty standard for python packages.  I cannot think of any that install the configuration file, because pip does not have a sense of backup files that I am aware of, unlike rpm and dpkg.  So when you would update the package with pip, it would just overwrite your config files,which is less than desireable.

**Comment by s0undt3ch** [comment]
For a while salt wrote default configuration files if those were not present on the system on which salt was being installed. This was a procedure done when starting salt, not at install time.
I can't remember precisely, but we did hit some bumps, probably performance issues since we also made sure the files were owned by the right user(not only configuration files) and also, not all distributions expect the configuration files to be on the same path.
However, as @gtmanfred mentioned, that's commonly the job of the system package which has support for backups, etc.
Since we started making our own packages for several distributions(and we're growing the packaging support to include additional distributions as fast as possible), we also left the work to manage those kinds of things where it should be, the distribution package(because not all distributions lay down the files on the same directories).

So, while I do understand that this might have seemed like a bug, it is actually expected behaviour.
Installing from source is something we expect more experienced users to do, and those usually know how and where the configuration files reside among other things.
For someone new to salt, we expect they follow a more safe procedure and install salt from a package built for the system they are running on.

Perhaps, we could have a section explaining this expected behavior when installing from source and what to do next? Would this alleviate your issue if you were stumbling on this again?

**Comment by rajvidhimar** [comment]
I agree that installing from source is for experienced users. But installing from distribution package gives the latest release. Is there any way to install the develop code (with default config files)?Suppose I want to install the carbon branch. The reason I ask for this is because all the changes made by us goes in the develop. And we want to give that code to people (many of whom are beginners).

**Comment by gtmanfred** [comment]
If you want the config files, they need to be installed using the provided packages.

Pip does not handle backup files like those packages managers do, so it would always overwrite the files.

Until setuptools supports those, we won't be distributing and overwritting users config files.
