### ISSUE TITLE
File.line is replacing a line instead add a new one, if the content start with '-'

### ISSUE THREAD

**Issue by fcortijo** [saltstack/salt#37360]
### Description of Issue/Question
File.line is replacing a line instead add a new one, if the content start with '-' .

### Steps to Reproduce Issue
I have the state:
```
iptables_rule:
  file.line:
    - name: /tmp/test.txt
    - mode: ensure
    - content: "-A INPUT -p tcp -m state -s 1.1.1.1/32 --state NEW -m tcp --dport 10050 -j ACCEPT"
    - before: ".*--dport 22 -j ACCEPT?"
    - backup: yes
```
This's the target file before the Salt run:
----------------------------------------------------------------------------------------------------------
```
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:RH-Firewall-1-INPUT - [0:0]
-A INPUT -j RH-Firewall-1-INPUT
-A FORWARD -j RH-Firewall-1-INPUT
-A RH-Firewall-1-INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
```
----------------------------------------------------------------------------------------------------------
And this after:
----------------------------------------------------------------------------------------------------------
```
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:RH-Firewall-1-INPUT - [0:0]
-A INPUT -j RH-Firewall-1-INPUT
-A FORWARD -j RH-Firewall-1-INPUT
-A INPUT -p tcp -m state -s 1.1.1.1/32 --state NEW -m tcp --dport 10050 -j ACCEPT
-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
```
----------------------------------------------------------------------------------------------------------

The state should add a line before the ssh rule, but instead that it replaced the line ".*ESTABLISHED,RELATED.*" with the new line.
I need escape the '-' character? Thanks

### Versions Report
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-45-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I have been able to replicate this issue.

Would you mind taking a look at this?  We very much appreciate community pull requests.  Otherwise, I have tagged our platform team to take a look at this bug.

Thanks,
Daniel

**Comment by lomeroe** [comment]
This appears to be caused by the _starts_till function.

This function compares the line you want inserted (i.e. the content parameter) with the line that occurs immediately before the line that matches the before parameter.  I believe the intent is to verify that the line that occurs previous to the "before" line (form here on noted as the "previous line") is not the same as "content".  However, after performing a straight comparison, the function then splits the "content" and "previous line" into words and tests if the "previous line" starts with any portion of the "content" line (by dropping a word at a time from the content and checking "startswith").

Your "content" and "previous line" both start with "-A", which causes the match and the line to be replaced.

If you changed the mode to "insert" you'd find the "content" line would also not get inserted b/c of the same _starts_till function (it finds the "-A" starts with in the "previous line" and decides that the "content" is already there.

@isbm can you help shed some light on why you have the _starts_till function do the "startswith" comparison?
