### ISSUE TITLE
manage.safe_accept fails on TypeError: expected string or buffer

### ISSUE THREAD

**Issue by arthurzenika** [saltstack/salt#37474]
### Description of Issue/Question

```
$ salt-run manage.safe_accept host 
Exception occurred in runner manage.safe_accept: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 356, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/manage.py", line 532, in safe_accept
    if not FINGERPRINT_REGEX.match(finger):
TypeError: expected string or buffer
```

going verbose seems to show that the command on the minion side (via salt-ssh) is working : 

```
SALT_ARGV: ['/usr/bin/python2.7', '/var/tmp/.root_12c647_salt/salt-call', '--retcode-passthrough', '--local', '--metadata', '--out', 'json', '-l', 'quiet', '-c', '/var/tmp/.root_12c647_salt', '--', 'key.finger']
_edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c0[snip]
```

### Steps to Reproduce Issue
install salt-minion (via salt-ssh but I don't think that's related) and when key hasn't been accepted run salt-run manage.safe_accept host on the master.

### Versions Report
```
# salt-run --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```

**Comment by Ch3LL** [comment]
@arthurlogilab I am able to replicate this behavior. Do you know what version this was previously working on. I tried all the way back to 2015.8.8 and still saw the same behavior

**Comment by galexrt** [comment]
@Ch3LL I'm also getting this error.
The problem seems to be that because of the `root_dir` being set, the original `pki_dir` is not used causing the `return` key to be empty.

Running the `salt-call` locally without the `-c /var/tmp/.vagrant_...salt` causes it to be empty.

I'll update my comment with more info as I find it.

**Comment by galexrt** [comment]
If I copy the `/etc/salt/pki/minion` to `/var/tmp/.vagrant_...salt/running_data/etc/salt/pki/minion` (the `/var/tmp/.vagrant_...salt/running_data/etc/salt/pki/minion` has to be created because it does not exist) I the command still fails but with this patch seems to work (tried on `2018.3.2` local install, will try latest "master" version):
```
--- a/salt/runners/manage.py
+++ b/salt/runners/manage.py
@@ -625,7 +625,7 @@
 
     failures = {}
     for minion, finger in six.iteritems(ret):
-        if not FINGERPRINT_REGEX.match(finger['return']):
+        if not FINGERPRINT_REGEX.match(finger):
             failures[minion] = finger
         else:
             fingerprints = salt_key.finger(minion)
@@ -640,7 +640,7 @@
             elif pending[minion] != finger:
                 failures[minion] = ("Minion key {0} does not match the key in "
                                     "salt-key: {1}"
-                                    .format(finger['return'], pending[minion]))
+                                    .format(finger, pending[minion]))
             else:
                 subprocess.call(["salt-key", "-qya", minion])
 
```

**Comment by Ch3LL** [comment]
`The problem seems to be that because of the root_dir being set`

where are you setting this?

**Comment by galexrt** [comment]
@Ch3LL `root_dir` seems to be automatically set by `salt-ssh` in the `/var/tmp/.salt-.../minion` config file.
I have attached an asciinema recording which shows the commands/steps I'm running (I have already applied my patch to the `/usr/lib/python2.7/dist-packages/salt/runners/manage.py`, but in the recording also had to add the `hash_type` to the `salt_key.finger()` which I don't know how to get from the config right now):
[![asciicast](https://asciinema.org/a/baV58GY1Nqk2cW6pPYnZ4LX3K.png)](https://asciinema.org/a/baV58GY1Nqk2cW6pPYnZ4LX3K)

**Comment by Ch3LL** [comment]
okay I went ahead and re-created the issue again and what i notice on the intial error without your fix I notice that the finger just is not returning. I believe this is because when we call `key.finger` the function calls this: `__opts__['pki_dir']` which is going to use the salt-ssh __opts__ and not whats on the minion so what if we add the pki_dir as an argument and pass in the the appropriate path we are wanting to query from the runner?

But maybe you aren't seeing the same thing.

**Comment by galexrt** [comment]
@Ch3LL That could also just be the issue (assuming you have tried with the current `develop` branch).

I hadn't gotten around to test it with the `develop` branch but I was simply suspecting that it may still be "broken" like that in the `develop` branch as from what I saw there haven't been too many changes to that code after the `2018.3.2` release. I was just using the Saltstack getting started guide.

**Comment by remichristiaan** [comment]
Hi, any news on this bug? This problem still seems to exist with salt 2019.2.0.

- Using 'salt-call key.finger' on the minion returns the key
- Using 'salt-ssh <snip> key.finger' (from the master) returns an empty string
- Using salt-ssh where /etc/salt/pki/minion is symlinked into /var/run/.root_12a5ec_salt/running_data returns the key

**Comment by Ch3LL** [comment]
There has been no progress here due to other higher priority issues, but anyone is welcome to push a PR for a fix.

**Comment by brianthelion** [comment]
@Ch3LL You're correct about the `pki_dir`. IMHO, relying on *any* assumptions about the location of the remote `pki_dir` is asking for trouble. Only the caller knows what the salt environment looks like on the target machine, and they may have a weird setup. I think the only clean solution here is to allow `key.finger` to take a `pki_dir` argument that overrides whatever is in `__opts__`. If that's allowable, the fix is pretty simple.

A more complicated solution involves modifying the way `salt-call` is run on the remote machine. Right now, `salt-ssh` uses `<thin_dir>/salt-call --local -c <thin_dir> ...`. An alternative would be to implement some logic in the ssh client that allows it to drop the `-c` under certain conditions -- this being one of them.

**Comment by dmurphy18** [comment]
@arthurzenika Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.
