### ISSUE TITLE
boto_elb and target groups

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#37651]
A while ago AWS released a new type of load balancer, Application Load Balancer. It has the concept of target groups. Being able to modify a load balancer is a very useful feature when 1) taking a server out of a target group (as a `prereq`), 2) upgrading the application, 3) putting the server back in service in the target group (as an `onchanges`).

Does https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_elb.html support adding/removing instances to/from a target group? If not, see this as a feature request to support target groups.

**Comment by Ch3LL** [comment]
So glancing at the elb docs [here](http://boto3.readthedocs.io/en/latest/reference/services/elbv2.html#ElasticLoadBalancingv2.Client.create_target_group) it looks like thats an example of a call that would need to be added using the boto module for elasticloadbalancingv2: create_target_group, delete_target_group, etc to manage the target groups. I'm not seeing any management of target groups in the current code base under develop so I'll add this as a feature request.

**Comment by pepoluan** [comment]
Hi, I just realized that I also need this functionality (i.e., managing AWS ELB "Application" Load Balancer).

Is there any progress?

**Comment by Ch3LL** [comment]
This currently has not been assigned to an engineer. You are more then welcome to start trying to add the feature yourself as a PR

**Comment by pepoluan** [comment]
Thanks for the info!

Let me see what I can do 😙

**Comment by pepoluan** [comment]
Hmmm... the changes might be quite significant... for instance, `list_elbs` only list the "classic ELB" instances and none of the new "ALB"...

I'll probably split the functionality off into its own set of functions (and modules), e.g., `list_albs`, `create_alb`, `create_alb_targetgroup`, and so on.

What do you think?

**Comment by twellspring** [comment]
Boto3 is in use in the below module.  Would it be easier to keep  classic ELB in boto_elb and ALB in boto_elbv2?

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_elbv2.html

**Comment by twellspring** [comment]
@Ch3LL, I just started working on this.  since boto_elbv2 exists I will try to extend that to allow for the creation of an ALB and creation of target groups.   Since creating target groups is already in the boto_elbv2 module I thought creating the corresponding state should be a good first effort in writing states.  But I am finding it hard going because it appears that the existing boto_elbv2 module is not written to handle errors well.  My new state using the other states in boto_elbv2 as examples does not allow the errors from the module to get to the results on the state.   Looking at other state/module combinations and I see similar results.   Put in a case for how to do this  ( #42853 )

**Comment by twellspring** [comment]
Now working on creating/deleting ALBs and the associated items ( listeners, rules, ... )
