### ISSUE TITLE
[REST_CherryPy] Why does /login create a session cookie on unsuccessful login?

### ISSUE THREAD

**Issue by NickDubelman** [saltstack/salt#38056]
### Why does /login create a session cookie on unsuccessful login? 
I'm using salt-api and REST_CherryPy and have noticed that a session cookie is created, regardless of whether or not a login is successful. Is this the desired behavior? If so, why?

I'm on versions 2015.5.10

**Comment by whiteinge** [comment]
Two approaches are: turn it on for all endpoints then selectively disable some endpoints; or turn it off for all endpoints then selectively enable some endpoints. We've take the former approach because session cookies are lightweight. It's disabled for some endpoints where we're specifically avoiding session handling:

https://github.com/saltstack/salt/blob/723699fda9/salt/netapi/rest_cherrypy/app.py#L1746-L1748

If session support is enabled for an endpoint the CherryPy server sends a session cookie for all HTTP requests regardless of the response.
```
% curl -sSI http://localhost:8000 | grep Cookie
```

I'd say it's desirable behavior because if you get a cookie you might as well reuse that same cookie even it takes a few tries to login. Once you log in successfully the session your cookie corresponds to will be updated with an associated Salt token.
