### ISSUE TITLE
git_pillar does not detect changes to remote repository when told to update

### ISSUE THREAD

**Issue by 747project** [saltstack/salt#38162]
### Description of Issue/Question
git_pillar does not seem to refresh immediately when telling it to update. When looking in debug log, it seems as if git_pillar thinks the local repo in cache is up-to-date with remote, and that is clearly not the case. 

### Setup
1. OS: centos7
2. Install salt: 2016.11.0 (Carbon)
3. Install pygit2 via yum: version 0.21.4 appears to be latest available
4. git_pillar configged as follows in salt master config file, including config variables that are explicitly set  (i.e., uncommented and set to something that is not default value):

```
ext_pillar:
  - git:
    - develop https://<redacted>.git:
      - user: <redacted>
      - password: <redacted>
      - env: base

ext_pillar_first: True
pillar_merge_lists: False
pillar_cache: False
```

### Steps to Reproduce Issue

1. Start master, ensure it successfully can read the pillars from the external pillar repository
2. Edit, commit, and push change to the external pillar repository
3. on master, call `salt-run git_pillar.update`
4. Logs show that git_pillar thinks the local repository copy is up-to-date:

```
2016-12-08 18:33:27,537 [salt.utils.gitfs ][DEBUG   ][393] Set update lock for git_pillar remote 'develop https://<redacted>.git'
2016-12-08 18:33:27,537 [salt.utils.gitfs ][DEBUG   ][393] Fetching git_pillar remote 'develop https://<redacted>.git'
2016-12-08 18:33:27,841 [salt.utils.gitfs ][DEBUG   ][393] git_pillar remote 'develop https://<redacted>' is up-to-date
2016-12-08 18:33:27,841 [salt.utils.gitfs ][DEBUG   ][393] pygit2 does not support detecting stale refs for authenticated remotes, saltenvs will not reflect branches/tags removed from remote 'develop https://<redacted>.git'
2016-12-08 18:33:27,841 [salt.utils.gitfs ][DEBUG   ][393] Removed update lock for git_pillar remote 'develop https://<redacted>.git'
```

5. Go to locally checked out git_pillar repo (in /var/cache) and notice that your recent changes to remote repository are not there:

```

[root@salt1 beb86f2d43eb67e14dab29e76f4dc31ecc644c2b1da20b3747dea3d68a30e10a]# cat /var/cache/salt/master/git_pillar/remote_map.txt 
# git_pillar_remote map as of 06 Dec 2016 22:20:11.190814
beb86f2d43eb67e14dab29e76f4dc31ecc644c2b1da20b3747dea3d68a30e10a = develop https://<redacted>.git

[root@salt1 beb86f2d43eb67e14dab29e76f4dc31ecc644c2b1da20b3747dea3d68a30e10a]# pwd
/var/cache/salt/master/git_pillar/beb86f2d43eb67e14dab29e76f4dc31ecc644c2b1da20b3747dea3d68a30e10a

[root@salt1 beb86f2d43eb67e14dab29e76f4dc31ecc644c2b1da20b3747dea3d68a30e10a]# git branch -a
* develop
  master
  remotes/origin/develop
  remotes/origin/master

[root@salt1 beb86f2d43eb67e14dab29e76f4dc31ecc644c2b1da20b3747dea3d68a30e10a]# git remote -v
origin	https://<redacted>.git (fetch)
origin	https://<redacted>.git (push)

[root@salt1 beb86f2d43eb67e14dab29e76f4dc31ecc644c2b1da20b3747dea3d68a30e10a]# git status
On branch develop
nothing to commit, working directory clean

[root@salt1 beb86f2d43eb67e14dab29e76f4dc31ecc644c2b1da20b3747dea3d68a30e10a]# git log -1 | grep commit
commit 9147712190562b235a86509bec87827e2d19acfb

[root@salt1 beb86f2d43eb67e14dab29e76f4dc31ecc644c2b1da20b3747dea3d68a30e10a]# git log -1 origin/develop | grep commit
commit 4f24ee9123027924fccf9e737e508bc0223e07f3
```

### Versions Report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
@747project looks like i'm able to replicate this behavior. It seems this is only the case when running `salt-run git_pillar.update`. When I run `pillar.items` and `saltutil.refresh_pillar` the pillar data is updated. So it seems this is only behavior related to this runner.

I have a docker container to quickly replicate issue but one might need to change the repo so they can update their personal repo:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38162`
2. change repo in /etc/salt/master
3. `salt-master -d;salt-minion -d`
4. make an update to your repo
5. `salt-run git_pillar.update`
6. change into  `/var/cache/salt/master/git_pillar/<commit>`
7. run `git log` and see if your latest commit is there.

**Comment by Ch3LL** [comment]
forgot to ping @terminalmage as a heads up on this issue.

**Comment by Ch3LL** [comment]
Just tested and am also seeing this on 2016.3.3 and 2016.3.4 so not a regression in 2016.11.0

**Comment by terminalmage** [comment]
@Ch3LL Just  FYI, ``saltutil.refresh_pillar`` has no impact on the repos being updated. The git_pillar repos are updated in the maintenance loop along with the fileserver. ``saltutil.refresh_pillar`` just recompiles pillar data from what is available in the repo.

I'm looking at this right now.

**Comment by Ch3LL** [comment]
gotchya. i must have been mistaken in my test case then when i run that. Thanks for clarifying

**Comment by terminalmage** [comment]
@Ch3LL What likely happened is that the maintenance loop just iterated during the course of your testing. It runs about every 60 seconds.

I had to step away but will look at this more over the weekend as time allows.

**Comment by terminalmage** [comment]
This is not a bug. I think that @747project is running into the same thing that @Ch3LL is, and that is the fact that git_pillar remotes are fetched roughly every 60 seconds.

@747project I think you are probably assuming that a ``salt-run git_pillar.update`` will update the git checkout. This is an incorrect assumption. ``salt-run git_pillar.update`` doesn't fast-forward the local clone, all it does is perform a ``git fetch``. As I'm sure you know, fetching doesn't fast-forward a git clone. The fast-forward doesn't happen until the next time pillar data is compiled.

As I mentioned above, the master has a process dedicated to performing maintenance tasks. It performs its tasks (one of which is to fetch the git_pillar repos), then sleeps for the amount of seconds specified by the master's [``loop_interval``](https://docs.saltstack.com/en/latest/ref/configuration/master.html#loop-interval) configuration option. This value defaults to 60 seconds. So, what is happening to you is that you are pushing to your git_pillar repo, and before you get the chance to run your ``salt-run git_pillar.update``, the master has already fetched.

You should be able to confirm this for yourself by setting ``log_level_logfile: debug`` in ``/etc/salt/master``, the git_pillar fetches will be logged and you'll be able to seen when objects are fetched.

I created a docker container where this can be demonstrated. In it, I modified the ``loop_interval`` to 300 seconds, so that there is more time after pushing to execute the ``salt-run git_pillar.update`` before the maintenance process updates the repo.

I saved my shell history showing this is working exactly as it should in [this gist](https://gist.github.com/terminalmage/6858ea735f0998c8cf0c3c968c673d2a).

I'm curious, did you ever try refreshing the pillar data to check if the updates to your pillar data were reflected in ``pillar.item``?

**Comment by terminalmage** [comment]
Also, ``ext_pillars_first`` is not a valid config option, I think you're thinking of ``ext_pillar_first``.

**Comment by pesachtw** [comment]
@terminalmage Thank you for the clarification. Indeed, I was assuming that ```salt-run git_pillar.update``` performs a full update in the sense that it pulls latest on whatever branch is configured. I just confirmed your explanation locally by:
1. committing to the remote branch
2. listing pillars via ```pillar.item``` and not seeing the update
3. waiting until the schedule process has run at least once at interval set by ```loop_interval```
4. listing pillars via ```pillar.item``` and still not seeing the update
5. calling ```salt-run git_pillar.update```
6. waiting until the schedule process has run at least once at interval set by ```loop_interval```
7. listing pillars via ```pillar.item``` and confirm seeing the update

We have a scenario where we would like to include external pillars in state runs within a continuous intregration build. Is there no way to ensure that the pillars are pulled immediately so that we can proceed to further steps within the CI pipeline? Or is the recommended approach to wait the ```loop_interval``` before utilizing the pillar changes?

Also, just to clarify the current ```git_pillar``` functionality: is ```salt-run git_pillar.update``` required to get the latest changes from the external repo? Or will the latest changes eventually appear on their own?

Finally, I was indeed referring to ```ext_pillar_first``` in my initial report (instead of ```ext_pillars_first```). Thank you for catching that.

**Comment by 747project** [comment]
@terminalmage Thank you for the clarification. Indeed, I was assuming that ```salt-run git_pillar.update``` performs a full update in the sense that it pulls latest on whatever branch is configured. I just confirmed your explanation locally by:
1. committing to the remote branch
2. listing pillars via ```pillar.item``` and not seeing the update
3. waiting until the schedule process has run at least once at interval set by ```loop_interval```
4. listing pillars via ```pillar.item``` and still not seeing the update
5. calling ```salt-run git_pillar.update```
6. waiting until the schedule process has run at least once at interval set by ```loop_interval```
7. listing pillars via ```pillar.item``` and confirm seeing the update

We have a scenario where we would like to include external pillars in state runs within a continuous intregration build. Is there no way to ensure that the pillars are pulled immediately so that we can proceed to further steps within the CI pipeline? Or is the recommended approach to wait the ```loop_interval``` before utilizing the pillar changes?

Also, just to clarify the current ```git_pillar``` functionality: is ```salt-run git_pillar.update``` required to get the latest changes from the external repo? Or will the latest changes eventually appear on their own?

Finally, I was indeed referring to ```ext_pillar_first``` in my initial report (instead of ```ext_pillars_first```). Correcting the post. Thank you for catching that.

**Comment by terminalmage** [comment]
You're confusing the process of fetching new git_pillar updates with that information appearing in the pilllar data. These are two distinct processes. Pillar data for a given minion is automatically recompiled when you either a) run a state, or b) run ``saltutil.refresh_pillar`` on a minion.

The process of compiling pillar data will in turn invoke the configured ext_pillar sources, including git_pilllar. THIS is when the local cachedir for git_pillar will show the new files. So, the regular update (or a ``salt-run git_pillar.update``, which does literally the same thing as what happens during the regular update) will fetch new objects from the remote repo, but they will not be reflected in the cachedir until the next time pillar is compiled.

When Salt fetches the repos, and then you run ``pillar.item``, you're not going to see the new pillar data, because it hasn't been compiled yet. You need to either run a state, or run ``saltutil.refresh_pillar`` to trigger a recompilation of pillar data.

**Comment by 747project** [comment]
@terminalmage Thank you. So the benefit of manually invoking `git_pillar.update` is essentially to prep the local clone earlier than the usual `loop_interval` for the next minion state/refresh_pillar run. If `git_pillar.update` is not manually run, and salt is left to its own devices, the local clone would get fetched anyway at `loop_interval` interval, and be ready for the next minion state/refresh_pillar run.

**Comment by terminalmage** [comment]
@747project That is correct. Hopefully the updates I made to the docs make this more clear.

Mainly this runner exists so that people can invoke it in orchestration. I know of one user who set up a reactor SLS file which looks for pushes to their git_pillar repo, and then kicks off an orchestration job which runs  ``git_pillar.update`` and then runs a ``state.sls`` on several minions.
