### ISSUE TITLE
[syndic] Why can't a syndic node signal when all of it's minions have returned?

### ISSUE THREAD

**Issue by NickDubelman** [saltstack/salt#38174]
Thanks much for all the quick replies. 

I've spent the day experimenting with syndic_wait and have decided to set the value to 1 second for my purposes. I'm wondering why this syndic_wait needs to exist in the first place. As I see it, the syndic master knows when all of its minions have returned and should return to its master when this happens.

**Comment by Ch3LL** [comment]
So the reason `syndic_wait` is necessary is because the master of masters does not have a way of knowing which minions are below the syndics. The master of master has its own list of expected minions and the masters below them have their list as well, so it does not how long to wait for all returns. I think we could improve the docs [here](https://docs.saltstack.com/en/latest/topics/topology/syndic.html#syndic-wait) to clarify this so i'll label this as a documentation bug.

**Comment by rallytime** [comment]
I have added documentation for the `syndic_wait` setting in #38279
