### ISSUE TITLE
Improved error messages for when a particular module could not be loaded

### ISSUE THREAD

**Issue by jcmcken** [saltstack/salt#38217]
### Description of Issue/Question

In docker containers, states containing module function calls (e.g. ``service.available``) may fail on execution, since no init system is present.

### Setup

Launch a docker container that has ``/bin/bash`` as its init process (``/proc/1/cmdline``), e.g.

```console
$ docker run -it --rm centos /bin/bash
```

Install ``salt`` and ``salt-minion`` into the image.

### Steps to Reproduce Issue

Once on the shell inside of a docker container, run ``salt-call`` to execute an SLS file that contains a ``service`` module invocation, e.g.

```
{% set is_available = salt.service.available('sshd') %}
```

Currently, the execution of this SLS file would raise an ``AttributeError``, and lead to a confusing error message like: 

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:some.service' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'service'
```

Ideally, there should be a more understandable message such as:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:some.service' failed on function 'salt.service.available': Could not detect any init systems, and thus no "service" modules were loaded.
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by gtmanfred** [comment]
This would be great to have.  I am not sure how easy it would be to implement, but I am tagging it for a feature request for our core team.

Thanks for reporting,
Daniel

**Comment by cmclaughlin** [comment]
I was going to open an issue for this, but this existing one seems to sum it up...

We hit the same error message today and it took some digging to get to to the root of the problem.  In our case, we were calling a custom module function from a template.  The actual Python error was a failed import.  Ideally we would have seen the Python error instead of the Jinja2 attribute error.

**Comment by h3** [comment]
I got here while because I got the same (quite unuseful) error ...

In my case I was trying to create a custom module in `_modules`, but it was not available in the salt object.

After some digging I found that it's because I was using `salt-call` on the master and custom modules aren't loaded on the master (needs to use the `extension_module` config).
