### ISSUE TITLE
cron.env_present always updated with empty string

### ISSUE THREAD

**Issue by ipmb** [saltstack/salt#38321]
### Description of Issue/Question

Setting a cron environment using the module or state to an empty string always reports changed/updated, even if it already exists.

### Steps to Reproduce Issue

`salt-call cron.set_env root MAILTO "" && salt-call cron.set_env root MAILTO ""`

The second one should report `present`, but it reports `updated`

### Versions Report

```
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-45-generic
         system: Linux
        version: Ubuntu 16.04 xenial```

**Comment by Ch3LL** [comment]
@ipmb execution modules are not designed to act in a stateful manner but if the state module is also exhibiting the same behavior then that is definitely an issue, because they should be detecting if its already been set.

It looks like there isn't a `cron.set_env` state module but possibly what you are attempting to use is `cron.env_present` state module. There is currently already an issue open regarding this here: https://github.com/saltstack/salt/issues/24567

Just need clarification from you if this is the state module you are referring to and then we can close this issue an track it there. Thanks

**Comment by ipmb** [comment]
Yes, this is a dupe. I added a comment there.. thanks!
