### ISSUE TITLE
Building salt documentation throws error.

### ISSUE THREAD

**Issue by rajvidhimar** [saltstack/salt#38332]
### Description of Issue/Question
I was trying to build the salt documentation (sphinx version=1.5.1) But it threw the following error:
```
No need to update translations. Skipping...
sphinx-build -b html -d _build/doctrees    . _build/html 
Running Sphinx v1.5.1
 
Extension error:
Could not import extension sphinx.builders.linkcheck (exception: No module named            packages.urllib3.exceptions)
make: *** [html] Error 1
```
I tried sphinx 1.5.0, still the same error. When I downgraded to 1.4.9, the documents got built. There might be an issue with sphinx or the Makefile is incompatible with newer versions of sphinx.

### Versions Report
I am working on Ubuntu 14.04.

**Comment by Ch3LL** [comment]
@rajvidhimar I believe this is an upstream issue. It seems this error has occurred for multiple projects, due to what looks like debian removing urllib3 from requests package. As shown in the changelog [here](https://launchpad.net/debian/+source/requests/+changelog) it looks like the patch `02_use-system-chardet-and-urllib3.patches` did the following: ```Use the system python-chardet and python-urllib3 instead of the
      embedded copies``` starting in requests version 1.1.0-1 

Can you try two things for me:

1. Upgrade requests to the latest version
2. Fnd the file: `sphinx/util/requests.py` and add this:


```
diff --git a/sphinx/util/requests.py b/sphinx/util/requests.py
index d358d84..5f66b1c 100644
--- a/sphinx/util/requests.py
+++ b/sphinx/util/requests.py
@@ -17,7 +17,10 @@ import pkg_resources
 
 from six import string_types
 from six.moves.urllib.parse import urlsplit
-from requests.packages.urllib3.exceptions import SSLError, InsecureRequestWarning
+try:
+    from requests.packages.urllib3.exceptions import SSLError, InsecureRequestWarning
+except ImportError:
+    from urllib3.exceptions import SSLError, InsecureRequestWarning
```

Please let me know if either of these fix the issues to verify this is an upstream issue.

**Comment by rajvidhimar** [comment]
Hi @Ch3LL, 

1. Upgrading requests didn't work.
2. Applying the patch did work, hence it was an upstream issue.

I am closing this issue. Thanks :)
