### ISSUE TITLE
file.serialize still expects show_diff instead of show_changes

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#38853]
### Description of Issue/Question

#30988 deprecated `show_diff` and replaced it with `show_changes` for all `file.*` states. All of them, except for `file.serialize`.

I would've made a PR, but forward-merging makes it quite challenging to me.

### Setup

Both 2016.3.4 and 2016.11.1 have this bug. It is also visible in documentation.

**Comment by gtmanfred** [comment]
This is not a bug in 2016.3, because show diff was still supported.  In 2016.11, we could probably change the show_diff to show_changes in the serialized function, but the show_diff value is passed as show_changes to the file.manage_file function in the module, so I am not sure what the problem actually is, could you provide more information?

Thanks,
Daniel

**Comment by bobrik** [comment]
Problem is that `file.serialize` uses a different name than everything else in `file.*` in 2016.11. It's correct that it passes `show_changes` to `file.manage_file`, but it's not what concerns the end user.

Should I make a PR agains 2016.11 branch only?

**Comment by gtmanfred** [comment]
You can add show_changes, and then add a depecation message like file.manage_file did in 2016.3, but then remove it from develop.

**Comment by bobrik** [comment]
PR is merged, closing.
