### ISSUE TITLE
salt.runner and salt.wheel ignore test=True

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#38894]
The orchestration states `salt.runner` and `salt.wheel` execute even if `test=True` is passed. These states should not make changes when `test=True`.

**Comment by Ch3LL** [comment]
@amendlik I think this would be pretty involved since it doesn't look like most runners include test=True, only state.py. Also in states/saltmod.py test option would need to be parsed in the wheel and runner functions because it currently is not, compared to the other functions that do handle that option.

To refine this issue a little more which runners and wheel modules are you attempting to use?

**Comment by amendlik** [comment]
I believe you only need to change `saltmod` state module. 3 of the 5 functions in that module already honor `test=True`. The last 2 (`salt.runner` and `salt.wheel`) just need code to print an informational message stating what would have run if `test != True`, rather than actually executing the wheel or runner function.

**Comment by Ch3LL** [comment]
So you are okay if we just print out what command would have been run? Not making a call out to the module with the test=True kwargs? Sounds good enough to me. Thanks

**Comment by amendlik** [comment]
I believe that is the right way to address this, since only state modules know how to deal with `test=True`.

**Comment by Ch3LL** [comment]
Agreed. Thanks :)

**Comment by thatch45** [comment]
I have to admit I was going to throw a fit over this one, but you have skillfully found an excellent way to solve this @Ch3LL , the force is strong with you!

**Comment by rickh563** [comment]
ZD-1174

**Comment by garethgreenaway** [comment]
@amendlik When you get a chance, if the merged changes in PR #41309 address the issue you raised, if you close out this issue.  Thanks!

**Comment by amendlik** [comment]
The change in #41309 is not correct. Please see my comments in the PR.
