### ISSUE TITLE
boto_rds: Tags not working (or incorrectly documented)

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#38936]
### Description of Issue/Question
According to the manual tags for a RDS instance should be defined as:
```
    - tags:
      -
        - key1
        - value1
      -
        - key2
        - value2
```

However, I have done that but executing the state fails with an exception:
```
          ID: aws_rds_rds-test2
    Function: boto_rds.present
        Name: rds-test2
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_rds.py", line 346, in present
                  promotion_tier, key, keyid, profile)
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto_rds.py", line 282, in create
                  taglist = _tag_doc(tags)
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto_rds.py", line 897, in _tag_doc
                  for k, v in six.iteritems(tags):
                File "/usr/lib/python2.7/dist-packages/salt/ext/six.py", line 583, in iteritems
                  return iter(d.iteritems(**kw))
              AttributeError: 'list' object has no attribute 'iteritems'
     Started: 13:35:27.648802
    Duration: 276.842 ms
     Changes:   
```

If I define it as such (output from `state.show_sls`):
```
             ----------
              tags:
                  ----------
                  key1:
                      value1
                  key2:
                      value2
```

It doesn't throw the exception (since it gets a dictionary which `iteritems()` expects) however no tags are being added.

### Setup
Relevant section of the output from `state.show_sls` is:
```
            |_
              ----------
              tags:
                  |_
                    - key1
                    - value1
                  |_
                    - key2
                    - value2
```

### Steps to Reproduce Issue
See above

### Versions Report
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
When just running this function in ipython i return taglist correctly when adding tags as such: 


```
In [8]: tags = {
   ...:   "tags": {
   ...:     "key2": "value2",
   ...:     "key1": "value1"
   ...:   }
   ...: }
```

Which i'm assuming is what you had your tag layout as when you showed the state.show_sls output for tags.

And running the function returns taglist correctly:

```
In [12]: def _tag_doc(tags):
    ...:     taglist = []
    ...:     if tags is not None:
    ...:         for k, v in six.iteritems(tags):
    ...:             if str(k).startswith('__'):
    ...:                 continue
    ...:             taglist.append({'Key': str(k), 'Value': str(v)})
    ...:     return taglist
    ...: 

In [13]: _tag_doc(tags)
Out[13]: [{'Key': 'tags', 'Value': "{'key2': 'value2', 'key1': 'value1'}"}]
```

So it looks like you might be right that the tags need to be laid out that way. But then if you look at the `def create` code: https://github.com/saltstack/salt/blob/v2016.11.1/salt/modules/boto_rds.py#L282 I don't see that taglist variable being used anywhere else. So i believe the issue is:

1. documentation issue
2. taglist probably needs to be added to kwargs or somewhere else in that create function. But i'm not familiar enough with this code to know if it needs to be passed into that `create_db_instance` call. 

We need to get this fixed up thanks

**Comment by twellspring** [comment]
Trying to add RDS to [aws-formula](https://github.com/saltstack-formulas/aws-formula) and ran into the same thing ... yes better documentation on all of the Boto modules would be helpful.

**Comment by Ch3LL** [comment]
@twellspring and when you changed the tag do you see the same behavior also where it does not actually set the tags?

**Comment by MDPolaris** [comment]
Is there an update on this issue, or a workaround I am not seeing for tagging RDS instances? I am hitting the same issue in 2016.11.4.

**Comment by Ch3LL** [comment]
@MDPolaris let me see if ican get someone else to look but there is not a workaround. I think taglist needs to be added to kwargs, but not sure if thats all we need to ensure the create_db_instance call will create the tags.

@claudiupopescu looks like you created this module. I think the issue is that taglist is not being added to the kwargs. Might be an easy fix but not familiar with this module. Mind taking a quick look.

**Comment by MDPolaris** [comment]
@Ch3LL Thank you for the update. I added the following at line 283 for testing purposes:
kwargs.update({"Tags": taglist})

The state module Tag structure must be in the normal format like this:
```
- tags:
     key1: val1
     key2: val2
```
Which is what you previously noted as well.

This does work properly and the tags are correctly added to the new instance. I am certainly not recommending this as the "fix" since i am not familiar enough to know if something else is missing, however I can at least confirm that the above change is all that is required to get the tags into the instance. Hopefully this is helpful.
