### ISSUE TITLE
Testing from slack

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#38933]
### Description of Issue/Question
Hi,
there is a way to pass test=True arg from slack?

I tried so:
```
! state.apply my_state test=True
```
but did not work. Any advices?

Thanks

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.14.32-xxxx-grs-ipv6-64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
I believe it should work the way you are expecting it to.  My guess though is that the True is actually a string, because we just split it here.  https://github.com/saltstack/salt/blob/develop/salt/engines/slack.py#L184

We could probably add some code that checks the string and converts them to True/False booleans .

I am going to mark this as a bug, if you wanna take a look at it, we would greatly appreciate it.

Thanks,
Daniel
