### ISSUE TITLE
python-tornado 4.2.1-2+ds+1_amd64.deb Hash Sum Mismatch

### ISSUE THREAD

**Issue by Artanicus** [saltstack/salt#39142]
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/pool/main/p/python-tornado/python-tornado_4.2.1-2~ds+1_amd64.deb  Hash Sum mismatch

### Steps to Reproduce Issue
- enable repo.saltstack.com for APT
- sudo apt update
- sudo apt install python-tornado

**Comment by Ch3LL** [comment]
@Artanicus i'm not able to replicate this on a clean ubuntu 16 VM.

i did the following: 
1. add `deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main` to sources.list
2. `apt-get update`
3. `apt-get install python-tornado=4.2.1-2~ds+1`

And it installed correctly with no errors. Any other information that would be useful to help replicate this.

**Comment by Artanicus** [comment]
It seems if I'm installing though apt-cacher-ng then it fails, directly it does not. A simple update and restart of the cacher didn't help so will need to dig deeper to find the issue.

**Comment by Artanicus** [comment]
Couldn't pinpoint the issue, switched to squid-deb-proxy for caching purposes. Now it works fine. Odd one that.

**Comment by papamoose** [comment]
I have business reasons to mirror all repositories and was experiencing the same issue. I use 'apt-mirror' (https://apt-mirror.github.io/) to mirror a ton of repositories and have had great success.
It seems that recently the python-tornado deb package did have a different checksum than the one specified in the 'Packages' file.  I redownloaded the entire repository, the checksums now match and everything works as expected.

The only thing I would be able to speculate is that the deb package was incorrectly added to the repository and some people noticed while the repo was in an inconsistent state. Though, there is no way I can know for sure since I don't run their apt repos...
