### ISSUE TITLE
Minion not killed using "best way to restart minion"

### ISSUE THREAD

**Issue by vquiering** [saltstack/salt#39157]
### Description of Issue/Question
Using [this howto](https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-daemon-using-salt) (cmd.run) we end up with two or more minions running every now and then. All minions on one host are responding to the master.
Using module.run solved our issue for now.

Is cmd.run best practise to restart a minion?

### Setup
Before:

    restart_minion:
      cmd.run:
        - name: |
            exec 0>&- # close stdin
            exec 1>&- # close stdout
            exec 2>&- # close stderr
              nohup /bin/sh -c 'sleep 10 && salt-call --local service.restart salt-minion' &
        - output_loglevel: quiet

After:

    restart_salt-minion:
      module.run:
        - name: service.restart
        - m_name: salt-minion

**Comment by Ch3LL** [comment]
So what I understand the issue to be is you are attempting to run that cmd.run state to restart the minion and sometimes the minion does not restart. 

To answer your questions is this the best way to restart the minion. According to those docs that is only a  alternative way to attempt to restart the minion compared to using the `atd` if that command is not available. So I would define that as one way to accomplish this task without scheduling the restart. If this is not properly occurring then lets troubleshoot why thats not, because we definitely want to make sure we document a solution that works.. When running that state is there anything the debug lgos stating it attempted to run the restart? On minions where you see the issue can you run the command manually on that host?
