### ISSUE TITLE
[Feature] add support for the new docker python module to dockerng.

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#39216]
### Description of Issue/Question
dockerng module stops working if you install a current version for docker-compose on your system.

This is due, to the fact that docker-compose has recently switched to using a new python 'docker' module instead of old 'docker-py'. Those two modules conflict with each other.
dockerng fails to work if python 'docker' module is installed (it requires docker-py module)

```
root@elk01:~# docker-compose 
ERROR: Dependency conflict: an older version of the 'docker-py' package is polluting the namespace. Run the following command to remedy the issue:
pip uninstall docker docker-py; pip install docker
root@elk01:~#
```

```
root@elk01:~# pip install docker-compose
...
...
Installing collected packages: docker-compose, docker
```

dockerng with presence of python 'docker' module
```
----------
          ID: prometheus-node-exporter_image
    Function: dockerng.image_present
        Name: prom/node-exporter
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1745, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 576, in image_present
                  all_tags = __salt__['dockerng.list_tags']()
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2409, in list_tags
                  for item in six.itervalues(images()):
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2214, in images
                  response = _client_wrapper('images', all=kwargs.get('all', False))
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 695, in wrapper
                  _get_client(timeout=client_timeout)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 824, in _get_client
                  __context__['docker.client'] = docker.Client(**client_kwargs)
              AttributeError: 'module' object has no attribute 'Client'
     Started: 11:10:35.267376
    Duration: 1.966 ms
     Changes:   
----------
```

**Comment by gtmanfred** [comment]
Unfortunately they also changed Client to DockerClient, so we do not support this version of the docker python module right now either.

Thanks for reporting,
Daniel

**Comment by terminalmage** [comment]
@gtmanfred Actually the split `Client` into `APIClient` and `DockerClient`, with `APIClient` being the low-level interface that we need. I made this fix in https://github.com/saltstack/salt/pull/38851 a couple weeks ago.

**Comment by gtmanfred** [comment]
Ahh, ok so this should be fixed in the next version.

Thanks @terminalmage

**Comment by terminalmage** [comment]
The imported name has always been ``docker``, and installing ``docker-py`` or ``docker`` from PyPI should install the same Python module. It's just that the client names changed in 2.0 and the fine folks at Docker left no deprecation path for the old ``docker.Client()`` class.

This is already fixed, the fix is just not in any current release. If you want to get the fix right now you can do the following:

- Make a copy of dockerng.py (from ``/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py``) and save that file in ``salt://_modules/dockerng.py`` in your salt fileserver.
- Copy this patch to your master:
```diff
diff --git a/salt/modules/dockerng.py b/salt/modules/dockerng.py
index 6396ed9242..f91b4e3af2 100644
--- a/salt/modules/dockerng.py
+++ b/salt/modules/dockerng.py
@@ -767,7 +767,11 @@ def _get_client(timeout=None):
             # it's not defined by user.
             client_kwargs['version'] = 'auto'

-        __context__['docker.client'] = docker.Client(**client_kwargs)
+        try:
+            __context__['docker.client'] = docker.Client(**client_kwargs)
+        except AttributeError:
+            # docker-py 2.0 renamed this client attribute
+            __context__['docker.client'] = docker.APIClient(**client_kwargs)

     # Set a new timeout if one was passed
     if timeout is not None and __context__['docker.client'].timeout != timeout:
```
- ``cd`` to that location where you backed up dockerng.py, and run ``patch dockerng.py <foo.patch`` (with ``foo.patch`` being whatever you named the patch file above when you saved it to the master. You should see something like this:

```bash
% patch dockerng.py <foo.patch
patching file dockerng.py
Hunk #1 succeeded at 821 with fuzz 2 (offset 54 lines).
```

You should now have the patch applied. You can then run a ``salt '*' saltutil.sync_modules``, and the patched dockerng.py should override the one installed from the .deb package.

However, once you upgrade to 2016.11.3, you'll need to remember to remove the file from ``salt://_modules/`` and re-run the sync_modules to remove this override.
