### ISSUE TITLE
Provide Docker version as grain value

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#39582]
If Docker is installed on the minion, it would be great to have a Docker version available as grain, so that I could make conditions in states based on that version.

**Comment by DaveOHenry** [comment]
This (and more) is already possible with custom grains. See https://docs.saltstack.com/en/latest/topics/grains/#writing-grains . But keep in mind that grains are designed to hold mostly static data, because they are not regularly / automatically updated. So when the Docker version changes a grains sync has to be triggered.

Maybe it is better to use the salt mine instead. It is designed for data that may change frequently. Under the hoods the mine executes functions regularly to keep the data up to date. Its a little more complex to set up, but one of the key concepts to understand.

**Comment by mitar** [comment]
I have seen `pythonversion` in grains, this is why I thought that Docker version could also be in grains. 

But thanks for pointing out mines. I am looking into them now.

**Comment by gtmanfred** [comment]
Mines would work for this, but you could also use a custom grain.

I am going to mark this as a feature request, but it is going to be a low priority.

Thanks,
Daniel

**Comment by mitar** [comment]
OK.

**Comment by mitar** [comment]
Please reopen this issue.

**Comment by OrangeDog** [comment]
I suspect this will be closed as won't do, as there's no reason to be putting software versions of unrelated installations into default grains. If you want a grain with the docker version, it's easy to add yourself.

**Comment by Ch3LL** [comment]
Agreed a custom grain is the solution here. Closing as wont fix.
