### ISSUE TITLE
Peer call (publish.publish) doesn't work thorugh Syndic

### ISSUE THREAD

**Issue by jay1648** [saltstack/salt#39680]
Peer call (publish.publish) doesn't seem to be working as expected, when called from a minion of a Syndic Master with a top level Master.

There's a top level master that has some direct minions on it. There are some Syndic Masters that are pointing to the top level Master. And each syndic master has their own direct minions. The requirement is, we need to call an execution module from one minion of Syndic Master 1 to another minion pointing to Syndic Master 2. They're all using gitfs and same repository.

I've tried to do this via salt-call publish.publish, but it seems a minion can only publish commands to the direct minions of it's salt master. We'd need it to reach up the top level master and be able to publish command from there, and gather results.

I'm not sure but I think it may be a limitation of the Syndic system as my guess is it's only one way communication (top level master to syndic masters). 

### Versions Report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by gtmanfred** [comment]
This is the expected behavior.  The syndic is a one way communication, the master can send messages down through the syndics, but the minions cannot request information using peering from other syndics.  The minions would need to be on the same syndic.

The other option would be to use the caching subsystem.  Right now in 2016.11 there is only one subsystem in there besides the localfs caching, and that is consul.
https://docs.saltstack.com/en/develop/ref/cache/all/salt.cache.consul.html#module-salt.cache.consul

This could be used to store all the mine data, so that all syndic masters could provide the information to all minions.

If you want to copy this cache module to all your masters, you could also use the redis cache instead of consul, but it is only available on develop right now. 

https://github.com/saltstack/salt/blob/develop/salt/cache/redis_cache.py

Thanks,
Daniel

**Comment by jay1648** [comment]
Well, I understand Mine and cache are for solving different type of problem altogether, when you only need information from one node to another. Here we're looking into some way of initiating a task from one minion to another.  
Just so that I can get some suggestions - What if I have the source minion raise an event message (which I think reaches up to the top level master), and then have the Top level master reactor setup to run some orchestration or salt modules. Is that expected to work ?

**Comment by gtmanfred** [comment]
That still won't reach the master of masters.  It will only go to the master on the syndic.

You would then need a reactor on the master on the syndic to forward the message to the master of masters event bus by grabbing the tag, and then use the minion on the master on the syndic to forward the event to the master of masters using a caller event.send.

**Comment by jay1648** [comment]
Can I in that case do a publish.runner and have a runner at the syndic master fire the event ?

**Comment by gtmanfred** [comment]
You cannot, because the runner on the syndic master would send it to the syndic master event bus.

And you also cannot do it through a publish.publish to the minion on the syndic, because that minion does not listen to the same master so it would not recieve calls from the master on the syndic.

What you could do would be to write a custom runner that initiates a [Caller](https://docs.saltstack.com/en/latest/ref/clients/#salt.client.Caller) which could do an event.send as the minion on the syndic.

**Comment by jay1648** [comment]
Just found https://github.com/saltstack/salt/issues/12917 . It says "The syndic is little more than an event forwarder. All events from lower minions should make it to your master of masters."   Is that not true on the latest version ? If it reaches up the top level master, I should be able to fire any state or execution module call to any minion, no ?

**Comment by gtmanfred** [comment]
It is worth testing, but I was under the impression that commands were only
passed one way. But I may be mistaken about events getting passed up the
syndicate

It is also possibly that they only meant the events as returns from state
calls getting passed up to the master of masters. Test it out and let us
know.

**Comment by jay1648** [comment]
will do and post and back. Thanks for your help though !

**Comment by jay1648** [comment]
The top level master does receive the events when generated by any minion under the Syndic Master.
Here's what I did : 

- Created a custom execution module with arguments to capture what execution module/state to run  on which host. 
- Generate an event from the within the execution module with a unique tag and all the details in it's data.
- Fired that execution module from one of the minions under syndic master using salt-call 
- Then watching the event bus on top level master, I could see that event coming. 

So all I need to do now, is configure a reactor at top level master to handle that event, and I should be good. Completely eliminates the peering call.

**Comment by gtmanfred** [comment]
Bood to know, thanks for reporting back!
