### ISSUE TITLE
[WARNING ] Template is an empty file

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#39684]
### Description of Issue/Question

Since your sls files got too complex, we avoid conditions like this at the moment:

include:
  - foo.{{ grains.os_family }}

Sometimes no special os-specific stuff needs to be done. Now this massage is visible, if the file is empty:

[WARNING ] Template is an empty file: /.../foo/Debian.sls

I asked at the user group: https://groups.google.com/forum/#!topic/salt-users/4W_T6eJaTHY  and found no satisfying answer.

After thinking about this again: 
  * Python does not emit a warning if you import an empty file
  * Most programming languages don't emit a warning if you loop over an empty list

on the other hand in SQL this is not allowed:
`select * from mytable where id in ()`

What would you lose if you disable this warning?

**Comment by Ch3LL** [comment]
Looks like this was originally added here: https://github.com/saltstack/salt/pull/19615

which was initially a `log.error` and is now a `log.warning`. I think for debugging purposes it would be nice to see that the file is empty if you did not intend for the jinja rendering to be empty. We could possibly turn that into a `log.debug` so a user would only see that in debug output, but would like to get others opinions on this.

ping @terminalmage @cachedout or @rallytime what do you think about changing this error to a debug log instead of a warning, since some people would intend for the file to be empty sometimes.

**Comment by guettli** [comment]
I created a pull request. Please revue it. Thank you.

**Comment by guettli** [comment]
thank you for merging.

**Comment by Ch3LL** [comment]
Thanks for the fix!
