### ISSUE TITLE
Amazon Linux repo appears to be missing 2016.11

### ISSUE THREAD

**Issue by shawnbutts** [saltstack/salt#39848]
https://repo.saltstack.com/yum/amazon/ does not have 2016.11 directory.

However, there is a 2016.11 directory under each of the other versions.
https://repo.saltstack.com/yum/amazon/2015.03/x86_64/2016.11/
https://repo.saltstack.com/yum/amazon/2015.09/x86_64/2016.11/
https://repo.saltstack.com/yum/amazon/2016.03/x86_64/2016.11/
https://repo.saltstack.com/yum/amazon/2016.09/x86_64/2016.11/
https://repo.saltstack.com/yum/amazon/latest/x86_64/2016.11/

This makes it really confusing to mirror internally.

**Comment by Ch3LL** [comment]
My understanding is this is the director you are looking for https://repo.saltstack.com/yum/amazon/latest/x86_64/   `latest` being the releaserver for amazon linux. Although I'm not sure what each of those other directories are because I don't believe we use these.

ping @dmurphy18 fyi above. Can you clarify what those other directories are?

**Comment by dmurphy18** [comment]
@shawnbutts The layout for Amazon differs from that used by Redhat due to Amazon's release cycle  is different.

For example: Amazon names their current version latest.
The 2015.3, 2015.09, 2016.03 and 2016.09 are the versions of Amazon which utilized python 2.7 rather than Redhat 6's python 2.6.  These are symbolic links to the current supporting Salt implementation for current Amazon AMI's.

The aim of the layout in repo.saltstack.com is to reflect Amazon layout as much as possible.  Normally Amazon releases ever 6 months, therefore I expect to see a release named 2017.3 sometime this summer. For example: https://aws.amazon.com/amazon-linux-ami/2016.09-release-notes and https://aws.amazon.com/amazon-linux-ami search for 'Release Notes'.

Thus the Amazon layout in repo.saltstack.com is to accommodate Amazon's release naming and then Salt Stack's release layout (similar to other Salt Stack operating system layouts, with an archive/<salt version> with symbolic links for major release and latest.

Please let me know if this clarifies the issue for you, otherwise I shall write up a more detailed explanation.

**Comment by shawnbutts** [comment]
Got it.  I was confused by the two date based version systems.

Thanks
