### ISSUE TITLE
Web Documentation not in sync with release 2016.11.3

### ISSUE THREAD

**Issue by Foxlik** [saltstack/salt#39942]
It seems the salt documentation is out of sync with salt packages.

I do have Salt 2016.11.3 installed via salt repository
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-65-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

But my salt instalation does not support ulimits in dockerng: 
```
$ ls -al /usr/lib/python2.7/dist-packages/salt/states/dockerng.py
-rw-r--r-- 1 root root 83784 Feb 22 22:23 /usr/lib/python2.7/dist-packages/salt/states/dockerng.py
$ grep -i ulimits /usr/lib/python2.7/dist-packages/salt/states/dockerng.py
```

Even though it is mentioned in the web documentation for 2016.11.3: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerng.html

It was added in this commit: c50374041d87b3611b2d133fc342bd55c0d95983 (the time of commit coincides with the time of release)

It's not a too big of a deal, but it is somewhat confusing. 😕

**Comment by Foxlik** [comment]
oh and just by the way ... https://docs.saltstack.com/en/develop/ref/states/all/salt.states.dockerng.html still shows 2016.11.2 ...

**Comment by Ch3LL** [comment]
I think what we need to do here is add the version when this was added. ping @terminalmage what do you think?

Let me find out about the other issue with it showing 2016.11.2 on develop at the bottom.

**Comment by Ch3LL** [comment]
ping @rallytime any ideas on why the develop docs are still showing 2016.11.2 at the bottom?

**Comment by rallytime** [comment]
@Ch3LL Hmmm....I think that is because that file has been renamed from `dockerng` to `docker` on the develop branch, so when the docs rebuild, that file shouldn't be there anymore for the develop branch to point to. I think we'll need to look at the build server for this to get any references to `dockerng` pages on the develop branch to redirect to `docker`.

Do you have any thoughts on that @whiteinge? I think you've been involved in these kinds of changes in the past.

**Comment by whiteinge** [comment]
Sphinx can't track renames so the old auto-generated `.rst` file needs to be nuked so that it can be re-generated for the new module on the next docs build, then that new version should be committed.

**Comment by rallytime** [comment]
Oh, derp. That's easy. I forgot to even check if we'd done that correctly. I can grab that really fast.

**Comment by rallytime** [comment]
Hi @Foxlik - After looking into this issue, the docs that you're seeing on docs.saltstack.com build from the HEAD of the release release branch (in this case, the 2016.11 branch), and not the tag from the actual release. The commit you referenced above was added to the 2016.11 branch _after_ the 2016.11.3 release.

I agree with @Ch3LL that we should just get a `Version Added` tag for this change in the documentation to make this more clear, which I have done in #39942. That should help clear up the confusion around when that change was added.

I also worked with @whiteinge today to remove the stale dockerng and dockerio files from the develop build on our doc build server, so that should also clear up any confusion on that part of this issue as well. It appears that the file you linked above is cached, so we will have to keep an eye on that. The `docker` state that replaced the `dockerng` state (just renamed) is here: https://docs.saltstack.com/en/develop/ref/states/all/salt.states.docker.html

I think that should cover everything in this issue. Or am I missing anything?

**Comment by Foxlik** [comment]
@rallytime 👍 
I agree that it covers both my 'complaints' ...  thanks!

Actually I do have one more suggestion, though not sure if it really is worth it as it is more of a UX thing:
When renaming modules, leave some kind of placeholder in the documentation stating the new name of the module. And vice versa. Now when you are in dockerng and switch to develop branch (button in top right), you get 404 ... (btw. just noticed, this 404 actually does not link back to 2016.11, just 2015.8 and 2016.3, but that really is just nitpicking ...)

**Comment by rallytime** [comment]
@Foxlik yeah, that's a totally valid UX complaint on navigating the docs 😄  

Would you mind filing a new issue about that? We would definitely like to clean that up. I think that is a bit of a difference issue that this original one, but we don't want to lose your suggestion either.

**Comment by Foxlik** [comment]
@rallytime : sure thing, will do.

feel free to close this one, once the web documentation for 2016.11 gets regenerated ... it's just fine in 2016.3 docs.

**Comment by rallytime** [comment]
@Foxlik Great! Thank you! We're all set on the 2016.11 docs too. I just checked and the `versionadded` is there. :)
