### ISSUE TITLE
Provide a larger example/use case for using thorium

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#39971]
### Description of Issue/Question
During the meet the maintainers discussion this afternoon, it came up that while we have improved the overall [documentation for Thorium](https://docs.saltstack.com/en/latest/topics/thorium/index.html), we don't have a larger example for a complete use case. We need to get a larger example added to the docs.

**Comment by rallytime** [comment]
FYI @joesusecom

**Comment by pcn** [comment]
I have spent a bit of time looking at thorium this week, and I agree that this is important.  My use case is that I'd like to react to inbound actions by turning them into a set, and removing them as a task on them is complete when there is a match.

The obstacles are currently that when bringing events into the register:

1) The use of comma-separated-strings or lists is not documented, and can be confusing
2) The shape of the data that I'm storing in the register for a particular name ends up being a list  of dictionaries
3) There is no way with check,contains (or anything else that I can identify) to match in a list of dictionaries.  The code looks like this:
```python
    if name not in __reg__:
        ret['result'] = False
        ret['comment'] = 'Value {0} not in register'.format(name)
        return ret
    try:
        if value in __reg__[name]['val']:
            ret['result'] = True
    except TypeError:
        pass
    return ret
```
So it looks like it's never going to match (it seems like it should be something like `[t for t in __reg__[name]['val'] if value in t]` instead?)

but the shape of the data being handed here isn't in the docs, so it's a lot of work to get this far (and some bugfixing in `file.save`).  The next thing I'm realizing here  is that check.contains really needs to be able to be capable of something like the `salt['pillar.get']` syntax, like `foo:bar:baz`.  Also, instead of just checking for the existence of the key it seems like matching on value could be helpful as well.

The documentation could help a lot if it clarified how to get to a destination like that.  The current examples are somewhat disconnected.

**Comment by danlsgiga** [comment]
I'm currently using Thorium to automate minion cert key lifecycle with the beacon pillar in order to keep it clean in our AWS AutoScaling group and so far it is working great.

For example, everytime we scale in the salt-master will revoke and delete all the minion keys of instances that did not contact the master in the last 24 hrs. Thorium, AFAIK, is the only effective and  the most simplest way of achieveing that at this moment.

Just my .2c from a use case perspective.

**Comment by pcn** [comment]
From what I heard at saltconf, thorium doesn't have a lot of active use/support and unless someone begins to actively use or develop it, it's likely to remain in this state, sadly.

**Comment by pcn** [comment]
Oh, no. Go ahead and close it stalebot.

**Comment by danlsgiga** [comment]
Yeah, that’s a shame. Thorium has been great for us to remove keys from minions that are destroyed by AWS as I explained in the comments above. Does anyone know a better way to handle this use case?

**Comment by pcn** [comment]
I don't think thorium is going away. It's just not receiving further development.

**Comment by pcn** [comment]
Otherwise I've found that writing up custom engines to do this sort of thing makes sense.

**Comment by mrj1m0thy** [comment]
Just came across this issue, I'm running into the same issues as @pcn . The "check" module doesn't support parsing the register to actually retrieve the value. The "file.save" module doesn't work with a "reg.set" because json serialize doesn't like sets. And there's no way to actually retrieve the register as a variable to parse it myself.

My use case is that I want to be able to execute a command in the case that the minion hasn't sent a status update in a certain period of time. Seems like a pretty normal use case but I can't do this in the current state of Thorium. (running version 3003.3). Would appreciate an update to thorium to fix these issues or at least a command that will return the register for me to play with.

**Comment by barbaricyawps** [comment]
Is anyone on this thread planning on working on this issue? It seems stale and I don't know that Thorium is getting much community support. I recommend possibly closing out this issue unless someone has plans to work on it in the immediate future.

**Comment by whytewolf** [comment]
enough time has passed and no comments. going to close this out.

**Comment by danlsgiga** [comment]
Would be awesome to have a response to this use case! https://github.com/saltstack/salt/issues/39971#issuecomment-479159068
