### ISSUE TITLE
Feature request - update rootfs paths without restarting master

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#40127]
### Description of Issue/Question
At the moment Saltstack does not provide the option to add rootfs path without restarting master.
It would be nice if user could call a module to update/add rootfs path on demand.

The reason I would like this is to have different rootfs fir each person and be able to add one if requested without having to restart master.

**Comment by gtmanfred** [comment]
I believe that this is a duplicate of https://github.com/saltstack/salt/issues/570 ?

Thanks,
Daniel

**Comment by tsaridas** [comment]
I wouldn't say so.

There are multiple ways to load things in memory and it doesn't mean you have to restart/reload.

**Comment by gtmanfred** [comment]
I would think that this was the way that we would do it, allowing for changing of the config file without restarting the salt master.

Outside of doing this, I think it opens up to security risk if you are just able to define a different root, which could have a different master config file that let that user be able to do anything with publisher_acls.  Also, you would have a problem that the master key would change, because it would look for a new master.pem and master.pub key in the new file root, so you would need to make sure each file root has all the same keys already.

**Comment by tsaridas** [comment]
What can be done is if user selects a fs which doesn't exist then try to load some special config file to see if it exists there and get the fstype and path etc. 

Or you can have a scheduled task that updates the fs.

Or you can have a file that notes that fs need to be updated and reloaded.

Or you can load a pickle every time you want to use a fs or update it.

**Comment by gtmanfred** [comment]
What exactly are you trying to accomplish?

**Comment by tsaridas** [comment]
I would like to add/remove a new rootfs without restarting master and causing downtime.

**Comment by gtmanfred** [comment]
What do you mean by rootfs?

Just another path in file_roots?  Or also another gitfs backend possible?

Thanks,
Daniel

**Comment by tsaridas** [comment]
I think they are all initiated by the same object so if you do rootfs you would also be able to other fs too but I just need rootfs.

**Comment by gtmanfred** [comment]
This is dependent on being able to reread/reload the master or minion config.

I am closing this as a duplicate of https://github.com/saltstack/salt/issues/570

Thanks,
Daniel
