### ISSUE TITLE
Error while bringing up minion for multi-master. Is master at cfg01 responding?

### ISSUE THREAD

**Issue by jason4wy** [saltstack/salt#40147]
### Description of Issue/Question
2017-03-20 04:40:39,177 [salt.minion      ][ERROR   ][2277] Error while bringing up minion for multi-master. Is master at cfg01 responding?
2017-03-20 04:40:49,228 [salt.crypt       ][ERROR   ][2277] The master key has changed, the salt master could have been subverted, verify salt master's public key
2017-03-20 04:40:49,229 [salt.crypt       ][CRITICAL][2277] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2016.11.3, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
on ubuntu 14.04

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
on ubuntu 14.04
salt-minion 2016.11.3 (Carbon)
salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@jason4wy the keys need to be the same for both masters in a  multi-master setup as documented [here](https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html#prepping-a-redundant-master) I'm guessing that might be what you are running into is you need the same key

**Comment by acoustic121** [comment]
hi There,i have installed one salt-master in my ubuntu and one salt-minion in my centos.
in my centos(salt-minion)machine,i have run command touch new.conf in cd etc/salt/minion.d and then wrote-
master: 10.0.2.15
master_port:4506
then restarted the minion but i am not able to send the minion key to master

ubuntu@salt-master-1:/etc/salt$ sudo salt-key
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:

master-
Sorry, try again.
[sudo] password for ubuntu: 
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[WARNING ] Unable to bind socket 0.0.0.0:4505, error: [Errno 98] Address already in use; Is there another salt-master running?
[INFO    ] The Salt Master is shut down
[DEBUG   ] Stopping the multiprocessing logging queue listener
[DEBUG   ] closing multiprocessing queue
[DEBUG   ] joining multiprocessing queue thread
[DEBUG   ] Stopped the multiprocessing logging queue listener
The salt master is shutdown. The ports are not available to bind

minion-
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/new.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/new.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 10.0.2.15
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "10.0.2.15"
[INFO    ] An instance is already running. Exiting the Salt Minion
[INFO    ] Shutting down the Salt Minion
[DEBUG   ] Stopping the multiprocessing logging queue listener
[DEBUG   ] closing multiprocessing queue
[DEBUG   ] joining multiprocessing queue thread
[DEBUG   ] Stopped the multiprocessing logging queue listener
The Salt Minion is shutdown.

Although both the salt master and minion are running
master:

ubuntu@salt-master-1:/etc/salt$ systemctl status salt-master
● salt-master.service - The Salt Master Server
     Loaded: loaded (/lib/systemd/system/salt-master.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-03-21 05:36:32 IST; 10h ago
       Docs: man:salt-master(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltstack.com/en/latest/contents.html
   Main PID: 24111 (salt-master)
      Tasks: 32 (limit: 2315)
     Memory: 231.4M
     CGroup: /system.slice/salt-master.service
             ├─24111 /usr/bin/python3 /usr/bin/salt-master
             ├─24118 /usr/bin/python3 /usr/bin/salt-master
             ├─24144 /usr/bin/python3 /usr/bin/salt-master
             ├─24145 /usr/bin/python3 /usr/bin/salt-master
             ├─24148 /usr/bin/python3 /usr/bin/salt-master
             ├─24149 /usr/bin/python3 /usr/bin/salt-master
             ├─24150 /usr/bin/python3 /usr/bin/salt-master
             ├─24157 /usr/bin/python3 /usr/bin/salt-master
             ├─24158 /usr/bin/python3 /usr/bin/salt-master
             ├─24159 /usr/bin/python3 /usr/bin/salt-master
             ├─24160 /usr/bin/python3 /usr/bin/salt-master
             ├─24161 /usr/bin/python3 /usr/bin/salt-master
             └─24163 /usr/bin/python3 /usr/bin/salt-master

Mar 21 05:36:30 salt-master-1 systemd[1]: Starting The Salt Master Server...
Mar 21 05:36:32 salt-master-1 systemd[1]: Started The Salt Master Server.


minion:
root@localhost salt]# systemctl status salt-minion
● salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2021-03-21 06:42:36 EDT; 13min ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 12725 (salt-minion)
    Tasks: 8 (limit: 8046)
   Memory: 69.7M
   CGroup: /system.slice/salt-minion.service
           ├─12725 /usr/bin/python3.6 /usr/bin/salt-minion
           ├─12734 /usr/bin/python3.6 /usr/bin/salt-minion
           └─12738 /usr/bin/python3.6 /usr/bin/salt-minion

Mar 21 06:48:17 localhost.localdomain salt-minion[12725]: [ERROR   ] Error while bringing up minion >
Mar 21 06:49:07 localhost.localdomain salt-minion[12725]: [ERROR   ] Error while bringing up minion >
Mar 21 06:49:57 localhost.localdomain salt-minion[12725]: [ERROR   ] Error while bringing up minion >
Mar 21 06:50:47 localhost.localdomain salt-minion[12725]: [ERROR   ] Error while bringing up minion >
Mar 21 06:51:37 localhost.localdomain salt-minion[12725]: [ERROR   ] Error while bringing up minion >
Mar 21 06:52:27 localhost.localdomain salt-minion[12725]: [ERROR   ] Error while bringing up minion >
Mar 21 06:53:17 localhost.localdomain salt-minion[12725]: [ERROR   ] Error while bringing up minion >
Mar 21 06:54:07 localhost.localdomain salt-minion[12725]: [ERROR   ] Error while bringing up minion >
Mar 21 06:54:57 localhost.localdomain salt-minion[12725]: [ERROR   ] Error while bringing up minion >

can someone please help on it
