### ISSUE TITLE
Syndic top-level 2016.11.3 master responding to sub-minion events 

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#40150]
### Description of Issue/Question
After upgrading a minion/master-syndic/top-level master topology to 2016.11.3, a minion_start event reactor fires twice, once from the minion's own master and once from the top-level master. Observing the mid-level master's logs you can see that one state.sls job run starts and the other fails due to the single-state running check. In rare instances both jobs fail due to some race condition where each job being run from the reactor sees the other state.sls job.

If the top-level master is downgraded to 2016.3.3 leaving all the other services at 2016.11.3 this does not happen so a change has definitely been introduced in 2016.11.3.

### Setup
Create one salt-master with a local minion on the top-level master.
Create one salt-master with local minion and a syndic process pointed to the top-level master
Create one salt-minion pointing to the mid-level master
Install a minion_start reactor on both the top-level and mid-level masters that will run a state.sls

### Steps to Reproduce Issue
Restart the top-level minion and it will only have one job run from the reactor
Restart the sub-level minion and it will run two jobs, one from it's master and one from the top-level master

### Versions Report
2016.11.3

**Comment by gtmanfred** [comment]
This is the expected behavior.  Both the syndic master and the master of masters should be able to react to the same event.

I am unable to replicate the behavior you are seeing with 2016.3 on the master, I see the event get triggered on the master of masters and the syndic master.

The solutions would be to only have syndics connected to the master of masters, or only have the reactor defined on the master of masters.

Thanks,
Daniel
