### ISSUE TITLE
[Feature request] Return Raspberry Pi model in grain 'productname'

### ISSUE THREAD

**Issue by Da-Juan** [saltstack/salt#40248]
### Description of Issue/Question

Raspberry Pis don't embark a BIOS so dmidecode doesn't return anything and grain `productname` is not set.

It would be nice to have the Raspberry Pi model as `productname`.

The model number can be found using the revision number in `/proc/cpuinfo` and the Board Revision History here: http://elinux.org/RPi_HardwareHistory#Board_Revision_History

Thanks! :smiley:

**Comment by gtmanfred** [comment]
I am marking this as a feature request.

If you could provide us with a pull request, we would greatly appreciate it.

Thanks!
Daniel

**Comment by Da-Juan** [comment]
Sorry I can't provide a pull request I'm not enough proficient in python to do it.

**Comment by aidanharris** [comment]
I don't know if this is specific to the ArchLinuxARM kernel but I noticed the following string printed in dmesg:

```sh
[    0.000000] Machine model: Raspberry Pi 3 Model B
```
If this is also present in other distros such as Raspbian and works for other Pi's, this could be a more reliable way to extract the productname instead of guessing from the CPU revision.

**Comment by Da-Juan** [comment]
I have a new job now and unfortunately I don't use Salt anymore.
It seems that I was the only one interested by this feature so let's close it.
