### ISSUE TITLE
_file_find unavailable on the master

### ISSUE THREAD

**Issue by mwtzzz** [saltstack/salt#40319]
the following error gets written 30x/second to /var/log/salt/master, wreaking havoc with disk i/o (disk %util goes from negligible to over 50% whenever this happens:

2017-03-25 10:51:48,063 [salt.master ][ERROR   ][22197] Received function _file_find which is unavailable on the master, returning False

I enabled log level debug on the master, but it did not add any additional information.

##
salt-master --version: salt-master 2016.3.2 (Boron)
salt-minion --version: salt-minion 2016.11.3 (Carbon)

**Comment by gtmanfred** [comment]
This is part of the fileclient, the minion is making calls for file_find on the master

To remedy this message, you will need to update the salt-master to 2016.11

https://docs.saltstack.com/en/latest/faq.html#can-i-run-different-versions-of-salt-on-my-master-and-minion

@terminalmage should this be an error?  It looks like it is caused by the changes with hash_and_stat_file.

https://github.com/saltstack/salt/blob/2016.11/salt/fileclient.py#L1308-L1311

@mwtzzz while it can still work, your minion won't be mirroring the file permissions on the minion cache, so that file_mode: keep can be used.

Thanks,
Daniel

**Comment by mwtzzz** [comment]
Thanks, I upgraded salt-master to 2016.11 and the error msgs went away.
