### ISSUE TITLE
userdata_file - How does this work?

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40413]
### Description of Issue/Question

I wanted to know how exactly "userdata_file" actually works. I am aware of what is user data but i am not sure how salt intends to utilize this feature in Profile or Providers.

**Comment by Ch3LL** [comment]
salt just copies that userdata file over and runs that script on initizliation of a VM. Does that clarify your question? Maybe you are asking something else if you could clarify?

**Comment by sumeetisp** [comment]
Is user_data more cloud provider specific? In the " Spinning windows minion" documentation it say that to open ports 445 and 5986 we can use user_data for passing script which will get executed and open the ports. But if the ports itself is not open then how will salt communicate with target? So i wanted to know how exactly user_data would work.

There are more parameter called "script"  and "file_map". What is difference between these 3?

**Comment by sumeetisp** [comment]
My question is more towards functionality. I am aware of the use.

**Comment by Ch3LL** [comment]
Thanks for clarifying I believe I understand what you are asking now. I just looked at the code and it looks like we are using requests python module to query the aws api, and we include the `UserData` parameter when making the api call. So then the magic happens on AWS which I believe on their end they run that script on initialization of the VM when they see UserData in the api call paramaters.

Can @gtmanfred confirm my interpration of the code and aws though since I am not an expert in this area.
