### ISSUE TITLE
single env, multple gitfs repos does not merge top.sls from those repos.

### ISSUE THREAD

**Issue by leonkatz** [saltstack/salt#40592]
Setup master with multiple gitfs repos. Each repo has a top file for the same env. The env is set in the master config. top_file_merging_strategy: merge_all.(But tried all the options) Top files are not merged. Only the first(top most) gitfs repo in the config, has its top file used. Seems to also be happenning with file_roots: - git / -root /. Whichever is at the top will have its top file read, not the next or all like they should. All states are available and can be used in that single top file. Would be nice if they actually merged top files.

**Comment by gtmanfred** [comment]
This is the expected behavior.

merge_all is only for between environments.

you would need to have more environments for it to merge all the top files.

https://docs.saltstack.com/en/latest/ref/file_server/file_roots.html#directory-overlay

Because of the directory overlay, it will only use the first top.sls file it finds in that environment in any of the environment sources.

Thanks,
Daniel
