### ISSUE TITLE
Modules executed from pillar SLS files are executed locally, not remotely, using Salt-SSH

### ISSUE THREAD

**Issue by AndrewPashkin** [saltstack/salt#40628]
### Description of Issue/Question
To my surprise I've discovered, that modules, that are called from pillar SLS files are executed locally instead of on the remote machine.

For example `salt['cmd.shell']('hostname')` called from a pillar returns local hostname.

Is that by design?

### Versions Report
```
$  salt-ssh --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
 
System Versions:
           dist: LinuxMint 18.1 serena
        machine: x86_64
        release: 4.4.0-72-generic
         system: Linux
        version: LinuxMint 18.1 serena
```

**Comment by gtmanfred** [comment]
This happens on the regular master too.

Pillars are rendered on the master, not on the minion.

https://docs.saltstack.com/en/latest/topics/pillar/#storing-static-data-in-the-pillar

```
Note
Storing sensitive data

Pillar data is compiled on the master. Additionally, pillar data for a given minion is only accessible by the minion for which it is targeted in the pillar configuration. This makes pillar useful for storing sensitive data specific to a particular minion.
```

Thanks,
Daniel

**Comment by AndrewPashkin** [comment]
@gtmanfred 
> Pillar data is compiled on the master.

Does not actually imply that modules are executed on master. Pillar could be compiled on master (which does make sense) but it doesn't prevent Salt from executing modules on the target machine (which makes much more sense than executing them on master).

**Comment by whiteinge** [comment]
Because Pillar is compiled on the Master it has access to all the things you can do from the Master, and that does include [sending a job down to Minions](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.cmd) and waiting for the return.

You are free to wire that up if you choose to, however that is a very heavy operation and Pillar must be compiled once for each requesting Minion. Pillar was written with the intent to be compiled as quickly as possible -- something essential for large minion head-counts -- and so usually it's best to compile Pillar using Minion data that is already cached on the Master such as Grains. The [Salt Mine](https://docs.saltstack.com/en/latest/topics/mine/) system allows you to cache your own arbitrary Minion-side data. And in all cases, whatever you decide to use will work more slowly and less automatically when using the SSH transport due to the inherent limitations there.

**Comment by gtmanfred** [comment]
You could also use the `saltutil.runner` module to look up information directly in the grains cache or in the mine.

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.cache.html#salt.runners.cache.mine

And if you wanted to query minions directly, you can use the publish.publish module.

https://docs.saltstack.com/en/latest/ref/peer.html

Thanks,
Daniel

**Comment by AndrewPashkin** [comment]
@whiteinge, @gtmanfred, my point is that it doesn't make sense to execute modules on master. It might be even dangerous if you have some external pillars. And while executing in on minion might be not an optimal solution it makes much more sense.

**Comment by gtmanfred** [comment]
We have discussed the dangerous part, even as recently as yesterday https://github.com/saltstack/salt/issues/40586

as for rendering the pillars, it is not secure to render them on the minion because these could be gated by jinja or other functions, and if you just send the whole file down, the minion could see information that it might not be supposed to see.

Specifically the jinja in the pillar is not meant to be run on minions, it is meant to be run on the master, that was the way it was designed.  It was just to allow the use of modules on the master to make decisions.  This is also one of the reasons that things like [saltutil.cmd](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.cmd) exist, so that if you do want to, you can run commands against minions.

**Comment by AndrewPashkin** [comment]
@gtmanfred, I'm not proposing rendering them on minions (which is inherently not secure as well), I'm just proposing forwarding calls to the modules to the current minion.
