### ISSUE TITLE
dockerng.image_absent does not support a timeout, will fail when removing an image with many layers

### ISSUE THREAD

**Issue by tkent** [saltstack/salt#40687]
### Description of Issue/Question

The `dockerng.image_absent` state, nor the associated `dockerng.rmi` module, supports a client_timeout (like  `dockerng.create` and others do). This is needed because the default timeout is 60 seconds, so any operation that may take more than that will need to have the timeout overwritten.

### Setup

Here is an SLS that will show the issue on a lower-powered hardware system (e.g. an AWS t2.medium system, chose any linux OS you'd like that runs docker).

```
ossec-image-pulled:
  dockerng.image_present:
    - name: "xetusoss/ossec-server:2.8.2"

ossec-image-deleted:
  dockerng.image_absent:
    - require:
      - dockerng: ossec-image-pulled
    - name: "xetusoss/ossec-server:2.8.2"
```

### Steps to Reproduce Issue
Run the above SLS. You'll see the ossec-image-deleted state always reports a failure due to a timeout.

### Versions Report
The minion version report
```
Salt Version:
           Salt: 2016.11.0-n/a-3416e9e
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 1.7.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-110-generic
         system: Linux
        version: Ubuntu 14.04 trusty

```

### Suggested fix

I think the fix here is to allow all the DockerClient calling modules/states to specify a timeout. Since we need it for a few of the modules/states, we'll be sending along a pull request later for the ones we've ran into.

**Comment by gtmanfred** [comment]
Yup, it looks like we need to add support for that to rmi. Would you be able to submit a PR for this?

Thanks for reporting.
Daniel

**Comment by tkent** [comment]
@gtmanfred 

We certainly can - but it looks like the current develop branch's docker stuff is very broken :-(. It's going to take a bit longer than expected.

The new `docker_image.present` state and `dockermod.pull` both now accept a client_timeout keyword arguments. The thing is, the corresponding DockerClient functions do not accept the client_timeout option there. This results in a runtime error and pulling images don't work.

Once I've traced down the commit that added it, I'll reference this and send along a pull request that patches it up.

**Comment by tkent** [comment]
@gtmanfred  

I've hit another issue, which appears to be pre-existing, that makes it impossible to reliably apply a `client_timeout` from any docker state. There are a few ways to fix this pre-existing issue, but I think I should get guidance from @terminalmage on what he would like me to do since it's a core part of the module operation.

@terminalmage, here's the short version:

Since [_docker_client()](https://github.com/saltstack/salt/blob/38e179388365c2bcef87b32285d0f39f80b60094/salt/modules/dockermod.py#L382-L395) caches the docker client in the `__context__` dunder, all calls to any `@_docker_client` annotated function will re-use the *first* docker client created.

That's an issue, since each docker client instance has its own client timeout, and different operations may need different timeouts. This comes up for states since they often make several `dockermod` calls to determine if changes need to be made. And, typically the first calls are for change detection and don't specify a non-default timeout.

Hopefully that makes sense and I can pretty easily throw together some code to demonstrate the issue if this isn't clear.

Anyway, I have an overly-simple fix in place locally, where I just re-assign the docker-py client in the `__context__` module each time `_docker_client()` is called. This works, but I really doubt that's what you'd want. I noticed from your comments in c526e8c7b0fd9299e18737a13edf092c51545579 that you're re-writing a lot of this already, and seemed to already want to remove docker client caching in the modue.

So, my questions:

1. Where would you like me to communicate about this? A separate issue, or just keep on this thread?
2. How would you like me to resolve this issue? Remove the @_docker_client annotation usage since caching isn't important? Create a utility to just create the client when needed? Or, should I not touch it since I know you're doing other re-write work?

**Comment by terminalmage** [comment]
The ``client_timeout`` in docker-py isn't an overall timeout for the action, it's a timeout for response from the API. Are you saying that it takes longer than the default timeout to remove that image?

For actions which involve pulling/pushing layers, Salt uses ``stream=True`` when invoking the functions. This results in a near-immediate response back from the API, followed by several events as the individual layers are processed.

The best fix for this is probably to make ``rmi()`` also process a stream of events, rather than just waiting for results. We should not be making the user manually set a timeout to make removal of an image work.

I can handle this fix.

**Comment by tkent** [comment]
@terminalmage  Thanks for the quick response! 

I apologize, I may not have been clear. It does take the API longer than the default timeout to respond when removing an image with many layers. You can reproduce the issue with the little sls snippet I included in the report, using a t2.medium AWS system. It takes about 70-80 seconds to complete, just over the 60 second default. It's not a common thing to have so many layers, but we clearly hit it.

The work around we have for now is pretty easy, just to use a `cmd.run` state with a long timeout, but we're a big fan of using the docker states :-).

I want to push a little bit on the client thing in my most recent comment. I'm sorry if I'm just completely missing the boat here, but here's what I believe I see happening:

1. In the salt docker modules and states, `client_timeout` is settable for some actions, but not all. It seems to have been only where it made sense, such as the `pull` action (though it's actually not needed for `pull` because the docker api [disables the client timeout under the hood anyway](https://github.com/docker/docker-py/blob/f127a9ffdc9db1a946c3d7943eaf16b207f33598/docker/api/image.py#L365-L368))
2. Due to how the client is cached in the `__context__` dunder, you can't have different `client_timeout` values for different actions. The easiest way to highlight what I'm seeing is in [docker_image.py](https://github.com/saltstack/salt/blob/38e179388365c2bcef87b32285d0f39f80b60094/salt/states/docker_image.py#L343-L385). Here the first few Docker API calls don't specify a timeout, and probably don't need too since they are just quick check actions. However, the delete action __will__ need a custom timeout, but can't have one because the Docker API client was already created in the previous calls and is now cached.

**Comment by terminalmage** [comment]
Yes, I understand both points. What I'm saying is that the better fix is to restructure the ``rmi()`` func such that it processes streamed results. Separately, we can also look at ways of letting the passed timeout override the client's ``timeout`` attribute (at least for the life of the function). But the greater point here is that you should _never_ be forced to set a timeout variable just to remove a larger-than-standard image, and processing streamed results (like we do for push/pull) will result in a near-immediate response from the docker daemon, so that it never hits the client timeout.

The current way that ``rmi()`` works is that it fires off an API command and waits for all of the results to come in once finished. So the API response comes only when docker has completed the removal. Processing streamed results will keep this timeout from ever being reached because updates will come in for each layer, and the first response back will keep that timeout from being triggered.

**Comment by tkent** [comment]
Ah, I follow what you're saying. Sorry to be slow on that and thanks for tackling this!

**Comment by terminalmage** [comment]
@tkent Within the last 24 hours we fixed some problems with the ``client_timeout`` value. This is a salt-ism and should have been popped off of the arguments before we pass them on to docker-py. But what happend is we were passing the kwargs using ``**kwargs`` and popping the ``client_timeout`` in that function, which of course wouldn't have popped them from the original ``kwargs`` dict because using the double-asterisk results in the calling function's kwargs dict being a new dict altogether.

The fix was submitted to https://github.com/gtmanfred/salt/pull/3 so @gtmanfred could verify it worked with some stuff he was working on, and it has been backported to the ``nitrogen`` feature release branch as well. This fix also may help alleviate the problems you're having with removing the image in that it will override, and then restore the cached client instance's timeout afterward. So, this will let you specify a longer ``client_timeout`` to get ``rmi()`` to finish.

However, the long term fix for this still is to make ``rmi()`` process streamed events.

**Comment by tkent** [comment]
@terminalmage Thanks for the update! I'll wait for that change to make it's way back into the saltstack/salt repo and then pull it into our custom 2016.11 branch.

I'm much happier to use `dockerng.image_absent`, specifying the `client_timeout` until the longer term fix is in, than our cmd.run workaround.

p.s. that was nice reminder about the behavior of `**kwargs`. I spend most my time in java/groovy/kotlin and hadn't thought about that for years. You intuitively think "that's just a pass by reference, nothing to see here".

**Comment by terminalmage** [comment]
I've also retroactively added a more visible explanation of the dockerng changes in 2016.11.4 to the release notes in PR https://github.com/saltstack/salt/pull/40936.

**Comment by terminalmage** [comment]
Oh, sorry, that comment was meant for a _different_ docker report. Please disregard. :)

**Comment by terminalmage** [comment]
@tkent yes, an easy mistake to make. Thanks for helping bring it to light. :smile:

**Comment by terminalmage** [comment]
@tkent It looks like it's not going to be possible to used streamed results, as the Docker API doesn't support it:

* [Docker Engine API docs](https://docs.docker.com/engine/api/v1.26/#operation/ImageDelete)
* [docker-py docs](http://docker-py.readthedocs.io/en/stable/api.html#docker.api.image.ImageApiMixin.remove_image)

Notice that there is no ``stream`` argument there.

However, the fix I submitted a few weeks ago will allow the timeout passed on the CLI to work properly for ``dockerng.rmi``, allowing you to set the longer timeout that you need. Given that, I'm going to close this issue. The fix will be present in the Nitrogen release, due in a few weeks.
