### ISSUE TITLE
Feature: configure template engine (ie: jinja2) defaults

### ISSUE THREAD

**Issue by epcim** [saltstack/salt#41043]
### Description of Issue/Question

Use case, configure inline comment prefix "##" characters for state .sls files.
https://github.com/pallets/jinja/blob/master/jinja2/defaults.py#L23

Especially talking about being able to use inline comments:

```
...
...                         
  - require:
    - pkg: nginx_packages
  
{%- endif %} ## ssl.chain

{%- endif %} ## ssl.key
  
{%- endif %} ## ssl.engine not defined

```
For more details search "Line statements": http://jinja.pocoo.org/docs/2.9/templates/#synopsis 

### Notes

I am actually looking for help, where to start implementation. If I do understand it should go here: https://github.com/saltstack/salt/blob/a33b8f81f7a29d0da54a88240771a41f489954c1/salt/utils/templates.py#L316

**Comment by epcim** [comment]
Relates:
https://github.com/saltstack/salt/issues/24494
https://github.com/saltstack/salt/issues/21217

**Comment by gtmanfred** [comment]
That would be great if you wanted to submit a PR that allowed for some of these features to be turned on.

I don't think we want to turn them on by default because there are people that use the comments and still use jinja behind them, and we wouldn't want to break their setups.

I am marking this as a feature request.

Thanks!
Daniel
