### ISSUE TITLE
maintain slack connection for returner

### ISSUE THREAD

**Issue by nomeelnoj** [saltstack/salt#41188]
My apologies if this is a duplicate, but I could not find it anywhere else.

We have Salt set up to post output to slack (my testing showed that I had to configure this as a returner on each minion, as configuring it on the master did not send output to slack).

I am seeing in the salt logs and more importantly in the Slack access logs that the saltstack bot I created for this integration is connecting to slack hundreds of times per hour.  The output of 

`salt-run state.event pretty=True`

shows in the event bus that salt is connecting and reconnecting to slack quite frequently, and is FILLED with entries like this:

```salt/engines/slack/presence_change	{
    "_stamp": "2017-05-11T07:29:38.384992", 
    "presence": "active", 
    "type": "presence_change", 
    "user": "<redacted>"
}
salt/engines/slack/reconnect_url	{
    "_stamp": "2017-05-11T07:29:45.671353", 
    "type": "reconnect_url", 
    "url": "wss://mpmulti-otcw.slack-msgs.com/websocket/cOAtIxjbTC3IYVZlqOq<truncated_for_space>"
}
salt/engines/slack/presence_change	{
    "_stamp": "2017-05-11T07:30:00.389536", 
    "presence": "away", 
    "type": "presence_change", 
    "user": "<redacted>"
}
salt/engines/slack/presence_change	{
    "_stamp": "2017-05-11T07:30:01.389628", 
    "presence": "active", 
    "type": "presence_change", 
    "user": "<redacted>"
}
salt/engines/slack/presence_change	{
    "_stamp": "2017-05-11T07:30:48.399877", 
    "presence": "away", 
    "type": "presence_change", 
    "user": "<redacted>"
}
```

The biggest issue here is that this is filling up our Slack access logs and making it very difficult to sort through and find valid access logs for our actual users.

Is this expected behavior based on how the slack returner is built?  I assume this is because each minion is establishing a connection, but **all I want is the output of all salt commands to show up in a slack channel**, and configuring the returner on the master does not accomplish this.  Is there a way to change it so it doesn't attempt a connection every few seconds, but holds an open connection? Or rather, set it up so that configuring the returner on the master shows all output I would normally see in the master console mirrored to a slack channel of my choosing?

Any information would be appreciated, the documentation available for the slack returner is limited.

Thanks!

### Versions Report
```Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-92-generic
         system: Linux
        version: Ubuntu 14.04 trusty```

**Comment by gtmanfred** [comment]
If you are using slack as a returner, the minions will all connect to slack individually, and post their message and then disconnect.  I believe that this is a limitation of how the slack api works.  If you do not use websockets to communicate it then has to reconnect for every call, or appears to reconnect for each message.

Because of the multiprocess nature of the minion, I also don't believe we have anything written that would be able to share a websocket connection.

I am going to mark this as a feature request to keep the same connection open for the returner and share it between multiple returns.

Thanks,
Daniel

**Comment by nomeelnoj** [comment]
I think it would be best if it were possible to configure the slack returner on the master, so that all the output from every minion would return to the slack channel from a single "user", and then configure that connection to rename open for several hours at a time.  Thanks!

**Comment by gtmanfred** [comment]
The problem with configuring it on the master is that it would have to be a master_job_cache, which would require it be possible for the master to lookup the jids.

I think the best way to do this would be to use some stuff from the slack engine, and watch the event bus, and rewrite it to only publish minion returns to slack.

**Comment by absolutejam** [comment]
Sorry to chime in, but does this link in with https://github.com/saltstack/salt/issues/36573 ?

Should it be possible to set the Slack returner via. `master_job_cache`? Currently I'm getting a traceback.

**Comment by gtmanfred** [comment]
You cannot do that, because there is no way to look up the jid after the
fact. This is required to be used as the job cache and not a returner

**Comment by absolutejam** [comment]
Slack is one of the examples in https://docs.saltstack.com/en/latest/topics/jobs/external_cache.html and it seems like we should aim to have returners work on either minion or master, right?

Is this something I'd be able to implement based on another returner, or am I missing the difference between a master job cache?

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by grandmasterv** [comment]
I finally found this issue when trying to figure out why I'm getting errors like this on the master and can't configure the Slack returner to work on the master.  

`[CRITICAL] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry.`

Or this one when I tried to configure both slack returner and the local_cache via the multi_returner:

`[ERROR   ][37723] Failed to allocate a jid. The requested returner 'multi_returner' could not be loaded.`

Slack is used in the documentation example for configuring returners.  There does not seem to be any mention of returners supporting a master or minion configuration only.  I figured a returner could be configured on either but this does not seem to be the case.  I really feel this needs to be clarified in the docs shouting out if a returner supports master, minion, or both!

I hope my addition of those error messages helps others find this issue.
