### ISSUE TITLE
Windows minion does not start if salt is not in path

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#41199]
Hi,

https://github.com/saltstack/salt/blame/v2016.11.4/salt/utils/verify.py#L534 block the minion from bring installed in any path that doesn't contain 'salt'.

This only affects windows minion.

If minion is installed in another path the specific loop runs fir ever without exiting.

**Comment by tsaridas** [comment]
Ping @twangboy

**Comment by gtmanfred** [comment]
Thanks for reporting this.
Daniel

**Comment by twangboy** [comment]
@tsaridas In what path do you have salt installed?

**Comment by tsaridas** [comment]
I have it at 
c:\Agent\
but I'll try to move it to program files

**Comment by twangboy** [comment]
@tsaridas For now Salt is installed at `c:\salt` by default. We haven't tested putting salt in other locations. Even you do move salt to another location, the default path for config, file_roots, and my other things, is located in `c:\salt`. I recommend you place your salt installation at `c:\salt`.

**Comment by tsaridas** [comment]
@twangboy I don't have the option to have salt in the default path due to conflicts with other teams.

I have already created an nsis package that installs salt to the dir specified. I only had to specify file_roots and logs to the minion config file and everything seems to work correctly until now.

I had to add my agent's folder name to the list of the loop mentioned.

**Comment by twangboy** [comment]
@tsaridas The fix for this is to make salt support installation into locations other than `c:\salt`. This may be something that we add to the next major release (Oxygen)... assuming that gets added to the roadmap.

In the meantime, you might try installing salt into `c:\agent\salt`. The only thing the `win_verify_env` cares about is that the last directory where Salt resides is called `salt`. Would mind giving that a try?

**Comment by tsaridas** [comment]
@twangboy ,
I have already done what you suggested and works well.
thanks

**Comment by twangboy** [comment]
Created issue to track the feature request.
