### ISSUE TITLE
undefined symbol: SSLv2_method while using M2Crypto 0.25.1

### ISSUE THREAD

**Issue by viru19192** [saltstack/salt#41276]
### Description of Issue/Question
 File "runserver.py", line 11, in <module>
    from commandment.app import create_app
  File "/root/python-mdm/commandment/app.py", line 7, in <module>
    from .mdm import mdm_app
  File "/root/python-mdm/commandment/mdm.py", line 8, in <module>
    from .pki.ca import get_ca, PushCertificate
  File "/root/python-mdm/commandment/pki/ca.py", line 11, in <module>
    from m2certs import RSAPrivateKey, Certificate, CertificateRequest, Identity, NID_userId
  File "/root/python-mdm/commandment/pki/m2certs.py", line 12, in <module>
    from M2Crypto import EVP, RSA, BIO, X509, ASN1, m2
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, util
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/BIO.py", line 10, in <module>
    from M2Crypto import m2, util
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto._m2crypto import *
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/_m2crypto.py", line 26, in <module>
    __m2crypto = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/_m2crypto.py", line 22, in swig_import_helper
    _mod = imp.load_module('__m2crypto', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/M2Crypto/__m2crypto.so: undefined symbol: SSLv2_method
root@mdm:~/python-mdm# /M2Crypto/__m2crypto.so: undefined symbol: SSLv2_method
-bash: /M2Crypto/__m2crypto.so:: No such file or directory

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
pip install M2Crypto==0.25.1
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt 2016.11.5 (Carbon)
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
@viru19192 could you elaborate when you are seeing this error? What command are you running? I have this same version of M2Crypto  and have not seen that error with regular salt use.

**Comment by viru19192** [comment]
after install M2Crypto==0.25.1

I have added PUSH Certificate and other pem certificate and when i restart server it shows me this error.

**Comment by rlaing00** [comment]
I am currently experiencing the same issue at present, this is output from my state which is based on the example in the x509 docs

`[INFO    ] Completed state [/etc/pki/ca.crt] at time 14:01:49.577696 duration_in_ms=480.666
[DEBUG   ] LazyLoaded module.run
[DEBUG   ] File /var/cache/salt/minion/accumulator/139854853919312 does not exist, no need to cleanup.
[DEBUG   ] Minion return retry timer set to 6 seconds (randomized)
[INFO    ] Returning information for job: 20170621140146899469
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506')
[INFO    ] User sudo_ubuntu Executing command state.sls with jid 20170621140237143776
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20170621140237143776', 'tgt': 'ca', 'ret': '', 'user': 'sudo_ubuntu', 'arg': ['ca'], 'fun': 'state.sls'}
[INFO    ] Starting a new job with PID 18884
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded direct_call.get
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506')
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'ca.sls' to resolve 'salt://ca.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/ca.sls' to resolve 'salt://ca.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/ca.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/ca.sls' using 'jinja' renderer: 0.00341415405273
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/ca.sls:
salt-minion:
  service.running:
    - enable: True
    - listen:
      - file: /etc/salt/minion.d/signing_policies.conf

/etc/salt/minion.d/signing_policies.conf:
  file.managed:
    - source: salt://signing_policies.conf

/etc/pki:
  file.directory: []

/etc/pki/issued_certs:
  file.directory: []

/etc/pki/ca.crt:
  x509.certificate_managed:
    - signing_private_key: /etc/pki/ca.key
    - CN: ca.example.com
    - C: US
    - ST: Utah
    - L: Salt Lake City
    - basicConstraints: "critical CA:true"
    - keyUsage: "critical cRLSign, keyCertSign"
    - subjectKeyIdentifier: hash
    - authorityKeyIdentifier: keyid,issuer:always
    - days_valid: 3650
    - days_remaining: 0
    - backup: True
    - managed_private_key:
        name: /etc/pki/ca.key
        bits: 4096
        backup: True
    - require:
      - file: /etc/pki

mine.send:
  module.run:
    - func: x509.get_pem_entries
    - kwargs:
        glob_path: /etc/pki/ca.crt
    - onchanges:
      - x509: /etc/pki/ca.crt

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('salt-minion', OrderedDict([('service.running', [OrderedDict([('enable', True)]), OrderedDict([('listen', [OrderedDict([('file', '/etc/salt/minion.d/signing_policies.conf')])])])])])), ('/etc/salt/minion.d/signing_policies.conf', OrderedDict([('file.managed', [OrderedDict([('source', 'salt://signing_policies.conf')])])])), ('/etc/pki', OrderedDict([('file.directory', [])])), ('/etc/pki/issued_certs', OrderedDict([('file.directory', [])])), ('/etc/pki/ca.crt', OrderedDict([('x509.certificate_managed', [OrderedDict([('signing_private_key', '/etc/pki/ca.key')]), OrderedDict([('CN', 'ca.example.com')]), OrderedDict([('C', 'US')]), OrderedDict([('ST', 'Utah')]), OrderedDict([('L', 'Salt Lake City')]), OrderedDict([('basicConstraints', 'critical CA:true')]), OrderedDict([('keyUsage', 'critical cRLSign, keyCertSign')]), OrderedDict([('subjectKeyIdentifier', 'hash')]), OrderedDict([('authorityKeyIdentifier', 'keyid,issuer:always')]), OrderedDict([('days_valid', 3650)]), OrderedDict([('days_remaining', 0)]), OrderedDict([('backup', True)]), OrderedDict([('managed_private_key', OrderedDict([('name', '/etc/pki/ca.key'), ('bits', 4096), ('backup', True)]))]), OrderedDict([('require', [OrderedDict([('file', '/etc/pki')])])])])])), ('mine.send', OrderedDict([('module.run', [OrderedDict([('func', 'x509.get_pem_entries')]), OrderedDict([('kwargs', OrderedDict([('glob_path', '/etc/pki/ca.crt')]))]), OrderedDict([('onchanges', [OrderedDict([('x509', '/etc/pki/ca.crt')])])])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/ca.sls' using 'yaml' renderer: 0.0070378780365
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] Module DSC: Only available on Windows systems
[DEBUG   ] LazyLoaded service.start
[DEBUG   ] LazyLoaded service.running
[INFO    ] Running state [salt-minion] at time 14:02:39.173218
[INFO    ] Executing state service.running for salt-minion
[INFO    ] Executing command ['systemctl', 'status', 'salt-minion.service', '-n', '0'] in directory '/root'
[DEBUG   ] stdout: * salt-minion.service - The Salt Minion
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-06-21 14:01:49 UTC; 49s ago
  Process: 18834 ExecStart=/usr/bin/salt-minion (code=exited, status=1/FAILURE)
 Main PID: 18834 (code=exited, status=1/FAILURE)
[DEBUG   ] retcode: 3
[INFO    ] Executing command ['systemctl', 'is-active', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: failed
[INFO    ] Executing command ['systemctl', 'is-enabled', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: enabled
[INFO    ] Executing command ['systemctl', 'is-enabled', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: enabled
[DEBUG   ] Service 'salt-minion' is not masked
[INFO    ] Executing command ['systemd-run', '--scope', 'systemctl', 'start', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: Running scope as unit run-rabd11515bc3a45358181e6b67b53e7b0.scope.
Failed to open /dev/tty: No such device or address
[INFO    ] Executing command ['systemctl', 'is-active', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: active
[INFO    ] Executing command ['systemctl', 'is-enabled', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: enabled
[INFO    ] Executing command ['systemctl', 'is-enabled', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: enabled
[INFO    ] {'salt-minion': True}
[INFO    ] Completed state [salt-minion] at time 14:02:39.313797 duration_in_ms=140.579
[DEBUG   ] LazyLoaded file.managed
[INFO    ] Running state [/etc/salt/minion.d/signing_policies.conf] at time 14:02:39.315608
[INFO    ] Executing state file.managed for /etc/salt/minion.d/signing_policies.conf
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506')
[DEBUG   ] In saltenv 'base', looking at rel_path 'signing_policies.conf' to resolve 'salt://signing_policies.conf'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/signing_policies.conf' to resolve 'salt://signing_policies.conf'
[INFO    ] File /etc/salt/minion.d/signing_policies.conf is in the correct state
[INFO    ] Completed state [/etc/salt/minion.d/signing_policies.conf] at time 14:02:39.334576 duration_in_ms=18.968
[INFO    ] Running state [/etc/pki] at time 14:02:39.334764
[INFO    ] Executing state file.directory for /etc/pki
[INFO    ] Directory /etc/pki is in the correct state
[INFO    ] Completed state [/etc/pki] at time 14:02:39.335466 duration_in_ms=0.702
[INFO    ] Running state [/etc/pki/issued_certs] at time 14:02:39.335625
[INFO    ] Executing state file.directory for /etc/pki/issued_certs
[INFO    ] Directory /etc/pki/issued_certs is in the correct state
[INFO    ] Completed state [/etc/pki/issued_certs] at time 14:02:39.336320 duration_in_ms=0.694
[DEBUG   ] LazyLoaded x509.certificate_managed
[INFO    ] Running state [/etc/pki/ca.crt] at time 14:02:39.337182
[INFO    ] Executing state x509.certificate_managed for /etc/pki/ca.crt
...................++
...........................................++
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1704, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/x509.py", line 494, in certificate_managed
    new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 1492, in create_certificate
    passphrase=kwargs['signing_private_key_passphrase'])
  File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 679, in get_public_key
    text = get_pem_entry(text)
  File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 472, in get_pem_entry
    raise salt.exceptions.SaltInvocationError(errmsg)
SaltInvocationError: PEM text not valid:
/etc/pki/ca.key

[INFO    ] Completed state [/etc/pki/ca.crt] at time 14:02:39.626517 duration_in_ms=289.334
[DEBUG   ] LazyLoaded module.run
[DEBUG   ] File /var/cache/salt/minion/accumulator/139854853939856 does not exist, no need to cleanup.
[DEBUG   ] Minion return retry timer set to 10 seconds (randomized)
[INFO    ] Returning information for job: 20170621140237143776
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ca', 'tcp://192.168.60.10:4506')`

**Comment by rlaing00** [comment]
Please let know if there is any more information you require from myself on the topic
