### ISSUE TITLE
Salt state distribution  and packaging 

### ISSUE THREAD

**Issue by talktosaswat** [saltstack/salt#41343]
### Description of Issue/Question
I have few states created for installing various application and database. Which is the best approach for packaging and reuse them on different salt masters independent of minion.  I found Salt formula and SPM ( Salt package manager ) .  Which is the best approach for productive environment ?

Also could you please suggest if it is good to keep salt formula and   download directly from github ? 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
latest salt open source version

**Comment by Ch3LL** [comment]
@talktosaswat have you thought of using gitfs with a repo you manage? That's also a possibility and you could just use the gitfs settings to point to those states on each master.

salt-formulas are managed by the community so the stability of each formula depends on the user creating the formula, but you can open issues on each saltstack-fromula if you run into a problem. If using gitfs with the salt-formulas keep in mind if there are any changes to the formulas repo you will see those changes. So this means if there is a bug introduced into that formula you will see it. 

spm is officially supported and managed by the saltstack team. Its a great way to deploy salt states across masters it also includes versioning which is a nice feature to ensure your states are at the correct version you would expect.

Another solution is to combine spm and salt-formulas, and package the salt-formulas so you know what version of a sls file you are on.

So to answer your question I don't think there is one best way to do this, but I have outlined what sort of support would be expected with each of these options and I think that will help you to make a decision. Closing since this is a question, but please let me know if that does not accurately answer you question and we can re-open.

**Comment by talktosaswat** [comment]
Can you please refer some document pointing to gifts . Also If we write our own formula without SPM , Is it robust for use between multiple salt masters. I was thinking SPM is still in review mode. Can I use SPM + Formula on open source version ?
