### ISSUE TITLE
certutil.add_store does not work on non english windows versions or on Windows 10 (localised or English)

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#41367]
Hi,

the certutil module for windows does not work on any non English versions of Windows, nor does it work on an English version of Windows 10.

The certutil module uses the certutil.exe binary, which is localised.
Furthermore, said binary has a slightly different output on Windows 10, which is why is fails even on an English version of Windows 10.

Ideally, this module would stop using certutil.exe, and instead would either use powershell or winapi to managed certificates.

Note that there are quite a few modules that are plagued by this type of issue.
Ideally, windows modules that rely the output of windows binaries would be tested on English and non English versions of Windows.

**Comment by Ch3LL** [comment]
@twangboy are you okay on changing the from certutil to a powershell or winapi command here?

**Comment by twangboy** [comment]
@Ch3LL I'm fine with that.

**Comment by morganwillcock** [comment]
I think that the easiest solution here is to adjust the functions to match the sha1 hash instead of the certificate's serial. I don't think that the serial numbers are guanteed to be unique anyway and I would think that the printing of the hash type is language independent (I've checked English and French, but would need to try something more exotic to confirm). I would be happy to give it a go, or try it with ctypes if you think matching the hash is the wrong approach. I would think Powershell will have the same type of locale issues.

**Comment by lubyou** [comment]
Hi,

Yes, the hash should be compared, as the serial is not guaranteed to be unique.

Powershell should not have the localisation issues, as you are basically working with .net objects where the name of all the properties, methods etc of the objects  do not change.

A wrapper around the native API's with ctypes or cffi would of course be even nicer, as you have more control and can avoid the extra time that is spent on launching powershell.

**Comment by morganwillcock** [comment]
It looks like the win_certutil module and state are effectively replaced by the win_pki module and state, which is implemented using Powershell.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_pki.html

**Comment by lubyou** [comment]
Not sure how I missed that, looks like it is addressing the issues that I raised.

Thanks for pointing that out @morganwillcock
