### ISSUE TITLE
Issue while using salt-ssh along with map file

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41624]
### Description of Issue/Question

I have a following map file,

```aws-linux-ssh:
  QE_02_DEL:
    minion:
      startup_states: top.sls
    grains:
      roles:
        - mysql
      packages:
```

After executing this i expected a grain called roles to be listed when i did a grains.items but it did not.

**Comment by gtmanfred** [comment]
That is not going to work, because the minion through salt-ssh uses /var/tmp/.salt-*/ as the rootdir, which will have a different grains file.

This is not supported and it would be difficult, because of the grains being passed to the minion from salt-ssh do not use /etc/salt/grains.  If you want to use that ability, you would need to use master + minion, or use pillars to assign those values to the minion.
