### ISSUE TITLE
salt.modules.win_pki dependencies are not documented

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#41633]
Hi,

the new win_pki module depends on the PKI module, which in turn requires powershell 4 and Windows 8+.
The dependencies are mentioned in the source code only.

Did saltstack drop support for Windows 7?

**Comment by gtmanfred** [comment]
We should still be supporting windows 7.  There are sometimes limitations on new modules that get added which might require newer versions of stuff based on tools that are available.  For example, the firewalld module is only supported on centos/rhel 7, because versions before that do not have firewalld at all.

Because of that I am actually going to mark this as a feature request to make win_pki module work with Windows 7.

@twangboy and @m03  could you take a look at this?

Thanks,
Daniel

**Comment by twangboy** [comment]
This module is specific to the PKI Client powershell module that is only available on Windows 8+ and Windows Server 2012+. The above PR adds some addional checks to the `__virtual__` and documents the requirement for Windows 8+ and Windows Server 2012+.
