### ISSUE TITLE
How would I or is there a process for migrating a Salt master to a new server?

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#41713]
### Description of Issue/Question

I need to move my existing salt-master off a RHEL6 server to a new RHEL7 server.   If possible I'd like to keep the keys and any other config etc so ideally I want to be able to simply change the DNS record and have clients connect tot the new server and work OK. is this possible? and if so how?

**Comment by Ch3LL** [comment]
You will need to rsync files in /etc/salt/ and of course any other files you want to migrate for your salt instance such as your pillar and file roots to the new server. I did find this issue here https://github.com/saltstack/salt/issues/10032 that will impact your planned migration so you will need to workaround this. I am guessing you could possibly schedule a minion restart with cron? So for example run a state that adds a cron job or uses the salt scheduler that will restart the minion service in 30-60 minutes, migrate the server and wait for minions to start coming online. There is also another workaround posted https://github.com/saltstack/salt/issues/10032#issuecomment-119296425 but some users reported that it did not work.

**Comment by gzcwnk** [comment]
thanks, seems salt needs a new version of python 2.7 which is breaking RHEL6 satellite badly as it uses python 2.6.6  so this needs to happen  :(

**Comment by oeuftete** [comment]
ZD-6017.
