### ISSUE TITLE
Salt Syndic fails randomly

### ISSUE THREAD

**Issue by ramaseshan** [saltstack/salt#41736]
### Issue 

I am running a multi master setup with the latest salt. What I observe is , my salt syndic failing randomly when a query from my Master of Masters go through. The logs dont say anything useful. Here are the logs trace : https://pastebin.com/2ADdvLAA

### Setup
On Syndic Master node : 
The only change in /etc/salt/master is : syndic_master: MOM

On Master of Master node : 
The only change in /etc/salt/msater is : order_masters: True

### Steps to Reproduce Issue
Just setup the a MoM and a syndic node  and this issue should possibly be reproducable.

### Versions Report
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by ramaseshan** [comment]
A little more info.
My setup is the following
1 - MoM (Master of Masters)
3  Masters

Each master has about 20 minions in it.

And from MoM I do a salt '*' , after 2-3  runs, the syndic fails

**Comment by gtmanfred** [comment]
Can you give me the specs of all the devices involved?

Thanks,
Daniel

**Comment by ramaseshan** [comment]
Specs you mean ?
They are mostly VPS from Digital Ocean and Linode, mostly 8 and 16GB servers. The MoM is on a different provider (azure) and all the masters talk to azure.  The azure has a whitelisted ip and port for salt and its masters. The masters have whitelisted ip for MoM and its ports. Not sure what else you would need.

**Comment by whiteinge** [comment]
We see on-again/off-again problems like this with connections that go over the public internet. It's not specific to Salt or ZeroMQ but rather maintaining a persistent connection there is just kinda tough. That's not to say there isn't room for improvement, of course, but I expect there will always be some connection hiccups with that setup.

A few general recommendations:
- Expect the always-on connection to falter and use systems in Salt that aren't affected by that for critical things, such as:
- Use returner modules (via either [ext_job_cache](https://docs.saltstack.com/en/latest/ref/configuration/master.html#ext-job-cache) or [master_job_cache](https://docs.saltstack.com/en/latest/ref/configuration/master.html#master-job-cache)) to send job returns (or Salt events) to a central store. They are invoked on-demand and have reliable delivery.
- Avoid persistent connections entirely and use either salt-api or salt-ssh to send Salt commands to the masters inside each cloud provider.

Otherwise (from experience), troubleshooting that requires someone with in-depth networking knowledge to look at that specific connection and make tweaks and recommendations and is something of an on-going effort.

**Comment by ramaseshan** [comment]
Hey, Thanks for the suggesstion.
I have been quite happy with salt-ssh and I should say, things work pretty neat. 

Just this is the only issue I am facing now. Apart from that, I should say, this issue is not something that can be fixed.

**Comment by bartelsb** [comment]
Jumping in here because we're seeing something similar. We're attempting to use syndication on AWS instances where the syndicate is in one private subnet and the salt MoM is in another private subnet. We have public-facing load balancers managing traffic to each subnet. 

Does syndication require a persistent connection? If a connection goes down, is there any retry logic?
