### ISSUE TITLE
Using runner.salt module via api

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41760]
### Description of Issue/Question

I want to understand how the following command can be converted to a salt api call,

salt-run salt.cmd cmd.run 'll /etc'

I tried many combinations as follows
curl -sSk https://10.236.220.135:8000/run -H 'Accept: application/x-yaml' -d username=admin -d password=admin -d eauth=pam -d client='runner' -d fun=salt.cmd -d kwargs={"fun":"cmd.run","args":"ll /etc"}

 curl -sSk https://10.236.220.135:8000/run -H 'Accept: application/x-yaml' -d username=admin -d password=admin -d eauth=pam -d client='runner' -d fun=salt.cmd -d args={"fun":"cmd.run"} -d kwargs={"ll /etc"}

But all returned following error,

return:
- "Exception occurred in runner salt.cmd: Traceback (most recent call last):\n  File\
  \ \"/usr/lib/python2.7/dist-packages/salt/client/mixins.py\", line 395, in _low\n\
  \    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: cmd() takes\
  \ at least 1 argument (0 given)\n"

My objective it to run cmds on master. And also how multiple arguments can be passed in rest call.

**Comment by gtmanfred** [comment]
It does not appear that you can use this.

I am going to mark this as a bug, because the key in the runner part of salt-api is fun, and the first key in salt.cmd runner is also fun, and you can only have one `fun`, this module cannot be used.

Thanks for reporting this,
Daniel

**Comment by gtmanfred** [comment]
@whiteinge am I missing something here?

Because it almost seems like it should be able to be passed through in kwargs?

```
curl -skS https://localhost:8000/run \
    -H 'Accept: application/x-yaml' \
    -H 'Content-type: application/json' \
    -d '[{
        "client": "runner",
        "fun": "salt.cmd",
        "username": "saltdev",
        "password": "saltdev",
        "eauth": "pam",
        "kwargs": {"fun": "cmd.run"}
    }]'
```

**Comment by whiteinge** [comment]
The nested calls are always 💫 .

@gtmanfred You're on the right track with sending JSON. (I'm not sure if this is actually possible in urlencoded format since RunnerClient didn't historically have support for `arg`/`kwarg`.) But JSON format always maps one-to-one with the Python API so it's a lot more clear. The above is _correct_...minus the kwargs -> kwarg typo. 😜 

@sumeetisp The following works (the values inside `kwarg` are any keyword arguments that [cmd.run](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run) accepts):
```
% curl -skS https://localhost:8000/run \
    -H 'Accept: application/x-yaml' \
    -H 'Content-type: application/json' \
    -d '
[{
    "client": "runner",
    "fun": "salt.cmd",
    "username": "saltdev",
    "password": "saltdev",
    "eauth": "auto",
    "kwarg": {
      "fun": "cmd.run",
      "cmd": "whoami",
      "shell": "/bin/sh"
    }
}]
'
```

**Comment by gtmanfred** [comment]
bah!

Thanks!
Daniel

**Comment by whiteinge** [comment]
@gtmanfred as for the bug, I'm not sure there's a good solution here. Salt runs into this same problem in a handful of places where we have a module call a module (with fallbacks like `m_name` and `fun_`) but even if we fix the `fun` overlap, urlencoded data can't express complex data structures that using nested kwargs require. I'm inclined to mark as (deficient but) 'wontfix'.

@sumeetisp does that solution work for you? Do you have any suggestions on where we might document this?

**Comment by gtmanfred** [comment]
Agreed on the won't fix for now.

Thanks!

**Comment by sumeetisp** [comment]
@whiteinge So how do i figure out when to use kwargs and kwarg?

**Comment by sumeetisp** [comment]
so if i consider a folllows,
1. salt.cmd
2. cmd.run

Then ,

kwargs is for salt.cmd and kwarg is for cmd.run?

**Comment by gtmanfred** [comment]
never use kwargs, kwargs is not a thing for salt-api.

kwarg is what is passed as `**kwarg` to the function and will fill up the `**kwargs` or any other key word arguments that the function you are running accepts.  In this case, salt.cmd accepts fun, and then *args and **kwargs, so arg and kwarg from salt-api fill that up.

Then salt.cmd passes *args and **kwargs to the function that you are calling, in this case cmd.run.

**Comment by whiteinge** [comment]
Yeah, this is pretty confusing and an unfortunate naming choice IMO. It may be a little more clear if you speak Python since the `**kwargs` mentioned above is a common pattern there. A good way to visualize the difference is to look at the function signature for [LocalClient.cmd()](https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd) in Salt's Python API. You can see it accepts a dictionary named `kwarg` that is passed to the module being called as well as `**kwargs` which are used directly by that method.

But as @gtmanfred said, the plural version is an internal variable so you should only ever see the singular version when working with Salt's Python API or salt-api. Any exceptions to that should be considered a bug a changed to be consistent.

**Comment by sumeetisp** [comment]
salt/run/20170622110020368690/ret       {
    "_stamp": "2017-06-22T11:00:24.730549",
    "fun": "runner.salt.cmd",
    "fun_args": [
        {
            "cmd": "cat /etc/salt/cloud.profiles.d/*.conf",
            "fun": "cmd.run",
            "shell": "/bin/sh"
        }
    ],
    "jid": "20170622110020368690",
    "return": "cat: /etc/salt/cloud.profiles.d/*.conf: No such file or directory
",
    "success": true,
    "user": "criuser"
}

**Comment by chrimi** [comment]
The mentioned Workaround with `kwarg` won't work with python based reactor config, because `RunnerClient._reformat_low` won't accept a `fun` argument within `kwarg`

**Comment by whiteinge** [comment]
@chrimi `_reformat_low` doesn't look inside `kwarg` and just passes it through. Could you post an example of what you're trying to do?
