### ISSUE TITLE
Running cmd.run to a minion and trying to get it to run sudo commands

### ISSUE THREAD

**Issue by sk4rp10n** [saltstack/salt#41807]
For example

saltmas1@saltmaster:~$ sudo salt 'saltminion' cmd.run 'apt-get install hexedit'
saltminion:
    E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
    E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
ERROR: Minions returned with non-zero exit code

and when i try to put 'sudo....'
    sudo: no tty present and no askpass program specified

I am still new to saltstack and an answer to this would be VERY helpful. any alternative solutions if you have them as well.

**Comment by Ch3LL** [comment]
@sk4rp10n i'm assuming you are running your salt-minion as a different user?

https://docs.saltstack.com/en/latest/ref/configuration/minion.html#sudo-user check out that configuration I believe that is what you are attempting to do.

**Comment by sk4rp10n** [comment]
i have the salt minion on a different vm. everything is running ubuntu server 16.04

**Comment by Arabus** [comment]
@sk4rp10n The problem is, when you issue the above `cmd.run` the minion running as the user `salt` tries to executed the specified command. Because that user is not allowed to run `apt-get install` though, you get the warnings you posted (It is similar to you running that command as your unprivileged user without `sudo`).

When you run the command with `sudo`, you are normally prompted for a password, which you cannot supply in this situation, because master-minion interaction is non-interactive (Your command is essentially pushed to a job queue from which the minion picks it, runs the job and returns the result).

One solution could be to put the user the salt-minion is running as in the sudoers file with the `NOPASSWD` option. Be aware though that this can be a potential security risk because it enables the `salt` user to become root without a password.

Running the salt-minion as a non-root user without this option is only useful if you want to run non-privileged commands though (e.g., If you want to schedule remote jobs on a set of machines that do not need root access). If you want to use the salt-minion to do root stuff, it will need to be root or at least a way to gain root access via sudo (without a password atm I'm afraid).
