### ISSUE TITLE
Recommended CherryPy version?

### ISSUE THREAD

**Issue by astronouth7303** [saltstack/salt#41862]
### Description of Issue/Question

The [documentation](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html) currently recommends CherryPy version 3.2.3 to avoid an issue fixed in 3.6.1. Latest CherryPy is 10.2.2.

Does this recommendation still stand?

* [3.2.3](https://github.com/cherrypy/cherrypy/releases/tag/3.2.3): Released Dec 26, 2012
* [3.7.0](https://github.com/cherrypy/cherrypy/releases/tag/3.7.0): Released Apr 24, 2015
* [10.2.2](https://github.com/cherrypy/cherrypy/releases/tag/v10.2.2): Release May 17, 2017

**Comment by Ch3LL** [comment]
@whiteinge do you know if this recommendation has changed?

**Comment by whiteinge** [comment]
It's probably time to update that. Testing on the 10.x releases has been looking good. The only problem versions that I know of were somewhere between ~3.2.5 and ~3.7.x due to an SSL bug.

**Comment by whiteinge** [comment]
We haven't packaged 10.x yet in the SaltStack repo since it req's several new deps to build, but if you can install via PyPI it should be working. The SSL error was a hard-stop so it'll be obvious if you see it.

**Comment by astronouth7303** [comment]
Yeah, it's working for me locally, but I'm not using salt in a heavy or complex manner, so I wasn't sure if a more subtle bug had been introduced.

**Comment by whiteinge** [comment]
Thanks, that's good to hear. I'll update that doc.

On Jun 20, 2017 14:47, "Jamie Bliss" <notifications@github.com> wrote:

Yeah, it's working for me locally, but I'm not using salt in a heavy or
complex manner, so I wasn't sure if a more subtle bug had been introduced.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/saltstack/salt/issues/41862#issuecomment-309886767>,
or mute
the thread

**Comment by whiteinge** [comment]
Changed in the PR above. Thanks for raising the question!
