### ISSUE TITLE
Recommended pip installation outdated?

### ISSUE THREAD

**Issue by astronouth7303** [saltstack/salt#41885]
### Description of Issue/Question

It's suggested to [install salt-cloud from pip](https://docs.saltstack.com/en/latest/topics/cloud/qs.html#salt-cloud-quickstart), but afaict, the version uploaded to PIP is horrifically out of date.

**Comment by astronouth7303** [comment]
Also in https://docs.saltstack.com/en/latest/topics/cloud/index.html#quickstart

**Comment by thatch45** [comment]
Yes, the pypi salt-cloud was deprecated a long time ago since salt-cloud was merged into mainline salt.
So this is a documentation bug, those docs should not reference pip installing salt could but rather to pip install salt. Or to use the salt bootstrap, or better to refer the person to the salt install docs.

**Comment by rallytime** [comment]
Thanks @astronouth7303 - I have updated the docs in PR #42099
