### ISSUE TITLE
documentation: remove old docker module page

### ISSUE THREAD

**Issue by epelc** [saltstack/salt#42015]
### Description of Issue/Question
`docker.login` is missing documentation on the latest develop

https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.docker.html

**Comment by gtmanfred** [comment]
https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.dockermod.html#salt.modules.dockermod.login

docker.html is the old one, i am not sure why that is there.

It is documented correctly in dockermod.

I am going to tag this as a documentation error and see if we can get these extra files cleaned up.

cc @rallytime @Ch3LL 

Thanks!
Daniel

**Comment by epelc** [comment]
@gtmanfred Is it supposed to be `dockerng.login` on the new page? Looks like another issue

Needs to be changed to `docker.login`

![image](https://user-images.githubusercontent.com/5204642/27697880-86e6c6fe-5cc3-11e7-8ca6-cd15bd636af4.png)

**Comment by gtmanfred** [comment]
Yup, Erik had made some changes and looks like they got merged forward when they didn't need to be.

I have reverted it in the newer branch in #42019 

Thanks!
Daniel

**Comment by terminalmage** [comment]
I had to go back and fix dockerng in the older branches, since the login func was originally backported from a newer branch and contanined the 2017.7-and-later usage. I meant to ping @rallytime to remind her that we'd need to re-fix that once it was merged forward, but I didn't do that and the merge-forward overwrote the docs in the newer branches. I've merged @gtmanfred's PR.

As for the page linked in the OP, we had to rename `salt.modules.docker` to `salt.modules.dockermod` to avoid a circular import in our loader. We are likely just deploying the docs using an rsync (without `--delete`), so the old file was left live on docs.saltstack.com. We just need to remove that old file from the webserver.

As you can see [here](https://docs.saltstack.com/en/develop/ref/modules/all/) the list of modules contains a link to the correct page.

**Comment by epelc** [comment]
@terminalmage Thanks!

Just fwi from a users perspective on how I ended up there. I was getting to that page by googling `salt docker module` clicking current docs link, going to develop branch, then manually changing `dockerio` to `docker` in the url since develop has no page for `dockerio`.

I'm not sure how typical this is or if it was just me being lazy and not liking the salt docs site search much. Anyways I think this fix is good and my fault for not being aware of the `docker` vs `dockermod` naming(have only been using python for a little while). I'll use the doc's site search from now on.

**Comment by terminalmage** [comment]
What you see there as "develop" will shortly be our 2017.7.0 release. In that release, `dockerio` (the legacy docker support) has been removed. The replacement, which was formerly called `dockerng`, has also been renamed.

I think your way of getting to the docs is totally valid though, and we should look into doing some sort of redirect for renamed modules. Sorry about any confusion.
