### ISSUE TITLE
SaltStack Caches installing package files and reproduce installation later

### ISSUE THREAD

**Issue by dcodery** [saltstack/salt#42221]
When we use a YAML file to install packages like this below

    nginx:
      pkg.installed

Is there any convenient way to cache the installing binary files used by SaltStack, and reuse them with Saltstack later? With these caches, we can ask SaltStack to precisely reproduce the installing (provision) process on another machine (with the same Linux distribution installed) at the binary level.

We know that there are other tools that provide this kind of binary-level reliability in different ways. For example, docker images and AWS AMIs; [Nix][1] manages packages by storing both binary packages and hash values over them.

  [1]: https://nixos.org/nix/

**Comment by terminalmage** [comment]
It's not 100% clear what you're asking. Are you asking for the Salt master to somehow cache the packages so that they can be used on other minions? If so, this is not possible. Salt does not involve itself in dealing with where binary packages are downloaded, it just acts as an interface to the package manager. It's the same as if you were to run a `yum install nginx` or `apt-get install nginx`, etc. on a minion. The master never downloads the packages.

**Comment by dcodery** [comment]
> Are you asking for the Salt master to somehow cache the packages so that they can be used on other minions?

Yes. I think that is the reliable way to reproduce the installing (provision) process later.

Is there any possible way to add this feature into SaltStack?
Like including some [Nix](https://nixos.org/nix/)-like package management system into SaltStack?

**Comment by terminalmage** [comment]
I don't think this is feasible, to be honest. Like I said, the master doesn't involve itself in package downloads. All the work happens on the minion side, and the minion calls `apt-get install`, `yum install`, etc. to perform the package installation. Salt isn't involved in any way with package caching, that's all handled by the package manager.
