### ISSUE TITLE
Debian 7 Package Support

### ISSUE THREAD

**Issue by MorphBonehunter** [saltstack/salt#42378]
This is a followup to #34115 and #31764
Sorry for stressing this, but as Debian 7 is still LTS i have to ask again.
Why is the support of SALT canceled? I know, it's not "oldstable" anymore but i would guess there are still thousands of installations out there and not all of them are upgradable to Debian 8 or 9 in the next weeks.

**Comment by Ch3LL** [comment]
Since Debian 7 is no longer considered oldstable with the release of Debian 9 we have decided to drop support which mirrors our [Supported Operating Systems](http://saltstack.com/wp-content/uploads/2016/08/SaltStack-Supported-Operating-Systems.pdf) policy:

```
Debian
Debian stable and oldstable versions.
https://wiki.debian.org/DebianReleases
```

The comment by @thatch45 in both of those issues states `we will keep them coming as long as it is still considered "oldstable"`.
