### ISSUE TITLE
bash redirection no longer works in Jinja cmd.run

### ISSUE THREAD

**Issue by mwtzzz** [saltstack/salt#42447]
I have been happily using `{% set HN = salt['cmd.run']('2>/dev/null /usr/local/sbin/hostname_for_collectd.sh') %}` on salt-2016. Just upgraded to 2017 and it no longer works:
```
 Comment: Unable to manage file: Problem running salt function in Jinja template: Unable to run command '
['2>/dev/null', '/usr/local/sbin/hostname_for_collectd.sh']' with the context '{'timeout': None,
```

Master and minion both running: salt-2017.7.0-1.el6.noarch

It doesn't like the redirection `2>/dev/null` anymore. If I remove this, it works fine.

**Comment by mwtzzz** [comment]
Moving the redirection operator to the end works:
`{% set HN = salt['cmd.run']('/usr/local/sbin/hostname_for_collectd.sh 2>/dev/null') %}`

I'm satisfied with this, except that it doesn't obey bash's ability to put redirection operators anywhere on the command line.

**Comment by gtmanfred** [comment]
I believe by default we use `sh` as the shell, and not bash, if you set `shell='bash'` in the cmd.run arguments, does it work?

I am not sure why the behavior would have changed though.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Actually, it looks like this is the expected behavior, you will need to use `cmd.shell` or set `python_shell=true`

https://github.com/saltstack/salt/pull/38218

This was deprecated in Nitrogen.

It is also worth noting that there are security implications with using python_shell=true.

```
python_shell (bool) -- If False, let python handle the positional arguments. Set to True to use shell features, such as pipes or redirection
```

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run

**Comment by mwtzzz** [comment]
@gtmanfred Thanks for the info, that's good to know.
