### ISSUE TITLE
Document cherrypy /token endpoint

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#42491]
### Description of Issue/Question
The [2017.7 release notes](https://docs.saltstack.com/en/develop/topics/releases/2017.7.0.html#salt-api-changes) mention a /token endpoint. However, this endpoint is not mentioned in the [rest_cherrypy docs](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#login). 

So from this, there are a few questions:
1. Is this simply an alias for /login, or intended to replace it? The /login endpoint still appears to function and the /token [commit](https://github.com/saltstack/salt/pull/41352/commits/bec3da3a2f0d871f6a735c87b9c0abb8145bdae9) appears to show the same usage as /login.
2. If the rest interface is being updated, is there a way to query the version of the api to be able to support multiple versions?
3. Is there intent to support the same api endpoints in tornado?

**Comment by mchugh19** [comment]
With the deprecation of expr_form in favor of the newer tgt_type in 2017.7, it is important to get version string from the salt-api in order to supporting multiple versions.

**Comment by mchugh19** [comment]
Hey all. Seems this will continue to be an issue. jenkinsci/saltstack-plugin#105 and jenkinsci/saltstack-plugin#99 demonstrate salt-api api breaking changes. Is there any mechanism for querying the version of the salt-api in use in order to support both pre and post 2017 json formats?

**Comment by rbjorklin** [comment]
@mchugh19 I can think of an ugly hack to find out which version is running in case there is no official support for it:

    #!/bin/bash

    # Write the cookie file on login:
    curl -sSk https://localhost:8000/login \
      -c ~/cookies.txt \
      -H 'Accept: application/x-yaml' \
      -d username=user \
      -d password=pass \
      -d eauth=pam
                                                                                   
    # Read the cookie file and query salt-api version:
    curl -sSk https://localhost:8000 \
      -b ~/cookies.txt \
      -H 'Accept: application/x-yaml' \
      -d client=runner \
      -d fun=salt.cmd \
      -d arg=cmd.run \
      -d arg="salt-api --version"

**Comment by mchugh19** [comment]
As far as I know, this issue is still unresolved. There should still be documentation about the purpose and use for the /token API, broadcasted version numbers, and the other items listed above.

**Comment by mattp-** [comment]
@mchugh19 I actually just had to figure this out yesterday, as it was missing from https://github.com/saltstack/salt/pull/51979. when using the cherrypy backend the 'token' returned to from /login is actually the cherrypy session id for some reason. This isn't the case in Tornado as the real salt mk_token token is returned with no session store in the web service. So in cherrypy it exposes the real token for use with the /run endpoint, while in tornado it is functionally identical to /login.
tbh I'd rather leave it undocumented as its kinda dumb, and if/when tornado deprecates the cherrypy implementation it is a just a backcompat implementation detail. (what _should_ have been done is instead of adding /token the /run endpoint translate session id implicitly and /login serves the only endpoint for minting tokens).

**Comment by barbaricyawps** [comment]
Reading through this issue, this issue looks possibly stale. Can anyone confirm that this is still undocumented in 3005+?

**Comment by whytewolf** [comment]
no update has happened. we would have loved volunteers on this.
