### ISSUE TITLE
k8s module needs a way to manage configmaps

### ISSUE THREAD

**Issue by amnonbc** [saltstack/salt#42639]

**Comment by gtmanfred** [comment]
Have you seen the new kubernetes state module?

https://github.com/saltstack/salt/blob/2017.7.1/salt/states/kubernetes.py

It can configure state maps, it looks like it can manage config maps.

https://github.com/saltstack/salt/blob/2017.7.1/salt/states/kubernetes.py#L583

I am going to make this as a documentation issue, since it looks like those docs are not being rendered and added to docs.saltstack.com

**Comment by amnonbc** [comment]
hmm. Yes, looks like it was added a month ago.
I'll try it out.
Thanks!

**Comment by rallytime** [comment]
The docs aren't building there because there is a typo in the autodoc module. I have fixed it in #42807.
