### ISSUE TITLE
eauth tokens only written to filesystem

### ISSUE THREAD

**Issue by kunal-bajpai** [saltstack/salt#42661]
Eauth tokens generated during login through netapi are written to the filesystem on the master (in opts['cache_dir'] + "/tokens"). This logic is baked in to salt.auth.LoadAuth and is not modular like the auth system itself.

In a multimaster setup where minions in the same environment are assigned to different masters, a client needs to authenticate with each master separately to issue commands to minions belonging to different masters.

This system can be made modular by offering different backends for writing tokens like filesystem, redis, mysql, etc. This would involve modularising salt.auth.LoadAuth.mk_token and salt.auth.LoadAuth.get_token. Is there any work being done on this issue?

**Comment by gtmanfred** [comment]
I think this is a great idea.

I am going to mark this as a feature request.

I do not believe anyone is working on this right now, but I would say that you could build it into the cache subsystem.  https://docs.saltstack.com/en/develop/ref/cache/all/salt.cache.redis_cache.html

https://docs.saltstack.com/en/develop/topics/cache/

It would need to be made to use localfs by default to do what it does right now and store on the disk, but then you could have `auth_token_cache` set to something like redis, so that it will stored there with the same functions.

Thanks,
Daniel

**Comment by kunal-bajpai** [comment]
Opened a PR #42720

**Comment by gtmanfred** [comment]
This looks great!

Thanks!
Daniel

**Comment by kunal-bajpai** [comment]
PR merged
