### ISSUE TITLE
Gluster module broken in 2017.7

### ISSUE THREAD

**Issue by rgcosma** [saltstack/salt#42683]
### Description of Issue/Question
Volume creation sls that works in 2016.11 errors in 2017.7

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
mesos_vol:
  glusterfs.created:
    - name: mesos-share
    - bricks:
      - {% for name,addr in salt['mine.get']('mesos-st*', 'get_ip').items()%} {{ addr }}:/gluster-priv/mesos {% endfor %}
    - start: True
    - require:
      - gluster_mnt
      - gluster_dir

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt '*st' state.highstate
With 2016:
          ID: mesos_vol
    Function: glusterfs.created
        Name: mesos-share
      Result: True
     Comment: Volume mesos-share is created and is started
With 2017:
          ID: mesos_vol
    Function: glusterfs.created
        Name: mesos-share
      Result: False
     Comment: State 'glusterfs.created' was not found in SLS 'gluster'
              Reason: 'glusterfs.created' is not available.
Switching between the two releases on the minion triggers the error, no other changes

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
CentOS 7 system, fresh install, EPEL and SaltStack repos enabled

Installed Packages
Name        : salt
Arch        : noarch
Version     : 2016.11.6
Release     : 1.el7
Available Packages
Name        : salt
Arch        : noarch
Version     : 2017.7.0
Release     : 1.el7

**Comment by gtmanfred** [comment]
It looks like glusterfs.created was deprecated in nitrogen.

https://docs.saltstack.com/en/2016.11/ref/states/all/salt.states.glusterfs.html#salt.states.glusterfs.created

The new name that should have had a warning in 2016.11 was pointing to use volume_present.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.glusterfs.html#salt.states.glusterfs.volume_present

https://github.com/saltstack/salt/blob/2016.11/salt/states/glusterfs.py#L204

We need to get that documentation updated to say volume_present instead of the deprecated name.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
The glusterfs.created state was deprecated in favor of the glusterfs.volume_present name in Nitrogen.

https://github.com/saltstack/salt/blob/2016.11/salt/states/glusterfs.py#L204

We do need to update the documentation because the 2017.7 docs still show `glusterfs.created` in the example under glusterfs.volume_present.

Thanks,
Daniel

**Comment by rallytime** [comment]
I have updated the doc references to `glusterfs.volume_present` in #42806.
