### ISSUE TITLE
cp module ignores configured saltenv

### ISSUE THREAD

**Issue by AstraLuma** [saltstack/salt#42780]
### Description of Issue/Question

The `cp` execution module hardcodes `'base'` as the default saltenv. This is surprising when you're configuring specific minions to specific environments.

### Setup

Set up a minion with an environment in its config file.

### Steps to Reproduce Issue
Call a `cp` function on the minion. See unexpected results when it calls to the environment it was not expecting.

### Versions Report

This is a bug in 2016.11 and 2017.7.

**Comment by astronouth7303** [comment]
Since I'm expecting some push-back on this, I'm going to go into further explanation.

There's a few ways to use saltenvs. The "primary" way is to assign specific minions to environments from the top file. However, this can be tricky in some uses. (I select minions by grain role/deploy environment, and I'm using saltenv for salt dev/prod (vs application dev/prod).)

You can also assign specific minions to a saltenv in their config file, and they'll ignore assignments in the state topfile.

The proposed change would have no effect on the first use case (`'base'` is a reasonable fall-back if no environment is configured). However, this would help make the second use case much simpler, because you can use `cp` commands across the cluster without having segregate by saltenv (which is not something easily matched on out-of-the-box) and issuing commands separately.

**Comment by gtmanfred** [comment]
Yeah, this should default to None, and use what is in the configuration for `saltenv`

I am marking this as a feature request.  If you wanted to take a shot at fixing it, we would appreciate it.

It should default to `None` and if something is passed, that is used, otherwise we do a `__salt__['config.get']('saltenv', 'base')` to set the value.

**Comment by astronouth7303** [comment]
The configuration key in the file is `environment`. Does something change during the configuration loading?

Can this be applied to current releases or should it be against development?

**Comment by gtmanfred** [comment]
Sorry, yes it should be `environment`.

I would make the change in 2016.11, and see what you get told in the PR.  If they want you to rebase it to develop, is shouldn't be too difficult.

**Comment by astronouth7303** [comment]
This is still a problem in the `develop` branch.

**Comment by daks** [comment]
Hello,

I think we are hit by the same bug.

We have a `production` environment and minions are affected to it using `saltenv: production` in their config file. It works well for highstates, running states and even custom execution modules which do not access to Salt fileserver.

We frequently use some `cp.get_file` or `state.single file.managed` to update files using Salt. Directly at command-line or inside a custom execution module.
We expect those commands to run in the minion environment _(production for now, others later)_ and we are surprised to see this is not the case, commands failing because the file is not available in 'base' env.

Adding `saltenv=production` to the command solves the problem but seems more a hack than a reliable solution.

**Comment by daks** [comment]
Link to https://docs.saltstack.com/en/latest/ref/file_server/#environments which indicates that environments should be supported in file server.

**Comment by astronouth7303** [comment]
PR is ongoing

**Comment by daks** [comment]
still relevant

**Comment by max-arnold** [comment]
I believe the `environment` config option was renamed to `saltenv`:

https://github.com/saltstack/salt/blob/1fb8f57234a19ed046daa98d138865413393cfe6/salt/config/__init__.py#L3703-L3719

**Comment by daks** [comment]
@astronouth7303 I started a PR https://github.com/saltstack/salt/pull/54473 long time ago but had no time to finish it,  you can add commits on top of it if you want

**Comment by daks** [comment]
Needs verification but this issue should have been fixed in salt 3005 with https://github.com/saltstack/salt/pull/61564

**Comment by whytewolf** [comment]
@daks you were right, i just went and verified this has been fixed by that PR. I'll go ahead and close this now.
