### ISSUE TITLE
CLI tools should accept the -v flag 

### ISSUE THREAD

**Issue by fake-name** [saltstack/salt#42900]
This is a minor issue.

Basically, `salt-cloud` (and possibly other CLI tools) accepts a `--state-verbose=STATE_VERBOSE` flag, where apparently `STATE_VERBOSE` is either true or false. 

Given that, is there a reason that the `-v` flag, as used in basically every unix CLI tool couldn't just directly mean `--state-verbose=true`? It'd certainly be a lot more intuitive, if you ask me.

**Comment by gtmanfred** [comment]
@saltstack/team-core Does anyone else have an opinion on this?

Thanks,
Daniel

**Comment by lorengordon** [comment]
I usually see `-v` as an option to increase the cli verbosity. State output is not managed as cli output (streaming to stdout), so this would feel weird to me.

**Comment by terminalmage** [comment]
@lorengordon not only that, verbose output is the default (I believe). So this would effectively change the default behavior.

**Comment by fake-name** [comment]
Yeah, `--state-verbose=STATE_VERBOSE` didn't wind up doing exactly what I though it did. It'd be better to have it mean `--log-level=all`, or at least "turn up the log level.

The default is *most definitely* not verbose.

**Comment by lorengordon** [comment]
Right, and that is already shortened to `-l all` :)

**Comment by terminalmage** [comment]
@fake-name the problem with your reasoning there is that the minion logging doesn't show up on the CLI, since it is being logged to the minion under /var/log/salt/minion. Any logging you see when running the `salt` CLI command is master-side logging. To get the minion logging at, say, the `debug` loglevel, you'd need to SSH into the minion and run `salt-call -l debug some_module.some_function .....`

**Comment by fake-name** [comment]
I guess  there's a lot more complexity there then what I'm using salt for (VPS creation and provisioning, where I'm managing my own log output return during the provisioning step).
