### ISSUE TITLE
python27-requests-2.6.0-4.el6 ImportError

### ISSUE THREAD

**Issue by kimoziiiii** [saltstack/salt#43128]
### Description of Issue/Question
```bash
[root@linux_229 ~]# /usr/bin/python2.7
Python 2.7.13 (default, Jul 12 2017, 17:32:34) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'
```
### Setup
Default

### Steps to Reproduce Issue
```bash
[root@linux_229 ~]# yum install salt-minion
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
base                                                                                              | 3.7 kB     00:00     
extras                                                                                            | 3.4 kB     00:00     
salt-latest                                                                                       | 2.9 kB     00:00     
updates                                                                                           | 3.4 kB     00:00     
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:2017.7.1-1.el6 will be installed
--> Processing Dependency: salt = 2017.7.1-1.el6 for package: salt-minion-2017.7.1-1.el6.noarch
--> Running transaction check
---> Package salt.noarch 0:2017.7.1-1.el6 will be installed
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2017.7.1-1.el6.noarch
--> Running transaction check
---> Package python27-requests.noarch 0:2.6.0-4.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=========================================================================================================================
 Package                          Arch                  Version                         Repository                  Size
=========================================================================================================================
Installing:
 salt-minion                      noarch                2017.7.1-1.el6                  salt-latest                 36 k
Installing for dependencies:
 python27-requests                noarch                2.6.0-4.el6                     salt-latest                 98 k
 salt                             noarch                2017.7.1-1.el6                  salt-latest                7.3 M

Transaction Summary
=========================================================================================================================
Install       3 Package(s)

Total download size: 7.4 M
Installed size: 52 M
Is this ok [y/N]: y
Downloading Packages:
(1/3): python27-requests-2.6.0-4.el6.noarch.rpm                                                   |  98 kB     00:00     
(2/3): salt-2017.7.1-1.el6.noarch.rpm                                                             | 7.3 MB     00:37     
(3/3): salt-minion-2017.7.1-1.el6.noarch.rpm                                                      |  36 kB     00:00     
-------------------------------------------------------------------------------------------------------------------------
Total                                                                                    185 kB/s | 7.4 MB     00:40     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : python27-requests-2.6.0-4.el6.noarch                                                                  1/3 
  Verifying  : python27-requests-2.6.0-4.el6.noarch                                                                  2/3 
...
Installed:
  salt-minion.noarch 0:2017.7.1-1.el6                                                                                    

Dependency Installed:
  python27-requests.noarch 0:2.6.0-4.el6                           salt.noarch 0:2017.7.1-1.el6                          

Complete!
```

### Versions Report
```bash
[root@linux_229 ~]# salt-minion --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.5 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final
```

**Comment by Ch3LL** [comment]
@kimoziiiii looks like i'm able to replicate this. As a workaround you can upgrade requests using pip.

First install pip `yum install python27-pip`
Then update requests `pip2.7 install --upgrade requests`

Then you can import requests. Seems there is an issue with the version of requests we are building. @dmurphy18 do you see any obvious reason for this import error or possibly we need to provide a newer version of requests?

**Comment by dmurphy18** [comment]
@kimoziiiii Using the steps above, this worked for me on Redhat 6.9 and Redhat 6.6

**Comment by dmurphy18** [comment]
@kimoziiiii @Ch3LL this will be fixed in the next point release,  see https://github.com/saltstack/salt-pack/issues/412

**Comment by mvyletel** [comment]
this fails because urllib3 fails to find ssl_match_hostname from python-backports-ssl_match_hostname.noarch which is still build for python2.6

>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'

>>> import urllib3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .packages.ssl_match_hostname import CertificateError
  File "/usr/lib/python2.7/site-packages/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
ImportError: cannot import name ssl_match_hostname

# rpm -ql python-backports-ssl_match_hostname.noarch
/usr/lib/python2.6/site-packages/backports
/usr/lib/python2.6/site-packages/backports.ssl_match_hostname-3.4.0.2-py2.6.egg-info
/usr/lib/python2.6/site-packages/backports.ssl_match_hostname-3.4.0.2-py2.6.egg-info/PKG-INFO
/usr/lib/python2.6/site-packages/backports.ssl_match_hostname-3.4.0.2-py2.6.egg-info/SOURCES.txt
/usr/lib/python2.6/site-packages/backports.ssl_match_hostname-3.4.0.2-py2.6.egg-info/dependency_links.txt
/usr/lib/python2.6/site-packages/backports.ssl_match_hostname-3.4.0.2-py2.6.egg-info/top_level.txt
/usr/lib/python2.6/site-packages/backports/ssl_match_hostname
/usr/lib/python2.6/site-packages/backports/ssl_match_hostname/__init__.py
/usr/lib/python2.6/site-packages/backports/ssl_match_hostname/__init__.pyc
/usr/lib/python2.6/site-packages/backports/ssl_match_hostname/__init__.pyo
/usr/share/doc/python-backports-ssl_match_hostname-3.4.0.2
/usr/share/doc/python-backports-ssl_match_hostname-3.4.0.2/LICENSE.txt
/usr/share/doc/python-backports-ssl_match_hostname-3.4.0.2/README.txt

**Comment by dmurphy18** [comment]
@mvyletel Can you provide a copy of --version-report as I believe this was fixed in the latest point releases.

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Comment by mvyletel** [comment]
@dmurphy18 here it is

$ salt-minion --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 27 2017, 16:47:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.10.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
