### ISSUE TITLE
When using Syndic with Multi Master the top level master doesn't reliably get returns from lower minion.

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#43447]
### Description of Issue/Question
When running a syndic with multi master minion returns don't always make it up to the top level master. When running the minion in debug mode I can see the minion return the job, but it often doesn't show up on the top level Master of Masters.

Also, when running an orchestration state sometimes the state fails because the minion return doesn't arrive back at the master and also it sometimes fails because when the orchestration state gets to the second step the minion still has a state running and won't run the second state.

### Setup

2 Master of Masters with the config file below:
```
order_masters: True
```
2 syndics.  Each syndic is using multi master to point to both Master of Masters with the following config 
/etc/salt/master:
```
syndic_master:
  - overlord01
  - overlord02
```
/etc/salt/minion.d/master.conf
```
master:
  - overlord01
  - overlord02
```

1 minion. This minion is set up with multi master to both syndics. 
/etc/salt/minion
```
master:
  - syndic01
  - syndic02
```

If I change the syndic configs to the following, then I reliably get the minion returns on the top level master and orchestration states also work reliably;

/etc/salt/master:
```
syndic_master: overlord01
```
/etc/salt/minion.d/master.conf
```
master: overlord01
```

Versions report of one of the overlords. All VMs are running the exact same OS and Salt version:

```
[root@overlord01 ~]# salt --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by UtahDave** [comment]
ZD 1669

**Comment by DmitryKuzmenko** [comment]
The problem is a configuration issue. To understand what MoM have to receive the minion ret syndic looks for a `master_id` value in the load. If there's no that value the return will be sent to any MoM in random order.
MoM inserts this value in case this value is set in config. So just set in both MoMs' configs either `master_id: <master_ip>` or `master_id: <master_hostname>` depending on how it's configured in syndics (values have to be equal).

This value is documented here: https://docs.saltstack.com/en/latest/ref/configuration/master.html#master-id

Probably we have to put a note about this somewhere else in the documentation.

**Comment by DmitryKuzmenko** [comment]
The same is actual for Multimaster minion too. So it looks we have to update this one in some way.
https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html#tutorial-multi-master

**Comment by DmitryKuzmenko** [comment]
I've fixed the issue with state execution in the same environment. The problem was in event forwarding logic. I've described it in the PR (#43526).
I've just thought shouldn't Syndic work in the same way for job returns by default? I.e. if job return contains no master ID syndic don't know what master issued the command and has to receive the response. In this case it's more correct to forward the return to all connected masters instead of a random one as it's implemented now. In this case setting of `master_id` in the master config would be no necessary and could be used as a network load optimization if needed.
@cachedout what do you think?

**Comment by austinpapp** [comment]
@DmitryKuzmenko i think you've got this spot on. executing mom with master_id set should always receive whatever jobs/events it has issued. the only downside here is that if mom1 sends a task and mom1 dies mid job execution, the ret data is black holed. i kind of have some thoughts on how to handle that but i'll punt on that with maybe another ticket. 

if master_id is *not* set, all connected masters get it. the downside is outputters and reactors (or whatever else) would see this event and thus reactor. of course you could use a pillar or grain set to drive who should do the outputter or reactor work.

**Comment by cachedout** [comment]
@DmitryKuzmenko As always, you've got it exactly right. That's just what we should do.
