### ISSUE TITLE
Mattermost runner failing to retrieve config values due to unavailable config runner  

### ISSUE THREAD

**Issue by haam3r** [saltstack/salt#43479]
### Description of Issue/Question
The new Mattermost runner use the config runner to query config options like api_url and hook, however the config runner is currently only in the develop branch and therefore unavailable causing mattermost runner functions to fail.

See below for the specific code portion in the source responsible.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
cat /etc/salt/master.d/mattermost.conf 
mattermost:
  hook: s0meRandomString
  api_url: https://mattermost.example.com/hooks
  username: Salt
  channel: salt
```

### Steps to Reproduce Issue

Running a state like:
```salt
message:
  salt.runner:
    - name: mattermost.post_message
    - message: 'Test'
    - require:
      - salt: some_other_state
```

Or running:
```
salt-run mattermost.post_message message='Test'
```

Result is:

```
Exception occurred in runner mattermost.post_message: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 392, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/mattermost.py", line 118, in post_message
    hook = _get_hook()
  File "/usr/lib/python2.7/dist-packages/salt/runners/mattermost.py", line 49, in _get_hook
    hook = __salt__['config.get']('mattermost.hook') or \
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1113, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'config.get'
```
### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.25.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.25.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-92-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

### Workaround
Currently using a workaround where I'm redefining the config query functions to use the more prevalent `__opts__.get`.

Code changed in: https://github.com/saltstack/salt/blob/develop/salt/runners/mattermost.py#L44-L89

#### Working code

```python
def _get_hook():
    '''
    Retrieves and return the Mattermost's configured hook
    :return:            String: the hook string
    '''
   return __opts__.get('mattermost', {}).get('hook', '')
 
def _get_api_url():
    '''
    Retrieves and return the Mattermost's configured api url
    :return:            String: the api url string
    '''
    return __opts__.get('mattermost', {}).get('api_url', '')
    
def _get_channel():
    '''
    Retrieves the Mattermost's configured channel
    :return:            String: the channel string
    '''
    return __opts__.get('mattermost', {}).get('channel', '')
    
def _get_username():
    '''
    Retrieves the Mattermost's configured username
    :return:            String: the username string
    '''
    return __opts__.get('mattermost', {}).get('username', '')
```

**Comment by Ch3LL** [comment]
Looks like you are indeed correct. the mattermost runner was added here https://github.com/saltstack/salt/pull/38319 in december 2016 but the config runner wasn't added until here https://github.com/saltstack/salt/pull/40732 april 2017. So i'm guessing the mattermost runner never was functional, since it would be dependent on this runner. 

It seems this would initialy be labeled a bug and we would backport config runner but I also know we try to not include new features in point releases. I would like to get @saltstack/team-core 's opinion on this one. Should we back port the config runner?

**Comment by cachedout** [comment]
I'm against backporting an entire runner.

**Comment by haam3r** [comment]
Sounds reasonable to me. As @cachedout pointed out, it's an easy fix, until the next major release. Was just bringing attention to this. I'm fine with this being closed as well.

**Comment by rallytime** [comment]
@haam3r Thanks for pointing that out. It might be worth adding a quick note to the mattermost docs about this issue to help others that experience this issue. Would you be interested in submitting a change to the `2017.7` branch to explain the need to drop the config runner into the master when running mattermost on 2017.7 releases?

**Comment by haam3r** [comment]
@rallytime No problem. Yeah sure, I'll have time later today to work up a PR for that.

**Comment by rallytime** [comment]
Closed via #43513

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT
