### ISSUE TITLE
minion service start but minion_id or key are not created

### ISSUE THREAD

**Issue by usernkey** [saltstack/salt#43500]
### Description of Issue/Question
minion service start but minion_id or key are not created

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Here the minion configuration

master:
   -  server1
   -  server2

master_type: failover
master_alive_interval: 30
retry_dns: 0

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

not clear yet.   I have more then 400 minions so far between linux and  windows and only 3 of them have this issue.

c:\salt\bin\python.exe c:\salt\bin\Scripts\salt-minion -c c:\salt\conf -l debug

self.filename = os.path.basename(pathname)
File "c:\salt\bin\lib\ntpath.py", line 208, in basename
return split(p)[1]
File "c:\salt\bin\lib\ntpath.py", line 180, in split
d, p = splitdrive(p)
File "c:\salt\bin\lib\ntpath.py", line 117, in splitdrive
if (normp[0:2] == sep*2) and (normp[2:3] != sep):
RuntimeError: maximum recursion depth exceeded in cmp

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Master and minion are on the same version

C:\>c:\salt\bin\python.exe c:\salt\bin\Scripts\salt-minion --version
salt-minion 2016.3.3 (Boron)

**Comment by garethgreenaway** [comment]
@usernkey thanks for the report.  Is it only the Windows machines that are having this particular issue or is it Linux machines as well?

**Comment by usernkey** [comment]
Only Window and only 3 of them.  We have more or less 50% Windows and 50% Linux.

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT
