### ISSUE TITLE
Windows cmdmod  forcing cmd to be a list

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#43522]
### Description of Issue/Question
From PY3 Doco for subprocess

> On Windows, the class uses the Windows CreateProcess() function. If args is a string, the interpretation is platform-dependent and described below
> On Windows, if args is a sequence, it will be converted to a string in a manner described in Converting an argument sequence to a string on Windows. This is because the underlying CreateProcess() operates on strings.

Doing this is bad for windows
```
if not isinstance(cmd, list):
      cmd = salt.utils.shlex_split(cmd, posix=False)
```
Because subprocess turns it back into a string.

Here you can see the " have been escaped by subprocess.call trying to turn the command into a string
```
>>> print subprocess.call(['cmd.exe','/c','echo "hello world"'], shell=False)
\"hello world\"
0
```
Here you can see passing a string the command is executed correctly.
```
>>> print subprocess.call('cmd.exe /c echo "hello world"', shell=False)
"hello world"
0
C:\>echo "hello world"
"hello world"
```

```
>>> print subprocess.call(['c:\\test file.bat','"hello"','"hello jim"'])
C:\salt\var\cache\salt\minion>echo \"hello\"
\"hello\"
C:\salt\var\cache\salt\minion>echo "\"hello
"\"hello
C:\salt\var\cache\salt\minion>echo jim\""
jim\""
```
VS
```
>>> print subprocess.call('c:\\test file.bat "hello" "hello jim"')
C:\salt\var\cache\salt\minion>echo "hello"
"hello"
C:\salt\var\cache\salt\minion>echo "hello jim"
"hello jim"
```
The above is all PY2

cmdmod needs to be modified so that strings are not converted to lists on windows platforms. Currently the code converts it to a list and subprocess converts it back to a string for Windows and the more conversion back and forwards happens the more outcome is different.

From the doco, if you provide a list instead of a string, python will do the following:
> 17.5.8.1. Converting an argument sequence to a string on Windows
> On Windows, an args sequence is converted to a string that can be parsed using the following rules (which correspond to the rules used by the MS C runtime):
> 
> 1.  Arguments are delimited by white space, which is either a space or a tab.
> 2.  A string surrounded by double quotation marks is interpreted as a single argument, regardless of white space contained within. A quoted string can be embedded in an argument.
> 3.  A double quotation mark preceded by a backslash is interpreted as a literal double quotation mark.
> 4.  Backslashes are interpreted literally, unless they immediately precede a double quotation mark.
> 5.  If backslashes immediately precede a double quotation mark, every pair of backslashes is interpreted as a literal backslash. If the number of backslashes is odd, the last backslash escapes the next double quotation mark as described in rule 3.

**Comment by damon-atkins** [comment]
This also includes utils/timed_subprocess.py

**Comment by Ch3LL** [comment]
ping @twangboy see above. Looks like we need to do some cleanup for python3 and windows.

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Comment by twangboy** [comment]
@terminalmage Do you have any thoughts on this?

**Comment by terminalmage** [comment]
You're not supposed to quote strings when passing args as a sequence to `subprocess`, so your `subprocess.call(['c:\\test file.bat','"hello"','"hello jim"'])` example is not proper usage anyway.

That said, if `subprocess` on Windows is meant to operate on strings, we should probably make sure we're using strings. I am going to be looking into another Windows-related issue tomorrow, so I'll investigate this as well.

**Comment by damon-atkins** [comment]
['c:\\test file.bat','"hello"','"hello jim"'] was a demonstration of how bad things can get.

Salt is turning a valid string into a list, when subprocess Windows comes along and turns it back into a string before giving it to Windows to execute the process.

Linux/Unix Results
```
Python 2.7.11 (default, Sep 29 2016, 13:49:11)
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.call(['./file test.sh','"hello"','"hello jim"'])
"hello"
"hello jim"
0
```

Windows Result, i.e. the process of converting to the string has an impact on the command.
```
>>> print subprocess.call(['c:\\test file.bat','"hello"','"hello jim"'])
C:\salt\var\cache\salt\minion>echo \"hello\"
\"hello\"
C:\salt\var\cache\salt\minion>echo "\"hello
"\"hello
C:\salt\var\cache\salt\minion>echo jim\""
jim\""
```

**Comment by terminalmage** [comment]
@damon-atkins I've opened https://github.com/saltstack/salt/pull/43807 to stop commands from being converted to lists. Is it your estimation that the existing Windows-specific code which is passing commands as lists should be OK? It seems to me that passing the commands as sequences is supported just fine, but splitting them only to have them re-joined is the main concern here.

**Comment by damon-atkins** [comment]
If cmdmod and utils/timed_subprocess.py are no longer forcing it into a list for the windows platform,  Then people can update windows modules to pass strings instead.
`subprocess`  turns the list into a string to be compatible with windows, as shown in the examples above.

Thanks

**Comment by terminalmage** [comment]
@damon-atkins From what I can see, the timed_subprocess code only performs a `shlex.split()` when the following two conditions are true:

1. The `args` value passed to `subprocess.Popen()` is invalid, causing it to raise a `TypeError`. This happens when `args` is either non-string, or the sequence being passed contains non-string items. See [this code block](https://github.com/saltstack/salt/blob/0623e40/salt/utils/timed_subprocess.py#L41-L49)
2. `python_shell` was `False` in `cmdmod.py` (and thus passed as `shell=False` to timed_subprocess.

Given the above, the split will not happen if a string is passed to timed_subprocess.

**Comment by damon-atkins** [comment]
Thanks

**Comment by terminalmage** [comment]
OK, given that https://github.com/saltstack/salt/pull/43807 has been merged, are you confident that this can be closed?

**Comment by damon-atkins** [comment]
Cheers
