### ISSUE TITLE
Need salt to execute any command only if previous return code is 0 in batched mode

### ISSUE THREAD

**Issue by siteshbehera** [saltstack/salt#43521]
Hi,

When we run a command in batched mode,  for example :
 
salt -C S053* -b 1 --batch-wait=100   cmd.run "hostname"

Salt runs the command on each host one by one wth a batch wait time of 100s. 

The issue we may have is, if something fails we have to manually kill the command and think the next host is not running the command. 

It would be great if we can add a switch to check return code of previous execution before moving to next host. This will help us to run batched mode safely across big clusters.

**Comment by Ch3LL** [comment]
I think what you are looking for is `--failhard` . You can also set it via config as documented [here](https://docs.saltstack.com/en/latest/ref/states/failhard.html) 

Is that what you are looking for?

**Comment by siteshbehera** [comment]
Not exactly. When we run a batch command, salt will get a subset of hosts to run the command. 

I want the subsequent sets to fail and not execute anything, if return code is not zero (0) for current selected subset. 
Let me know if you want a example for the ask.

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT
