### ISSUE TITLE
Add gitfs Test to Auto Test Suite

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#43536]
This task is to monitor the addition of one test to the auto test suite:

- [ ] T137061: test gitfs functionality

Ensure you add gitfs settings the configuration setup:

For Example:

```
fileserver_backend:
  - git 
  - roots
gitfs_provider: gitpython
gitfs_remotes:
  - https://github.com/repo/gitfs-test
gitfs_mountpoint: salt://
```

Add files similar to the following:

script.sh

```
#!/bin/bash

echo "Simple script is running."
echo "Here's a list of files:"
ls
```

state.sls 

```
nano:
  pkg.installed
```

1. run `salt-call --local cp.list_master` and ensure it list the correct files in the repo [state.sls, script.sh]
2. run `salt-call --local cmd.script salt://script.sh` and ensure it runs the script above (or a similar script) and returns correct output
3. run `salt-call --local state.sls state` and make sure it correctly runs the state.

**Comment by rallytime** [comment]
@terminalmage I am assigning this to you. I know you have already written many gitfs tests in the past, so perhaps this is already covered. If there isn't a test covering this use case already, then can you write one?

**Comment by terminalmage** [comment]
I think step 1 is already well covered by the GitFSTestFuncs class (shared to test both GitPython and pygit2) in tests/unit/fileserver/test_gitfs.py.

As far as ensuring that we grab the desired file using salt-call, that would need to be in an integration test. It's also not really something easily done on the fly, as fileserver changes require a reset of the master daemon, which is a non-starter. So we can't get a true salt-call test here. I did however write a test framework for git_pillar integration testing which was designed to be expanded to gitfs as well, I've just not had a chance to write the tests for it. It doesn't run a full-fledged salt-call, but instead invokes the functions directly. This wouldn't be a true 100% test of the fileserver however, it would be calling the functions in salt/fileserver/gitfs.py directly rather than via a salt.fileserver.Fileserver object. So, we wouldn't be testing things like order of backends, etc., only that the test repo we generate is handled properly by gitfs. @rallytime, @Ch3LL would that suffice?

**Comment by rallytime** [comment]
That covers it nicely, IMO. I think this manual test was likely written long ago to cover the masterless gitfs use case when we didn't have automated gitfs tests at all.

@Ch3LL Any concerns on your side?

**Comment by Ch3LL** [comment]
No concern here
