### ISSUE TITLE
salt-common 2017.7.1+ds-1_all.deb includes an outdated bootstrap-salt.sh, causing salt-cloud to fail

### ISSUE THREAD

**Issue by jessebye** [saltstack/salt#43577]
### Description of Issue/Question
The salt-common_2017.7.1+ds-1_all.deb package contains an outdated `bootstrap-salt.sh` which does not recognize version 2017.7 as a valid stable version:

```
Unknown stable version: 2017.7 (valid: 1.6, 1.7, 2014.1, 2014.7, 2015.5, 2015.8, 2016.3, 2016.11, latest, $MAJOR.$MINOR.$PATCH)
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPassword
Authentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i 
/path/to/key -p 22 ubuntu@x.x.x.x 'sudo /tmp/.saltcloud-x-x-x-x-x/deploy.sh
 -c '"'"'/tmp/.saltcloud-x-x-x-x-x'"'"' stable 2017.7'' failed. Exit code: 1
```

### Setup
1. Add 2017.7 apt source: `deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2017.7 xenial main`
2. `apt update`
3. `apt install salt-common`

### Steps to Reproduce Issue
1. `cat /usr/lib/python2.7/dist-packages/salt/cloud/deploy/bootstrap-salt.sh`
2. observe that the bootstrap script was updated _before_ 2017.7.1 was released, and will not recognize that as a valid version.
3. Run a `salt-cloud` command to create a server with bootstrap arguments of `stable 2017.7` and see the error message above.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
@jessebye Thanks for the report.  @dmurphy18 thoughts on this one?

**Comment by dmurphy18** [comment]
@jessebye The appropriate place to download bootstrap from is https://bootstrap.saltstack.com.  The version installed with a point release of Salt is the version that is stable at the point of release, that is, the release is a snapshot in time of the available independent packages.  The release and development of bootstrap is not tied to the point releases of Salt, hence it cannot accommodate a specific point release of Salt before it is actually released.  However we shall try to ensure in general that it recognizes the version it is getting released with.

Thanks for bring this to SaltStack's attention.

**Comment by dmurphy18** [comment]
@rallytime Just a reminder to check if bootstrap will recognize upcoming point releases, such that the stable version that ships with a point release will recognize that point release

**Comment by rallytime** [comment]
@dmurphy18 The bootstrap script automatically recognizes upcoming point releases in terms of `2017.7.x`, where the x is detected by default. However, we do have to update the bootstrap script to recognize new major release branches (i.e. 2017.7).

We were late in updating the 2017.7 major release branch (fixed in https://github.com/saltstack/salt-bootstrap/pull/1120), but we've added a check to the feature release process for this so we won't miss this in the future for major release branches.

The bootstrap release cadence is different than the salt release cadence. As soon as a new bootstrap release is cut, the bootstrap stable release is merged into the salt codebase.

@jessebye You can run `salt-cloud -u`, which will grab the latest stable from bootstrap.saltstack.com and place it in your `/etc/salt/cloud.deploy.d/` directory.

This process certainly needs more documentation. However, I have already opened an issue about this lack of documentation in #34089. As such, I consider this a documentation issue, so I am going to close this as a duplicate.

@jessebye If you have more questions, do let us know and we can continue the discussion. Thanks!

**Comment by twellspring** [comment]
@rallytime if we run the `salt-cloud -u` and therefore have the bootstrap script in `/etc/salt/cloud.deploy.d` will salt-cloud check and use the script in that location before it uses the one in the package?

**Comment by rallytime** [comment]
@twellspring Yep!
