### ISSUE TITLE
Could not run bat file on windows minions - Minion did not return. [Not connected]

### ISSUE THREAD

**Issue by YooTimmy** [saltstack/salt#43947]
### Hello, I have a problem when using salt to execute bat files on windows minions. 
Background information:
I am trying to update the salt version on my windows minions servers. Because I have quite a number of machines to take care, I would like to do the update using salt.
I have managed to put the installation package & install_minion.bat on respective servers (Dir: C:\upgrade_salt_minion). Next step is to execute the bat file from salt master. My thought is to use the salt state function, but when trying to execute it, it seems not working and some more, the salt minions will be disconnected and I have to restart the service again on minion itself. 
### Setup
**DeploySaltUpdate.sls**
```
deploy:
  cmd.run:
    - name: 'C:\upgrade_salt_minion\install_minion.bat'
```
**Install_minion.bat**
```
@echo off
C:\upgrade_salt_minion\Salt-Minion-2016.11.7-AMD64-Setup.exe /S /master=XXXX /minion-name=P74 /start-service=1
exit
pause
```
### Steps to Reproduce Issue
on salt master, execute:
`salt 'P74' state.sls DeploySaltUpdate
`
Returns:

> P74:
>     Minion did not return. [Not connected]

### Versions Report
Salt Version (Salt Master):
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: 0.1.6
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.7.0
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.13.0-86-generic
         system: Linux
        version: Ubuntu 12.04 precise

Salt minion version is 2016.3.1

Appreciate if anyone could help with this issue, tried google but did not find a exact matching issue. Appreciated the help in advance!

**Comment by YooTimmy** [comment]
On another side note, when I tried to execute the Install_minion.bat file on the windows minion locally, it works well and salt minion version is updated as expected.

**Comment by Ch3LL** [comment]
ping @twangboy can you speak here concerning  concerning his bash script. If i remember correctly when upgrading i've never needed to restart the minion service so I'm wondering if there is a command line argument that needs to be added?

**Comment by twangboy** [comment]
@YooTimmy 
So, this is an issue we had for a while... You can't update salt using the salt installer from salt with a batch file. The issue is that the first thing the installer does is kill the `salt-minion` service. The result is that all child processes are killed, including the installer. So basically, all it does is top the service and then die.

So, starting with 2016.3 we added a feature to winrepo that allows you to use the Task Scheduler to install software. We modified the `salt-minion` software definition to use this feature ([https://github.com/saltstack/salt-winrepo-ng/blob/master/salt-minion-py2.sls](url)).

So, if you're using the current winrepo (https://github.com/saltstack/salt-winrepo-ng) you should just be able to issue `salt * pkg.install salt-minion` to update to the latest version. Using a state that would be:
```
update_salt:
  pkg.installed:
    - name: salt-minion
```
That will pull the salt installer from SaltStack's servers and upgrade salt. No need to pass additional parameters as the installer will use the existing configuration.

If you want to use an installer hosted somewhere else, you'll need to modify the `installer` parameter in the software definition file in winrepo to point to the location on your file server.... so, instead of:
```
installer: 'https://repo.saltstack.com/windows/Salt-Minion-{{ version }}-Py2-AMD64-Setup.exe'
```
you would have
```
installer: 'salt://windows/installer/Salt-Minion-2017.7.1-Py2-AMD64-Setup.exe
```
_Note: The winrepo is located on the master at `/srv/salt/win/repo-ng` by default._

Now, I see you've already copied the file locally, so the following should work:
```
installer: 'C:\upgrade_salt_minion\Salt-Minion-2016.11.7-AMD64-Setup.exe
```

If you want to pass the installer parameters anyway, change the `install_flags` parameter:
```
install_flags: /S /master=XXXX /minion-name=P74 /start-service=1'
```

If you haven't been using winrepo, see the documentation for setting that up... https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html

Using the defaults, it should be as simple as running the following on the master:
```
salt-run winrepo.update_git_repos
salt * pkg.refresh_db
salt * pkg.install salt-minion
```

Hope this helps

**Comment by YooTimmy** [comment]
Thanks a lot for the advice @twangboy , that method works well on majority of my windows minions! 
I have 2 servers having some issues after the installation though, when I tried to ping them from salt master the result is "Minion did not return. [Not connected]".
Checked on the minions itself, the salt-minion service is not started on that particular server. when I tried to start the service manually, it returns me following error message: 

> Windows could not start salt minion on local computer, For more information, review system event log. If this is a non-Microsoft service, contact the service vendor, and refer to service-specific error code 3.

Event logs are attached here as well:

> Failed to start service salt-minion.  Program c:\salt\bin\python.exe couldn't be launched. CreateProcess() failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

After googling a bit, I realized that the issue might be solved through re-installing vcredist_x64 package, which I will need to perform during server downtime so have not confirmed it is working for me or not. However any idea on why updating salt minions version can resulting this issue? cause I am quite sure that before performing this update this specific server can be connected to my salt master without any issue.
