### ISSUE TITLE
`grafana4_dashboard.present` incorrectly sets timeShift and timeFrom

### ISSUE THREAD

**Issue by dharmab** [saltstack/salt#44082]
### Description of Issue/Question

When using the `grafana4_dashboard.present` state, if `timeFrom` and/or `timeShift` are defined but blank in the dictionary passed to the `dashboard` argument (as Grafana exports if these values are unset), the corresponding time range fields in Grafana will be set to the *string* 'None' instead of the empty string.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Example Pillar: https://github.com/dharmab/homelab/blob/3c13915dd5dbfaff796254f0b363305bfb8c6e61/pillar/grafana/dashboards.sls#L14
Example SLS: https://github.com/dharmab/homelab/blob/3c13915dd5dbfaff796254f0b363305bfb8c6e61/salt/grafana/init.sls#L53

### Steps to Reproduce Issue

- Pass a dashboard to `grafana4_dashboard.present` containing a panel which has `timeShift` and `timeFrom` defined but unset, as in the above link
- Go to the panel in Grafana. There will be an error message displayed on the panel
- Edit the panel and click the time range tab. The 'Override relative time - Last' and 'Add time shift -
 Amount' fields will contain the string 'None'

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.6.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by dharmab** [comment]
Workaround: [when exporting dashboards from Grafana, override the timeShift and timeFrom fields.](https://github.com/dharmab/homelab/blob/master/salt/grafana/scripts/export.py#L24)

**Comment by gtmanfred** [comment]
@bbinet can you assist me with this?

Thanks,
Daniel

**Comment by dharmab** [comment]
It looks like this is ambiguous YAML:

> YAML allows the node content to be omitted in many cases. Nodes with empty content are interpreted as if they were plain scalars with an empty value. Such nodes are commonly resolved to a “null” value.

[source](http://www.yaml.org/spec/1.2/spec.html#id2786563)

The YAML library I'm using dumps null as empty content... This may be better suited to be a bug in ruamel.

**Comment by xavierog** [comment]
The issue is not limited to timeShift and timeFrom. It can happen with any null value in a dashboard export; for instance, right after adjusting timeShift and timeFrom, I noticed I had to adjust yaxes.*.max.

Additionally, although it may be related to YAML, ruamel is not necessarily the culprit here... when storing my dashboards in the Pillar, I did not convert the JSON data provided by Grafana into YAML: I simply reformatted it using ``jq --indent 4 '{"grafana": {"dashboards":{"'${slug}'": .dashboard}}}'`` then leveraged the fact that YAML is a superset of JSON to store it directly in the Pillar... and I still stumbled upon the same issue. It is very likely that, due to SaltStack working with YAML, the Grafana-provided JSON get altered between the moment it gets stored in the Pillar and the moment it gets sent to a Grafana instance.

**Comment by xavierog** [comment]
After some more investigations, it appears that storing null JSON data in the Pillar is perfectly fine: ``salt <target> pillar.get <whatever> --output.json`` will output both null and non-null data untouched. Another way to put it is: we can safely pass a Grafana-issued JSON dashboard dump to SaltStack.

On the other hand, I can also confirm that grafana4.create_update_dashboard() **receives** a dict where all null values have been replaced with ``"None"``. I suspect this is due to the way we pass the Pillar contents through Jinja2. I will keep investigating.

**Comment by xavierog** [comment]
> I suspect this is due to the way we pass the Pillar contents through Jinja2.
And confirmed. The issue simply got away when I adjusted my state file from
``        - dashboard: {{ salt['pillar.get']('grafana:dashboards:' + slug) }}``
``        - dashboard: {{ salt['pillar.get']('grafana:dashboards:' + slug|json()) }}``
After that change, every part of the chain receives correct data:

- grafana4_dashboard.present()
- grafana4.create_update_dashboard()
- Grafana itself

**Comment by xavierog** [comment]
@dharmab Additional tip: in your homelab/export.py script, you may want to remove ``dashboard['dashboard']['id']``. Indeed, when provided with a dashboard featuring an id, Grafana is liable to reply with HTTP 400 (leading to a Python stacktrace when applying your SaltStack states) if that dashboard does not exist.
