### ISSUE TITLE
redis.host defaults to 'salt' instead of 'localhost'

### ISSUE THREAD

**Issue by dannymichaelson** [saltstack/salt#44156]
### Description of Issue/Question
[redismod](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.redismod.html) says it defaults to `redis.host: 'localhost'`, however it uses `config.option` which [looks like it defaults to `redis.host: 'salt'`](https://github.com/saltstack/salt/blob/develop/salt/modules/config.py#L50)

### Steps to Reproduce Issue
With no `redis.host` line present in minion config, run `salt-call config.option redis.host` and it will return `salt` instead of the expected `localhost`

**Comment by gtmanfred** [comment]
That is correct, would you mind submitting a PR that fixes the documentation?

Thanks,
Daniel

**Comment by dannymichaelson** [comment]
Wouldn't `localhost` be the better default here? Can I make that PR?

**Comment by gtmanfred** [comment]
Well, if you wanted to do that, it would have to go through a deprecation process.

And generally the returner would be on the master (initially) or somewhere else, instead of on each specific minion, so `salt` seems reasonable so that all the minions could return back to it directly using the ext_job_cache or the master command could store it for the master_job_cache.

Daniel

**Comment by rallytime** [comment]
Closed via #44177
