### ISSUE TITLE
Solaris 11 sparc returns incorrect os grain

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#44154]
### Description of Issue/Question
The os grain on Solaris 11 is incorrect:

```
root@pkg-testsparcZUQP:~# salt-call --local grains.get os
local:
    Oracle Solaris
```

ping @sjorge I believe that is suppose to be Solaris correct?

### Versions Report
2017.7.2 / Solaris 11 sparc

**Comment by sjorge** [comment]
There was a fix in 2016.3 PR #37472 that fixed the parsing of /etc/release,
After the fix it correctly identified OmniOS, Oracle Solaris (so Solaris 11 and up, as that got rebranded) and it also correctly parses the version for the patch release that are common especially for Solaris 10

So in this case unless /etc/release does not list it as 'Oracle Solaris' I do not think this is a bug but expected behaviour.

More details see:
https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L1597

**Comment by Ch3LL** [comment]
ahh thanks for clarifying that. I wasn't entirely sure because the other platforms such as solaris 10 were spitting out 10. I ran into the solarisips module not correclty loading cuz of this:

https://github.com/saltstack/salt/blob/v2017.7.2/salt/modules/solarisips.py#L59

so i thought it needed to be Solaris as well there.

But it looks like someone fixed this here: https://github.com/saltstack/salt/pull/42628

So i'll go ahead and close this since it looks like its been fixed. Thanks for helping out once again :)

**Comment by sjorge** [comment]
For all of those the os_family is 'Solaris' so it's probably better to use that grain in the modules (unless for example they only work on SmartOS) Alternatively there is also the check for kernel == 'SunOS' that could be use, but there is talk of switching that to something else in illumos so os_family is probably the safest.
