### ISSUE TITLE
salt.utils.versions.warn_until stacklevel

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#44236]
### Description of Issue/Question
In development

```
def version_cmp(pkg1, pkg2, ignore_epoch=False):
    # Late import to avoid circular import.
    import salt.utils.versions
    salt.utils.versions.warn_until(
        'Neon',
        'Use of \'salt.utils.version_cmp\' detected. This function has '
        'been moved to \'salt.utils.versions.version_cmp\' as of Salt Oxygen. '
        'This warning will be removed in Salt Neon.',
        stacklevel=3  #  !!!!!! Need to add to find the real location of the issue. !!!!!!!!!
    )
    return salt.utils.versions.version_cmp(pkg1,
                                           pkg2,
                                           ignore_epoch=ignore_epoch)
```
```
"c:\Python27\python.exe" -B  C:\Salt-Dev\salt\scripts\salt-call -l debug pkg.junk
[WARNING ] versions.warn_until c:\Salt-Dev\salt\salt\utils\__init__.py:3094: DeprecationWarning: Use of 'salt.utils.version_cmp' detected. This function has been moved to 'salt.utils.versions.version_cmp' as of Salt Oxygen. This warning will be removed in Salt Neon.
```
With Change To stacklevel=3
```
[WARNING ] versions.warn_until c:\Salt-Dev\salt\salt\modules\win_pki.py:49: DeprecationWarning: Use of 'salt.utils.version_cmp' detected. This function has been moved to 'salt.utils.versions.version_cmp' as of Salt Oxygen. This warning will be removed in Salt Neon.
```

Is the default stacklevel still correct ?

salt.utils.* e.g. salt.utils.which may need the same treatment.
```
[WARNING ] versions.warn_until c:\Salt-Dev\salt\salt\utils\__init__.py:2539: DeprecationWarning: Use of 'salt.utils.which' detected. This function has been moved to 'salt.utils.path.which' as of Salt Oxygen. This warning will be removed in Salt Neon.
```

**Comment by gtmanfred** [comment]
@saltstack/team-core does anyone have an opinion or some insight on this?

Thanks,
Daniel

**Comment by terminalmage** [comment]
We've deprecated all calls to `salt.utils.somefunc` in develop, that has all been refactored now with the merge of https://github.com/saltstack/salt/pull/44103 last week.

When no stacklevel is passed, we just fire the warning from the location from which we invoke the warn_until. In the vast majority of cases this is the correct location, but because these are convenience functions to allow the deprecated function names from prior release cycles to work, the location from which the deprecated code is invoked is different than the location from which we fire the warning. Therefore, we should indeed update the stacklevel, but _only_ in `salt/utils/__init__.py`. Therefore, all 127 functions in `salt/utils/__init__.py` should be updated.

@damon-atkins would you like to open a PR for this?

**Comment by damon-atkins** [comment]
My win_pkg 43708 update for 2016.11 you reviewed for me has stalled with to many changes, looks like the back port of develop (which had next to know differences to 2017) and my added fixes will need to be targeted 2017 instead, as it was too many changes for 2016.11.  I need to work on this first.

I will update this ticket if I start on it.  Maybe add a label for this to be cleared before the next release.

**Comment by terminalmage** [comment]
I took care of this as part of https://github.com/saltstack/salt/pull/44442. Closing this one.
