### ISSUE TITLE
how to use "returner" with salt-state modules OR salt-runner ?

### ISSUE THREAD

**Issue by pratik705** [saltstack/salt#44252]
### Description of Issue/Question
I am able to use "mongo_return" returner with salt execution module:
salt 'salt-master.novalocal' test.ping --return mongo_return <==

But, I am unable to understand how I can use "returner" with any salt-state modules OR salt-runners.

Can anyone help me on the same?

### Versions Report
 salt --version
salt 2017.7.2 (Nitrogen)

**Comment by gtmanfred** [comment]
so, you can pass to the state.highstate,state.sls, or state.apply execution module, and it will be used there.

Otherwise, you could just use the returner as the job cache for the salt master.

https://docs.saltstack.com/en/latest/topics/jobs/external_cache.html

`ext_job_cache`, the minion puts the job into the cache
`master_job_cache`, the master puts the job into the cache

If you setup master_job_cache, `salt-run` would also put the job data from a salt-run command into the returner that is configured.
