### ISSUE TITLE
Windows PY3 Minion Returns UTF16 UnicodeError

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#44516]
### Description of Issue/Question
The following state works in Python 2, but not Python 3. Both minions run on Windows 2016. The PY3 version returns a UTF16 Unicode Error. This is being tested against patched versions of the `win_lgpo.py` and `reg.py` modules. 

```
configure_remote_assistance:
  lgpo.set:
    - computer_policy:
        Configure Offer Remote Assistance: Disabled
        Configure Solicited Remote Assistance: Disabled
```

```
win2016-3:
----------
          ID: router_gpo_1
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1843, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 244, in set_
                  hierarchical_return=False)
                File "c:\salt\var\cache\salt\minion\extmods\modules\win_lgpo.py", line 5021, in get
                  return_not_configured=return_not_configured))
                File "c:\salt\var\cache\salt\minion\extmods\modules\win_lgpo.py", line 3810, in _checkAllAdmxPolicies
                  policy_filedata):
                File "c:\salt\var\cache\salt\minion\extmods\modules\win_lgpo.py", line 3250, in _checkValueItemParent
                  check_deleted=check_deleted)
                File "c:\salt\var\cache\salt\minion\extmods\modules\win_lgpo.py", line 3501, in _processValueItem
                  six.unichr(len(this_element_value.encode('utf-16-le'))),
              UnicodeEncodeError: 'utf-16-le' codec can't encode character '\udd00' in position 0: surrogates not allowed
     Started: 18:44:09.868773
    Duration: 6765.204 ms
     Changes:   

Summary for win2016-3
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   6.765 s
```
### Setup
1. Stand up a Window VM with the attached Vagrantfile. 
[Vagrantfile.txt](https://github.com/saltstack/salt/files/1468133/Vagrantfile.txt)
2. Run the attach Powershell script to install the Salt minion
[install_test.ps1.txt](https://github.com/saltstack/salt/files/1468140/install_test.ps1.txt)
3. Create `C:\salt\srv\salt`
4. Add the above test state to the directory
5. Install patched versions of `reg.py` and `win_lgpo.py`
[LGPO Fix.zip](https://github.com/saltstack/salt/files/1468420/LGPO.Fix.zip)

Verify your locale info matches the following:
```
    locale_info:
        ----------
        defaultencoding:
            cp1252
        defaultlanguage:
            en_US
        detectedencoding:
            cp1252
```

### Steps to Reproduce Issue
Run `salt-call --local state.sls <whatever you named the state>`

### Versions Report
MINION VERSIONS:
    Salt Version:
               Salt: 2017.7.2
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free

**Comment by doesitblend** [comment]
ZD-1970

**Comment by doesitblend** [comment]
@saltstack/team-windows Note that I updated the instructions to included patched versions of these modules to duplicate the issue.

**Comment by damon-atkins** [comment]
In python 3 it should not be touching the strings at all.
I do not think the logic in to_unicode is correct.
```
def to_unicode(s, encoding=None):
    '''
    Given str or unicode, return unicode (str for python 3)
    '''
    #If Unicode already or not a type which can be converted to Unicode return unchanged.
    if isinstance(s, six.text_type) or not isinstance(s, (bytes, bytearray, six.string_types)) or :
        return s
    if six.PY2 and isinstance(s, str):
        return s.decode(encoding or __salt_system_encoding__)
     # can only be PY3 bytes or bytearray
     return to_str(s, encoding)
```

A diff of reg.py would be handy.

**Comment by twangboy** [comment]
@terminalmage ^^^

**Comment by lomeroe** [comment]
```
six.unichr(len(this_element_value.encode('utf-16-le')))
```

This is getting the size of the data field that is going to be stored in the regpol file.  The data field is stored in the regpol file in utf-16-le, so the size must be the size of the data in that encoding.

See https://msdn.microsoft.com/en-us/library/aa374407(VS.85).aspx (though this doesn't discuss the utf-16-le encoding of the file, but that is how the file is stored).

**Comment by damon-atkins** [comment]
Hi 	@doesitblend. Based on lomeroe anwser, can you tell me where this character is  '\udd00' i.e. the state file or in some other file like the policy files or the registry.

http://www.unicode.org/charts/PDF/UDC00.pdf   If I am reading this right   'dd00'  is not valid character

**Comment by lomeroe** [comment]
Just finally looked at the stack trace a little closer.  This is actually coming after the Regpol file has been set and the module is determining what policies are configured/etc for display back in the results.

Added some additional logging and this is the particular bit causing the trouble.

```
[DEBUG   ] creating expected string now
[DEBUG   ] reg_key == SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
[DEBUG   ] reg_valuename == MaxIdleTime
[DEBUG   ] reg value type == REG_DWORD  chr == 
[DEBUG   ] element value == \udd00m
```

I haven't had a chance to compare to a py2 minion to see what it looks like there with this same logging....

**Comment by damon-atkins** [comment]
https://apps.timwhitlock.info/unicode/inspect/hex/DD00
Low Surrogate Area
Range: DC00-DFFF
Isolated surrogate code points have no interpretation; consequently, no character code charts or names lists are provided for this range.

**Comment by damon-atkins** [comment]
six.unichr not sure what this does. I suspect it might be trying to conver the results of len to a Unicode before giving a result.   Can you try breaking the line into more parts, to see which function has the problem.

**Comment by lomeroe** [comment]
For reference, here's what it looks like on Py2:

```
DEBUG   ]  creating expected string now
[DEBUG   ] reg_key == SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
[DEBUG   ] reg_valuename == MaxIdleTime
[DEBUG   ] reg value type == REG_DWORD  chr == 
[DEBUG   ] element value == φ┤Çm
```

**Comment by lomeroe** [comment]
@damon-atkins sorry, the reg value type line is just extra data and isn't really that pertinent.  I added it to my debug output so I could see each piece that is being used in the format command.  

The 'chr == �' is the representation of how the reg value type (REG_DWORD) is stored in the regpol file.  It is non-printable (chr(4) for a DWORD), which is why it gets the non-printable symbol.

**Comment by damon-atkins** [comment]
Python 2
```
>>> print 'a:',six.unichr(len(u'hello'.encode('utf-16-le'))),'b:',len(u'hello'.encode('utf-16-le')),'c:',six.unichr(65)
a:
b: 10 c: A
>>> z=0xdd00
>>> z
56576
>>> print 'a:',six.unichr(z)
a: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\Lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\udd00' in position 0: character maps to <undefined>
>>> v=u'\udd00'
>>> v.encode('utf-16-le')
'\x00\xdd'
>>> print 'a:',six.unichr(len(v.encode('utf-16-le'))),'b:',len(v.encode('utf-16-le'))
a:  b: 2
```
Looks like codecs.charmap_encode is called by six.unichr(), which does not like invalid values.

**Comment by lomeroe** [comment]
For the particular item that is causing the exception on my system (REG_DWORD/decimal MaxIdleTime above), the possible registry value that fails is 7200000.

The code takes 7200000 and unpacks it into 2 unsigned shorts (56576 and 109), which are then converted to unicode characters (\udd00 and m).  "\udd00m" would represent 7200000 in the registry.pol file (the actual file the bytes would be \x00\xddm\x00).

In the end, what is needed is to get \udd00m in py3 to the byte string \x00\xddm\x00 (or <null>Ým<null> if you were to look at the actual file in ascii).

Py2 did this with unichr(56576) + unichr(109) which was then put into the file content and when the file content was written, it was encoded as utf-16-le.

As I noted before, this particular stack trace is occurring when the module is creating what it would expect to see in the registry.pol file for a particular policy so it can determine how it is configured to report back (via a get or in this case through the set state).  For this, it builds a string as it would expect for a particular value (since MaxIdle is a drop down, there are specific values it will test to determine which is selected).  Part of that expected string is the length -- which for \x00\xddm\x00 would be 4, which is then kept in the string as a chr, so you would see <EOT><null> if you were to look at the file in ascii.

https://stackoverflow.com/questions/31898353/python-cant-encode-with-surrogateescape has a good description of the basics behind what is going on with the surrogates and points to explanations.

It appears that on the encode (and decode) calls, we could add 'surrogatepass' to get PY3 to behave as PY2 is behaving.

```
six.unichr(len(this_element_value.encode('utf-16-le', 'surrogatepass'))),
``` 

However, 'surrogatepass' isn't valid in Py2 for 'decode', so trying to have MaxIdle set to something like 7200000 would fail in py2 when attempting to set (or if the policy has been set).  Now the problem becomes that if you were to actually set the MaxIdle to 2 hours (7200000), py2 would break as "surrogatepass" isn't valid error handler in py2 (it is for py3 and seems to work as expected) for the decode that is being done of the registry.pol file.

A further dig into https://msdn.microsoft.com/en-us/library/cc232696.aspx shows that the entire file isn't necessarily utf-16-le (as it appears to be), but only some fields are required to be (the data field being one that isn't necessarily).

So:
Individual registry.pol fields might need to be encoded/decoded as opposed to the entire file when being read/written

decimal/reg_dword data values can be only packed (instead of packed then unpacked to get the chr codes -- the same for the long decimal/reg_qword) to get the appropriate value to place in the field (if the entire file isn't being encoded/decoded, then using just the bytes for the data should be fine)

string/reg_sz/reg_multi_sz data values still appear to be utf-16-le encoded when written into the data field
