### ISSUE TITLE
Batch support for eauth not working

### ISSUE THREAD

**Issue by thequailman** [saltstack/salt#44550]
### Setup
Salt Master Config:
```
external_auth:
  pam:
    user:
      - '*':
        - 'state.highstate'
```
### Steps to Reproduce Issue

Failing Command:
```
root@salt:~# salt -a pam -b 1 '*' state.highstate
username: user
password:
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 476, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 253, in _run_batch
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, parser=self.options)
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 36, in __init__
    self.minions, self.ping_gen, self.down_minions = self.__gather_minions()
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 63, in __gather_minions
    for ret in ping_gen:
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 875, in cmd_iter
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 346, in run_job
    return self._check_pub_data(pub_data)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 256, in _check_pub_data
    'Failed to authenticate! This is most likely because this '
EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 476, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 253, in _run_batch
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, parser=self.options)
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 36, in __init__
    self.minions, self.ping_gen, self.down_minions = self.__gather_minions()
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 63, in __gather_minions
    for ret in ping_gen:
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 875, in cmd_iter
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 346, in run_job
    return self._check_pub_data(pub_data)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 256, in _check_pub_data
    'Failed to authenticate! This is most likely because this '
salt.exceptions.EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

Success command:
```
root@salt:~# salt -a pam '*' state.highstate
username: user
password:
minion1:

Summary for minion1
--------------
Succeeded: 127
Failed:      0
--------------
Total states run:     127
Total run time:    15.061 s
minion2:

Summary for minion2
--------------
Succeeded: 144
Failed:      0
--------------
Total states run:     144
Total run time:    17.689 s
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.2
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.2
```

**Comment by garethgreenaway** [comment]
@mikemcrill Thanks for the report!

**Comment by brenwhyte** [comment]
Hi,

I'm getting the same issue (I think) after upgrading to Salt 2017.7.2 from  salt 2016.11.8


`user01@syslsm001:/$ salt -l debug '*' test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/acl.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/acl.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/admins.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/admins.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/cherrpy.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/cherrpy.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/jobcache.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/jobcache.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/mastersettings.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mastersettings.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: syslsm001.*****.***
[DEBUG   ] Missing configuration file: /home/user01/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/acl.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/acl.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/admins.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/admins.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/cherrpy.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/cherrpy.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/jobcache.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/jobcache.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/mastersettings.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mastersettings.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: syslsm001.*******.***
[DEBUG   ] Missing configuration file: /home/user01/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'syslsm001.********.***_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded nested.output
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
user01@syslsm001:/$`

Same message for any non-root user added to external_auth

`external_auth:
   pam:
      user01:
         - .*
      user02:
         - test.ping
         - state.sls
         - cmd.*
         - grains.*`

**Versions Report**
`Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-141-generic
         system: Linux
        version: Ubuntu 14.04 trusty
`


I enabled auditd filelogging thinking it might be a permissions issue but nothing is logged.

**Comment by brenwhyte** [comment]
Ok, nerver mind. My issue was down to not updating the acl file.

    2018-01-26 16:35:54,132 [py.warnings      ][WARNING ][5961] /usr/lib/python2.7/dist-packages/salt/utils/event.py:1103: DeprecationWarning: ACL rules should be configured with 'publisher_acl' and 'publisher_acl_blacklist' not 'client_acl' and 'client_acl_blacklist'. This functionality will be removed in Salt Nitrogen.


    diff /etc/salt/master.d/acl.conf /etc/salt/master.d/acl.conf.bak
    2c2
    < publisher_acl:
    ---
    > client_acl:
