### ISSUE TITLE
'shadow.set_password' is not available.

### ISSUE THREAD

**Issue by pimiento** [saltstack/salt#45107]
### Description of Issue/Question
salt on my CentOS (CloudLinux) can not run shadow command `shadow.set_password`

#### /etc/salt/minion
```master: 192.168.246.49
id: bar.endpoint1
ping_interval: 3
file_client: local
use_master_when_local: True
cmd_whitelist_glob:
  - 'ls /tmp'
file_roots:
  base:
    - /srv/salt
grains:
  roles:
    - fileserver
  deployment: atm
  groupname: bar
  os: CloudLinux
  cpanel: True
  minion_blackout: True
  minion_blackout_whitelist:
    - state.apply
  aes_key: U2FsdGVkX18m8DkrW57b/U6O/oRFGjvv6EXi3FXQPR0=
providers:
  service: systemd
  pkg: yumpkg
  shadow: shadow```
#### /srv/salt/password.sls
```Create status directory:
  shadow.set_password:
    - name: foobar
    - password: $6$X9ZyELfu$HggwaWP/E/6eWTqT6u/1nwEPlMroJh/DXSUJIfhLwH3NP2OA.UCn48j4AQpd8hQ4s38mDSRBDg38RIhBEks.M.
```
### Steps to Reproduce Issue
```salt 'bar.*' state.apply password
bar.endpoint1:
----------
          ID: Create status directory
    Function: shadow.set_password
        Name: foobar
      Result: False
     Comment: State 'shadow.set_password' was not found in SLS 'password'
              Reason: 'shadow.set_password' is not available.
     Changes:   
```

### Versions Report
```
# /opt/alt/python35/bin/salt-minion --version
salt-minion 2017.7.2 (Nitrogen)
```

**Comment by Ch3LL** [comment]
`shadow.set_password` is an execution module not a state module.

You have a couple options though. If you still want to use this execution module you can use the `module.run` state module as documented here: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html and still call the execution module, but take note that because its an execution module it will run each time you call the state.

Or you can use the user state module documented here: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html which calls this execution module if the password is set. This will not try to set the password each time if it is already set and is better approach if you are running this state multiple times.
