### ISSUE TITLE
__salt__ dictionary in nested modules?

### ISSUE THREAD

**Issue by yagnik** [saltstack/salt#45252]
### Description of Issue/Question
Currently __salt__ dict is only present in the top level module, is there a particular reason we don't load into nested modules ? Would you recommend reloading salt in nested modules to access __salt__ ?

**Comment by gtmanfred** [comment]
What do you mean by `nested` modules?

**Comment by yagnik** [comment]
Say if you have this structure:
```
_modules/
  foo.py
  bar/
    __init__.py
    baz.py
```

__salt__ will be available in foo and bar but not in bar.baz module. 
I am assuming we inject __salt__ only in top level modules i.e. foo and bar.

Does that help ?

**Comment by gtmanfred** [comment]
correct, it won't be in baz, because we are only loading `bar` and `foo` in the loader.

bar.baz is imported in `bar/__init__.py` and not loaded through the loader.

You could namespace all the modules from bar.baz, into __init__.py and then they would be available

https://github.com/saltstack/salt/blob/develop/salt/utils/functools.py#L15  (it is in salt.utils in versions before oxygen)

**Comment by yagnik** [comment]
Ah I see,
in that case though I'm forced to use only functions in sub modules right  and not the whole module ? Essentially I'd prefer doing namespace(bar.baz) as opposed to namespace(bar.baz.func1).

**Comment by gtmanfred** [comment]
We do not have a function that namespaces the whole module, only individual functions.

**Comment by yagnik** [comment]
Would you be open to that being added ? I can give it a shot ?

**Comment by gtmanfred** [comment]
Absolutely!

**Comment by yagnik** [comment]
For now I bypassed it by passing salt dict into the module :(
As soon as I get some time, I'll try to figure this one out but from the looks of the code in lazyloader and how we inject globals, it doesn't look like I'll have a clean way to do this.
