### ISSUE TITLE
Links to parts in the docs scroll too low. You need to scroll up to see  heading

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#45289]
### Description of Issue/Question

If I follow this link:

https://docs.saltstack.com/en/latest/ref/states/ordering.html#state-auto-ordering

My firefox show this:

![grafik](https://user-images.githubusercontent.com/414336/34601809-e23ae6aa-f1fd-11e7-82db-d038c10abdc7.png)

I need to scroll up manually to see the heading and the first lines of this part of the docs.

BTW, do you read you docs?

**Comment by gtmanfred** [comment]
This is caused by the header, it scrolls down so that the line is at the very top of the page, instead of at the bottom of the header.

I have seen this in the past, but not recently, it is working correctly for me in chrome
<img width="984" alt="screen shot 2018-01-05 at 6 03 22 am" src="https://user-images.githubusercontent.com/732321/34610407-3bacfc3e-f1de-11e7-8590-28e0a32db6f3.png">

**Comment by MKelley80** [comment]
I can't reproduce this on Chrome 69.0.3497.81 or Firefox 62.0. The JavaScript that scrolls the page seems to be working fine.

Close? @rallytime, @gtmanfred, @garethgreenaway

**Comment by guettli** [comment]
yes I can confirm that is is working now. I guess firefox got fixed. Thank you.
