### ISSUE TITLE
execution module named `pip_state`, but examples in doc use `pip.installed:`

### ISSUE THREAD

**Issue by jf** [saltstack/salt#45342]
### Description of Issue/Question

As per description. See https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html#module-salt.states.pip_state

If the module is called `pip_state`, surely the examples should use the same name in the examples (so `pip_state.installed:`, *instead* of `pip.installed`). That's just confusing, and makes doc lookup harder when coming across a state file that uses `pip.installed`.

**Comment by gtmanfred** [comment]
The virtualname for the module is `pip` so it will be loaded as `pip`

https://docs.saltstack.com/en/latest/ref/modules/#virtualname

**Comment by jf** [comment]
I see. I am familiar with the example of the `pkg` being a virtual module and actually being implemented by multiple possible modules. What about for `pip`? Besides `pip_state`, what else implements (if you could call it that) `pip`?

**Comment by gtmanfred** [comment]
i am not sure why it was initially done, but usually it is done for the test suite so that it can be imported without conflicting with the `pip` module for the actual pip binary.  not sure why the execution module isn't pipmod if that is the case, maybe when it was originally written, tests were only written for the state module.
