### ISSUE TITLE
Deleting files older than 7 days using scheduled jobs

### ISSUE THREAD

**Issue by asymetrixs** [saltstack/salt#45821]
### Description of Issue/Question
I'd like to automatically delete files older than 7 days on Monday/Tuesday.

### Setup
Doing this by hand I used
`salt '*' file.find 'C:\Windows\Temp' type=f name=cab_\* mtime=+7d delete`
and it works perfectly. It gives a list of files that were deleted.

But how to achieve this in a scheduled job? I tried this:
`salt '*' schedule.add job1 function='file.find' job_args="['C:\Windows\Temp']" job_kwargs="['type=f', 'name=cab_*', 'mtime=+7d', 'delete']" when="['Monday 08:00pm', 'Tuesday 08:00pm']"`

And that
`salt '*' schedule.add job2 function='file.find' job_args="['C:\Windows\Temp', 'delete']" job_kwargs="['type=f', 'name=cab_*', 'mtime=+7d']" when="['Monday 08:00pm', 'Tuesday 08:00pm']"`

But when I run the job with `salt '*' schedule.run_job job1` (or `...job2`) the files only get listed, not deleted. (I know that I actually am missing the times when the job should fire)
How can I delete these files using this module in a scheduled job?

Edit:
Also tried `job_kwargs="{type: f, name: 'cab_*', mtime: '+3d', delete: f}"`

### Versions Report
Salt 2017.7.2 on Windows 7 64 Bit and Python 3.5.3 (sorry, cannot copy paste due to airgap, hope this helps)

**Comment by gtmanfred** [comment]
job_kwargs needs to be a dictionary. and delete is an arg, not a kwarg, because it doesn't have an equal sign.

```
salt '*' schedule.add job2 function='file.find' job_args="['C:\Windows\Temp', 'delete']" job_kwargs'{"type": "f", "name": "ks-*", "mtime": "+7d"}' when="['Monday 08:00pm', 'Tuesday 08:00pm']"
```

**Comment by asymetrixs** [comment]
@gtmanfred thanks, now the job runs as expected on the given times.

However, I cannot manually run the job using schedule.run_job <job>. Nothing happens when I try to run the job with job_run, except that the log shows an error similar to #45822 except that the last line is `_pickle.PicklingError: Can't pickle <function normpath at 0x00000000035AAA60>: attribute lookup normpath on salt.loader.salt.int.module.win_file failed`

**Comment by gtmanfred** [comment]
I think those are related.

The problem with windows + python + multiprocessing is that windows has no equivalent of os.fork in linux, which forks the whole process memory, and continues running with that same memory in the new process.  On windows what it does to simulate this, is pickle everything and pass it to the new process.  Unfortunately, in salt, we store all the references for all the functions in memory, so that they don't have to be loaded from files each time we want to run a command.  This is a problem in windows, because function objects are not picklable.  So I think that is what has happened, something got added to the scheduler that can't be pickled, and we need to remove it and reload it after forking.

I am going to be working on replicating that today.

As this has fixed the main issue reported here, I am going to close this issue.

Thanks, 
Daniel
