### ISSUE TITLE
minion matches all grain/pillar/mine targets after key deletion (open_mode)

### ISSUE THREAD

**Issue by jubrad** [saltstack/salt#45889]
### Description of Issue/Question
It would appear that if a minions cache is empty on the master the master may target the minion in cases that targeting shouldn't apply to it. This is a bit of a throw back/old version. We're using 2016.11.6 (updating soon) and have noticed this issue in a somewhat contrived scenario where `open_mode` is enabled and a minion-key is deleted while the minion is still running. 

Ex:

```bash
[root@salt-master user]# salt-run cache.grains ip-10-128-8-198
ip-10-128-8-198:
    ----------
[INFO    ] Runner completed: 20180206220242397846
[root@salt-master user]# salt-run cache.mine ip-10-128-8-198
ip-10-128-8-198:
    ----------
[INFO    ] Runner completed: 20180206220618267122
[root@salt-master user]# salt-run cache.pillar ip-10-128-8-198
ip-10-128-8-198:
    ----------
[INFO    ] Runner completed: 20180206220645823697
```

```bash
# the targeted machine does not have the requested grain
[root@salt-master user]# salt ip-10-128-8-198 grains.get key_not_exists
ip-10-128-8-198:

# target with the request grain anyway and it somehow tries to run on the minion
[root@salt-master user]# salt -G key_not_exists:true test.ping | grep -A 2 ip-10-128-8-198
ip-10-128-8-198:
    Minion did not return. [No response]

# but wait! that minion is responding to test.ping. Who was the master targeting previously?
[root@salt-master user]# salt ip-10-128-8-198 test.ping
ip-10-128-8-198:
    True
[root@salt-master user]# 
```

Again, this is happening on a system where we have set `open_mode: True` and where we inadvertently deleted the minion key of a machine which was still running. 

Still seems like it's worth mentioning as an empty cache should likely mean that it doesn't match targeting that it should match not the reverse.

There's definitely a bug here somewhere but my guesses about targeting when caches are empty could be off. 

### Setup
see steps to reproduce

### Steps to Reproduce Issue
Setup a salt-minion and master master using default config with `open_mode: True`
ex:
```yaml
# /etc/salt/master
open_mode: True
state_auto_order: True
log_level: info
failhard: True
master_sign_pubkey: True
worker_threads: 10
sock_pool_size: 15
```
delete the minion-key while keeping the minion service running
```bash
salt-key -d -y <minion-id>
```

target the minion via a grain, pillar, or mine you know it should not match.
```bash
salt -G not_a_grain:True  test.ping
```

### Versions Report
```
[root@salt-master user]# salt-master --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.6.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment]
So, it is not actually sending the data to the minion.

What you see on the commandline is that since there is no minion grains cache, the master has to guess that maybe that minion could respond for that request.  So it will wait for a return from that minion.

SInce it is in open mode, even though you have deleted the key, the minion is still attached to the master and can listen to the pub bus, so it is never disconnected, because any minion is allowed to connect, and the key is never actually checked to be valid.

Because of these two things, the minion is actually able to return data.  If you did not have open mode enabled, the minion would not actually see the message, and wouldn't return anything, so you would end up with the salt commandline tool printing out a message that the minion did not return.

**Comment by jubrad** [comment]
This makes sense I assumed it worked in a similar way, although, I assumed the master would make the opposite assumption [ that the minion would not be responding ]. If this is expected behavior that's great to know. Just hoping this ticket will be helpful to the next person experiencing this.

**Comment by gtmanfred** [comment]
yeah, the reason it just assumes that the minion would return because it is assumed that it would be better to wait for a return if it might come, then to just exit once we have the other that itknows will return.

Because all the master does is put the job on the pub bus, and then the minions pick it up, see if they match, and then run the job.  and then the master sends saltutil.is_running to check which minions are still running jobs, and if minions do not return an is_running response in a `timeout: ` it is assumed that they won't return at all.

So what you are seeing is the minion, even though the master doesn't know it is matched, the minion could still be sending back responses to the is_running command.
