### ISSUE TITLE
slow bash completion

### ISSUE THREAD

**Issue by colttt** [saltstack/salt#45974]
### Description of Issue/Question
 I use debian jessie and tab-copmpletion, but when i for example type : `salt '*' pkg.<TAB><TAB>`, it takes around 25s

### Setup
not necessary?! 

### Steps to Reproduce Issue
not necessary?! 

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.10 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.10

**Comment by gtmanfred** [comment]
It is slow because it reaches out to the minions to figure out what commands can be run.

It should only be slow the first time though, https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/pkg/salt.bash#L136  because it puts the function list into a cache

But it will set a timeout on that cache, so that it refreshes it after a certain amount of time.

https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/pkg/salt.bash#L132
