### ISSUE TITLE
Minion RPM package restarts on upgrade

### ISSUE THREAD

**Issue by oarmstrong** [saltstack/salt#46108]
The RPM package for the minion will automatically restart the `salt-minion` service during an upgrade of the package. This is causing issues for me as running `salt * pkg.upgrade` when there is a `salt-minion` upgrade available will restart the minion during the full system upgrade. This then leaves yum in a wonky state and for some reason during my issue the transaction wasn't able to be cleanly resolved.

Obviously, this can be worked around by upgrading the minion first (either manually or with salt). However, I do see this as a work around and not a resolution. The minion still restarts during this upgrade (and I haven't tested this) and would probably loose connection. It is rather unidiomatic in RPM-land to restart services during installation/upgrade as this seems to be more something that Debian based distributions prefer to do.

I'd like to open a discussion as to whether this is required. It's my opinion that the service should not be restarted during an upgrade. I'd like to be able to run `salt * pkg.upgrade` without worrying about whether yum is going to exit half way through due to a minion upgrade.

---

```
[ollie@salt ~]$ rpm -qp --scripts salt-minion-2017.7.3-1.el7.noarch.rpm 
postinstall scriptlet (using /bin/sh):
  if [ $1 -gt 1 ] ; then
    /usr/bin/systemctl try-restart salt-minion.service >/dev/null 2>&1 || :
  else
    
if [ $1 -eq 1 ] ; then 
        # Initial installation 
        systemctl preset salt-minion.service >/dev/null 2>&1 || : 
fi 

  fi
preuninstall scriptlet (using /bin/sh):
  
if [ $1 -eq 0 ] ; then 
        # Package removal, not upgrade 
        systemctl --no-reload disable salt-minion.service > /dev/null 2>&1 || : 
        systemctl stop salt-minion.service > /dev/null 2>&1 || : 
fi
postuninstall scriptlet (using /bin/sh):
  
systemctl daemon-reload >/dev/null 2>&1 || : 
if [ $1 -ge 1 ] ; then 
        # Package upgrade, not uninstall 
        systemctl try-restart salt-minion.service >/dev/null 2>&1 || : 
fi
```

We can see here that we restart during the `%post` section. Interestingly, we'll also restart during the `%postun` section too - a separate issue that should probably be fixed for correctness.

I am unable to trace where the restarting block comes from:

```
  if [ $1 -gt 1 ] ; then
    /usr/bin/systemctl try-restart salt-minion.service >/dev/null 2>&1 || :
  else
```

The segment after that is output by the `%systemd_post` macro but is not relevant for this issue.

---

Could this be assigned to the RPM packager? It'd be good to have a discussion about whether my thoughts on the idiosyncrasies of RPM packages are correct and what the reasoning behind the automatic restart is.

**Comment by gtmanfred** [comment]
Actually it is not unusual. This is something that the RPM spec specifys can be done.

https://fedoraproject.org/wiki/Packaging:Scriptlets#Systemd

```
On upgrade, a package may only restart a service if it is running; it may not start it if it is off. Also, the service may not enable itself if it is currently disabled. 
```

It is recommended that you keep the master up to date.  Even though we reserve the right to break it, we try to maintain backwards compatibility between the newer minions and older masters whenever possible, and it has been quite a while since that has been broken on purpose (2017.7.0 and 2017.7.1 were the exception).

Starting with 2017.7.3 and every version after, this restart should be able to happen without killing off the salt-minion process that is running the upgrade state.

If you are stuck, you can add this file.

>/etc/systemd/system/salt-minion.service.d/killmode.conf
```
[Service]
KillMode=process
```

And then run a `systemctl daemon-reload`, and it will only send a sigterm to the parent of all the processes, letting the running highstate or pkg.upgrade finish and return to the master.

Daniel
