### ISSUE TITLE
file.mkdir is not work for Chinese path

### ISSUE THREAD

**Issue by SwinBlackSea** [saltstack/salt#46210]
In py27-salt,
I had occured one problem that the file.mkdir was not worked on Chinese path.
you may say that the file.mkdir is just make the Chinese path random code,but the file.py is begain with **'UTF-8'** and I decode directory by `directory = directory.decode('utf-8')` , but isn't work; then I use `import sys;reload(sys);
sys.setdefaultencoding('gbk')   ` in header of the file.py but isn't work also.

Then I try to orientate the location in file.py by use `raise CommandExecutionError(
            "Unable to open file '{0}'".format(directory)
        )`  (not skilled in python) ; but I can't recieve any message even I delete all code of mkdir in file.py, then,one miraculous thing happened that the method of "file.mkdir" can also work on **not Chinese path**，I am so superised because the file.copy can't work if I delete the code. 

Then I think if the pyc file isn't delete? So I delete the file.pyc but it can work also.

If someone know why the phenomenon happened or the way to create directory by Chinese path (one way is to create the thired party module by salt ,but I just like salt orignal module,haha), please tell me.
Thank you!

**Comment by garethgreenaway** [comment]
@SwinBlackSea Thanks for the report.  Sounds like you might be hitting the Unicode issues that we had in previous version of Salt.  Beginning with the Oxygen release everything internally within the Salt code base will be using Unicode strings, so the issue above should be resolved.  Until Oxygen is released, unfortunately the above issue is expected behavior as we were not handling these situations prior.

**Comment by SwinBlackSea** [comment]
@garethgreenaway Thank for your replay. It's really not a problem in salt-py3 release, So you are right. but we are trying to use salt-py2 release  . So maybe I can only do this by write a self-module to make directory.
thanks!
