### ISSUE TITLE
Implement PY2 file descriptor workaround (if needed) on Mac OS/Darwin/FreeBSD/etc.

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#46319]
### Description of Issue/Question
salt/salt/utils/subprocess.py  About line 38

Check if FreeBSD, Darwin or OS X and dir exists `/dev/fd/` use `/dev/fd`
else if exist dir `/proc/self/fd` use `/proc/self/fd`
else if exist dir `/proc/<pid>/fd` use `/proc/<pid>/fd`
else slowly close them all.

Currently only supports Linux or platforms which also have `/proc/<pid>/fd`

Ref: From https://stackoverflow.com/questions/899038/getting-the-highest-allocated-file-descriptor?answertab=active#tab-top

**Comment by gtmanfred** [comment]
@isbm @terminalmage @DmitryKuzmenko can yall weigh in here?

I think @damon-atkins is bringing this up about #46286

Thanks,
Daniel

**Comment by isbm** [comment]
@gtmanfred I already answered this: my PR is initial and brings support on Linux. Whoever wants to add another OS support — feel free to write:

- Check for that OS if the fix is needed
- Implement support itself (if this is just a path — fine)
- Include a working unit test[s]

And since I have none of these OSes around, I am not going to do here anything, sorry.

**Comment by terminalmage** [comment]
:+1:  ^^^

**Comment by damon-atkins** [comment]
This was open based on the discussion in the PR by isbm.  So it would not be forgotten about.

**Comment by terminalmage** [comment]
I don't have FreeBSD but I have a NetBSD VM, and it uses `/proc/PID/fd`.

**Comment by terminalmage** [comment]
FreeBSD doesn't have anything but 0-2 (stdin/stdout/stderr) in /dev/fd, and doesn't use /proc by default.

**Comment by damon-atkins** [comment]
.
