### ISSUE TITLE
Handle deprecated code in mongodb files for Fluorine

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#46472]
The following files have deprecation notices for functions set for removal in Fluorine:

- [ ] salt/states/mongodb_user.py
- [ ] salt/states/mongodb_database.py

**Comment by terminalmage** [comment]
I've reverted the PR that initiated this deprecation. It should never have been deprecated, and the additional role management already existed in develop at the time that PR was opened.

https://github.com/saltstack/salt/pull/46597 handles reverting the deprecation. This was done in 2018.3.0rc1 because the reverted code has never been in an official release of Salt, and reverting it now before it is released (only to be removed again) would be confusing.

**Comment by rallytime** [comment]
Awesome! Thanks @terminalmage!
