### ISSUE TITLE
win_lgpo.py resets disabled policies

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#46568]
### Description of Issue/Question
While investigating the issue https://github.com/saltstack/salt/issues/46236 I ran into another problem with the LGPO module. While trying to replicate the issue above, I modified some settings in the Local Machine Group Policy using `gpedit.msc` (Windows Server 2016). I modified settings in **Computer Configuration->Administrative Templates->Windows Components->App Privacy**. I changed 2 policies to `Enabled` and 2 policies to `Disabled`. Then I applied the state defined in the above issue. I was unable to replicate the issue above, but I did notice that the Group Policy objects that were set to `Disabled` were now reset back to `Not Configured`.

### Setup
Set some policies in **Computer Configuration->Administrative Templates->Windows Components->App Privacy** to `Disabled`.
Make sure `Configure Automatic Updates` is set to `Not Configured` **(Computer Configuration->Administrative Templates->Windows Components->Windows Update)**

### Steps to Reproduce Issue
Apply the state defined in https://github.com/saltstack/salt/issues/46236

### Versions Report
Tested on 2017.7.3 and the HEAD of 2017.7 which would include 2017.7.4

@lomeroe ^^^

**Comment by lomeroe** [comment]
The disabled policies aren't being detected as actually disabled by the module.

You can see this if you disable one of those policies and then simply do an 'lgpo.get machine'

For example, with only "Let Windows apps access call history" and "Let Windows apps access the camera" disabed, the policies are not shown as disabled by lgpo.get.

We should obviously see a "Windows Components\....\Let Windows apps access call history: Disabled", which we don't.  This is then why the policies aren't staying configured (they aren't detected as disabled, so the data isn't written back into the file).

This is b/c 3 of the elements of each of those policies are "multiText" elements and the policy does not have an explicit disable setting.  The module expects the value type in the registry.pol file for a multiText element to be 7 (REG_MULTI_SZ --chr(7) in the actual file) but the **del.<valueName> are in the Registry.pol with a 1 (seen as an SOH in the file since they are chr(1)).

Modifying line 3439, from:
```
this_vtype = 'REG_MULTI_SZ'
```
to
```
this_vtype = 'REG_MULTI_SZ' if not check_deleted else 'REG_SZ'
```

Will then correctly show the policies as disabled as well as not remove the policies when configuring something else.

I checked other policies with multitext items and they all seem to behave the same way, using a 1 as the vtype when they are configured disabled by a **del entry in the registry.pol file.

**Comment by twangboy** [comment]
@lomeroe That fixes the issue. I submitted a PR for it: https://github.com/saltstack/salt/pull/46584. Thanks for looking at that.
