### ISSUE TITLE
Oxygen OpenStack Documentation.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#46633]
### Description of Issue/Question

Documentation in Develop for the OpenStack driver is confusing. The user could end up coming to 
https://docs.saltstack.com/en/develop/topics/cloud/openstack.html which has information on the old OpenStack salt-cloud driver.
While the driver documentation at https://docs.saltstack.com/en/develop/topics/cloud/config.html#module-salt.cloud.clouds.openstack is correct.

**Comment by whytewolf** [comment]
ZD-1735

**Comment by gtmanfred** [comment]
I do not see a difference here?

This should have been updated.

https://github.com/saltstack/salt/blob/develop/doc/topics/cloud/openstack.rst

The first one you are referencing is just an autodoc of the salt.cloud.clouds.openstack module.

Can you verify this?

Thanks,
Daniel

**Comment by whytewolf** [comment]
strange. it looks good now. When i had put in this ticket the content on the first page was still the old libcloud info.

**Comment by gtmanfred** [comment]
Yup, it was probably left behind from the old ones, because we didn't have a getting started doc, and our rsync command to setup the docs server doesn't delete old files that aren't on the source.

Now that the new one is there, it must have been just recently updated, so it would have overwritten the old doc.

Looks good now.

Thanks!
Closing, Daniel
