### ISSUE TITLE
Q: orchestrations after reactive state.apply

### ISSUE THREAD

**Issue by mmisztal1980** [saltstack/salt#46915]
### Description of Issue/Question

I have a salt-cloud based solution which I'm deploying to DigitalOcean.
The solution consists of:

N x NodeA
M x NodeB

After minions start, they sync grains and apply highstate, based on the reactor setup below.

**Question:**
I'd like to perform an orchestration AFTER all minions from NodeB have completed their highstate job(s).

- What would be the best way to achieve this? 
- Reactor with a custom runner? 
- Is there an example?

### Setup
**/etc/salt/master.d/reactor.conf**
```
reactor:
  - 'salt/minion/*/start':
    - '/srv/reactor/sync-grains.sls'
    - '/srv/reactor/sync-state.sls'
```

**/srv/reactor/sync-grains.sls**
```
sync-grains-on-{{ data['id'] }}:
  - local.saltutil.sync_grains:
    - tgt: {{ data['id'] }}
```

**/srv/reactor/sync-state.sls**
```
sync-grains-on-{{ data['id'] }}:
  - local.saltutil.highstate:
    - tgt: {{ data['id'] }}
```

**Comment by Ch3LL** [comment]
can't you just have the reactor call an orchestration file that then does in order: 1. grains 2. highstate 3. whatever other actions you need to perform. Then with the orch file you can use requisites to ensure order

**Comment by mmisztal1980** [comment]
@Ch3ll unfortunately I explicitly need to wait for all of NodeBs to be ready in order to start my orchestration

**Comment by gtmanfred** [comment]
What you are looking for is more complex than what the simple reactor can handle on its own.

You could do the janky way, which is to store information about the nodes in sdb, and once all the minions have been marked as returned in sdb, then the last reactor triggered by a return to sdb would start your orchestrate function by sending a new event that triggers orchestration.

Otherwise you can use the complex thorium reactor.

This allows you to have a register to know which minions have returned.

https://docs.saltstack.com/en/latest/topics/thorium/index.html

But it is worth noting that we have switched our focus from that reactor, to a complex reactor in the enterprise product, so it may require some extra work to get going with what you need, but there is a register module for registering all the minions, and you can trigger state runs, so it should work for what you need.

Daniel
