### ISSUE TITLE
[Question] Is docker.run_container supposed to use *args and pass it in as cmd to the container?

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#47288]
I am running a short living container which simply runs a bash script and then exits. While building the command, after reading the docs I assumed *args would be passed along as the arguments to the docker container. This appears to not be the case.

The first arg is the image and second is used as the container name. All other args appear to be ignored?

My example command which works as intended.
```
salt prod docker.run_container xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/update-rigdata rigdata-updater environment='AWS_PROFILE=auto_updater' replace=True force=True cmd='test test'
```

However when I move my cmd to the args it does not work. It simply ignores my other args.
```
salt prod docker.run_container xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/update-rigdata rigdata-updater test test environment='AWS_PROFILE=auto_updater' replace=True force=True
```

Is this expected behavior?

**Comment by Ch3LL** [comment]
since you did not include a salt versions report I am pasting this information based off of the 2018.3.0 version.

Here is the code for this function: https://github.com/saltstack/salt/blob/v2018.3.0/salt/modules/dockermod.py#L3149-L3159

as you can see there is only one arg: image and everything else is kwargs, and does no include `cmd` so it gets tacked on by the `**kwargs`, so yes you will have to set `cmd=<cmd to run>` to ensure it works properly.

**Comment by tyhunt99** [comment]
Sorry forgot to include the salt version. But yes I am working with 2018.3.0. That makes sense thank you
