### ISSUE TITLE
grains metadata.py should handle user-data as a string

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#47543]
The `169.254.169.254` server provides two endpoints meta-data and user-data.
Currently, both are handled by a recursive function `_search()`
user-data, however, is just a text (YAML ?) and should not be 'walked' like meta-data

**Comment by zerthimon** [comment]
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: 3.3.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-122-generic
         system: Linux
        version: Ubuntu 16.04 xenial```

**Comment by jleproust** [comment]
Hello,

I've come across EC2 VMs with non-trivial user-data scripts (shell), which makes metadata_server_grains fail with the following stack (`saltstack 2017.7.8`):
```
2019-01-29 10:21:39,676 [salt.loader      :756 ][CRITICAL][19942] Failed to load grains defined in grain file metadata.metadata in function <function metadata at 0x7fc90220ba28>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 747, in grains
    ret = funcs[key]()
  File "/usr/lib/python2.7/dist-packages/salt/grains/metadata.py", line 79, in metadata
    return _search()
  File "/usr/lib/python2.7/dist-packages/salt/grains/metadata.py", line 63, in _search
    ret[line] = _search(prefix=os.path.join(prefix, line + '/'))
  File "/usr/lib/python2.7/dist-packages/salt/grains/metadata.py", line 72, in _search
    ret[line] = json.loads(retdata)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

What happens is that `grains/metadata.py` fetches `/latest/user-data`, which returns a `text/plain` document with many lines, and recurses on each line. Then each recursive fetch fails with a `404` obviously, but `json.loads()` is still called with `None` so fails.

This is grave because it prevents a minion from applying the high state. The only workaround for us is either to disable `metadata_server_grains` or to patch the grains module.

I don't know why some of my VMs return the user-data as `text/plain` and others as `application/octet-stream`, I can see no pattern.

@gtmanfred I can provide you with a PR if the fix is easy enough, would it be acceptable to hard-code the `meta-data` and `user-data` paths and only recurse on the former? or would it break on other providers?

**Comment by jleproust** [comment]
Well the issue is precisely that we can't trust the content-type for the user-data. It can be `text/plain` or `application/octet-stream`, with no visible pattern, but we never need to recurse. So the easiest fix would be to never recurse on the path `/latest/user-data`. Is it ok for you?

**Comment by gtmanfred** [comment]
Yeah, i am fine with that.
