### ISSUE TITLE
issue in acl using array

### ISSUE THREAD

**Issue by thatsk** [saltstack/salt#47896]
i want to use salt acl using publisher acl

salt "node" pkg.install pkgs='["pkg1", "pkg2"]'

/etc/salt/master

publisher_acl:
  user1:
    - test.ping
    - pkg.clean_metadata
    - node:
        - pkg.install:
            args:
              - 'pkg2'
              - 'pkg1'

user@node: /opt/salt-scripts/ci-cp$ salt "node" pkg.install pkgs='["pkg1", "pkg2"]'
getting new repodata
node:
    True
Updating pkg1 & pkg2
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

**Comment by Ch3LL** [comment]
what version of salt are you using?

**Comment by thatsk** [comment]
2016

**Comment by Ch3LL** [comment]
thanks for clarifying that. Since you are passing a kwarg you would need to specify kwarg instead of arg, but I still am not able to get this to work. Setting the following in the master config:

```
publisher_acl:
  saltdev:
    - '*':
      - 'pkg.install':
          kwargs:
            'pkgs':
              - 'pkg'
```

and running `salt '*' pkg.install pkgs="['pkg']" -ldebug` i am seeing error  `Invalid regular expression: [u'pkg']`. in the master log.

ping @DmitryKuzmenko seems you added this feature initially any ideas here am I setting this up incorrectly or we just need to update the code to handle kwargs that include lists in them?

**Comment by DmitryKuzmenko** [comment]
@thatsk , @Ch3LL 
Yes, you're correct, that functionality works for the only string values. I'll think about the best way to adopt it for list and dict values.
