### ISSUE TITLE
multi master exec command return failed

### ISSUE THREAD

**Issue by slhu91** [saltstack/salt#47963]
### Description of Issue/Question
when we use multi master，exec   salt "*" test.ping，always exist some minions return true and some minions did not return，but all the minion is exec success，the result from cache/master/jobs/。And I shared the cache directory  cache/master/jobs、pki。
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
![image](https://user-images.githubusercontent.com/14175152/40973630-96721e7a-68f7-11e8-8294-205433d7f69c.png)

**Comment by Ch3LL** [comment]
Can you clarify your issue I am having a hard time understanding. Are you stating your issue is that some minions are not returning when they should be or maybe there is something missing from the cache?

Also was this working in a previous release?

**Comment by slhu91** [comment]
When I use the multi master、multi syndic, when the command is executed on the master, all the minions are executed successfully, but the master display part of the minion is not returned. I save the result to mysql, master_job_cache: mysql  and return: mysql, and  all minion return true from mysql query.

both of minion 、syndic  and master is 2018.3.0

**Comment by Ch3LL** [comment]
Thanks for further clarifying, I believe I understand the issue now. Probably the reason you are seeing the return in your mysql return information instead of when running the command from the master is the timeout is timing out when running the command from the master. The timeout value which defaults to 5 is the time the master will wait for a minion return. So probably what is happening is the minion is still running the command even though the master has stopped waiting for the results it will still post the return to the msyql returner database because the command is run asynchronously on the minion so if the timeout has exceeded on the master it does not kill the job it still continues running on the minion.

Just to verify do you have a minion running onyour salt-syndic? As described in this documentation: https://docs.saltstack.com/en/latest/topics/topology/syndic.html  this can speed up things:

> While it is possible to run a Syndic without a Minion installed on the same system, it is recommended, for a faster CLI response time, to do so. Without a Minion installed on the Syndic node, the timeout value of syndic_wait increases significantly - about three-fold. With a Minion installed on the Syndic, the CLI timeout resides at the value defined in syndic_wait.

So you could possibly be running into slowness due to not having a minion setup as described above.

Lets verify that my theory is correct. If you increase the the timeout value which you should be able to do  on the cli or in teh master config:
   - master config: `timeout: <number in seconds>`
   - cli: `salt '*' test.ping -t 30`

If you are still not seeing the results return make sure you change the `syndic_wait` time and see if that helps also described in that documentation.

The one thing that I really want to verify for you is I want to make sure the returns are returning to the master you are expecting. Can you verify that the minion returns that are not returning are not trying to return to the other master instead? This would definitely be an issue.

Also do you know if this was a regression or if this is a first time setup for you? If its a regression then we might need to look into performance issues.

**Comment by slhu91** [comment]
I think this is because the random selection of a master is not a performance problem when syndic is returned. So when I execute a command on one of the masters, I only see a part of the minions returning.

**Comment by Ch3LL** [comment]
Can you clarify what you mean by "the random selection of a master"? Did you verify if the commands return if you increase the timeout?
