### ISSUE TITLE
Updating SNMP Configurations on network device

### ISSUE THREAD

**Issue by prashanthtuttu** [saltstack/salt#47961]
Hi,
I am following 
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.netsnmp.html#network-snmp
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.napalm_snmp.html#module-salt.modules.napalm_snmp  to update SNMP configurations on my test device.

Though i am able to update contact & location , im not able to update SNMP community string , ACL's and read-write option , can anyone help me with few examples.

Thanks in advance.

Regards,
Prashanth

**Comment by Ch3LL** [comment]
ping @mirceaulinic can you take a look here? is there somewhere else in the docs that would outline this?

**Comment by prashanthtuttu** [comment]
@mirceaulinic , Also wanted to know is there any way to compare the current SNMP config on a device against a template using saltstack ?

**Comment by prashanthtuttu** [comment]
Hi @mirceaulinic / @Ch3LL ,
 Any update on above request ?

**Comment by prashanthtuttu** [comment]
Can anybody suggest me some options on the above request?

**Comment by Ch3LL** [comment]
apologies I am not versed in this area at all. let me try to get someone from the network team.
ping @saltstack/team-network any chance you can take a look here.

**Comment by prashanthtuttu** [comment]
@saltstack/team-network , any update on my request?

**Comment by mirceaulinic** [comment]
Hi @prashanthtuttu - yes, there's an issue with that state. You can use https://docs.saltstack.com/en/latest/ref/states/all/salt.states.netconfig.html, or simply use this pre-written formula: https://github.com/saltstack-formulas/napalm-ntp-formula/.

**Comment by prashanthtuttu** [comment]
Thank you @mirceaulinic - Let me give it a try on the same.
Also when i write my own custom modules and do a salt-call , i get error like module not found though the standalone python script works. Is there something im missing here?

**Comment by mngan** [comment]
I found a few things that were stopping this from working. If you specify the community as a dictionary then _clear_community_details bombs out due to a typo. The community defaults should also include acl so that a dict comparison will work properly. But the main one is that the logic for the diff is all messed up. If the value is None in both the previous and current dicts then it will always try to add a key with a None value. Keys are never updated because the third test is inverted. It should remove the "not" in the expression. I found all this while trying to track down why I was getting an empty snmp config being applied to my Juniper device. Turns out that it was because the code was trying to add an extraneous chassis_id key with a None value, and the Junos template doesn't support a chassis_id key. So the Junos template issue is solved by correcting the diff code. 

```
diff --git a/salt/states/netsnmp.py b/salt/states/netsnmp.py
index 9bafffefbc..d14955ad0e 100644
--- a/salt/states/netsnmp.py
+++ b/salt/states/netsnmp.py
@@ -107,7 +107,8 @@ def _community_defaults():
     '''

     return {
-        'mode': 'ro'
+        'mode': 'ro',
+        'acl': ''
     }


@@ -120,7 +121,7 @@ def _clear_community_details(community_details):
     for key in ['acl', 'mode']:
         _str_elem(community_details, key)

-    _mode = community_details.get['mode'] = community_details.get('mode').lower()
+    _mode = community_details['mode'] = community_details.get('mode').lower()

     if _mode in _COMMUNITY_MODE_MAP.keys():
         community_details['mode'] = _COMMUNITY_MODE_MAP.get(_mode)
@@ -216,11 +217,11 @@ def _create_diff(diff, fun, key, prev, curr):
     Builds the diff dictionary.
     '''

-    if not fun(prev):
+    if not fun(prev) and fun(curr):
         _create_diff_action(diff, 'added', key, curr)
     elif fun(prev) and not fun(curr):
         _create_diff_action(diff, 'removed', key, prev)
-    elif not fun(curr):
+    elif fun(curr):
         _create_diff_action(diff, 'updated', key, curr)
```

**Comment by prashanthtuttu** [comment]
Thank you @mirceaulinic , Can you please provide some examples on the usage of updating the community , acl and mode attributes

**Comment by prashanthtuttu** [comment]
@mirceaulinic - please let me know incase if there is there any pre-written formula for **napalm-snmp configuration**
