### ISSUE TITLE
Notify changes in Salt minion to master with timings and user details

### ISSUE THREAD

**Issue by vimalkesavan** [saltstack/salt#47995]
Hi Team,

I am new to salt, I have a masterless minion that watches some files.  The salt call command  salt-call state.highstate --state-output=changes runs daily as a crown job. 

Now I need to connect the masterless minion to master and make it work in master minion mode. I need to notify any changes that earlier masterless minion which is now normal minion watches to notify to the master.

Basically I need a dynamic notification from minion to master which includes file details and user details.

Can this be done.

**Comment by garethgreenaway** [comment]
@vimalkesavan Thanks for the report.  To clarify, what you're looking for is the ability for any previous actions performed on the masterless Salt minion before it was added to the master to be reported back to the Salt master?

**Comment by vimalkesavan** [comment]
No . Actually what I need, is to notify the master that which all files were modified in minion then and there itself.  It is just that the files/directories I am using for watching the changes were earlier configured to restored using salt call command when there were working as masterless salt-minion earlier.

I have using beacons and inotify, but the problem is that we need to give the files manually. Instead all the files and directories should be watched that will be restored using salt-call command in the earlier masterless minion. 

Thanks,

Vimal

**Comment by vimalkesavan** [comment]
Hi Gareth,

Kindly update on the issue if you have any answer on this.

Thanks,

Vimal Kesavan

**Comment by gtmanfred** [comment]
You don't have to switch away to using a master to watch these files, if you have a generic way to watch all modified files that is working for you in masterless mode, you can continue to use `salt-call` in minion-master mode.  If you want the master to trigger running the jobs, you will need to use the inotify beacon + reactor in order to do it.

Otherwise, If it works now for masterless, i would stick with just calling salt-call when you need to.
