### ISSUE TITLE
Autoloading Utility Modules?

### ISSUE THREAD

**Issue by onmeac** [saltstack/salt#48025]
### Description of Issue/Question
In https://docs.saltstack.com/en/2017.7/topics/utils/index.html it is written that 

> Utility modules placed in salt://_utils/ will be synced to the minions when any of the following Salt functions are called:
>   - state.apply
>   - saltutil.sync_utils
>   - saltutil.sync_all

But following the examples displayed on that page does not seem to work.
`state.apply` does not appear to sync anything from _utils.

### Steps to Reproduce Issue
_utils/foo.py
```
# -*- coding: utf-8 -*-
'''
My utils module
---------------

This module contains common functions for use in my other custom types.
'''

def bar():
    return 'baz'

```

foo.sls state
```
#!py
import salt.config
import salt.loader

# required? else __utils__ not available...
__opts__ = salt.config.minion_config('/etc/salt/minion')
__utils__ = salt.loader.utils(__opts__)


def run():
    print __utils__['foo.bar']()

```
command
```
salt-call state.apply foo

local:
    Data failed to compile:
----------
    Rendering SLS 'base:foo' failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 589, in py
    data = mod.run()
  File "/var/cache/salt/minion/files/base/foo.sls", line 11, in run
    print __utils__['foo.bar']()
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1117, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'foo.bar'

```

with saltutil.sync_utils
```
salt-call saltutil.sync_utils; salt-call state.apply foo

local:
    - utils.foo

baz
baz

local:
Summary for local
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
Total run time:  0.000 ms

```

### Versions Report
```
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

```

**Comment by terminalmage** [comment]
This is a documentation issue that I introduced when I replaced references to `state.highstate` with `state.apply`. The `state.apply` function is a convenience function for running states. When it is run with no arguments, it runs a `state.highstate` (this behavior is described [here](https://docs.saltstack.com/en/latest/topics/tutorials/states_pt1.html#install-the-package)). When run *with* arguments, then it runs a `state.sls`, which just runs individual SLS files.

Custom modules *are* synced during highstates, but not when running individual SLS files. The rationale behind this is that a highstate is meant to be a single action where you can run all the things in a single pass, where as running indivdual SLS files is more of a one-off action, and thus we should not slow down its execution by also syncing all custom modules.

@thatch45 should I change it so that a `state.sls` will also sync custom modules, or should I just update the docs to accurately state that custom modules are synced when running a highstate, and not *any* time `state.apply` is invoked?

**Comment by thatch45** [comment]
Yes, lets update the docs

**Comment by onmeac** [comment]
Thank you for clarifying, though this is unfortunate.

We had hoped that modules would also be synced when just wanting to apply a single state.
Would it be possible to provide some kind of flag/option?

**Comment by terminalmage** [comment]
@onmeac yes, that is definitely doable

**Comment by terminalmage** [comment]
@onmeac See https://github.com/saltstack/salt/pull/48037.

**Comment by onmeac** [comment]
Awesome, tyvm

**Comment by terminalmage** [comment]
No problem! Thanks for helping to point this out.
