### ISSUE TITLE
Question - how to best handle multiple customer environments

### ISSUE THREAD

**Issue by GitHubAre** [saltstack/salt#48063]
### We have many customers (200+). For our customers we will automate deployments (by deployment I mean like publishing a website to web server) by using SALT on the other hand I would love to use SALT for internal server management (installing software, OS updates, cleanup of log files, ...). I would be thankful for your opinion on how to handle the following scenario:

1. Our environment is in Azure and I would like to automate general tasks - like creating and setting up a new build server, joining computers to domain, rolling OS updates etc.
2. Our project have several internal (also could say development) environments, but those environments are not using staged deployments (we dont do dev=>qa=>stage=>prod), instead we have several independent testing environments internally in Azure (those environments are not visible to our customer).
3. Our customers have their own servers which are usually consisting of Test and Production environment, so when we perform deployment, we first deploy to their testing env, and later to prod.

I have been googling about "environments in Salt", but I am not convinced whether we really need it (maybe I could have two environments - test and prod where test would be for testing our Salt scripts and playbooks). But I am not sure how to best handle cases where I want to target specific customer environment for deployment - f.e. single test environment of one customer out of those 200 customers.

**Comment by gtmanfred** [comment]
I would stick to two environments, one for testing and one for prod.

Then i would write templated formulas, that pull all of the individual data for each customer from pillar data.  Then you just assign the necessary pillar data to each customers servers based on the hostnames of their machines.

And then if you setup the hostnames in a specific fashion.

`<app>.<test/prod>.<customername>`

Then you can target the testing environment for one customer, `'*.test.customer1'`, and run just a highstate on those guys.

This will also be useful for your testing environment, because you can have a whole bunch of pillar data that is based around the customer name as well, and then a prod/test environment in the same top file.

**Comment by GitHubAre** [comment]
Thank you for such a quick reply!

Can you please describe little bit more this part:
`Then i would write templated formulas, that pull all of the individual data for each customer from pillar data. Then you just assign the necessary pillar data to each customers servers based on the hostnames of their machines.`

**Comment by gtmanfred** [comment]
Take a look at the saltstack-formulas repository, and you will see a bunch of examples of writing generic formulas, and configuring them using pillar data.

https://github.com/saltstack-formulas/apache-formula/blob/master/pillar.example#L41
