### ISSUE TITLE
Pass in pillar file with salt-call for state execution

### ISSUE THREAD

**Issue by dgengtek** [saltstack/salt#48076]
### Question

I am already able to use `$ salt-call --local --pillar-root=pillar`. Is there some other way to pass in for example a single pillar file to override settings from the pillar root? Thought this would be possible `$ salt-call --local state.sls test pillar=@mypillarfile.sls`.

Could not find anything in the documentation and grepping sys.doc output had no results either in that direction. Am I missing something?

Thanks

**Comment by gtmanfred** [comment]
Everything that is passed in from the commandline is passed through the yaml safe loader, so you should be able to just do.  

But otherwise, pillar is just pillar data, so you would need to cat in the file

```
$ salt-call --local state.sls test pillar="$(<pillar/path/to/mypillarfile.sls)"
```

or `"$(cat path/to/mypillar.sls)"`, `$(<file)` does the same thing as catting the file out.
