### ISSUE TITLE
Support for new system role 'Transactional Server' in openSUSE Leap 15.0

### ISSUE THREAD

**Issue by WackyOne** [saltstack/salt#48168]
openSUSE Leap 15.0 has added a new system role called _Transactional Server_, which features a new update system that applies updates atomically (as a single operation) and makes them easy to revert should that become necessary. It is an outcome of the openSUSE Kubic effort.

To work with transactional updates, the command **transactional-update** is used instead of YaST and Zypper for all software management. I'm not sure of all of the ramifications, but obviously the zypper execution module from salt.modules.pkg is no longer appropriate. If it is as simple as adding the execution module transactional-update and being able to pick it properly from the pkg state it might not be a big deal, but I'm probably missing out on some of the finer points.

Any chance people are looking into this?

**Comment by Ch3LL** [comment]
ping @saltstack/team-suse any comments here?

**Comment by isbm** [comment]
@WackyOne, the transactional update is not what you think. It is not used _instead_ of YaST and Zypper. What it actually does is that it _wraps_ Zypper, allowing you to update read-only FS by taking snapshot of it, install all the packages you would need into it, save it, and then tell you which it is. So then the next time you reboot into this snapshot, you will have your software available. In case error, you always can reboot into a previous snapshot. So this is what it is for. Obviously, it works only with the default BTRFS file system.

Current Zypper Salt module won't help you here at all, as it doesn't work with the snapshots. There are lots of underlying parts where Salt should get it right knowing what snapshot to take on etc. And so right now this feature is not yet supported in Salt. To cheer you up, I am saying "yet", because we are going to write a separate module for this. Soon enough... :wink: 

@Ch3LL this issue can be closed.

**Comment by WackyOne** [comment]
Thanks @isbm , it's good to know it is being worked on. How will the module interact with a `pkg.installed` state? It sounds like it won't just call the `transactional-update` command.

**Comment by isbm** [comment]
It should be something more extended than just `pkg.installed`, as it installs "elsewhere", not on the direct machine (though it is). So the changes take effect only after the complete reboot. And therefore it should be treated more like a work with the snapshots. This is why I think here more sort of a separate, snapshot-aware approach, rather then direct installation.

**Comment by MAHDTech** [comment]
Wouldn't a better mechanism be to include knowledge of transactional-update into zypper upstream by SUSE similar to how zypper currently handles btrfs snapshots.

Then not only does there need to be no extra work done in salt, but every current openSUSE user doesn't have to remember to use `transactional-update`  when their muscle memory keeps typing `zypper`.

Not to mention all the existing scripts out there they need logic to handle the newer format :roll_eyes:

**Comment by brejoc** [comment]
Like mentioned on the zypper issue (https://github.com/openSUSE/zypper/issues/198) I think it makes perfect sense to have a separate module for this and I think @meaksh already started working on this.

I really feel your pain with the scripts and the muscle memory, @MAHDTech. It's the same for me. But a transactional server behaves completely different from a traditional server and having `transactional-update` handle this is the way to go. At least for now.

**Comment by meaksh** [comment]
As @brejoc mentioned, I've already started working on the `transactional-update` module for Salt. Hopefully it will be ready soon.
