### ISSUE TITLE
Feature: Solaris support for disk.usage

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#48427]
### Description of Issue/Question
solaris `df` needs `-k` just like AIX and FreeBSD for parsable disk info. 
Please add a test for Solaris

### Setup
try and use disk.usage on Solaris.

### Steps to Reproduce Issue
try and use the current disk.usage on Solaris

**Comment by rallytime** [comment]
@dmurphy18 This should be a quick change that is needed right around [here](https://github.com/saltstack/salt/blob/c0d42793135eebdba9cd97abf296339b05b7c7ae/salt/modules/disk.py#L107). Can you fix this for Fluorine, please?

**Comment by dmurphy18** [comment]
@whytewolf The default for Solaris is 1K blocks, and the output of df and df -k were found to be the same:
df > d.txt
df -k > k.txt
diff d.txt k.txt produced no difference.

Note I am getting errors with parsing the output on Salt 2018.3.2 when salt abc disk.usage.  
Could that be the issue that is being reported ?

**Comment by dmurphy18** [comment]
With the Salt 2018.3.2 release

Running salt-call --local disk.usage [k] works on Solaris 10 (Intel), both with and without argument k.

Running the same on Solaris 11, _salt-call --local dish.usage k_ functions correctly, but fails without the optional _k_ argument, the error _[ERROR   ] Problem parsing disk usage_ information  occurs.

This is probably due to the missing header line from the output of _df_ on Solaris 11
**Filesystem            kbytes    used   avail capacity  Mounted on**

**Comment by dmurphy18** [comment]
Problem is due to missing space on Solaris 11

From Solaris 10 line:
/                  (/dev/dsk/c0t0d0s0 ): 5379098 blocks   644184 files

From Solaris 11 line:
/                  (rpool/ROOT/solaris):23919631 blocks 23919631 files

Missing the Space after the colon for parameter 2 on Solaris 11

**Comment by dmurphy18** [comment]
This is more complicated that, seeing issues with Solaris 10 too depending on time of day. Additional problem is that the code is assuming that the device is at the end (as when -k is used) rather than the start of the line hence the following problematic lines:
/                  (/dev/dsk/c0t0d0s0 ): 5372840 blocks   644179 files
/lib/libc.so.1     (/usr/lib/libc/libc_hwcap1.so.1): 5372840 blocks   644179 files
/system/zones      (rpool/VARSHARE/zones):23912250 blocks 23912250 files
where labels and size have eaten all of the whitespace etc.

Given this day and age, simple solution is to change to defaulting to 1K blocks rather than bytes.  Using Bytes was probably okay back in the day, but we are now into the realm of Terabyte hard drives etc.

Will change to 1k blocks as default and add versionchanged:: Fluorine

**Comment by rallytime** [comment]
@whytewolf This should be fixed with #48833
