### ISSUE TITLE
salt-cloud Should Generate Minion Key on the Minion

### ISSUE THREAD

**Issue by doc987** [saltstack/salt#48483]
I think the way salt-cloud currently works is that the public/private key pair is generated on the master, saved to a temporary directory, and then copied to the minion.  At least that's what I think based on what I have observed.  I didn't actually see it written down anywhere.  Please correct me if this is not accurate.

Shouldn't the key pair be generated on the minion, and then the public key (and not the private key) copied to master?  That way the private key wouldn't touch the disk of the master, or be transmitted over a network.  It might be argued that these are low risk areas, but what's the advantage of generating the key pair on the master?

**Comment by gtmanfred** [comment]
You are correct that this is the way it is currently generated.

A PR would be welcome to change this to the way you are talking about, it would just need to use the key generation wheel function, and then copy it back, and since this is all done with bash commands this is significantly more complicated because we do not have a command line interface for that portion of salt.

**Comment by doc987** [comment]
If it's currently done with bash commands, why not continue to do so?  Something like the following might be run on the minion, adding options where appropriate (e.g. key size, key type).
```sh
openssl genrsa -out /etc/salt/pki/minion/minion.pem
openssl rsa -in /etc/salt/pki/minion/minion.pem -pubout -out /etc/salt/pki/minion/minion.pub
```
Then run scp on the master.
```sh
scp user@example.com:/etc/salt/pki/minion/minion.pub /etc/salt/pki/master/minions/example.com
```

**Comment by gtmanfred** [comment]
@techhat @thatch45 can one of yall weigh in on why the bootstrap process in salt-cloud makes the minion key on the master and transfers it over instead of making the key on the minion and copying the key back?

**Comment by techhat** [comment]
The keys are generated in Python, internally in Salt Cloud, not with bash commands. 

Because the master normally has unfettered access to the minion (unless explicitly restricted), creating the keys on the minion in order to keep the private key off the master will not increase security. I'm not sure how you would secure a minion so that the master would not have access to just copy its private Salt key back.

Unless I'm missing something here, I don't think there's any real advantage, in terms of security, of generating keys on the minion and then copying the pub key back. It would however add more moving parts, and Salt Cloud has more than plenty of those.

**Comment by doc987** [comment]
Advantages of generating the minion private key on the minion include:
- Minion private key is never passed over a network.
- Minion private key never touches the disk of any system other than the minion.

Even if the salt master process has full access to the salt minion, the minion private key could be compromised in either of the above cases by something other than the salt master process.

That being said, one might still make the argument the level of risk reduction is not worth the time or increased complexity required to make this work.

**Comment by gtmanfred** [comment]
I think that is the point that we are at. The key is transfered across the network using winrm https (unless you explicitly disable it) or ssh. If one of those is compromised there are bigger problems.

I am going to close this issue

Thanks for bringing this up.
Daniel
