### ISSUE TITLE
salt-cloud Prompt for Password

### ISSUE THREAD

**Issue by doc987** [saltstack/salt#48565]
Can ```salt-cloud``` prompt the user for a password if neither a key file or password is provided in the profile?

**Comment by Ch3LL** [comment]
i don't believe this is possible but to make sure ping @saltstack/team-cloud

**Comment by gtmanfred** [comment]
It cannot, and I am not sure we want to add that.

**Comment by doc987** [comment]
If the key or password is part of the configuration, then there could be a problem if the machine is compromised.  If the credentials are not directly available (e.g. requiring an ssh password to be provided, or requiring a key decryption password to be provided, etc.), then this adds a layer of security.

**Comment by gtmanfred** [comment]
But you can always use something like sdb, and store it elsewhere.

Or set it in an environment variable so that it is not stored in your config files.

https://docs.saltstack.com/en/latest/topics/sdb/

https://docs.saltstack.com/en/2017.7/ref/sdb/all/salt.sdb.env.html

If you are really concerned about that, this is what I would use, or something like the keyring sdb, which you can unlock before salt-cloud gets started.

If your salt master server gets compromised, there are more things you should be concerned about than the default password to log into images.  Which can be changed once the salt-minion is installed.

And if you use an ssh key, if the compromise the salt master, they can already contact all of the minions, why would they care about the ssh key.

**Comment by gtmanfred** [comment]
But if what you want to do is just be able to input it at the command time, just store it in keyringdb, and use a backend that asks for a password to decrypt the keyring.

https://docs.saltstack.com/en/2017.7/ref/sdb/all/salt.sdb.keyring_db.html

**Comment by doc987** [comment]
I mentioned this with respect to ```salt-cloud```, but I think applies to any command that directs minions to do something.  I think an encrypted master key might now work (#42587) with the ```salt``` command, but I haven't tried it, as that update was after the 2017.7.3 version I currently have.  If I encrypt the master key, will running the ```salt``` command trigger a prompt for a password?  Reading that PR, and in light of your comment, I'm thinking that mechanism also relies on keyring sdb, so maybe using the keyring will work for all salt commands.

**Comment by Ch3LL** [comment]
@gtmanfred after searching for a separate issue i actually found this feature: https://github.com/saltstack/salt/pull/12291

looks like its only for openstack though

**Comment by gtmanfred** [comment]
I am pretty sure that was removed, and replaced with the keyring sdb module.

**Comment by Ch3LL** [comment]
ahh gotchya thanks for clearing that up
