### ISSUE TITLE
salt-cloud. Non-root users can use it by default. Is it normal?

### ISSUE THREAD

**Issue by 4815162342lost** [saltstack/salt#48806]
Hello,

I noticed that non-root users can execute the any salt-cloud command 'by default':
```
[vodka@cent_os_1 ~]$ salt-cloud -a create_snapshot asasas snapshot_name="just_for_fun" description="why not" memdump=False quiesce=False
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/cloud?
The following virtual machines are set to be actioned with "create_snapshot":
  asasas

Proceed? [N/y] y
... proceeding
```

We receive only warning error. is it a normal behavior? Or is it a security issue?

Thanks.

**Comment by gtmanfred** [comment]
Non root users should be able to run the commands.  To prevent them from being able to do anything, set your cloud config directories to 700, so that they cannot look at any config files in there.

@dmurphy18 we should fix this in the salt-cloud packages, /etc/salt/cloud.providers.d/ and /etc/salt/cloud.profiles.d should probably be given 700 permissions for the packages, like /etc/salt/cloud has so only the root user can read them

```
[root@ddc23355e676 /]# ls -ld /etc/salt/cloud*
-rw-r----- 1 root root 2926 Jun 21 17:15 /etc/salt/cloud
drwxr-xr-x 2 root root 4096 Jun 21 18:20 /etc/salt/cloud.conf.d
drwxr-xr-x 2 root root 4096 Jun 21 18:20 /etc/salt/cloud.deploy.d
drwxr-xr-x 2 root root 4096 Jun 21 18:20 /etc/salt/cloud.maps.d
drwxr-xr-x 2 root root 4096 Jun 21 18:20 /etc/salt/cloud.profiles.d
drwxr-xr-x 2 root root 4096 Jun 21 18:20 /etc/salt/cloud.providers.d
```

**Comment by dmurphy18** [comment]
@4815162342lost Can you confirm that this issue is now fixed in the latest Salt point release, and if so, close this issue.
