### ISSUE TITLE
salt-cloud. Can not create create snapshot for servers which use 'Disaster Recovery Replica created VMware Site Recovery Manager'

### ISSUE THREAD

**Issue by 4815162342lost** [saltstack/salt#48805]
Hello @all,

Sorry, i am not VmWare specialist and can be wrong in some term, but i will try to  describe the situation.

We have two DC: DC1 and DC2.
Several servers located in DC1, several servers in DC2. But we have 3 servers which use _'Disaster Recovery Replica created VMware Site Recovery Manager'_. It is very cool[ VmWare feature](https://youtu.be/5OaSemd8qAc).

But on DC1 we have a real server. On DC2 we have 'copied fake server', look to pic:
https://imgur.com/a/i2UYvIe

Via salt-cloud we can not choose the correct VmWare farm and we can not create snapshot, because salt-cloud tried to create snapshot for 'copied fake server':
```
[me@secrect_host]$ sudo salt-cloud -y -a create_snapshot VM snapshot_name="just_for_fun" description="why not" memdump=False quiesce=False
[ERROR   ] Error while creating snapshot of VM: (vim.fault.MethodDisabled) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = "The method is disabled by 'com.vmware.vcDr'",
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   source = 'com.vmware.vcDr'
}
vmware_farm_on_DC2:
    ----------
    vmware:
        ----------
        vm:
            failed to create snapshot
```

Could you please suggest something?

Thanks in advance!

**Comment by gtmanfred** [comment]
Can you please provider the `--versions-report` like the issue template requested?

Thanks,
Daniel

**Comment by 4815162342lost** [comment]
hello, thanks for your reply.

Salt-version:
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: 3.6.0
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: ISO-8859-1
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by gtmanfred** [comment]
ok, and from my understanding of how disaster recovery works, both machines would have the same name?

I think this is something that is a limitation of salt-cloud specifically the vmware driver.  One of the things that wasn't really built in when salt-cloud was the ability to have servers with the same name in different setups, so it is kind of a race condition, which ever server is returned back first for a lookup of that name is assumed to be the only one.

```
    for obj in object_list:
        obj_id = six.text_type(obj.get('object', '')).strip('\'"')
        if obj[property_name] == property_value or property_value == obj_id:
            return obj['object']
```

Based on the code in salt.utils.vmware, we look for the first vm_ref with that name, and just return it, which could be your fake machine or the real one.

If the two machines could be distinguished by names, that would be the best way to work around this.  Like include the `dc1` or `dc2` in the name of the machine.

Otherwise, i think that this is going to require some reworking of the salt-cloud vmware driver to fix this.

@nmadhok can you take a look?

Thanks for reporting.
Daniel
