### ISSUE TITLE
Install requires "universe" on Ubuntu Bionic

### ISSUE THREAD

**Issue by pcdummy** [saltstack/salt#48923]
I tried to install "salt-minion" on a fresh Install from the Server iso, it failed first with

```
root@mediak01:~# LANG=C apt install salt-minion
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-minion : Depends: python-zmq (>= 14.4.0) but it is not installable
               Depends: salt-common (= 2018.3.2+ds-1) but it is not going to be installed
               Recommends: debconf-utils but it is not installable
E: Unable to correct problems, you have held broken packages.
```

After activating **universe** in **/etc/apt/sources.list** installing salt-minion worked, does this need a **note** somewhere on repo.saltstack.com?

**Comment by gtmanfred** [comment]
universe exists in vanilla ubuntu installs.

**Comment by jf** [comment]
I am getting the same message as well on a fresh install off of the bionic install cd (`ubuntu-18.04.1-live-server-amd64.iso` from https://www.ubuntu.com/download/server)

It seems that the list of entries is way shorter than for 16.04:
```
$ cat /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu bionic main
deb http://archive.ubuntu.com/ubuntu bionic-security main
deb http://archive.ubuntu.com/ubuntu bionic-updates main
$
```

**Comment by gtmanfred** [comment]
@dmurphy18 how do you feel about adding a not on the repo.saltstack.com page saying that universe needs to be enabled?

**Comment by dmurphy18** [comment]
Actually we should probably add a statement along the lines of 'standard OS Install, that is, for a regular OS install without modification of normally supported / installed OS repositories'.

That should cover 'universe' in Ubuntu's case, but also people removing 'updates' or 'extras' in Redhat's case too, which some customers have done in the past.

**Comment by gtmanfred** [comment]
makes sense to me :+1:

**Comment by dmurphy18** [comment]
@Ch3LL Can we add a general statement to repo.saltstack.com with similar verbiage as outlined above, about a standard install ?

**Comment by dmurphy18** [comment]
@Ch3LL Possible additional sentence after initial sentence: _This page contains instructions to download and install the latest release of SaltStack._

**Assumes installing Salt on a platform with a standard OS install, that is, for a regular OS install without removal of normally installed / supported OS repositories: For example: _updates_ on Redhat, _universe_ on Ubuntu.**

All in favor of better / alternative wording of above .

**Comment by jf** [comment]
Just to be clear, universe is __not__ enabled by default on Ubuntu 18.04 a.k.a. Bionic. Otherwise, this sounds alright, and really should be the case. If you make modifications to a standard install, you should be prepared to deal with the repercussions.

**Comment by gtmanfred** [comment]
I just installed with the ubuntu server image, and i got this.

```
daniel@gttest:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
daniel@gttest:~$ grep '^[^#]' /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu bionic main restricted
deb-src http://archive.ubuntu.com/ubuntu bionic main restricted
deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted
deb-src http://archive.ubuntu.com/ubuntu bionic-updates main restricted
deb http://archive.ubuntu.com/ubuntu bionic universe
deb-src http://archive.ubuntu.com/ubuntu bionic universe
deb http://archive.ubuntu.com/ubuntu bionic-updates universe
deb-src http://archive.ubuntu.com/ubuntu bionic-updates universe
deb http://archive.ubuntu.com/ubuntu bionic multiverse
deb-src http://archive.ubuntu.com/ubuntu bionic multiverse
deb http://archive.ubuntu.com/ubuntu bionic-updates multiverse
deb-src http://archive.ubuntu.com/ubuntu bionic-updates multiverse
deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu bionic-security main restricted
deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
deb-src http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse
```

**Comment by gtmanfred** [comment]
And here is the etc/apt/sources.list from the root tarball form the cloud-images on ubuntu's website.

```
$ curl -LO https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64-root.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  138M  100  138M    0     0  2860k      0  0:00:49  0:00:49 --:--:-- 4994k
$ tar -xf bionic-server-cloudimg-amd64-root.tar.xz etc/apt/sources.list
$ grep '^[^#]' etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu/ bionic main restricted
deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
deb http://archive.ubuntu.com/ubuntu/ bionic universe
deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe
deb http://archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse
deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted
deb http://security.ubuntu.com/ubuntu/ bionic-security universe
deb http://security.ubuntu.com/ubuntu/ bionic-security multiverse
```

Which also has universe enabled.

**Comment by pcdummy** [comment]
I just did another install in a KVM Machine, no "multiverse" in /etc/apt/sources.list .

I did not install any other components than base system.

**Comment by jf** [comment]
> I just did another install in a KVM Machine, no "universe" in /etc/apt/sources.list .
>
> I did not install any other components than base system.

pretty much the same here! I didnt install any additional snaps. Again, see https://github.com/saltstack/salt/issues/48923#issuecomment-415976034

**Comment by dmurphy18** [comment]
@pcdummy @iffy @gtmanfred 
Have to believe that this is a bug introduced by Ubuntu 18.,04.1 since cannot believe that the other regular repositories have been removed without notice on Ubuntu, noting that others on the net asking the same questions about where is universe and multiverse gone to.

As a work-around, the repositories can be added by the following:
sudo add-apt-repository universe
sudo add-apt-repository multiverse
sudo add-apt-repository restricted

**Comment by dmurphy18** [comment]
Bug in Ubuntu describing this issue, https://bugs.launchpad.net/subiquity/+bug/1783129

Hence we should wait for Ubuntu's fix.  Note link contains work-around for 18.04.1 LTS

**Comment by dmurphy18** [comment]
Closing this since with Ubuntu 18.04.2 LTS universe appears to be there, install from AWS.

root@ip-10-200-22-11:/home/ubuntu# apt-get update
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/main Sources [258 kB]
Get:5 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/universe Sources [143 kB]  
Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [573 kB]        
Get:7 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [211 kB]         
Get:8 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [755 kB]      
Get:9 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [200 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                              
Get:11 http://security.ubuntu.com/ubuntu bionic-security/main Sources [78.2 kB]              
Get:12 http://security.ubuntu.com/ubuntu bionic-security/universe Sources [37.2 kB]
Get:13 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [296 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [106 kB]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [131 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [74.1 kB]
Fetched 3115 kB in 3s (1219 kB/s)          
Reading package lists... Done
root@ip-10-200-22-11:/home/ubuntu# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
