### ISSUE TITLE
Isolated fix for CVE-2017-7893? Which releases apart 2016.3.6 fix the issue?

### ISSUE THREAD

**Issue by carnil** [saltstack/salt#48939]
Hi

While going within Debian trough a couple of CVEs for salt noticed the CVE-2017-7893 mentioned in the https://docs.saltstack.com/en/2017.7/topics/releases/2016.3.6.html which credits Frank Spierings as the discoverer). 

In further research I only further found that in later releases the Credit mentioning was added, https://github.com/saltstack/salt/commit/24dea24b7e and https://github.com/saltstack/salt/commit/33c0644ac4 .

Unfortunately neither https://bugzilla.redhat.com/show_bug.cgi?id=1572139 or https://bugzilla.novell.com/show_bug.cgi?id=1090665 is helping identifying the fix.

Can you share the fix which would neet to be cherry-picked (and/or which releases contain the fix)?

**Comment by gtmanfred** [comment]
The fix should be just the second part of this 

https://github.com/saltstack/salt/commit/0a0f46fb1478be5eb2f90882a90390cb35ec43cb

We ended up turning this behavior back off by default though, in https://github.com/saltstack/salt/pull/40206

**Comment by anarcat** [comment]
> We ended up turning this behavior back off by default though, in #40206

... why?

**Comment by gtmanfred** [comment]
i don't remember @cro do you?

**Comment by anarcat** [comment]
and why should we consider CVE-2017-7893 fixed if the protection is disabled?

**Comment by anarcat** [comment]
ping? I'm trying to figure out how to backport those fixes into Debian for security updates, and it's not clear at all what the proper course of action is, or if this is even fixed in current stable releases.

Thanks for any update.

**Comment by cro** [comment]
@anarcat, sorry, I was on vacation for a couple of days.

> > We ended up turning this behavior back off by default though, in #40206

> ... why?

We turned `sign_pub_messages` back off by default because it broke compatibility with older masters (#40203).  We don't guarantee compatibility between newer minions and older masters, but we strive for it since sometimes folks upgrade their minions by accident and it's painful to recover when they won't talk to the current masters.

CVE-2017-7893 is fixed by the code in [this PR](https://github.com/saltstack/salt/pull/40159).  The best mitigation scenario is when `sign_pub_messages` is turned on.  The behavior is documented in the master configuration file here: https://github.com/saltstack/salt/blob/develop/conf/master

**Comment by anarcat** [comment]
So the upgrade path for users is to apply the patch, then simultaneously turn on `sign_pub_messages` at once, is that right?

**Comment by cro** [comment]
Yes, provided they don't have older masters that would be bitten by #40203.

**Comment by anarcat** [comment]
thanks. i have determined this cannot be fixed in the jessie version anyways (2014.1.13) as it doesn't have master signing in the first place, so I've skipped that issue, for what that's worth. hopefully a fix can be deployed in stretch (2016.11.2) nevertheless.
