### ISSUE TITLE
Proxy minion is not reconnecting session

### ISSUE THREAD

**Issue by jpvis** [saltstack/salt#48965]
I'm using
`proxy_keep_alive: False`
`proxy_always_alive: False`
 in proxy config file.

When I'm command net.facts I'm getting: 
```salt test_csr net.facts
test_csr:
    ----------
    comment:
        Cannot execute "get_facts" on 1.1.1.1 as cisco. Reason: Socket is closed!
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 167, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/lib/python2.7/site-packages/napalm/ios/ios.py", line 928, in get_facts
            show_ver = self._send_command('show version')
          File "/usr/lib/python2.7/site-packages/napalm/ios/ios.py", line 156, in _send_command
            raise ConnectionClosedException(str(e))
        ConnectionClosedException: Socket is closed
```
Same problem with other commands like : net.mac net.cli and etc. 
Tried with `always_alive: true` in pillar file - same problem.
 
However net.load_config works fine.

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by gtmanfred** [comment]
@mirceaulinic can you help troubleshoot this?

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
Yep, this is a bug. Please assign it to me and I'll look into it once we finish with the Fluorine features.

**Comment by mirceaulinic** [comment]
However:

> Tried with always_alive: true in pillar file - same problem.

This shouldn't be the case, there are many people using this and it should behave correctly (unless this is another thing affected by the issues with the scheduling system on 2018.3, which probably is).

**Comment by jpvis** [comment]
Strange I found this option in your provided link - 
![image](https://user-images.githubusercontent.com/38690054/43816505-cab35be6-9add-11e8-9046-e17a3a2c34b0.png)

Furthermore this option exists in /etc/salt/proxy file.

**Comment by mirceaulinic** [comment]
I agree. In Salt there's a mechanism for that already, which works in the way you described for Junos (and probably others) which throws this `ConnectionClosedException` - see https://github.com/saltstack/salt/blob/develop/salt/utils/napalm.py#L191

Unfortunately the NAPALM driver for IOS doesn't have that, which is why I would suggest you raise a feature request or submit a PR to add it: https://github.com/napalm-automation/napalm

**Comment by gtcat** [comment]
I get the following error after the ssh session from the proxy minion to the Cisco switch has been closed. I can reproduce this by clearing the ssh session on the Cisco device.

[root@saltgery ~]# salt 'tankstelle_1-port1-dev' net.cli "show version" 
tankstelle_1-port1-dev:
    ----------
    comment:
        Cannot execute "cli" on 10.82.12.6 as admin. Reason: Socket is closed!
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/usr/lib/python3.4/site-packages/napalm/ios/ios.py", line 165, in _send_command
            output = self.device.send_command(command)
          File "/usr/lib/python3.4/site-packages/netmiko/base_connection.py", line 1139, in send_command
            prompt = self.find_prompt(delay_factor=delay_factor)
          File "/usr/lib/python3.4/site-packages/netmiko/base_connection.py", line 972, in find_prompt
            self.write_channel(self.RETURN)
          File "/usr/lib/python3.4/site-packages/netmiko/base_connection.py", line 360, in write_channel
            self._write_channel(out_data)
          File "/usr/lib/python3.4/site-packages/netmiko/base_connection.py", line 331, in _write_channel
            self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
          File "/usr/lib/python3.4/site-packages/paramiko/channel.py", line 846, in sendall
            sent = self.send(s)
          File "/usr/lib/python3.4/site-packages/paramiko/channel.py", line 801, in send
            return self._send(s, m)
          File "/usr/lib/python3.4/site-packages/paramiko/channel.py", line 1180, in _send
            raise socket.error("Socket is closed")
        OSError: Socket is closed
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/lib/python3.4/site-packages/salt/utils/napalm.py", line 167, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/lib/python3.4/site-packages/napalm/ios/ios.py", line 1726, in cli
            output = self._send_command(command)
          File "/usr/lib/python3.4/site-packages/napalm/ios/ios.py", line 168, in _send_command
            raise ConnectionClosedException(str(e))
        napalm.base.exceptions.ConnectionClosedException: Socket is closed

Below some further information and the workaround with restarting the proxy minion.
Do I hit the same problem that is described in this issue?

--- Info Outputs ---	
[root@saltgery ~]# systemctl status *tankstelle_1-port1-dev*
● salt-proxy@tankstelle_1-port1-dev.service - salt-proxy service for tankstelle_1-port1-dev
   Loaded: loaded (/usr/lib/systemd/system/salt-proxy@.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-10-30 14:13:49 CET; 2h 28min ago
     Docs: man:salt-proxy(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 19105 (salt-proxy)
   CGroup: /system.slice/system-salt\x2dproxy.slice/salt-proxy@tankstelle_1-port1-dev.service
           ├─19105 /usr/bin/python3.4 -s /usr/bin/salt-proxy --proxyid=tankstelle_1-port1-dev
           └─19108 /usr/bin/python3.4 -s /usr/bin/salt-proxy --proxyid=tankstelle_1-port1-dev

Oct 30 16:42:04 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
Oct 30 16:42:05 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
Oct 30 16:42:06 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
Oct 30 16:42:07 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
Oct 30 16:42:08 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
Oct 30 16:42:09 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
Oct 30 16:42:10 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
Oct 30 16:42:11 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
Oct 30 16:42:12 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
Oct 30 16:42:13 saltgery.localdomain salt-proxy[19105]: [ERROR   ] Exception argument of type 'bool' is not iterable occurred in scheduled job
		
[root@saltgery ~]# cat /usr/lib/systemd/system/salt-proxy@.service
[Unit]
Description=salt-proxy service for %i
Documentation=man:salt-proxy(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltstack.com/en/latest/contents.html
After=network.target

[Service]
ExecStart=/usr/bin/salt-proxy --proxyid=%i
Type=simple
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target

[root@saltgery ~]# salt --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.9 (default, Aug 14 2018, 21:28:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
		
[root@saltgery ~]# pip3.4 list
Package           Version   
----------------- ----------
asn1crypto        0.24.0    
backports-abc     0.5       
bcrypt            3.1.4     
certifi           2018.10.15
cffi              1.11.5    
chardet           3.0.4     
cryptography      2.3.1     
future            0.16.0    
idna              2.7       
Jinja2            2.8       
junos-eznc        2.2.0     
lxml              4.2.5     
MarkupSafe        0.23      
msgpack-python    0.5.6     
napalm            2.3.3     
napalm-logs       0.7.0     
ncclient          0.6.3     
netaddr           0.7.19    
netmiko           2.3.0     
paramiko          2.4.2     
pip               18.1      
prometheus-client 0.4.2     
psutil            2.2.1     
pyasn1            0.4.4     
pycparser         2.19      
pycrypto          2.6.1     
pycurl            7.43.0    
pyeapi            0.8.2     
pyIOSXR           0.53      
PyNaCl            1.3.0     
pynxos            0.0.3     
pyserial          3.4       
PyYAML            3.11      
pyzmq             15.3.0    
requests          2.19.1    
salt              2018.3.2  
scp               0.12.1    
selectors2        2.0.1     
setuptools        40.4.3    
six               1.11.0    
textfsm           0.4.1     
tornado           4.4.2     
u-msgpack-python  2.5.0     
urllib3           1.23     

--- Workaround ---
[root@saltgery ~]# systemctl restart *tankstelle_1-port1-dev*
[root@saltgery ~]# salt 'tankstelle_1-port1-dev' net.cli "show version"
tankstelle_1-port1-dev:
    ----------
    comment:
    out:
        ----------
        show version:
            Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(2)E6, RELEASE SOFTWARE (fc1)
            Technical Support: http://www.cisco.com/techsupport
            Copyright (c) 1986-2016 by Cisco Systems, Inc.
            Compiled Fri 16-Dec-16 21:27 by prod_rel_team
            
            ROM: Bootstrap program is C2960X boot loader
            BOOTLDR: C2960X Boot Loader (C2960X-HBOOT-M) Version 15.2(2r)E1, RELEASE SOFTWARE (fc1)
            
            tankstelle_1-port1-dev uptime is 4 days, 1 hour, 2 minutes
            System returned to ROM by power-on
            System restarted at 18:39:44 MEST Fri Oct 26 2018
            System image file is "flash:/c2960x-universalk9-mz.152-2.E6/c2960x-universalk9-mz.152-2.E6.bin"
            Last reload reason: Reload command
            
            
            
            This product contains cryptographic features and is subject to United
            States and local country laws governing import, export, transfer and
            use. Delivery of Cisco cryptographic products does not imply
            third-party authority to import, export, distribute or use encryption.
            Importers, exporters, distributors and users are responsible for
            compliance with U.S. and local country laws. By using this product you
            agree to comply with applicable laws and regulations. If you are unable
            to comply with U.S. and local laws, return this product immediately.
            
            A summary of U.S. laws governing Cisco cryptographic products may be found at:
            http://www.cisco.com/wwl/export/crypto/tool/stqrg.html
            
            If you require further assistance please contact us by sending email to
            export@cisco.com.
            
            cisco WS-C2960X-24PS-L (APM86XXX) processor (revision F0) with 524288K bytes of memory.
            Processor board ID FCW1917B0U6
            Last reset from power-on
            1 Virtual Ethernet interface
            1 FastEthernet interface
            28 Gigabit Ethernet interfaces
            The password-recovery mechanism is disabled.
            
            512K bytes of flash-simulated non-volatile configuration memory.
            Base ethernet MAC Address       : F0:78:16:67:48:80
            Motherboard assembly number     : 73-15972-02
            Power supply part number        : 341-0528-01
            Motherboard serial number       : FOC19152DSY
            Power supply serial number      : DCB191170YY
            Model revision number           : F0
            Motherboard revision number     : C0
            Model number                    : WS-C2960X-24PS-L
            Daughterboard assembly number   : 73-14200-03
            Daughterboard serial number     : FOC191604KK
            System serial number            : FCW1917B0U6
            Top Assembly Part Number        : 800-41469-01
            Top Assembly Revision Number    : C0
            Version ID                      : V02
            CLEI Code Number                : CMMLR00ARB
            Daughterboard revision number   : A0
            Hardware Board Revision Number  : 0x12
            
            
            Switch Ports Model                     SW Version            SW Image                 
            ------ ----- -----                     ----------            ----------               
            *    1 28    WS-C2960X-24PS-L          15.2(2)E6             C2960X-UNIVERSALK9-M     
            
            
            Configuration register is 0xF
    result:
        True

**Comment by mirceaulinic** [comment]
@gtcat I think in your case it's the reconnect scheduler that is not working due to a bug. Please upgrade to 2018.3.3 and normally this should work fine (i.e., should reconnect when the Minion detects that the connection has been dropped).
Note however, that on IOS, as mentioned above, you may hit a interval between the moment the connection is dropped and the Minions re-establishes it, when the commands fail, as stated above. But overall, in 2018.3.3 this should be much improved.

**Comment by gtcat** [comment]
@mirceaulinic Thank you for the quick answer. I just updated to 2018.3.3. It now recovers itself after the session has been closed. This takes about 40 seconds. But like you said during the recovery the ` OSError: Socket is closed` still appears.
Will this be fixed as well? Can I improve that by increasing the ssh timout on the Cisco device?
