### ISSUE TITLE
integrate salt-cloud into salt instead of a separate project

### ISSUE THREAD

**Issue by ptitdoc** [saltstack/salt#49208]
### Description of Issue/Question
Salt cloud is currently implemented as a specific runner with different drivers depending on the cloud provider. This runner is masterless and creates a separate codebase and concepts (maps and configuration instead of pillars, drivers instead of modules,  ...) while trying to share part of the code (esxi, vsphere, vmware ...).

Why isn't salt-cloud more integrated into the salt project. For instance I started working on the following proof of concept:
- a state module called cloud implements cloud.vmpresent, cloud.vmrunning, cloud.vmsetup ...
- this state module for my proof of concept only works for vsphere_over_ssh but can be made as an abstraction such as the pkg state module
- a module called cloud also implements update_vm_settings, start_vm, register_vm, clone_vm, copy_vm, vm_exists, list_vms...
- a proxy minion esxi_ssh implements the 'run' function

Generic usage of such a cloud can use existing salt features:
- the salt proxy minion `mycloud` acts as a cloud manager
- user can define cloud maps into the pillar for the minion `mycloud`
- user can create a vm using `salt mycloud cloud.vmpresent myvmname` and parameters will be taken from the cloud map (from the pillar)
- user can create a .sls file to deploy automatically multiple VMs based on the defined pillar as `salt-cloud -m` already does
- eventing system and/or orchestration can be used to chain deployment (clonevm, then setup vm parameters, then startup, then wait for VM to be up and get network, then deploy salt minion)
- can continue cloud deployment in case of failure (because state modules are used) for instance, if a vm has been properly cloned but failed to startup, it will cloud.vmpresent will success without changes and cloud.vmrunning will try to start the VM again.
- works out of the box with cloud proxy minions as it is a now a requirement (instead of using drivers)

**Comment by gtmanfred** [comment]
Ok, so here is what the current plan is.

Right now, leave salt-cloud as is.  It was designed back before all this extra functionality in clouds existed, when you could only build cloud servers, and there was no kubernetes, and no DBaaS, etc.

The plan is to take all of the execution and state modules like boto_ and azurearm_ and move them to a new project, so that they can be released more rapidly than salt, when new products are released.  And then we don't have to build all this extra stuff to make all the cloud providers the same, because they aren't...  Instead the only thing that would be the same between each cloud provider in salt is that they need to provide a function that returns all the information needed to bootstrap a server using `salt.utils.cloud.bootstrap()`.  Then the minion that is building and bootstrapping the cloud server will need to pass the minions key to the master on the message bus, and the master will accept that minions key.  Allowing a full bootstrapping of the process.

This will allow salt-cloud v2 to be a seperate project like terraform, that is idempotent and can build all of these different projects without tearing stuff down like terraform does, but would also allow it to be integrated back into salt if it was to be used with the regular state system.

Here is a working proof of concept.  https://github.com/gtmanfred/fractus

**Comment by gtmanfred** [comment]
The problem with your proposal is that it is already difficult enough to make these drivers use the same interface, when we only want to build cloud servers, it is going to be impossible if we want to handle all the options for load balancers, and autoscaling groups, and the different kubernetes as a service implementation, and database as a service implementations.

And there is no reason for them to be the same, they never interact with each other.

If we just make sure that they can interact with the ones that are the same, like the boto modules should be able to be used together, i don't need to use a google rds with an amazon ec2 instance.

**Comment by ptitdoc** [comment]
Thanks for your quick answer.

Of course normalizing names is not mandatory as there are completely different cloud concepts. I compared it to the pkg module on purpose because only some of the function are normalized, which allows calling specific package management function depending on the user requirements.

The best benefit is see is to be able to use states modules, pillar, reactors and orchestration to deploy cloud instead of a specific runner that re-implement all these things. Such a project can also be implemented as a salt-formula project using _states, _modules ...

**Comment by ptitdoc** [comment]
I will definitively take a look at fractus. I see there are cloudstates and cloudmodules. Wow, is there really already 17k commits ?

**Comment by gtmanfred** [comment]
No, i did a git filter-branch, and just pulled all the git history for the boto_ and azurearm modules out of salt, so a lot of the commits are from those things, and stuff that couldn't be filtered from the salt branch.

**Comment by ptitdoc** [comment]
Ah ok.

**Comment by gtmanfred** [comment]
So, the problem with the pkg module idea, is that we do normalize the behavior across all the different package managers so that they can all be controlled by one central package module.

Well, what happens when you have 2 different cloud providers that you use?  You don't want to only load one of them, you want to be able to use them all.  With pkg modules, you only need one loaded, the one for your distribution/os.

The fractus stuff allows you all of the flexibility of salt, if installed, it can be used in salt through the pkg_resources part of the salt loader, and it can also be used independently of a salt run, because it has it's own state runner.

https://github.com/gtmanfred/fractus/blob/develop/setup.py#L16

And here is the state runner in fractus.

https://github.com/gtmanfred/fractus/blob/develop/fractus/state.py#L17

It actually just uses salts state system, but just modifies which modules are loaded, so when you just want to load the states for your cloud provider, you don't load all the extra salt stuff, like mount or yumpkg.

**Comment by gtmanfred** [comment]
And it has its own test suite, which is mostly just the boto module tests pulled out and modified to run in pytest, but it tests most of the same things, i have a little work to do on the integration tests.

**Comment by gtmanfred** [comment]
It definitely isn't ready yet for people to start contributing to, but once Fluorine is out, I am hoping to have time to work on it again.  and get it read for a lot of community contributions.

**Comment by ptitdoc** [comment]
In my use case I have at least 2 cloud providers. I would just use a separate proxy minion for each cloud and make them working together through reactors or orchestration. To follow the pkg example, each minion loads its own variant of pkg (or cloud in our case).

So if I understand correctly running fractus cause a creation of a minimal standalone salt-master? using the vanilla salt state/module engine. This looks clean.

Is it daemonized and/or uses salt-master bus so that I will be able in the future to use salt-api or salt reactors on cloud modules events ?

**Comment by ptitdoc** [comment]
Even if it is not ready for contribution, I would be interested to see if I can use it for my vcenter-proxy and vsphere-ssh clouds, because salt-cloud in its current state does not seems to support that anyway.

**Comment by ptitdoc** [comment]
Thanks a lot for your time anyway. Can I come back to this issue if I have additional questions ?

**Comment by gtmanfred** [comment]
yeah, it will need vsphere/vmware modules for, and you should discuss this with @nmadhok , since he has been waiting to contribute vmware stuff to this idea as well for about a year now.

As for your last question, fractus is just a commandline tool, for bootstrapping clouds, you can still use all of those modules in regular salt, and they will need configs, so you can designate minions to reach out and talk to whatever cloud you want using the cloud states and modules in fractus.

**Comment by gtmanfred** [comment]
Sure, you can also come to the #cloud channel on the community slack listed in the README for salt, and we can talk about it there.

I am going to close this issue though.
