### ISSUE TITLE
Snotty people on #salt IRC channel

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#49765]
### Description of Issue/Question
Don't understand the attitudes of the people on IRC

### Setup
I am deploying windows machines. The deployment system auto installs salt with the correct salt ID's (that's pretty neat but I won't go into details). The salt ID's are partially based on a date stamp and remain permanent for the life of the PC. They are effectively the _true_ names of the PC's.

The deployed machines are not set up to automatically domain join. Partly because the Windows computer names names are somewhat in flux. Partly because my boss and co-workers don't want our credentials stored anywhere

To domain join I create an sls file which can be invoke by the sysamin. The runner will ask for a user name and password and pass that as pillar data. The intended computer names come out of an external pillar (stored in a postgresql db). The runner then just applies the state and the PC's join with their intended names.

I've been testing this today and it's working well, but people on the #salt irc channel were giving me flak and insinuating that I'm an idiot. BTW i don't care if i am an idiot. I just want to know why anything I'm doing is worse than anything anyone else does.

I have asked #windows people: "how do you join 100 machines?". This is the conversation
```
 hi
<hrumph_> what's the typical method for joining say 100 computers at once?
* BrainWork has quit (Ping timeout: 244 seconds)
<S_SubZero> joining?
<hrumph_> domain joining
<hrumph_> sasy they're not joined to any domain
<S_SubZero> do you have a mechanism to push software and or scripts to said 100 machines?
<hrumph_> is there a way to avoid going aroudn to each computer and joining?
<hrumph_> S_SubZero, yes but i'm wondering what other people do
<S_SubZero> their version of that thing you have
* adapter (~adapter@c-71-227-131-190.hsd1.wa.comcast.net) has joined
<naphtali> You could script it with PowerShell. hrumph, typically a place with 100 PCs would use MDT/WDS with domain join as part of the deployment
<naphtali> Even with the script someone is going to have to touch them to get admin rights
```

So there you have it, the typical process involves someone ineracting with 100 machines. I avoid all that. Why am I being criticised?

Edit: I should also add that if people believe in the vision of management offered by salt they should be encouraging the extension of salt's usage in every direction.

**Comment by cachedout** [comment]
Hi @hrumph. I lead the core maintainers team at Salt.

I'm sorry you felt criticized. In the morning, I'll ask somebody on @saltstack/team-windows to try to help you with your question specifically.

I do want to respond, however, to your comment about the "vision of management" of Salt to "extend in every direction". 

As the principal maintainer of this project, my view is one of great pride that people in our community are trying to offer what they may see as the best solution for a problem, regardless of whether or not that answer involves Salt. 

While I hope that we can always continue to grow the project to cover more ground, If another solution for a given problem is better than ours, I hope our community continues to have the integrity to heartily recommend it over Salt in the interest of being as helpful as possible instead of merely dogmatic.

That said, I hope you'll keep using Salt and, as I said, I'll make sure the Windows folks get in touch with you in the morning to see if there's a way that Salt can be made to work in a way that solves the problem you're concerned with.

Best,

-Mike

**Comment by hrumph** [comment]
@cachedout I don't need any help specifically. All of the specific technical problems I was having are resolved. My first question was "how could this be done better _without_ salt", since people were implying that it could. I couldn't think of any solution that would be substantially simpler in terms of number of operations.

I'll forget about the scond point I was making for the time being.

**Comment by damon-atkins** [comment]
> but people on the #salt irc channel were giving me flak and insinuating that I'm an idiot. BTW i don't care if i am an idiot. I just want to know why anything I'm doing is worse than anything anyone else does.

I assume above is the main point of this issue.

There is a slack channel for windows help. Slack keeps a few days worth of history, so if people are not constructive in their comments  its more noticeable. (Invite sent to you email address)

**Comment by hrumph** [comment]
I'm sorry about this. Anyway I've come up with a much better system thanks to some of the help I got on slack. Thanks to all the people who have helped me with suggestions so far.
