### ISSUE TITLE
Question/Feature proposal: running states from sls files specified as paths

### ISSUE THREAD

**Issue by DrPyser** [saltstack/salt#50010]
### Description of Issue/Question
This is a question/feature proposal(hope it's the right place)

One thing I'd really like to do in salt is to run/apply states from an sls file(as with `salt state.sls`) specified as a path to an arbitrary location on the local file system. That is, I'd like to be able to run state files not present under one of the configured `file_roots`. 

This would, for example, allow me to include sls files in an application's repository. Those sls files would define states to deploy the application. Then, deploying the application would simply involve pulling that repository, and running the appropriate salt command to apply those states, without having to copy/move those state files beforehand. I guess, being able to also specify paths to pillar files in the same command would also be useful. 

Maybe there's a way to do this already, or a way to do something similar(i.e. run salt commands from state-like files).

Thanks!

**Comment by gtmanfred** [comment]
you can do this with salt-call, on the minions in question, because salt-call starts up a whole minion process.

But the only way to do this would be to update the master config, and have the master reload the config, and look for files to server from there.

Based on the way the minion works and requests data, it can be completely asynchronous of the master issuing commands.  So if you did update this data, then any other minion that happened to be doing a checking for something else would end up with fileroots it wasn't expecting.

Also, we wouldn't be able to allow the minion to tell the master where on the filesystem it wanted to look for files, because then the minion could point anywhere, and we could potentially leak data, that needs to be secure about the master that controls all the minions in your environment.

I am going to open this up for @saltstack/team-core to disagree with me, but my opinion right now is this is just something that we won't want to implement, for security reasons.

Thanks for the request though.
Daniel

**Comment by DrPyser** [comment]
Right, I guess my use case is really for a masterless or agentless setup. Can you elaborate how to use `salt-call` on a minion to execute a state file by pointing to the path of the state file?

Thanks for your answer.

**Comment by DrPyser** [comment]
Thanks, that fit my use case pretty well.

**Comment by garethgreenaway** [comment]
@DrPyser This is closed and the suggested solution worked for you, but just to add another solution on the pile.  You can also use the `template` function in the `state` execution module.
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.template

**Comment by DrPyser** [comment]
This also perfectly fits my needs, thanks!

**Comment by DrPyser** [comment]
If i can suggest one thing(I can create a separate issue if you want), it would be great to be able to set pillar data on the command line with `state.template`(as with `state.sls`, for example), or even better to also be able to specify a path to a sls file to use directly as source for pillar data. I know I can use the `--pillar-root` flag to specify a local directory for pillars, but that forces me to write a `top.sls` file, which is unnecessary overhead for my use case.
