### ISSUE TITLE
Docker modules should use "latest" tag implicitly

### ISSUE THREAD

**Issue by thebluesnevrdie** [saltstack/salt#50032]
### Description of Issue/Question
From the docs:

> Changed in version 2018.3.0: If no tag is specified in the image name, and nothing matching the specified image is pulled on the minion, the docker pull that retrieves the image will pull all tags for the image. A tag of latest is no longer implicit for the pull. For this reason, it is recommended to specify the image in repo:tag notation.

I don't understand this default, because the new behavior:

1. Goes against the implicit behavior of the project tools Salt is managing (in this case Docker CLI tools)
1. When end users don't understand this, the effect will be to silently fill up the filesystem since many images can be several hundred megabytes each

IMHO, this is not a sane default.

### Setup
container.sls:

    container-test:
      docker_container.running:
        - image: busybox

### Steps to Reproduce Issue
salt-call state.apply container

### Versions Report
`>= 2018.3`

**Comment by Ch3LL** [comment]
ping @terminalmage looks like you added this doc. Can you answer @thebluesnevrdie 's concerns.

**Comment by terminalmage** [comment]
The simple answer here is that we stopped parsing the image name, since that is a recipe for disaster. There are multiple different formats used to specify tags, some of which include registry URLs (and some of _those_ include port numbers, in which case there will be a colon present that doesn't delimit the image name from the tag name).

So, what is passed as the image name is sent directly to docker-py, and docker-py's behavior for pulling when there is no explicit tag is to pull all tags.

I suppose we could look for the absence of a colon and assume `latest` in those cases, since the absence of a colon would mean that there is definitely no custom registry.

**Comment by terminalmage** [comment]
Of course, this wouldn't account for cases in which someone wants to pull from a custom registry that includes a port number, and does not specify a tag name.

**Comment by thebluesnevrdie** [comment]
@terminalmage Thanks for the insight. For the last case, could we add an argument to indicate the use of a custom registry with a custom port? `private_reg: True` or `registry_port: 5000`

**Comment by thebluesnevrdie** [comment]
Understood. So would an acceptable compromise be to require the tag? I don't think that the current behavior (when not specifying a tag) is ever something that would be desired, but if it was we could introduce a "meta tag" such as "all". If you agree we can simply require a tag, is it too late to get this into the Fluorine release?

**Comment by terminalmage** [comment]
@thebluesnevrdie we're already deep into the release-candidate process for Fluorine, and changes like this are not something we'd like to do in a point release.

However, there's no way for us to truly know if a tag is part of the image name passed to the state. We can look for the presence of a colon, but that wouldn't be foolproof, for example, when using a custom registry, you could have something like `myregistry.tld:5000/myimage` and that would be an image without a tag.
