### ISSUE TITLE
Salt Debugger with steppings feature request

### ISSUE THREAD

**Issue by mruepp** [saltstack/salt#50176]
### Description of Issue/Question

If we could get a debugger like salt option when issuing state.apply or similar, this would be awesome.

Something like salt * state.apply debug=true

with the options:
Option to write breakpoints into sls files
Option to step into and step out of states and functions
Option to see variables and rendered jinja on the side

Currently it is quite hard to debug salt in certain conditions. If pillars missing, jinja variables are empty, stuff like this.

I don´t think there is something like this available, right?

Thanks

**Comment by gtmanfred** [comment]
you will never be able to do that from `salt` because all of the work is done on the minion.

If you login to the minion, you can run `salt-call state.apply -l debug` and see all of your stuff.

You can also insert logging into the state files with the `log` module 

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.logmod.html

**Comment by mruepp** [comment]
You don´t think it would be possible to step through lowstate on the minion and return after every step to the master?

**Comment by gtmanfred** [comment]
it is possible, but it will require an almost full rewrite of how the localclient return system works, because we only return the full data at the end of the command being run.

Now, i could see this happening on the minion, with salt-call, it would still be a substantial change, but it wouldn't require reworking the entire way the event system returns work.
