### ISSUE TITLE
saltclass pillar not available to jinja

### ISSUE THREAD

**Issue by ReubenM** [saltstack/salt#50265]
/etc/salt/master
```
ext_pillar_first: True
```

saltclass/nodes/node1.yml
```
pillars:
  foo:
    - ^
    - bar
    - baz
```

pillar/top.sls
```
base:
  'I@foo':
    {%- for x in salt['pillar.get']('foo') %}
    - subdir.{{ x }}
    {%- endfor %}
```

The 'I@foo' pillar targeting works fine.
However, the pillar object made available to jinja when preprocessing the template is empty.

Salt: 2018.3.2
Python: 2.7.5

**Comment by rbthomp** [comment]
@ReubenM I believe you have to use ` {%- for x in salt['__pillars__.get']('foo') %}`

https://github.com/saltstack/salt/blob/033ce00ad0259fd286665b4a19740121cf247135/salt/tops/saltclass.py#L32

**Comment by rbthomp** [comment]
@ ReubenM are you trying to merge saltclass pillars and standard top style pillars? Both are completely different top and pillar generating systems. Maybe you can clarify on the use case for defining pillars for `foo` by saltclass and standard pillar top.sls.

**Comment by garethgreenaway** [comment]
@ReubenM Thanks for the report.
@saltstack/team-core Does anyone whose more familiar with saltclass have any ideas here?

**Comment by ReubenM** [comment]
@rbthomp:

Yes, I'm merging pillar from two sources. The first pass is from saltclass. The second pass using the pillar top sets additional pillar data based on the first pass. The pillar targeting within the pillar top file is working. However using pillar within the Jinja template processing does not. 

The real world use case for it is that I want to define roles using pillar, but I also want to assign pillar data based upon those roles. saltclass makes that possible. I have a large collection of nodes being used for perf testing, and their roles can change quite a bit. Modifying roles using grains on each minion is tedious and time consuming. Use pillar to define roles keeps role assignments all centralized to the master node.

I can do it entirely through pillar matching in the pillar top file instead of using jinja to iterate over sets, but it can make for an unwieldy pillar top file.

**Comment by rbthomp** [comment]
@ReubenM I'm using roles as your are to avoid setting grains on nodes, except I'm keeping everything within saltclass instead of merging. This way you don't have to maintain top files. You can just define role classes that contain the pillars you need. You can even include classes in classes. 

saltclass/nodes/node1.yml
```
classes:
  - role.role1
  - role.role2
```
saltclass/classes/role/role1.yml
```
pillars:
  role1:
    - ^
    - bar
    - baz
```
saltclass/classes/role/role2.yml
Classes can also include other classes.
```
classes:
  - apps.apache
  - apps.ntp

pillars:
  role2:
    - ^
    - bar
    - baz
```
These were some recent features added in 2018.3.3 that allow you to do Linux shell style globing for files. For example you want every class.yml in `saltclass/classes/role/role1/`

https://github.com/saltstack/salt/blob/b4a29d73c17a5bba16a3c7b31adfa2ca3236ec9f/salt/utils/saltclass.py#L233
```
classes: 
  - role.role1.*
```

Hope this helps.

**Comment by ReubenM** [comment]
@rbthomp 

Fun part for me is that no two nodes share the same role. Roles in my case are large dictionary trees. Nodes may share common branches of the roles tree, (which is what I was matching against in the pillar top files) but none share the same tree which make classes a bit cumbersome. Plus the pillar top files allowed to keep stuff segregated by environment.

I'll do some experiments and see if I can make something work using just saltclass that isn't more trouble that it's worth.
