### ISSUE TITLE
It's impossible to restart salt-minion from the master on MacOS minions

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#50422]
### Description of Issue/Question
A command like `salt MINION service.restart salt-minion` works fine on Linux, Windows, and even Solaris. But on MacOS, it just kills the service. There's no apparent workaround either, because any process (including a local script that would start the service) started by the minion dies with the main process when it restarts, killing any would-be restart commands anywhere.

Also, I can't use `at` because every attempt for any command in the `at` module just results in a dump and a `list index out of range` error from the minion.

**Comment by weswhet** [comment]
Looks like service.restart on macOS does a stop/start. Which is an issue because when it the stops the service, it kills the process thats running the command so its unable to start it again. Looks like we should be able to change this to run `launchctl kickstart -k system/com.saltstack.salt.minion` and we should be good to go.

**Comment by ThisGuyCodes** [comment]
bump.

Seems like the fix for this is already known (to the point that people are doing it themselves.
