### ISSUE TITLE
provide a mechanism for enforcing a timeout for salt commands to complete

### ISSUE THREAD

**Issue by netllama** [saltstack/salt#5054]
It would be useful if there was a way to enforce a timeout period for any salt command, such that if any minion didn't respond or complete the command requested after X seconds, the command would give up (and cancel/cleanup what internal book keeping it had going on).  

I'm hoping to use salt for as a monitoring tool (amongst other purposes), and I need a means of ensuring that the monitoring is going to run to completion at a specific time interval.  Along these lines, I'd like to be able to specify a timeout which would be enforced on each minion.  That way, if I ran a command (without any batching), and specified an X second timeout, i'd be reasonably confident that the entire command invocation from the master would exit within those X seconds.

Detailed discussion of this topic is here:
https://groups.google.com/forum/?fromgroups=#!topic/salt-users/pjgF_vLH3-o

**Comment by sjmh** [comment]
As an aside, we do this via a custom runner wrapper.  In essence, we execute the runner and provide it the command and arguments we want to run.  The runner takes care of executing the job async and then waits on the job return for a certain amount of time.

If that job return fails to show up, it then executes a kill_job on the job id and returns an error that the job timed out.

We do this for both runners and exec modules - although in the case of the runner jobs, it should be noted that you can't use the kill job functionality, since the job id you are given isn't a real 'jid', for the purposes of actually killing it - but it does work for any exec commands you're trying to run on minions.

It's not the best way of doing this - but it's a workaround we've had a bit of success with.

**Comment by nw0428** [comment]
This feature would be really nice!

**Comment by dsteele0301** [comment]
I would still like to see this feature implemented. I have seen no indication that it exists yet other than for the `cmd.run timeout=x` argument. I'm not sure if this same argument is available for other modules besides `cmd`. Example:

`salt test_minion cmd.run 'sleep 45' timeout=5`
`
test_minion:
    sleep 45 : Timed out after 5 seconds
`

As @netllama mentioned in the use case, I occasionally have minions that are in bad states/hung but will still respond to salt commands continue to run jobs while the master will wait seemingly indefinitely for that one minion to return. 
I know there are workarounds to this (async, wrapper scripts, etc), but I would hope a global hard timeout could be set configured at some point. 

Here's to hoping that this comment makes this issue no longer stale.
