### ISSUE TITLE
 APIs for Salt Minion-Masterless

### ISSUE THREAD

**Issue by kamuops** [saltstack/salt#50665]
### Description of Issue/Question
I want to access the Masterless Salt Minion (Only for Windows) to execute some local commands, is there any APIs available for this. What is the default port for SALT Minion

**Comment by dwoz** [comment]
@kamuops Generally when we talk about running salt in 'masterless' mode. We're referring to using salt-call to apply state to the box. To do this remotely you'll probably want to use WinRM. Our enterprise offering also adds support for WinRM to salt-ssh. Otherwise if you want to manage the box remotely using salt it might be worth spinning up a master.

**Comment by kamuops** [comment]
@dwoz : Considering security measures , we are not supposed to enable WinRM on Desktop machines. Is there any other way to achieve this. Thanks in advance.

**Comment by kamuops** [comment]
@mikeadamz : Appreciate your clear explanation.  i am completely new to salt and exploring the options for masterless minion. We have our master server , our problem statement is to call salt-minion via Microsoft Teams(We have a chat bot). Whenever the user is facing some issues, they can select the appropriate options and the chat bot will Call the user's salt-minion for executing that command.  I think our task is not achievable by directly calling the salt-minion from MS Teams. Any way to acheive this?

**Comment by mikeadamz** [comment]
There is an api you can use to connect from teams to the salt master to remotely execute commands on the minion.

**Comment by kamuops** [comment]
@mikeadamz  If I connect Salt Rest-API from Ms teams, how salt with recognize the hostname/minion-id of the user's machine.
