### ISSUE TITLE
How to use external pillar and get all pillars from master?

### ISSUE THREAD

**Issue by dmytro-shevchenko** [saltstack/salt#51077]
Hi folks!

I need run orchestration from master as well as apply some states, but during this operation I need access to all minions pillars. I'm trying to accomplish this with external pillar - it will responsible for gathering and filtering all pillars from each minion. 
But unfortunately seems while external pillar executing on master it completely blocking any other requests to master via API. Maybe this is recursion or just deadlock? Here is the sample:

```python
import salt.client

def ext_pillar(minion_id, pillar, *args, **kwargs):
  local = salt.client.LocalClient()
  minions = __salt__['minion.list']()['minions']  # <-- this working good
  for minion in minions:
    data = local.cmd(minion, 'pillar.items', timeout=10)  # <-- this blocking salt master and return None after timeout
  # ....

```

Question is how I can get pillars for particular minion inside external pillar? (like: `salt <minion> pillar.items`)

Salt Version: 2017.7.3

**Comment by Ch3LL** [comment]
ping @saltstack/team-core any ideas here on how @dmytro-shevchenko can accomplish this?

**Comment by waynew** [comment]
Hi @dmytro-shevchenko, thanks for reaching out! I might be able to help if I understand more about what it is that you're trying to accomplish.

You've definitely explained _how_ you're trying to get it done, I just don't think I understand your _why_ enough to be able to give some good advice 🙂

**Comment by dmytro-shevchenko** [comment]
Hi @waynew, thanks for your help. 

The main idea is next: I have a set of minions, lets call them 'customers'. It is quite important isolate their data/pillars from each other. And another set of minions, lets call them 'service' minions - they should know about 'customers' and have access to customers pillars (at least to some part of pillar data). How I can accomplish this with best practice? 
I don't want to put any information about customers to service pillar data, because here is a lot of 'service' minions and information about single entity (customer) become spreded across multiple places in code.

**Comment by waynew** [comment]
Hey @dmytro-shevchenko thanks for the update!

I could be misunderstanding, but it _sounds_ like what you might want to do is just provide the service(s) with the customer pillars that they should have access to.

A simple example (apologies if this doesn't precisely match your goals):

**/srv/pillar/top.sls**

```
base:
  'role:Service1':
     - match: grain
     - customer_data1_1
     - customer_data1_2
     - customer_data1_3
  'role:Service2':
    - match: grain
    - customer_data2_1
    - customer_data2_2
```

With this approach you can use grains to toggle which minions get access to specific pillars. Rather than using `match: grain`, of course, you could just use the minion name (or other matching) to specify the groups of "services" that should have "customer" data.

Does that approach make sense 🙂 ? Am I right on? Or am I missing something and just sound crazy :trollface:?
