### ISSUE TITLE
Py3 should prefer venv module to virtualenv binary

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#51742]
In Python 3 the `virtualenv` script was replaced by `pyvenv`, and then in 3.6 deprecated in favour of the builtin `venv` module.

The latter should be preferred, but at minimum `pyvenv` should be added to `virtualenv_mod.KNOWN_BINARY_NAMES`.

**Comment by OrangeDog** [comment]
Additionally, despite what the documentation says (for 2018.3.3) it's not possible to globally override.
The code (snippets below) is arranged such that the pillar is never consulted.
```
__opts__ = {
    'venv_bin': salt.utils.path.which_bin(KNOWN_BINARY_NAMES) or 'virtualenv'
}
```
```
if venv_bin is None:
    venv_bin = __opts__.get('venv_bin') or __pillar__.get('venv_bin')
```

**Comment by Ch3LL** [comment]
looks like you are working on a commit for this. would you mind pushing as PR? thanks!

**Comment by OrangeDog** [comment]
@Ch3LL I've done the easy bit. I'm not planning to rewrite it to `import venv`.
I'm also not sure how/whether it can still be set via minion config, or whether someone wants to put that in.

**Comment by OrangeDog** [comment]
The partial fix is still awaiting a merge into master, but as previously mentioned there may also be further improvements.

I'm not sure on the details, but it looks like `virtualenv` may shortly have a big rewrite landing. That may affect what's best to use.

**Comment by OrangeDog** [comment]
N.B. the `pyvenv` script has also been removed as of 3.8.

**Comment by DaAwesomeP** [comment]
It does not seem possible to use `venv` with salt currently (at least on Debian 11 through my testing). There is no `venv` or `pyvenv` available in the shell. You have to run `python3 -m venv` (or `python3.9 -m venv` for Python 3.9) to access it.

However the `venv_bin` options seems to be looking for an executable, not a Python global script. Setting it to `venv` does not work. Setting it to `/usr/lib/python3.9/venv/__main__.py` does not work either since that is not an executable file. Setting it to `/usr/bin/python3 -m venv` does not work either.

**Comment by OrangeDog** [comment]
@DaAwesomeP indeed. You can create `/usr/local/bin/pyvenv` as a workaround for newer pythons:
```sh
#!/bin/sh
python3 -m venv "$@"
