### ISSUE TITLE
salt-latest won't install on RHEL7.5

### ISSUE THREAD

**Issue by tganzeboom** [saltstack/salt#51829]
### Description of Issue/Question
yum install salt-minion does not work with the latest (2019.2 as of this writing.)
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
N.A. 
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
yum install salt-minion
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:2019.2.0-1.el7 will be installed
--> Processing Dependency: salt = 2019.2.0-1.el7 for package: salt-minion-2019.2.0-1.el7.noarch
--> Running transaction check
---> Package salt.noarch 0:2019.2.0-1.el7 will be installed
--> Processing Dependency: python-tornado < 6.0 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python2-futures >= 2.0 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-tornado >= 4.2.1 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-requests >= 1.0.0 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-msgpack >= 0.4 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-crypto >= 2.6.1 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: yum-utils for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: systemd-python for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-zmq for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-psutil for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-markupsafe for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-jinja2 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: PyYAML for package: salt-2019.2.0-1.el7.noarch
--> Running transaction check
---> Package PyYAML.x86_64 0:3.11-1.el7 will be installed
--> Processing Dependency: libyaml-0.so.2()(64bit) for package: PyYAML-3.11-1.el7.x86_64
---> Package python-crypto.x86_64 0:2.6.1-2.el7 will be installed
---> Package python-jinja2.noarch 0:2.7.2-2.el7 will be installed
--> Processing Dependency: python-babel >= 0.8 for package: python-jinja2-2.7.2-2.el7.noarch
---> Package python-markupsafe.x86_64 0:0.11-10.el7 will be installed
---> Package python-msgpack.x86_64 0:0.4.6-1.el7 will be installed
---> Package python-psutil.x86_64 0:2.2.1-1.el7 will be installed
---> Package python-requests.noarch 0:2.6.0-1.el7_1 will be installed
--> Processing Dependency: python-chardet >= 2.2.1-1 for package: python-requests-2.6.0-1.el7_1.noarch
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-1.el7_1.noarch
---> Package python-tornado.x86_64 0:4.2.1-1.el7 will be installed
--> Processing Dependency: python-backports-ssl_match_hostname for package: python-tornado-4.2.1-1.el7.x86_64
---> Package python-zmq.x86_64 0:15.3.0-3.el7 will be installed
--> Processing Dependency: zeromq >= 4 for package: python-zmq-15.3.0-3.el7.x86_64
--> Processing Dependency: libzmq.so.5()(64bit) for package: python-zmq-15.3.0-3.el7.x86_64
---> Package salt.noarch 0:2019.2.0-1.el7 will be installed
--> Processing Dependency: python2-futures >= 2.0 for package: salt-2019.2.0-1.el7.noarch
---> Package systemd-python.x86_64 0:219-57.el7 will be installed
---> Package yum-utils.noarch 0:1.1.31-45.el7 will be installed
--> Processing Dependency: python-kitchen for package: yum-utils-1.1.31-45.el7.noarch
--> Running transaction check
---> Package libyaml.x86_64 0:0.1.4-11.el7_0 will be installed
---> Package python-babel.noarch 0:0.9.6-8.el7 will be installed
---> Package python-backports-ssl_match_hostname.noarch 0:3.5.0.1-1.el7 will be installed
--> Processing Dependency: python-backports for package: python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch
--> Processing Dependency: python-ipaddress for package: python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch
---> Package python-chardet.noarch 0:2.2.1-1.el7_1 will be installed
---> Package python-kitchen.noarch 0:1.1.1-5.el7 will be installed
---> Package python-urllib3.noarch 0:1.10.2-5.el7 will be installed
---> Package salt.noarch 0:2019.2.0-1.el7 will be installed
--> Processing Dependency: python2-futures >= 2.0 for package: salt-2019.2.0-1.el7.noarch
---> Package zeromq.x86_64 0:4.1.4-7.el7 will be installed
--> Processing Dependency: libsodium.so.23()(64bit) for package: zeromq-4.1.4-7.el7.x86_64
--> Processing Dependency: libpgm-5.2.so.0()(64bit) for package: zeromq-4.1.4-7.el7.x86_64
--> Running transaction check
---> Package libsodium.x86_64 0:1.0.16-1.el7 will be installed
---> Package openpgm.x86_64 0:5.2.122-2.el7 will be installed
---> Package python-backports.x86_64 0:1.0-8.el7 will be installed
---> Package python-ipaddress.noarch 0:1.0.16-2.el7 will be installed
---> Package salt.noarch 0:2019.2.0-1.el7 will be installed
--> Processing Dependency: python2-futures >= 2.0 for package: salt-2019.2.0-1.el7.noarch
--> Finished Dependency Resolution
Error: Package: salt-2019.2.0-1.el7.noarch (salt-latest)
           Requires: python2-futures >= 2.0
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
ping @dmurphy18

**Comment by dmurphy18** [comment]
@tganzeboom After using the install repo rpm for Salt 2019.2.0 latest, did you perform a 
yum makecache to update the yum database.

Working with a CentOS 7.3 system, the missing python2-futures is supplied by the base, as seen,

Dependencies Resolved

==================================================================================================================================================================
 Package                                    Arch                            Version                                    Repository                            Size
==================================================================================================================================================================
Installing:
 salt-minion                                noarch                          2019.2.0-1.el7                             salt-latest                           37 k
Installing for dependencies:
 PyYAML                                     x86_64                          3.11-1.el7                                 salt-latest                          160 k
 libsodium                                  x86_64                          1.0.16-1.el7                               salt-latest                          140 k
 libtomcrypt                                x86_64                          1.17-26.el7                                extras                               224 k
 libtommath                                 x86_64                          0.42.0-6.el7                               extras                                36 k
 libyaml                                    x86_64                          0.1.4-11.el7_0                             base                                  55 k
 openpgm                                    x86_64                          5.2.122-2.el7                              salt-latest                          172 k
 python-babel                               noarch                          0.9.6-8.el7                                base                                 1.4 M
 python-jinja2                              noarch                          2.7.2-2.el7                                base                                 515 k
 python-markupsafe                          x86_64                          0.11-10.el7                                base                                  25 k
 python-msgpack                             x86_64                          0.4.6-1.el7                                salt-latest                           73 k
 python-psutil                              x86_64                          2.2.1-1.el7                                salt-latest                          114 k
 python-tornado                             x86_64                          4.2.1-4.el7                                base                                 641 k
 python-zmq                                 x86_64                          15.3.0-3.el7                               salt-latest                          520 k
 python2-crypto                             x86_64                          2.6.1-15.el7                               extras                               477 k
 python2-futures                            noarch                          3.1.1-5.el7                                base                                  29 k
 salt                                       noarch                          2019.2.0-1.el7                             salt-latest                          9.5 M
 zeromq                                     x86_64                          4.1.4-7.el7                                salt-latest                          556 k

Transaction Summary
==================================================================================================================================================================
Install  1 Package (+17 Dependent packages)

Total download size: 15 M
Installed size: 65 M
Is this ok [y/d/N]: 


There is a python-futures provided by SaltStack's repo, but I shall ensure that the dependency is correct in the spec file, that is, python-futures, but updating yum database should get you working.

**Comment by dmurphy18** [comment]
fix is in backlog for salt-pack https://github.com/saltstack/salt-pack/issues/658

**Comment by tganzeboom** [comment]
@dmurphy18
That's because you are using Centos, which uses the EPEL repo. After I added the EPEL repo, everything worked again. I hope they this is fixed now, so that it comes with the saltstack repo.

**Comment by tganzeboom** [comment]
@dmurphy18
Could not edit my previous statement, so I'll put it here.

I read your #658 comment now. So it was a wrong reference. However, you can not compare the RHEL repo's with Centos' Repo's. Epel has a lot more in its repo plus it differs on rpm's.

**Comment by offgridengineering** [comment]
If you enable the epel.repo, you can install the python2-futures package, then disable epel.repo and install the salt-minion on CENTOS7

# vi epel.repo
[root@hw97 yum.repos.d]# yum install python2-futures
Loaded plugins: fastestmirror, langpacks, priorities, product-id, refresh-packagekit, rhsm-auto-add-pools, search-disabled-repos, shaman, va, virtuozzo, vzlinux, yum-
              : plugin-readykernel
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                                                                                                           | 4.8 kB  00:00:00     
 * epel: mirror.overthewire.com.au
Trying to discover and attach new pools
epel                                                                                                                                           | 4.7 kB  00:00:00     
(1/3): epel/x86_64/group_gz                                                                                                                    |  88 kB  00:00:00     
(2/3): epel/x86_64/updateinfo                                                                                                                  | 960 kB  00:00:00     
(3/3): epel/x86_64/primary_db                                                                                                                  | 6.6 MB  00:00:00     
703 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package python-futures.noarch 0:3.0.3-1.el7 will be obsoleted
---> Package python2-futures.noarch 0:3.0.5-1.el7 will be obsoleting
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================================================================
 Package                                      Arch                                Version                                     Repository                         Size
======================================================================================================================================================================
Installing:
 python2-futures                              noarch                              3.0.5-1.el7                                 epel                               26 k
     replacing  python-futures.noarch 3.0.3-1.el7

Transaction Summary
======================================================================================================================================================================
Install  1 Package

Total download size: 26 k
Is this ok [y/d/N]: y
Downloading packages:
python2-futures-3.0.5-1.el7.noarch.rpm                                                                                                         |  26 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python2-futures-3.0.5-1.el7.noarch                                                                                                                 1/2 
  Erasing    : python-futures-3.0.3-1.el7.noarch                                                                                                                  2/2 
  Verifying  : python2-futures-3.0.5-1.el7.noarch                                                                                                                 1/2 
  Verifying  : python-futures-3.0.3-1.el7.noarch                                                                                                                  2/2 
Installed:
  python2-futures.noarch 0:3.0.5-1.el7                                                                                                                                
Replaced:
  python-futures.noarch 0:3.0.3-1.el7                                                                                                                                 
Complete!

**Comment by dmurphy18** [comment]
@tganzeboom Add information to https://github.com/saltstack/salt-pack/issues/658, but basically both in CentOS 7.3 and RHEL 7.3 I see python2-furtures and not from EPEL.

The packages are built such as to not require EPEL (except for Python 3 support)

I am updating the spec files to require python-futures instead of python2-futures since
CentOS:
root@localhost:~# rpm -q --whatprovides python2-futures
python2-futures-3.1.1-5.el7.noarch
root@localhost:~# rpm -q  python2-futures --provides
python-futures = 3.1.1-5.el7
python2-futures = 3.1.1-5.el7

and Redhat:
[root@ip-10-200-19-243 ec2-user]# rpm -q --whatprovides python2-futures
python2-futures-3.1.1-5.el7.noarch
[root@ip-10-200-19-243 ec2-user]# rpm -q  python2-futures --provides
python-futures = 3.1.1-5.el7
python2-futures = 3.1.1-5.el7


Can you provide a copy of yum repolist, if that is possible since curious as to why you are not finding python2-futures from either CentOS or RHEL 7

**Comment by dmurphy18** [comment]
@tganzeboom Having installed Redhat 7.5 from DVD iso into VirtualBox, I see the issue of python-futures, however note that similar Redhat 7.5 images available on AWS do contain python2-futures which is also aliased as python-futures.

I would be interested to know if your RHEL 7.5 installation is a minimal install, server install, etc. to better match your environment when testing resolution of the issue with the next point release.

**Comment by dmurphy18** [comment]
@tganzeboom Note installed and registered RHEL 7.6 in a VirtualBox VM and found the following:

[root@localhost ~]# yum list python* | grep future
python2-futures.noarch           3.1.1-5.el7                  @anaconda/7.6     
[root@localhost ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
[root@localhost ~]# 

However with the RHEL 7.5 system with no registration, there is no python[2]-futures available.  Unfortunately with registration and my user credentials this system doesn't have any repos available.

[root@localhost ~]# subscription-manager auto-attach
Auto-attach preference: enabled
[root@localhost ~]# subscription-manager repos
This system has no repositories available through subscriptions.
[root@localhost ~]# yum list python* | grep future
[root@localhost ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
[root@localhost ~]# 

Wondering it this might also be the case with your system ?, and hence the issue.

**Comment by dmurphy18** [comment]
@tganzeboom Wondering what kind of Redhat 7.5 install you used ?
