### ISSUE TITLE
YAML.org recommends `.yaml` extension for pillar data

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack/salt#51910]
### Description of Issue/Question

By convention YAML markup files should use `.yaml` extension but salt refuses to read YAML file saved with this extension.   This is non-intuitive, a barrier to adopting salt, and does not follow recommendation from [https://yaml.org/faq.html](https://yaml.org/faq.html) 

> Is there an official extension for YAML files?
> Please use ".yaml" when possible.

Please allow `.yaml` extension for pillar data.

### Setup

salt error for pillar data in saved as `/srv/pillar/template.yaml`
```
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'template' in environment 'base' is not available on the salt master
```

**Salt enforces `.sls` extension for files in YAML format.**

1. [L82](https://github.com/saltstack/salt/blob/b44f0f1d0fd564690c6e45c6dd061c0e84d76def/salt/spm/pkgfiles/local.py#L82)
1. [L120](https://github.com/saltstack/salt/blob/b44f0f1d0fd564690c6e45c6dd061c0e84d76def/salt/spm/pkgfiles/local.py#L120)
1. [L148](https://github.com/saltstack/salt/blob/b44f0f1d0fd564690c6e45c6dd061c0e84d76def/salt/spm/pkgfiles/local.py#L148)

Here's the code in [`salt/pillar/__init__.py`](https://github.com/saltstack/salt/blob/61baab97de511aab9273446062430f02623f5d2d/salt/pillar/__init__.py#L707-L725), which calls [`salt/fileclient.py`](https://github.com/saltstack/salt/blob/138c9321d43aa1aa3950df8509f3d47aa24fe244/salt/fileclient.py#L361-L374). 

### Versions Report
All versions

**Comment by aboe76** [comment]
@noelmcloughlin but pillar.sls files aren't only ```yaml``` they could contain jinja or ggp secrets,
see for the complete list: https://docs.saltstack.com/en/latest/ref/renderers/

**Comment by dwoz** [comment]
@noelmcloughlin As @aboe76 points out, pillars are a mixture of jinja templating and yaml hence the  `sls` file extension. Having said that I think it might make sense to be able to load static data from yaml files under the pillar roots.

@saltstack/team-core thoughts on this?

**Comment by waynew** [comment]
I'm personally disinclined given the fact that they're not *actually* YAML files, they just use YAML syntax. YAML files just happen to be a subset of Salt state and pillar files. I suspect there may be documentation that suggests otherwise, but it seems like allowing `.yaml` for pillar is misleading.

> This is non-intuitive, a barrier to adopting salt

If we have some documentation that suggests a `.yaml` extension is OK, then we should absolutely fix that. Otherwise, can you help me understand why that would be confusing? As far as I'm aware, our documentation only says to use `.sls` extensions, so if someone is reading the documentation they shouldn't be thinking they can use `.yaml` extensions. What am I missing here?

**Comment by thatch45** [comment]
I understand where this is coming from but I would strongly discourage it. it would mandate that how we look up sls files needs to be changed and could potentially break any existing pillars if they have added .yaml files tot he tree for any other reason.

I also think it makes adoption harder, because now there is an arbitrary, confusing construct that pops up in random pillar trees and a need to explain why we have multiple loaded file types

**Comment by waynew** [comment]
If you're really interested in being able to load from `.yaml` files, you can create a [pillar module](https://docs.saltstack.com/en/latest/topics/development/external_pillars.html) and in your `ext_pillar` function load the `.yaml` file yourself.

Or, there's also the [cmd_yaml](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.cmd_yaml.html#module-salt.pillar.cmd_yaml) pillar module that you could use, though I'm not entirely sure on the syntax there.

**Comment by noelmcloughlin** [comment]
> @noelmcloughlin but pillar.sls files aren't only `yaml` they could contain jinja or ggp secrets,
> see for the complete list: https://docs.saltstack.com/en/latest/ref/renderers/

This issue is to request support for files with extension `.yaml` because its a data exchange format.

**Comment by noelmcloughlin** [comment]
The background to this request is discussion at https://github.com/saltstack-formulas/template-formula/pull/62

**Comment by dwoz** [comment]
@noelmcloughlin If you want to consume raw yaml files as pillar data I think the best approach is to use the external pillar system: 

https://docs.saltstack.com/en/latest/topics/development/external_pillars.html

It should be a fairly straight forward exercise to write an ext_pillar that reads your yaml files.

**Comment by noelmcloughlin** [comment]
Hi @dwoz 
That sounds interesting. If there is consensus to leave this alone regarding extension, that's fine with me.
