### ISSUE TITLE
Missing Documentation for RotatingLogHandler

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#51921]
### Description of Issue/Question
Found a couple of undocumented logging options for the minion. These aren't mentioned in either the master or the minion config pages.

```
    # The maximum number of bytes a single log file may contain before
    # it is rotated. A value of 0 disables this feature.
    # Currently only supported on Windows. On other platforms, use an
    # external tool such as 'logrotate' to manage log files.
    'log_rotate_max_bytes': int,

    # The number of backup files to keep when rotating log files. Only
    # used if log_rotate_max_bytes is greater than 0.
    # Currently only supported on Windows. On other platforms, use an
    # external tool such as 'logrotate' to manage log files.
    'log_rotate_backup_count': int,
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
This is in current version:

https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py

**Comment by Ch3LL** [comment]
thanks! we should get this documented. Did you want to take a stab at a PR? Should be pretty easy. Just need to add it to `doc/ref/configuration/master.rst` and `doc/ref/configuration/minion.rst` files, so that its now documented at: https://docs.saltstack.com/en/latest/ref/configuration/minion.html and https://docs.saltstack.com/en/latest/ref/configuration/master.html

**Comment by Akm0d** [comment]
The above PR adds the missing documentation
