### ISSUE TITLE
Salt package for RHEL/CentOS 7 requires python34 which will be EOLed soon

### ISSUE THREAD

**Issue by AndreyMZ** [saltstack/salt#51952]
### Description of Issue/Question
Salt package for RHEL/CentOS 7 requires python34. But:
1. End-of-life of Python 3.4 will be on 2019-03-16. This is earlier than EOL of Python 2.7!
2. Looks like Python 3.6 is available through EPEL: https://lists.fedoraproject.org/archives/list/epel-announce@lists.fedoraproject.org/thread/VLTFSZEQHXBZHHDAKMT4KCQEKPSFV5OS/

### Setup
\-

### Steps to Reproduce Issue
```
yum install https://repo.saltstack.com/py3/redhat/salt-py3-repo-2019.2.el7.noarch.rpm 
yum install salt-minion
rpm -q salt --requires
```

**Actual result:**
```
[root@host ~]# rpm -q salt --requires
...
python(abi) = 3.4
python34-...
...
```

**Expected result:**
```
[root@host ~]# rpm -q salt --requires
...
python(abi) = 3.6
python36-...
...
```

### Versions Report
[version-report.txt](https://github.com/saltstack/salt/files/2925662/version-report.txt)

**Comment by garethgreenaway** [comment]
@dmurphy18 FYI.

**Comment by dmurphy18** [comment]
@AndreyMZ  There are plans to update to using Python 3.6 from EPEL-7 with RHEL 7 for upcoming point releases, noting that EPEL-7 were planning on updating by today, April 2nd 2019.  Once they have updated, then will adjust packages from Salt.

You can track this in salt-pack-py3 which is the correct location for packing issues with Salt for Python 3
https://github.com/saltstack/salt-pack-py3/issues/119

Hence closing this issue in Salt GitHub repo since this is a packaging issue.
