### ISSUE TITLE
Installing salt-minion 2018.3.4 failing on debian jessie (8.8)

### ISSUE THREAD

**Issue by cavepopo** [saltstack/salt#52204]
### Description of Issue/Question
Trying to install salt-minion on debian jessie (fresh install) 8.8 fails.

Salt-minion needs salt-common:
`The following packages have unmet dependencies:
 salt-minion : Depends: salt-common (= 2018.3.4+ds-1) but it is not going to be installed`

which in turn needs python-systemd, but:
`salt-common : Depends: python-systemd but it is not installable`

Content of saltstack.list :
`deb https://repo.saltstack.com/apt/debian/8/amd64/archive/2018.3.4 jessie main`

### Steps to Reproduce Issue
Spawning a brand new vm using debian 8.8 and trying to install the salt-minion 2018.3.4 should be enough

### Versions Report
Target version:  2018.3.4

**Comment by garethgreenaway** [comment]
@dmurphy18 FYI.

**Comment by dmurphy18** [comment]
@cavepopo Removed the previous python-systemd dependency since it is already provided by the underlying OS. Building on Debian 8.7 on AWS, and the version that SaltStack used was causing conflicts with the version provided by AWS Debian 8.7.

Can you provide the output of apt-cache policy python-systemd to see what version is available to you, since as part of my investigation into the systemd conflicts, the version of python-systemd dated back to changes in Debian 8.5.

**Comment by dmurphy18** [comment]
@cavepopo fixing this for the next point release, see saltstack/salt-pack#657 for discussion of issue.
Marking this as duplicate and closing it since salt-pack is the correct location to discuss Salt packaging issues.

**Comment by dmurphy18** [comment]
@cavepopo FYI - Both of the Salt 2018.3.4 and 2019.2.0 for Debian 8 on amd64 repositories have been updated with a restored python-systemd package.

**Comment by cavepopo** [comment]
OK, good news, thanks for the update.
