### ISSUE TITLE
pip install outdated? maybe?

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#52309]
### Question
Does [this](https://docs.saltstack.com/en/latest/topics/development/hacking.html#editing-and-previewing-the-documentation) page's example command still require sphinx=1.3.1 or should this be changed?
```
pip install Sphinx==1.3.1
```

**Comment by dmurphy18** [comment]
@alan-cugler The version of Sphinx used in the example could be changed to a later version, but generally with SaltStack documentation, specific versions are usually only called out when a certain version is required, and typically implies at least a minimal version, for example: python-tornado v4.2.1 but most operating systems now ship with a later version.

Also SaltStack would need to change the versions specified for for each operating system, for example: Debian 8, Debian 9, Ubuntu 14.04, Ubuntu 16.04 and Ubuntu 18.04.  Hence a never ending task updating all versions in examples provided.  With the upcoming depreciation of support for Python 2 which is reaching End-of-Life on 1 January  2020, (currently scheduled for Sodium time frame) the documentation will be over-hauled to reflect support only for Python 3 and examples will be revised at that time.

Thanks for pointing the issue out and the need for revision at that time.
Closing this and marking as Won't Fix due to explanation above.  Please feel free to re-open the issue if the explanation is unsatisfactory.
