### ISSUE TITLE
Azurearm with Salt 2019.2.0 Salt Cloud can't connect to Windows VMs

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#52529]
### Description of Issue/Question
Salt Cloud can provision a new Windows VM on Azure, but it can't connect to the new VM to install and configure the Salt Minion.  I'm not sure if it's because my user can't connect from a remote minion or if my Salt Master needs to be on Azure as well.

My Salt Master is on a different cloud.
### Setup
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud any ideas here?

**Comment by gtmanfred** [comment]
There is no information on troubleshooting done here, so I can't even begin to guess.

Did you make sure the ports are open on the for the security groups so that the master could winrm/winexe in?  Have you tried doing it manually?

It is worth noting that once you get the minion connected, you will see problems with the minion disappearing from time to time.  There are several other issues in the salt issue tracker where Azure is killing off long running connections over their edge gateway, which has killed salt-minion connections in the past.

So i would probably just say... don't do this?
