### ISSUE TITLE
unit.utils.test_jinja.TestCustomExtensions.test_http_query - KeyError: 'body'

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52821]
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.utils.test_jinja/TestCustomExtensions/test_http_query)
---

'body'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 212, in wrap
    raise exc
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 209, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/unit/utils/test_jinja.py", line 1116, in test_http_query
    self.assertIsInstance(dict_reply['body'], six.string_types, 'Failed with backend: {}'.format(backend))
KeyError: 'body'
		
```

**Comment by frogunder** [comment]
This seems to have been resolved with the change to use nox when running tests.

The fix was to update requests from 2.20.2 to 2.21.0, but in the nox requirement file, requests is set to use version 2.21.0.

2019.2.1 is on nox, develop is not yet, but this issue will also be resolved in develop once that changes to use nox.

Closing this issue.
