### ISSUE TITLE
Support for RHEL8

### ISSUE THREAD

**Issue by sastorsl** [saltstack/salt#53125]
### Description of Issue/Question
Any roadmap for when saltstack will have packages for RedHat Enterprise Linux 8 / RHEL8?
http://repo.saltstack.com/yum/redhat/

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
N/A

**Comment by dmurphy18** [comment]
@sastorsl  This is an active project which is currently undergoing development with our automation processes.  Hopefully it will be completed in time for the next point release.

You can follow it's progress here https://github.com/saltstack/salt-pack-py3/issues/120.

Closing this issue since, above is the correct place to track this

**Comment by saltpicker** [comment]
Hello.

So - how about RHEL8 support?
Is there any public repo available? (similiar to 6/7 repos)

Thanks.

**Comment by saltpicker** [comment]
OK, sorry looks like i missed smth, Got it:
http://repo.saltstack.com/py3/redhat/8.1/x86_64/
