### ISSUE TITLE
Reactor System documentation page has wrong indentation in examples

### ISSUE THREAD

**Issue by cifvts** [saltstack/salt#53154]
### Description of Issue/Question

Page 'Reactor System' in site documentation (https://docs.saltstack.com/en/latest/topics/reactor/index.html) contains examples with wrong indentation.

https://docs.saltstack.com/en/latest/topics/reactor/index.html#local-reactions
https://docs.saltstack.com/en/latest/topics/reactor/index.html#runner-reactions
https://docs.saltstack.com/en/latest/topics/reactor/index.html#caller-reactions

**Comment by newwebash** [comment]
After some investigation I can confirm the incorrect indentation, which seems to be caused by the `.align-center` class. This is present in all three published versions of the docs, in both FireFox and Chrome.

![image](https://user-images.githubusercontent.com/16036486/58122430-a18bf580-7bd7-11e9-875a-a8dc7a0ee9e6.png)

However, I'm not able to reproduce this issue in my local build. I wonder if the root cause is a Sphinx build issue. Assigning to @Ch3LL for further investigation.
