### ISSUE TITLE
I can't get custom grain data remotely.but local salt-call grains.get is fine

### ISSUE THREAD

**Issue by iwz2099** [saltstack/salt#53150]
I can't get custom grain data remotely.but local salt-call grains.get is fine

```
#salt master:
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.6.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
```
#salt minion:
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
```
[root@manage-op salt]# cat _grains/memory_all.py
#!/usr/bin/env python
#coding:utf-8
#pip install py-dmidecode==0.0.2
import dmidecode

def get_memory():
    memlist = []
    grains = {}
    p = dmidecode.get_by_type(17)
    for mem in p:
        dict_items={}
        if mem['Type'] not in 'Unknown' and mem['Serial Number'] not in 'NO DIMM':
            dict_items["sn"] = mem['Serial Number']
            dict_items["model"] = mem['Type']
            dict_items["manufacturer"] = mem['Manufacturer']
            dict_items["slot"] = mem['Locator']
            dict_items["Size"] = mem['Size']
            memlist.append(dict_items)
    grains['memory'] = memlist
    return grains
```
```
[root@manage-op salt]# salt-run cache.clear_all
[root@manage-op salt]# salt gz-hdfs022.test.cn saltutil.sync_all
[root@manage-op salt]# salt gz-hdfs022.test.cn grains.get memory -ldebug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: manage-op.test.cn
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: manage-op.test.cn
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'manage-op.test.cn_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/0b/b8b579b9f3cd9a66c179d716fc7792393290ca65024c812136399147a65710/.minions.p
[DEBUG   ] get_iter_returns for jid 20190521205239476360 sent to set(['gz-hdfs022.test.cn']) will timeout at 20:52:44.501906
[DEBUG   ] jid 20190521205239476360 return from gz-hdfs022.test.cn
[DEBUG   ] return event: {u'gz-hdfs022.test.cn': {u'jid': u'20190521205239476360', u'retcode': 0, u'ret': u''}}
[DEBUG   ] LazyLoaded nested.output
gz-hdfs022.test.cn:

```
```
[root@gz-hdfs022 ~]# salt-call grains.get memory
local:
    |_
      ----------
      Size:
          32 GB
      manufacturer:
          Hynix
      model:
          DDR4
      slot:
          CHE_0
      sn:
          827A6154
    |_
      ----------
      Size:
          32 GB
      manufacturer:
          Hynix
      model:
          DDR4
      slot:
          CHA_0
      sn:
          827A6153
```

**Comment by twangboy** [comment]
@nanguawu Maybe the loader isn't getting the new grain file after a sync... what if you restart the minion?

@saltstack/team-core Any ideas here?

**Comment by twangboy** [comment]
Probably related: https://github.com/saltstack/salt/issues/53150

**Comment by nanguawu** [comment]
@twangboy  yeah. I still can't get custom grain data after restarting minion.
But I have to execute saltutil.sync_all on the master instead of saltutil.sync_grains .
Then I can get to my custom grain data.

#After executing saltutil.sync_grains
[root@manage-op ~]# salt gz-hdfs022.test.cn grains.get memory
gz-hdfs022.test.cn:
    Minion did not return. [No response]

#After executing saltutil.sync_all
[root@manage-op ~]# salt gz-hdfs022.test.cn saltutil.sync_all -ldebug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: manage-op.test.cn
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: manage-op.test.cn
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'manage-op.test.cn_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/e7/44b15dd7c38357a078554bc930a7da5516f0288161289df0f2ab58021be486/.minions.p
[DEBUG   ] get_iter_returns for jid 20190522102329435656 sent to set(['gz-hdfs022.test.cn']) will timeout at 10:23:34.454596
[DEBUG   ] Checking whether jid 20190522102329435656 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'manage-op.test.cn_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Passing on saltutil error. Key 'u'retcode' missing from client return. This may be an error in the client.
[DEBUG   ] jid 20190522102329435656 return from gz-hdfs022.test.cn
[DEBUG   ] return event: {u'gz-hdfs022.test.cn': {u'jid': u'20190522102329435656', u'retcode': 0, u'ret': {u'clouds': [], u'engines': [], u'grains': [], u'beacons': [], u'utils': [], u'returners': [], u'modules': [], u'renderers': [], u'log_handlers': [], u'thorium': [], u'states': [], u'sdb': [], u'proxymodules': [], u'output': []}}}
[DEBUG   ] LazyLoaded nested.output
gz-hdfs022.test.cn:
    ----------
    beacons:
    clouds:
    engines:
    grains:
    log_handlers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    thorium:
    utils:
[root@manage-op ~]# salt gz-hdfs022.test.cn grains.get memory
gz-hdfs022.test.cn:
    |_
      ----------
      Size:
          32 GB
      manufacturer:
          Hynix
      model:
          DDR4
      slot:
          CHE_0
      sn:
          827A6154
    |_
      ----------
      Size:
          32 GB
      manufacturer:
          Hynix
      model:
          DDR4
      slot:
          CHA_0
      sn:
          827A6153
