### ISSUE TITLE
Exception occurred when minion return large data.

### ISSUE THREAD

**Issue by GwiYeong** [saltstack/salt#53230]
### Description of Issue/Question
i reinstalled requirements/base.txt with `pip -r` when i upgrade my salt-master. after then `Exception occurred while handling stream: 1048606 exceeds max_str_len(1048576)` error is occured.
my previous version of saltstack is `v2017.7.4` and upgrading to `v2017.7.8`.

i search the issue and then i find out that is `msgpack` version issue.
`pip -r requirements/base.txt` will install latest version of msgpack (0.6.1 currently). i find this [issue](https://github.com/borgbackup/borg/issues/4251). so i installed msgpack 0.5.6 manually after uninstalling latest version of msgpack and the error is gone. the problem is solved. 

so how does saltstack solve this problem? 
i thinks there is 2 options to fix it.
  1. fix requirements
  2. support current msgpack version

first option is simpler than second, so i can fix it myself and send pr(just update requirements). 
but second one i can not fix it (it is so complicated).  

So what do you think what should i do for? 
could you guys fix it?

i need your opinion.

thanks in advance

### Setup
1. install saltstack 2017.7
2. make large length file.
```
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 8126 > ~/long_text_1 
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 8127 > ~/long_text_2
```

### Steps to Reproduce Issue
3. send commend with salt-api with payload
```
{
	"client": "local",
	"tgt": ["salt-minion"],
	"tgt_type": "list",
	"fun": "cmd.run",
	"arg": ["cat ~/long_text_1"]
}
```
- with msgpack > 0.5.6
```
  long_text_1 -> Success
  long_text_2 -> Exception occurred while handling stream: 1048646 exceeds 
 max_str_len(1048576) occured
```
- with msgpack <= 0.5.6
```
  long_text_1 -> Success
  long_text_2 -> Success
```

### Versions Report
salt-master & salt-minion (same host)
```
Salt Version:
           Salt: 2017.7.8-426-g464764a

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec 23 2016, 09:50:41)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: centos 6.5 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.3.2.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final
```

**Comment by dmurphy18** [comment]
@GwiYeong The version of Salt that you are using has CVE-Support Only and I would urge upgrading to a currently supported version, for example: Salt 2018.3.4 or 2019.2.0 for which there are RHEL 6 packages provided.

Note that with pip installations, you will get the latest version of a package unless a specific version is specified, for example: Salt 2019.2.0 salt/requirements/base/txt

:~/devcode/test_checkout_salt/salt/requirements$ cat base.txt 
Jinja2
# This should be changed to msgpack-python for Packages
# msgpack-python>0.3,!=0.5.5
msgpack>=0.5,!=0.5.5
PyYAML<5.1
MarkupSafe
requests>=1.0.0
tornado>=4.2.1,<6.0; python_version < '3'
tornado>=4.2.1,<5.0; python_version >= '3.4'

# Required by Tornado to handle threads stuff.
futures>=2.0; python_version < '3.0'

There have been fixes made since 2017.7.x for msgpack issues, hence the benefit of updating to supported versions.  Note that Salt 2017.7.8-426-g464764a is not a released version and hence is unsupported. Release versions for Redhat 6 are available from repo.saltstack.com.

Internal testing with latest versions of msgpack, pip installed, have not shown any issues with currently supported software, however if you upgrade to a later version of Salt and still encounter an issue with msgpack v0.6.1, please let us know as soon as possible.

If this resolves the issue, please consider closing the issue.

**Comment by GwiYeong** [comment]
ok. i will upgrade my saltstack. thanks!

**Comment by hedrickbt** [comment]
We are seeing this error with 2019.2.0

webtask@webadminubuntu02:~$ sudo salt --versions-report
[sudo] password for webtask: 
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.5.0
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.10
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 12 2018, 13:43:14)
   python-gnupg: 0.3.8
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-151-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by hedrickbt** [comment]
It looks like the issue is that changes were made in msgpack 0.60 to avoid DOS attacks caused by large messages.  https://github.com/msgpack/msgpack-python/blob/master/ChangeLog.rst

We are going to try to change the MAX_EVENT_SIZE in the salt master configuration file to see if we can accommodate the size of our messages.  A 1MB response default size seems small for something like a highstate.

**Comment by gordonm** [comment]
@hedrickbt We have a similar issue, the return data for large orchestration states wind up being around 2-3 MB and are supposed to be returned to a client calling salt-api. In our case the exception is in `salt.transport.ipc`, so `max_event_size` has no effect there (I tested this just to be sure, I'm sure you will have found the same).

For msgpack >=0.6.1, I believe the fix would be to pass `max_buffer_size` to `msgpack.Unpacker()` with a configurable value. For now I'll try to patch the master with a hardcoded value and test again.

**Comment by johnj** [comment]
I had a similar issue and I just ended up pinning msgpack to 0.5.6 in our build for now.
