### ISSUE TITLE
SSH config affecting/breaking salt gitfs

### ISSUE THREAD

**Issue by mjtorn** [saltstack/salt#5372]
I always have a special conf in _~/.ssh/config_ for ssh repos, ie. github.com.

    Host github.com
        LogLevel DEBUG
        IdentityFile ~/.ssh/whatever

The LogLevel part breaks salt-master when running (eg.) _salt \\* saltutil.sync_all_:

    2013-06-02 11:58:20,872 [salt.master                                 ][ERROR   ] Exception len(["6311b6aa0d81bccd530167397eb29aefda170c97\tnot-for-merge\tbranch 'master' of git+ssh://github.com/XXX/XXXXXXXXXX\n"]) != len(['debug1: Connecting to github.com [204.232.175.90] port 22.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ' = [up to date]      master     -> origin/master', 'debug1: client_input_channel_req: channel 0 rtype exit-status reply 0', '', '', '', '', '', '', '']) occurred in file server update

Or the above split for readability:

    2013-06-02 11:58:20,872 [salt.master                                 ][ERROR   ] Exception
    len(["6311b6aa0d81bccd530167397eb29aefda170c97\tnot-for-merge\tbranch 'master' of git+ssh://github.com/XXX/XXXXXXXXXX\n"]) 
        !=
    len(['debug1: Connecting to github.com [204.232.175.90] port 22.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '
        = [up to date]      master     -> origin/master', 'debug1: client_input_channel_req: channel 0 rtype exit-status reply 0', '', '', '', '', '', '', ''])
    occurred in file server update

The setup in question is Debian Wheezy with salt 0.15.2 built and packaged from the Github tag. Should break on anything, though.

    salt@ip-10-34-204-69:~$ salt --versions-report | sed 's/^/    /g'
               Salt: 0.15.2
             Python: 2.7.3 (default, Jan  2 2013, 13:56:14)
             Jinja2: 2.6
           M2Crypto: 0.21.1
     msgpack-python: 0.1.10
       msgpack-pure: Not Installed
           pycrypto: 2.6
             PyYAML: 3.10
              PyZMQ: 2.2.0
                ZMQ: 2.2.0

(It should also be noted the documentation says the _id_rsa_ file must be used with gitfs. This is obviously not true ;))

**Comment by terminalmage** [comment]
GitPython has become actively developed once again, so the initial issue reported may well be resolved in newer GitPython releases.

In addition, we now have pygit2 support for a few release cycles (pygit2 0.20.3 added support for passing credentials), allowing for both HTTPS and SSH key authentication (even with passphrases!).

Information on the expanded gitfs support can be found in the [GitFS Walkthrough](https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html).

I'm going to close this, if you still get this error with newer GitPython then I recommend filing an [upstream bug report](https://github.com/gitpython-developers/GitPython/issues) with GitPython, or using Pygit2 instead of GitPython.
