### ISSUE TITLE
Py2 Ubuntu 16.04 TCP timeout issue 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53929]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/All/job/salt-ubuntu-1604-py3-tcp/60/console

**Comment by dmurphy18** [comment]
Waiting for part of PR https://github.com/saltstack/sre-jenkins/pull/100 to be merged, namely https://github.com/saltstack/sre-jenkins/pull/100/files#diff-798c9769e42651578e64f8590f2c99af need that lower and the **RUNTESTS-TCP-3*

00:03:56.660         [Nox] Verify on instance py3-ubuntu-1604 with state={:username=>"ubuntu", :server_id=>"i-0e95aa4d5e8e91ff2", :hostname=>"10.72.110.95", :last_action=>"setup", :last_error=>nil}
00:03:57.035         Running Command: env CI=1 nox -f /tmp/kitchen/testing/noxfile.py -e '**RUNTESTS-TCP-3**(coverage=True)' -- --output-columns=120  --sysinfo --xml=/tmp/kitchen/testing/artifacts/xml-unittests-output -v --run-destructive --ssh-tests  


And on a side note why is s0undtech in git paths ?, for example:

00:00:24.573  + bundle install --with ec2 windows --without docker macos opennebula vagrant
00:00:24.573  Fetching https://github.com/**s0undt3ch**/kitchen-salt.git
00:00:24.950  Fetching https://github.com/test-kitchen/kitchen-docker.git
00:00:25.249  Fetching https://github.com/s0undt3ch/winrm-fs.git

Resolving this should work for all of the TCP tests on other platforms since see similar config issues

**Comment by dmurphy18** [comment]
The update in configuration appears to have been made over the weekend, tests are now passing hence closing this.
