### ISSUE TITLE
where is the saltenv file

### ISSUE THREAD

**Issue by kussatom** [saltstack/salt#54027]
### Description of Issue
i can't use file.managed to define a file in a special saltevn with a special git branch

### Setup
 /etc/salt/master config file:
            - saltenv:
              - base:
                - ref: master
                - mountpoint: salt://files/gitfs/base
              - dev:
                - ref: dev
                - mountpoint: salt://files/gitfs/dev/
file_roots:
  base:
    - /srv/salt/base
  test:
    - /srv/salt/test
  dev:
    - /srv/salt/dev

cat /srv/salt/dev/centos/ff.sls
/home/tang/vimsec:
  file.managed:
    - source: salt://files/gitfs/dev/vimrc
with the above config, i run the commad: salt 'cent7test' state.sls saltenv='dev' centos/ff
then i get errors ,but if i run :salt 'cent7test' state.sls  centos7/files with another sls file in base dir ,it works.

my english is not good, hope you can get my meaning,thanks a lot for give me a hand

### Steps to Reproduce Issue
Function: file.managed
      Result: False
     Comment: Source file salt://files/gitfs/dev/vimrc not found in saltenv 'dev'
     Started: 05:36:19.076794
    Duration: 57.337 ms
     Changes:

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 3.7.2
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.3
         Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by bryceml** [comment]
when running states from the command line, the folders traversed using `.`'s instead of `/`'s so your command would be of the form:
```bash
 salt 'cent7test' state.sls saltenv='dev' centos.ff
```
I can't tell if your whitespace is off in config files because it looks like all the whitespace is missing, but it sounds like it's correct if you can get files in the base directory.

Also, issues are typically used to report bug or feature requests.  The community slack or irc channels are great resources for getting help like this:
https://saltstackcommunity.herokuapp.com/
https://webchat.freenode.net/#salt

The docs on this could be improved, but here they are: https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.state.html#salt.modules.state.sls

**Comment by kussatom** [comment]
@bryceml  it is a good idea to use . instead of / ,looks like better.i donot change anything  about whitespace,even i don't know what 's the  affect about whitespace, do you mean whitelist ?

**Comment by kussatom** [comment]
@bryceml   i change the  mountpoint ,and now it works
