### ISSUE TITLE
Ubuntu py3 18.04 failures 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54053]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-ubuntu-1804-py3/97/

**Comment by dmurphy18** [comment]
Wonders if we hit their 10 requests/second limit ? since  individual run is okay 

From their FAQ:
Q2: What is the maximum number of requests per second my client can issue?
We have DoS protection in place that will kick in if you issue more than 10 requests/second from the same IP address. If this happens, your IP address will be blocked for 24 hours.

If your applications requires a higher rate, please get in touch and we will help. Please do not distribute your traffic across several IP addresses to try and circumvent our DoS protection.

**Comment by dmurphy18** [comment]
Disabling tests for now since easy to abuse Random websites quota allowance, that is, number of requests/second, number of bits allowed/ip address.

Tests should initially be mocked to check API usage, since that will not abuse quotas, but in addition tests should be re-written to allow for Random's quotas to ensure that tests are run when allowance is within bounds.

**Comment by dmurphy18** [comment]
Closing since PR merged https://github.com/saltstack/salt/pull/54080
