### ISSUE TITLE
Py3 Ubuntu 18.04 failures on 2019.2.1 branch

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54118]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-ubuntu-1804-py3/114/

**Comment by dmurphy18** [comment]
Failure due to clock ran out doing the tests, this was due to following error on startup:

 25  * [0;1;32mStarting salt-master ... STARTED!
 26 [2019-08-03T18:18:17.236Z]        [0;0m * [0;1;33mStarting salt-minion ... [0;0m
 27 
 28  * [0;1;32mStarting salt-minion ... STARTED!
 29 [2019-08-03T18:24:26.616Z]        [0;0m * [0;1;33mStarting sub salt-minion ... [0;0m
 30 
 31  * [0;1;31mStarting sub salt-minion ... **_FAILED!_**
 32 [2019-08-03T18:24:30.245Z]        [0;0m * [0;1;33mStarting syndic salt-master ... [0;0m
 33 
 34  * [0;1;32mStarting syndic salt-master ... STARTED!
 35 [2019-08-03T18:24:30.245Z]        [0;0m * [0;1;33mStarting salt-syndic ... [0;0m

However note the time taken for the sub salt-minion to start 6:09 minutes, whereas the previous run it took only 11 seconds.  Something in the infrastructure is not working right.

Bryce mentioned that Felippeb is moving the logging over to EC2, so should look at that when it is available to see why it is taking so long for a minion to come up

**Comment by KChandrashekhar** [comment]
This OS test runs are failing in Neon 
https://jenkinsci.saltstack.com/job/neon/view/Python3/job/salt-ubuntu-1804-py3/112/

**Comment by KChandrashekhar** [comment]
Failing again in https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-ubuntu-1804-py3/127/ 

@felippeb Checking to see if Testing process is still active but no logging happening, and to get more logging.

**Comment by bryceml** [comment]
We need to look into this again, I think our logging is working well enough that we should be able to dig into it.

**Comment by dmurphy18** [comment]
Being testing successfully for the last couple of days hence closing
