### ISSUE TITLE
Fedora 30 py3 build failure on Neon branch 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54120]
### Description of Issue
Builds from 
https://jenkinsci.saltstack.com/job/neon/view/Python3/job/salt-fedora-30-py3/89/
to 
https://jenkinsci.saltstack.com/job/neon/view/Python3/job/salt-fedora-30-py3/94/

**Comment by KChandrashekhar** [comment]
Failed again: https://jenkinsci.saltstack.com/job/neon/view/Python3/job/salt-fedora-30-py3/

**Comment by dmurphy18** [comment]
#94 deliberately killed, issue is timeout, awaiting the current build to finish since the ami has been updated

**Comment by dmurphy18** [comment]
current builds have been successful with the updated ami's, that is  build 98 through 100

**Comment by dmurphy18** [comment]
Build 101: failure due to timeout, after successful tests, as if problem is launching CodeCov
Build 102: failure due to ssh timeout, after successful tests, problem in nox and  CodeCov (beginning to think CodeCov has issues on F30)
Build 103:  one test failed due to cache cleaning and package install that the test appears not to allow for. However again failure due to timeout, after tests report, as if problem is launching CodeCov

**Comment by dmurphy18** [comment]
seeing similar issue with CodeCov not starting on Fedora 29 too, see build 112 http://jenkinsci.prod.pdx.ci.aws.saltstack.net:8080/job/neon/view/Python3/job/salt-fedora-29-py3/112/console

**Comment by dmurphy18** [comment]
resorting to good known golden image that ran in successful  98 - 100
