### ISSUE TITLE
tests.integration.modules.test_cp.CPModuleTest.test_cache_remote_file

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54130]
### Description of Issue
https://jenkinsci.saltstack.com/job/neon/job/salt-debian-8-py2/110/

**Comment by dmurphy18** [comment]
Failure due to address already in use

00:06:43.343         tests/integration/modules/test_cp.py::CPModuleTest::test_cache_remote_file 
00:06:43.343         -------------------------------- live log call ---------------------------------
00:06:43.343         08:54:43,556 [salt.loaded.int.grains.core                               :2240][ERROR   ][Maintenance-6(1569)] [salt-master/master] Exception during resolving address: [Errno 1] Unknown host
00:06:44.890         08:54:44,981 [salt.loader.127.0.0.1.int.module.cmdmod                   :854 ][ERROR   ][ProcessPayload(5816)] [salt-minion/minion] Command '[u'nginx', u'-c', u'/tmp/salt-tests-tmpdir/tmp7bFSwC/conf/nginx.conf']' failed with return code: 1
00:06:44.890         08:54:44,981 [salt.loader.127.0.0.1.int.module.cmdmod                   :856 ][ERROR   ][ProcessPayload(5816)] [salt-minion/minion] stdout: nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] still could not bind()
00:06:44.890         08:54:44,981 [salt.loader.127.0.0.1.int.module.cmdmod                   :860 ][ERROR   ][ProcessPayload(5816)] [salt-minion/minion] retcode: 1
00:06:44.890         08:54:44,982 [salt.loader.127.0.0.1.int.module.cmdmod                   :1236][ERROR   ][ProcessPayload(5816)] [salt-minion/minion] Command '[u'nginx', u'-c', u'/tmp/salt-tests-tmpdir/tmp7bFSwC/conf/nginx.conf']' failed with return code: 1
00:06:44.890         08:54:44,982 [salt.loader.127.0.0.1.int.module.cmdmod                   :1241][ERROR   ][ProcessPayload(5816)] [salt-minion/minion] output: nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] bind() to 0.0.0.0:51677 failed (98: Address already in use)
00:06:44.890         nginx: [emerg] still could not bind()
00:06:44.890         FAILED

**Comment by dmurphy18** [comment]
Presume issue is due to not all directories in path are created due to use of os.mkdir, replace with os.makedirs to ensure all dirs are created.

dir path /tmp/salt-tests-tmpdir/tmp7bFSwC/conf/nginx.pid

can see no other reason and previous/post builds are successful, can only assume that the initial directory paths are not fully instantiated, using makedirs will ensure that does not occur.

**Comment by dmurphy18** [comment]
PR merged
