### ISSUE TITLE
Missing M2Crypto in Ubuntu salt repository

### ISSUE THREAD

**Issue by mwidera** [saltstack/salt#54135]
### Description of Issue
M2Crypto package isn't shipped via Salt Ubuntu repository, thus is breaks compatibility with Python 3. Ubuntu provides package https://packages.ubuntu.com/xenial/python-m2crypto, but it's only Python 2 compatible.
Given that package is available in similar salt CentOS repository, please provide it also for Ubuntu.

Problem was initially highlighted via Launchpad please see: https://bugs.launchpad.net/ubuntu/+source/m2crypto/+bug/1823026
but due to lack of willingness there, it might be worth to provide it same as in CentOS.

### Steps to Reproduce Issue
Check Salt repositories:
 - CentOS:  https://repo.saltstack.com/yum/redhat/7/x86_64/2019.2/
 - Ubuntu: https://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2/

### Versions Report
Starting form: 2017.7 (First Python 3 supported release) till latest release 2019.2

**Comment by dmurphy18** [comment]
@mwidera Thanks for bringing it to SaltStack's attention. The next point release of Salt (2019.2.1) which is completing final QA, contains v0.33.0 of M2Crypto for Redhat 7 & 8 on Python 3.

I shall endeavor to create a Debian/Ubuntu Python 3 version of M2Crypto for that point release.

Packaging for Python 3 is done in this repo https://github.com/saltstack/salt-pack-py3 (opensourced so contributions always grateful).

This task can be tracked via https://github.com/saltstack/salt-pack-py3/issues/150
Closing this issue since the correct repo to track it on is given above.

**Comment by mwidera** [comment]
@dmurphy18: 
Cool that's really neat! Didn't know there's dedicated repo for that. 
Thanks for correcting and pointing issue to the proper one.
