### ISSUE TITLE
Py2 Crypto failures 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54138]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Crypto/job/salt-centos-7-py2-pycryptodomex/117/

**Comment by dmurphy18** [comment]
Problem is using Python 3.4 on Centos 7 tests

00:06:59.517             pythonversion:
00:06:59.517          - 3
00:06:59.517          - 4
00:06:59.517          - 10
00:06:59.517          - final
00:06:59.517          - 0
00:06:59.517             saltpath:

This needs to be Python 3.6 before looking at any issues. 
This is blocked until the Centos 7 testing is updated to Python 3.6

**Comment by dmurphy18** [comment]
Failed due to missing Reactor tests, that is the next tests that should have been run were the Reactor tests, for example: from the succeeding successful build 118

00:52:39.685         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
00:52:39.685         Starting Reactor Tests
00:52:39.685         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
00:52:39.685         
00:52:39.685         Running tests...
00:52:39.685         ----------------------------------------------------------------------
00:52:40.063           test_ping_reaction (integration.reactor.test_reactor.ReactorTest) ... OK (0.505s)
00:52:40.063         

Given we didn't even get text output for the Reactor tests, wondering if there is an issue with infrastructure since the last item to running the XML reports

Build 117

00:45:28.262         Generating XML reports...
00:45:28.262         Generated XML report: /tmp/kitchen/testing/artifacts/xml-unittests-output/TEST-integration.output.test_output.OutputReturnTest-20190807104956.xml
00:45:28.262         Finished generating XML reports
06:02:29.920  Cancelling nested steps due to timeout

**Comment by dmurphy18** [comment]
Closing this
