### ISSUE TITLE
 Salt-minion process exits abnormally

### ISSUE THREAD

**Issue by menglong81** [saltstack/salt#54227]
My salt-minion irregular process exit phenomenon caused disconnection from the master, but the log did not display an error message

salt version
```
Salt Version:
           Salt: 2016.3.0
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6
         pygit2: Not Installed
         Python: 2.7.14 (default, Nov 19 2018, 15:39:30)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.2

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-754.12.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

minion config
```
retry_dns: 0
random_master: True
random_reauth_delay: 60
master_failback: True
master_type: failover
master_alive_interval: 60
random_startup_delay: 5
```

![image](https://user-images.githubusercontent.com/12707137/63140798-b1b84300-c015-11e9-82c1-464e4fef4b0e.png)
When the process exits abnormally, the connection with the master is lost, and the minion process is restarted
![image](https://user-images.githubusercontent.com/12707137/63140844-e0ceb480-c015-11e9-9b8e-d7e6eec802f9.png)

There is no valuable information in the log

question:
Why does the process exit abnormally?
![image](https://user-images.githubusercontent.com/12707137/63141388-183e6080-c018-11e9-993d-4d7abb87adf0.png)

**Comment by dmurphy18** [comment]
@menglong81 Salt 2016.3.0 is no longer supported (not even CVE support, that is 2017.7.8) and has not been for some time, can you see if you can duplicate the issue with Salt 2018.3.4 (the oldest under maintenance support) or the latest Salt 2019.2.0 for Redhat 6.

Salt dropped support for Python 2.6 with the release of 2017.7.0 (Python 2.7) on Redhat 6, hence it would help to see if the problem exists with currently versions of supported Salt.  A large number of improvements have been made since Salt 2016.3.0 was released, and the issue you are experiencing may have already been solved.
