### ISSUE TITLE
Doc about saltutil.clear_cache seems wrong

### ISSUE THREAD

**Issue by daks** [saltstack/salt#54403]
### Description of Issue

Quoting documentation about `saltutil.clear_cache` (visible [here](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.clear_cache), [source](https://github.com/saltstack/salt/blob/feee29b6ffb93b90de62fb083b2a85d95fd44265/salt/modules/saltutil.py#L1180) )

> WARNING: The safest way to clear a minion cache is by first stopping the minion and then deleting the cache files before restarting it.

I'm quite sure that this warning is useless and wrong because `clear_cache` can't be run if minion is stopped.

`clear_job_cache` warning looks wrong as well.

I can make a PR to fix this if someone tells me which is the correct way to handle this cache clearing (I did it manually with `rm -fr /var/cache/salt/minion`).

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

not relevant

**Comment by Paulo-Nunes** [comment]
I may be wrong, but I interpreted that warning as saying the safest way to clear the cache is to manually clear the cache on the minion instead of relying on the salt command.

So, you are given a command you can run to clear the minion cache (clear_cache), but the docs say if you want to do it the safest way, log into the minion and delete the cache files with a `rm` command.

**Comment by daks** [comment]
You're right, I misunderstood the doc. I'll close the issue.
