### ISSUE TITLE
Centos 8 pkg hold error yum-plugin-versionlock not installed.

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#54798]
### Description of Issue
On a fresh install Centos 8 with installing packages with `hold: false` results in an error:
[ERROR   ] Cannot proceed, yum-plugin-versionlock is not installed.

My initial thoughts, is that salt is using yum on centos-8 but it should use dnf.

### Setup
packages-formulas
```
54  wanted_pkgs:
1   pkg.installed:
2     - pkgs: {{ wanted_packages | json }}
3     {% if grains['os_family'] not in ['Suse'] %}
4     - hold: false
5     {% endif %}
6     - require:
7       - pkg: pkg_req_pkgs
8       {% if req_states %}
9         {% for dep in req_states %}
10       - sls: {{ dep }}
11         {% endfor %}
12       {% endif %}
13     - retry: {{ packages.retry_options|json }}
```

### Steps to Reproduce Issue
install salt-minion on centos8 and use packages-formula to install list of packages.

### Versions Report

Salt Version:
Salt: 2019.2.1
Dependency Versions:
cffi: 1.11.5
cherrypy: Not Installed
dateutil: 2.6.1
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.10.1
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: 0.33.0
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.6.1
mysql-python: Not Installed
pycparser: 2.14
pycrypto: Not Installed
pycryptodome: Not Installed
pygit2: Not Installed
Python: 3.6.8 (default, Jul  1 2019, 16:43:04)
python-gnupg: Not Installed
PyYAML: 3.12
PyZMQ: 17.0.0
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.2
ZMQ: 4.3.1
System Versions:
dist: centos 8.0.1905 Core
locale: UTF-8
machine: x86_64
release: 4.18.0-80.7.1.el8_0.x86_64
system: Linux
version: CentOS Linux 8.0.1905 Core

**Comment by dmurphy18** [comment]
This looks like working as expected.  yum-plugin-versionlock is not installed by default and Redhat 8 renamed dnf to yum under the covers, can still run all of the dnf commands and some of the dnf functionality did not make it to yum, specifically some of the module stream handling from Fedora 28 which Redhat 8 is based on.  Everything installed fine in my unit tests, but believe QA tested on Centos 8, will check once back in the office on Monday , btw no Centos 8 used in building since only out 17 Sept, all done with Redhat, had it ready since June but the Salt 2019.2.1 test and stabilization effort delayed the support for Redhat 8 being released.

@aboe76 Can you retry with yum-plugin-versionlock installed by hand.  Note yum-plugin-versionlock has never been deliberately packaged by SaltStack for the Redhat family.

Note packaging issues are handled on https://github.com/saltstack/salt-pack-py3

**Comment by dmurphy18** [comment]
From Redhat 8:
[root@localhost david]# yum list | grep versionlock
python3-dnf-plugin-versionlock.noarch                4.0.2.2-3.el8                                            rhel-8-for-x86_64-baseos-rpms    
[root@localhost david]# 


From CentOS 8:
[root@localhost david]# yum list | grep versionlock
python3-dnf-plugin-versionlock.noarch                4.0.2.2-3.el8                                          BaseOS    
[root@localhost david]# 

Looks like salt/salt/modules/yumpkg.py:def _check_versionlock(): Needs updating to allow for Redhat/CentOS 8

**Comment by dmurphy18** [comment]
@aboe76 Thanks for the bug report, had more time to dig into it this morning.  Have everything we need from you.

**Comment by jodok** [comment]
same issue here. any progress? thanks!
