### ISSUE TITLE
Yanked 2019.2.1 Ubuntu repo breaks python3-m2crypto

### ISSUE THREAD

**Issue by cheald** [saltstack/salt#54994]
### Description of Issue

`latest` used to point to 2019.2.1, but was recently redirected to 2019.2.0 due to issues in 2019.2.1, per [the banner message](https://repo.saltstack.com). This breaks attempts to install the python3-m2crypto package:

Exists: https://repo.saltstack.com/py3/ubuntu/18.04/amd64/archive/2019.2.1/pool/main/m/m2crypto/

Does not exist: 
* https://repo.saltstack.com/py3/ubuntu/18.04/amd64/2019.2/pool/main/m/m2crypto/

```
root@az-ops1:~# apt-cache showpkg python3-m2crypto
Package: python3-m2crypto
Versions:
0.31.0-6 (/var/lib/apt/lists/repo.saltstack.com_py3_ubuntu_18.04_amd64_latest_dists_bionic_main_binary-amd64_Packages)
 Description Language:
                 File: /var/lib/apt/lists/repo.saltstack.com_py3_ubuntu_18.04_amd64_latest_dists_bionic_main_binary-amd64_Packages
                  MD5: 008b98d28832b4ee63d25ccaed126efd


Reverse Depends:
Dependencies:
0.31.0-6 - python3 (3 3.7) python3 (2 3.6~) python3:any (2 3.3.2-2~) libc6 (2 2.14) libssl1.1 (2 1.1.1) m2crypto-doc (0 (null))
Provides:
0.31.0-6 - python3.6-m2crypto (= ) m2crypto (= )
Reverse Provides:
```
But it fails to install due to it actually missing:

```
root@az-ops1:~# apt install python3-m2crypto
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'apt autoremove' to remove it.
Suggested packages:
  m2crypto-doc
The following NEW packages will be installed:
  python3-m2crypto
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 169 kB of archives.
After this operation, 908 kB of additional disk space will be used.
Err:1 https://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic/main amd64 python3-m2crypto amd64 0.31.0-6
  404  Not Found [IP: 13.224.51.44 443]
E: Failed to fetch https://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest/pool/main/m/m2crypto/python3-m2crypto_0.31.0-6_amd64.deb  404  Not Found [IP: 13.224.51.44 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by dmurphy18** [comment]
@cheald python3-m2crypto was only introduced (backported) for Salt 2019.2.1, it did not exist in 2019.2.0, hence not added back to that version since it did not exist at that point in time.

There is no python3-m2crypto for Ubuntu 16.04 as was unable to backport it to Ubuntu 16.04 successfully.  Similarly ran into issues backporting to Debian 10 (available from Debian testing, sid).

Will attempt to backport to Ubuntu 16.04 and Debian 9 and 10 in the future, however have some other fires to put out so cannot give a timeline as to when that will occur.  Apologizes about the pulling of and replacing Salt 2019.2.1, hopefully 2019.2.2 shall be released very soon and this can be put in the past.

**Comment by cheald** [comment]
Understood. I was thrown for a loop as I'd wired up python3 installs for all our 18.04 boxes, and suddenly found it broken on the python3-m2crypto dependency. I've just updated the apt list to the explicit 2019.2.1 repo for now, and will deal with the sharp edges until 2019.2.2 lands.
