### ISSUE TITLE
m2crypto-0.31.0-3.el7.x86_64.rpm - Package does not match intended download.

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#55012]
Hi,

I have this error on all my system, when using this repository https://repo.saltstack.com/yum/redhat/7/x86_64/latest/

I tried to clean all the yum's metadata but still not working.

Is there a problem on the official yum repository ?

Best regards

**Comment by dmurphy18** [comment]
@Poil The error output would be helpful.  There have been no issues reported with downloading m2crypto.  Just check with upcoming m2crypto from Salt 2019.2.2

root@localhost:~# yum list m2crypto
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.den.host-engine.com
 * extras: mirror.den01.meanservers.net
 * updates: mirror.tocici.com
Available Packages
m2crypto.x86_64                                            0.31.0-4.el7                                             salt-latest
root@localhost:~# yum install m2crypto
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.den.host-engine.com
 * extras: mirror.den01.meanservers.net
 * updates: mirror.tocici.com
base                                                                                                    | 3.6 kB  00:00:00     
extras                                                                                                  | 2.9 kB  00:00:00     
salt-latest                                                                                             | 2.9 kB  00:00:00     
updates                                                                                                 | 2.9 kB  00:00:00     
Resolving Dependencies
--> Running transaction check
---> Package m2crypto.x86_64 0:0.31.0-4.el7 will be installed
--> Processing Dependency: python2-typing for package: m2crypto-0.31.0-4.el7.x86_64
--> Running transaction check
---> Package python2-typing.noarch 0:3.5.2.2-4.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================================
 Package                          Arch                     Version                         Repository                     Size
===============================================================================================================================
Installing:
 m2crypto                         x86_64                   0.31.0-4.el7                    salt-latest                   287 k
Installing for dependencies:
 python2-typing                   noarch                   3.5.2.2-4.el7                   salt-latest                    39 k

Transaction Summary
===============================================================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 326 k
Installed size: 1.6 M
Is this ok [y/d/N]: y
Downloading packages:
(1/2): python2-typing-3.5.2.2-4.el7.noarch.rpm                                                          |  39 kB  00:00:00     
(2/2): m2crypto-0.31.0-4.el7.x86_64.rpm                                                                 | 287 kB  00:00:00     
-------------------------------------------------------------------------------------------------------------------------------
Total                                                                                          447 kB/s | 326 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python2-typing-3.5.2.2-4.el7.noarch                                                                         1/2 
  Installing : m2crypto-0.31.0-4.el7.x86_64                                                                                2/2 
  Verifying  : python2-typing-3.5.2.2-4.el7.noarch                                                                         1/2 
  Verifying  : m2crypto-0.31.0-4.el7.x86_64                                                                                2/2 

Installed:
  m2crypto.x86_64 0:0.31.0-4.el7                                                                                               

Dependency Installed:
  python2-typing.noarch 0:3.5.2.2-4.el7                                                                                        

Complete!
root@localhost:~# 


Happened to have it to hand, since just finished unit testing it before going to QA.  Essentially same as that available from regular repo.

Retried with current latest
root@localhost:~# yum clean all
Loaded plugins: fastestmirror, langpacks
Cleaning repos: base extras salt-latest updates
Cleaning up list of fastest mirrors
root@localhost:~# yum list m2crypto
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
 * base: mirrors.ocf.berkeley.edu
 * extras: repos.forethought.net
 * updates: mirror.fileplanet.com
base                                                                                                    | 3.6 kB  00:00:00     
extras                                                                                                  | 2.9 kB  00:00:00     
salt-latest                                                                                             | 2.9 kB  00:00:00     
updates                                                                                                 | 2.9 kB  00:00:00     
(1/5): extras/7/x86_64/primary_db                                                                       | 152 kB  00:00:00     
(2/5): base/7/x86_64/group_gz                                                                           | 165 kB  00:00:00     
(3/5): salt-latest/x86_64/primary_db                                                                    |  40 kB  00:00:00     
(4/5): base/7/x86_64/primary_db                                                                         | 6.0 MB  00:00:00     
(5/5): updates/7/x86_64/primary_db                                                                      | 1.9 MB  00:00:00     
Available Packages
m2crypto.x86_64                                            0.31.0-3.el7                                             salt-latest
root@localhost:~# yum install m2crypto
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.ocf.berkeley.edu
 * extras: repos.forethought.net
 * updates: mirror.fileplanet.com
Resolving Dependencies
--> Running transaction check
---> Package m2crypto.x86_64 0:0.31.0-3.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================================
 Package                     Arch                      Version                            Repository                      Size
===============================================================================================================================
Installing:
 m2crypto                    x86_64                    0.31.0-3.el7                       salt-latest                    287 k

Transaction Summary
===============================================================================================================================
Install  1 Package

Total download size: 287 k
Installed size: 1.4 M
Is this ok [y/d/N]: y
Downloading packages:
m2crypto-0.31.0-3.el7.x86_64.rpm                                                                        | 287 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : m2crypto-0.31.0-3.el7.x86_64                                                                                1/1 
  Verifying  : m2crypto-0.31.0-3.el7.x86_64                                                                                1/1 

Installed:
  m2crypto.x86_64 0:0.31.0-3.el7                                                                                               

Complete!
root@localhost:~# 

See no issue there either .

**Comment by Poil** [comment]
Hi,

Thanks for you analyse, I have no more problem this morning, dunno why ...

Best regards,
