### ISSUE TITLE
the way to check if minion is doing nothing

### ISSUE THREAD

**Issue by saltpicker** [saltstack/salt#55022]
Hey,

This problem still exists and its annoying: https://github.com/saltstack/salt/issues/54021
Restart of the salt minion do the job and all is working fine after.

It is possible to check if minion is doing something somehow?
I would like to schedule a minion restart, but i don't want to kill the running jobs.

Thanks you.

**Comment by rares-pop** [comment]
I don't think that would be enough, because something can be dispatched and executed after your check, but before the actual restart.

Probably you would want something more like 'restart if nothing in progress'

**Comment by garethgreenaway** [comment]
@saltpicker Thanks for the report.  You can see if there are jobs active on the minions using the jobs runner, https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.jobs.html.  You could also look at the `state.running` function which will tell you if any states are running.  The `state.disable` function will disable state runs so you can safely restart the job.

**Comment by arizvisa** [comment]
@saltpicker, you can also use `saltutil.running` on your minion to list all of the currently running processes on that particular minion.

**Comment by max-arnold** [comment]
If you only care about not interrupting `state.sls` or `state.higstate` jobs, then it may be possible to restart a minion by queueing another state run: `salt MINION state.apply a_state_to_restart_the_minion queue=True`. This approach is possible because by default Salt prevents multiple state calls from being run at the same time, and the `queue=True` argument allows to run them sequentially.

Another option to explore is minion blackout: https://docs.saltstack.com/en/latest/topics/blackout/

**Comment by saltpicker** [comment]
Thanks for the suggestions.
This is a workaround because it is a deeper problem i think.

I am talking about this: https://github.com/saltstack/salt/issues/54021

Thank you.

**Comment by arizvisa** [comment]
Wrt issue #54021: When running a command with salt (without the `--async` parameter), the salt client simply issues the job to each minion, and then watches the salt bus for a period of time until each minion responds. That's why the timeout is suggested to be increased if you're issuing single-instance jobs via the client and want to see an immediate result.

In situations where you don't want to sit around and watch the bus waiting for responses from all your minions (because you have more important work to do), the returner/job api can be used so that your minions will just return their results whenever they're done. If you issue your jobs with `--async` you can just use that jid to view your status, or anything in `job.*` to see what's running.
That's the best place to see what jobs you've executed and the higherlevel state that they're in.

I'm no saltstack developer, but I think choosing a good returner is pretty key for jobs that can take an arbitrary amount of time against an arbitrary number of hosts.

**Comment by saltpicker** [comment]
Yes and no.
Because when i'm targeting fe. salt '*' (around 1600 hosts) all is working fine.
But i if use more complicated syntax with for example - compound match (matches around 500-600), even timeout does not help.

And one more thing... there is a situation when the same hosts are timeouting.
But if restart the salt-minion and supply the command again (by using the same compund match) all is fine.

Its look like long running minion takes more time to "do something" and it timeouts after.
After restart all is ok, no timeout for couple of days.
