### ISSUE TITLE
salt minion cann't be started

### ISSUE THREAD

**Issue by kussatom** [saltstack/salt#55139]
### Description of Issue
when i restart the windows server,then  the salt-minon  start-up failed
i try to uninstall the salt-minion, reinstall  it ,but the problem  still exist

debug  logs:

Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 184, in salt_minion
    import salt.cli.daemons
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 48, in <module>
    import salt.utils.parsers
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 27, in <module>
    import salt.config as config
  File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 27, in <module>
    import salt.utils.network
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 24, in <module>
    import wmi
  File "C:\salt\bin\lib\site-packages\wmi.py", line 157, in <module>
    obj = GetObject ("winmgmts:")
  File "C:\salt\bin\lib\site-packages\win32com\client\__init__.py", line 72, in GetObject
    return Moniker(Pathname, clsctx)
  File "C:\salt\bin\lib\site-packages\win32com\client\__init__.py", line 87, in Moniker
    moniker, i, bindCtx = pythoncom.MkParseDisplayName(Pathname)
pywintypes.com_error: (-2147217406, 'OLE error 0x80041002', None, None)

### Setup
nothing special ,only master ip  and minion id ,

### Versions Report
Salt-Minion-2019.2.0-Py3-AMD64-Setup.exe

**Comment by frogunder** [comment]
@kussatom Thank you for reporting this issue.

I am not able to replicate it. I do not see what you are describing, at least not on my 2019 Server.
What version of Windows did you see this on?
Can we see the full output of versions report?

@saltstack/team-windows Do you have any thoughts on this?

**Comment by xeacott** [comment]
Let me check this out tomorrow morning...

**Comment by arizvisa** [comment]
@kussatom, what user are running salt as?

That error code, `0x80041002` is `WBEM_E_ACCESS_DENIED` which means that saltstack is unable to query WMI. This could be a permissions issue or a dead `wbemsvc`. One way to proceed here is to ensure that we can query WMI with something other than salt.

There's a number of ways to do this:
- You can use `wbemtest` if you're familiar with WMI
- Otherwise you can try running `wmic COMPUTERSYSTEM` at your cmd prompt to ensure that you can query `Win32_ComputerSystem` at least..
- This is happening during the import of the `wmi` module, so if you run the Python executable inside `/salt/bin/python.exe` (or somewhere in there) and then type in `import wmi` you should see the error (or not).

If all of these are successful, then there might be an issue with salt not enabling COM. But then we'd all likely have that problem. ;-) So plz let us know if they are! :)

**Comment by arizvisa** [comment]
Also.. logs for the wbem service (if it comes to this) can be found at `%windir%\System32\Wbem\Logs\Setup.log`

**Comment by arizvisa** [comment]
This issue is racy and related to #54869 as its related to COM not being initialized
