### ISSUE TITLE
Misleading error logged in boto_ec2

### ISSUE THREAD

**Issue by nnsense** [saltstack/salt#55338]
### Description of Issue

With reference to [this line](https://github.com/saltstack/salt/blob/9edcfab3f3a808724c75a6fdeb5cf910e20f3391/salt/modules/boto_ec2.py#L1062): on AWS there are indeed 2 reservations, but the first one is being used 'behind the curtain' and it's quite rare while the second one is related billing and almost everywhere on internet.

In this case, by saying that the 'Instance could not be reserved' when the instance cannot be created (the error arise when boto, for any reason, fails to return the instance id) is confusing.

**Comment by cmcmarrow** [comment]
Hello @nnsense `log.warning('Instance could not be reserved')` is a warring for developers. The warning is being logged because aws did not give back a instance. In this case the instance is really to tool that lets us talk to the AWS box. This lets use see if the box is pending, running or has failed etc...
  
If we don’t get back a instance odds are the box was never made but we can’t say that with 100%. Also typically even if AWS could not make a box it would still give back a instance. So the warning is not just implying the box was not made but also something else went wrong.

If you want to put in a pull request to change the warning to ‘Did not get box Instance’ you may.

**Comment by nnsense** [comment]
Yes, I was just speaking more about terminology. I will review the code and put a pull request, the error can be made more helpful adding variables instance_run had. Thanks :)
