### ISSUE TITLE
AttributeError: module 'azure.storage' has no attribute 'BlobService'

### ISSUE THREAD

**Issue by pycode122** [saltstack/salt#55849]
im trying to provision vms in azure using salt-cloud.
but ending up with below error while creating container on storage_accounts
..............................................................................
All packages installed as per prequesites in salt docs.
https://docs.saltstack.com/en/latest/topics/cloud/azure.html
...............................................................................
error:

[ERROR ] There was an error running the function: module 'azure.storage' has no attribute 'BlobService'
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/salt/cloud/clouds/msazure.py", line 2567, in list_storage_containers
storage_conn = get_storage_conn(conn_kwargs=kwargs)
File "/usr/lib/python3/dist-packages/salt/cloud/clouds/msazure.py", line 2490, in get_storage_conn
return azure.storage.BlobService(storage_account, storage_key)
AttributeError: module 'azure.storage' has no attribute 'BlobService'
....................................................................................
even azurearm didnt help, its throwing below error

The cloud driver, 'azurearm', configured under the 'my-azure-config' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'azurearm' driver.
......................................................................................

**Comment by Ch3LL** [comment]
what version of salt are you seeing this in?

looks like azure-storage v0.30.0 they changed the `BlobService` attribute to `BlockBlobService`, `AppendBlobService` and so forth. If you install a version less then v0.30.0 it should work.

**Comment by pycode122** [comment]
@Ch3LL  thanks for your response.
I have tried with azure-storage v0.20.0 as well, but facing same error.

any help would be appreciated.

**Comment by pycode122** [comment]
@Ch3LL @SaltStackSupport  salt team..may i have some help on fixing this issue.

**Comment by Ch3LL** [comment]
looking into this a bit more, it looks like we are accessing that object incorrectly in the code:

```
In [4]: from azure.storage import blob

In [5]: blob.BlobService
Out[5]: azure.storage.blob.blobservice.BlobService
```

instead of `azure.storage.BlobService`.


The `msazure` cloud provider is used to access the old azure api so I'm not sure we even still want to support this and instead want to only support the azurearm cloud provider. ping @saltstack/team-cloud any opinions here? Im guessing we want to actually deprecate the old msazure cloud provider since i dont believe azure plans on supporting it going forward.


@pycode122 you did mention that you did try the `azurearm` cloud provider and it gave you this error:

```
The cloud driver, 'azurearm', configured under the 'my-azure-config' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'azurearm' driver.
```

Can you show the output from `pip list |grep -i azure` so i can see if you have all hte required dependencies. im guessing there is one missing.

**Comment by nicholasmhughes** [comment]
@Ch3LL , correct... the `msazure` driver should just go away.

**Comment by Ch3LL** [comment]
ping @pycode122 any luck setting up azurearm?
