### ISSUE TITLE
Only run doc tests on prs with "Documentation" as a label

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#56548]
https://github.com/saltstack/salt/pull/56547 was an initial idea, @s0undt3ch says we should still run all distros, but only documentation related tests when it's a "Documentation" pr.

**Comment by s0undt3ch** [comment]
The reason for still running on All platforms is because we would have to either set the builds that didn't run as passing or we would have to merge with failing builds(those that didn't build docs).
The alternative would be to disable the required commit statuses for any other platform that didn't run doc tests, which could mean that, for non doc builds, if a build was still in Jenkins queue and not being built, the pull request would show as passing instead of showing as pending because there's still one required build that needs to pass.

If we run on all platforms, but only doc related tests, we don't have to mess with commit statuses and the build times will be way shorter.

This is pending pytest landing on master so we can pass a test selection filter to only run doc tests.

**Comment by Ch3LL** [comment]
I'm pretty sure is complete right @s0undt3ch

**Comment by s0undt3ch** [comment]
Yep, that's correct.
