### ISSUE TITLE
[BUG] saltstack 2019.2 ubuntu 18.04 repo broken due to hash sum mismatch

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#56992]
**Description**
Since a few hours ago, the ubuntu 18.04 repository for SaltStack 2019.2 does not work

**Setup**
A clean ubuntu 18.04 machine.

**Steps to Reproduce the behavior**
Run the first two commands from the repo configuration guide:
https://repo.saltstack.com/2019.2.html#ubuntu
While performing the third step: "sudo apt-get update" the following error will appear:
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2/dists/bionic/main/binary-amd64/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:3348 [weak]
    - SHA256:26ba314d36f27e09e958b8334f890fd6952797c6e5ff7e76e2a71267d247931f
    - SHA1:b20bfd445185dfad53e57ad528cb988c2b8c5af7 [weak]
    - MD5Sum:e019bd398e8e0f1e2d27bcacbde6d295 [weak]
   Hashes of received file:
    - SHA256:d38779987d34b860c5b26d4d698856e7976968f35e9a62594b0fdf0db38dc748
    - SHA1:cbe0439854c438be087d073b1e74692d33db0776 [weak]
    - MD5Sum:66b8b9314839ce48bf0de47e14f24221 [weak]
    - Filesize:3348 [weak]
   Last modification reported: Wed, 29 Apr 2020 20:37:44 +0000
   Release file created at: Wed, 08 Jan 2020 01:23:40 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Expected behavior**
apt-get update should be successful

**Screenshots**
-

**Versions Report**
-

**Additional context**
-

**Comment by daisyzhou** [comment]
I haven't reproduced this on a clean machine, but on production machines we're definitely also running into the same hash mismatch for the same package.

**Comment by dmurphy18** [comment]
@blankspace923 The repo is currently being sync'd for point releases 2019.2.4 and 3000.2 and what usually takes less than 15 minutes has been now going for 5h5m and is at 98% (been that for a while).

Hopefully the sync'ing should finish soon and normal service be restored.
The issue will be under review and investigation as to what occurred to basically sync all releases rather than just point releases 2019.2.4 and 3000.2, but with it almost complete, it is better to just let it run its course

Apologies for the interruption in service

**Comment by blankspace923** [comment]
Thanks for the quick answer. Please send us an update when the sync is done so we can test it on our end :)

**Comment by dmurphy18** [comment]
checkout https://saltstackcommunity.slack.com/archives/C8E7RJCPN
There are a number of people waiting for it to be announced in there.

**Comment by sagetherage** [comment]
Repo.saltstack.com is sync'd now please review.
