### ISSUE TITLE
bug #51797 not fixed because #51838 is not merged into main

### ISSUE THREAD

**Issue by maznu** [saltstack/salt#57060]
**Description**
Please re-open #51797, or better yet merge in #52631, because salt's netbox module is still broken:

```
# salt-call netbox.get_interfaces example.com

Passed invalid arguments: '<' not supported between instances of 'dict' and 'dict'.
```

**Versions Report**

This is a bug on 3000.2:

<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 3.4.1
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.5 (default, Apr 19 2020, 20:18:17)
   python-gnupg: 0.4.3
         PyYAML: 5.1.2
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: Ubuntu 19.10 eoan
         locale: UTF-8
        machine: x86_64
        release: 5.3.0-46-generic
         system: Linux
        version: Ubuntu 19.10 eoan
```
</details>

Same story on SaltStack's own packages of 2019.2.4 released just a few days ago.

**Additional context**
It has been a year since this PR was submitted, and almost a year since #51797 has been marked as fixed without the one line patch merged into the main tree.

All it needs is: https://github.com/saltstack/salt/pull/52631/commits/eeb158a5e7d8d3b81f5eb46489770e72a1c86c72

**Comment by waynew** [comment]
Hi @maznu, thanks for the report! I went ahead and re-opened that issue. Would you be interested/able to port https://github.com/saltstack/salt/pull/52631 to master? It looks like it needs both that change, and a test that confirms the change.

Looks like it would be a relatively simple test to add - if you're unsure about writing tests, I'll be streaming tests on our [twitch stream](https://www.twitch.tv/saltstackinc) tomorrow afternoon (America time). 

I would just write a test that patches `__utils__` and ensures that a list of dictionaries comes back properly instead of exploding. Probably 2-3 tests are all you would need to ensure that it's well-tested.

**Comment by waynew** [comment]
I guess I can close this issue, since this issue was just that #51797 needs to be re-opened (BTW, if nobody responds to a comment on the GH issue, feel free to ping folks in #salt on freenode or #develop on the community Slack)
