### ISSUE TITLE
Offer SaltStack repo for Fedora

### ISSUE THREAD

**Issue by thekabal** [saltstack/salt#57126]
**Is your feature request related to a problem? Please describe.**
With CVE-2020-11651 and CVE-2020-11652, we are seeing a many-day delay for Fedora to package an updated/patched version of SaltStack. Since https://repo.saltstack.com/#fedora tells users to use the fedora repo for SaltStack, there is no 'clean' path for them to upgrade. (They'd need to use Python/pip to install instead, which uses different paths and configs)

**Describe the solution you'd like**
Much like the SaltStack repo's offered for RedHat 7 & 8, SaltStack should also package for Fedora, and offer a repo for them.

**Describe alternatives you've considered**
As a Fedora user, I tried upgrading via dnf/yum, but there was no update available. I checked the CVE today (May 7th) and it does not show progress from RH/Fedora for this CVE. I tried upgrading via Python/pip, but ended up with substantially different path locations and configurations and in some cases errors as a result of mismatching libraries until I removed those as well.

**Comment by dmurphy18** [comment]
@thekabal Currently SaltStack povides Salt packages into Fedora and they take caring of testing, signing, etc.  This significantly reduces the burden on duplication of a bleeding edge environment.
SaltStack typically does not create packages for non-production environments, of which Fedora is considered one, similarly SaltStack does not create packages for non-LTS Ubuntu releases.

SaltStack provides packaging into Fedora as an exception since it is a pre-cursor as to where Redhat  is typically headed.  Currently a new point release is being developed for release Wednesday 13th May 2020, and updated Fedora packages will be created on that day once the release is available on PyPI.  Fedora complains if package other than tar-balls available from PyPi.

Hence has Fedora is a non-production OS, SaltStack currently has no plans to create a repository solely for Fedora and will rely on Fedora's repositories.

Patches have not been created for Fedora unlike other environments and older releases and I shall bring this over-sight up in internal meetings, however  the community has already supplied some, thanks @rossengeorgiev .  Being somewhat burden with the CVE and accommodating production environments.

Closing this issue, please re-open if there are other points which you want ro raise.

**Comment by thekabal** [comment]
https://access.redhat.com/security/cve/cve-2020-11652 now shows that RedHat / Fedora has marked this CVE as "Won't fix".

What is the official suggestion from SaltStack for Fedora users? The Python install package seems to be the only patched version, and it installs in different locations and with different settings than the original Fedora package.

**Comment by terminalmage** [comment]
> https://access.redhat.com/security/cve/cve-2020-11652 now shows that RedHat / Fedora has marked this CVE as "Won't fix".

Maybe I'm misreading, but that page only seems to say this is "Won't fix" for `Red Hat Ceph Storage 2`. Not Fedora.

> What is the official suggestion from SaltStack for Fedora users? The Python install package seems to be the only patched version, and it installs in different locations and with different settings than the original Fedora package.

Uhh... install from the upstream repos?

```
% docker run --rm -it fedora:31 dnf info salt-master
Fedora Modular 31 - x86_64                      3.5 MB/s | 5.2 MB     00:01
Fedora Modular 31 - x86_64 - Updates            3.7 MB/s | 4.1 MB     00:01
Fedora 31 - x86_64 - Updates                     10 MB/s |  25 MB     00:02
Fedora 31 - x86_64                               16 MB/s |  71 MB     00:04
Last metadata expiration check: 0:00:01 ago on Tue May 19 15:10:02 2020.
Available Packages
Name         : salt-master
Version      : 3000.2
Release      : 1.fc31
Architecture : noarch
Size         : 3.0 M
Source       : salt-3000.2-1.fc31.src.rpm
Repository   : updates
Summary      : Management component for salt, a parallel remote execution system
URL          : http://saltstack.org/
License      : ASL 2.0
Description  : The Salt master is the central server to which all minions
             : connect. Supports Python 3.
```

**Comment by rossengeorgiev** [comment]
If you look at https://apps.fedoraproject.org/packages/salt the current release is now `3000.2` with `3000.3` being in testing.

**Comment by carlwgeorge** [comment]
> we are seeing a many-day delay for Fedora to package an updated/patched version of SaltStack

Fedora isn't some magically entity that spits out package updates.  Fedora is a community, and relies on that community to get things done.  The [salt package in Fedora](https://src.fedoraproject.org/rpms/salt) is maintained by @dmurphy18 and @terminalmage.  For the scope of the salt package, they *are* Fedora.  If they are having issues keeping the package up to date, they should reach out to the [Fedora devel mailing list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/) to see if other Fedora packagers are interested in co-maintaining the package.

> does not show progress from RH/Fedora for this CVE

As detailed in the Red Hat CVE notices ([CVE-2020-11651](https://access.redhat.com/security/cve/cve-2020-11651) and 
[CVE-2020-11652](https://access.redhat.com/security/cve/cve-2020-11652)), this package was only ever shipped as part of Red Hat Storage Console 2, which is already end of life.  That is why it's labeled as "will not fix".  Red Hat is not responsible for updating the Fedora or EPEL salt packages.

> SaltStack typically does not create packages for non-production environments, of which Fedora is considered one, similarly SaltStack does not create packages for non-LTS Ubuntu releases.

There are companies, organizations, and users that use Fedora and non-LTS Ubuntu in production.  It's fine for Saltstack to say "we don't make packages for those", but it's unnecessary to denigrate those distros by calling them "non-production".

I also want to point out here that the EPEL packages for Salt are vulnerable to the CVEs.  They are still on version 2015.5.10, and haven't been modified since 2016.  I understand that Saltstack would prefer users to subscribe to their RHEL/CentOS repositories, but EPEL is the standard community repository for RHEL/CentOS.  Many users prefer to use packages from there instead of adding another third party repository.  Regardless of that, one of three things needs to happen to the EPEL packages.

1. Backport security fixes to them.
2. Update them to a non-vulnerable version by following the [incompatible upgrades policy](https://fedoraproject.org/wiki/EPEL_incompatible_upgrades_policy).
3. [Retire](https://fedoraproject.org/wiki/How_to_remove_a_package_at_end_of_life) them.

**Comment by carlwgeorge** [comment]
For those that would like to follow along, here are the open bugzillas for salt in Fedora and EPEL that include the string "CVE" in the summary.  If you have a bugzilla account you can CC yourself on each one to get email notifications.

https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&component=salt&product=Fedora&product=Fedora%20EPEL&query_format=advanced&short_desc=CVE&short_desc_type=allwordssubstr

**Comment by thekabal** [comment]
I'm thrilled to see updated versions hitting Fedora now. As of a few days ago, it wasn't available. I also cc'd (added myself) to the multiple Bugzillas for the CVE's, which conveniently did not mention the updated packages. The "build" page under the apps.fedora... link also doesn't work.

Regardless! I'm happy with the end result - a patched, updated version available for Fedora. Thank you all!

**Comment by carlwgeorge** [comment]
> which conveniently did not mention the updated packages

That's because no bugs were associated with the [update](https://bodhi.fedoraproject.org/updates/FEDORA-2020-43cd31fba0).  When those are submitted the maintainer has the option to check boxes for any bugzillas that will be resolved by it, and then those bugzillas get automatic comments about the updated packages moving to the testing and then stable repos.  If the maintainer doesn't check the boxes, then they should manually comment and close bugzillas as needed.

> The "build" page under the apps.fedora... link also doesn't work.

The builds tab works for me, and shows a list of the builds in the build system.  What isn't working?
