### ISSUE TITLE
[FEATURE REQUEST] ip virtual module for SUSE operating systems

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#57517]
**Is your feature request related to a problem? Please describe.**
Lack of virtual ip module for SUSE operating systems.

**Describe the solution you'd like**
Addition of a suse_ip module.

**Describe alternatives you've considered**
I've written a module using the rh_ip and debian_ip modules as templates and can create a pull request if desired.

**Additional context**
This is my first contribution to an open source project (eep!). Hope I'm doing it right!

**Comment by thelande-kla** [comment]
@dmurphy18 Thanks for the guidance. I'll take care of creating the PR.

SUSE uses different variables, values, and configuration formats versus RedHat, not to mention different file locations (`/etc/sysconfig/network` vs. `/etc/sysconfig/network-scripts`). For example, SUSE uses `STARTMODE` vs. `ONBOOT` and `PREFIXLEN` vs. `PREFIX`. RH also seems to place DNS settings in the device configuration files while SUSE centralizes them. I felt it made more sense to create a separate module rather than trying to if/else much of the `rh_ip` code.

**Comment by whytewolf** [comment]
this is now 3 years old and i don't see a PR mentioned. as this isn't something we are likely to work on directly, SuSE maintains most of their own modules for salt. I'm going to go ahead and close this. If a PR is submitted later feel free to open a new ticket and link the pr.
