### ISSUE TITLE
[BUG] Beacon Watchdog doc is missing from Salt 3000.3

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#57547]
**Description**
The documentation for watchdog is here https://docs.saltstack.com/en/master/ref/beacons/all/salt.beacons.watchdog.html#module-salt.beacons.watchdog

Note that it is missing from 20192.5 and 3000.3 documentation, when searching for it.
It used to be in the older  documentation, and the functionality has been there for some significant time and was in the 2018.3 documentation too.

**Comment by dmurphy18** [comment]
@saltstack/docs-working-group FYI

**Comment by ScriptAutomate** [comment]
This has been properly added and present now in the `3001` documentation. It is in `master`, `3001`, and should be included in new releases going forward.

It is still not present in the `3000.x` documentation, but because this documentation is within a docstring and older documentation is locked after the latest non-CVE-related point releases, it won't be updated for this branch `3000.x`. This is my understanding of how the documentation is managed, especially with docstrings.

I think whenever this issue was introduced, something like [blackening salt](https://github.com/saltstack/salt/commit/0b2a5613b345f17339cb90e60b407199b3d26980#diff-4e0d70ea7519525e805a30333c7fe4fc) may have resolved it in `master`, and must have re-introduced the documentation properly so it was included when `3001` was released.
