### ISSUE TITLE
Exception/Error catch on sls include statement

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#57542]
I have the following dynamic include block:
```
include:
{% for file_to_include in include_list %}
  - {{ file_to_include }}
{% endfor %}
```

The sls will fail if one of the include files are missing.
Is there a way to `catch` (expect) the exception so the rendering and the salt run will not fail, i.e it will just skip this `include`.

for example:
```
{% for file_to_include in include_list %}
try:
    include:
      - {{ file_to_include }}
except error_of_some_type:
    pass
{% endfor %}
```

In that note, is it possible to call include several times across a sls file?
meaning:
```
include:
  - sls: some.path.to.sls1
***more sls code here***
include:
  - sls: some.path.to.sls2
***more sls code here***
```

**Comment by OrangeDog** [comment]
I'm sure this has been a feature request for ages, but probably got staled at some point.

**Comment by dmurphy18** [comment]
Closing this as will not implement feature request.
The issue was discussed in the core team planning meeting and it was decided to not implement the requested functionality, as that too many changes would have to be implemented in Jinja2 and YAML and it would be a departure from Jinja2 and YAML functionality that Salt did not want to support.

If Jinja2 and YAML should ever support this functionality, then Salt would revisit the issue of supporting the requested feature.
