### ISSUE TITLE
[FEATURE REQUEST] Older versions of python modules for Windows

### ISSUE THREAD

**Issue by berkut-174** [saltstack/salt#57695]
**Is your feature request related to a problem? Please describe.**
What is the reason for using old versions of python modules when building .exe:
https://github.com/saltstack/salt/blob/master/pkg/windows/req.txt
https://github.com/saltstack/salt/blob/master/pkg/windows/req_pip.txt
https://github.com/saltstack/salt/blob/master/pkg/windows/req_win.txt
?
I checked, the assembly passes correctly with the latest versions of these modules.

**Describe the solution you'd like**
I would like to see the latest versions of these modules.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by arizvisa** [comment]
Some things to keep in mind are that some modules are binary and don't have recent wheels which means they'll require a compile. (#57740 is an exmaple, although these ones specifically are optional).

There's also been history with some issues in core modules like msgpack where the maintainer had introduced a broken change that resulted in saltstack acting pretty awkwardly (and was difficult to troubleshoot iirc). Plus there's the major work that's being done on the tornado module (which is being vendorized at the moment while that particular work is happening). I believe they've been bitten by issues like these numerous times throughout its growth.

At some point if salt decides to vendorize their "core" modules which are relevant to salt working elegantly, it could make sense to start cleaning up the requirements to always use the newer versions (on all platforms). But without that, the devers have to suffer the detriment of maintaining saltstack while the modules they develop upon can break the entire product and result in spending developer effort troubleshooting code outside their scope. The python2<->python3 transition was likely a major hassle too.

Although I would definitely like to see saltstack using newer versions of some of these modules on the Windows platform, at the moment saltstack needs to be pretty conservative with its development resources since saltstack fulfills a pretty important role and thus stability is a huge priority.

**Comment by cmcmarrow** [comment]
@berkut-174 We lock the versions because if a new version of a module gets released and someone pip installs on to a box the behavior might change or a break will happen that wont occur on older Minions running the same version of Salt. Also some 3rd party modules may not support the newest versions of another 3rd party module that we use. Then you have modules like msgpack which backwards compatibility gets broken a lot. Here you can see my PR that updates it  https://github.com/saltstack/salt/pull/57571.

If there is a module with a new major bug fix/feature/CVE Patch you can always put in a new issues for it explaining why action is need it. Will take a look at it and might even put in a PR for it if its a big problem or the new feature is really cool.

@Shane usually updates as many modules as he can be for the next release. But with so many conflicts and new bugs that come up it can take a lot of time to get all modules updated. So he prioritizes the modules that need to be updated.

To ask for all modules to be updated to the latest version is literally impossible with the version conflicts unless we clone are 3rd party modules and maintain them our selves.

**Comment by twangboy** [comment]
In this case, we should put in the PR to update as many modules as we can early on in the release process so that there is adequate testing. That will allow us to discover conflicts and regressions that may exist in the new versions.
