### ISSUE TITLE
[TEST FAILURE] centos8 py3 slow tests

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#57722]
**Description**

https://jenkinsci.saltstack.com/job/pr-centos8-py3-slow/job/master/225/

**Comment by dmurphy18** [comment]
they have been failing for some time in what appears to be integration shell tests

**Comment by sathieu** [comment]
It looks like py3/centos8 is failing since [build #142](https://jenkinsci.saltstack.com/job/pr-centos8-py3-slow/job/master/142/) ([build #141](https://jenkinsci.saltstack.com/job/pr-centos8-py3-slow/job/master/141/) is successful). Both builds are at the same revision b95213ec903402f25c1e0aeb3990fe8452ab63ce.
