### ISSUE TITLE
Ability to define nodegroups through `master_tops` system

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#5787]
Edit: `master_tops` is probably not the right place for this. I'll repurpose (and retitle) this issue as soon as the storm has left my brain (i.e. "brainstorming is done…").

---

At least with [reclass](http://github.com/madduck/reclass), nodegroups are part of the inventory and thus could easily be made available to Salt, such that I could target commands or states at groups in my inventory.

Instead of defining a new interface (we already have `master_tops` and `ext_pillar` separately, do we want a third?), maybe the `master_tops` interface could be extended to allow the external source to return nodegroups?

I don't have a clear idea of how this would work yet, but if you give a general green light into this direction, I could start looking and evaluating various options. It is possible that the interface would have to be incompatibly changed, unfortunately, but I would document this appropriately and change the existing `tops` plugins.

**Comment by HontoNoRoger** [comment]
+1

**Comment by Galser** [comment]
+1

**Comment by dharmab** [comment]
+1

**Comment by loz-hurst** [comment]
We now do this with ext_pillar to import "group" pillar information based on a custom module that reads the data from a combination of external inventory systems. The addition of ext_pillar_first (available in stable after this bug was filed) means we can target using the "group" from ext_pillar in our pillar files.

In short, for our use case we have a workaround through other developments in salt in the meantime.

**Comment by iavael** [comment]
@loz-hurst 

Unfortunately it doesn't help if there are only ext_pillar sources and one of them provides "groups" list and it's needed to use these groups to target pillars from other sources.

**Comment by loz-hurst** [comment]
@iavael Indeed, which is why I said "for our use case".  It's very much a workaround, not a fix, as we've had to create a single ext_pillar that interfaces with the other ext_pillars (and some sources that we've not bothered to write a proper ext_pillar interface around, since we can't use it direct because of this) so we can cross-reference and cross-use them before using (some of) the information in them to target the pillar_root files.

The functionality to do it properly in salt would be much better than mangling ext_pillar sources via our own hacky interface to get it to work.

**Comment by iavael** [comment]
As a workaround we currently target pillars to nodegroups in the external system. Basically, our internal service that provides nodegroups for state targeting via pillars, also began to provide some actual pillar data that was stored in git.
This solves some of the most painful moments (at least we got rid of bunch of cryptic regexps in pillar top.sls), but this is _very_ kludgy, because targeting mechanism is now outside of saltstack.

**Comment by bbinet** [comment]
Any news on this issue?

Is it normal that I'm not able to target minions using pillar (`salt -I` or `salt -J`) when my pillar data sit exclusively in reclass ext_pillar ?
I don't understand why pillar data coming from ext_pillar could not be used to target minions like any other pillar data? shouldn't it be considered as a bug?

**Comment by iavael** [comment]
@bbinet you can target jobs (via salt -I) and states (via top.sls) by pillar data (including ext_pillar). We successfully ise this in production for several years. You cannot target pillar via top.sls by pillar data.

**Comment by bbinet** [comment]
@iavael it does not work for me for all my minions (version 2019.2.0), but I've just come across issue https://github.com/saltstack/salt/pull/52234 and I think I should upgrade my minions to latest 2019.2.4 which should have the fix.
I've just tried to target an old minion (2018.3.3) with `salt -I` and it does work!
So I think I just need to upgrade, thanks.

**Comment by iavael** [comment]
@bbinet that's strange. We used such targeting since 2017.7. It could be available even earlier, but we didn't use saltstack then yet.
But if it works for you after upgrade, then it's fine, I suppose.

**Comment by whytewolf** [comment]
Is this still an issue? from the last comments on the ticket it sounds like it has been fixed

**Comment by whytewolf** [comment]
closeing this issue. if users are still having issues with this. please test in latest supported version to see if already addressed.
