### ISSUE TITLE
[BUG] Archived salt repo 2017.7 points to the wrong repo URL

### ISSUE THREAD

**Issue by warpnine** [saltstack/salt#57885]
**Description**
When installing https://archive.repo.saltstack.com/yum/redhat/salt-repo-2017.7.el7.noarch.rpm it has the wrong URL in the file etc/yum.repos.d/salt-2017.7.repo that is created by installing this package.

The URL points to repo.saltstack.com instead of the correct archive.repo.saltstack.com

**Setup**
Standard CentOS 7 system with Salt 2017

**Steps to Reproduce the behavior**
yum -y install https://archive.repo.saltstack.com/yum/redhat/salt-repo-2017.7.el7.noarch.rpm
yum -y install salt-minion
Fails to install because it points the wrong repo URL

**Expected behavior**
The repo URL should be correct and it would be able to install the salt packages.

**Screenshots**

**Versions Report**
Salt 2017.7

**Comment by s0undt3ch** [comment]
@dmurphy18 could you please triage this issue?

**Comment by bryceml** [comment]
We decided in the SEP that we would not update those since it would take too much time for something that was already out of support.

We have 2 main options going forward I think.  We could leave them up with the expectation that people sed them afterward with something like

```bash
sed -i 's/repo.saltstack.com/archive.repo.saltstack.com/g' /etc/yum.repos.d/saltstack*.repo
```
We would have to document that somewhere probably.

Option 2 is that we could just delete them when we move the relevant packages to archive.repo.saltstack.com so they don't confuse people.  Afterall, it's just putting down a .repo file and the gpg key which wouldn't be hard for people to script.

**Comment by sagetherage** [comment]
Assigning myself for follow up, here, yes, we likely need some sort of documentation/notificaiton to the user. I will follow up here next week on next steps.

**Comment by ScriptAutomate** [comment]
My PR #57756 may be related, when it comes to a documentation solution. It hasn't been accepted yet. If we want to make additional changes to the PR, when it comes to the install guides (such as post-install commands), I can expand the PR if needed.

**Comment by sagetherage** [comment]
yes, @ScriptAutomate let's add at least some text about the work-around:
> We could leave them up with the expectation that people sed them afterward with something like

`sed -i 's/repo.saltstack.com/archive.repo.saltstack.com/g' /etc/yum.repos.d/saltstack*.repo`

**Comment by ScriptAutomate** [comment]
I have included additional information in the following installation docs, in #57756 :
- Ubuntu
- Debian
- CentOS/RHEL/AmazonLinux
