### ISSUE TITLE
macOS and Windows service states fail to start if disabled, even with enable: true

### ISSUE THREAD

**Issue by weswhet** [saltstack/salt#57908]
**Description**
If you attempt to start a service on macOS or Windows and the service is disabled `service.running` with fail to start the service even if the `enable: true` option is set.

This is caused by the service state wanting to enable a service after it attempts to start the state. On macOS and Windows the service state should attempt to enable a service prior to starting it. 

PR coming soon.

cc @twangboy

**Comment by adcpdk** [comment]
Hi Guys, @weswhet @dwoz 
I am wondering what was the reason reason behind this implementation, is there any Microsoft article that explicitly says that the service MUST be enabled in order to run?
I have a case when service MUST be started manually and 'enable: True' is not a solution, unless I use service.disabled later on or call a service.start module directly from the state.

https://github.com/saltstack/salt/commit/4798babaef859ac39c1499bba12680580cf3e5c4#diff-2f7c8c335ccacbfa84a72e52f66a67fd926e52f221ca9807ad7f7ed3814d0962R517
