### ISSUE TITLE
 [TEST FAILURE] centos8 py3 slow test being skipped, fix for future releases

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#57928]
**Description**
Failing and currently is being skipped (https://github.com/saltstack/salt/pull/57917): https://jenkinsci.saltstack.com/job/pr-centos8-py3-slow/job/master/225/

Original failure found by our awesome community: https://github.com/saltstack/salt/issues/57722#issuecomment-656175220

**Comment by sagetherage** [comment]
These are now running closing

**Comment by sagetherage** [comment]
Re-opening still skipping

**Comment by s0undt3ch** [comment]
The offending test is `integration.modules.test_pkg.PkgModuleTes.test_pkg_upgrade_has_pending_upgrades` which even get's skipped if there are no upgrades.
On some platforms, the test takes more than 30 minutes, which makes jenkins stop the build since there's no output.

We should instead unit test each of the package manager separately.
