### ISSUE TITLE
[BUG] Can't browse repositories on Firefox 79

### ISSUE THREAD

**Issue by ymasson** [saltstack/salt#58157]
**Description**
Since Firefox 79 and its privacy enhancement
https://blog.mozilla.org/security/2020/08/04/firefox-79-includes-protections-against-redirect-tracking/

It is impossible to browse the repositories contents without disable the Firefox native tracking protection.
https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js is blocked.

**Setup**
Open Firefox and developer tools on https://repo.saltstack.com/py3/debian/10/amd64/

**Additional context**
Why using JS and useless things instead of a simple and efficient web server (Apache, Nginx,..) and its simple directory listing functionality ?
Since repositories have migrated on this and before Firefox 79, I must disable my uMatrix rules for just browse repositories.
This is insane.
Sorry, I'm a fan off KISS principle.

**Comment by garethgreenaway** [comment]
@ymasson Thanks for the report.  We're including this javascript to gather download stats so we can track whose downloading what versions of Salt. We'll look into this and find a better less problematic way.

**Comment by bryceml** [comment]
we're using https://github.com/rufuspollock/s3-bucket-listing to provide the directory listings.  If it would help for us to host the jquery.min.js file, we can do that.

We avoided switched from apache and rsync because it's easier to have high uptime with much fewer "moving parts"  it also means that for those that want to sync our repo into an s3 bucket, that's much faster now.  You can also sync over an encrypted protocol instead of the unencrypted rsync protocol.  see https://repo.saltstack.com/#mirror

**Comment by ymasson** [comment]
My configuration is probably more restrictive.
[ff79.png](https://postimg.cc/0KCMvLcv)

**Comment by bryceml** [comment]
try now, I've moved the jquery file to be hosted on the same site.

**Comment by ymasson** [comment]
its works fine, thanks you @bryceml
