### ISSUE TITLE
salt '*' test.verison No minions matched the target. No command was sent, no jid was assigned. ERROR: No return received

### ISSUE THREAD

**Issue by Venkateshsandupatla** [saltstack/salt#58632]
**Description**
I have created a salt-master on a rhel8 vm, and salt-minion another rhel8vm. I have installed it by downloading repo and using yum. But, now am unable to accept the keys. So am unable to send commands to minion.  

**Setup**
I am attaching /etc/salt/master and /etc/salt/minion 

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
it should accept the keys, and I should send commands to minion

**Screenshots**
THIS IS THE SCREENSHOT FROM MASTER
![Screenshot from 2020-10-05 15-35-15](https://user-images.githubusercontent.com/66814938/95066854-97ad5880-0720-11eb-993a-aaff1e48f2a1.png)
![Screenshot from 2020-10-05 15-37-46](https://user-images.githubusercontent.com/66814938/95067058-de02b780-0720-11eb-9609-d49af390ae45.png)

**Comment by cmcmarrow** [comment]
Hello @Venkateshsandupatla. The master is failing to start because it looks like the address you gave it is being used. Because the master cant start, you cant find any keys. So you currently have no keys to accept.

Trouble shooting ideas.

1. I would try rebooting your box to see if that address opens up. There might be a dead master in the background that is holding onto that address.

2. change your master address to 127.0.0.1 and try and get a minion on the same box to connect.


Right now this does not look like a salt bug. But rather a setup problem. 
You might find this helpful https://docs.saltstack.com/en/latest/topics/tutorials/walkthrough.html

**Comment by sagetherage** [comment]
@Venkateshsandupatla I hope this info solved your issue. I am closing for now.
