### ISSUE TITLE
auth_safemode

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#58805]
What does this parameter mean：auth_safemode

**Comment by sagetherage** [comment]
In the minion configuration the default is `False`

If authentication fails due to SaltReqTimeoutError during a ping_interval, this setting, when set to True, will cause a sub-minion process to restart.
```
auth_safemode: False
```

@andyyumiao you can find this here: https://docs.saltstack.com/en/latest/ref/configuration/minion.html#std-conf_minion-auth_safemode. You can also ask questions in our Community Slack https://saltstackcommunity.slack.com/ or our public mailing list for salt-users https://groups.google.com/g/salt-users
