### ISSUE TITLE
[FEATURE REQUEST] salt.states.mount.unmounted - add comment-out functionality

### ISSUE THREAD

**Issue by udf2457** [saltstack/salt#58905]
`salt.states.mount.unmounted` has no option to comment out `/etc/fstab`.

There is a `persist` option but that only decides between purging or leaving in `/etc/fstab`

In a situation such as managing `drbd`,  it would be useful to have an option to comment out `/etc/fstab`, e.g. in conjunction with `- unless: drbdadm status | fgrep -i 'r0 role' | fgrep -qi 'primary'`

**Comment by garethgreenaway** [comment]
@udf2457 Thanks for the report.  So this would include a commented out mount line in /etc/fstab unless `drbdadm status | fgrep -i 'r0 role' | fgrep -qi 'primary'` returned True, otherwise it would include the uncommented line?  I'm curious what the advantage of having the commented out line would be?  Rather than having Salt add the line or not based on the status of the unless?

**Comment by whytewolf** [comment]
no response to the question after 3 years. we will go ahead and close this issue now. if this is something that we should do please create a new ticket in the new ticket respond with the answer to the questions above.
