### ISSUE TITLE
[Feature Request] SaltStack Formula for Nvidia cuda driver installation

### ISSUE THREAD

**Issue by saurabhnemade** [saltstack/salt#58916]
**Is your feature request related to a problem? Please describe.**
Installation of Cuda drivers is always a challenging task. First time I did it, it took more than 4 hours just to understand how to do it. Plus its behaviour is very weird. For centos 7 you need reboot. For centos 8, ubuntu 16,19,20 you don't need reboot. So it would be really helpful if someone can write saltstack formulas for these to standardise the installation process on a fresh machine.

**Describe the solution you'd like**
It could be as simple as "cuda.install" "cuda.persistanced" and "cuda.healthcheck". Since I am not a subject matter expert on this, I guess its good to get everyone's opinion on this.

**Describe alternatives you've considered**
I have been able to get it running for only certain set of systems. They work as of now but we would really like to have more stable solution like salt-formulas.

**Comment by sagetherage** [comment]
@myii if you also can help around this please do! :)

**Comment by s0undt3ch** [comment]
Does the https://github.com/saltstack-formulas have a generic repo for feature requests?

**Comment by sagetherage** [comment]
@myii Does the https://github.com/saltstack-formulas have a generic repo for feature requests?

**Comment by myii** [comment]
> Does the https://github.com/saltstack-formulas have a generic repo for feature requests?

We don't currently have a repo for that but we generally route these sort of requests through our main (and only) pinned repo, which is the [`template-formula`](https://github.com/saltstack-formulas/template-formula).  I suppose we could repurpose the [`workinggroup`](https://github.com/saltstack-formulas/workinggroup) repo for things like this -- I'll raise that in tomorrow's working group meeting.

@saurabhnemade It's not common for the formulas' org to receive requests for writing formulas (I've not seen one, at least over the last couple of years).  The usual process is that people write new formulas (help is available) and then ask for their formula to be added to the org's collection.  In terms of your situation, someone would have to have a similar set up in order to be able to even test it -- which may not be readily available.

I believe the most realistic way forward would be for you to make an attempt to write the formula and then tap into the help that is available when you need it.  We're available in the `#formulas` channel in [Slack](https://saltstackcommunity.slack.com/), which is also bridged to Matrix (`#saltstack-formulas:matrix.org`), Freenode IRC (`#saltstack-formulas`) and Gitter (`saltstack-formulas/workinggroup`).

**Comment by sagetherage** [comment]
closing in this repo @saurabhnemade please see the above and contact info for questions, thank you!
