### ISSUE TITLE
[DOCS] How to get started with Salt on NixOS

### ISSUE THREAD

**Issue by rajatpundir** [saltstack/salt#58912]
I have experience running Salt on Ubuntu but how do you use it on NixOS?

I am unable to start salt-minion and salt-master services via config (if they need to be started via config)

$salt-key gives following error:

WARNING: CONFIG '/etc/salt' directory does not exist.
Error: [Errno 2] No such file or directory: '/etc/salt/pki/master'

**Comment by eliasp** [comment]
For `salt`/`salt-run`/`salt-key` to work on NixOS, you need to have `services.salt.master.enable = true;` in your `configuration.nix` - otherwise the configuration expected by them [won't be present](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/admin/salt/master.nix#L38).

The [same goes](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/admin/salt/minion.nix#L43) for the Minion/`salt-call`, which needs `services.salt.minion.enable = true;` in your `configuration.nix`.

**Comment by rajatpundir** [comment]
Thanks for letting me know. I will try it asap.

**Comment by rajatpundir** [comment]
Services are up and minions are working as expected.Although I had to create a minion.conf file in /var/lib/salt/minion.d/
