### ISSUE TITLE
random.get_str function produces different character set output on windows machines

### ISSUE THREAD

**Issue by ewhitesides** [saltstack/salt#59063]
**Description**
character set returned by random.get_str function on windows machines is different from linux machines.  

**Setup**
using version 3002.2 on master and minions. master is centos 8, minion 1 is centos 8, minion 2 is windows server 2016.

**Steps to Reproduce the behavior**
```
[root@salt-master-c8 ~]# salt salt-minion-c8 grains.get saltversion
salt-minion-c8:
    3002.2
[root@salt-master-c8 ~]# salt salt-minion-c8 random.get_str 16
salt-minion-c8:
    EazOncSV9Bc10G64 #sane normal output
```
```
[root@salt-master-c8 ~]# salt salt-minion-win2016 grains.get saltversion
salt-minion-win2016:
    3002.2
[root@salt-master-c8 ~]# salt salt-minion-win2016 random.get_str 16
salt-minion-win2016:
    ÝúdsúÆÀäÚYÅuÄÊjà #weird output!
```

**Expected behavior**
Expecting output of random.get_str on windows to be from same standard character set as on linux

**Screenshots**

**Versions Report**
3002.2 throughout

**Comment by s0undt3ch** [comment]
@ewhitesides if you login into the windows machine and locally run a `salt-call random.get_str 16` do you get the same weird output?

**Comment by ewhitesides** [comment]
yes i do:

PS C:\> salt-call random.get_str 16
local:
    5v╙1WYk¬┌êⁿd═┼ΩK

**Comment by xeacott** [comment]
I'd say that's pretty random nonetheless. 😄 I'll take a look at get this fixed.

**Comment by xeacott** [comment]
I would say https://github.com/saltstack/salt/compare/master...xeacott:test_pycrypto?expand=1 should probably do it for ya.

I'm guessing the issue is this...https://github.com/saltstack/salt/blob/2627e6ca1c099f5cc70d7d870785206400d793ae/salt/utils/stringutils.py#L38

whatever `__salt_system_encoding__`is deciding on for Windows is not defaulting to utf-8, so forcing it in this situation fixes it. Just not entirely sure if that's the correct fix @s0undt3ch
