### ISSUE TITLE
Ubuntu packages for the following architecture, arm64 and armhf

### ISSUE THREAD

**Issue by yun14u** [saltstack/salt#59086]
### Description of Issue
Please provide Ubuntu packages for the following architectures, arm64 and armhf.  Presently, there is only Ubuntu packages  for amd64 architecture, https://repo.saltstack.com/#ubuntu.

### Setup
apt configured to install Salt packages from the Saltstack apt repositories.

### Steps to Reproduce Issue
Configure Saltstack apt repository for Ubuntu Server 20.10 for architecture, arm64.  I was trying to install salt-minion on a Raspberry Pi running Ubuntu Server 20.10.

**Comment by bryceml** [comment]
We will probably only add arm64 support. armhf is supported for raspbian, and we sill continue to support that, but we don't have enough time to add support for other armhf distros and it's going to end up only being older devices that would use it.

you can currently install the packages from the amd64 repo since they are architecture independent in the mean time, but it would be nice to add the dedicated repos.

**Comment by M1Screw** [comment]
Hello there, 

Does saltstack have a plan to add arm64 support for RHEL like system? (for example, CentOS Stream, RHEL, Oracle Linux, etc.)

**Comment by bryceml** [comment]
> Hello there,
> 
> Does saltstack have a plan to add arm64 support for RHEL like system? (for example, CentOS Stream, RHEL, Oracle Linux, etc.)

Yes at some point, but ubuntu and and debian are way easier since they have less dependencies that aren't already in the distro repos so they will likely come first.  I'd love to see a poll on whether amazon linux or centos/rhel should be higher priority from the perspective of the community so we know what should come next.  Both of those have quite a few dependencies to package.

**Comment by bryceml** [comment]
https://github.com/saltstack/salt-pack-py3/issues/235#issuecomment-933665195

**Comment by jccurtis** [comment]
@bryceml Thank you! This is awesome news.

**Comment by anilknayak** [comment]
Ubuntu ```[ubuntu/18.04/arm64/latest](https://repo.saltproject.io/py3/ubuntu/18.04/arm64/latest)```  is not available
