### ISSUE TITLE
Create official saltstack repo for openSUSE 15.2 & 15.3

### ISSUE THREAD

**Issue by jetojedno** [saltstack/salt#59309]
**Is your feature request related to a problem? Please describe.**
The most recent official repo you have for openSUSE is 15.1, which is now end of life.
https://repo.saltstack.com/opensuse/

openSUSE 15.2 is the current stable release and 15.3 is announced.

**Describe the solution you'd like**
Add official repos for openSUSE 15.2 & 15.3

**Describe alternatives you've considered**
There are community builds for 15.2 so it must be simply possible.  I prefer the official builds for provenance.

**Additional context**
I believe SUSE have been working actively to support saltstack so I'm surprised at the absence of an official repo.

**Comment by ScriptAutomate** [comment]
In the case of openSUSE packages, SUSE is the official source. Historically, we have setup a mirror of the packages maintained created by SUSE.

From https://repo.saltproject.io/#suse, we say:
> _Installs the latest version currently available from SUSE. (These packages are only a mirror from SUSE)_

We initially we're packages from here:
- https://software.opensuse.org/download/package?package=salt&project=systemsmanagement%3Asaltstack%3Aproducts

The latest official builds, for **openSUSE Leap 15.2** and **openSUSE Tumbleweed** can be found here:
- https://software.opensuse.org/package/salt
  - Leap 15.2: Seems to have `v3000` as current stable release, with `v3000.3` or `v3002.2` as an `Experimental` latest build available.
  - Tumbleweed: Seems to be most up-to-date (as Tumbleweed is meant to be as a rolling release) with `v3002.2`

It looks like the latest, `v3002.2`, can be pulled down from `systemsmanagement:saltstack`, which is _not_ a community managed repo, but looks to be SUSE managed:
- https://software.opensuse.org/download/package?package=salt&project=systemsmanagement%3Asaltstack

Their official releases don't currently seem to include **openSUSE Leap 15.3**, and our mirror is out-of-sync with what SUSE is currently building, by the looks of it. I believe we will be meeting with SUSE in the coming weeks, but in the meantime, the above openSUSE Leap/Tumbleweed targets would be best since Salt Project is likely going to change our `https://repo.saltproject.io` directions to install via SUSE official repos.

**Comment by ScriptAutomate** [comment]
Also, potentially related repos:
- https://github.com/openSUSE?q=salt&type=&language=

**Comment by sagetherage** [comment]
@saltstack/team-suse

**Comment by sagetherage** [comment]
we will update our documentation on OpenSUSE, and we will point to their repo since they are a distribution

**Comment by bryceml** [comment]
we have been moved (added to archive.repo.saltstack.com), they will be removed from repo.saltstack.com at our next archive date in May 2021, probably the 18th or 19th.

**Comment by ScriptAutomate** [comment]
The repo installation directions at https://repo.saltproject.io/#suse have been updated. The latest, patched versions of `salt` should be available via default `zypper` installation, sometime after a CVE release occurs.

After further research, it looks like SUSE "backports" CVE fixes and point-releases into the latest official release versions. This may cause confusion for people auditing environments, as `3002.2` in Tumbleweed is likely `3002.5` at the moment, per the revisions/changelog:
- Tumbleweed / `3002.2`: https://build.opensuse.org/package/revisions/openSUSE:Factory/salt

But I think `3000` on OpenSuSE Leap 15.2 is something more like `3000.3` at the moment, when it needs to be patched to `3000.8`.
- Leap 15.2 / `3000`: https://build.opensuse.org/package/revisions/openSUSE:Leap:15.2:Update/patchinfo.14360
