### ISSUE TITLE
[FEATURE REQUEST] Astra Linux compability

### ISSUE THREAD

**Issue by bergentroll** [saltstack/salt#59332]
I am working closely with Astra Linux GNU/Linux which [is a Debian derivative](https://wiki.debian.org/Derivatives/Census/AstraLinux). It have two editions, Common and Secure, which have `os_family` `AstraLinuxCE` and `AstraLinuxSE`. Both editions use the Debian packages toolchain and should be decided fully compatible with `modules.aptpkg`. I'd like to make a PR to match Astra Linux with `aptpkg`, but I failed to find logic where `os_family` is testing.

For now there is just workarounds with `/etc/lsb_release` or grains to make `modules.pkg` working with this distro.

**Comment by bergentroll** [comment]
Well, it seems `os_family` is matching in `modules.aptpkg.__virtual__()`. I am not sure, which one is correct: match `startwith('AstraLinux')` in aptpkg, or force Astra Linux to be `os_family == 'Debian'`. For me the first option is more reliable, because there is a little chance that AstraLinux is not be fully compatible with other modules.

**Comment by ScriptAutomate** [comment]
Related issues and PRs that may good references for direction here on introducing support:
- https://github.com/saltstack/salt/pull/58443 (this PR is adding support for Pop!_OS, and could act as a template)
- https://github.com/saltstack/salt/issues/58395 (this issue is what the above PR resolves)
- https://github.com/saltstack/salt/issues/59061 (this feature request was created to help generically cover instances like this)
