### ISSUE TITLE
[BUG] A couple of README badges are broken

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#59365]
**Description**

![image](https://user-images.githubusercontent.com/170730/106039021-00915580-60af-11eb-85e4-f4c4eefd3fe4.png)

https://github.com/saltstack/salt/blob/2627e6ca1c099f5cc70d7d870785206400d793ae/README.rst#L25-L39

**Expected behavior**

* Twitter account up to date.
* Current release shown.

**Comment by ScriptAutomate** [comment]
Thanks for this issue.

We're working on the following:
- Removing the `latest` badge from the README: GitHub doesn't seem to have automated functionality that can designate the _latest_ major release version as the `latest` release. Instead, it lists the literal latest release of the project, including if it is a new release of a previous major version. Guidance from GitHub seems to imply we should be doing something like labeling them with `prerelease` (which they aren't) in order to avoid them becoming the `latest` release. Though, this still presents the problem of showing the `latest` release on the main project page as the latest uploaded release (see image attached).
  - https://github.community/t/latest-release-isnt-the-real-latest/2244/6
  - https://github.com/cli/cli/issues/2678
  - I've opened an issue with GitHub, also, but that seems to go off into the underworld, and I'm unable to track opened tickets with GitHub. I may open an issue against their docs for additional awareness, and for tracking purposes: https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository
  - We are removing this badge as part of this PR: https://github.com/saltstack/salt/pull/59289
- It looks like social media accounts for Salt are in the midst of transitioning over to Salt Project naming conventions in the URLs as opposed to their displaynames, so this is currently impacting a few of our projects and sites. I'll get the fix included in https://github.com/saltstack/salt/pull/59289 so that it will close this issue
