### ISSUE TITLE
[FEATURE REQUEST] Document installation instructions from a separate domain name

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#59421]
**Is your feature request related to a problem? Please describe.**
Right now, our installation instructions are directly on repo.saltproject.io, we need to update them so that people verify our gpg key when they add it in case repo.saltproject.io becomes compromised at some point.  We also need to move the installation instructions to a separate website so that if repo.saltproject.io were compromised, they couldn't update the instructions with a different gpg key fingerprint.

**Describe the solution you'd like**
I think it would work well to put them somewhere on docs.saltproject.io maybe https://docs.saltproject.io/en/installation/

We could probably even make the repo to create them public like https://github.com/saltstack/open/docs/builddocs is so that the community could update them.

We should put a redirect or link at the root of https://repo.saltproject.io that goes to the offsite instructions.

**Describe alternatives you've considered**
We could put them in the regular docs, but then they would be harder to update outside of a release.

**Comment by ScriptAutomate** [comment]
I think that's a good idea. The site is a bit out-dated, and we could create an improved landing page. I'm not sure about them being in the regular docs, due to the difficulty of updating the `salt` docs.

- The `salt-user-guide` is a place where we are refreshing a variety of the topics content about salt, for example, without being stuck in the `salt` monorepo.
- We could potentially have a repo setup where the content gets published to an endpoint like `docs.saltproject.io/downloads` or something to that effect, depending on wherever we keep the content.
- I also vote for the idea of it being a public repo too, because then it is a secondary source of truth, and issues/contributions can be made directly against it.

**Comment by sagetherage** [comment]
Yes, let's put this in the User Guide outside of the salt repo

**Comment by bryceml** [comment]
tests/integration/modules/test_cp.py::CPModuleTest::test_get_file_str_https looks like it will need changed as part of this change.  It looks like the test is to fetch https://repo.saltstack.com/index.html and see if it contains the word "Bootstrap".

**Comment by ScriptAutomate** [comment]
Update: The repo https://gitlab.com/saltstack/open/docs/salt-install-guide is created for this purpose, as an install guide and for having the install directions existing on a different domain. The goal is to get this into `docs.saltproject.io/salt/install-guide` as an endpoint. This is a WIP at the moment, as it is meant to combine the install docs that exist in this repo and the install docs that exit on `repo.saltproject.io`.

**Comment by dfidler** [comment]
IMHO, repo.saltproject.io is one of the best features of the salt project documentation.  Once I figure out how to get there, i have a single page that tells me how to get it installed.  It's so fast to get started and I love that.

Consider a new user's journey.  They've just come to the home page and they see this:

![image](https://user-images.githubusercontent.com/13830158/172437817-64bd5b27-0366-4101-95b3-098618045df6.png)

So they click on the "install salt" link which goes to repo.saltproject.io and then get...

![image](https://user-images.githubusercontent.com/13830158/172437866-473f6f22-77f9-4a3f-9949-c2c45a3a9933.png)

The only thing that's missing is a visual prompt that says "Pick your operating system and you're done!  Yeah Baby!  (Sorry, was channeling Mike Meyers there).

Anyway, the workflow is awesome.

I like browsing to repo.saltproject.io to do my installs because it's a unique URL that is remembered by my browser page history - I only have to type "repo" and chrome takes me to the page.  The ultimate in convenience - it's quick and painless.  

So as to not rock the boat too much, I like @bryceml idea of a redirect to the equivalent page for repo (with a dropdown that makes you pick your OS, then makes you pick your OS Version, then makes you pick the repo behavior, which then displays the stuff you want to see., instead of using the tabs. Lots of users make mistakes because they choose the wrong OS version or pin to latest because they don't know that there are other options).

**Comment by dfidler** [comment]
Contrast that with the TOC in the current docs which looks like this...

![image](https://user-images.githubusercontent.com/13830158/172438274-aa6d10fd-21f2-40f5-88b3-6f4afde96440.png)

I really don't find this useful.  

When starting with any new product I follow the same workflow:

1. Homepage
2. Read the first paragraph of the "About Product" and get instantly bored
3. Find the "Download" link - and download
4. Find the "Install" link - and do that
5. Run through the tutorials

Note: I might try to "Configure product" if such a page exists, but with the salt docs, they just point the the list of configuration items for the master and minion (which is useless for any new user)

The architecture is interesting for contributors and architects but they are the minority of the user base.

Having said all of that, I'm not sure a redirect really addresses the issue here.  If you compromise repo, then you have the ability to add in rewrite rules (instead of a redirect) that allows you to attack the page.  

PS - I thought repo was just an S3 bucket.

**Comment by barbaricyawps** [comment]
@dfidler I don't disagree with anything you've said, but before you continue, can you check out where I'm going with the new guide? https://saltstack.gitlab.io/open/docs/salt-install-guide/

**Comment by dfidler** [comment]
@barbaricyawps - that's a much better install guide (aside from the insipid bgcolour of the sidebar) :)

So would repo redirect to that?

**Comment by barbaricyawps** [comment]
@dfidler , glad you like it! If you had said, "Your entire approach here is wrong!" I think I honestly would have started to cry. So... disaster averted!

Re: the sidebar color, this documentation theme picks up your system preferences so are you looking at it in dark mode or light mode? The beauty of this particular theme is that it's very well-supported and it's open-source (so we can change it!). The developer on the theme is a great guy and I could reach out to him and talk to him today if you'd like. We can also implement custom CSS overrides, but that does increase some maintenance issues on our end if we follow that route. I'd prefer to get it into the theme's source repo where possible.

Re: would repo redirect to that, that's kind of the next thing I need to figure out. I'm thinking of forming a quick advisement team with some stakeholders to tell me about what the future of repo.saltproject.io should be from a front-end perspective. It will always host the packages, but what does it look like when you first visit that site after we deprecate the install content?

**Comment by dfidler** [comment]
@barbaricyawps I was being glib about the colour of the sidebar - that comes down to personal preference.  :)  Anyway, we can take that conversation offline :)

**Comment by OrangeDog** [comment]
This doesn't really provide any extra security. Wherever the instructions are hosted, if it becomes compromised, then they can be changed to whatever an attacker wants. If they can change the repo key then they can also change the repo URL to one under their control. If the repo site is compromised, then they can change the link to the instructions, or just revert this change entirely.

Plus, having different domains is moot if they're hosted on the same infrastructure. The issue should be about hosting from a different server.

**Comment by barbaricyawps** [comment]
Resolved: https://docs.saltproject.io/salt/install-guide/en/latest/
