### ISSUE TITLE
CVE Release 2021-FEB-25 RETRO will be held MAR-11 Open Hour

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59631]
### Start

This is something we need to implement or start doing.

### Stop

This is not working well and we will stop doing.

### Continue

What did go well? What is working?

**Comment by dafyddj** [comment]
### Start
Make sure that [`salt-winrepo-ng`](https://github.com/saltstack/salt-winrepo-ng) is updated with the new Windows packages in time for the CVE release.

**Comment by cachedout** [comment]
### Start

1. Assessing the impact of last-minute delays. It seems as if it may not be fully appreciated how disruptive it is when releases are delayed in the final minutes or hours before they are scheduled to go out. In many organizations -- especially those with compliance requirements -- security release events need to be tightly coordinated among multiple teams and involve the orchestration of resources around the globe. A delay of a few hours may not be severe for a team in the UTC-8 but is extremely disruptive for a team in UTC+2. Delays of several weeks such as we had in this case can end up blocking projects as teams struggle to understand for just how long they might need to implement temporary measures or hold off on planned work.

1. With a SEP on the topic of creating risk assessment reports when upcoming security releases are announced. The SEP should discuss what specific, if any, should be released about security vulnerabilities prior to the  release, such as potentially listing the affected components of Salt. (Minions, Masters, API, SSH, etc) and whether the vulnerability is local or remote. I'm sure there are many security teams from organizations who use Salt who would be willing to advise on this topic. A better balance may be possible between responsible disclosure and empowering the users of Salt to make good security decisions.

1. Staffing the problem appropriately. If VMware chooses not to add additional paid staff so that the release team has the resources that they need to execute on-time releases, then moves should be made to include a select group of community volunteers in the release and testing process for security releases.

1. Clearly outlining the impact of each individual flaw which is being fixed and including that information in the release when it goes out. Security and operations teams need to immediately assess the impact on their organizations, once the release is available so that they can understand how to structure their deployment strategy. Consider the use of a SEP or other means which defines a template for this process. Such a template could potentially include items like the full text of each CVE, and any additional recommendations provided by the Salt project itself for mitigation and remediation.

1. Consider the inclusion of a manifest of what is being released and through what means for each release. If individual patches are being released in addition to packages, the location of those patches should be clearly indicated. It should be exceedingly easy to see which platforms and versions are receiving updates and which are not.

1. Consider moving the release time up to earlier in the day. 9:00 AM MST would still provide good coverage for the United States and for global teams, it is aligned with the period of time where it's easiest for EMEA and the Americas to be online at the same time.

1. Ensuring that CVE a submitter has a chance to review the final language in the CVE and release text.

1. Consider the creation of a 'Release' [working group](https://github.com/saltstack/community/tree/master/working_groups) which can help with the improvement of release handling.

1. Considering a Bug Bounty program. The latest CVE was found by [running a security scanner on the Salt code base](https://sec.stealthcopter.com/cve-2020-28243/) and then simply picking one of 117 high-severity issues to investigate. The project could benefit greatly by having more eyes looking for security issues.

1. Write up and formalize a Secure Coding policy for the project. There are lots of examples of these out in the wild, but whatever policy is implemented should include strategies for ensuring that code is stringently evaluated for security prior to its inclusion. Consider the creation of a 'Security' working group to assist with this.

1. Producing reports on security release delays within a few hours or a day of a delay happening. In some organizations, operations teams need to produce these reports for their security teams and they are time-sensitive.

### Stop

1. Waiting until the last moment to announce a delay. While delays are not desirable, they're understandable and the sooner teams can get information about a delay, the more easily they can reconfigure their plan. Consider the implementation of a Go / No-Go call at least 24-48 hrs before the release where the all the files are staged and the release is locked in.

### Continue

1. Pre-announcing security releases with specific dates. This was a good change and appears to have been well-received by the community.

1. Communicating over multiple channels. Many of the speed-bumps in the past seem to have been resolved and having information available across a variety of medium is really helpful.

1. Having retrospectives. I'm not sure if retrospectives are happening for all releases or just in this case, but they seem to be a good idea. Please make sure these are accessible via GitHub issues like this one for those who can't join video or audio calls.

1. Fixing issues and gathering direct feedback. On behalf of everybody, your hard work that it took to get these releases out is seen and for the request for feedback is appreciated. Security releases are stressful even when they go smoothly, so please know that lots of people are grateful for what it takes to get them out. Thank you!

**Comment by OrangeDog** [comment]
### Stop
1. Trying to do Stop Start Continue with outside input. The point of that system is personal insight and responsibility. We have no idea what happened day-to-day on the responsible team(s), and we cannot make commitments on their behalf to stop, start, or continue anything.

### Start
1. Perform a proper root cause analysis of the repeated problems (release delayed weeks by regression, release delayed hours at last minute (no reason given)) and share them with the community.
2. Provide honest reasons why the previous measures taken were ineffective in preventing them from occurring.
3. Commit to actions that have broad consensus of being successful, being in place in a timely manner, and hold yourselves to account to meet them. If you are unable to do this then say so, preferably with explanations from whoever is preventing them.

**Comment by sagetherage** [comment]
From Salt's Community Slack https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1614283195202000?thread_ts=1614280019.180400&cid=C7K04SEJC Copying the text since the free plan of slack isn't long lasting:

Andrew Herrington:
That is a fairly common case out there for orgs with strict security controls. Once the CVE is announced, have X days to patch it in some way - either with a patch from upstream, a patch internally developed, or by replacing the system entirely.

I've got good rapport with my security org and have been able to smooth their concerns over through the first delay, but I just had to say "Hey, more delays no ETA yet" and they're quite unhappy.
Even worse, we don't have any way of knowing whether we're potentially affected or not because its just "there's a CVE" - no details about what is possibly affected so I can't even assure them its in a salt feature we're not using or have hardened internally.

What I'm trying to drive at is while its fine and good to say "you shouldn't have tired engineers working on this"  to @ Hannah Wolfe, the reality of this situation for a lot of orgs not your own is pretty bad. I personally blocked out my entire afternoon to handle this issue and now I have to move that time around and am possibly looking at patching a critical bit of infra on a Friday. That's not good for anyone.

**Comment by sagetherage** [comment]
From Salt's Community Slack: https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1614284073205300?thread_ts=1614280019.180400&cid=C7K04SEJC Copying the text since the free plan of slack isn't long lasting:

Chris Ruscio

Fwiw @ sagetherage - I've been a SaltStack evangelist in my company for a few years. We've been running OSS on 10k nodes and I've been trying to fund an Enterprise license for 50k nodes - the handling of this CVE, and the additional delay an hour ago officially killed it. We're either going with Microsoft tooling (sadface) or Ansible. Couple sore points:
- Disclosures will be "released by" (not "at") a specific date/time
- Zero information for over a month
- You knew (you must have) well before an hour ago that you wouldn't be ready - and if you didn't, that's even worse.

**Comment by sagetherage** [comment]
From Salt's Community Slack: https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1614280019180400 Copy ing the text since free plan on slack isn't long lasting:

Hannah Wolfe

Can someone from salt please update everyone on what is happening with this CVE? Delaying it by a few hours at the last minute is completely unacceptable. My engineers have had no time to prepare for being online at 1am and certainly can’t be expected to come online at 1am for a maybe

And https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1614281316195900?thread_ts=1614280019.180400&cid=C7K04SEJC

Not every company has 1000s of engineers sat around twiddling their thumbs.
This has already been delayed once by weeks and now says just “expected”. That’s not manageable for small teams. We at least have the benefit of spanning timezones but what about the people who don’t?

**Comment by sagetherage** [comment]
From Salt's Community Slack: https://saltstackcommunity.slack.com/archives/C8E7RJCPN/p1614337051025500 Copying the test since the free plan on slack isn't long lasting:

Kevin Roy:
I'm wondering why the 2021/02/04 patches are not mentioned in https://gitlab.com/saltstack/open/salt-patches/-/blob/master/README.md
It seems to fix CVE-2020-35662 which is mentioned in 2021/02/05 readme but the content of patches in 2021/02/05 does not match what's in 2021/02/04 patches
Am I right to suppose every 2021/02 patches are needed to patch my 2019.2.8 master and minions ?

**Comment by sagetherage** [comment]
https://saltstackcommunity.slack.com/archives/C8E7RJCPN/p1614301147005900 copying the text since the free plan on slack isn't long lasting:

Erik Johnson @ sagetherage I see the announcement has been posted to http://repo.saltproject.io/3000.html, any ETA on EL6 packages?

Bryce Larson  EL6 is eol, we don't package for eol oses.

And the thread https://saltstackcommunity.slack.com/archives/C8E7RJCPN/p1614301770010500

Erik Johnson @bryceml cool. leaving people out to dry when there's a CVE. cool cool.

Bryce Larson you can take the source rpm for 3000.5 replace the source tarball of salt, and build it.  nothing else changed but version numbers. (edited) 

Erik Johnson Nothing happened between 2019.2.7 and 3000.8?

Erik Johnson Are you sure about that?

Bryce Larson got my versions mixed up

Bryce Larson whatever latest 3000 is on archive.repo.saltstack.com

And https://saltstackcommunity.slack.com/archives/C8E7RJCPN/p1614302431014800

Erik Johnson I guess I don't understand the arbitrary logic of not packaging for platforms that became EOL after the .0 was released, especially given that EL5 got CVE packages in the past after it was EOL (edited) 

David Murphy  did RHEL 5 get CVE after it was EOL, not sure about that, could not wait to drop that once it was EOL. but then > 5 years ago, so memory could be fuzy

**Comment by sagetherage** [comment]
Thread of use of patches the regression that breaks runners is fixed, but more than one patch must be applied https://saltstackcommunity.slack.com/archives/C8E7RJCPN/p1614303086017900

Matt Phillips fyi im fairly sure the 2018.x release/patchset breaks runners
Sage Robins (SaltStack) you will need the patch to the patch, there are more than one file for each version
Matt Phillips ah
Sage Robins (SaltStack)  the original delay we caught this very late, please see the second set of files
Sage Robins (SaltStack)  https://gitlab.com/saltstack/open/salt-patches/-/blob/master/patches/2021/02/05/README.md
Sage Robins (SaltStack)  the last link on the read links you to the patch file that fixes runners
Matt Phillips  gotcha. sorry a bit confusing navigating through them. thanks
Sage Robins (SaltStack)  I know and I asked for something different there, but it didn't happen, so I am monitoring here to try to help

**Comment by sagetherage** [comment]
viq https://github.com/saltstack/salt-winrepo-ng/blob/master/salt-minion-py3.sls could use an update as well

salt-minion-py3.sls
```
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# This software definition will only work in versions of Salt newer than
# 2015.8.2. In verion 2015.8.2 we added the `use_scheduler` option which
# allowed us to launch the installer using the Windows task manager.
# This option is not available in earlier versions of Salt. So, while this
# software definition will allow you to install versions of Salt older than
# 2015.8.2 you will not be able to use pkg.install to upgrade Salt again. You
# will have to upgrade Salt through another means.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
salt-minion-py3:
  {%
      for version in [
          '3002.2',
          '3002.1',
          '3001.4',
          '3001.2',
          '3000.6',
          '3000.4',
          '2019.2.8',
          '2019.2.6'
      ]
  %}
  '{{ version }}':
    full_name: 'Salt Minion {{ version }} (Python 3)'
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'https://repo.saltstack.com/windows/Salt-Minion-{{ version }}-Py3-AMD64-Setup.exe'
    {% else %}
    installer: 'https://repo.saltstack.com/windows/Salt-Minion-{{ version }}-Py3-x86-Setup.exe'
    {% endif %}
    {% raw %}
    # install_flags: "/S /master={{ salt['pillar.get']('salt:master', 'salt.domain.tld') }} /minion-id={{ salt['pillar.get']('salt:minion:ids:' ~ grains['host'] }}"
    {% endraw %}
    install_flags: '/S'
    uninstaller: 'C:\salt\uninst.exe'
    uninstall_flags: '/S'
    msiexec: False
    use_scheduler: True
    reboot: False
  {% endfor %}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Versions of Salt that contain CVE's have been moved to an archive at:
# archive.repo.saltstack.com/windows. The ability to install those versions
# using winrepo has been removed.
# An uninstall only definition will remain here so the packages will show up
# correctly in `pkg.list_pkgs` and to allow for removal using `pkg.remove`
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  {%
      for version in [
          '3002',
          '3001.1',
          '3001',
          '3000.3',
          '3000.2',
          '3000.1',
          '3000',
          '2019.2.5',
          '2019.2.4',
          '2019.2.3',
          '2019.2.2',
          '2019.2.1',
          '2019.2.0',
          '2018.3.5',
          '2018.3.4',
          '2018.3.3',
          '2018.3.2',
          '2018.3.1',
          '2018.3.0',
          '2017.7.8',
          '2017.7.7',
          '2017.7.6',
          '2017.7.5',
          '2017.7.4',
          '2017.7.3',
          '2017.7.2',
          '2017.7.1',
          '2017.7.0'
      ]
  %}
  '{{ version }}':
    skip_urltest: True
    full_name: 'Salt Minion {{ version }} (Python 3)'
    uninstaller: 'C:\salt\uninst.exe'
    uninstall_flags: '/S'
    use_scheduler: True
  {% endfor %}
```
Daf J  @Twangboy :point_up::skin-tone-2:

Shane Lee  Saw your PR... merged.... 
Daf J  Thanks

**Comment by sagetherage** [comment]
https://saltstackcommunity.slack.com/archives/C8E7RJCPN/p1614612280040200

ymasson In https://saltproject.io/security_announcements/active-saltstack-cve-release-2021-feb-25/, I read
`Important: During the CVE release process during testing a regression was found. We communicated this here which delayed the release. Please note the version numbers will not match a conventional order.`
is the regression fixed or still present ?
Sage Robins (SaltStack)  I apologize this was missed - full details will be given, and the regression was corrected.

**Comment by sagetherage** [comment]
https://saltstackcommunity.slack.com/archives/C8E7RJCPN/p1614625020045000 

David Eyk  Has SaltStack adopted any formal release cadence? Or are releases scheduled on a “when it’s ready” basis?

Wayne Werner eykd: IIRC the goal is 4x/yr, I'm not sure if we've quite hit that yet

Sage Robins (SaltStack)  more than a year ago we started to say every 4 months we will have a major release, but don't have that published in a formal way - we probably should

David Eyk  OK, thanks.

**Comment by sagetherage** [comment]
Meeting Notes from Open Hour 2021-MAR-11 in-person retrospective: https://saltproject.io/open-hour-2021-mar-11/

**Comment by sagetherage** [comment]
Please see final report or Retro Artifact of Actions: https://saltproject.io/cve-retro-artifact-actions-2021-mar/. Extended responses are on the [meeting notes for the Open Hour 2021-MAR-11](https://saltproject.io/open-hour-2021-mar-11/) this closes this issue for the 2021 FEB/MAR CVEs. Thank you for all your participation and contributions!
