### ISSUE TITLE
[BUG] pillarenv-from-saltenv in the master config does not work

### ISSUE THREAD

**Issue by ichilton** [saltstack/salt#59718]
**Description**

The documentation states that you can set pillarenv-from-saltenv in the master config.
https://docs.saltproject.io/en/latest/ref/configuration/master.html#pillarenv-from-saltenv

However it doesn't work.

If I set saltenv=somerthing on the commandline, pillarenv is still using base unless explicitly set.

Setting it in the minion config works as expected - setting saltenv also sets pillarenv.

**Setup**

/etc/salt/master.d/someconfig.conf
```
pillarenv-from-saltenv: True
```

**Steps to Reproduce the behavior**

Set `pillarenv-from-saltenv: True` in the master config.

Set pillar somevar differently between salt environments.

```
salt-call pillar.item somevar saltenv=something
```

and

```
salt-call pillar.item somevar saltenv=something pillarenv=something
```

Compare results...

**Expected behavior**

Setting pillarenv-from-saltenv in the master config should work globally.
(Setting in the minion config should work for that minion.)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
root@salt-master:~# salt --versions-report
Salt Version:
          Salt: 3002.5

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: 0.27.7
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 0.27.4
        Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-12-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Comment by twangboy** [comment]
Underscores maybe? `pillarenv_from_saltenv`

**Comment by garethgreenaway** [comment]
@ichilton Following up on this one and making sure you say @twangboy's comment about the use of dashes instead of underscores in the above configuration?

**Comment by ichilton** [comment]
Checking my config, it looks like i've since swapped to `pillarenv_from_saltenv`.

**Comment by garethgreenaway** [comment]
@ichilton With this change is the problem still occurring?  If not, please feel free to close out this issue.  Thanks!

**Comment by garethgreenaway** [comment]
@ichilton Following up here and seeing if the issue is still persisting with the correct configuration option.

**Comment by garethgreenaway** [comment]
Closing this one out due to the lack of activity, if the issue persists please feel free to open a new issue.

**Comment by ipaqmaster** [comment]
This seems to still be an issue in salt-call 3006.1 if not just a bad setting in my testing environment.

I'm testing with a relatively stock salt-master service it has:

1. `pillarenv_from_saltenv: True` in /etc/salt/master (Restarted plenty of times since then)
2. pillar_roots for `base`, `dev` and `prod` each of which just point to the single /srv/salt/pillar dir. The file_roots are configured the same for this testing case.
3. The single pillar top.sls has each top level `env:` defined with identical pillar file references except a base.sls/dev.sls/prod.sls reference consisting of a single line `env: <envname>` so I can determine which pillar root salt is aiming at during pillar.xxx lookup testing.
4. Its own salt-minion service pointing to itself.

When I invoke `salt-call pillar.get env saltenv=dev` its own salt-minion returns "prod", which is not what should've been returned given the saltenv=dev argument while the salt-master has `pillarenv_from_saltenv: True`.

In further testing:

1. Running `salt saltmaster_minon_name_here pillar.get env saltenv=dev` to its own minion while having `pillarenv_from_saltenv: True`  in the master config file  also returns "prod" which is still not correct.
2. Setting pillarenv=dev successfully returns the string "dev" which is what I want the above commands to do while the master has `pillarenv_from_saltenv: True`.
3. Setting `pillarenv_from_saltenv: True` in the minion's config file at `/etc/salt/minion` and restarting it also successfully starts returning the correct env: value when saltenv= is used.

This continues to occur changing various settings on the salt-master such as `top_file_merging_strategy: same` and/or `pillar_source_merging_strategy: none`.

Overall it seems the minion is entirely ignoring the master's `pillarenv_from_saltenv` setting. But the above _does work_ if the minion has `pillarenv_from_saltenv: True` in its own config.

I have not tested yet, but I presume this issue _doesn't_ happen when running salt states which reference pillar data and instead only when calling the pillar module yourself with saltenv=.
