### ISSUE TITLE
[BUG] Missing documentation on pyupgrade in pull request docs

### ISSUE THREAD

**Issue by danielrobbins** [saltstack/salt#59853]
Currently, https://docs.saltproject.io/en/latest/topics/development/pull_requests.html mentions the step of installing a pre-commit hook, but does not talk at all about the pyupgrade solution that is implemented.

This is potentially confusing for community contributors. Pyupgrade will add py2->3 code to any file they touch. The contributors will see a bunch of changes to salt code that they did not actually touch, as part of their commit.

**Comment by danielrobbins** [comment]
It seems like there is a Python 2 deprecation FAQ: https://docs.saltproject.io/en/latest/topics/development/faq-py2-deprecation.html

But this doesn't seem to address community contributor impact of these decisions, such as use of pyupgrade. So, bigger picture, as part of python2 deprecation process, we are planning to drop py2 support from the tree. However, we have an interim solution in place which is quite complex and should be documented in our community contribution documentation.

**Comment by OrangeDog** [comment]
Py2 support was already dropped with the 3001 (Sodium). The deprecation process is finished. 

Rather than `pyupgrade` the entire tree in one go it was decided it would be less disruptive to simply do it incrementally with the hook. Compare the mess that `black`ing the whole tree caused to pending (and needing ports from `develop`) PRs.
