### ISSUE TITLE
Bug #53199 is present in Ubuntu 20.04 MySQL8

### ISSUE THREAD

**Issue by te-af-github** [saltstack/salt#60031]
**Description**
See #53199. MySQL returns list of privileges. Salt compares to "ALL PRIVILEGES". THis obviously always fails.

**Setup**
Minion:
Stock Ubuntu 20.04

mysql-client-8.0 8.0.23-0ubuntu0.20.04.1
mysql-client-core-8.0 8.0.23-0ubuntu0.20.04.1
mysql-common 5.8+1.0.5ubuntu2
mysql-server 8.0.23-0ubuntu0.20.04.1
mysql-server-8.0 8.0.23-0ubuntu0.20.04.1
mysql-server-core-8.0 8.0.23-0ubuntu0.20.04.1

salt-common 3003+ds-1
salt-minion 3003+ds-1

**Steps to Reproduce the behavior**
```
mailbackup-grants:
   mysql_grants.present:
    - grant: ALL PRIVILEGES
    - database: mailbackup.*
    - user: mailbackup
    - host: localhost
```
**Expected behavior**
Execute state successfully.

**Screenshots**

```
2021-04-14 17:11:50,419 [salt.loaded.int.module.mysql:2444][DEBUG   ][19274] grants mismatch '{'user': '`mailbackup`', 'database': '*.*', 'host': '`localhost`', 'grant': ['USAGE']}'<>'{'user': 'mailbackup', 'host': 'localhost', 'grant': ['ALTER', 'ALTER ROUTINE', 'BACKUP_ADMIN', 'BINLOG_ADMIN', 'CONNECTION_ADMIN', 'CREATE', 'CREATE ROLE', 'CREATE ROUTINE', 'CREATE TABLESPACE', 'CREATE TEMPORARY TABLES', 'CREATE USER', 'CREATE VIEW', 'DELETE', 'DROP', 'DROP ROLE', 'ENCRYPTION_KEY_ADMIN', 'EVENT', 'EXECUTE', 'FILE', 'GROUP_REPLICATION_ADMIN', 'INDEX', 'INSERT', 'LOCK TABLES', 'PERSIST_RO_VARIABLES_ADMIN', 'PROCESS', 'REFERENCES', 'RELOAD', 'REPLICATION CLIENT', 'REPLICATION SLAVE', 'REPLICATION_SLAVE_ADMIN', 'RESOURCE_GROUP_ADMIN', 'RESOURCE_GROUP_USER', 'ROLE_ADMIN', 'SELECT', 'SET_USER_ID', 'SHOW DATABASES', 'SHOW VIEW', 'SHUTDOWN', 'SUPER', 'SYSTEM_VARIABLES_ADMIN', 'TRIGGER', 'UPDATE', 'XA_RECOVER_ADMIN'], 'database': '`mailbackup`.*'}'
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.9

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Aug 22 2020, 10:03:02)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.13
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-14-amd64
         system: Linux
        version: debian 9.13
```
</details>

Minion is 3003

**Additional context**

**Comment by danielrobbins** [comment]
The underlying cause of this issue is that the original bug was not fixed. The original bug reporter simply closed the bug, as it was a "bug" of a specific version of mariadb. But after some research, it turns out that this "ALL PRIVILEGES" issue is potentially more widespread than just this specific version of MariaDB, so it could cause problems for other versions too. I found this in the current MySQL docs: https://dev.mysql.com/doc/refman/8.0/en/show-grants.html:

"In MySQL 8.0 compared to previous series, SHOW GRANTS no longer displays ALL PRIVILEGES in its global-privileges output because the meaning of ALL PRIVILEGES at the global level varies depending on which dynamic privileges are defined. Instead, SHOW GRANTS explictly lists each granted global privilege:
...

**Applications that process SHOW GRANTS output should be adjusted accordingly.**"

So I believe this bug would also potentially impact the current official version of MySQL 8 as well.

**Comment by garethgreenaway** [comment]
Looks like there was the assumption that "ALL PRIVILEGES" will always be translated to the full list of all available privileges.  Apparently this is only the case when the grant is on the global level, eg. using a database of `*.*`.  When the grant is to a specific database then the grant is add to the grand table with the text `ALL PRIVILEGES`.
