### ISSUE TITLE
[BUG] 3003 static grains and grains_dirs don't work in statefile 

### ISSUE THREAD

**Issue by 1ricardo** [saltstack/salt#60198]
**Description**
I' m working on automation in serverless mode and I'm using  `--saltfile` option (btw. there is missing any documentation how to use this switch, I found a very short description on  [Twitter](https://twitter.com/salttips/status/1262345221058318336)  :/ ) how to use it. I noticed that static grains and `grains_dirs` don't work at all in that setup.

**Setup**
```sh
salt-call:
  file_client: local
  log_level: warning
  file_root: saltstack/state
  pillar_root: saltstack/pillar
  grains_dirs: 
    - saltstack/grains
  user: root
  sudo_user: root
  id: arch-saltstack
  # state_output: changes
  state_output: full
  multiprocessing: True
  grains:
    roles:
      - webserver
      - memcache
```

**Steps to Reproduce the behavior**
After executing command
```sh
sudo salt-call --local --saltfile=saltstack/minion.conf grains.items
```
I am not able to find my static grains or grains from `grains_dirs` and you can notice that `grains_dirs` are not even set.
```sh
> salt-call --local --saltfile=saltstack/minion.conf config.items
...
grains_cache_expiration:
  300
grains_deep_merge:
  False
grains_dirs:
grains_refresh_every:
  0
grains_run:
  False
...
```

**Expected behavior**
I would like to use the  static grains or `grains_dirs`

**Screenshots**

**Versions Report**
```sh
sudo salt-call --versions-report
Salt Version:
Salt: 3003

Dependency Versions:
cffi: 1.14.5
cherrypy: Not Installed
dateutil: 2.8.1
docker-py: 5.0.0
gitdb: Not Installed
gitpython: Not Installed
Jinja2: 3.0.0
libgit2: 1.1.0
M2Crypto: 0.37.1
Mako: 1.1.4
msgpack: 1.0.2
msgpack-pure: Not Installed
mysql-python: Not Installed
pycparser: 2.20
pycrypto: Not Installed
pycryptodome: 3.9.9
pygit2: 1.5.0
Python: 3.9.5 (default, May 12 2021, 17:14:51)
python-gnupg: 0.4.7
PyYAML: 5.4.1
PyZMQ: 22.0.3
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.3.4

System Versions:
dist: arch rolling n/a
locale: utf-8
machine: x86_64
release: 5.12.3-zen1-1-zen
system: Linux
version: Arch Linux rolling n/a

```
PASTE HERE
```
</details>

**Additional context**
Add any other context about the problem here.

**Comment by waynew** [comment]
Hey @1ricardo thanks for opening this issue! Turns out it's a problem with our docs not clearly explaining what a Saltfile *is*.

The Saltfile isn't a config file - it allows you to provide command line args without providing command line args. So if you're constantly calling something like:

```
salt-call --local -c path/to/my/config <commands>
```

You can avoid having to provide all those extra args by creating a Saltfile

```
salt-call:
  local: True
  config_dir: path/to/my/config
```

Then you only have to do

```
salt-call <my commands
```

And salt-call will use the commands from the Saltfile. While this is super handy, what you really want is to be adding config options to your minion config, and probably have a Saltfile that's roughly like that. HTH!
