### ISSUE TITLE
[DOCS] How to link topic and module overview?

### ISSUE THREAD

**Issue by marbx** [saltstack/salt#60280]
The minion data cache [module overview](https://docs.saltproject.io/en/latest/ref/cache/all/index.html) lacks description or a link to the minion data cache [topic](https://docs.saltproject.io/en/latest/topics/cache/index.html) 

The topic is generated from an [rst file](https://github.com/saltstack/salt/blob/master/doc/ref/cache/all/index.rst).

The module overview is not generated from rst.   How is the html generated an could the topic be linked?

**Comment by sagetherage** [comment]
@marbx thank you for the issue report!

Let me restate so I know I'm understanding ,correctly: if a user of salt lands on [this index page of cache modules](https://docs.saltproject.io/en/latest/ref/cache/all/index.html) there is no way to know f these modules all are referencing or concerning the [Minion Data Cache on the Salt Master](https://docs.saltproject.io/en/latest/topics/cache/index.html) which is a main table of contents topic or index (all of these words are confusing I realize).

Yes, it would be helpful to have a link on [the index of the cache modules page](https://docs.saltproject.io/en/latest/ref/cache/all/index.html) to [the minion data cache details page](https://docs.saltproject.io/en/latest/topics/cache/index.html). We do have a link one direction, but both directions is preferable.

There is an .rst of the [minion data cache](https://github.com/saltstack/salt/blob/master/doc/topics/cache/index.rst) and we use sphinx to render the HTML which you see [here](https://docs.saltproject.io/en/latest/topics/cache/index.html) in the HTML format -- you can find more details on [Writing Documentation](https://docs.saltproject.io/en/latest/topics/development/conventions/documentation.html#writing-salt-documentation).

In this case perhaps, you are looking for the details in [Cross References](https://docs.saltproject.io/en/latest/topics/development/conventions/documentation.html#cross-references) and specifically to add something to the index page that is generated by sphnix [here](https://docs.saltproject.io/en/latest/topics/development/conventions/documentation.html#index-entries). I hope this helps and yes this would be very nice to have since it is clearly missing.

**Comment by marbx** [comment]
Hi @sagetherage, thank you for your great overview!
Not confusing at all.
I was aware of the sphinx documentation but have not found the rst from which sphinx generates the cache modules index.
 
I took a second look and guess it is `doc/ref/cache/all/index.rst` but I cannot verify because creating the docs on Windows fails due to a lack of `make` and pip install nox failed on my Linux box, probably due to my hardware.

I edited the rst file in PR https://github.com/saltstack/salt/pull/60306
Could you please have a look? I intend(ed) to use a dedicated branch but used master by mistake.

**Comment by sagetherage** [comment]
Looks good! Thank you @marbx :)

**Comment by marbx** [comment]
This question is answered
