### ISSUE TITLE
fileserver_limit_traversal - remove old setting

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#60444]
If I set `fileserver_limit_traversal` to true on minion, then execute state module, salt master will only scan the directory which containing SLS files and the _modules directory. Why is this not the default behavior of master? because of scan the entire fileroot directory(by default) will cause a great waste of resources.

**Comment by whytewolf** [comment]
I think a better question is why this setting exists when it doesn't have any code to actually do anything beyond being set.

**Comment by sagetherage** [comment]
@andyyumiao 
you may want to pose your question in the [mailing list forum for salt-users](https://groups.google.com/forum/#!forum/salt-users), ask on [IRC]((https://web.libera.chat/#salt), or in our [community slack workspace](https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg) for a better conversation platform and quicker turn around time, but I will assign in an attempt to get more details, here.

**Comment by sagetherage** [comment]
It looks like the code behind this was not working as intended and was removed/deprecated https://github.com/saltstack/salt/pull/49987 and the setting was left behind and changes nothing if set to `True` or `False` likely we need to do some clean up work, although, I am not entirely sure what would be exactly since there have been so many changes. To your point @andyyumiao it could cause performance issues and then why have the setting, and to your point @whytewolf what should be here and what is the intended use? I will have to get more details from the Core Team.

**Comment by whytewolf** [comment]
@sagetherage the original goal of the setting was to keep abused filesystems from causing too much havoc. for users who put everything and the kitchen sink in the filesystem and then wondered why the master had a hard time functioning. It was never a good solution and mostly just a stop-gap for 1 user.

**Comment by sagetherage** [comment]
I guess we should call this tech-debt to remove this setting then
