### ISSUE TITLE
[BUG] distutils is deprecated and slated for removal in python3.12

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#60476]
**Description**
from setup.py on py3.10

```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```
We need to update our setup.py to not use distutils by the time python3.12 is out.

**Comment by twangboy** [comment]
We're starting to see this with every salt command:
```
PS C:\Users\vagrant> salt-call --version
C:\Program Files\Salt Project\Salt\bin\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is repl
acing distutils.
  warnings.warn("Setuptools is replacing distutils.")
salt-call 3005rc1
```

**Comment by twangboy** [comment]
This is in Master

**Comment by dmurphy18** [comment]
run into issue with generating versions for Salt, setup.py wrote out salt/_versions.py when generating sdist, see write_salt_version etc.
However the versions generated differ from that using setuptools-scm, for example: on the current master branch
```
david@david-XPS-15-9570:~/devcode/dgm_salt_master/salt$ python3 -m setuptools_scm 
Warning: could not use pyproject.toml, using default configuration.
 Reason: /home/david/devcode/dgm_salt_master/salt/pyproject.toml does not contain a tool.setuptools_scm section.
/home/david/.pyenv/versions/3.8.6/lib/python3.8/site-packages/setuptools_scm/config.py:61: UserWarning: relative_to is expected to be a file, its the directory '.'
assuming the parent directory was passed
  warnings.warn(
3005.2.dev1490+gb728d0e0e4
david@david-XPS-15-9570:~/devcode/dgm_salt_master/salt$ python3 setup.py --version
3005.1+1490.gb728d0e0e4
3005.1+1490.gb728d0e0e4
```
and untaring a python3 setup.py sdist generated tar ball
```
tar -xzvf salt-3005.1+1490.gb728d0e0e4.tar.gz
.
.
david@david-XPS-15-9570:~/devcode/dgm_salt_master/salt/dist$ cat salt-3005.1+1490.gb728d0e0e4/salt/_version.py 
# This file was auto-generated by salt's setup

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(3005, 1, None, 0, '', 0, 1490, 'gb728d0e0e4')
david@david-XPS-15-9570:~/devcode/dgm_salt_master/salt/dist$
```
so need to reconcil the setuptools-scm 3005.2 ??? and why it is 3005.2 vs the current 3005.1

**Comment by dmurphy18** [comment]
Agreed work for now keeping setup.py since work-flows and usage patterns (was always the plan) but need to resolve how version is handled, especially since want to be able to release a nightly build that has passed all tests etc. as v300x.y.z without having to rebuild anything, which currently can not do with distutils or setuptools approaches.

**Comment by dmurphy18** [comment]
Problem with 3006.0 is due to changes in salt/utils/version.py, changes to StrictVersion or LooseVersion cause the problem to occur, noting that a pip3 list | grep salt reuturns 3006.0, but salt-call --local test.version returns the 3005.1+1545.g776c30659f, with distutils.version but those agree with 3005.1+1545.g776c30659f.

The PyPI looseversion is not a direct compatible direct replacement for distutils.version.LooseVersion as it stated.

**Comment by dmurphy18** [comment]
Ran into the cause of the issue of version 3006.0 appearing and is due to an ImportError in salt/version.py.
If you get an ImportError, the code drops through to attempt to __discover_version, see https://github.com/saltstack/salt/blob/master/salt/version.py#L645-L656
which attempts to discover the version from salt/version.py and it returns 3006.0 (basically the current_release - imho poorly named since it is really the next release, as the current release is actually 3005.1, master branch current version is 3005.1+1546.g974558464a)

With Python recommending using packaging.version instead of distutils.version, and thus import from packaging, results in an ImportError with pip install
```  
  49     File "/tmp/pip-req-build-pbnkyin6/salt/utils/versions.py", line 44, in <module>
  50       from packaging.version import InvalidVersion
  51   ModuleNotFoundError: No module named 'packaging'
```
This implies needing to add **build-system** to the pyproject.toml file, such that pip will install the needed packages, packaging and looseversion before attempting to install the rest of Salt (note the problem occurs during pip's 'Getting requirements to build wheel: started', so there is not a chance to fuly resolve all the requirements for Salt.  
The pyproject.toml additions:
```
[build-system]
requires = ["setuptools", "wheel", "packaging", "looseversion"]
build-backend = "setuptools.build_meta"
```
However this result in the following ModuleLoadError
```
   9 Processing ./salt-3005.1+1545.g776c30659f.tar.gz
  10   Created temporary directory: /tmp/pip-req-build-k51mbuzs
  11   Added file:///home/david/tmp_salt/salt-3005.1%2B1545.g776c30659f.tar.gz to build tracker '/tmp/pip-build-tracker-tlooebmj'
  12   Created temporary directory: /tmp/pip-build-env-jkrp9_am
  13   Installing build dependencies: started
  14   Running command pip subprocess to install build dependencies
  15   Using pip 22.3.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
  16   Collecting setuptools
  17     Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
  18   Collecting wheel
  19     Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
  20   Collecting packaging 
  21     Downloading packaging-22.0-py3-none-any.whl (42 kB)
  22        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 740.9 kB/s eta 0:00:00
  23   Collecting looseversion 
  24     Using cached looseversion-1.0.2-py3-none-any.whl (6.4 kB)
  25   Installing collected packages: wheel, setuptools, packaging, looseversion
  26     Creating /tmp/pip-build-env-jkrp9_am/overlay/bin 
  27     changing mode of /tmp/pip-build-env-jkrp9_am/overlay/bin/wheel to 755
  28   ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  29   launchpadlib 1.10.13 requires testresources, which is not installed.
  30   Successfully installed looseversion-1.0.2 packaging-22.0 setuptools-65.6.3 wheel-0.38.4
  31   WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/w     arnings/venv
  32   Installing build dependencies: finished with status 'done'
  33   Getting requirements to build wheel: started
  34   Running command Getting requirements to build wheel
.
.
  43     File "/tmp/pip-req-build-k51mbuzs/salt/version.py", line 684, in __get_version
  44       from salt._version import __saltstack_version__  # pylint: disable=E0611,F0401
  45   ModuleNotFoundError: No module named 'salt'
```

This problem occurs even if you remove any changes in salt/utils/version.py, that is back to using distutils.version.  The presence of the build-system commands in pyproject.toml causes the issue.  This may be due to pyproject.toml in its current state is not fully fleshed out for use, for example: nothing defining project salt.

Solution for now is to utilize setuptools._distutils.version for now, and allow time to fully research pyproject.toml issues and fully flesh it out for use with  Salt.  Note Setuptools links still shows pyproject.toml usage as BETA as of 2022-12-15  , url https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#beta
```
Support for adding build configuration options via the [tool.setuptools] table in the pyproject.toml file is still in beta stage.
```
