### ISSUE TITLE
[FEATURE REQUEST] Any chance of killing the 301 redirect to https for the salt Debian repo ?

### ISSUE THREAD

**Issue by udf2457** [saltstack/salt#60672]
I ran into this one today.

I've got a DHCP pre-seed fully automated install that does a fully automated install.

Unfortunatley, the wise brains at Debian are living in the last century and there is no first-class support for https.

This means that a nice one-liner:

`d-i apt-setup/local0/repository string http://repo.saltproject.io/py3/debian/10/amd64/latest buster main`

Does not work because http://repo.saltproject does a silent 301 redirect to https://repo.saltproject.  

This results in the Debian installer marking the repository as "unverifiable" and falling back to installing the ancient salt from the Debian repo instead.  Not cool !

This means I've got to do a hacky messy workaround involving a chain of commands at the end of my preseed.

Since its an unknown when (if ever) Debian might finally support https, I thought it might be quicker for you to kill off the 301 redirect ?  ;-)

**Comment by bryceml** [comment]
no, it has been requested as a feature request to change to https only repos, and it is vmware's policy as far as I am aware.

you could make a local mirror of our repos and fetch that over http: https://repo.saltproject.io/#mirror

you should probably open a bug report against debian's tooling so that can get fixed.
