### ISSUE TITLE
[TEST FAILURE] arm64 debian 11

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#60671]
https://jenkins.saltproject.io/job/Full-PR/job/full-pr-debian-11-arm64/job/PR-1712/5/

It segfaults halfway through the test suite consistently.

This is needed for raspberry pi support going forward.

**Comment by waynew** [comment]
Looks like this is failing on tests/integration/runners/test_nacl.py

I installed libnacl on my personal pi & gave it a shot and it seemed to work fine, I'm guessing maybe we have the wrong version of libsodium installed or may be there's actually a bug in libnacl :thinking:

**Comment by waynew** [comment]
(I'm not running debian 11, and it's ARMv7 that I'm on, so that might also have something to do with it succeeding for me)

**Comment by bryceml** [comment]
you can launch an arm64 debian 11 instance on aws:  ami-02e4c099f464c7b6d was the ami used above as a starting point.

ami-06e2b0c5779874ddd looks like the latest version currently.

**Comment by waynew** [comment]
Looks like just running this test_nacl.py will repro the segfault on this AMI. I had to install libgit2, libsodium23 and a few other things to get the tests to run. Interestingly enough, just importing libnacl & running the encryption did *not* cause a failure. I'm going to try just running the Salt code to do the encryption and see if we still fail :thinking:

**Comment by waynew** [comment]
Both of these seem to work fine:
```
root@ip-10-27-59-48:~/salt-master# salt-run nacl.enc 'blerp' pk=ny7RqsiaMjr+2IFDjZfhRDWkrfgUY8HGSWV9pfbPVQE=d1jamBL1m+8vq33/2cGGVJGwxJggPQ7+mc4C6AIkTzucuA7mX8gvT0y97rj8yg+DpkA5vmA=
root@ip-10-27-59-48:~/salt-master# salt-call --local nacl.enc 'blerp' pk=ny7RqsiaMjr+2IFDjZfhRDWkrfgUY8HGSWV9pfbPVQE=local:
    vjNVHD6oVldVwXMKyIyRzIb/cwcqkgNviZiAEYxHT3gmLBzVKmhDk1WAMX1agsTUEwEaCFg=
```

Renaming the failing test to include `XXX` and doing 

```
python3 -m nox -e 'pytest-3(coverage=False)' -- tests/integration/runners/test_nacl.py --run-slow --run-destructive -k XXX
```

will reproduce the failure. Makes me wonder if it's something in the loader...

**Comment by waynew** [comment]
Ah. Okay so this is very weird. Other bits work as expected, but for some reason when providing the PK, possibly because it's getting sent as the wrong type, but for some reason it's trying to seal the box with the wrong length key, despite libnacl having protections for that.... like... for a long time. So something is wonky here :thinking:

**Comment by waynew** [comment]
Something is very wrong here and I don't know why.

I added some debugging code right before the libnacl code that calls off to ctypes. It dumped out this

```
import libnacl
msg=b'hello'
pk=b'\xe2\x04\xaehd_\xa2:YS\xf7\xb0x\xb5\x8aPE\x12\xb0H\xc5]\x19\xf0\x89+NX\xc6\x1f\x12\x0f'
c = libnacl.ctypes.create_string_buffer(len(msg)+libnacl.crypto_box_SEALBYTES)
libnacl.nacl.crypto_box_seal(c, msg, libnacl.ctypes.c_ulonglong(len(msg)), pk)
```

But it doesn't make any sense because that code works just fine. I thought it might have something to do with going through the utils code but nope,

```
import base64
import salt.utils.nacl
salt.utils.nacl.enc(data='hello', pk=base64.b64encode(b'\xe2\x04\xaehd_\xa2:YS\xf7\xb0x\xb5\x8aPE\x12\xb0H\xc5]\x19\xf0\x89+NX\xc6\x1f\x12\x0f'), opts={'pki_dir': '/tmp'})
```
that works just fine, too.

It succeeds in every way that I can find, except via the test suite. Tomorrow I'll see if it will still fail via the pytest fixtures -- it might just be a runtests issue :shrug:

**Comment by waynew** [comment]
This *also* fails under pytest's runner...

**Comment by waynew** [comment]
For more fun, just a simple unit test will actually fail here too

**Comment by waynew** [comment]
Further information: eliminating everything in the test suite except the pytest/conftest.py and this still fails when executed via nox...

Ah! Very interesting:

```
root@ip-10-27-59-48:~/salt-master# .nox/pytest-parametrized-3-crypto-none-transport-zeromq-coverage-false/bin/python3 /blerp/test.py 
b'\xcb\xbd|+\xb6'
root@ip-10-27-59-48:~/salt-master# cat /blerp/test.py 
import libnacl

def test_boop():
    msg=b'hello'
    pk=b'\xe2\x04\xaehd_\xa2:YS\xf7\xb0x\xb5\x8aPE\x12\xb0H\xc5]\x19\xf0\x89+NX\xc6\x1f\x12\x0f'
    c = libnacl.ctypes.create_string_buffer(len(msg)+libnacl.crypto_box_SEALBYTES)
    libnacl.nacl.crypto_box_seal(c, msg, libnacl.ctypes.c_ulonglong(len(msg)), pk)
    print(c.value)


if __name__ == '__main__':
    test_boop()
```
This works when called via python. Via pytest? not so good. Hrm... seems like it might be a library issue :thinking: I have two different installs - one pytest works with the above, but the nox version does not, when executed even via `python -m pytest test.py`

**Comment by waynew** [comment]
Looks like this is an issue in pytest-salt-factories - removing that via pip uninstall allows this sample test to succeed

**Comment by waynew** [comment]
I was wrong! Well, sort of!

It's actually an issue with pyzmq 19.0.2. That's broken on arm64 debian11, badly. Just importing zmq and then doing anything with ctypes hangs (probably the GIL?). Creating a zmq.context and then doing a context.socket (for sure with `zmq.PULL`) means that other calls (like the libnacl one) out through ctypes will segfault.

Installing `'pyzmq>19.0.2,<22.0.0'`, as in the `zeromq.txt` requirements makes this work. I *think* this is due to the requirements file configured incorrectly because `zeromq.txt` has `pyzmq>=19.0.2,<22.0.0 ; python_version >= "3.9"`, and the Python 3 that nox installs is
```
$ .nox/pytest-parametrized-3-crypto-none-transport-zeromq-coverage-false/bin/python3   --version
Python 3.9.2
```

Oh. Wait. Just noticed while writing this - `>=19.0.2`. That should probably be `>19.0.2`.
