### ISSUE TITLE
Support busybox

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#6076]
Working with a user that had busybox installed on a custom linux distro it became apparent that there are some issues running salt-minion on a machine running busybox.

For example, apparently `ps` doesn't have all the flags/options as normal.

```
2013-07-09 16:37:40,770 [salt.loaded.int.module.cmdmod               ][DEBUG   ] output: ps: invalid option -- e
BusyBox v1.17.2 (2013-07-09 22:27:53 UTC) multi-call binary.

Usage: ps  

Show list of processes

Options:
    w   Wide output
```

Also, a binary named `start-stop-daemon` doesn't exist:

```
2013-07-09 16:38:56,731 [salt.loaded.int.module.cmdmod               ][ERROR   ] stderr: dpkg: warning: 'start-stop-daemon' not found in PATH or not executable.
dpkg: 1 expected program not found in PATH or not executable.
NB: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin.
E: Sub-process /usr/bin/dpkg returned an error code (2)
2013-07-09 16:38:56,731 [salt.loaded.int.rawmodule.apt               ][ERROR   ] Error:  dpkg: warning: 'start-stop-daemon' not found in PATH or not executable.
dpkg: 1 expected program not found in PATH or not executable.
NB: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin.
E: Sub-process /usr/bin/dpkg returned an error code (2)
```

**Comment by bortels** [comment]
Was considering adding this as a feature to support Alpine, but it turns out Alpine Linux has a "shadow" package that adds the useradd group of utilities. 

echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
apk --no-cache add shadow

Minimal testing shows this makes salt work with Alpine (at least for users). Figured it was worth mentioning in case someone searching comes across this. 

Non-alpine users interested might look at the package home: https://pkg-shadow.alioth.debian.org/
