### ISSUE TITLE
[FEATURE REQUEST] Expanded architecture support for Juniper Native Minion

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#60780]
**Is your feature request related to a problem? Please describe.**
The Juniper native minion currently only supports the x86_64 architecture. I'd like to see that expanded to support additional devices.

**Describe the solution you'd like**
Build for the following architectures

ARM (32-bit): EX2300/EX3400
PPC (32-bit): EX series, MX5/MX10/MX40/MX80/MX104
MIPS (32-bit): Low-end SRX
x86 (32-bit): vQFX

**Describe alternatives you've considered**
Only alternative is to run proxy minion

**Comment by dmurphy18** [comment]
@ggiesen I will bring this up during the planning meeting, but I feel this may become a user-contributed project due to limited resources.  

The Juniper native minion repository on GitLab has been moved to the open side of the house but his still private, since it currently has a Juniper Cert which cannot be made public.  Discussion is on-going as to altering the CI/CD pipeline to ensure that the cert is privately available, but not publicly available, similar to how Vault was used for secrets when building packages, before the move to GitLab CI/CD.

**Comment by ggiesen** [comment]
@dmurphy18 I'm just opening this issue to document the request, and didn't figure it would happen before the build pipeline has been opened and myself or someone else from the community is able to attempt building.

**Comment by dmurphy18** [comment]
@ggiesen No problem, good to get it tracked so it doesn't slip between the cracks

**Comment by dmurphy18** [comment]
With support for Juniper  moving to a community repository, going to close this issue since not the correct place for it. Please duplicate the issue if you desire on the Git Hub repository https://github.com/vmware/salt-native-minion-for-juniper

I am still the maintainer for the GitHub repository, but VMware is inviting co-maintainers, if you are interested.
