### ISSUE TITLE
[BUG] Auto Update not working (DEB packages / apt-get install)

### ISSUE THREAD

**Issue by sjkummer** [saltstack/salt#60949]
**Description**
As we have learned from the past, it's a good thing to keep the salt master up to date because there is a CVE scored 9+ ~once a year. The docs says that this should be done by regularly running a `sudo apt-get install salt-master` followed by a service restart. Unfortunately, this is not the whole story, due to config file conflicts.

**Setup**
Salt-Master on Ubuntu 18

Please be as specific as possible and give set-up details.

- [ X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
- Run `sudo apt-get install salt-master` on a machine
- Wait until a new version got released
- Run `sudo apt-get install salt-master` again to fetch the update

**Expected behavior**
Update should succeed without a manual review of the config file. Or the docs should describe an alternate solution.

**Actual behavior**
```
Setting up salt-master (3003.3+ds-1) ...

Configuration file '/etc/salt/master'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** master (Y/I/N/O/D/Z) [default=N] ?
```

This will result in numberous salt masters in the wild that are not up-date and potentially vulnerable. I have seen that several times now (different version updates).

PS:
Additionally, there are availablity / reachability problems with the Release file:

```
Ign:4 https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic InRelease                                                                                         
Err:6 https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic Release                                                                                       
  404  Not Found [IP: 2600:9000:2190:5a00:d:e451:e500:93a1 443]
Reading package lists... Done
E: The repository 'https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic Release' no longer has a Release file.

```

**Comment by OrangeDog** [comment]
That's generally why you should use `.d/` directories instead of editing packaged config. That applies to everything, not just Salt.

Further, in a non-interactive `apt` session (or you add `-y`) then it won't ask the question and perform the listed default action. That can be configured via `/etc/apt/preferences` (or, as previously mentioned, `/etc/apt/preferences.d/`). Then automatic updates won't be blocked. The `unattended-upgrades` utility would also do this for you.

Salt repositories moved to saltproject.io a while ago. You will need to update all your sources lists.
Python2 is also fully unsupported. If you are concerned about known CVEs then you need to upgrade.
The latest releases for 18.04 are at [https://repo.saltproject.io/py3/ubuntu/18.04/amd64/latest](https://repo.saltproject.io/#ubuntu)

In summary, I don't see any bug here. Everything is working as it's supposed to. Any issues you have with the behaviour are due to `apt` configuration, not Salt.

**Comment by sjkummer** [comment]
Thanks for the hint regarding `.d/`. Works for me now. 

For others, it might be helpful if https://docs.saltproject.io/en/latest/ref/configuration/master.html would be more clear about not to use `/etc/salt/master `

Also, it would be great if the repos do not change anymore in the future.
