### ISSUE TITLE
[FEATURE REQUEST] Add support for reporting state run stats via Prometheus

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#61206]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Take data from salt and "return" it into a file formatted for Prometheus using the [Text Exposition Format](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example) which rolls up state success and failure data. The intended use case for this module is to have distributed success/failure reporting from minions for unattended state or highstate runs.

**Describe alternatives you've considered**
Considered using a minion engine with the `prometheus-client` library, but it seemed like overkill for my use case.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by nicholasmhughes** [comment]
PR inbound

**Comment by hkbakke** [comment]
+1 to this! I currently do this with a python package I wrote that collects everything from the master every 30 minutes into the master's textfile collector, with minion id as a metric label. I also have a dashboard in Grafana and prometheus alerting for the status of the entire fleet of minions connected to each master. However because it is an external tool I have to use salt-run's --json output to collect the data where especially the part where I get the last highstate execution result is slow. So slow infact that I finally got a real need for pythons multithreading!

A builtin metrics exporter that is mostly for free timewise with current state generated during the execution is much faster and will enable immediate alerting if something is wrong. 

(As a personal side note: I did create my own implementation of the simple format used for the textfile collector at first, but after I while I tried using the official prometheus-client library, and I much recommend that approach. In my opinion it is a little bit simpler, supports every metric type and has robust error handling. Features such as atomic write to the textfile is just a function call.)

**Comment by nicholasmhughes** [comment]
Had a discussion with core engineers, and it was decided that this feature will not be integrated into the main Salt project. Instead, it will live separately as a Salt Extension which can be pip installed into Salt in order to extend it as a plugin.

This version of the returner has been published to PyPi as v1.0.0 of the saltext.prometheus package.

https://pypi.org/project/saltext.prometheus/1.0.0/

In the future, additional Prometheus functionality (such as engines, etc.) can be added. Contribute to the project here:

https://github.com/eitrtechnologies/saltext-prometheus

Docs are in process, and will live on Read the Docs.
