### ISSUE TITLE
[BUG] Unexpected minion timeouts when running `manage.down`

### ISSUE THREAD

**Issue by paladin8** [saltstack/salt#61237]
**Description**
I'm trying to periodically run `manage.down` to handle minions that are dead (autoscaling). When I do so, if there happens to be another command running on the cluster (e.g. highstate), it's often the case that the highstate reports that a number of minions (that are still up) have timed out. I suspect there is some interaction between the `timeout` and `worker_threads` parameters, but I haven't been able to come up with a fix.

**Setup**
Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [X] VM running on a cloud service, please be explicit and add details **(AWS)**
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

We're running a pretty large salt deployment (3-4k minions) on a `c4.4xlarge` master (8 logical cores, 30GB memory).

Relevant `/etc/salt/master` lines:
```
verify_env: True
master_sign_pubkey: True
state_output: terse
timeout: 30
pillar_source_merging_strategy: recurse
worker_threads: 128
keep_jobs: 8
job_cache: False
```
  
**Steps to Reproduce the behavior**
1. From the master, run a `highstate` across ~100 nodes normally. Things work fine and it takes 30s - 1m.
2. From the master, run a `highstate` across ~100 nodes, but then trigger `salt-run manage.down` as well a few seconds afterwards. `manage.down` will complete fine, but many of the minions will time out on the highstate despite being up.
3. Repeat step 2 but add a timeout to `manage.down` (e.g. 10s). Fewer minions time out, but some still do.

**Expected behavior**
I expect the highstate to successfully run on all nodes that are up regardless of whether a `manage.down` happens to be running or not.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.2
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1022-aws
         system: Linux
        version: Ubuntu 16.04 xenial
 
```
</details>

**Additional context**
It's possible there is no "bug" here in the strict sense. But guidance on how to avoid this scenario would be equally helpful. Thanks!

**Comment by paladin8** [comment]
Hi @krionbsd or whoever takes a look at these, any chance you could provide some pointers on what the issue might be? Any hints at what path to explore would be super helpful for us to debug this issue in our production system. Thanks!

**Comment by whytewolf** [comment]
@paladin8 I'm looking at this now but there are some issues right off the bat that might be adding to the problems. 

`worker_threads` should never be higher then 1.5 times the number of cpus. this can cause the master to become unresponsive in high load systems. or minions to lose connection and reconnect as the multiplexing of the threads doesn't happen quick enough for the cpus to handle all of the threads in a timely manner for tcp timeout. 

another is you are using an outdated version of salt. It is possible that some of the issues might have been fixed if there was code issues that caused this. there have been 5 major releases since the last release you are using. 

next an understanding of `manage.down`. manage.down works by sending a test.ping across `*`. with 3-4k minions you are flooding your network with traffic. and since you are doing this during a highstate the master is also busy rendering pillars and tracking highstate events as they come in. mixed with threading multiplexing issues cause by way to many worker_treads for the number of cpus on the system the master most likely is missing events. with the amount of events happening you might also be hitting the zmq high water marks and dropping events.

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity.  If the issue persists please feel free to open a new issue.
