### ISSUE TITLE
[FEATURE] schedule state/module not working without minion running

### ISSUE THREAD

**Issue by p3lim** [saltstack/salt#61324]
**Description**

Setting up a schedule while the minion is not running gives an error "Failed to add job X to schedule.".

This needs to be more verbose, specifically stating either in the docs or in the error that the minion needs to be running before a schedule can be added.

Or better yet, configure the schedule (in `/etc/salt/minion.d/_schedule.conf`) without requiring the minion to be running.

**Steps to Reproduce the behavior**

1. Disable minion
2. Add anything to the schedule, e.g. with `salt-call schedule.add foo`

**Expected behavior**

The schedule should be added, or a descriptive reasoning as to why it couldn't be added should be returned.

**Versions Report**

This happened to all hosts we've upgraded from py2 to py3, specifically 3003.3 and 3004.

**Comment by garethgreenaway** [comment]
@p3lim Thanks for the report.  This is expected behavior.  The schedule module and schedule state module utilize the Salt event bus to add a scheduled job to the running minion, if the Salt minion is not running then the event bus for the minion is unavailable.  The above functionality would require an update to the modules, which is doable, to fall back to simply writing the files out on the minion rather than adding to a running minion.

**Comment by Adam-Zvolanek** [comment]
It looks like this bug has re-appeared, currently running salt-minion version 3006.1 and with the salt-minion not running it fails to apply the scheduling state. Likewise occurs when running salt-minion 3006.2.
