### ISSUE TITLE
[FEATURE REQUEST] pillar.file_exits to work wil git_pillar

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#61508]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
User would like to use pillar.file_exists with git_pillar

**Describe alternatives you've considered**
informed user about ignore_missing

**Additional context**
uswer is looking to auto detect files in pillar using git_pillar

**Please Note**
thinking about how git_pillar works I'm not sure if this is currently possible so maybe a sep would be required to make sure git_pillar is updated allowing this kind of functionality.

**Comment by dmurphy18** [comment]
@whytewolf The documentation for pillar.file_exists is here https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.pillar.html#salt.modules.pillar.file_exists and it states
```
Will only work with pillar_roots, not external pillars.
```
To utilize git_pillar have to use GitPython (in maintence mode) and pygit2.

There are ways to utilize GitPython to access and check if a file exists, see https://stackoverflow.com/questions/10466449/checking-if-an-object-is-in-a-repo-in-gitpython

And with pygit2 similar functionality could be achieved by walking the index etc. to check if the file exists within the repo for the provided branch/tag/version etc.

I think this should be a SEP given the issues in providing this functionality, for example: support GitPython ? since in maintenance mode, would it make sense. The versions of pygit2 and associated libgit2 had to be matched in the past (I hear it has gotten better with recent releases) and as such, requests to include them as part of the packages delivered by Salt have been rejected for over 7 years.

A SEP would be best to discuss and explore all issues as to whether Salt should provide such functionality.

I believe this should be turned into a SEP and close this issue

**Comment by dmurphy18** [comment]
This issue is being tracked in SEP https://github.com/saltstack/salt-enhancement-proposals/pull/61.
Closing this issue and all further discussion should occur in the SEP
