### ISSUE TITLE
Salt masters with version of 3004.1.el7 don't work with minions of version 3004.1-1.el7

### ISSUE THREAD

**Issue by sudo-justinwilson** [saltstack/salt#61874]
**Description**
We have discovered that salt masters that have a salt version of `3004.1.el7` don't work with minions that have a salt version of `3004.1-1.el7`:

```
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[ERROR   ] Error while bringing up minion for multi-master. Is master at salt-cdc responding?
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] "salt-cdc" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://10.23.4.12:4506
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/minion', 'pau1XXXXXXX001', 'tcp://10.X.x.x:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (3608)
[DEBUG   ] Setting zmq_reconnect_ivl to '3608ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.x.x.x:4506
[DEBUG   ] Trying to connect to: tcp://10.X.X.X:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[ERROR   ] Sign-in attempt failed: {'enc': 'pub', 'pub_key': '-----BEGIN PUBLIC KEY----XXXXXXXXXXXXXXXXXXXX
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ X] VM running on a cloud service, please be explicit and add details <= (The salt hosts were Azure VMs running CentOS)
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Use a salt master with version of `3004.1.el7` and minions with a version of `3004.1-1.el7` and `salt` doesn't work

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by garethgreenaway** [comment]
@sudo-justinwilson Thanks for the report.  Please ensure that your Salt masters are running the latest version from the CVE release.  Generally speaking older minions will work with newer masters, but newer minions are not always guaranteed to work with older masters.

**Comment by dahrens** [comment]
https://github.com/saltstack/salt/blob/d1811dd828fcef9769f61e5c0253a117144f7777/doc/topics/releases/3004.1.rst#id1

**Comment by PeterS242** [comment]
So why was there not any general warning about the complete abandonment of all *slightly older* Salt Masters?  And why is there no easy-to-enable workaround to allow access to the older Salt Masters in case a client is not able to schedule an emergency update to an older Salt Master?

You've also removed all access to the older Salt Minions, so said clients will be left in a non-functional state if they allow their Minions to update themselves.  This sounds like a recipe for disaster.

Other organizations broadcast a "major API client/server breaking update" prior to its release, and they also provide a method by which you can at least _downgrade_ in order to continue to function in a production state and allow for upgrading later as needed.  However SaltStack has provided no such means.

The moral of the story is to keep full mirrors of the SaltStack repositories local to your company at all times, since SaltStack can not be expected to act appropriately to security responses.

**Comment by OrangeDog** [comment]
There's a general warning here: https://docs.saltproject.io/en/latest/topics/installation/#upgrading-salt

It is a bit odd that for most releases, which don't break comms, there has been an additional warning in the release notes, but not in this one.
