### ISSUE TITLE
[BUG] pkg.latest broken on FreeBSD when searching by origin

### ISSUE THREAD

**Issue by ari** [saltstack/salt#61889]
**Description**

With state like this:

```yaml
zabbix_agentd:
  pkg.latest:
    - pkgs:
      - security/sudo
```

this error is thrown

```
          ID: zabbix_agentd
    Function: pkg.latest
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python3.8/site-packages/salt/state.py", line 2179, in call
                  ret = self.states[cdata["full"]](
                File "/usr/local/lib/python3.8/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/local/lib/python3.8/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/local/lib/python3.8/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/local/lib/python3.8/site-packages/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.8/site-packages/salt/states/pkg.py", line 2685, in latest
                  avail = __salt__["pkg.latest_version"](
                File "/usr/local/lib/python3.8/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/local/lib/python3.8/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/local/lib/python3.8/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/local/lib/python3.8/site-packages/salt/modules/pkgng.py", line 316, in latest_version
                  pkgver = pkg_output.rsplit("-", 1)[1]
              IndexError: list index out of range
```

The same error can be reproduced with just

```
salt-call pkg.latest_version security/sudo -l trace
```

**Versions Report**

```yaml
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.15.0
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.14
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.12.0
        pygit2: Not Installed
        Python: 3.8.12 (default, Mar 10 2022, 23:10:14)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: freebsd 13.0
        locale: utf-8
       machine: amd64
       release: 13.0-RELEASE-p6
        system: FreeBSD
       version: FreeBSD 13.0
```

**Comment by ari** [comment]
The problem in the code is that it calls this function:

```
pkg search -eqS origin -U security/sudo
```

Which return just `security/sudo` with no version at the end. And therefore the rsplit fails. A more robust approach might be to call 

```
pkg version -O security/sudo
```
Or something like that and allow FreeBSD pkg to itself work out whether the version is upgraded or not.

**Comment by network-shark** [comment]
A year ago I tried to fix it , but failed there were so many edge cases , but I have never used the "ports" syntax. 

Currently I don't have a freebsd machine with ports installed , but how does it look like if you have different node version ? Like node14 and node11 . Does ports provide a folder for each version ?

**Comment by ari** [comment]
I am not sure what you mean by "ports" syntax. None of this operates on ports, only pkg.

`pkg version` has the origin syntax (security/sudo) and the name syntax (sudo). And it also has the -l parameter which returns only if the pkg needs upgrading.

```
# pkg version -l \> -O security/sudo
sudo-1.9.10                        >
```

Using this command seems a lot more robust than parsing the output of pkg search.

**Comment by network-shark** [comment]
For me port syntax means pkg install security/sudo

I never to it I just do pkg install sudo

**Comment by ari** [comment]
They both work the same way and you don't need to have ports installed

**Comment by asomers** [comment]
I ran into this problem too.  A good fix for `pkg.latest_version` is this:
```diff
--- a/salt/modules/pkgng.py
+++ b/salt/modules/pkgng.py
@@ -299,12 +299,7 @@ def latest_version(*names, **kwargs):
     pkgs = list_pkgs(jail=jail, chroot=chroot, root=root)
 
     for name in names:
-        cmd = _pkg(jail, chroot, root) + ["search", "-eqS"]
-        if "/" in name:
-            # FreeBSD's pkg supports searching by origin, like java/openjdk7
-            cmd.append("origin")
-        else:
-            cmd.append("name")
+        cmd = _pkg(jail, chroot, root) + ["search", "-eqL", "name"]
         if not salt.utils.data.is_true(refresh):
             cmd.append("-U")
         cmd.append(name)
```
That will cause `pkg search` to return the package name and version regardless of whether the search string is a package name or an origin.  And pkg already knows how to detect whether you're searching for an origin.
However, fixing `pkg.latest_version` is only half the story.  Fixing the `pkg.installed` state is harder.  That's because on FreeBSD you can't install a specific version of a package when specifying an origin.  That is, you can't do `pkg install security/sudo-1.0.0`.  So fixing the state would require either:
* Adding special cases in the `pkg.installed` and `pkg.latest` states when dealing with origins, or
* Changing the `pkg.latest_version` command to return the package name as well as the version, but that would require corresponding changes in the other modules and in the pkg state too.

**Comment by asomers** [comment]
Could a Salt maintainer please retitle the bug to "[BUG] pkg.latest broken on FreeBSD when searching by origin"?

**Comment by dmurphy18** [comment]
Closing this since Salt is currently not testing against FreeBSD with onedir packaging.

**Comment by asomers** [comment]
What is onedir packaging, and why does the validity of the bug depend on Salt's test coverage?

**Comment by dmurphy18** [comment]
@asomers onedir packaging is where the Salt package is self contained, including all dependencies for running Salt, including Python, (3.10.11 at the moment).  Allows Salt to work on older platforms such as RHEL 7 & 8 where Python 3.6 (long EOL) and old OS dependencies, with the most current versions, rather than having to use out of date dependencies with known CVEs.  Not a problem with Ubuntu 22.04 or RHEL 9, but some day they will be old too.

Part of the problem with FreeBSD is that @krionbsd left Salt, and don't have a knowledgeable person / maintainer for FreeBSD to keep that platform current, and with limited resources, FreeBSD is a reasonable  effort , see https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-supported-operating-systems.html.

It is not just a FreeBSD issue either, with 3006.x, we dropped support for native minions on AIX, Solaris 10 & 11, Arista and Juniper (aka FreeBSD v10.x under the covers) too, also 32-bit Raspberry PI Raspbian OS (since now pushing ARM64 support with 3006 and up).

With 3006, Salt moved to new automation using GitHub actions, and this was part of the reason for dropping support for various OS's, given what resources available and time / effort / return / etc. discussions.

**Comment by asomers** [comment]
Ok so there's a resource shortage. But why mark the issue as "completed"?

**Comment by network-shark** [comment]
> Closing this since Salt is currently not testing against FreeBSD with onedir packaging.

@dmurphy18
Correct me if I am wrong , there was never gitlab pipeline or any pipeline for freebsd ..., so nothing has changed. It's really bad for the freebsd support that @krionbsd left the company , but salt still remains open source ... Maybe other maintainers will jump in.
Just closing freebsd issues should not the way to go.

**Comment by krionbsd** [comment]
@network-shark we had CI pipelines for 2 different FreeBSD versions iirc
