### ISSUE TITLE
Ubuntu 16.04 py3 apt repository has disappeared

### ISSUE THREAD

**Issue by pnickerson-cashstar** [saltstack/salt#61900]
### Description of Issue
The Salt Project APT repository for Python 3 on Ubuntu 16.04 has disappeared. I think this just happened in the past couple hours.

I know Ubuntu 16.04 has been out of Canonical's mainline support for a long time now, but Salt Project's documentation appears to indicate it is still supported up to version 3002.8 [click the Ubuntu 16 (xenial) PY3 button here]: https://repo.saltproject.io/3002.html#ubuntu

I have a few Ubuntu 16.04 servers. Earlier today, this APT sources list worked fine:
`deb https://repo.saltstack.com/py3/ubuntu/16.04/amd64/latest xenial main`
But now I get this when I run apt update:
```
Err:8 https://repo.saltstack.com/py3/ubuntu/16.04/amd64/latest xenial Release
  404  Not Found
```

On another Ubuntu 16.04 server, I tried running `bootstrap-salt.sh` from https://bootstrap.saltproject.io. I was able to run that script fine earlier today, but now I get this error:
```
 * ERROR: https://repo.saltproject.io/py3/ubuntu/16.04/amd64/latest/salt-archive-keyring.gpg failed to download to /tmp/salt-gpg-WIbbcJw9.pub
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!
```

If I visit https://repo.saltproject.io/py3/ubuntu/ in my web browser, 16.04 is not listed.

https://archive.repo.saltproject.io/py3/ubuntu/ does have `16.04`, but there is no `latest` directory under `amd64`, so this documentation does not work: https://docs.saltproject.io/en/latest/topics/installation/ubuntu.html
`sed -i 's/repo.saltproject.io/archive.repo.saltproject.io/g' /etc/apt/sources.list.d/salt.list`
Also, if I'm seeing this right, `archive.repo.saltproject.io` has version `3002.7` available but no `3002.8`.

### Setup
Ubuntu server 16.04.7 LTS (Xenial Xerus)

### Steps to Reproduce Issue
Following the instructions at https://repo.saltproject.io/3002.html#ubuntu for Ubuntu 16 (xenial) PY3, try to download https://repo.saltproject.io/py3/ubuntu/16.04/amd64/3002/salt-archive-keyring.gpg

Expected result: Successful download.
Actual result: 404 Not Found

Or, taking from https://github.com/saltstack/salt-bootstrap (where Ubuntu 16.04 is mentioned a few times), run this on an Ubuntu 16.04 server:
```
curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
chmod +x bootstrap-salt.sh
./bootstrap-salt.sh -x python3
```

Expected result: Successful script run with Salt minion installed and no errors.
Actual result: Script exists with error downloading `salt-archive-keyring.gpg` (see above).

### Versions Report
N/A (Salt is not installed)

**Comment by mbochenk** [comment]
From my side: seem everything in archive was cleaned up. https://repo.saltproject.io/py3/redhat/8/x86_64/archive/
Currently there are only 3 versions available. 
While in the past archive had archived versions too. Documentation still points to archive as a way to pin to a minor release. https://repo.saltproject.io/3002.html#rhel

There is no update in the docs to indicate that all minor versions except latest will be removed either.

**Comment by OrangeDog** [comment]
As an unsupported OS it has been moved to the archive repos, as detailed above.
This should have been done a year ago, but better late than never.

**Comment by mbochenk** [comment]
@OrangeDog I do not see it in archives at all. I also do not see 3001 in archive.

**Comment by mbochenk** [comment]
P.S. there is no archive for ubuntu btw: https://repo.saltproject.io/py3/ubuntu/

**Comment by OrangeDog** [comment]
Sorry, I should have checked first.

**Comment by OrangeDog** [comment]
Yes, 3003 and 3004 should have been moved there, not just deleted.

**Comment by arsiesys** [comment]
```
Err:12 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/archive/3002.7 focal Release
  404  Not Found [IP: 54.230.102.28 443]
```
Seems it was a more global cleaning.. did we miss an announcement regarding this surprise deletion?

**Comment by mbochenk** [comment]
I think the policy was "we keep two **previous** releases, all versions, besides current, in repo, and everything else in archive repo" or something along these lines. 3002.7 is missing, only 3002.8 is available.
Meanwhile in archive repo 3002 thru 3003.7 are available, but 3002.8 is not present. Previously it was stated that it is due to archiving reasons and the two previous versions on main repo should be enough.
For example, we cannot move to 3003.x versions due to a bug that made us to roll back, and 3004.1 needs investigation.

**Comment by dmurphy18** [comment]
@pnickerson-cashstar Closing this, the reason for the move is as follows:

- Salt only supports OS's till they End Of Life (EOL), ESM is not supported
- Ubuntu 16.04 is EOL
- All builds of 16.04 are affected by the most recent CVE, hence they are moved to archive.repo.saltproject.io
- 3002.8 is not built for Ubuntu 16.04 since it has been EOL for just a year

**Comment by d-shi** [comment]
@dmurphy18 this issue actually affects all versions of all OSes, because all versions of salt 3003.X were removed for all OSes (including Ubuntu 18.04 and 20.04 which are not EOL), except for the latest version. This broke our production environment as well (we're running 18.04 and 20.04), as we were running 3003, and 3003.4 introduces breaking changes for us that we haven't been able to resolve yet. We were forced to point everything to https://archive.repo.saltproject.io in order to resolve the issue.

**Comment by pnickerson-cashstar** [comment]
Ok, I see that 3002.8 was released 4 days ago. It was available under `https://repo.saltproject.io/py3/ubuntu/16.04/amd64/latest/` for a few days. Was that a mistake? Meaning, was it never meant to be released for installation on Ubuntu 16.04?
https://github.com/saltstack/salt/releases/tag/v3002.8

I see the CVE you mention. I get that an urgent release like this can require some last minute repository reshuffling.
https://saltproject.io/security_announcements/salt-security-advisory-release/

But there are still some non-working documentation and scripts out there.

https://repo.saltproject.io/3002.html#ubuntu
The Ubuntu (xenial) PY3 button has you try to use `repo.saltproject.io`, which now won't work. Also, the Pin to Minor Release page shows that 3002.8 was once available for Ubuntu 16.04: `https://repo.saltproject.io/py3/ubuntu/16.04/amd64/archive/3002.8`

https://bootstrap.saltproject.io/
This script fails with a failure to download error when run on Ubuntu 16.04. I think the script should be updated to use `archive.repo.saltproject.io`, or it should exit with a message saying that Ubuntu 16.04 is unsupported.

https://docs.saltproject.io/en/latest/topics/installation/ubuntu.html
Simply replacing `repo.saltproject.io` with `archive.repo.saltproject.io` in the apt sources list file might not work, since the bootstrap script puts `https://repo.saltproject.io/py3/ubuntu/16.04/amd64/latest` into `/etc/apt/sources.list.d/salt.list` and `https://archive.repo.saltproject.io/py3/ubuntu/16.04/amd64/latest` does not exist. People finding this page trying to figure out how to make Salt work on Ubuntu 16.04 after running the bootstrap script will find instructions that do not work for their systems.

https://github.com/saltstack/salt-bootstrap#readme
Ubuntu 16.04 is explicitly listed as a supported operating system.

I'll see if I can find all the right places to report these issues as new bugs.

I was able to get version 3002.7 installed on my servers by running this:
```
curl --fail --silent --show-error --location --output /usr/share/keyrings/salt-archive-keyring.gpg https://archive.repo.saltproject.io/py3/ubuntu/16.04/amd64/3002/salt-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg arch=amd64] https://archive.repo.saltproject.io/py3/ubuntu/16.04/amd64/3002/ xenial main" > /etc/apt/sources.list.d/salt.list
apt update
apt install salt-minion
```

**Comment by pnickerson-cashstar** [comment]
@d-shi I'm guessing that due to the CVEs at https://saltproject.io/security_announcements/salt-security-advisory-release/, Salt Project needed to remove all vulnerable versions of Salt packages from `repo.saltproject.io`, and store those vulnerable builds on `archive.repo.saltproject.io` instead. The CVE announcements say that 3003.4 is patched, implying that all the previous 3003 versions are vulnerable.

Oh, and now I see that the linked CVE page does say that Ubuntu 16.04 doesn't get the patched Salt, which makes sense.

**Comment by dmurphy18** [comment]
@pnickerson-cashstar The Ubuntu 16.04 release for 3002.8 was a mistake, the automated build tools had an error and hence it was built mistakenly.  BTW: it did not work since there it needed a python3-distro dependency.  That Ubuntu 16.04 Salt 3002.8 does not exist in archive.repo.saltproject.io.

**Comment by d-shi** [comment]
@pnickerson-cashstar Yes the affected versions were pulled due to the CVE, but IMO that is not the right thing to do. You don't see other software vendors just yank old versions completely. Instead, announcements are made to tell people to upgrade, and people can upgrade on their own schedule. This instead just breaks people's environments without warning. Secondly, there are typically patch versions that are published when these things happen for supported version branches. In this case, we cannot even upgrade to the unaffected version because other major breaking changes have been introduced.

**Comment by dmurphy18** [comment]
@pnickerson-cashstar The process of moving CVE Releases has been standard practice for some years, and has been mentioned in Open Hours and documented.  Leaving swiss cheese for production systems to be comprised is not a safe practice.

**Comment by d-shi** [comment]
@dmurphy18 I'll just say one more thing and then I'll go away:

I think you all should reconsider this strategy. As many have pointed out already, it creates further distrust of Saltstack as an organization from operations teams who have to deal with the fallout of these decisions. It will push them away from Saltstack towards other solutions. Saying nonchalantly that you would rather break our production environments than leave them vulnerable to CVEs is a fairly hostile position to take, and it is furthermore not really your call to make. If we want to run with vulnerable code that is our choice. We can mitigate the issues in a number of other ways, but what you have decided to do is provide us an incident without warning instead.

There is no other software provider I can think of that has this process of rolling out CVE updates. In all other cases patch versions are introduced where only the CVE mitigation commit(s) are patched on top of existing supported branch versions, and communication is sent out for people to upgrade to those mitigated versions. However, the vulnerable versions are not immediately pulled since that would cause guaranteed breakage versus just risk of breakage due to the CVE. Saying that you don't guarantee breaking changes in minor versions is also fairly hostile stance to take towards your users. If you are going to introduce breaking changes in minor versions, then it is necessary to keep older versions in the main repo. Otherwise you are giving users the choice of either breakage due to the breaking change in the newer version or breaking because you can't even install any other version.

**Comment by dmurphy18** [comment]
@pnickerson-cashstar  Usually we keep all versions available as long as possible, case in point being Ubuntu 16.04 Py3, even though it has been EOL for just about a year.

Unfortunately the CVE meant we had to move CVE affected releases, and this has been the policy since 2019 when there was a very severe CVE.

However your points are well taken and are being brought to the attention of the relevant parties.  There is an on-going internal debate as to making an LTS branch and a non-LTS branch similar to Ubuntu. This may migrate the issues you are raising.  Your points and others in the community are raising similar issues will hopefully be addressed in the future.

**Comment by mbochenk** [comment]
@dmurphy18 In the past we were told that two previous versions - 3002 and 3003 in this case - would be kept in the the main repo, excluding maybe critical vulnerabilities for selected versions. This works for me. 

However what does not work for me is Debian, Ubuntu, RHEL and others having ONLY latest, without prior versions.
I would not complain about that if archive repo would hold ALL versions (including latest). Archive does not need "latest" symlink either, I just need to be sure I can update versions.
If updates in between minor salt versions were simple, That would not be a big issue. However multiple times we were running into issues that prevented such updates.
This question was raised multiple times in many discussions and we were told a couple of time that our concerns are heard and that is why two supported versions will have previous versions available in repo, and archive will be exclusively used for archiving purpose.

This was discussed multiple times and was a previously discussed policy. If that has changed, can we be pointed to where and when? Because if this change was "silent" it is not a good thing, or if the previous explanation of the policy was, in fact, incorrect and should be stated again on the front page of the repo (as it was for around a year when switching to new policy)

**Comment by dmurphy18** [comment]
@mbochenk ALl previous releases were affected by the CVE, hence there movement to the archive repo, as you mentioned in your first sentence.

The archive repo holds all releases that have been archived, and those currently supported are held on rep.saltproject.io, and that has always been the policy.  See my previous comment, actively discussing LTS release internally, perhaps this could resolve some of the issues you raise.  It would be great if you could attend the Open Hours and raise your concerns, every other Thursday, see Announcements in Salt Community Slack https://app.slack.com/client/T7KPDM7M3/CNZKJMQ1E/thread/C7K4F0L8H-1648897745.534539.

**Comment by jerrykan** [comment]
I just want to add to what the others have said about this breaking production deployments. It should be up to the people management the Salt deployment to do a risk assessment and decide how and when and upgrades should take place. This is not a decision the Salt project can (or should) make for someone else because every deployment is different. I believe yanking versions from repositories can also be counter-productive because by breaking exiting Salt deployments it can actually hinder managing the rollout of package upgrades.

The main issue as I see it though is that there is no immutable repo for installing a specific version of Salt. If I install the latest version of Salt from `repo.saltproject.io` and want to pin my deployment to that version then I risk that at any time that version will be yanked an moved to `archive.repo.saltproject.io`. The alternative is to use a version from `archive.repo.saltproject.io` to start with but that limits me to versions that are already out of date. If new packages were published to `archive.repo.saltproject.io` at the same time as they are published to `repo.saltproject.io` it would greatly improve the situation.

**Comment by mbochenk** [comment]
^this

**Comment by mbochenk** [comment]
Did anyone mention this doc?
https://repo.saltproject.io/3003.html#other
see here: 

> End of Life Support for Ubuntu 16.04 ended in April 2021. 3001.x and 3002.x are the last Salt releases for which Ubuntu 16.04 packages will be created.

Does not this mean that 16.04 packages still have to be created for 3001 and 3002?

**Comment by dmurphy18** [comment]
@mbochenk No, it means that there will be no 3003.x and 3004.x versions built.  Also it means that whatever version of 3002.x at the end of April 2021 is the last version to be built for Ubuntu 16.04, that is, 3002.x is short-hand for whatever minor version of 3002, in this case it was 3002.7.

It is the Salt Projects policy to not support OS's when free security updates are no longer available, hence no support for ESM , only Standard End of Life, as stated in https://wiki.ubuntu.com/Releases

**Comment by mbochenk** [comment]
Frankly this reads that they will still be created. Please update the wording in that case.

**Comment by rjc** [comment]
>     * 3002.8 is not built for Ubuntu 16.04 since it has been EOL for just a year

@dmurphy18 That's fine - I understand all of this. However, the issue is that your [web page](https://repo.saltproject.io/3002.html#ubuntu) *still* references it and, until it is fixed, you'll be getting bug reports about it so 3002.8 should either:

1. Be built for Ubuntu 16.04 (which it seems like it was for a spell - #61883)*and* moved to _archive.repo.saltproject.io_, or
2. The web page needs fixing.

It seems strange that broken packages got published and, subsequently, removed rather than getting fixed but, given that you're saying you're not going to do any more builds for _EOL_ systems, the only viable option is 2.

I would have sent a PR but that part of your website is not in any of the repositories.

**Comment by OrangeDog** [comment]
#61905

**Comment by pnickerson-cashstar** [comment]
In addition to commenting on @OrangeDog's [linked issue](https://github.com/saltstack/salt/issues/61905), I opened up two new issues for fixing documentation elsewhere since Ubuntu 16.04 is no longer supported:

Remove Ubuntu 16.04 as supported OS, or fix script · Issue #<span></span>1822 · saltstack/salt-bootstrap
https://github.com/saltstack/salt-bootstrap/issues/1822

[DOCS] Installation instructions still mention Ubuntu 16 (Xenial) · Issue #<span></span>61985 · saltstack/salt
https://github.com/saltstack/salt/issues/61985
