### ISSUE TITLE
states.supervisord restart option should not exist

### ISSUE THREAD

**Issue by olliewalsh** [saltstack/salt#6218]
The restart option in the supervisord state always restarts the given program group.

This feels completely wrong. This isn't a state. If it were it would be called 'restarted', not 'running'. It's a command, and modules.supervisord.restart already exists to do this.

If the state of the program group is being managed by salt e.g the virtualenv, pkg, etc... then a watch should be used.

If the state of the supervisor program group is being managed outside of salt states then it should be restarted outside of salt states.

**Comment by jacobhammons** [comment]
Checked the docs and restart is no longer there, closing.

**Comment by 62mkv** [comment]
have just wasted 2 hours or so bumping the wall with my head on this :)) 

Someone (I actually know who) wrote a "supervisord.running" state and included "restart=False" as an option. Thus "watch" actually did nothing, because it has "restart=True" ONLY if the state itself has not "restart" in options. And specifying "restart=True" ALWAYS restarts a service ! 

In retrospect, it sort of seems logical, but still... :) was very annoying experience
