### ISSUE TITLE
Add saltstack repo for Ubuntu jammy (22.04)

### ISSUE THREAD

**Issue by korjek** [saltstack/salt#62202]
So far repo for Ubuntu jammy (22.04) is [missing](https://repo.saltproject.io/py3/ubuntu/).
Would be great if it's added.

**Describe alternatives you've considered**
So far we use Ubuntu focal (20.04) repo to install salt-minion.

**Comment by Foorack** [comment]
Related to https://github.com/saltstack/salt-bootstrap/issues/1821

**Comment by Foorack** [comment]
I see. I was incorrect when I said "3005 was released". **3005rc1** was released, a pre-release. 3005 has not yet hit stable.
This means 3005 has not yet landed in repo.saltproject.io, which is a severe problem for 22.04 support.

According to https://github.com/saltstack/salt/issues/62229, salt-master has a problem with python 3.10, which jammy comes with by default. This was fixed in **3005rc1**, so we first need to wait for 3005 to hit stable before 22.04 can be added to the APT repo.

**Comment by garethgreenaway** [comment]
3005 is available for Ubuntu 22.04.  Closing this one out.
