### ISSUE TITLE
[FEATURE REQUEST] Pip Migration Option for Tiamat Installs

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#62361]
**Is your feature request related to a problem? Please describe.**
With the move to Tiamat based packages.the salt package needs to maintain it's own installed Python modules.  For those migrating from non-Tiamat packages having a tool available to install Python libraries previously installed to the system via PIP into the Tiamat installation.

**Comment by OrangeDog** [comment]
A lot of people would have been installing to the system python with their system package manager rather than pip, as the latter is discouraged (and gives you warnings in later pip versions).

Is the idea to look in the system python in general for packages that are known to be used by a salt module? That would cover both cases.

**Comment by garethgreenaway** [comment]
@OrangeDog Yes.  That is the general idea, so we can make sure that any additional Python libraries that are installed outside of Tiamat are also available inside the Tiamat package.

**Comment by garethgreenaway** [comment]
Ultimately decided that would lead to more problems with installing Python packages into the TIamat environment that are installed n the system that aren't needed by Salt.
