### ISSUE TITLE
[BUG] Salt command names on macOS changed unexpectedly with onedir 3005 release

### ISSUE THREAD

**Issue by sheagcraig** [saltstack/salt#62665]
**Description**
All of the standard salt commands on macOS have had no file type suffix. However, upon installing the new 3005 onedir package, they all have the `.sh` suffix, which leads to none of them being available for use from existing scripts except by updating them all. As none of the documentation for 3005 seems to reference this, I have to imagine this is an accident.

**Setup**
Install https://repo.saltproject.io/salt/py3/macos/latest/salt-3005-1-macos-x86_64.pkg on a Mac.
(Note-these commands won't work and will blow up on arm Macs: https://github.com/saltstack/salt/issues/62664)

**Steps to Reproduce the behavior**
1. Try to run `/opt/salt/bin/salt-call -V`

**Expected behavior**
Salt commands retain their previous names and are called without a `.sh` extension, or are at least symlinked to the `.sh` one.

**Versions Report**
Unfortunately not possible given the openssl issues with ARM Mac right now.

**Comment by twangboy** [comment]
This is because the package you downloaded is a Tiamat package. The paradigm is different for Tiamat packages. There is a single binary called ``salt``. All Salt components are arguments to ``salt.exe``. So, to run a minion, for example, the command would be ``salt minion``. To try to maintain expected behavior, we added the `.sh` scripts to mimic the binaries that used to be present.

If you want a 3005 version with the old binaries, you can download one of the classic packages here: https://repo.saltproject.io/osx/

Starting with 3006, the onedir packages have binaries just like the classic packages. So, it shouldn't be a problem going forward.
