### ISSUE TITLE
[DOCS] pillar.saltclass has broken link

### ISSUE THREAD

**Issue by jensgw** [saltstack/salt#62970]
**Description**
The site for pillar.saltclass refers to examples located at "http://git.mauras.ch/salt/saltclass/src/master/examples".
However, the mentioned site does not exist.

**Suggested Fix**
Fix the link? Provide own examples?

**Location or format of documentation**
[DOC LINK.](https://docs.saltproject.io/en/latest/ref/tops/all/salt.tops.saltclass.html#module-salt.tops.saltclass)

**Comment by barbaricyawps** [comment]
Closing since this is a duplicate. We have a lot of broken link problems in the docs and I think the solution is to implement a broken link pre-commit check into the docs and then do a massive fix of them. I'll investigate what that would entail. I opened an issue to track this work: https://github.com/saltstack/salt/issues/62981
