### ISSUE TITLE
[DOCS]

### ISSUE THREAD

**Issue by SLiMann** [saltstack/salt#63508]
**Description**
They python command is no longer valid for salt.modules.linux_shadow.set_password

**Suggested Fix**
salt.modules.linux_shadow.set_password
python -c "import crypt; print crypt.crypt('password', '\$6\$SALTsalt')"
Update to:
python3 -c "import crypt; print(crypt.crypt('password', '\$6\$SALTsalt'))"

**Type of documentation**
Salt documentation, Salt modules

**Location or format of documentation**
[Insert page URL if applicable.](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.linux_shadow.html#salt.modules.linux_shadow.set_password)

**Additional context**
https://stackoverflow.com/a/51104708

**Comment by barbaricyawps** [comment]
I'll defer to @OrangeDog 's judgment here (thanks for triaging, btw). Since this issue isn't actionable, I'm closing it. @SLiMann , feel free to re-open it if you disagree and think this issue is still needed. If you do decide to re-open it, please assign a clearer title besides just "Docs" and provide more information about what clarity is needed.
