### ISSUE TITLE
Add support for Arch Linux variants (e.g., EndeavourOS, Manjaro, etc.)

### ISSUE THREAD

**Issue by jmuchovej** [saltstack/salt#63887]
👋 Some of my computers use derivatives of Arch Linux, so I was hoping they could be supported by `salt`. To my knowledge they're predominantly desktop-oriented flavors of Arch, but that's only because some of the computers I manage double as "servers" and user desktops (or because it was the only straightforward way to install Arch on ARM).

It seems that these lines need to be changes so `pacman` is properly used, but I want to double-check that this is all that needs to be changed to add support for these flavors.

https://github.com/saltstack/salt/blob/e5cd6086a75818885f2bd5bee3d7da3b2c07b110/salt/modules/pacman.py#L35-L41

Specifically, I'm looking to add `EndeavourOS` and `Manjaro` (and `Manjaro-ARM`). Does `salt` have a preference towards set/list lookups vs something like... `any([__grains__['os_family'].startswith(os) for os in ['Arch', 'EndeavourOS', 'Manjaro']])`?

(For clarity, I'm asking if `salt` favors exact matches versus partial matches when deciding on the package manager to use.)

**Comment by whytewolf** [comment]
the fix is not there. The correct way to fix something like this is to get the os_family to correctly be identified as Arch. 

that is done through the core grains. it looks like Manjaro should already be supported so try and figure out why it isn't showing up as os_family Arch. EndeavourOS is coming in 3006rc1 already. 

see https://github.com/saltstack/salt/blob/master/salt/grains/core.py#L1811-L1814

**Comment by jmuchovej** [comment]
> it looks like Manjaro should already be supported so try and figure out why it isn't showing up as os_family Arch.

Manjaro on ARM identifies as "Manjaro ARM". I'm pretty sure that's why it's not showing up as Arch.

> EndeavourOS is coming in 3006rc1 already.

Awesome! 🙂
