### ISSUE TITLE
[BUG] Debian APT error during 3006.0 to 3006.1 upgrade

### ISSUE THREAD

**Issue by ymasson** [saltstack/salt#64248]
**Description**
Update APT source.list file with 3006.1 version and run `apt-get update && apt-get dist-upgrade`

```
The following packages will be upgraded:
  salt-common salt-minion
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 40.8 MB of archives.
After this operation, 41.0 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://repo.saltproject.io/salt/py3/debian/11/amd64/minor/3006.1 bullseye/main amd64 salt-minion amd64 3006.1 [76.5 kB]
Get:2 https://repo.saltproject.io/salt/py3/debian/11/amd64/minor/3006.1 bullseye/main amd64 salt-common amd64 3006.1 [40.7 MB]
Fetched 40.8 MB in 2s (20.7 MB/s)      
Reading changelogs... Done
(Reading database ... 59698 files and directories currently installed.)
Preparing to unpack .../salt-minion_3006.1_amd64.deb ...
Unpacking salt-minion (3006.1) over (3006.0) ...
dpkg: error processing archive /var/cache/apt/archives/salt-minion_3006.1_amd64.deb (--unpack):
 trying to overwrite '/etc/salt/proxy', which is also in package salt-common 3006.0
Preparing to unpack .../salt-common_3006.1_amd64.deb ...
Adding group salt....done
Adding system user salt....done
Unpacking salt-common (3006.1) over (3006.0) ...
Errors were encountered while processing:
 /var/cache/apt/archives/salt-minion_3006.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Please be as specific as possible and give set-up details.

- [x ] on-prem machine
- [ x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x ] onedir packaging
- [ ] used bootstrap to install

**Screenshots**
It seem `/etc/salt/proxy` and `/lib/systemd/system/salt-proxy@.service` have been added in `salt-minion_3006.1_amd64.deb`.
Checked with `dpkg -L salt-minion` between 3006.0 and 3006.1 install.

**Comment by smcv** [comment]
This seems to be the relatively common apt/dpkg upgrade scenario where a file moves from one package (salt-common) to a different package (salt-minion), and the upgrade fails because there is nothing telling apt/dpkg what order the packages must be upgraded in, or that it's OK for the copy in salt-minion to overwrite the copy in salt-common.

Workaround:

```
# dpkg -i /var/cache/apt/archives/salt-common_3006.1_amd64.deb
# apt-get --fix-broken install           # upgrades salt-minion
```

This is (at the time of writing) scenario 9 on https://wiki.debian.org/PackageTransition, "Reorg: A and B existed; move some files from A to B; new A does not require new B". In this case, A is salt-common and B is salt-minion.

The solution documented in https://wiki.debian.org/PackageTransition is that salt-common 3006.2 should have `Breaks: salt-minion (<< 3006.2~)`, and salt-minion 3006.2 should have `Breaks: salt-common (<< 3006.2~)` and `Replaces: salt-common (<< 3006.2~)`.

The `Replaces` means that dpkg will be willing to let `salt-minion` overwrite the old `/etc/salt/proxy` from `salt-common`.

The `Breaks` means that apt/dpkg will temporarily allow `salt-common` and `salt-minion` to be at different versions, but only briefly during the upgrade, and the only consistent state is to have them both at the same version (or not have `salt-minion` at all).

**Comment by ymasson** [comment]
@smcv 
since this is only a package issue, shouldn't 3006.1 be rebuilt?
with :
```
diff --git a/pkg/debian/control b/pkg/debian/control
index c830310185..ea946ddc71 100644
--- a/pkg/debian/control
+++ b/pkg/debian/control
@@ -16,6 +16,7 @@ Vcs-Git: git://github.com/saltstack/salt.git
 
 Package: salt-common
 Architecture: amd64 arm64
+Breaks: salt-minion (<< 3006.1~)
 Depends: ${misc:Depends}
 Suggests: ifupdown
 Recommends: lsb-release
@@ -68,6 +69,8 @@ Description: remote manager to administer servers via salt
 
 Package: salt-minion
 Architecture: amd64 arm64
+Breaks: salt-common (<< 3006.1~)
+Replaces: salt-common (<< 3006.1~)
 Depends: bsdmainutils,
          dctrl-tools,
          salt-common (= ${source:Version}),
```

**Comment by smcv** [comment]
> since this is only a package issue, shouldn't 3006.1 be rebuilt?

I don't know how you do change-management for the upstream-provided .deb packages, but it's confusing to reuse the same version number (and therefore filename) for a package with different content, and you've already released a .deb labelled `3006.1`, so it's conventional to avoid doing that.

If you want the ability to do a respin of the same upstream source code but with different packaging, then the version number for that would conventionally be something like `3006.1-0salt1`, `3006.1-0salt2`, ... rather than just `3006.1` (a "non-native" package, with a packaging revision added to its version number).

**Comment by smcv** [comment]
Having a revision number would also avoid publishing the same filename with different content for different Debian releases: for example you could have `3006.1-0salt1.deb10` for a version built for Debian 10, and `3006.1-0salt1.deb11` for a matching version built for Debian 11. [The upstream packages for PostgreSQL](https://apt.postgresql.org/pub/repos/) do something similar.

**Comment by MKLeb** [comment]
This was fixed in a merge forward, closing.  The change will be reflected in the next 3006 dot release.
