### ISSUE TITLE
salt pip install does not work for 3006.1

### ISSUE THREAD

**Issue by zbukhari-apex** [saltstack/salt#64397]
[**Description**
If you look at step 4 [here](https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#how-to-upgrade-to-onedir), you'll see a suggestion to use `salt pip install THING`. This doesn't work anymore with 3006.1. It does work for 3005.1.

I used `salt-pip` to get it to work but when I run a list on 3006.1 I get a lot of packages and my psycopg2-binary, but when I run it for 3005.1 I just get the psycopg2-binary.

**Suggested Fix**
Update the documentation or maybe this is a bug, not sure.

When I try to do `salt pip install THING` it errors out saying no minions matched the target. As I already have it installed I'll show an example with `salt pip list`.

3006.1:

```
$ sudo salt pip list
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

3005.1:

```
$ sudo salt pip list
Package         Version
--------------- -------
psycopg2-binary 2.9.6
```

**Type of documentation**
This could be Salt documentation, Salt modules, the Salt Repo or the Getting Started guide.

**Location or format of documentation**
Insert page URL if applicable.

**Additional context**
](https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#how-to-upgrade-to-onedir)

**Comment by barbaricyawps** [comment]
@zbukhari-apex , we recently did a big update to the docs last week to address this issue, including updating the [install depedencies](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-dependencies.html) page and adding a lot of notices to go to that page. Can you review that doc to see if it resolves your issue?

In particular, I wonder if there's a syntax issue in the command you're trying. The correct command (which came out in the MR review last week) is: `salt-pip install <package name>`. Note the hyphen there. Does that resolve the issue for you or do you still have problems?

The [upgrade to onedir](https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#how-to-upgrade-to-onedir) doc you linked to has the incorrect syntax and I can update that.

Can you confirm it's just a syntax issue? Otherwise, I'll pull in a Salt engineer to troubleshoot the steps.

**Comment by barbaricyawps** [comment]
Here's the MR to fix the command syntax on the topic you linked: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/122

**Comment by Ch3LL** [comment]
Closing as issue was resolved and inactivity from original submitter with requested information. If you are still running into this issue please open a new issue.

**Comment by zbukhari-apex** [comment]
Sorry - didn't mean to be inactive but this was a "suggestion" for clarity so figured I didn't need to be involved anymore. Pretty sure it's good, I'll double check but thanks!
