### ISSUE TITLE
[BUG] Missing repos for Raspberry Pi 3 in onedir path

### ISSUE THREAD

**Issue by didiatworkz** [saltstack/salt#64591]
**Description**
I manage a large number of Raspberry Pis with Saltstack.
They are currently still running on version 3004.2.
Now I wanted to update all the Minions and switch to Onedir and unfortunately, I can't find the source package.
There is no osarch: `armhf` here: https://repo.saltproject.io/salt/py3/debian/10/.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
Goto https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/raspbian.html
See the Banner with the headline: _What is onedir?_
Download the GPG Key
Start to switch the repo to: `deb [signed-by=/etc/apt/keyrings/SALT-PROJECT-GPG-PUBKEY-2023.gpg arch=armhf] https://repo.saltproject.io/salt/py3/debian/10/armhf/latest buster main`
Look at the URL `https://repo.saltproject.io/salt/py3/debian/10/` and see that no `armhf` folder exists.

**Expected behavior**
There is a `armhf` folder with the packages for 3005 and 3006

**Screenshots**
![image](https://github.com/saltstack/salt/assets/18490798/fc21379b-84e2-4356-8977-b5350b0e02b6)
![image](https://github.com/saltstack/salt/assets/18490798/3f40a6d1-1536-4bee-8f56-c7ec9d1a2cb4)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

**Master:**
```
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.31
        Jinja2: 3.1.2
       libgit2: 1.6.4
  looseversion: 1.2.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.12.2
  python-gnupg: 0.5.0
        PyYAML: 6.0
         PyZMQ: 25.1.0
        relenv: 0.12.3
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04.6 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-153-generic
        system: Linux
       version: Ubuntu 20.04.6 focal
```

**Minion:**
```
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Oct 31 2022, 14:04:00)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: raspbian 10 buster
        locale: utf-8
       machine: armv7l
       release: 5.10.103-v7+
        system: Linux
       version: Raspbian GNU/Linux 10 buster

```

</details>

**Additional context**
Not possible to update Raspberry Pi Buster or Bulleseye via onedir

**Comment by OrangeDog** [comment]
Related: #28742

Not sure why it wasn't closed before, because armhf builds _were_ provided.

**Comment by didiatworkz** [comment]
I hope this will not be the case, because that would be a step backwards and not a step forward. Who or when will decide on the issue, because the latest version has already been published for a few days?

**Comment by OrangeDog** [comment]
It is officially not supported, making this an issue with the documentation implying that it is.
https://docs.saltproject.io/en/latest/topics/releases/3005.html#raspberry-pi

**Comment by ScriptAutomate** [comment]
> It is officially not supported, making this an issue with the documentation implying that it is.
https://docs.saltproject.io/en/latest/topics/releases/3005.html#raspberry-pi

That link says the following at the destination:

> **Raspberry Pi**
>
> We will no longer build the Raspberry Pi packages after the 3005 release but will provide open sources project links in an updated announcement later. Please see the announcement for more details: https://saltproject.io/salt-project-announces-the-open-sourcing-of-several-saltstack-native-minions/

The blog post it is referencing wasn't available, but I have now recently restored that blog post referenced above. More blog posts are being restored over time at the moment, due to our website migrating to a static site.

@didiatworkz This means that no new releases after the 3005 release of Raspbian (`armhf`) are to be available. The last built version of salt for Raspbian:

- Raspbian v3005: https://docs.saltproject.io/salt/install-guide/en/3005/topics/install-by-operating-system/raspbian.html
- Example path, for Debian 11: https://repo.saltproject.io/py3/debian/11/armhf/3005/

**Comment by dmurphy18** [comment]
@didiatworkz  You have the c&p associated with ```latest``` but clicked the docs link referenced https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/raspbian.html, and 
```
sudo curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring.gpg https://repo.saltproject.io/py3/debian/10/armhf/latest/salt-archive-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg arch=armhf] https://repo.saltproject.io/py3/debian/10/armhf/latest buster main" | sudo tee /etc/apt/sources.list.d/salt.list
```
Those instructions are correct, they reference ```https://repo.saltproject.io/py3``` which is classic packaging and not 'onedir' which would be ```https://repo.saltproject.io/salt/py3```

```latest``` would be for 3006.1 which only handles ```amd64``` and ```arm64```, since as the documentation states, support for ```armhf``` dropped after 3005, and that information was part of the Salt 3005 Release Notes, so the announcement has been available for some time.

The GitLab repository to build ```arnhf``` will be made available, just has to be cleaned up and transitioned to GitHub, similar to the Native Minions whose support was also dropped after 3005 was released, that is, open-sourced, community supported.  Cannot say when the Raspberry Pi GitLab repository will be made available on GitHub, as not responsible for that repository (different team).

All blog posts didn't fully transition from the old Wordpress ```saltproject.io``` to the latest, but as @ScriptAutomate stated, that one has been restored.  Please forgive the difficulties has the new ```saltproject.io``` comes fully online from the old Wordpress web sote.

**Comment by didiatworkz** [comment]
Hello @OrangeDog and @ScriptAutomate

Thanks fit your quick response and the information you post here.

In that case I will update my Pi devices to v3005 and the rest of the infrastructure to v3006.

I think the classic repos will not be available so long time after the next saltstack versions will be released.

Do you have maybe have here a eol date, too?
Or will the classic repos first go offline until the community packages are created?
Is there any community working right now on such packages?

Best
didiatworkz

**Comment by didiatworkz** [comment]
Alright @dmurphy18 answered my questions 😅

**Comment by OrangeDog** [comment]
Sorry, it was linked in the related issue, but not here. The doc that says there is onedir support for Raspbian is
https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#repository-paths

**Comment by dmurphy18** [comment]
@OrangeDog Thanks for that link, yeah, the Raspbian needs to get removed from onedir repository paths. Created https://github.com/saltstack/salt/issues/64601 for the Doc Fix.

@didiatworkz The Salt 3005 repositories should remain indefinitely, in the past we moved EOL support to the archive repository, and after the outcry from the community, now leave them on repo.saltproject.io and there are no plans to change that policy.  Hence, you should not have any worries about them not being available in the future.

If this addresses your issue, please consider closing it.
