### ISSUE TITLE
[BUG] `salt-cloud` Dev Installation Reports the Permission Error When Valid Config Dir Passed In

### ISSUE THREAD

**Issue by zliang-akamai** [saltstack/salt#64728]
I was following [this doc](https://docs.saltproject.io/en/master/topics/development/contributing.html#salt-tests-documentation-and-you) to setup a dev version of salt

I found `salt-cloud` always report [the permission error](https://docs.saltproject.io/en/master/topics/development/contributing.html#no-permissions-to-access) even with the `-c local/etc/salt` arguments.

```
zhiwei@localhost:~/salt$ pyenv exec salt-cloud --config-dir=/home/zhiwei/salt/local/etc/salt/ -p my-linode-profile-advanced my-linode-instance
No permissions to access "/var/log/salt/cloud", are you running as the correct user?
zhiwei@localhost:~/salt$ pyenv exec salt-cloud --config-dir=/home/zhiwei/salt/local/etc/salt/
No permissions to access "/var/log/salt/cloud", are you running as the correct user?
```

**Comment by garethgreenaway** [comment]
@zliang-akamai Thanks for the report.  The error you're seeing is because Salt is trying to write a log file to the `/var/log/salt/cloud` file and the `var/log` directory is typically owned by the root user, and only that user has permission to write to the files in that directory.  When running the `salt-cloud` command you can avoid this error either by running the command as the root user using the `sudo` command or include the additional `log_file` argument to the `salt-cloud` command by including that in the configuration file you created.

**Comment by zliang-akamai** [comment]
@garethgreenaway Thanks! It solved the problem, but I think it would be nicer if we can update the doc to include this.

**Comment by dwoz** [comment]
This is a bug, not a docs change.. Other salt cli commands will modify the default log path when `root_dir` is set in the config file.
