### ISSUE TITLE
[FEATURE REQUEST] Support verify token using JWKS loaded from https endpoint

### ISSUE THREAD

**Issue by XiyouNiGo** [saltstack/salt#65486]
**Describe the solution you'd like**
Hi, everyone! My team uses JWKS to do authentication for applications, and we had sucessfully intergrated it with some platforms such as Grafana and Opensearch. Now we'd like to use Saltstack to manage our machines. I had read https://docs.saltproject.io/en/latest/ref/auth/all/index.html and https://docs.openstack.org/kolla-ansible/wallaby/reference/shared-services/keystone-guide.html, and I found that Saltstack doesn't support this feature. So it is necessary to support it?
I would be very grateful if you would do so.

**Describe alternatives you've considered**
Develop this feature by myself.

**Additional context**
Saltstack auth intruduction: https://docs.saltproject.io/en/latest/ref/auth/all/index.html
How Grafana did: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/#verify-token-using-a-json-web-key-set-loaded-from-https-endpoint

**Comment by lkubb** [comment]
Can't speak for the team, but I heavily suspect you will have to implement this yourself (unless you're an enterprise customer). Some comments on writing your own (note that I do not have experience with JWKS):

It should not require much work to do so though. You would essentially need to write a Python module that has an `auth` method (`def auth(username, password)`) and returns a boolean result. Optionally, it can provide ACL information via `def acl(username)`, otherwise the definitions from the master config are used. There are several examples to learn from in https://github.com/saltstack/salt/tree/master/salt/auth.

You could use https://github.com/latchset/jwcrypto for the verification, `python-cryptography` is a base requirement of Salt anyways. I would recommend developing it inside a https://github.com/saltstack/salt-extension environment for proper testing (this should be installed from master currently, the last release is from 2021).
