### ISSUE TITLE
[BUG] salt version 3005 not available for py3 ubuntu arm64  https://repo.saltproject.io/salt/py3/ubuntu/20.04/arm64/

### ISSUE THREAD

**Issue by miguelacaro** [saltstack/salt#65575]
**Description**
The 3005 version is not available on the repo on the following url 

https://repo.saltproject.io/salt/py3/ubuntu/20.04/arm64/

The bootstrap script relies on this url for the installation and it´s crashing for that specific version, distro and arquitecture. 
`https://bootstrap.saltstack.com`

The script Returning the error
ERROR: https://repo.saltproject.io/salt/py3/ubuntu/20.04/arm64/3005/salt-archive-keyring.gpg failed to download to /tmp/salt-gpg-OFxX0cpC.pub

Could you please add the version there ?

Thanks.
Regards.

**Comment by dmurphy18** [comment]
https://repo.saltproject.io/salt/py3 contains the OneDir architecture Salt and is for 3006 and up.

Salt 3005 can be found at https://repo.saltproject.io/py3 and has both classic packages which rely OS packages for dependencies, and Tiamat based packages which include all dependencies, that is, salf-contained

3005 will **NOT** be made available on https://repo.saltproject.io/salt/py3 as this is reserved for Salt 3006 and up.

Note: 3005 is reaching end of life (EOL) Feb 25, 2024

**Comment by dmurphy18** [comment]
@miguelacaro Let me know if there is anything else I can help you with on this issue.

**Comment by miguelacaro** [comment]
Hi, and what this is only for the arm64? On the other arch's we nevera had this issue as
https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/

**Comment by dmurphy18** [comment]
@miguelacaro All of 3005 is ONLY on https://repo.saltprojection.io/py3, and not the salt/py3.  This is due to it being classic packaging and Tiamat-based packages.  All of 3006 and up is on https://repo.saltproject.io/salt/py3 and this is due to the new use of GitHub Actions for automation, and use of SHA-256 keys, rather than SHA-1 and SHA-256 for RHEL 89 and Ubuntu 22.04 (which are only Tiamat-based packages).  Salt 3006 uses the Relenv-based packages too (replaces use of Tiamat which had issues supporting pip installs).

Here is the Tiamat-based package for Salt 3005 ARM64 Ubuntu 20.04 https://repo.saltproject.io/py3/ubuntu/20.04/arm64/latest

Note, with the new automation from GitHub Actions, Salt 3006 is also supporting ARM64 on many more platforms.

So the change is due to use of new automation (GitHub Actions, move to Relenv-backend instead of Tiamat, switch to using SHA-256 for better security).  Note: SHA-1 is not available on REHL 9, Ubuntu 22.04 and Fedora is about to drop it too.

All of this was explained when Salt 3006.0 was released btw.

**Comment by vitotafuni** [comment]
@dmurphy18 
so why https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/3005/ is on salt/py??

commands need to be back-compatible and running 
`bootstrap-salt.sh -P stable 3005 `
simply breaks on arm but not on amd64!

that's the problem @miguelacaro is talking about.

however as you said moving to 3006 solve the problem...

**Comment by dmurphy18** [comment]
@vitotafuni Good catch, missed it, that is a Tiamat-based package for 3005, and they used not to be in salt/py3 path, and really shouldn't be.  Have a feeling someone working on the automation got carried away when they started playing with handling of AWS S3 buckets (where the packages are kept to feed the web etc.), esp. since the Tiamat-based packages are built on GitLab.

Cannot speak to bootstrap.sh since that is another repo but I have to use **old-stable** to pick off the 3005 releases.

Here is a section from using salt-cloud to bootstrap a VM for me on AWS
```
script_args: -x python3 old-stable 3005.1
```
