### ISSUE TITLE
feature request: running local/masterless with arbitrary paths

### ISSUE THREAD

**Issue by rrauenza** [saltstack/salt#6575]
I'm working on deploying an application I'm developing.  It is in a single git repository, and it gets deployed on a single host.  I'd like to build salt files to deploy this on the machine.

The workflow I'd like to be able to use is:
- login to machine
- git checkout
- cd into repository's deploy directory, run salt against top.sls

But instead it seems I have to modify /etc/salt/... to point to my repository.. or copy the deployment code to /srv, etc., etc.

It would be handy if salt either knew I was running an arbitrary path, and sets the root to that, or if I was able to pass the root dir on the command line.

(And maybe I can already - I just haven't found out how yet!)

**Comment by techdragon** [comment]
Some of the project templates I use have grown to the point where I think it would be better if they were constructed with more powerful tools, so I'm keen to dig into this and see what can be done. Can we reopen this issue?

**Comment by rallytime** [comment]
@techdragon Certainly!

**Comment by techdragon** [comment]
@rallytime Thanks for reopening.

From a quick skim of the existing open tickets and a look at some of the code, it seems clear there is at least two parts to solving this. 

1. Invocation - Does this belong as a specific way to invoke `salt-call` or does this fit better as a new separate command line script/tool, or even a separate repo like `pepper` that will isolate unnecessary additional code in the already dense `cli.*` modules. A separate repo would also enable the use of additional dependencies without having to add them to salt's core dependencies. ( Also if it is a new separate cli tool or repo, I'd like to suggest the names "mill"/"salt-mill", or "grinder"/"salt-grinder")

2. Relative Path Issues - Its clear from the code path reading that the way `salt-call` and the other CLI commands work with respect to configuration files and directories is shared, so many of the existing relative path issues with all of the components of Salt will be blockers to getting this working in a properly portable way. 

The Plan!
- I'll start with trying to fix up enough of the relative path issues that I can write a small proof of concept script that works self contained in a directory and doesn't break when that directory is moved around.

**Comment by waynew** [comment]
Looks like it's been quite some time since there's been any activity on this. Interestingly enough, I'm pretty sure that Salt more or less already supports this in the minions. I put together an example here: 
https://github.com/waynew/salt-standalone-sample

This just uses a masterless minion setup, and only requires that `--config-dir` be set to the repo directory, and that in the `minion` file the config has `file_roots: /path/to/repo` and `file_client: local` (though that one might be optional??)

If my example isn't enough, then could we have some more thoughts/reasons why we might want to do something different/more? From what I've read _so far_ I don't think I see a pressing need to build any more functionality, and would like to go ahead and close this issue.

Anyone disagree (with some convincing reasons 😄)?
