### ISSUE TITLE
Where 3007

### ISSUE THREAD

**Issue by frebib** [saltstack/salt#65779]
According to the release schedule, it should have been out and EOL'd by now
https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-version-support-lifecycle.html

**Comment by whytewolf** [comment]
due to a lot of things going on internally with the team, during the merger, it was delayed. we are looking at releasing the RCs very soon. 

Thank you for your question. however questions like this are better served in the community locations rather than in github issues. please take this to slack or one of the other community locations.
