### ISSUE TITLE
Salt key in Accepted AND Unaccepted list.

### ISSUE THREAD

**Issue by DaveQB** [saltstack/salt#6593]
I have two keys that appear in both Accepted and Unaccepted.

The way I got into this situation was by forgetting to add a pattern to the autosign.conf and thus accumulating a few keys in unaccepted. Then adding this pattern to to autosign.conf. Next these keys were accepted but still listed under Unaccepted.

I restarted salt-master with no effect.

Not a big issue, I can deal with it myself but thought I'd report it case this is just the tip of the iceberg of a bigger problem.

Thanks.

**Comment by vielmetti** [comment]
Just ran into this issue today, with a key showing up in both the "accepted" and "unaccepted" lists. Following the instructions here to recover.

**Comment by mosuowhq** [comment]
The issue, that a key appears in both the accepted and unaccepted lists, still exits with salt version 2015.5.3. 
To address this issue, I modified the "_auth(self, load)" function in the master.py. The following code were added after "self.event.fire_event(eload, tagify(prefix='auth'))":
    if os.path.isfile(pubfn_pend): 
        os.remove(pubfn_pend)
with the modification, the keys in /etc/salt/pki/master/minions_pre are deleted after being automatically accepted and only appears in the accepted list.
Test results show that the issue can be fixed by adding the simple code. However, other potential issue may appear.

**Comment by mozgomes** [comment]
Just curious. If i stop the master service.
Then delete everything under 

> /etc/salt/pki/master/minions_pre

 
Then start the service. Will i screw anything up? I got so much unaccepted keys and want to mass remove them instead of doing a salt-key -d on every single one.

**Comment by cro** [comment]
That should work fine.

`salt-key -d` also takes globs like the `salt` command does, if you can construct a glob pattern that will cover your need.

**Comment by benediktwerner** [comment]
This was probably fixed in #40726
