### ISSUE TITLE
[DOCS] Contributer guide suggests setup using python 3.7.0 which is not supported by current salt versions

### ISSUE THREAD

**Issue by Obbi89** [saltstack/salt#65978]
**Description**
pyenv setup uses an out-of-date python version

**Suggested Fix**
replace 3.7.0 with a more current version like 3.9.0

**Type of documentation**
[Contributing](https://docs.saltproject.io/en/master/topics/development/contributing.html)

**Location or format of documentation**
https://docs.saltproject.io/en/master/topics/development/contributing.html

**Comment by terminalmage** [comment]
I had a docs change I needed to make in the same file and noticed this, so I updated it in https://github.com/saltstack/salt/pull/66051. Since that PR has been merged, this issue can be closed. I thought that including `Resolves #issue_num` would do so automatically, but I guess I should have used `Fixes #issue_num`.

**Comment by Obbi89** [comment]
Thank you. I'm gonna close this then.
