### ISSUE TITLE
[BUG] file.manage doesn't see file as symbolic link

### ISSUE THREAD

**Issue by speedytom** [saltstack/salt#66212]
**Description**
file.manage doesn't see file as symbolic link. It seems like regression from 3006.5

**Setup**
root@salt:~# dpkg -l "salt*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-================================================================
ii  salt-api       3007.0       amd64        Generic, modular network access system
ii  salt-common    3007.0       amd64        shared libraries that salt requires for all packages
ii  salt-master    3007.0       amd64        remote manager to administer servers via salt

tok-le-wildcard-key:
  file.managed:
    - name: /etc/ssl/tok-le-wildcard.key
    - source: salt:///etc/ssl/tok-le-wildcard.key
    - makedirs: True
    - user: root 
    - group: root
    - mode: 644

root@work-18-09:~# salt-call state.apply misc.ssl-tok-le-wildcard
[ERROR   ] Source file salt:///etc/ssl/tok-le-wildcard.key not found in saltenv 'base'
[ERROR   ] Source file salt:///etc/ssl/tok-le-wildcard.crt not found in saltenv 'base'
local:
----------
          ID: tok-le-wildcard-key
    Function: file.managed
        Name: /etc/ssl/tok-le-wildcard.key
      Result: False
     Comment: Source file salt:///etc/ssl/tok-le-wildcard.key not found in saltenv 'base'
     Started: 10:12:59.933144
    Duration: 20.868 ms
     Changes:   
----------

lrwxrwxrwx  1 salt salt   48 Sep 15 10:48 tok-le-wildcard.crt -> /home/salt/.acme.sh/tok.ipp.cas.cz/fullchain.cer
lrwxrwxrwx  1 salt salt   53 Sep 15 10:49 tok-le-wildcard.key -> /home/salt/.acme.sh/tok.ipp.cas.cz/tok.ipp.cas.cz.key
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
This should work without problem. It seems like regression from 3006.5.

One more mote. There is minor bug in the showed version:
root@salt:~# salt-master --version
salt-master 3006.2
root@salt:~# salt --version
salt 3007.0 (Chlorine)

root@salt:~# dpkg -S salt-master
salt-master: /etc/init.d/salt-master
salt-common: /opt/saltstack/salt/salt-master
salt-master: /lib/systemd/system/salt-master.service
salt-master: /usr/share/doc/salt-master/copyright
salt-common: /usr/share/fish/vendor_completions.d/salt-master.fish
salt-common: /opt/saltstack/salt/share/man/man1/salt-master.1
salt-master: /usr/share/man/man1/salt-master.1.gz
salt-master: /usr/share/doc/salt-master
salt-master: /usr/share/doc/salt-master/changelog.gz
salt-master: /usr/bin/salt-master

**Comment by AndersonMartins1** [comment]
The file.managed state in SaltStack does not recognize the file as a symbolic link. This issue appears to be a regression from version 3006.5.  

root@salt:~# dpkg -l "salt*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name Version Architecture Description
+++-==============-============-============-================================================================
ii salt-api 3007.0 amd64 Generic, modular network access system
ii salt-common 3007.0 amd64 shared libraries that salt requires for all packages
ii salt-master 3007.0 amd64 remote manager to administer servers via salt


State Configuration


tok-le-wildcard-key:
  file.managed:
    - name: /etc/ssl/tok-le-wildcard.key
    - source: salt:///etc/ssl/tok-le-wildcard.key
    - makedirs: True
    - user: root
    - group: root
    - mode: 644

Reproducible Steps

Run the state file using salt-call state.apply misc.ssl-tok-le-wildcard.
Expected Behavior

The file.managed state should recognize the file as a symbolic link and perform the required actions without any errors. This issue appears to be a regression from version 3006.5.

**Comment by Akm0d** [comment]
To be clear, the file path "/etc/ssl/tok-le-wildcard.key" is a symlink that points to elsewhere on your system, but salt is pointed to the symlink for file.manage?

**Comment by Akm0d** [comment]
@speedytom ^^

**Comment by speedytom** [comment]
Yes, you are right.

**Comment by Akm0d** [comment]
I could not replicate the issue on any version of salt.  Rather, this seems to be a configuration problem.

When you write:
```
- source: salt:///etc/ssl/tok-le-wildcard.key
```
Salt looks for the path relative to the saltenv root. 

To use an absolute path relative to the system root, your source should be:
```
- source: file:///etc/ssl/tok-le-wildcard.key
```
