### ISSUE TITLE
[BUG] CentOS 7. 9 port 4505 cannot be connected after salt-master upgade to 3007 

### ISSUE THREAD

**Issue by pppineapple** [saltstack/salt#66236]
**Description**
My Salt-Master has 6000+ minions in our environment. When I upgraded my salt-master to 3007 by yum repo and started Salt-master service. I noticed that a lot of minons connected to Salt-master's port 4505. That connctions are establed. But I can not telnet Salt-master host by port 4505. Such as command `telnet <salt-master-host> 4505`. So my Salt-master dose not work for any command about send job to minions. Such as `salt '*' test.ping`. It's responsed `Minion did not return. [No response]`.
I noticed  a wired thing that if my Salt-master has less then 1000 minions. It works at 3007 version.
When I roll back to 3002.5. It works very well ! Salt-master can hold 6000+ minons connection and also send job to minions very fast. Port 4505 are connected. 
Anybody has the same problem? How shold I fix it?

**Setup**
Salt-master
```
interface: xx.xx.xx.xx
user: root
gather_job_timeout: 30
timeout: 30
worker_threads: 200
auto_accetp: True
autosign_file: /xx/xx/xx/autosign.conf
```

**Comment by dmurphy18** [comment]
@pppineapple RHEL 7 and its derivatives are EOL (End Of Life) and no support any longer.  Can you try this with currently supported versions of Salt e.g. 3006.8 or 3007.1, note 3006.9 should be getting released tomorrow, on supported platforms, that is, RHEL 8 or RHEL 9 or their derivatives like Rocky Linux.

Use of telnet, is not the best way to connect to anything (since the 2000s), and ports 4505 and 4506 are used for communication between salt-masters and salt-minion, hence recommend using ssh and port 22 to connect to salt-masters and salt-minions.

With later versions of Salt, security improvement are always being made, and what worked in earlier versions may no longer function as holes found, are closed.  Using telnet on 4505 is not recommended.

**Comment by dmurphy18** [comment]
@pppineapple Closing this due to unresponsive, please feel free to reopen if more information is provided.
