### ISSUE TITLE
Installation of salt minion 3005.1 on Solaris 11.

### ISSUE THREAD

**Issue by madurani** [saltstack/salt#66869]
Installation of minion 3005.1 to Solaris 11 isn't success, because package is depend on libxevie which is obsolete:

```
pkg install -g file:///var/tmp/work/salt-3005.1_solaris11_sparc.p5p library/python/salt-minion
No updates necessary for this image.

details:
pkg install: No matching version of library/python/salt-minion can be installed:
Reject: pkg://SaltStack/library/python/salt-minion@3005.1:20221025T215519Z
Reason: All acceptable versions of 'require' dependency on x11/library/libxevie@1.0.3-11.4.0.0.1.14.0 are obsolete

# pkg list -af libxevie

NAME (PUBLISHER)                                  VERSION                    IFO

x11/library/libxevie (solaris)                    1.0.3-11.4.60.0.1.151.0    --o


```

**Comment by dmurphy18** [comment]
@madurani Sorry but closing this since Salt Project doesn't support Solaris anymore and Salt 3005.1 is end of life.  The Salt repositories are now in community support and the repo for Solaris 11 can be found here https://github.com/vmware/salt-native-minion-for-solaris-11

That repo is where this issue should be raised, and not in the current Salt repo here.
