### ISSUE TITLE
unicide error in yumpkg.py

### ISSUE THREAD

**Issue by FlorianLudwig** [saltstack/salt#6694]
it seems that entering package names that are not made out of ascii you get a error while logging an error.

    File "/usr/lib/python2.7/site-packages/salt/state.py", line 1208, in call *cdata['args']
        , **cdata['kwargs'])
    File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 361, in installed
         **kwargs)
    File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 529, in install
        log.error('Install failed: {0}'.format(e))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 38: ordinal not in range(128)

in my humble opinion it should state the actual problem.

**Comment by terminalmage** [comment]
The offending code is no longer a part of Salt, as we dropped support for the yum Python API and switched to simply wrapping yum due to numerous errors and the overall poor documentation of the yum Python API.

For this reason, and because we have not heard back in almost two years, I am closing this issue.
