### ISSUE TITLE
[BUG] Saltstack bootstrap is broken

### ISSUE THREAD

**Issue by gilgameshfreedom** [saltstack/salt#67006]
**Description**
According to the instruction https://docs.saltproject.io/salt/install-guide/en/latest/topics/bootstrap.html the following steps must be done to use bootstrap

```
$ curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
$ chmod +x bootstrap-salt.sh
$ ./bootstrap-salt.sh
```

The problem is that `curl` pulls not a bootstrap shell script, but a HTLM-page

```
$ curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
$ cat bootstrap-salt.sh                                        
<meta http-equiv="refresh" content="0; url=./bootstrap-salt.sh" />
```

**Setup**

- [x] used bootstrap to install

**Expected behavior**

The curl command pulls a bootstrap shell script instead of the HTLM page.

**Comment by tjyang** [comment]
Please see solution from  https://saltproject.io/blog/salt-bootstrap-breakage/

**Comment by ScriptAutomate** [comment]
There was a follow-up blog post on where best to download (to avoid potential rate limiting):
- https://saltproject.io/blog/salt-bootstrap-breakage-part-2/

As of today, the script is non-functional due to the new repo backend being the only one available. More details here:
- https://github.com/saltstack/salt-bootstrap/issues/2027

Closing this issue since new download location of the script is resolved, and linking the new issue above as next steps `salt-bootstrap` is taking.
