### ISSUE TITLE
Unable to create local mirror of saltstack repo, due to filelists.xml not being available

### ISSUE THREAD

**Issue by salman8328** [saltstack/salt#67032]
**Description**
Unable to create local mirror of saltstack repo, due to filelists.xml not being available

**Setup**

sync the saltstack repo using pulp and this url:
https://packages.broadcom.com/ui/repos/tree/General/saltproject-rpm

**Steps to Reproduce the behavior**
sync that rpm repo, it will fail with error:

"description": "XML file(s): filelists not found"

**Expected behavior**
local mirror created 

**Additional context**
When the repo url has been moved to public Jfrog url, this issue occured, so the steps to solve it would be to enable filelists.xml indexing in jfrog.

**Comment by ScriptAutomate** [comment]
I'm taking a look at this to see if we can get that enabled for the `rpm` repo.

In the meantime, we have alternative directions for pulling down the repos on Artifactory:
- https://docs.saltproject.io/salt/install-guide/en/latest/topics/other-install-types/air-gap-install.html

**Comment by clayoster** [comment]
@ssoto2 The repositories at repo.saltproject.io no longer exist. More details on the transition can be found here:

https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/

**Comment by Ivca50V** [comment]
Issuing the same problem when trying to mirror repo on Foreman:
[E|bac|9161b7fb] XML file(s): filelists not found (Katello::Errors::Pulp3Error)

**Comment by abdelhousni** [comment]
Hello team,
We currently use redhat satellite(foreman) for managing our rpm repositories.
When creating the repos following your instructions : https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/

I encounter the following error :  
XML file(s): filelists not found (Katello::Errors::Pulp3Error)

I found out that the reason is from the data type used returned by this file : https://packages.broadcom.com/artifactory/saltproject-rpm/repodata/repomd.xml
should be : <data type="filelists"> instead of <data type="other"> or <data type="primary">

 you will find the detailed fix from this article : https://community.theforeman.org/t/external-private-yum-repository-on-jfrog-io-not-synchronizing-in-foreman-katello/24938

Thank you in advance for the fix and for all your hard work
Best regards
Abdellatif

**Comment by MartinEmrich** [comment]
I read elsewhere that Artifactory can be configured to enable/disable creation of the filelists file. I also get an Error message on yum based OS.
Maybe Salt Project/Broadcom can turn it on?

**Comment by ssoto2** [comment]
@MartinEmrich We use Jfrog and it can be turned on, don't know if Salt has a specific reason for not turning it on but it is available in the manage repo settings of Jfrog

![Screenshot from 2024-11-06 13-11-03](https://github.com/user-attachments/assets/a78ce6d1-a019-4c6a-8a4d-76d3c624ac81)

**Comment by mmacdo02-tufts** [comment]
Hi, We also use Red Hat Satellite in our organization to mirror Salt repos so we definitely would like to have this fixed.

**Comment by ScriptAutomate** [comment]
`Enable File List Indexing` has now been enabled on the `saltproject-rpm` repository, and should work with tools that seek a `<data type="filelists">` entry in the `repomd.xml` file.

Can see the new updates here:
- `repomd.xml`: https://packages.broadcom.com/artifactory/saltproject-rpm/repodata/repomd.xml
  - Currently pointing to: `*-filelists.xml.gz`: https://packages.broadcom.com/artifactory/saltproject-rpm/repodata/6f77c6f727dea05b58e0082794a118b66088c55c-filelists.xml.gz
