### ISSUE TITLE
Preseeding Minion Key is Failing

### ISSUE THREAD

**Issue by akoumjian** [saltstack/salt#6861]
Salt versions: 0.16.3 and b2465eb40577e5ead4ef26c7efbdab83476d728e

I was attempting to test preseeding minion keys on salty-vagrant. As far as I can tell, the script is seeding everything correctly but my salt-master is rejecting the public key.

To reproduce: create a key pair. Install salt via bootstrap script, passing the "-k /dir-with-keys" and "-M" to install salt master.

Wait for minion and master to install and startup. Observe that the minion's public key is in /etc/salt/pki/master/minions/minion_id and also in /etc/salt/pki/minion/minion.pub as it should be.

Perform a diff on the two pub key files and they are identical. List the accepted keys, and you will see minion_id. However, looking in master or minion logs will show that the minion's key was rejected. Restarting the master or minion does not fix the problem.

Deleting the key and reaccepting it does work, however.

**Comment by jf** [comment]
guys, it's October 2017 already... Would somebody care to update the status of this issue? I for one bumped into some problems and *thought* that this was a problem that still existed... Except I found out in the end that it was a firewalling issue on my part, blocking communications between the preseeded minion and the salt master.

So for those guys who had issues... are you still having issues now? If not it would do folks a lot of good to close this, instead of them assuming that there really is a problem with preseeding when they see that this issue is still open. Thank you.

**Comment by ifiokjr** [comment]
Yeah, it's definitely worth closing this. I can't remember how I resolved the issue, but I've long since moved on.

**Comment by rallytime** [comment]
Yeah, I agree. If this pops up again we can either re-open or a new issue can be filed with the relevant and specific information.
