### ISSUE TITLE
Add documentation and example for pillar_dirs on master config

### ISSUE THREAD

**Issue by micahhausler** [saltstack/salt#7300]
Issue #1589 discusses using a pillar_dirs in the master config file, but I cannot find any reference for how to use this. Perhaps an example in the master config as well as documenting its use in the external pillars doc would be a solution.

**Comment by brad-alexander** [comment]
This should be reopened, the "_dirs" options are dynamic, and may automatically add new valid master options when new modular systems are added.
https://github.com/saltstack/salt/blob/bfcfcd75e8e902812b3abc4450118cd8d85fac6d/salt/loader.py#L150

**Comment by rallytime** [comment]
Thanks @brad-alexander

**Comment by rallytime** [comment]
Thanks @brad-alexander - Is this something you'd be willing to add to the documentation?

**Comment by rallytime** [comment]
Thanks @brad-alexander - Is this something you'd be willing to add to the documentation?

**Comment by rallytime** [comment]
Thanks @brad-alexander - Is this something you'd be willing to add to the documentation?

**Comment by waynew** [comment]
Okay, so I've dug into this - this does not appear to be a *config* setting but a way to load plugins into Salt.

And after grokking what Salt is doing and plugging in `saltstack loader plugins` to Google, I got this page: https://docs.saltstack.com/en/latest/topics/tutorials/packaging_modules.html

So... I'd say that this already exists? Unless we feel the need to link to it from the master/minion config pages 😕

I'll go ahead and close this issue - we can re-open if there's something that's not already addressed in the packaging_modules docs.

**Comment by cachedout** [comment]
Hi @waynew. I don't think that doc is what this issue is referring to. This specific issue  is referring to extension modules, I believe.

**Comment by gtmanfred** [comment]
The correct thing to document is the ability to drop pillar modules in `salt://_pillar`

and to sync them with `salt-run saltutil.sync_pillar` which did not exist when this issue was opened 

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.saltutil.html#salt.runners.saltutil.sync_pillar

**Comment by waynew** [comment]
@cachedout I suspect there may be confusion in this issue then, because the behavior mentioned here:

> This should be reopened, the "_dirs" options are dynamic, and may automatically add new valid master options when new modular systems are added.
> [salt/salt/loader.py](https://github.com/saltstack/salt/blob/bfcfcd75e8e902812b3abc4450118cd8d85fac6d/salt/loader.py#L150)
> 
> Line 150 in [bfcfcd7](/saltstack/salt/commit/bfcfcd75e8e902812b3abc4450118cd8d85fac6d)
> 
>  ext_type_dirs = u'{0}_dirs'.format(tag)

is definitely the behavior in the document I linked to.

But if we're talking about documenting `salt://_pillar`in a better way than https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.saltutil.html#salt.runners.saltutil.sync_pillar I'm 👍 for that.

**Comment by bVector** [comment]
It has been a long time since I left that comment and I can't recall exactly what I was getting at lol.  

I think I was trying to get at was that these options 
- are valid config options but are not documented
- are dynamic based on the 'tag' passed to `_module_dirs`

So even if pillar_dirs is documented in the salt config docs, it would quickly be out of date if a new modular system is added.  This might not be a problem big enough to solve, but making the docs dynamic would be a fix or adding a *_dirs section into the docs explaining all this would be a simple solution.
