### ISSUE TITLE
salt-ssh should allow to specify hostname/connect-user on command line (thus making roster optional)

### ISSUE THREAD

**Issue by pfalcon** [saltstack/salt#7911]
I spent half an hour looking for "connect as user" command line arg for salt-ssh, before figuring out all that "roster" thing. Please don't enforce it as required. Quite a few people would just want to do:

```
salt-ssh <arbitrary_host> --connect-user <myuser> test.ping
```

So, if host is present in roster, that should allow to override connection user, otherwise just use args as is for SSH. (Note that "--connect-user" is just an example, it's too long and would rather be shortened, and one-letter variant would be a must).

Thanks! (As additional motivation, Ansible allows that ;-) ).

**Comment by phpdave11** [comment]
salt-ssh should default to whatever user you are logged in as, rather than assuming "root". That way, you would be able to omit the username from the salt roster.

Right now I have to specify my username in the salt roster, but other members of my team who run salt-ssh commands will have to manually edit the salt roster and replace my username with their username. The private keys are already handled nicely with SSH agent forwarding -- but the username should also be "forwarded", IMO.

**Comment by basepi** [comment]
I think you're right on this, it does make sense to follow SSH's default behavior, which is to use the user that's initiating the command, rather than defaulting to root. Thanks for the update and bump on this issue.
