### ISSUE TITLE
Proper way to upgrade salt-minions / salt-master packages without losing minion connectivity

### ISSUE THREAD

**Issue by shantanub** [saltstack/salt#7997]
We ran through the right way of doing this in salt training with Seth but I think I'm still missing something. I'm not sure if this is a bug or if I've missed something. I tried to run through the upgrade the master first / use salt to upgrade the minion service steps to upgrade from v.17 to v.17.1 of salt and ended up with losing access to most of my minions.

Long story short, I need a reliable way of upgrading all of the salt-minions and salt-master packages without losing access to the minions. From what I can tell, every time I perform such an upgrade I lose access to some if not all of my minions and need to login to each host/VM and restart the salt-minion package. This is doable in test/dev where we have 30 nodes being managed but not when I move this infrastructure to prod where I have over 200 nodes to manage. I need the upgrade path not to break the remote execution framework established between minions and master.

So without further ado here's what I did:

Update the master.

```
[root@salt-master ~]# yum list updates
Loaded plugins: security 
epel                                                                                                | 3.0 kB     00:00
epel/primary_db                                                                                     | 6.2 MB     00:00
epel-testing                                                                                        | 2.9 kB     00:00
epel-testing/primary_db                                                                             | 2.2 MB     00:00
rhel-localrepo                                                                                      | 3.0 kB     00:00
rhel-localrepo/primary_db                                                                           |  26 MB     00:00
Updated Packages         
glibc.x86_64                                         2.12-1.107.el6_4.5                                      rhel-localrepo
glibc-common.x86_64                                  2.12-1.107.el6_4.5                                      rhel-localrepo
glibc-devel.x86_64                                   2.12-1.107.el6_4.5                                      rhel-localrepo
glibc-headers.x86_64                                 2.12-1.107.el6_4.5                                      rhel-localrepo
java-1.6.0-openjdk.x86_64                            1:1.6.0.0-1.65.1.11.13.el6_4                            rhel-localrepo
kernel.x86_64                                        2.6.32-358.23.2.el6                                     rhel-localrepo
kernel-firmware.noarch                               2.6.32-358.23.2.el6                                     rhel-localrepo
kernel-headers.x86_64                                2.6.32-358.23.2.el6                                     rhel-localrepo
libtar.x86_64                                        1.2.11-17.el6_4.1                                       rhel-localrepo
nscd.x86_64                                          2.12-1.107.el6_4.5                                      rhel-localrepo
perf.x86_64                                          2.6.32-358.23.2.el6                                     rhel-localrepo
salt.noarch                                          0.17.1-1.el6                                            epel-testing
salt-master.noarch                                   0.17.1-1.el6                                            epel-testing
salt-minion.noarch                                   0.17.1-1.el6                                            epel-testing
setup.noarch                                         2.8.14-20.el6_4.1                                       rhel-localrepo
tzdata.noarch                                        2013g-1.el6                                             rhel-localrepo
tzdata-java.noarch                                   2013g-1.el6                                             rhel-localrepo
You have new mail in /var/spool/mail/root
[root@salt-master ~]# yum update -y
```

I restart the master and minion on my master VM.

```
[root@salt-master ~]# service salt-master restart
Stopping salt-master daemon:                               [  OK  ]
Starting salt-master daemon:                               [  OK  ]
[root@salt-master ~]# service salt-minion restart
Stopping salt-minion daemon:                               [  OK  ]
Starting salt-minion daemon:                               [  OK  ]
```

Try to upgrade some of my test minion VMs.

```
[root@salt-master ~]# salt 'salt-minion*' pkg.upgrade
[root@salt-master ~]# salt 'salt-minion*' pkg.list_upgrades

[root@salt-master ~]# salt -v 'salt-minion*' test.ping
Executing job with jid 20131021102016190263
-------------------------------------------

salt-minion-00:
    Minion did not return
salt-minion-01:
    Minion did not return
```

I login to each minion VM and restart the salt-minion service.

```
[root@salt-minion-01 ~]# service salt-minion restart
Stopping salt-minion daemon:                               [FAILED]
Starting salt-minion daemon:                               [  OK  ]
[root@salt-minion-01 ~]# chkconfig --list | grep salt-minion
salt-minion     0:off   1:off   2:on    3:on    4:on    5:on    6:off
```

Now I can ping the VMs again.

```
[root@salt-master ~]# salt -v 'salt-minion*' test.ping
Executing job with jid 20131021102229314417
-------------------------------------------

salt-minion-01:
    True                 
salt-minion-00:
    True  
```

Versions reports:

```
[root@salt-master ~]# salt --versions-report
           Salt: 0.17.1
         Python: 2.6.6 (r266:84292, May 27 2013, 05:35:12)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 2.2.0.1
            ZMQ: 3.2.4

[root@salt-minion-00 ~]# salt-call --versions-report
           Salt: 0.17.1
         Python: 2.6.6 (r266:84292, May 27 2013, 05:35:12)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 2.2.0.1
            ZMQ: 3.2.4

[root@salt-minion-01 ~]# salt-call --versions-report
           Salt: 0.17.1
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
         Jinja2: unknown
       M2Crypto: 0.21.1
 msgpack-python: 0.1.12
   msgpack-pure: Not Installed
       pycrypto: 2.3
         PyYAML: 3.08
          PyZMQ: 2.1.9
            ZMQ: 2.2.0
```

You'll notice that the upgrade proceeded correctly. The packages were upgraded,  but the salt-minion services were not restarted as a part of the upgrade process (for both minion VMs - one is RHEL5 and the other is RHEL6). Unfortunately, I didn't think to run the upgrade packages command in verbose mode at the time. 

Do I need to find some external remote-execution method to restart all of the minions post-upgrade (mussh/omnitty, etc...)? This is probably not a bug but it's still very frustrating... I'm unlikely to upgrade again until I can figure out how to do this properly.

**Comment by andrejohansson** [comment]
The ```at``` command mentioned in this issue as a resolution for windows is deprecated. I'm running Windows Server 2012 and I'm trying to get a version similar to @equinoxefr solution using schtasks to work.

Here is my attempt:
```
schedule-start:
  cmd:
    - run
    - name: schtasks /create /sc once /tn restartsalt /tr "cmd /c net start salt-minion" /st (Get-Date).AddMinutes(1).ToString("HH:mm") /sd (Get-Date).ToString("MM/dd/yyyy")
    - shell: powershell
    - order: last
  service:
    - dead
    - name: salt-minion
    - require:
        - cmd: schedule-start
```

But using 2015.2.0rc2 this returns an error:
```
----------
          ID: schedule-start
    Function: cmd.run
        Name: schtasks /create /sc once /tn restartsalt /tr "cmd /c net start salt-minion" /st (Get-Date).AddMinutes(1).ToString("HH:mm") /sd (Get-Date).ToString("MM/dd/yyyy")
      Result: False
     Comment: Command "schtasks /create /sc once /tn restartsalt /tr "cmd /c net start salt-minion" /st (Get-Date).AddMinutes(1).ToString("HH:mm") /sd (Get-Date).ToString("MM/dd/yyyy")" run
     Started: 09:34:36.998000
    Duration: 1535.0 ms
     Changes:
              ----------
              pid:
                  3856
              retcode:
                  1
              stderr:
                  ERROR: No mapping between account names and security IDs was done.
                  (40,4):UserId:
              stdout:
```
Apparently ```schtasks``` doesn't seem to be happy when executed from the ```Local System``` account.

Does anyone have a suggestion? Maybe @equinoxefr? Did your solution work on 2012 or are you running earlier versions?

Maybe my only solution is to supply the ```/ru``` and ```/rp``` passwords and specifcy a user. But I would like to avoid that since all machines use different credentials and the are not in a domain (cloud based machines).

**Comment by dragon788** [comment]
@andrejohansson Do any of the workarounds in this fellow's repo work on 2012? https://github.com/markuskramerIgitt/LearnSalt/blob/master/learn-run-as.sls

**Comment by dragon788** [comment]
We ended up creating a batch file to uninstall and reinstall the salt minion, since simply upgrading in place had weird behaviors on 2014.7.x to newer 2014.7.x. We then schedule the batch file using the method above which with /ru "SYSTEM" works quite well. The one thing we added to the batch was backing up the minion.pem and minion.pub (could also add the minion [.conf]) so that when it talks back to the master it isn't colliding with its old key, it is reusing it.

**Comment by andrejohansson** [comment]
@dragon788 yes, I ended up doing something similar, but I havent saved the key files yet. Smart!
What I've done is the following:

1. Made a salt state that does the following:
  * Downloads the new minion and places in a temp folder
  * Downloads a scheduled task with multiple actions (xml file) to the same temp folder
  * Schedules the task (xml file) to run __once on boot__
  * Disable the minion so it doesn't autostart
  * Schedules a reboot
2. Once the computer reboots the scheduled tasks
 * Uninstalls salt-minion
 * Removes the c:\salt dir completely (we don't want leftover cache stuff or other things)
 * Installs the new minion
 * Waits 10 minutes 
 * Starts the minion

The reboot I've found necessary because even in the newest 2015.5.X releases sometimes nssm.exe won't be deleted by the uninstaller and remains active in c:\salt. This can prevent successful installs and startups later. 

The wait 10 minutes I've found necessary because sometimes the installer won't start the minion after exit.

**Comment by douardda** [comment]
under systemd systems, this upgrade of salt-minion via salt is really a pain in the neck.
On Debian jessie, not only the salt call never returns (which is not really a problem), but it le the salt-minion package half upgraded and the salt-minion stopped...
This is due to the fact the salt-minion.service file uses the default cgroup mode for the KillMode.
 
Setting this to KillMode=process helps there. I guess the salt-minion.service should be modified in this way. Meanwhile, I deploy the file  /etc/systemd/system/salt-minion.service.d/killmode.conf  with

```
[Service]
KillMode=process
```
It allows me to properly run  

```
root@pw01:/srv/salt# salt 'pw02' service.restart salt-minion 
pw02:
    True
```

**Comment by basepi** [comment]
@douardda Thanks for the update. Looks like your pull request is merged, and I'm working on merging it forward today.

**Comment by sjorge** [comment]
Having this issue too on SmartOS/Solaris.
My solution for now is also using at but I use this command:
```salt-call --local service.restart salt-minion``` this works on both SmartOS and my ubuntu test vm

**Comment by JensRantil** [comment]
Hm, this issue is labeled "documentation", but the discussions doesn't really be about documentation. Is this properly labeled?

**Comment by basepi** [comment]
This is the relevant comment: https://github.com/saltstack/salt/issues/7997#issuecomment-51981491

**Comment by sjorge** [comment]
Ideally there would be a 'reload' command instead that would properly reload everything for the salt-master/salt-minion without actually stopping and starting the process.

**Comment by cachedout** [comment]
@sjorge That would be nice but that's a pretty tall order. We'd have to refresh the opts dict everywhere and that's non-trivial.

**Comment by sjorge** [comment]
Can't the bigger brush be use? Closing the socks on the current process and forking a new copy, then existing. Since all listening sockets are close the new minion process should start fine while the old can still send a reply that all is OK to the master?

**Comment by dragon788** [comment]
The reload sounds really similar to how nginx handles config changes, it lets the sockets from the old config survive and spawns new ones with the new config until the old ones all expire.

One thing we've noticed is that upgrading a debian version forces the service restart due to how Debian derivatives handles services in general, ie "you requested this be installed so we are enabling/starting the service NOW!". We have worked around this when preseeding salt-minion on machines by using the rc-policy.d trick (I might have dyslexia'd the name) which basically prevents a service from starting during apt-get operations, though it shouldn't affect running services. This could then possibly be followed up by a salt-call --local service.restart as mentioned above to flip from old version (in memory) to new version (on disk). 

This is completely untested, I'm just going through my watched issues and seeing if I've found any new creative ways to fix them.

**Comment by basepi** [comment]
I'm wondering if we should close this in favor of #5721?

**Comment by markuskramerIgitt** [comment]
I need to update out-of-date (0.17.5) Ubuntu Minions from an up-to-date (2016.3.2) salt-master; Minion-ID must remain the same, minion key must remain the same, minion cache should remain the same.
```saltutil.update``` fails (see below)
What shall I do?
 - Install Esky on each Minion?
 - Uninstall each Minion and re-install it with pip?

Documentation at  https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.update seems not updated since 2014.
Is what mickep76 commented on Jul 7, 2014 documented somewhere else?
update_url for UNIX  is missing.
dragon788 commented on May 29, 2015 that an undocumented script is needed to retain the minion key.

Does  ```saltutil.update``` work?
If yes, what are the requirements?


```
mkramer@mgmt-bn-051:~$ sudo salt --version
salt 2016.3.2 (Boron)

mkramer@mgmt-bn-051:~$ sudo salt PC* test.versions_report
PC-LIN-01:
               Salt: 0.17.5
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
                ZMQ: 4.0.4
PC-LIN-02:
               Salt: 0.17.5
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
                ZMQ: 4.0.4
mkramer@mgmt-bn-051:~$ sudo salt PC* saltutil.update
PC-LIN-01:
    Esky not available as import
PC-LIN-02:
    Esky not available as import

```

**Comment by oliver-dungey** [comment]
The relatively new minion config option `master_tries` should help out in this area - I've recently set all my minions to a value of `-1` (unlimited retries) which seems to be really helping to keep the minions connected up to the master ... but I may be talking nonsense as I haven't had enough time to be definite about that.

**Comment by carsonoid** [comment]
I've solved this by having salt simply fork off an upgrade script that lets the minion return instantly and has the service restart in the background. The script is Ubuntu 14.04 specific but could easily be adapted.

minion-upgrade.sls
```yaml
/tmp/salt-minion-upgrade-deb.sh:
  cmd.script:
    - source: salt://salt/upgrade-minion-deb.sh
```

**minion-upgrade-deb.sh**
```bash
#!/bin/bash

# This script forks off and runs in the background so salt can continue

{
	DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confold salt-minion
	service salt-minion restart
} >>/var/log/salt/minion-upgrade.log 2>&1 &

disown
```

**Comment by Reiner030** [comment]
Just to complete the ideas:
Last week found which do a good way (with "at" or "nohup" way):
https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-daemon-using-salt

**Comment by vutny** [comment]
Speaking only about restarting Minion, I really like the solution from here: #5721 
Being nice and tiny, it works with Salt `2016.3` on most Linux distros:
```sh
salt '*' cmd.run_bg 'sleep 10; service salt-minion restart'
```

---
As for Debian 8 and Ubuntu 16 with `systemd` on board, to prevent the `salt-minion` service to be restarted automatically after the upgrade, you need to **mask** it first.
So, the "upgrade" procedure is following:

```sh
salt -C 'G@init:systemd and G@os_family:Debian' service.mask salt-minion
salt -C 'G@init:systemd and G@os_family:Debian' pkg.install salt-minion refresh=True
salt -C 'G@init:systemd and G@os_family:Debian' service.unmask salt-minion
```

There is another solution for *Upstart* and *SystemV* init -- using of `policy-rc.d` method. You need to **temporarily** deny the runlevel operations:

```sh
salt -C '( G@init:upstart or G@init:sysvinit ) and G@os_family:Debian' file.manage_file \
/usr/sbin/policy-rc.d '' '{}' '' '{}' root root '755' base '' contents=''
salt -C '( G@init:upstart or G@init:sysvinit ) and G@os_family:Debian' file.append \
/usr/sbin/policy-rc.d '!#/bin/sh' 'exit 101'
salt -C '( G@init:upstart or G@init:sysvinit ) and G@os_family:Debian' pkg.install \
salt-minion refresh=True
salt -C '( G@init:upstart or G@init:sysvinit ) and G@os_family:Debian' file.remove \
/usr/sbin/policy-rc.d
```

I've found that it's the most reliable way to get Salt Minion upgraded properly.
Now you could safely restart Minions using `nohup` method from the FAQ.

Also I've discovered that restarting Minions just with:
```sh
salt '*' service.restart salt-minion
```
works like a charm with recent Salt version from `2015.8` and `2016.3` branches even after I did the upgrade. I believe this is because of `systemd` units were patched and Salt does the trick by forking itself to run restart command while keeping connection to a Master. 

Need to do more testing, but I think using `at` or `nohup` is only required for scripting upgrade from very old versions in Salt States.

**Comment by Trouble123** [comment]
Hi, i had been trying to restart a windows minion for ages, and finally worked out a way to get it to work everytime:

salt '*' cmd.run_bg 'Restart-Service salt-minion' shell=powershell

**Comment by pavankumar2203** [comment]
Thanks @Trouble123 👍 That worked.

**Comment by vutny** [comment]
What about `saltutil.update`? Looks like it's Windows specific function.
https://docs.saltstack.com/en/latest/topics/tutorials/esky.html

And more, I see that `esky` becomes unmaintained (again?): https://github.com/cloudmatrix/esky
Anyone from Windows camp, does the thing still works?
