### ISSUE TITLE
Improve reactor sls files.

### ISSUE THREAD

**Issue by johnnoone** [saltstack/salt#8098]
Currently reactor sls files are just a big mapping, and can't take advantage on master's module, nor requisite.
Another big improvement would be to log errors when their compilations fail.

**Comment by JensRantil** [comment]
I would love to see what @CDSRV mentioned regarding `top.sls` for reactors.

**Comment by CDSRV** [comment]
https://docs.saltstack.com/en/latest/topics/reactor/#where-to-put-reactor-sls-files

it seems reasonable and consistent to supply a parameter for search paths rather than repeat the path prefixes everywhere.

**Comment by mchugh19** [comment]
Feature request is still valid

**Comment by dmurphy18** [comment]
@johnnoone Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue/feature request, which will have metrics in tracking issues.

Lot of water under the bridge this feature request was originally filed.
