### ISSUE TITLE
Support http_proxy/https_proxy for sources

### ISSUE THREAD

**Issue by otrempe** [saltstack/salt#8177]
For example, a file.managed with source pointing to a file on a HTTP location will not work if you are behind a proxy.

Same thing with a "Windows software repository" package for which the source points to an HTTP location.

Having the ability to specify http_proxy to be able to download the source would be a nice improvement.

**Comment by cmrichards** [comment]
What's the recommended way to use an http proxy with file.managed?  Has this been fixed yet?

**Comment by The-Loeki** [comment]
It's semi-fixed;
If you specify `requests_lib: True` in you minion conf (and have Python requests lib naturally), requests lib listens to the environment.

So running a minion with the environment variables http_proxy, https_proxy, ftp_proxy etc. set, requests will automagically use that.
OR if you want to override it; you can specify a environ.setenv before running the requesting state, that works too.

For now however, I came here because in 2015.8 using requests seems broken, and the Tornado client that's now the default doesn't do this :(

**Comment by porterjamesj** [comment]
@otrempe proxies were supported well in the 2014 series, so you could downgrade to 2014.7.

**Comment by otrempe** [comment]
@porterjamesj
I reported this issue almost 2 years ago. 2014.7 was not released at that time.

**Comment by porterjamesj** [comment]
oh wow sorry, I missed that, I thought this was part of the recent wave of proxy-support-is-broken-in-the-2015-release issues.

**Comment by The-Loeki** [comment]
@porterjamesj well I made it that ;) I searched the issue list before posting my own, hence the interconnection between these issues

**Comment by mrproper** [comment]
I've done a PR which has been merged which addresses some of these issues, basically you can define: proxy_host/proxy_port/proxy_username/proxy_password in the /etc/salt/minion config and the file.managed resources will use the proxy supplied

#29322

**Comment by tingvold** [comment]
As with #23617, this is not really solved (i.e. it should be refined more).
