### ISSUE TITLE
salt.states.locale not setting LANG variable

### ISSUE THREAD

**Issue by ruimarinho** [saltstack/salt#8421]
The mongodb daemon crashes when the LANG environmental variable is not set to something like `en_US.UTF-8`. On Debian Wheezy, out of the box `service mongodb start` won't work. The solution requires setting the default locale, but while salt is able to do that properly using the locale state, it is not able to pass it to the service state.

Since the `service` binary on the a default Wheezy installation execute `/etc/init.d/` scripts using $LANG, I'm kind of stuck.

What do you suggest in this situation? Thanks.

**Comment by RyPeck** [comment]
If anyone gets here by Google - see https://github.com/saltstack/salt/issues/23543#issuecomment-102448757 for a work around.

**Comment by jfindlay** [comment]
@ruimarinho, are you still having this issue?

**Comment by ruimarinho** [comment]
@jfindlay sorry, I can't add any constructive feedback at this point since I'm no longer using the package in question. @RyPeck maybe in a better position to confirm if this is still reproducible or not.

**Comment by RyPeck** [comment]
@jfindlay Let me know if there a specific branch that this is supposed to be fixed on - happy to test.

**Comment by jfindlay** [comment]
@RyPeck, the best place to test would be 2015.5.0 or 2015.5.1, whichever is easiest for you, thanks.

**Comment by webloginwu** [comment]
rsyslog_start:
 service.running:
  - name: rsyslog
I found rsyslog can not generate state file(imfile) after being started, I guess ,  salt use default  "LANG=C" to start the service, my minion's operating system default LANG is en_US.UTF-8 

i change solution
 i use   the following state with "service rsyslog start" in the run_before_starting_rsyslog.sh
     cmd.script:
    - name: salt://svn/wu/run_before_starting_rsyslog.sh
    - cwd: /tmp
    - reset_system_locale: False
then rsyslog runs fine, it  can generate state file(imfiel)  as normal because of reset_system_locale parameter

**Comment by gravyboat** [comment]
It would be great if this was fixed since people are now creating workarounds in the formulas to get around this.
