### ISSUE TITLE
Tomcat war_deployed state always re-deploys

### ISSUE THREAD

**Issue by djs52** [saltstack/salt#8604]
I use tomcat.war_deployed with a war file called "jobs.war". This provides some internal services, and gets updated periodically. I'd like highstate to re-deploy the webapp whenever the war file changes. Instead, highstate always re-deploys the webapp, leading to unnecessary outages while Tomcat reloads.

Looking at the code, I see that the file name with .war trimmed off is used as the tag when deploying (see http://tomcat.apache.org/tomcat-7.0-doc/manager-howto.html#Deploy_A_New_Application_Remotely). In the state function, the tag reported by list (if any) is compared with the filename in the state, and if it differs, the webapp is re-deployed.

This only works well if the version is recorded in the filename and is a complete record of the version. It would be good to document this assumption.

As an alternative, it would be nice to be able to use the md5 of the .war file as the tag, since this would quickly identify whether the .war had changed. This should probably be an option, to avoid breaking existing installations.

**Comment by thor** [comment]
I came across this in my journeys, and as far as I can tell the issue regarding always redeploying when the version is the same has been fixed by #12889 and commit cbb0624031a69a6618b26da26a1218af0069ae10.

Could the issue title and description perhaps be edited -- or just create a new one -- to specify redeployment on changed hashes to the WAR-files? 👍
