### ISSUE TITLE
salt-ssh with password (without pubkey auth) doesn't work

### ISSUE THREAD

**Issue by pniederw** [saltstack/salt#8723]
I'm trying to use `salt-ssh` to bootstrap a fresh machine (getting a minion installed). `user` and `passwd` are set up correctly in the roster file. However, I nevertheless get:

```
[DEBUG   ] STDERR xxx.yyy.zzz
Permission denied (publickey,password).
```

Debug output shows that roster is rendered correctly. Other than that, there is nothing of interest in the debug output. The user is `root`, so I don't think this is the `/etc` issue mentioned in https://github.com/saltstack/salt/issues/7531. Logging in via `ssh` (using the same credentials) works fine.

Another, less critical problem is that `salt-ssh` hangs forever after logging the message above (see https://github.com/saltstack/salt/issues/8262).

I'm able to use `salt-ssh` with other machines which already have pubkey authentication set up.

Ubuntu 12.04, Salt 0.17.2

**Comment by dzwicker** [comment]
ping

**Comment by ichilton** [comment]
ping

**Comment by MKLeb** [comment]
@Ch3LL assigning since this is salt-ssh.

**Comment by dwoz** [comment]
@pniederw This issue is very old and never got any traction however salt-ssh has had tons of improvements since this issue was opened. If this is still an issue in currently a [supported version](https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-version-support-lifecycle.html), please open a new issue.

**Comment by OrangeDog** [comment]
I can confirm this is still an issue. As did @ichilton last year.
