### ISSUE TITLE
[salt.cloud] Add an option to not auto-generate minion keys

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#8746]
Refs: https://groups.google.com/forum/#!topic/salt-users/LN_6TxknsDo

This is important for when salt-cloud is not being run on the same machine as the master. Otherwise, salt-cloud will try to write out the public key that it's generated to /etc/salt/pki/, which it may not have access to, or which may not even exist.

Tagging @pwaller.

**Comment by Maudite** [comment]
Has there been any progress on this?  I think this is the fix for our problem, or perhaps we are missing another config in salt-cloud.  We are building on a MoM that has salt-cloud in it, but having the newly build server attach to one of many syndic's below.  As of now, salt-cloud will generate a key and add it to the approved minions on itself.  We would prefer to not have it generate these keys on itself, and we will have our scripts approve the minions on the Syndic.

Alternatively, if salt-cloud can handle key generation on the syndic during the build, as well as key cleanup during machine deletion, that would be ideal.
