### ISSUE TITLE
Feature Request : Support Glob pattern in file.absent state

### ISSUE THREAD

**Issue by JeremieCharest** [saltstack/salt#9183]
The file.absent state (and some others) need an absolute path to work. It will be nice if they can support glob or regex patterns.

As a side note; the file module contains a lot more interesting stuff than is state counterpart. Do you have plan to expose more of these methods in the file state?

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Comment by blhsing** [comment]
My team was in need of this exact same feature so I went ahead to implement it and am now seeking to push it into the develop branch as part of a possible future release.

The way I implemented it is with a decorator that wraps any existing function in states/file.py and makes it accept an addition keyword argument of _resolve_glob_ such that when it is set True, the decorator will treat the given file name as a glob pattern and calls the wrapped function for each file that matches the glob pattern, and for the returning dict, the _result_ will only be True if every call to the wrapped function returns _result_ as True, and _changes_, _pchanges_ and _comment_ will all be made into dicts indexed by matching file names, with values set to those of the corresponding values returned by the individual calls to the wrapped function, so that the changes and comments for each matching file can be individually tracked in case they're different. And if _resolve_glob_ is set False or if no file is found, the decorator will simply call the wrapped function directly for its original behavior.

Let me know if I can go forward with pushing my changes. Thanks.

**Comment by waynew** [comment]
Looks like a couple of PRs failed to actually make their way to completion, I'm going to reopen this issue, since it looks like the functionality is still absent... from file.absent :trollface:

**Comment by waynew** [comment]
bad bot!

**Comment by heini** [comment]
BTW: As of 2019.2.0, there's `file.tidied`, which may do what you want. Was inspired by Puppet's `tidy`.

**Comment by heini** [comment]
Ping.

**Comment by sharkbruhaha** [comment]
Can we please get globbing/regex enabled for this already?

**Comment by dmurphy18** [comment]
@JeremieCharest Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue/feature request, please open a new issue, which will have metrics in tracking issues.

Would be interested in the PR you have, but it would need to be rebased against the current master branch to ensure up to date. It was also need tests to exercise the code changes, no PR's are accepted without tests, using pytest.

If you are no longer interested in this functionality, perhaps @sharkbruhaha you can open a feature request for the functionality against the current master branch.  That is, if  file.tidied does not satisfy the need.
