### ISSUE TITLE
Minion should refresh environment variables

### ISSUE THREAD

**Issue by bkeroack** [saltstack/salt#9876]
On Windows (and apparently Linux), the minion never refreshes any environment variables (such as PATH). So if an environment variables changes (for example, after software installation) the only way to pick up the change is to restart the salt-minion.

This should be fixed to refresh environment variables on the minion prior to each salt command.

**Comment by ghostsquad** [comment]
@gtmacdonald - a workaround - restart the minion after states that update the environment take place, but before the calls to those tools happen. There's some problems with that, like concurrent jobs, and preventing child jobs from terminating prematurely, etc.

**Comment by bkeroackdsc** [comment]
@ghostsquad Not a great workaround because (IIRC), restarting the minion either causes the state run to fail or causes it to hang indefinitely.

**Comment by ghostsquad** [comment]
@bkeroack - what version of salt?

**Comment by famousgarkin** [comment]
+1

**Comment by m03** [comment]
@famousgarkin, To avoid restarting the minion, you could use the environ.setenv state with update_minion set to True in order to propagate the change to the current running minion. As an example for adding Git to the Windows System Path:

```
{% set git_dir = 'C:\Program Files\Git\cmd' %}
{% set env_path = salt['environ.get']('PATH') %}
{% set env_path = env_path ~ ';' ~ git_dir %}

win-path-exists-git:
  win_path.exists:
    - name: {{ git_dir }}

environ-setenv-path-git:
  environ.setenv:
    - name: PATH
    - value: {{ env_path }}
    - update_minion: True
    - onchanges:
      - win_path: win-path-exists-git
```

**Comment by are-prabhu** [comment]
@m03 It work with root $PATH, Im still experiencing this issue with non-root user do we have any fix or workaround

**Comment by damon-atkins** [comment]
Only way I can think of doing this is to add `path` to the minion configuration files. Then the minion checks minion configuration files for changes (time stamp) it reloads the configuration file settings.

See also #32806

**Comment by kedare** [comment]
I confirm this is required on Windows...
Typically when I bootstrap my systems with SaltStack I need to restart it at least twice because it doesn't get the new PATH variable, for example first after installing chocolatey, then after installing git using chocolatey. because they each install in different path and update the PATH variables that salt-minion doesn't see until restarting

**Comment by damon-atkins** [comment]
@kedare See https://support.microsoft.com/en-us/help/104011/how-to-propagate-environment-variables-to-the-system  or setx should do the same thing ( you could use setx afterwords to set any variable even one which does not matter).

**Comment by basepi** [comment]
@saltstack/team-triage

**Comment by nils-ballmann** [comment]
Chocolatey has the command [`refreshenv`](https://github.com/chocolatey/chocolatey/blob/master/src/redirects/RefreshEnv.cmd) which (at least on Windows) does an environment refresh for `pwsh` and `cmd.exe`. Maybe this a good starting point?

**Comment by xxsim3lu** [comment]
For Windows minion, I created a custom module as a workaround to update the minion `PATH` environment variables.

Here's the code snippet:

```python
from __future__ import absolute_import
import logging
import salt.utils.platform
import re

log = logging.getLogger(__name__)

__virtualname__ = 'myenviron'

def __virtual__():
  if salt.utils.platform.is_windows():
    return __virtualname__

def refresh():
  ret = {}
  # ====== Get the environment from registry ====== 
  cmd = 'reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment"'
  res = __salt__['cmd.run'](cmd=cmd)
  tmp = res.splitlines()
  environ = {}
  for item in tmp:
    val = item.strip().split('    ')
    if len(val) == 3:
      environ.update({val[0].strip().upper():val[2].strip()})
  
  # ====== Resolve the environment values and replace them ======
  # ====== e.g. %systemroot% to 'C:\Windows' ======
  for key, value in environ.items():
    matches = re.findall(r'%(.+?)%', value)
    match = set([i.upper() for i in matches])
    for item in match:
      a = environ.get(item)
      if not a:
        a = __salt__['environ.get'](item)
      
      if a:
        redata = re.compile(re.escape('%{}%'.format(item)), re.IGNORECASE)
        environ[key] = redata.sub(a, value)
  
  # ====== Only set the PATH environment ====== 
  setenviron = {'PATH':environ.get('PATH')}
  ret = __salt__['environ.setenv'](environ=setenviron,update_minion=True)
  return ret
```

With this custom module, after installation of Windows packages that changes the `PATH` variables, by running `sudo salt -G 'os:Windows' myenviron.refresh`;
I am able to run command with `cmd.run` such as `cmd.run 'java -version'` from salt master.

Note: Windows package is installed with SaltStack Windows package manager instead of Chocolatey.

**Comment by jayvdb** [comment]
Im not sure if this will help salt, but there is a need for Chocolatey to have a sh-compatible refreshenv .  See https://github.com/chocolatey/choco/issues/1851 .

**Comment by muddman** [comment]
@xxsim3lu - Thanks for providing your module!!  Why doesn't it work when installing git with chocolatey?

I need to get `git.latest` working on a Windows Server 2019 masterless minion (2019.2.2) and, as `git` is a prerequisite to get the SaltStack Windows package manager to work (`winrepo.update_git_repos` and `pkg.refresh_db`), that solution is a moot point for me when bootstrapping an ec2.  It's also causes issues with test-kitchen and other CI/CD pipelines.

The Chocolatey git install does add `C:\Program Files\Git\cmd` to the `PATH` so I don't understand why it doesn't work.

Thanks!!

```
local:
  Name: chocolatey.bootstrap - Function: module.run - Result: Clean Started: - 15:06:01.310000 Duration: 10936.0 ms
----------
          ID: chocolatey.installed.git
    Function: chocolatey.installed
        Name: git
      Result: True
     Comment:
     Started: 15:06:12.246000
    Duration: 39008.0 ms
     Changes:
              ----------
              git:
                  ----------
                  new:
                      - 2.24.0
                  old:
              git.install:
                  ----------
                  new:
                      - 2.24.0
                  old:
----------
          ID: myenviron.refresh
    Function: module.run
      Result: True
     Comment: myenviron.refresh: Success
     Started: 15:06:51.442000
    Duration: 63.0 ms
     Changes:
              ----------
              myenviron.refresh:
                  ----------
                  PATH:
                      C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\salt;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd
----------
          ID: test-github-repo
    Function: git.latest
        Name: https://github.com/rtyley/small-test-repo.git
      Result: False
     Comment: State 'git.latest' was not found in SLS 'test-github-repo'
              Reason: 'git' __virtual__ returned False
     Changes:

Summary for local
------------
Succeeded: 3 (changed=2)
Failed:    1
```

**Comment by onnodb** [comment]
> For Windows minion, I created a custom module as a workaround to update the minion `PATH` environment variables.

For me, the custom module didn't quite work (Windows minion, Salt 2019.2.2 PY3). My use case is installing a package and then calling one of its executables, within the same job run. So I'd like to install program X, add X's directory to the `PATH`, and then call it using the `cmd.run` state:

```yaml
Install program X:
  pkg.installed:
    - name: X
    - version: 1.0
  win.path.exists:
    - name: 'C:\Program Files\X'
  module.run:
    - name: win_minion_env.refresh    # xxsim3lu's custom module

Run program X:
  cmd.run:
    - name: 'x'
```

What I noticed, is that xxsim3lu's module only works if I run the highstate *twice*. So, somehow, the changes to the environment do not get propagated to the process that's applying the highstate, but only to the next job process?

After some digging in the code of `salt.modules.cmdmod`, I noticed that its `_run` method [pulls the environment from `nt.environ`](https://github.com/saltstack/salt/blob/master/salt/modules/cmdmod.py#L585-L586). So we can amend xxsim3lu's code with a few extra lines, which do seem to make things work:

```py
def refresh():
    # ...

    # Only set the PATH environment
    setenviron = {'PATH': environ.get('PATH')}
    ret = __salt__['environ.setenv'](environ=setenviron, update_minion=True)

    # NEW LINES:
    import nt
    for k, v in setenviron.items():
        nt.environ[k] = v
    # END OF NEW LINES

    return ret
```

Note that, due to `cmdmod`'s curious use of `nt.environ` instead of `os.environ`, I really need to use `nt.environ` in the code above to make it work.

More generally, I'm puzzled by how difficult it is to get environment changes propagated. Maybe it is a Windows-specific issue, but even so, it's been incredibly frustrating to get this to work. (The obvious `environ.setenv` with `update_minion=True` doesn't work on a Windows minion.)

**Comment by muddman** [comment]
I agree completely -- it's way too difficult to get this working.  I don't think it's a windows thing, I think it's a lack of consistency, documentation and examples with saltstack.

**Comment by zbarr** [comment]
Unmark as stale - running into this issue right now.

**Comment by mklessen** [comment]
I am also running into an issue with this.  Essentially all I want is to get the windows environment variable setup permanent which can be done using either setx or the environ.setenv state with permanent equal to HKLM.  I can get it to update the windows registry, but the environment variable is not available in any windows processes until I either reboot the system (not ideal) or manually go into the set environment variable GUI in windows and save (defeats the purpose of using these commands to automate the update).  Basically when I do the installation and then run a program (manually) depending on that env variable I want that program to work (without reboot).

**Comment by bartvdbraak** [comment]
Has there been a more official way to get this working correctly in the meantime?
