### ISSUE TITLE
Improve the "flow" of Salt documentation

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#9912]
Many of the Salt docs are "dead-ends". Meaning you land on a page that explains something and there's rarely links to deeper explanations or related topics. When there are links they are typically embedded in the text and not friendly to skimming.

Here is an example. Say you land on the main States documentation <http://docs.saltstack.com/ref/states/>. How do you get from that main page to any of the sub-pages (and there are many)?

For example, that main page has a section on the top file but no link to this page:
http://docs.saltstack.com/ref/states/top.html

I have no idea how to get to this page without going through the Full Table of Contents:
http://docs.saltstack.com/ref/states/vars.html

I think a big part this problem was (my) decision to have a monolithic, stand-alone table of contents (``contents.rst``). Although that makes it easy to globally reorder the entire documentation it avoids smaller section-local table of contents. There's probably a good middle-ground; let's find it.

**Comment by jacobhammons** [comment]
There have been many changes since this was opened to address the flow of the documentation, I think with the full TOC displaying in the right navigation and the TOC reorganization in 2016.3.0 this is mostly solved. I'm going to close this with the recommendation that new issues be opened if there are still issues with flow.
